### PR TITLE
fix(android): Replace deprecated APIs for Display, Size, Metrics

### LINKED ISSUE #9586: chore(android): getDefaultDisplay() and getSize() deprecated in Android SDK 30
The functions getDefaultDisplay() and getSize() have been deprecated for a while,

https://github.com/keymanapp/keyman/blob/31fd6ea42afef1dddd7d883fc31c5086fe9ae9b2/android/Samples/KMSample2/app/src/main/java/com/keyman/kmsample2/SystemKeyboard.java#L181

WindowMetrics seems to be new to 30, and it looks like the deprecation may have happened in 13, so maybe I need an intermediate form to clear the deprecation warning. I'm a bit nervous mucking around in here, but I want to update it in my app. Can someone confirm that this is the code I want in my SystemKeyboard.:

```
if (Build.VERSION.SDK_INT >= 30) {
            WindowMetrics windowMetrics = wm.getCurrentWindowMetrics();
            width = windowMetrics.getBounds().width();
            height = windowMetrics.getBounds().height();
        } else {
            Display display = wm.getDefaultDisplay();
            if(display == null) return;
            display.getSize(size);
            width = size.x;
            height = size.y;
        }
```
LAter, I have: 
```
outInsets.touchableRegion.set(0, outInsets.contentTopInsets, width, height);
```

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #9586

Android API 30 deprecated several calls used to determine Window Display, Size, and Metrics. This refactors the calls to KMManager to handle the different API calls.

### Setup
* These tests should run the PR builds on an Android Device/emulator of the specified API level to test each side of API 30
  * GROUP_API_28: Android 9.0 Pie
  * GROUP_API_34: Android 14.0 UpsideDown Cake

**Tests**
**TEST_KEYMAN** - Verifies orientation and keyboard height for Keyman app
1. Install Keyman for Android with the device in Portrait orientation
2. From "Get Started", enable Keyman as the default system keyboard. 
3. Dismiss "Get Started"
4. Note the current keyboard height.
5. From Keyman Settings --> Adjust keyboard height
6. From "Adjust keyboard height" menu, adjust the keyboard height for both portrait and landscape orientation.
7. From the nav bar, hit back arrow to return to the Keyman app
8. Verify the keyboard height matches what was set from the "adjust keyboard height" menu for both
  * Portrait orientation
  * Landscape orientation
9. Launch Chrome browser and select a text area
10. With Keyman selected as the system keyboard, verify the system keyboard height matches what was set from the "adjust keyboard height" menu for both
  * Portrait orientation
  * Landscape orientation
 
**TEST_FIRSTVOICES** - Verifies orientation and keyboard height for FirstVoices app
1. Install FirstVoices for Android with the device in Portrait orientation
2. From the FV setup menu, install a keyboard (BC Coast --> SENCOTEN) and enable FirstVoices as the default system keyboard
3. Launch Chrome browser and select a text area
4. With FirstVoices selected as the system keyboard, verify the system keyboard appears
5. Verify the keyboard outputs:
  * Regular key press
  * longpress key
  * suggestion from the suggestion banner (if  fv_sencoten is selected and installed dictionary)

### CODE REVIEW

**Comment by dinakaranr** [comment]
# Test Results

### GROUP_API_28: Android 9.0 Pie

* **TEST_KEYMAN (PASSED):** I tested this issue with the attached "Keyman 18.0.35-alpha-test-11436" build on an Android 9.0(emulator) environment: Here is my observation.
- Installed the "Keyman 18.0.35.apk" file and gave all permissions to the application.
- Checked the "Enable Keyman as system-wide keyboard" and set the keyboard as the default keyboard box on the settings page.

- **On portrait view:** Change the keyboard height by clicking the three-dot menu/Keyman Settings/Adjust keyboard height.
- Navigate back to the Keyman app. Here, the keyboard height appeared(increased) in the modified height and the key function works as well.
Open the Chrome browser, and then enter some text in the address bar and Google search box. Here, keyboard height appeared(increased) in the modified height

- **On landscape view:** Change the keyboard height by clicking the three-dot menu/Keyman Settings/Adjust keyboard height.
- Navigate back to the Keyman app. Here, the keyboard height appeared(increased) in the modified height and key function works as well.
Open the Chrome browser, and then enter some text in the address bar and Google search box.
Here, keyboard height appeared(increased) in the modified height.

* **TEST_FIRSTVOICES (PASSED):** 
I tested this issue with the attached "firstvoices-18.0.35-alpha-test-11436" build on an Android 9.0(emulator) environment: Here is my observation.
- Installed the "firstvoices-18.0.35.apk" file and gave all permissions to the application.
- Checked the "Enable FirstVoices" and then checked the "Choose FirstVoices as current Input method" on the setup dialog.
- Installed a keyboard (BC Coast --> SENCOTEN)(installed the online dictionary) by clicking the "Select Keyboards" button.
- Open the Chrome browser, and then enter some text in the address bar and Google search box.
Here, the FirstVoices keyboard appeared and the key works as well. 
The subkey menu list appeared after the long press key.
Suggested words appeared on the banner when typing a word.

### GROUP_API_34: Android 14.0 UpsideDown Cake
* **TEST_KEYMAN (FAILED):** 
I tested this issue with the attached "Keyman 18.0.35-alpha-test-11436" build on an Android 14(physical device): Here is my observation.
I have followed the steps that mentioned in the "Android 9.0 Pie" here. keyboard height appeared(increased) in the modified height and key function works as well. 

On the Chrome browser: the keyboard disappeared when moving portrait to landscape view. the keyboard appeared when clicking in the search box.
Please refer to the screenshot below. Hence, I failed this scenario.
https://github.com/keymanapp/keyman/assets/19683059/48401aa3-5e82-472e-aaa5-a38d0dd16f26

* **TEST_FIRSTVOICES (PASSED):** 
I tested this issue with the attached "firstvoices-18.0.35-alpha-test-11436" build on an Android 14(physical device): Here is my observation.
I have followed the steps that mentioned in the "Android 9.0 Pie" here. keyboard height appeared(increased) in the modified height and the key function works as well. 
The keyboard output is given the subkey after pressing long-press. The suggested word appeared on the banner. Hence, It works well.

**Comment by darcywong00** [comment]
> On the Chrome browser: the keyboard disappeared when moving portrait to landscape view. the keyboard appeared when clicking in the search box.
Please refer to the screenshot below. Hence, I failed this scenario.

@dinakaranr - I retested on emulator and could reproduce what you saw. However, I think that's just the behavior on google.com when you are on the search bar but don't have anything.
On my Android 13 device, the Google Gboard and Samsung keyboards also disappear when rotating the device. And I see this on Keyman 17.0.325 stable.

@keymanapp-test-bot retest GROUP_API_34 TEST_KEYMAN

**Comment by dinakaranr** [comment]
# Test Results

### GROUP_API_34: Android 14.0 UpsideDown Cake

* **TEST_KEYMAN (PASSED):** I retested this issue in the "Keyman 17.0.325 stable" build on an Android 14 (physical device): Here is my observation.
I retested this issue in the Firefox browser for Google.com. The search box works correctly when switching from portrait to landscape view on a mobile device. It seems that Chrome browser behaviour is intended as of now. Hence, I passed this test. Thank you

File: android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java [hunk 1]
```diff
@@ -218,9 +218,7 @@ public void onComputeInsets(InputMethodService.Insets outInsets) {
     super.onComputeInsets(outInsets);
 
     // We should extend the touchable region so that Keyman sub keys menu can receive touch events outside the keyboard frame
-    WindowManager wm = (WindowManager) getSystemService(Context.WINDOW_SERVICE);
-    Point size = new Point(0, 0);
-    wm.getDefaultDisplay().getSize(size);
+    Point size = KMManager.getWindowSize(getApplicationContext());
```
Comment (mcdurdin) [inline android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java:221]: These new API endpoints need to be documented

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java [hunk 2]
```diff
@@ -2052,6 +2069,34 @@ public static void applyKeyboardHeight(Context context, int height) {
...
+      WindowMetrics windowMetrics = wm.getCurrentWindowMetrics();
+      return new Point(
+        windowMetrics.getBounds().width(),
+        windowMetrics.getBounds().height());
+    }
+
+    // Deprecated in API 30
+    Point size = new Point(0, 0);
+    wm.getDefaultDisplay().getSize(size);
+    return size;
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2091]: It's good programming practice to make the default path the main path in the code, so this condition should be inverted:

```suggestion
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
      // Deprecated in API 30
      Point size = new Point(0, 0);
      wm.getDefaultDisplay().getSize(size);
      return size;
    }
    
    WindowMetrics windowMetrics = wm.getCurrentWindowMetrics();
    return new Point(
      windowMetrics.getBounds().width(),
      windowMetrics.getBounds().height());    
```

**Review by mcdurdin — APPROVED** [review]

File: android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java (hunk 1 above)
Comment (darcywong00) [reply android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java:221]: will do on help.keyman

Comment (darcywong00) [reply android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java:221]: on keymanapp/help.keyman.com#1270

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.38-alpha](https://keyman.com/downloads/releases/alpha/18.0.38)
