### PR TITLE
fix(web): interactions from layer-shifting during gesture-event processing 🐵

### LINKED ISSUE #7173: bug(web): Rapid typing on first caps letter sometimes gives TWo cap letters (touch) 🐵
**Describe the bug**

Repro: Press Shift, type two letters very rapidly. They will both get capitalized. (Two thumb typing)

Per @jahorton:
* [JH] Does repro on iOS.
* [JH] I suspect it’s due to how the Web OSK operates - for this scenario, the user does press both shift-layer keys before the display-layer is updated.

**Screenshots**

https://user-images.githubusercontent.com/4498365/187534413-92cf5c92-5c95-40bb-b226-e85eef21b61c.mp4

---

**Keyman for Windows/macOS/Linux/iPhone/iPad/Android:**
 - Device:             Samsung A90 5G 
 - OS:                 Android 12 
 - Keyman version:     15.0.269-stable

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #7173.  (Finally!)

One long-running feature of KeymanWeb's key input processing is that if a second tap starts before a first tap finishes, we automatically complete the first tap preemptively.  This is all well-and-good for most scenarios, but there's a fun caveat to be considered - what if that first tap's key triggers a layer shift.  

This was the crux of #7173, the TWo caps problem:  because the second touch started on the original layer, the resulting key was determined to _be_ from the original layer - and we had nothing built-in to adjust for this.

By waiting until the first tap fully completes processing - including the layer shift - before starting the gesture-model for the second tap, we can ensure that the second tap's key lookups are performed against the correct layer.

While this fix, as is, does ensure that the second tap acts properly for basic text output... there are still a few lingering complications to resolve - key previews / key highlighting, in particular.  It's definitely possible to fix, but I have... reasons to push that off into a follow-up PR.

@keymanapp-test-bot skip

User testing will be specified on the immediate followup, #9803.

----

I have the rough outline for a unit test to be written, but I believe it must be triaged to later in order to prioritize feature implementation for parts not yet handled.  Thus, I've created the issue #9834 to preserve that "rough outline" for future implementation.

### CODE REVIEW

File: common/web/gesture-recognizer/src/engine/headless/gestures/matchers/gestureMatcher.ts [hunk 1]
```diff
@@ -244,6 +248,15 @@ export class GestureMatcher<Type> implements PredecessorMatch<Type> {
...
       const contactSpec = this.model.contacts[i];
 
+      /* Future TODO:
+       * This should probably include "committing" the state token and items used by the subview,
+       * should they differ from the base source's original values.
+       *
+       * That said, this is only a 'polish' task, as we aren't actually relying on the base source
+       * once we've started identifying gestures.  It'll likely only matter if external users
+       * desire to utilize the recognizer.
+       */
```
Comment (jahorton) [inline common/web/gesture-recognizer/src/engine/headless/gestures/matchers/gestureMatcher.ts:258]: Note:  After #9803... this would mostly apply to _multitaps_; we may want to reverse the layer-write mechanism.

That said... I'm almost certain that we have no _need_ to do so; it should be a low-priority task as I don't think I'll need the corrected version for multitap handling.

**Review by mcdurdin — APPROVED** [review]

File: web/src/engine/osk/src/keyboard-layout/oskLayerGroup.ts [hunk 2]
```diff
@@ -75,30 +107,41 @@ export default class OSKLayerGroup {
...
 
-    try {
-      return this.nearestKey(coord, layer);
-    } finally {
-      if(layer != priorLayer) {
+    /* As soon as control returns to the JS microtask queue, restore the original layer.
+     * We want to avoid doing it sooner in case another lookup occurs before the standard
+     * async reflow, as that could trigger expensive "layout thrashing" effects.
+     *
+     * In the case that a gesture-source's path needs to be remapped do a different layer,
```
Comment (ermshiperete) [inline web/src/engine/osk/src/keyboard-layout/oskLayerGroup.ts:127]: Should the "do" be a "to" ?

```suggestion
     * In the case that a gesture-source's path needs to be remapped to a different layer,
```
