### PR TITLE
fix(android): Fix insets for in-app vs system keyboard 🪟

### LINKED ISSUE #14579: bug(android): A blank space appeared above the three buttons navigation
### Describe the bug

A blank space appeared above the three buttons navigation.

### Reproduce the bug

Steps to reproduce:

1. Installed the "Keyman-19.0.103-alpha.apk" file. Open the Keyman app.
2. On "Get Started": Checked the "Enable Keyman as system-wide keyboard" and set the "keyboard as the default keyboard" box.
3. Installed the arabic keyboard.
4. Open the chrome browser.
5. Click in the textarea or search box
6. Actual Results: OSK appeared but the blank space appeared above the "3 dots navigation"
Please refer to the screenshot below

### Expected behavior

_No response_

### Related issues

_No response_

### Keyman apps

- [x] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

19.0.103-alpha

### Operating system

android 14

### Device

samsung a23

### Target application

_No response_

### Browser

Chrome

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darcywong00**
fixes #14579 which was a regression introduced resolving the Android edge to edge layouts in #14248

This PR incorporates the pattern of fixes in AlphaTiles/AlphaTiles#237
specifically https://github.com/AlphaTiles/AlphaTiles/pull/237/files#diff-ffa9782556981f30f50417410a12d591b1659c2b19873327147a9330bbc1982e changing from `setLayoutParams()` to `setPadding()`

To keep the in-app keyboard from being obscured by the bottom navigation bar, I still needed to keep the `applyInsetsToKeyboard()` call. 

## User Testing
**Setup** - Install the PR build of Keyman for Android on an Android emulator/device of Android API 34
From the Keyman "Get Started" menu, set Keyman as the default system keyboard

* **TEST_NO_BLANK_SPACE** - Verifies no blank space between the bottom navigation bar and OSK (as reported in the issue)
1. Open the Keyman app
2. On "Get Started": Checked the "Enable Keyman as system-wide keyboard" and set the "keyboard as the default keyboard" box.
3. Installed the arabic keyboard.
4. Open the chrome browser.
5. Click in the textarea or search box
6. Observer the OSK appears, and verify there's **no** blank space between the OSK and bottom navigation bar

* **TEST_INAPP_KEYBOARD** - Verifies in-app keyboard is not covered by system insets (status bar, camera notch, navigation bar)
1. Open the Keyman app with the device in portrait orientation. Dismiss the "Get Started" menu 
2. Verify the in-app keyboard is not covered by any of the system insets 
3. Verify the keyboard keys and suggestion banner function
4. Rotate the device to landscape orientation
5. Verify the in-app keyboard is not covered by any of the system insets
6. Verify the keyboard keys and suggestion banner function

* **TEST_SYSTEM_KEYBOARD** - Verifies system keyboard is not covered by system insets (status bar, camera notch, navigation bar)
1. With the device in portrait orientation, launch Chrome and select text area to type. 
2. Select Keyman as the system keyboard if not already selected.
3. Verify the Keyman system keyboard is not covered by any of the system insets
4. Verify the keyboard keys and suggestion banner function
5. Rotate the device to landscape orientation
6. Verify the Keyman system keyboard is not covered by any of the system insets
7. Verify the keyboard keys and suggestion banner function

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java [hunk 1]
```diff
@@ -718,12 +718,7 @@ public static RelativeLayout.LayoutParams getKeyboardLayoutParams() {
    * @param bottom int padding to account for navigation bar on bottom of screen
    */
   public static void applyInsetsToKeyboard(int left, int right, int bottom) {
-    // System keyboard
-    if (SystemKeyboard != null) {
-      applyInsetsPaddingToKeyboardView(SystemKeyboard, left, right, bottom);
-    }
-
-    // In-App Keyboard
+    // Only applies to In-App keyboard
```
Comment (jahorton) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java]: Would it be worth adding a reference to this PR / its issue as part of this comment?

**Review by jahorton — APPROVED** [review]

**Comment by dinakaranr** [comment]
# Test Results
I tested this PR in the "Keyman-19.0.107-alpha-test-14619" build on Pixel 7a API 34(Emulator),  Android 14(Samsung A23). Here I am sharing my observation.

* **TEST_NO_BLANK_SPACE (Passed):** 
1. Open the Keyman app
2. On "Get Started": Checked the "Enable Keyman as system-wide keyboard" and set the "keyboard as the default keyboard" box.
3. Installed the Arabic keyboard.
4. Open the chrome browser.
5. Click in the textarea or search box(or editpad.org online editor)
6. Observer the OSK appears.
7. Verified there's no blank space between the OSK and bottom navigation bar.
It works well.

* **TEST_INAPP_KEYBOARD (Passed):** 
1. Open the Keyman app with the device in portrait orientation. 
2. Dismiss the "Get Started" menu
3. Verified the in-app keyboard is not covered by any of the system insets
4. Verified the keyboard keys and suggestion banner function
5. Rotate the device from portrait to landscape orientation
6. Verified the in-app keyboard is not covered by any of the system insets
7. Verified the keyboard keys and suggestion banner function.
It works well.

* **TEST_SYSTEM_KEYBOARD (Passed):** 
1. Open the Keyman app.
2. The mobile device in portrait orientation.
3. Launch Chrome browser.
4. Select text area to type.(or editpad.org online editor)
5. Select Keyman as the system keyboard if not already selected.
6. Verified the Keyman system keyboard is not covered by any of the system insets.
7. Verified the keyboard keys and suggestion banner function.
8. Rotate the device from portrait to landscape orientation.
9. Verified the Keyman system keyboard is not covered by any of the system insets.
10. Verified the keyboard keys and suggestion banner function.
It works well.

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java (hunk 1 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java]:
```suggestion
    // Only applies to In-App keyboard #14619
```

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 19.0.108-alpha](https://keyman.com/downloads/releases/alpha/19.0.108)
