### PR TITLE
fix(windows): Keyman was crashing sporadically

### LINKED ISSUE #2147: [Windows] UnregisterControllerWindows exception on shutdown
**Describe the bug**
Various exceptions have been reported when calling UnregisterControllerWindows when exiting Keyman:

* https://github.com/sillsdev/keyman-issues/issues/6060 (12.0.1)

* https://github.com/sillsdev/keyman-issues/issues/5971 (11.0.1361.0)
* https://github.com/sillsdev/keyman-issues/issues/5865 (11.0.1352.0)
* https://github.com/sillsdev/keyman-issues/issues/5920 (11.0.1356.0)
* https://github.com/sillsdev/keyman-issues/issues/5966 (11.0.1360.0)
* https://github.com/sillsdev/keyman-issues/issues/5848 (11.0.1350.0)
* https://github.com/sillsdev/keyman-issues/issues/5965 (11.0.1359.0)

* https://github.com/sillsdev/keyman-issues/issues/5823 (10.0.1207.0)
* https://github.com/sillsdev/keyman-issues/issues/5788 (10.0.1206.0)
* https://github.com/sillsdev/keyman-issues/issues/5771 (10.0.1205.0)
* https://github.com/sillsdev/keyman-issues/issues/5677 (10.0.1201.0)
* https://github.com/sillsdev/keyman-issues/issues/6079 (10.0.1208.0)
* https://github.com/sillsdev/keyman-issues/issues/5990 (10.0.1203.0)

There are multiple exception messages recorded here (all found in https://github.com/sillsdev/keyman-issues/issues/5971):

* Exception EOleException in keyman.exe: Could not load keyman32.dll.  Windows returned the error code        2 (Failed to find keyman32.dll at "C:\Program Files (x86)\Common Files\Keyman\Keyman Engine\keyman32.dll", The system cannot find the file specified)

* Exception EOleException in keyman.exe: Could not load keyman32.dll.  Windows returned the error code      3E6 (Failed to LoadLibrary for "C:\Program Files (x86)\Common Files\Keyman\Keyman Engine\keyman32.dll", Invalid access to memory location)

* Exception EOleException in keyman.exe: EKeyman Could not unregister controller window

Not clear from this whether they all have the same root cause or not.

---

(Delete the irrelevant sections)

**Keyman Desktop:**
 - OS: Windows
 - Keyman version: Multiple versions

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #2147.

This potentially addresses the issues reported in #2147 where Keyman
would crash due to a race condition as a critical section was not
deleted before attempting to recreate it.

Some logging has been added for debugging these issues.

Also fixes memory leaks and another race on startup relating to loading
the taskbar icon.

There are still some known memory leaks because DLL_THREAD_DETACH is
not called for all threads before keyman32.dll is unloaded, so those
threads don't get the opportunity to clean themsselves up. However, the
key danger with the csGlobals critical section has been addressed.

### CODE REVIEW

**Comment by mcdurdin** [comment]
There is certainly more we can do to improve things here. Much of this code needs a solid refactor, but that's a big job and not due for 13.0; we'll do it inline with the Keyman Core work.

File: windows/src/engine/keyman32/Keyman32.cpp [hunk 1]
```diff
@@ -938,13 +955,14 @@ void RefreshKeyboards(BOOL Initialising)
 
   _td->FInRefreshKeyboards = FALSE;
 }
-
 void ReleaseKeyboards(BOOL Lock)
 {
+  OutputThreadDebugString("ReleaseKeyboards");
   PKEYMAN64THREADDATA _td = ThreadGlobals();
-	if(!_td || _td->lpKeyboards) return;
+	if(!_td || !_td->lpKeyboards) return;
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/Keyman32.cpp]: Note the flipped test here. This was the primary cause of leaks. Fixing this showed up another issue in `KeyboardOptions.cpp` where assertions in `FreeKeyboardOptions` would be triggered for keyboards that had never been loaded were being torn down.

File: windows/src/engine/keyman32/hookutils.cpp [hunk 2]
```diff
@@ -15,45 +15,44 @@ typedef BOOL
     IN CONST PMINIDUMP_CALLBACK_INFORMATION CallbackParam OPTIONAL
     );
 
-
-DWORD ExceptionMessage(LPSTR Proc, LPEXCEPTION_POINTERS ep)
-{
+DWORD ExceptionMessage(LPSTR Proc, LPEXCEPTION_POINTERS ep) {
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/hookutils.cpp]: For this function, I opted to use lower level debugging messages because we are in an exception state.

File: windows/src/engine/keyman32/hotkeys.cpp [hunk 3]
```diff
@@ -45,6 +45,18 @@ Hotkeys *Hotkeys::Instance() {   // I4326
   return g_Hotkeys;
 }
 
+void Hotkeys::Unload() {
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/hotkeys.cpp]: Fixes another (small) leak

File: windows/src/engine/keyman32/k32_globals.cpp [hunk 4]
```diff
@@ -185,6 +189,7 @@ void Globals_UninitProcess()
   TlsFree(dwTlsIndex);
   dwTlsIndex = TLS_OUT_OF_INDEXES;
   LeaveCriticalSection(&csGlobals);
+  DeleteCriticalSection(&csGlobals);
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/k32_globals.cpp]: This is the most critical change. If we attempt to use `csGlobals` after this we'll run into huge problems, so we have to assume that the DLL has been detached from all threads prior to this being called. This is not necessarily a safe assumption to make!

The problem is, if keyman32.dll is reloaded, it typically reloads at the same address, and so `csGlobals` gets reused. It may be that a safer alternative is to allocate memory for `csGlobals` and let it leak: that will effectively ensure it gets relocated and avoid double-initialization.

DLL detach is messy.

**Comment by mcdurdin** [comment]
My main concern with this is I still have not identified how the crash condition can arise. The error occurs while Keyman is shutting down, and appears to show keyman32.dll being loaded in **keymancontrol.pas**, `TKeymanControl.LoadKeyman32`. However, I have, as yet, been unable to find any scenarios where `hlibKeyman32` could be zero during shutdown, so it seems impossible to reach that code. The fixes I have made are good fixes, but without a full understanding of how we get from `a` to `b` (or `z`) I am not 100% confident that this is sufficient.

There are also risks, of course, with making these changes. They may impact stability. Thus, once this hits alpha, it would be good for all of us on Windows to be using this version.

File: windows/src/engine/keyman32/K32_DBG.CPP [hunk 5]
```diff
@@ -304,4 +304,12 @@ char *Debug_UnicodeString(PWSTR s, int x) {
...
   return bufout[x];
-}
\ No newline at end of file
+}
+
+#ifdef _DEBUG
+void _OutputThreadDebugString(char *s) {
+  char buf[256];
+  wsprintf(buf, "[%d]: %s\n", GetCurrentThreadId(), s);
+  OutputDebugString(buf);
```
Comment (jahorton) [inline windows/src/engine/keyman32/K32_DBG.CPP]: It's not too dangerous since we do control what debug strings are possible within our code, but it might be wise to add a string-length bounds check anyway.

File: windows/src/engine/keyman32/hookutils.cpp [hunk 6]
```diff
@@ -15,45 +15,44 @@ typedef BOOL
...
-  if(GetTempPath(MAX_PATH, temppath) == 0 ||
-      GetTempFileName(temppath, "kmc", 0, filename) == 0)
-    SendDebugMessageFormat(0, sdmGlobal, 0, "Minidump failed to generate temp file name");
-  else
-  {
+  if (GetTempPath(MAX_PATH, temppath) == 0 ||
+      GetTempFileName(temppath, "kmc", 0, filename) == 0) {
+    OutputThreadDebugString("Minidump failed to generate temp file name\n");
+  } 
+  else {
```
Comment (jahorton) [inline windows/src/engine/keyman32/hookutils.cpp]: Not same line?  I know, style nitpick, but still.

File: windows/src/engine/keyman32/hookutils.cpp [hunk 7]
```diff
@@ -66,23 +65,26 @@ DWORD ExceptionMessage(LPSTR Proc, LPEXCEPTION_POINTERS ep)
...
-    	  er->ExceptionInformation[0] == 0 ? "read from" : "write to",
-    	  er->ExceptionInformation[1]);
-    else
-  	  SendDebugMessageFormat(0, sdmGlobal, 0, "CAUGHT EXCEPTION %d IN %s AT %x",
-    	  er->ExceptionCode, Proc, er->ExceptionAddress);
+  while(er != NULL) {
+    if (er->ExceptionCode == EXCEPTION_ACCESS_VIOLATION) {
+      OutputThreadDebugString("EXCEPTION_ACCESS_VIOLATION in ");
+      OutputThreadDebugString(Proc);
+      SendDebugMessageFormat(0, sdmGlobal, 0, "CAUGHT EXCEPTION %d (ACCESS VIOLATION) IN %s AT %x; attempted to %s %x",
```
Comment (jahorton) [inline windows/src/engine/keyman32/hookutils.cpp]: I assume this (and the one in the following `else` block) weren't possible to replace like the others?

(in reference to https://github.com/keymanapp/keyman/pull/2297/files#r342938825)

File: windows/src/engine/keyman32/k32_globals.cpp (hunk 4 above)
Comment (jahorton) [reply windows/src/engine/keyman32/k32_globals.cpp]: Clearly... I don't quite understand what's going on here, even from this.  I've probably got an oversimplified view of things.  So, I'll expound on what I think intuitively here - please address the invalid assumptions I've probably made below:

- `csGlobals` stands for "critical section globals"
- `csGlobals` is allocated in static memory.
  - I say this due to the dereference (`&`) being used to grab a pointer to the variable for the "deletion".
- So, "deleting" `csGlobals` basically means zeroing-out the memory, resetting it to prepare for the next DLL attach?
- The worry then is that b/c race conditions, a thread might pollute the "reset" memory space during shutdown, causing trouble on reload due to unexpectedly altered `csGlobals` state?  (This is the least clear part to me.)

Following from that:
- "safer alternative":  allocate `csGlobals` on the heap instead
- `csGlobals` would then store a pointer
- by letting `csGlobals` leak, any existing references (b/c race conditions) to the old memory location don't cause crashes

Of course, memory leaks aren't ideal.  There ought to be some sort of synchronization/concurrency check on use of `csGlobals` so that we can know when it's safe to delete / reset it.
- since this is mentioned as a problem, I'm assuming there are no concurrency checks in place on `csGlobals`.  (Or "insufficient")
- [ ] Before merging, an issue should be made to fix the ensuing memory leak.

File: windows/src/engine/keyman32/hookutils.cpp (hunk 7 above)
Comment (mcdurdin) [reply windows/src/engine/keyman32/hookutils.cpp]: They add more information so I left them ... which may not be the best idea.

File: windows/src/engine/keyman32/k32_globals.cpp (hunk 4 above)
Comment (mcdurdin) [reply windows/src/engine/keyman32/k32_globals.cpp]: Pretty good summary 😉 

I don't know what `DeleteCriticalSection` does internally but it will be removing that cs from Windows' list of critical sections in the process if nothing else.

The concurrency check **is** `csGlobals` -- so when deallocating it there is no other check we can make.

According to the world, `DLL_PROCESS_DETACH` will always be the last event we receive so it's safe to do this deallocation there (e.g. https://docs.microsoft.com/en-us/windows/win32/dlls/dllmain, https://blogs.msdn.microsoft.com/larryosterman/2004/06/10/dll_process_detach-is-the-last-thing-my-dlls-going-to-see-right/)

The concern is primarily that we may still have activity on another thread that is stepping into our DLL's code at the time when we do the deallocation. From my understanding this cannot happen for hooks because a hook is guaranteed to be detached from the process before the library is unloaded by Windows. Unless we have a bug elsewhere! So I *think* it's all safe.

Speaking of leaks, a process detach may happen without a thread detach for all threads. The appropriate response is to free the memory we've allocated for every thread left in the process but we don't currently have a shared list of allocated resources (it's all done in thread-local storage as you'd expect). So this means closing Keyman does leak a few KB in each process. Not enough to matter most of the time. And probably not worth the effort to clean up.

Comment (jahorton) [reply windows/src/engine/keyman32/k32_globals.cpp]: > So this means closing Keyman does leak a few KB in each process

I assume that means that the memory we leak is technically within the host process (i.e., program receiving keyboard input)?

Comment (mcdurdin) [reply windows/src/engine/keyman32/k32_globals.cpp]: Yes.

File: windows/src/engine/keyman32/hookutils.cpp (hunk 6 above)
Comment (mcdurdin) [reply windows/src/engine/keyman32/hookutils.cpp]: Thank Visual Studio for this -- that's its default. For now, I am comfortable sticking with this; I would like to do a tabs->spaces cleanup at some point and some of this formatting kinda belongs with that.

File: windows/src/engine/keyman32/k32_globals.cpp (hunk 4 above)
Comment (jahorton) [reply windows/src/engine/keyman32/k32_globals.cpp]: > The concurrency check **is** `csGlobals` -- so when deallocating it there is no other check we can make.

Interesting - so no separate object to synchronize on for modifications to its contents/state?

Comment (jahorton) [reply windows/src/engine/keyman32/k32_globals.cpp]: Then, how often do we expect Keyman to create leaks within a process?  Does Keyman come in and out of a process with regularity?

Comment (mcdurdin) [reply windows/src/engine/keyman32/k32_globals.cpp]: Critical sections are a synchronization primitive -- they are the object that we use for all other synchronization. They of course need initialization and teardown. Perhaps I'm not understanding your question?

Comment (mcdurdin) [reply windows/src/engine/keyman32/k32_globals.cpp]: > Then, how often do we expect Keyman to create leaks within a process? Does Keyman come in and out of a process with regularity?

Only when a user exits Keyman completely. This should not be normal user behaviour... apart from Explorer and a few system processes, most other processes are started and shut down regularly in any case, so the memory leak will be short lived also.

Comment (mcdurdin) [reply windows/src/engine/keyman32/k32_globals.cpp]: But, none of this around leaks is new -- it's been here for 20+ years so we can probably live with it a little longer...

Comment (jahorton) [reply windows/src/engine/keyman32/k32_globals.cpp]: Ah, so I didn't understand the nature of `csGlobals`.  I see the "global**s**", I think `struct`, not primitive.

Comment (mcdurdin) [reply windows/src/engine/keyman32/k32_globals.cpp]: `csGlobals` uses the Windows-style variable name "cs" = critical section, "globals" refers to what it is protecting -- our Keyman global variables (of which there are far too many but topic for another [rainy] day).
