### PR TITLE
fix(android): keyboard's black bar bug

### LINKED ISSUE #5252: bug(android): Inconsistent OSK dimensions on rotation - in-app
**Describe the bug**

Split out from #5211.

@darcywong00 writes:

During testing of #5201, I noticed the OSK height doesn't reliably resize to the correct height when toggling between portrait and landscape orientation. (landscape usually ends up "taller" than what the default dimension specifies)

Going into the globe button menu and existing seems to refresh OSK to the correct dimensions.
This affects both in-app and system keyboard; this issue is about the in-app glitches.

Keyman 15

---

**Keyman for iPhone/iPad/Android:**
 - Device: Samsung Galaxy A90 (@mcdurdin test) 
 - OS: Android 11 
 - Keyman version: 15.0.65-alpha 
 - Target application: Keyman

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #5252.

I figured out the solution while working on embedded keyboard layout issues in #5459 after asking @darcywong00 how the WebView sets its height.

----------

## User Testing

@keymanapp/testers 

Gonna be kinda lazy with this one.

- [ ] TEST_WITH_PREDICTIONS:  load up the Keyman app with `sil_euro_latin` as the active keyboard, predictive text on.
    - Rotate the phone and confirm that the layout looks correct.
    - Rotate the phone back to its original orientation and confirm that the layout looks correct.
- [ ] TEST_WITHOUT_PREDICTIONS:  this time, use a keyboard without predictive text - say, `kbd_basicmyan` - and repeat the test.

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java [hunk 1]
```diff
@@ -324,6 +325,10 @@ public void onConfigurationChanged(Configuration newConfig) {
     super.onConfigurationChanged(newConfig);
     dismissKeyPreview(0);
     dismissSubKeysWindow();
+
+    RelativeLayout.LayoutParams params = KMManager.getKeyboardLayoutParams();
+    this.setLayoutParams(params);
```
Comment (darcywong00) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java:330]: Will SystemKeyboard.java need this too?

Though I see it doesn't have the rest of `onConfigurationChanged()` either.

Comment (jahorton) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java:330]: This fixes both.  This is the `KMKeyboard` class, which is the base class of both the in-app and system keyboards.

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java:330]: /facepalm

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by MakaraSok** [comment]
## User Testing - Results


- [x] **PASSED** TEST_WITH_PREDICTIONS:  load up the Keyman app with `sil_euro_latin` as the active keyboard, predictive text on.
    - Rotate the phone and confirm that the layout looks correct.
    - Rotate the phone back to its original orientation and confirm that the layout looks correct.

- [x] **PASSED** TEST_WITHOUT_PREDICTIONS:  this time, use a keyboard without predictive text - say, `kbd_basicmyan` - and repeat the test.

---

> There is one issue on Android 5.0, the backspace doesn't work as expected while it works fine on Android 6.0 and 10.0.
> Keyman was set as the system keyboard, from the web browser, type in the text input area and then type a few characters and try deleting, only to find nothing got delete when the backspace was pressed on.

image


@darcywong00 Something weird with Android 5.0.

**Comment by darcywong00** [comment]
> Something weird with Android 5.0.

I don't think that's it. Likely something similar to #4753 that's still an issue. This PR should be fine to merge though.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.96-alpha](https://keyman.com/downloads/releases/alpha/15.0.96)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.101-alpha](https://keyman.com/downloads/releases/alpha/15.0.101)
