### PR TITLE
fix(core): strip markers in `actions_update_app_context_nfu()`

### LINKED ISSUE #10605: bug(core): `actions_update_app_context_nfu` needs to strip markers when updating app context
This was showing up in Keyman for Windows, Hieroglyphic keyboard, per rc_swag:

1. Install [Hieroglyphic ](url)Keyboard from [keyman.com](http://keyman.com/)
2. Open a app that supports surround_text in linux.
3. Select the Hieroglyphic keyboard
4. In the linux application type Type: <kbd>d</kbd><kbd>i</kbd><kbd>spacebar</kbd><kbd>spacebar</kbd>
5. Expected Output : 𓂞
6. Type:<kbd>backspace</kbd>
7. Expected Output: Empty and the character bar above the input text should no have any character just showing `empty`.
Step 4 fails for me with windows TSF apps when I press the second spacebar nothing happens it stays as 𓏙.

---

Logging of that action shows the following:

```
TIPProcessKey: Enter VirtualKey=['D' 0x44] lParam=200001   IsUp=0 Extended=0 Updateable=1 Preserved=0
TIPProcessKey: Enter VirtualKey=['D' 0x44] lParam=c0200001   IsUp=1 Extended=0 Updateable=1 Preserved=0
Process_Event_Core: set_if_needed result: 0
Process_Event_Core: context app before:   |d| (len: 1) [ U+0064 ]
Process_Event_Core: context app after:    |d| (len: 1) [ U+0064 ]
Process_Event_Core: context cache before: |d| (len: 1) [ U+0064 ]
Process_Event_Core: context cache after:  |d| (len: 1) [ U+0064 ]
TIPProcessKey: Enter VirtualKey=['I' 0x49] lParam=170001   IsUp=0 Extended=0 Updateable=1 Preserved=0
Process_Event_Core: set_if_needed result: 0
Process_Event_Core: context app before:   |d| (len: 1) [ U+0064 ]
Process_Event_Core: context app after:    |d| (len: 1) [ U+0064 ]
Process_Event_Core: context cache before: |d| (len: 1) [ U+0064 ]
Process_Event_Core: context cache after:  |d| (len: 1) [ U+0064 ]
TIPProcessKey: Enter VirtualKey=['I' 0x49] lParam=c0170001   IsUp=1 Extended=0 Updateable=1 Preserved=0
Process_Event_Core: set_if_needed result: 0
Process_Event_Core: context app before:   |di| (len: 2) [ U+0064 U+0069 ]
Process_Event_Core: context app after:    |di| (len: 2) [ U+0064 U+0069 ]
Process_Event_Core: context cache before: |di| (len: 2) [ U+0064 U+0069 ]
Process_Event_Core: context cache after:  |di| (len: 2) [ U+0064 U+0069 ]
TIPProcessKey: Enter VirtualKey=['Spacebar' 0x20] lParam=0   IsUp=0 Extended=0 Updateable=0 Preserved=1
Process_Event_Core: set_if_needed result: 0
Process_Event_Core: context app before:   |di| (len: 2) [ U+0064 U+0069 ]
Process_Event_Core: context app after:    |di| (len: 2) [ U+0064 U+0069 ]
Process_Event_Core: context cache before: |di| (len: 2) [ U+0064 U+0069 ]
Process_Event_Core: context cache after:  |di| (len: 2) [ U+0064 U+0069 ]
TIPProcessKey: Enter VirtualKey=['Spacebar' 0x20] lParam=0   IsUp=0 Extended=0 Updateable=1 Preserved=1
TIPProcessKey: Enter VirtualKey=['Spacebar' 0x20] lParam=c0390001   IsUp=1 Extended=0 Updateable=1 Preserved=0
Process_Event_Core: set_if_needed result: 1
Process_Event_Core: context app before:   |??| (len: 2) [ M(59) U+133d9 ]
Process_Event_Core: context app after:    |??| (len: 1) [ U+133d9 ]
Process_Event_Core: context cache before: |??| (len: 2) [ M(59) U+133d9 ]
Process_Event_Core: context cache after:  |??| (len: 1) [ U+133d9 ]
TIPProcessKey: Enter VirtualKey=['Spacebar' 0x20] lParam=0   IsUp=0 Extended=0 Updateable=0 Preserved=1
Process_Event_Core: set_if_needed result: 1
Process_Event_Core: context app before:   |??| (len: 1) [ U+133d9 ]
Process_Event_Core: context app after:    |??| (len: 1) [ U+133d9 ]
Process_Event_Core: context cache before: |??| (len: 1) [ U+133d9 ]
Process_Event_Core: context cache after:  |??| (len: 1) [ U+133d9 ]
TIPProcessKey: Enter VirtualKey=['Spacebar' 0x20] lParam=0   IsUp=0 Extended=0 Updateable=1 Preserved=1
TIPProcessKey: Enter VirtualKey=['Spacebar' 0x20] lParam=c0390001   IsUp=1 Extended=0 Updateable=1 Preserved=0
Process_Event_Core: set_if_needed result: 1
Process_Event_Core: context app before:   |??| (len: 1) [ U+133d9 ]
Process_Event_Core: context app after:    |??| (len: 1) [ U+133d9 ]
Process_Event_Core: context cache before: |??| (len: 1) [ U+133d9 ]
Process_Event_Core: context cache after:  |??| (len: 1) [ U+133d9 ]
```

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #10605.

Includes unit test for marker stripping; unit tests for the module extensively refactored to ensure that we are testing the full context and not inadvertently missing markers.

# User Testing

* **TEST_HIEROGLYPHIC_WINDOWS**
  1. Install Hieroglyphic Keyboard from keyman.com into Keyman for Windows.
  2. Open Wordpad.
  3. Select the Hieroglyphic keyboard
  4. In wordpad, type: <kbd>d</kbd><kbd>i</kbd><kbd>spacebar</kbd><kbd>spacebar</kbd>
  5. Expected Output : 𓂞
  6. Type:<kbd>backspace</kbd>
  7. Expected Output: Empty

### CODE REVIEW

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_HIEROGYLPHIC_WINDOWS (FAILED):** Tested with the attached PR build (17.0.257-alpha-test-10607) on Windows 10 OS and here is my observation: 1. Installed Hieroglyphic keyboard from Keyman.com. 2. Opened WordPad. 3. Switched to Hieroglyphic keyboard. 4. In wordpad, typed "di<spacebar><spacebar>". 5. Noticed that it is showing the wrong output. 6. Retested in Windows 11 OS (VM) and I am seeing the same behavior.

**Comment by mcdurdin** [comment]
TEST_HIEROGLYPHIC_WINDOWS SKIP - now running this test in the follow-up PR #10618 as this PR still had other bugs impacting this test.

File: core/tests/unit/kmnkbd/test_actions_normalize.cpp [hunk 1]
```diff
@@ -329,5 +592,25 @@ int main(int argc, char *argv []) {
...
+  run_actions_normalize_tests();
+  run_actions_update_app_context_nfu_tests();
+}
+
+
+void compare_context(km_core_context *app_context, const km_core_cp* expected_final_app_context) {
+  // Compare context items -- to ensure no markers have leaked into app context
+  km_core_context_item *actual_final_app_context_items = nullptr, *expected_final_app_context_items = nullptr;
+  try_status(km_core_context_get(app_context, &actual_final_app_context_items));
+  try_status(context_items_from_utf16(expected_final_app_context, &expected_final_app_context_items));
```
Comment (rc-swag) [inline core/tests/unit/kmnkbd/test_actions_normalize.cpp:604]: This will strip the markers when `expected_final_app_context_items`. Which when I think about it is what you want as you want to make sure the app_context does not have any markers.

File: core/tests/unit/kmnkbd/test_actions_normalize.cpp [hunk 2]
```diff
@@ -118,44 +131,115 @@ void test(
...
+void run_actions_normalize_tests() {
 
   // Null boundary tests
 
-  test(
+  test_actions_normalize(
     "noop",
     /* app context pre transform: */     u"",
     /* cached context post transform: */ u"",
+    /* cached context post transform: */ nullptr,
```
Comment (rc-swag) [inline core/tests/unit/kmnkbd/test_actions_normalize.cpp:220]: It took me a while to realise that this is a one or the other situation. The caller either provides a cached context string XOR a cached context items array. At least I think that is the case. Maybe have a comment about this where `test_actions_normalize` is defined.

**Review by rc-swag — APPROVED** [review]
I was little confused with the test cases but the code change LGTM

File: core/tests/unit/kmnkbd/test_actions_normalize.cpp [hunk 3]
```diff
@@ -118,44 +131,115 @@ void test(
...
+ * @param final_cached_context_string   cached context _after_ actions have been
+ *                                      applied -- NFU (essentially,
+ *                                      this is initial_cached_context -
+ *                                      actions_code_points_to_delete +
+ *                                      actions_output) - no markers supported
+ * @param final_cached_context_items    cached context _after_ actions have been
+ *                                      applied -- NFU (essentially,
+ *                                      this is initial_cached_context -
+ *                                      actions_code_points_to_delete +
+ *                                      actions_output) - markers supported
```
Comment (mcdurdin) [inline core/tests/unit/kmnkbd/test_actions_normalize.cpp:159]:
```suggestion
 * @param final_cached_context_string   cached context _after_ actions have been
 *                                      applied -- NFU (essentially,
 *                                      this is initial_cached_context -
 *                                      actions_code_points_to_delete +
 *                                      actions_output) - no markers supported.
 *                                      If specified, final_cached_context_items 
 *                                      must be nullptr.
 * @param final_cached_context_items    cached context _after_ actions have been
 *                                      applied -- NFU (essentially,
 *                                      this is initial_cached_context -
 *                                      actions_code_points_to_delete +
 *                                      actions_output) - markers supported.
 *                                      If specified, final_cached_context_string
 *                                      must be nullptr.
```

File: core/tests/unit/kmnkbd/test_actions_normalize.cpp (hunk 2 above)
Comment (mcdurdin) [reply core/tests/unit/kmnkbd/test_actions_normalize.cpp:220]: https://github.com/keymanapp/keyman/pull/10607/files#r1477694532

**Review by ermshiperete — APPROVED** [review]

File: core/src/actions_normalize.cpp [hunk 4]
```diff
@@ -301,6 +301,17 @@ bool km::core::actions_update_app_context_nfu(
     return false;
   }
 
+  // Strip markers from returned context
+
+  int i, j;
+  for(i = 0, j = 0; items[i].type != KM_CORE_CT_END; i++) {
+    if(items[i].type == KM_CORE_CT_CHAR) {
```
Comment (srl295) [inline core/src/actions_normalize.cpp:308]: Would this be more robust? Since the wording is 'remove markers'

```suggestion
    if(items[i].type != KM_CORE_CT_MARKER) {
```

**Review by srl295 — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.262-alpha](https://keyman.com/downloads/releases/alpha/17.0.262)
