### PR TITLE
fix(ios): make text size of in-app editor consistent with slider

### LINKED ISSUE #7185: bug(iOS): In-app text initially appears smaller than the value in the Text Size setting
**Describe the bug**
The initial text size when typing with the in-app keyboard is smaller than the default Text Size setting.
**To Reproduce**
1. Install Keyman 16.0.54-alpha build in iPhone 13 Pro Max Simulator. 
2. Open Keyman In-App.
3. Type some text on the Text pane. 
4. Notice that the font size is smaler than the default Text Size setting. 
5. Click the 3 dots button. 
6. Click the Text Size button. 
7. Verify that the Text Size dialog appear on the screen. 
8. Click on the slider button without actually moving it and notice the size of the existing text immediately grows in size to match the Text Size setting.

**Expected behavior**
Typing on the Text pane should always match the default Text Size setting. 

**Screenshots**
iPhone 13 Pro Max Simulator:

   

iPad 9th generation Simulator:

  

---

**Keyman for iPhone/iPad:**
   Device:   iPhone 13 Pro Max Simulator / iPad 9th generation Simulator  
 - OS:  iOS 15.5          
 - Keyman version:  Keyman 16.0.54 alpha    
 - Target Application: Keyman In-App

---

**Keyboard**
 - Keyboard name:    English - EuroLatin(SIL)
 - Keyboard version: 2.0
 - Language name:    English

**Additional context**
Able to reproduce this issue in iPad Simulator. It would be better to reproduce this issue in iPhone real device.

### PR DESCRIPTION
**Pull request by sgschantz**
Fixes #7185 

Modified the way that the text size setting is initialized during the creation of Keyman's in-app editor view so that it is always in sync with the user's saved value and the text size slider.

# User Testing

* **TEST_IPHONE_IN_APP_EDITOR:**

1. Run Keyman on an iPhone or simulator with no user data saved so that no previous text or installed keyboards appear in the app
2. Type some text in the in-app editor
3. The text should appear in a 16 point font, but it may be difficult to see if it is the correct size
4. Go to the three dots menu and choose Text Size, confirm that it is set to 16
5. While carefully watching the text you typed to make sure that it does not change size, tap on the slider control without moving it
* **TEST_IPAD_IN_APP_EDITOR:**

1. Run Keyman on an iPad or simulator with no user data saved so that no previous text or installed keyboards appear in the app
2. Type some text in the in-app editor
3. The text should appear in a 32 point font, but it may be difficult to see if it is the correct size
4. Go to the three dots menu and choose Text Size, confirm that it is set to 32
5. While carefully watching the text you typed to make sure that it does not change size, tap on the slider control without moving it

* **TEST_IPHONE_SAVE_TEXT_SIZE**

1. Run Keyman on an iPhone or simulator and type some text in the in-app editor
2. Go to the three dots menu and choose Text Size
3. Drag the slider to change the text to a different size
4. Close the app by switching to the home screen or another app
5. Use the task switcher to kill Keyman
6. Tap on Keyman to open it again
7. Verify that the text size setting in the Keyman editor is set to the same value as before you closed the app

### CODE REVIEW

**Comment by bharanidharanj** [comment]
* **TEST_IPHONE_IN_APP_EDITOR (PASSED):** Tested with the attached PR build in iPhone 12 Pro Simulator and here is my observation: 1. Verified that the text size did not change to any other size and it alwayas showing 16 size. 


   

* **TEST_IPAD_IN_APP_EDITOR (PASSED):** Verified that the default text size is 32 in the iPad Simulator. 

   


* **TEST_IPHONE_SAVE_TEXT_SIZE (PASSED):** Verified that the saved (custom) text size appearing on the text area after relaunching Keyman In-app.

File: ios/keyman/Keyman/Keyman/Classes/MainViewController/MainViewController.swift [hunk 1]
```diff
@@ -135,28 +139,67 @@ class MainViewController: UIViewController, TextViewDelegate, UIActionSheetDeleg
...
+        self.textSize = self.calculateDefaultTextSize()
+      }
+    
+      // default to system font so that we have a non-nil font that allows us to set size
+      self.textView.font = UIFont.systemFont(ofSize: textSize)
 
-    if UIDevice.current.userInterfaceIdiom != .phone {
-      textSize *= 2
-      textView.font = textView?.font?.withSize(textSize)
+    // set slider position
```
Comment (mcdurdin) [inline ios/keyman/Keyman/Keyman/Classes/MainViewController/MainViewController.swift:185]:
```suggestion
      // set slider position
```

**Review by mcdurdin — APPROVED** [review]
LGTM

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.109-beta](https://keyman.com/downloads/releases/beta/16.0.109)
