### PR TITLE
fix(mac): fix corrupt installer

### LINKED ISSUE #8533: bug(macOS): Not able to install Keyman 17.0.78-alpha on macMini M1 OS
### Describe the bug

I was not able to install Keyman 17.0.78-alpha build on macMini M1 OS, since it is showing an error message. 

### Reproduce the bug

Here, What I did is:
1. Downloaded Keyman 17.0.78.dmg file from keyman status site. 
2. I tried to install the .dmg file in my macMini M1 (Ventura) OS and I was getting the following error message, 

   

### Expected behavior

Keyman 17.0.78 build should install in the macOS. 

### Related issues

_No response_

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.78-alpha

### Operating system

macMini M1 Ventura OS

### Device

_No response_

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes https://github.com/keymanapp/keyman/issues/8533 after build agent maintenance put GNU coreutils cp on path ahead of macOS /bin/cp. This subtly changed the behaviour of the `-R` flag such that it copied the folder into a subfolder rather than copying the contents of the folder into the destination folder:

Original layout:

```
Install Keyman.app/Contents/MacOS/
  applet
  textinputsource
  Keyman.app/
```

Corrupted layout:

```
Install Keyman.app/Install Keyman.app/Contents/MacOS/
  applet
  textinputsource
  Keyman.app/
```

Query: should we be rolling back the path changes so that /bin is first on the path? I am concerned about other subtle changes in behaviour in the macOS and iOS builds. Otherwise it feels like we may need to audit the scripts in /mac, /ios (and possibly /common, /core, /web, /resources) for potential changes.

Annoyed that it took me so long to figure out. Also annoying that macOS fails so subtly when a parent folder has the .app extension in its name (this seems to be a bug in Gatekeeper, really).

# User Testing

* TEST_INSTALLER: Verify that Keyman for Mac installs and runs successfully, on a clean VM. Make sure that you can install and use a keyboard.

### CODE REVIEW

**Comment by mcdurdin** [comment]
I guess if we go this way, we'll need to cherry-pick this to stable-16.0. Not sure I am happy with this solution!

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
Another thing for me to check: globbing skips dot files so this may still be subtly different. My preference is for identical behaviour on GNU cp and BSD cp, so we may need to tweak incantations.

Same problem experienced by another dev: https://dev.to/ackshaey/macos-vs-linux-the-cp-command-will-trip-you-up-2p00

File: mac/Keyman4MacIM/make-km-dmg.sh [hunk 1]
```diff
@@ -174,7 +174,7 @@ displayInfo "Copying files from \"$SOURCE_KM_APP\"..."
 find "$DEST_KM_APP" -mindepth 1 -maxdepth 1
 echo "---------"
 find "$DEST_KM_APP" -mindepth 1 -maxdepth 1 -print0 | xargs -0 rm -rf
-cp -fR "$SOURCE_KM_APP/" "$DEST_KM_APP"
+cp -fR "$SOURCE_KM_APP/"* "$DEST_KM_APP/"
```
Comment (mcdurdin) [inline mac/Keyman4MacIM/make-km-dmg.sh:177]:
```suggestion
cp -fR "$SOURCE_KM_APP/." "$DEST_KM_APP/"
```

Moving to using this instead of `*` because `*` excludes dot files. I have tested this with both GNU cp and BSD cp, and seems to be reliable.

**Review by mcdurdin — COMMENTED** [review]
Because I am now worried about this, I have audited for all instances of `cp -R` that I can find, using the following regex:

```
\bcp\b.+-[a-zA-Z]*R
```

Which found the following results:

```
20 results - 11 files

developer\src\kmcmplib\tests\keyboards\resources\external.sh:
  103    # We copy all files (excluding dot-files such as .git, .gitignore)
  104:   cp -R -t "$dest_path" *
  105  

developer\src\server\build.sh:
  140    cp "$UI_SRC/"*.js "$UI_SRC/"*.js.map "$DST/"
  141:   cp -R "$WEB_SRC/osk/"* "$DST/osk/"
  142:   cp -R "$WEB_SRC/ui/"* "$DST/ui/"
  143    cp "$KEYMAN_ROOT/web/LICENSE" "$DST/"

  186    mkdir -p "$PRODBUILDTEMP/node_modules/@keymanapp/"
  187:   cp -R "$KEYMAN_ROOT/node_modules/@keymanapp/keyman-version/" "$PRODBUILDTEMP/node_modules/@keymanapp/"
  188  

  191    mkdir -p "$KEYMAN_ROOT/developer/bin/server/dist/"
  192:   cp -R dist/* "$KEYMAN_ROOT/developer/bin/server/dist/"
  193:   cp -R "$PRODBUILDTEMP"/* "$KEYMAN_ROOT/developer/bin/server/"
  194    rm -rf "$PRODBUILDTEMP"

ios\samples\build_common.sh:
  131      # Copy resources.
  132:     cp -Rf "$KEYMAN_ENGINE_FRAMEWORK_SRC" "$KEYMAN_ENGINE_FRAMEWORK_DST"
  133  fi

mac\Keyman4MacIM\localdeploy.sh:
  44  echo "Copying $KM4MIM_APP_PATH to $IMLIBRARY_PATH..."
  45: cp -R "$KM4MIM_APP_PATH" "$IMLIBRARY_PATH"
  46  

mac\Keyman4MacIM\make-km-dmg.sh:
  176  find "$DEST_KM_APP" -mindepth 1 -maxdepth 1 -print0 | xargs -0 rm -rf
  177: cp -fR "$SOURCE_KM_APP/" "$DEST_KM_APP"
  178  

mac\setup\build.sh:
  64  # Copy new install image to output folder
  65: cp -R "$SOURCEAPP" "$TARGETPATH/"
  66  
  67  # Copy Keyman.app into install image
  68: cp -R "$KEYMANAPP" "$TARGETAPP/Contents/MacOS/Keyman.app"
  69  

oem\firstvoices\ios\build_common.sh:
  156      # Copy resources.
  157:     cp -Rf "$KEYMAN_ENGINE_FRAMEWORK_SRC" "$KEYMAN_ENGINE_FRAMEWORK_DST"
  158  fi

resources\standards-data\ldml-keyboards\techpreview\fetch-latest-cldr-techpreview.sh:
  59  # copy over everything
  60: cp -Rv "${IMPORT_DIR}" "${DATA_DIR}" "${DTD_DIR}" "${TEST_DIR}" .
  61  

web\build.sh:
  197        builder_echo "- src/resources/$RESOURCE/ => $CONFIG_OUT_PATH/$RESOURCE"
  198:       cp -Rf "src/resources/$RESOURCE"  "$CONFIG_OUT_PATH/"  >/dev/null
  199      done

  244        mkdir -p "$CONFIG_OUT_PATH/src/$SOURCE_FOLDER"
  245:       cp -Rf  "src/$SOURCE_FOLDER/"*    "$CONFIG_OUT_PATH/src/$SOURCE_FOLDER/"
  246      done

  277    do
  278:     cp -Rf "$src/$SCRIPTJS"             "$dst/"
  279:     cp -Rf "$src/$SCRIPTJS.map"         "$dst/"
  280    done

web\ci.sh:
  113  
  114:   cp -Rf build/app/web/release/* "$BASE_PUBLISH_FOLDER"
  115:   cp -Rf build/app/ui/release/* "$BASE_PUBLISH_FOLDER"
  116  

web\src\test\manual\embed\android-harness\build.sh:
  13  mkdir -p "$THIS_DIR/host"
  14: cp -R "$KEYMAN_ROOT/android/KMEA/app/src/main/assets/"* "$THIS_DIR/host/"
  15  cp "$KEYMAN_ROOT/web/build/app/embed/debug/keyman.js" "$THIS_DIR/host/keymanandroid.js"
```

Now verifying that these are also okay. I don't know if we have other potential GNU vs BSD inconsistencies in our scripts though. I am assuming that it's probably only a concern for `ios/` and `mac/` because our other projects are already building well on multiple platforms.

**Comment by mcdurdin** [comment]
Went with `/bin/cp` to ensure we always use mac cp regardless of path. Kinda sucky but safe. Only on mac-specific scripts.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_INSTALLER (PASSED):** Tested with the attached PR build (Keyman 17.0.84) in both mac Mini Ventura OS (Native Machine) and mac Mojave (VM) and here is my observation: 1. Able to install the attached Keyman build without having any problem. Seems to be working fine in macOS. 

..mac Ventura OS

   


..mac Mojave OS (VM)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.84-alpha](https://keyman.com/downloads/releases/alpha/17.0.84)

**Comment by mcdurdin** [comment]
> I guess if we go this way, we'll need to cherry-pick this to stable-16.0. Not sure I am happy with this solution!

Yeah, I forgot to do this at the time, meaning we released a broken 16.0.140 update. See #9332. My bad.
