### PR TITLE
fix(linux): Fix version comparison

### LINKED ISSUE #9593: bug(linux): Fix version comparison in `keymanutil.c`
`keymanutil.c` contains at least one comparison of versions. This currently uses string comparison which doesn't work very well for version numbers, e.g. `1.9` and `1.10`.

One scenario where a user would notice this, is if he has version 1.9 of a keyboard installed in the shared area. He then installs version 1.10 (which adds language X) into the user area. Until this bug is fixed the keyboard won't show up as keyboard for X.

### PR DESCRIPTION
**Pull request by ermshiperete**
Implement proper comparison of versions so that 1.10 is newer than 1.9.

Fixes #9593.

@keymanapp-test-bot skip

### CODE REVIEW

File: linux/ibus-keyman/src/keymanutil.c [hunk 1]
```diff
@@ -212,6 +212,30 @@ get_engine_for_language(
...
+        j++;
+      }
+
+      if (version1 < version2)
+        return -1;
+      if (version1 > version2)
+        return +1;
+    }
+  return 0;
+}
```
Comment (mcdurdin) [inline linux/ibus-keyman/src/keymanutil.c:237]: This looks okay. But it might be cleaner to do it with pointers:

```suggestion
int
keyman_compare_version(const gchar *ver1, const gchar *ver2) {
  for (; *ver1 || *ver2; ) {
    int version1 = 0, version2 = 0;

    while (*ver1 && *ver1 != '.') {
      assert(*ver1 >= '0' && *ver1 <= '9');
      version1 = version1 * 10 + (*ver1 - '0');
      ver1++;
    }
    while (*ver2 && *ver2 != '.') {
      assert(*ver2 >= '0' && *ver2 <= '9');
      version2 = version2 * 10 + (*ver2 - '0');
      ver2++;
    }

    if (version1 < version2)
      return -1;
    if (version1 > version2)
      return +1;
    if(*ver1) 
      ver1++;
    if(*ver2)
      ver2++;
  }
  return 0;
}
```

**Review by mcdurdin — APPROVED** [review]

File: linux/ibus-keyman/src/keymanutil.c (hunk 1 above)
Comment (ermshiperete) [reply linux/ibus-keyman/src/keymanutil.c:237]: Done. Also added a few more tests.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.259-alpha](https://keyman.com/downloads/releases/alpha/17.0.259)
