### PR TITLE
fix(android): check index validity in getCurrentKeyboardInfo

### LINKED ISSUE #6703: bug(android): getKeyboardInfo with invalid index: -1
Sentry Issue: [KEYMAN-ANDROID-75](https://sentry.io/organizations/keyman/issues/2720587980/?referrer=github_integration)

```
getKeyboardInfo with invalid index: -1

    at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
    at java.lang.Thread.getStackTrace(Thread.java:1736)
    at com.tavultesoft.kmea.util.KMLog.LogError(KMLog.java:39)
    at com.tavultesoft.kmea.data.KeyboardController.getKeyboardInfo(KeyboardController.java:170)
    at com.tavultesoft.kmea.KMManager.getCurrentKeyboardInfo(KMManager.java:1747)
    at com.keyman.android.SystemKeyboard.onStartInput(SystemKeyboard.java:142)
    at android.inputmethodservice.InputMethodService.doStartInput(InputMethodService.java:2433)
    at android.inputmethodservice.InputMethodService$InputMethodImpl.startInput(InputMethodService.java:652)
    at android.inputmethodservice.InputMethodService$InputMethodImpl.dispatchStartInputWithToken(InputMethodService.java:688)
    at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:199)
    at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:257)
    at android.app.ActivityThread.main(ActivityThread.java:8192)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #6703.

This issue was first reported in 14.0.282-stable. I have done a careful review of changes in 14.0.282 (and 14.0.281) but have been unable to find any changes that could have bearing on this.

The basic issue is that there appears to be some circumstances where `KMManager` thinks that it has a keyboard loaded (ref `SystemKeyboardLoaded` variable), but `KMKeyboard.currentKeyboard` is still `null`.

The crash has been reported for only a very small set of users, 119 at time of fix, but average reports per user is over 100. As is usual with this type of thing, a small fraction of those users are reporting the majority of crashes. I have not found any real commonality across the error reports -- they are geographically dispersed, across multiple device types and Android versions.

Note that this addresses the error at hand but as I am unable to reproduce the issue, does not necessarily address the root problem, so there may still be other issues reported even after this is fixed.

A longer-term refactor would eliminate `SystemKeyboardLoaded` because from what I can tell, we should always be able to determine that from the state of `KMKeyboard.currentKeyboard`. However, the state entanglement is a lot deeper than just those two variables, with cross references to keyboard indexes between `KMManager` and `KMKeyboard` which need to be resolved (`KMKeyboard` should *never* refer to `KMManager`).

# User Testing

* TEST_BASIC: Run through a basic usage test of Keyman for Android, both in-app and system keyboards, verifying that you can switch keyboards, lock and unlock your device, switch between Keyman and other input methods, and install and use Keyman keyboards without errors.

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java [hunk 1]
```diff
@@ -1999,6 +1999,9 @@ public static int getCurrentKeyboardIndex(Context context) {
 
   public static Keyboard getCurrentKeyboardInfo(Context context) {
     int index = getCurrentKeyboardIndex(context);
+    if(index < 0) {
+      return null;
+    }
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java:2004]: This is the primary fix. I audited all calls to `getCurrentKeyboardInfo`, and where a `null` result was not tested, fixed that as well.

**Review by jahorton — CHANGES_REQUESTED** [review]
After further investigation of the underlying issue, I believe I've identified the root issue, which has user-privacy implications.  As such, I recommend abandoning this PR in favor of #6726.

**Comment by mcdurdin** [comment]
The following errors were captured in Sentry relating to this build:

* `Uncaught TypeError: Cannot read properties of null (reading 'layout')`: [**KEYMAN-WEB-21**](https://sentry.io/share/issue/5a6f963e165c41188b93cbbc55be77fe/) (cascades to "Error in keyboard sil_euro_latin:sil_euro_latin for language")
* `Uncaught TypeError: Cannot set properties of null (setting 'variableStores')` [**KEYMAN-WEB-1P**](https://sentry.io/share/issue/d97aa05bf68648c6bf84d726f3e2458e/)

Note that Sentry has merged the error reports into [**KEYMAN-ANDROID-SD**](https://sentry.io/share/issue/f3855c76629d45eeb8f498770af88ba4/) on the Android side, though they are different source errors.

However, neither of these errors are new to this build. A similar error to KEYMAN-WEB-21 was first seen in [14.0.291](https://sentry.io/organizations/keyman/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=Uncaught+TypeError%3A+Cannot+read+properties+of+null+%28reading+%27layout%27%29&project=5983520&query=issue.id%3A3063173397+reading+%27layout%27+release%3Arelease-14.0.291&sort=-timestamp&statsPeriod=90d&widths=593&widths=198&yAxis=count%28%29). KEYMAN-WEB-1P is rare but was seen, once, in [15.0.206-beta](https://sentry.io/organizations/keyman/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=TypeError%3A+Cannot+set+properties+of+null+%28setting+%27variableStores%27%29&project=5983524&query=issue.id%3A3096408350+release%3Arelease-15.0.206-beta&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29).

## KEYMAN-WEB-21 call stack

```
TypeError: Cannot read properties of null (reading 'layout')
  at InputProcessor.buildAlternates(/keyman.js:17520:68)
  at InputProcessor.processKeyEvent(/keyman.js:17438:47)
  at Function.PreProcessor.handleClick(/keyman.js:26868:48)
  at Function.PreProcessor.raiseKeyEvent(/keyman.js:26848:51)
  at VisualKeyboard.modelKeyClick(/keyman.js:29470:38)
  at VisualKeyboard.touch(/keyman.js:29188:38)
  at TouchEventEngine.InputEventEngine.onInputStart(/keyman.js:28411:37)
  at TouchEventEngine.onTouchStart(/keyman.js:28499:26)
```

## KEYMAN-WEB-1P call stack

```
TypeError: Cannot set properties of null (setting 'variableStores')
  at KeyboardInterface.applyVariableStores(/keyman.js:6124:56)
  at RuleBehavior.finalize(/keyman.js:3491:49)
  at RuleBehavior.keyman_6.text.RuleBehavior.finalize(/keyman.js:20076:46)
  at InputProcessor.processKeyEvent(/keyman.js:17441:38)
  at Function.PreProcessor.handleClick(/keyman.js:26868:48)
  at Function.PreProcessor.raiseKeyEvent(/keyman.js:26848:51)
  at VisualKeyboard.modelKeyClick(/keyman.js:29470:38)
  at VisualKeyboard.release(/keyman.js:29260:34)
  at TouchEventEngine.InputEventEngine.onInputEnd(/keyman.js:28426:37)
  at TouchEventEngine.onTouchEnd(/keyman.js:28512:26)
```

Both these errors seem to be appearing only in Keyman for Android. @jahorton any thoughts?

**Comment by jahorton** [comment]
My first thought:  well, I have seen flashes of errors before in Chrome debugging for DOM-Web when refreshing a test page.  (Especially if I didn't bother to 'resume' from a debugging session.)  Chrome... doesn't exactly care to wait on the JS engine to finish whatever it's doing and sync up.  The first two screenshots above sound like they line up with this; the JS engine emitted errors that occurred _because of_ the keyboard swap.

Whenever I saw it when working with DOM-Web, my impression was that it was as if the previous page's instance of the code were still running, but with the new page's state.  It would only ever generate one `console.error`-like message when this occurred.  Of course, if our old "reset the keyboard on an error" code is in place... all it takes is one such message.

The above does assume that swapping was done via the modal picker.  The newer quick-swap via globe key tap actually doesn't reload the page, while the big, formal picker does result in a page reload.

That third screenshot is obviously more concerning.

**Comment by jahorton** [comment]
> The first two screenshots above sound like they line up with this; the JS engine likely emitted errors that occurred _because of_ the keyboard swap.

To elaborate on this... suppose for a second that DOM-based JS could actually run multithreaded.  (We know it can't, but just play along for a moment.)

* With a loaded keyboard, tap the globe key to swap the keyboard.
* There will be a brief time window where the OSK for the old keyboard is still visible and interactive.
* Tap a key on that keyboard.

So now we have both:

1.  a keyboard swap, during which there will be a window of time where there is no active keyboard.
2. an active touch event, which depends on an active keyboard for processing.

If both actually could run simultaneously, we have an obvious race condition.

Here's the thing, though - page navigation events in Chrome, in my experience, appear to be able to cause an effect like point 1 above.  Assuming my interpretation is correct... while Chrome is doing its DOM-handling that effects a state like point 1, the JS engine's processing thread can reach point 2... and we get an effect that looks like an impossible race condition in JS.

**Review by jahorton — APPROVED** [review]
Right, forgot to approve this once I closed my alternative.  Apologies on that.

**Comment by MakaraSok** [comment]
* **TEST_BASIC (PASSED):**

Keyman for Android `v15.0.258` was installed on Android 10 of a physical device `Galaxy S9+`. Keyman is shown to be working without any issue in-app and as a system keyboard.
- keyboards can be installed and uninstalled without errors.
- keyboards can be switched to and fro in-app and a system keyboard without any obvious errors.
- the device can be locked and unlocked without any obvious issues either.

The tests have been done on an emulator running Android 11.0 and no error is found.
