### PR TITLE
fix(web): locks page scroll when scrolling lang menu

### LINKED ISSUE #7637: bug(web): `languageMenu.touch*` should be passive
### Describe the bug

The `touch*` events on the language menu call `preventDefault()` but this is probably not necessary, as AFAICT there is no default behaviour that we need to be blocking (the elements are `<div>`s and `<p>`s).

When scrolling is happening, we get a error:

```
languageMenu.ts:448 [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
  c @ languageMenu.ts:448
  sentryWrapped @ helpers.ts:87
```

When constructing the menu, we get a cascade of (often thousands of) warnings:

```
trycatch.ts:185 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
  (anonymous) @ trycatch.ts:185
  (anonymous) @ instrument.ts:421
  e.addKeyboard @ languageMenu.ts:489
  k @ languageMenu.ts:365
  e.addLanguages @ languageMenu.ts:315
  e.show @ languageMenu.ts:115
  b.showLanguageMenu @ oskView.ts:989
  e.optionKey @ visualKeyboard.ts:1675
  e.handleClick @ preProcessor.ts:62
  e.raiseKeyEvent @ preProcessor.ts:44
  e.modelKeyClick @ visualKeyboard.ts:980
  (anonymous) @ visualKeyboard.ts:620
  sentryWrapped @ helpers.ts:87
```

More information: https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

### Reproduce the bug

_No response_

### Expected behavior

_No response_

### Related issues

_No response_

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [X] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.97-beta

### Operating system

_No response_

### Device

_No response_

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

I was testing in Chrome with mobile emulation

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #7637.  

Also mitigates (if not fixes) the underlying issue that the related code sought to address - the fact that sometimes, scrolling the language menu would scroll the full _page_ instead.  Sometimes in short bursts, sometimes persistently until the end of the active touch interaction.

As best as I can tell, the unwanted page scrolling is due to some unwanted cross-effects with default browser behavior while interacting with the language list and its use of `overflow-y` styling.  We definitely want this styling - that's what gives us the scrolling language/keyboard list, after all.  This matters greatly when using keymanweb.com on touch devices, which would result in a _massive_ set of entries, and scrolling is important.  

Unfortunately, I can't see a way to prevent the browser from deciding to scroll the page by default without styling adjustments; the event goes uncancelable at the exact moment we would _want_ to cancel default behavior.  That is, related touch events become uncancelable once the page itself begins to scroll - at the first opportunity we have to detect and thus react to the page scrolling when not desired.

If a better preventative measure could be identified, I'd love to go with that instead... but this approach seems to do "well enough" to prevent unwanted side effects for now.  We simply change a bit of the full page's styling momentarily and make sure to restore it once the corresponding touch interaction ends.

## User Testing

**TEST_PAGE_SCROLL_LOCK**: Verify that the testing page does not scroll while scrolling the keyboard-selection menu for KMW's touch OSK.

1. Using Chrome mobile-device emulation (Pixel 5 or iPhone SE mode)...
2. Load the "Test unminified Keymanweb" Web testing page.
3. Click the "Type here" text area to display the touch OSK.
4. Use the globe key to activate the keyboard menu.
5. Do the following as one continuous touch.  If the page itself scrolls at any point _but_ the final step, _**FAIL**_ this test.
    1. Begin a touch on one of the language options in the menu.
    2. Move the touchpoint horizontally over the alphabetical bar / "menu index" on the right-hand side of the menu; stay inside that bar.
    3. Move the touchpoint upward rapidly, past the top of the language menu.
    5. Move the touchpoint up and down repeatedly, as if trying to make the page bounce up and down.
    6. Move the touchpoint back down into the list of languages and attempt to scroll it again, this time staying within the area displaying selectable languages.
        - While not ideal, the expected behavior is that the list will not scroll.
        - If the list scrolls at this point in the emulated touch-drag sequence, return to step 5 and try again until this expectation is met.
    7. Release the touchpoint.  (Do _**not**_ fail the test if the page scrolls a slight bit on _this_ step.  If there's a big jump, though - that's fail-worthy.)
6. Perform a touch and drag on the main body of the page, verifying that the page may scroll normally.

This test sequence simply uses the most reliable reproduction that I've found for the page-scroll issue.  It's not the only way it can happen, or even the simplest.  Just the simplest way I know that is also reliable.

### CODE REVIEW

File: web/source/osk/languageMenu.ts [hunk 1]
```diff
@@ -405,22 +409,38 @@ namespace com.keyman.osk {
...
+
+        // Must be separate line from previous due to TS type inference stuff.
+        const obs = languageMenu.originalBodyStyle;
+        const dbs = document.body.style;
+        obs.overflowY = dbs.overflowY;
+        obs.height = dbs.height;
+
+        // Now that the properties we're going to overwrite have been cached...
+        dbs.overflowY = 'hidden';
+        dbs.height = '100%';
```
Comment (mcdurdin) [inline web/source/osk/languageMenu.ts:437]: Can we factor this into a separate function alongside `restoreBodyStyle()`?

Perhaps we can call them `stopBodyScroll()` and `restoreBodyScroll()`. And please also add a link to the issue in the comment for the functions.

**Review by mcdurdin — APPROVED** [review]
I hear you on feeling a bit uncomfortable with the solution. It feels a bit like a big, imprecise hammer for a local issue. But I don't see a better way forward.

The linked SO post also applies these styles to the `html` element. Did you find that wasn't necessary?

I note also this may have limitations for webpages which have scrolling sub-elements.

So LGTM I guess?

**Comment by mcdurdin** [comment]
I note the build is failing with:

```
FAILED
Error: Uncaught Error: Keyboard Keyboard_test_chirality does not have a layer with id leftctrl (http://localhost:9876/source/keymanweb.js:24225)
    at BrowserDriver.simulateHardwareEvent (base/web/tools/recorder/build/index.js?03d4548876df4a413bd80f3386907ec67ac1fe7c:720:25)
    at BrowserDriver.simulateEvent (base/web/tools/recorder/build/index.js?03d4548876df4a413bd80f3386907ec67ac1fe7c:705:26)
    at BrowserDriver.simulateSequence (base/web/tools/recorder/build/index.js?03d4548876df4a413bd80f3386907ec67ac1fe7c:759:22)
    at BrowserProctor.simulateSequence (base/web/tools/recorder/build/index.js?03d4548876df4a413bd80f3386907ec67ac1fe7c:1083:31)
    at TestSequence.test (base/web/tools/recorder/build/index.js?03d4548876df4a413bd80f3386907ec67ac1fe7c:227:34)
    at RecordedSequenceTestSet.test (base/web/tools/recorder/build/index.js?03d4548876df4a413bd80f3386907ec67ac1fe7c:556:44)
    at KeyboardTest.test (base/web/tools/recorder/build/index.js?03d4548876df4a413bd80f3386907ec67ac1fe7c:654:48)
    at runLoadedKeyboardTest (base/web/unit_tests/test_utils.js?9834e74182af3b6e4a3dee028bb8682edd972507:167:11)
    at http://localhost:9876/base/web/unit_tests/test_utils.js?9834e74182af3b6e4a3dee028bb8682edd972507:176:5
```

I reran the build but the error persisted.

File: web/source/osk/languageMenu.ts [hunk 2]
```diff
@@ -411,23 +411,17 @@ namespace com.keyman.osk {
...
-        e.stopPropagation();
-        if(this.className.indexOf('selected') <= 0) {
-          this.className=this.className+' selected';
-        }
-        languageMenu.scrolling=false;
-        languageMenu.y0=e.touches[0].pageY;//osk.lgList.childNodes[0].scrollTop;
-
+      // Refer to https://github.com/keymanapp/keyman/pull/7790 for context on
+      // the following two methods.
+      const lockBodyScroll = () => {
```
Comment (mcdurdin) [inline web/source/osk/languageMenu.ts:416]: I think I'd like to make these two functions more robust by ensuring that repeated calls don't lead to broken behaviour -- as it stands, if you called `lockBodyScroll` twice before `unlockBodyScroll`, it would then never be able to unlock :grin:

I don't think this can happen at present, but it's good for code durability in the long run.

**Review by mcdurdin — CHANGES_REQUESTED** [review]

File: web/source/osk/languageMenu.ts [hunk 3]
```diff
@@ -433,12 +439,22 @@ namespace com.keyman.osk {
       }
 
       const unlockBodyScroll = () => {
+        if(!this.originalBodyStyle) {
+          // We shouldn't be able to reach here, but in case things go out-of-order due
+          // to some unforeseen circumstance, let's null-guard here.
+          return;
```
Comment (mcdurdin) [inline web/source/osk/languageMenu.ts:445]: Should we console.error this so we can track it on Sentry, given we don't currently expect this to happen?

File: web/source/osk/languageMenu.ts [hunk 4]
```diff
@@ -414,6 +414,12 @@ namespace com.keyman.osk {
       // Refer to https://github.com/keymanapp/keyman/pull/7790 for context on
       // the following two methods.
       const lockBodyScroll = () => {
+        // If this object still exists, we never ran our paired `unlock` method;
+        // preserve the original state so that we can still restore it later!
+        if(this.originalBodyStyle) {
+          return;
```
Comment (mcdurdin) [inline web/source/osk/languageMenu.ts:420]: Should we do a console.error here given this is not supposed to happen?

**Review by mcdurdin — APPROVED** [review]

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_PAGE_SCROLL_LOCK (PASSED):** Tested in the "Test unminified Keymanweb" Web testing page and here is my observation: 1. Opened it in chrome mobile-device emulation. 2. Clicked the globe key. 3. Able to move the touchpoint up and down repteadly and noticed that the page bouncedup and down. 4. Able to move the touchpoint upward rapidly, inside the language menu. 5. Able to move the touchpoint back down into the list of languages and tried to scroll it again. This time it is staying within the area displaying selectable languages. 6. In the main body of the page, I was able to scroll the page up and down without having any problem.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.114-beta](https://keyman.com/downloads/releases/beta/16.0.114)
