### PR TITLE
change(web): rotation polish - OSK reload no longer needed 🍒

### LINKED ISSUE #7169: bug(android): At start of input, pressing globe key, going back, leads to stuck shift key
**Describe the bug**

From a team review of the Keyman for Android UX (#7161)

When I was at start-of-sentence, I pressed globe key, went back, then keyboard was lower case, predictions showed Title Case, but the Shift key did not work -- the shift layer would not be activated.

https://user-images.githubusercontent.com/4498365/187527077-d54b68c1-3486-43ea-a253-89417f527700.mp4

Also documented at https://community.software.sil.org/t/locked-on-one-layer-or-dancing-between-two-layers/6446

Note:
* repro on 15.0.268-stable, 16.0.37-alpha. also repro on 15.0.269.
* per @jahorton: Does not appear to repro in iOS, though I only tried the once.  (Multiple kbds installed, 15.0.268-stable)

---

**Keyman for Windows/macOS/Linux/iPhone/iPad/Android:**
 - Device:             Samsung A90 5G 
 - OS:                 Android 12 
 - Keyman version:     15.0.269-stable

### PR DESCRIPTION
**Pull request by darcywong00**
:cherries: pick of #6787 and #6979 and fixes #7169 to stable-15.0 (16.0 master already contains the fix)

# User Testing

## Test environments

- GROUP_IOS - any iOS device should suffice
- GROUP_ANDROID - any Android device should suffice

## Tests

- **TEST_INAPP_ROTATE_P-TO-L**:

  1. With Keyman not active, load it in a portrait orientation.
  2. Once loaded, rotate the device to a landscape orientation.
      - The test "passes" if the OSK rotates properly.

- **TEST_INAPP_ROTATE_L-TO-P**:

  1. With Keyman not active, load it in a landscape orientation.
  2. Once loaded, rotate the device to a portrait orientation.
      - The test "passes" if the OSK rotates properly.

- **TEST_BROWSER_ROTATE_P-TO-L**:

  1. Before loading the test page, have the device in a portrait orientation.
  2. Load the KeymanWeb testing page "Test unminified Keymanweb".
  3. Select the top text area in order to display the OSK.
  4. Open the language menu, but do not change keyboards.
  5. Once loaded, rotate the device to a landscape orientation.
      - The test "passes" if the OSK rotates properly.
      - The test "fails" if the OSK is not visible after rotation.

- **TEST_BROWSER_ROTATE_L-TO-P**:

  1. Before loading the test page, have the device in a landscape orientation.
  2. Load the KeymanWeb testing page "Test unminified Keymanweb".
  3. Select the top text area in order to display the OSK.
  4. Open the language menu, but do not change keyboards.
  5. Once loaded, rotate the device to a portrait orientation.
      - The test "passes" if the OSK rotates properly.
      - The test "fails" if the OSK is not visible after rotation.

- **TEST_ANDROID_SHIFT_AFTER_GLOBE**: Verifies fix to #7169

  1. Load the PR build of Keyman for Android
  2. In the Keyman app with the default sil_euro_latin keyboard, the keyboard should be at start-of-sentence
  3. Verify the OSK starts in the Shift layer (note, suggestions may appear in lowercase)
  4. Press the globe key, then exit the Keyboard picker menu
  5. Verify the OSK is still in the Shift layer
  6. Press the <kbd>Shift</kbd> button and verify the OSK switches to the default layer

-------------------
(edit) Additional user tests from #6979

SUITE_ROTATION

## Test environments

- GROUP_IOS_PHONE - any modern iOS phone should suffice
- GROUP_IOS_TABLET - any modern iOS tablet should suffice
- GROUP_OLD_IOS - try to find an iOS 12 or iOS 13 device to test with
- GROUP_ANDROID_PHONE - any modern Android phone should suffice
- GROUP_ANDROID_TABLET - any modern Android tablet should suffice
- GROUP_ANDROID_7 - run tests against early Android if possible (Android 7.0)

## Tests

- **TEST_OSK_PORTRAIT_LOAD**:

  1. Before loading the test page, have the device in a portrait orientation.
  2. Load the KeymanWeb testing page "Test unminified Keymanweb".
  3. Select the top text area in order to display the OSK.
  4. Report on the appearance of the OSK.  Does it seem reasonably positioned and sized?  No cropping issues?

- **TEST_OSK_LANDSCAPE_LOAD**:

  1. Before loading the test page, have the device in a landscape orientation.
  2. Load the KeymanWeb testing page "Test unminified Keymanweb".
  3. Select the top text area in order to display the OSK.
  4. Report on the appearance of the OSK.  Does it seem reasonably positioned and sized?  No cropping issues?

- **TEST_BROWSER_ROTATE_P-TO-L**:

  1. Before loading the test page, have the device in a portrait orientation.
  2. Load the KeymanWeb testing page "Test unminified Keymanweb".
  3. Select the top text area in order to display the OSK.
  4. Open the language menu, but do not change keyboards.
  5. Once loaded, rotate the device to a landscape orientation.
      - The test "passes" if the OSK rotates properly.
      - The test "fails" if the OSK is not visible after rotation.

- **TEST_BROWSER_ROTATE_L-TO-P**:

  1. Before loading the test page, have the device in a landscape orientation.
  2. Load the KeymanWeb testing page "Test unminified Keymanweb".
  3. Select the top text area in order to display the OSK.
  4. Open the language menu, but do not change keyboards.
  6. Once loaded, rotate the device to a portrait orientation.
      - The test "passes" if the OSK rotates properly.
      - The test "fails" if the OSK is not visible after rotation.

### CODE REVIEW

File: web/source/osk/anchoredOskView.ts [hunk 1]
```diff
@@ -59,13 +61,37 @@ namespace com.keyman.osk {
       s.position = 'fixed';
     }
 
-    protected postKeyboardLoad() {
-      // Initializes the size of a touch keyboard.
+    public refreshLayout(pending?: boolean): void {
```
Comment (jahorton) [inline web/source/osk/anchoredOskView.ts:64]: The main difference is that I see we didn't 🍒 the @override annotation; this is reflected by three less added lines in the lines-changed count.

There's also a dropped newline at line 70 compared to the original - that's the one additional line-change difference of note.  The rest seems to match.

**Review by jahorton — APPROVED** [review]
LGTM.

**Comment by bharanidharanj** [comment]
### GROUP_IOS: - any iOS device should suffice

* **TEST_INAPP_ROTATE_P-TO-L (PASSED):** Tested this with the attach PR build (15.0.270-test-7188) in iOS 15.5 / iPhone 13 Pro max simulator and the OSK rotates properly. 
* **TEST_INAPP_ROTATE_L-TO-P (PASSED):** Tested this with the attach PR build (15.0.270-test-7188) in iOS 15.5 / iPhone 13 Pro max simulator and the OSK rotates properly. 
* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested this with the attach PR build (15.0.270-test-7188) in iOS 15.5 / iPhone 13 Pro max simulator and the OSK rotates properly. 
* **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested this with the attach PR build (15.0.270-test-7188) in iOS 15.5 / iPhone 13 Pro max simulator and the OSK appears partially on the Screen. 
   
* **TEST_ANDROID_SHIFT_AFTER_GLOBE (PASSED):** Tested this with the attach PR build (15.0.270-test-7188) in iOS 15.5 / iPhone 13 Pro max simulator and verified that the OSK switches to the default layer.

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID: - any Android device should suffice

* **TEST_INAPP_ROTATE_P-TO-L (PASSED):** Tested this with the attached PR build (Keyman 15.0.270-test-7188) in my Android Mobile device Version 11.0 and verified that the OSK rotates properly. 
* **TEST_INAPP_ROTATE_L-TO-P (PASSED):** Tested this with the attached PR build (Keyman 15.0.270-test-7188) in my Android Mobile device Version 11.0 and verified that the OSK rotates properly. 
* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested this with the attached PR build (Keyman 15.0.270-test-7188) in my Android Mobile device Version 11.0 and verified that the OSK rotates properly. 
* **TEST_BROWSER_ROTATE_L-TO-P (PASSED):** Tested this with the attached PR build (Keyman 15.0.270-test-7188) in my Android Mobile device Version 11.0 and verified that the OSK rotates properly. 
* **TEST_ANDROID_SHIFT_AFTER_GLOBE (PASSED):** Tested this with the attached PR build (Keyman 15.0.270-test-7188) in my Android Mobile device Version 11.0 and verified that the OSK switches to the default layer.

**Comment by mcdurdin** [comment]
> * **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested this with the attach PR build (15.0.270-test-7188) in iOS 15.5 / iPhone 13 Pro max simulator and the OSK appears partially on the Screen.

@jahorton and @darcywong00 can you review this issue?

**Comment by jahorton** [comment]
> > * **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested this with the attach PR build (15.0.270-test-7188) in iOS 15.5 / iPhone 13 Pro max simulator and the OSK appears partially on the Screen.
> 
> @jahorton and @darcywong00 can you review this issue?

I am able to reproduce the test failure on my personal iPhone, though not in Chrome emulation.

For comparison, and to ensure that it isn't broken on `master`, I double-checked on the same device using the test build product from #7142, which includes the already-merged 16.0-alpha version of these changes.  (I double-checked _that_ aspect - that the changes are there - as well.)

This test result _does not reproduce_ on 16.0-alpha; somehow, there's... _something_ different that's specific to 15.0-stable.  What "something"?  Good question!  That'll take time to investigate.

**Comment by jahorton** [comment]
Well, _that's_ probably related:  we should probably cherry-pick the "patch PR" followup as part of this, too.  See #6979.

The original version had similarly-noted test issues, but since it'd already undergone significant review at the time, I made a "patch PR" that could be reviewed separately, in case reviewers didn't like the "patch" changes.

**Review by jahorton — CHANGES_REQUESTED** [review]
Oh, right.  Noting my prior comment, I'm requesting that the changes from #6979 be included in this 🍒-pick, as that should address the failed unit test.

**Review by jahorton — APPROVED** [review]

**Comment by darcywong00** [comment]
With the changes from #6979 now :cherries:-picked, 

@keymanapp-test-bot retest GROUP_IOS TEST_BROWSER_ROTATE_L-TO-P

**Comment by bharanidharanj** [comment]
### GROUP_IOS: - any iOS device should suffice

* **TEST_BROWSER_ROTATE_L-TO-P (OPEN):** notes

## SUITE_ROTATION: 

### GROUP_IOS_PHONE: - any modern iOS phone should suffice

* **TEST_OSK_PORTRAIT_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPhone 14 Pro max simulator and the OSK rotates properly.

   


* **TEST_OSK_LANDSCAPE_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPhone 14 Pro max simulator and the OSK rotates properly.

   


* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPhone 14 Pro max simulator and the OSK rotates properly.

   


* **TEST_BROWSER_ROTATE_L-TO-P (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPhone 14 Pro max simulator and the OSK rotates properly.

**Comment by bharanidharanj** [comment]
## SUITE_ROTATION: 

### GROUP_IOS_TABLET: - any modern iOS tablet should suffice

* **TEST_OSK_PORTRAIT_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPad Pro 3 generation simulator and the OSK rotates properly.

   


* **TEST_OSK_LANDSCAPE_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPad Pro 3 generation simulator and the OSK rotates properly.

   



* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPad Pro 3 generation simulator and the OSK rotates properly.


   



* **TEST_BROWSER_ROTATE_L-TO-P (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPad Pro 3 generation simulator and the OSK rotates properly.

**Comment by bharanidharanj** [comment]
### GROUP_IOS: - any iOS device should suffice

* **TEST_BROWSER_ROTATE_L-TO-P (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 15.0 / iPhone 13 Pro Simulator and the OSK rotates properly.

**Comment by bharanidharanj** [comment]
## SUITE_ROTATION: 

### GROUP_OLD_IOS: - try to find an iOS 12 or iOS 13 device to test with

* **TEST_OSK_PORTRAIT_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 12.4 / iPhone 7 Simulator and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues. 


   

* **TEST_OSK_LANDSCAPE_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 12.4 / iPhone 7 Simulator and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues. 

   


* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 12.4 / iPhone 7 Simulator and the OSK rotates properly. 

   


* **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 12.4 / iPhone 7 Simulator and I noticed that the OSK flashes on the screen and it does not appear on the View.

**Comment by darcywong00** [comment]
@bharanidharanj 
TEST_BROWSER_ROTATE_L-TO-P  should have rotated from landscape to portrait orientation, and the screenshot looks like it's still landscape. Are you saying the OSK failed to display in the original landscape orientation?

See the [screenshot](https://user-images.githubusercontent.com/19683143/182170252-9e17fe5d-d8a7-44cf-8e28-17dfc235191b.png) from the original PR

**Comment by bharanidharanj** [comment]
## SUITE_ROTATION: 

### GROUP_ANDROID_PHONE: - any modern Android phone should suffice

* **TEST_OSK_PORTRAIT_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in my Android Mobile device Version 11.0 and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues.

   


* **TEST_OSK_LANDSCAPE_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in my Android Mobile device Version 11.0 and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues.

   


* **TEST_BROWSER_ROTATE_P-TO-L (FAILED):** Tested this with the attach PR build (15.0.271-test-7188) in my Android Mobile device Version 11.0 and I noticed that the Inconsistent behavior of the OSK. ie., the OSK sometimes appear on the screen and sometimes it does not appear after rotating it from Portrait to Landscape. Seems to be an issue.

   

* **TEST_BROWSER_ROTATE_L-TO-P (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in my Android Mobile device Version 11.0 and the OSK rotates properly.

**Comment by bharanidharanj** [comment]
## SUITE_ROTATION: 

### GROUP_ANDROID_TABLET: - any modern Android tablet should suffice

* **TEST_OSK_PORTRAIT_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in Pixel C API 31 / Android 12.0 and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues.

   


* **TEST_OSK_LANDSCAPE_LOAD (PASSED):**  Tested this with the attach PR build (15.0.271-test-7188) in Pixel C API 31 / Android 12.0 and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues.

   

* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in Pixel C API 31 / Android 12.0 and verified the appearance of the OSK and it rotates properly.

   


* **TEST_BROWSER_ROTATE_L-TO-P (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in Pixel C API 31 / Android 12.0 and verified the appearance of the OSK and it rotates properly.

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID_7: - run tests against early Android if possible (Android 7.0)

* **TEST_OSK_PORTRAIT_LOAD (PASSED):**  Tested this with the attach PR build (15.0.271-test-7188) in API 24 / Android 7.0 emulator and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues.




* **TEST_OSK_LANDSCAPE_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in API 24 / Android 7.0 emulator and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues.

   


* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in API 24 / Android 7.0 emulator and verified the appearance of the OSK and it rotates properly.

    


* **TEST_BROWSER_ROTATE_L-TO-P (PASSED):**  Tested this with the attach PR build (15.0.271-test-7188) in API 24 / Android 7.0 emulator and verified the appearance of the OSK and it rotates properly.

**Comment by bharanidharanj** [comment]
> @bharanidharanj TEST_BROWSER_ROTATE_L-TO-P should have rotated from landscape to portrait orientation, and the screenshot looks like it's still landscape. Are you saying the OSK failed to display in the original landscape orientation?
> 
> See the [screenshot](https://user-images.githubusercontent.com/19683143/182170252-9e17fe5d-d8a7-44cf-8e28-17dfc235191b.png) from the original PR

@darcywong00 The attached Screenshot looks like it's in Portrait orientation. (from Landscape). Actually, I am confused which emulator you are asking about. 

When I tested 15.0.270-test-7188 in iOS 15.5 / iPhone 13 Pro Max Simulator, after rotating the device from Landscape to Portrait, the OSK appears partially on the Screen. (Please, see my attached Screenshot) [screenshot](https://user-images.githubusercontent.com/19683143/191295429-e9a8bcef-596f-42f7-b2ed-2c192c68b498.png)

When I tested the same (TEST_BROWSER_ROTATE_P-TO-L) in iOS 12.4 / iPhone 7 Simulator, the OSK is failed to display in the original landscape orientation. (Please, see the attached Screenshot) [screenshot](https://user-images.githubusercontent.com/19683143/191295776-2a72f91c-48b3-4b26-bd69-2ff6d6c2878d.png)

Please, let me know if further clarification is needed. Thanks.

**Comment by darcywong00** [comment]
@bharanidharanj 
I was asking about your test result from here:

> * **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 12.4 / iPhone 7 Simulator and I noticed that the OSK flashes on the screen and it does not appear on the View. 
>
>    

Are you saying the OSK flashed and disappeared **before** rotating from landscape to portrait orientation?

@jahorton - is the browser OSK expected to intermittently disappear?

**Comment by bharanidharanj** [comment]
> @bharanidharanj I was asking about your test result from here:
> 
> > * **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 12.4 / iPhone 7 Simulator and I noticed that the OSK flashes on the screen and it does not appear on the View.
> >    
> 
> Are you saying the OSK flashed and disappeared **before** rotating from landscape to portrait orientation?
> 
> @jahorton - is the browser OSK expected to intermittently disappear?

@darcywong00 Yes, That's right.

**Comment by darcywong00** [comment]
From Friday standup, @mcdurdin said we'll hold off on this PR till @jahorton can investigate the browser OSK rotation issues.

**Comment by jahorton** [comment]
> @jahorton - is the browser OSK expected to intermittently disappear?

I'll need to revisit it to be sure, but my memory is that KMW will usually hide the OSK pre-rotation and re-display it afterward.  So, this suggests that the 'redisplay' part isn't happening for whatever reason.

**Comment by jahorton** [comment]
While certainly not an answer to the lingering issues from user testing mentioned above, there were a few oddities noted here on one of the original PRs: https://github.com/keymanapp/keyman/pull/6979#issuecomment-1203688781

It does make me wonder if there may be a bit more to address there as well.

**Comment by jahorton** [comment]
Unlike before, I'm having trouble attempting to repro the user test failures.  That's going to make investigation at least a bit tricky.

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest SUITE_ROTATION GROUP_OLD_IOS TEST_BROWSER_ROTATE_L-TO-P GROUP_ANDROID_PHONE TEST_BROWSER_ROTATE_P-TO-L

**Comment by MakaraSok** [comment]
Self assigned to retest and double check the failed cases

**Comment by MakaraSok** [comment]
# Test Results

## SUITE_ROTATION: 

### GROUP_OLD_IOS: - try to find an iOS 12 or iOS 13 device to test with

* **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested with the [build off of this PR](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/339125:id/index.html):

  * on iOS 12.4 iPhone Xs Max simulator. There is no way to open the language menu as the globe key is nowhere to be found.

  image

    Here is how it looks after rotate to portrait:
  image

If this is out of the scope of this test case, please ignore the this result.

  * The behavior above doesn't occur in iOS 13.7 simulator though.

  image

  image


### GROUP_ANDROID_PHONE: - any modern Android phone should suffice

* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested with Android 12 (API 31), the keyboard is shown OK after rotating to landscape.
 
  image

**Comment by jahorton** [comment]
> # Test Results
> ## SUITE_ROTATION:
> ### GROUP_OLD_IOS: - try to find an iOS 12 or iOS 13 device to test with
> 
>     * **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested with the [build off of this PR](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/339125:id/index.html):
>       
>       * on iOS 12.4 iPhone Xs Max simulator. There is no way to open the language menu as the globe key is nowhere to be found.
>       
>       image

I may need to double-check, but I think this is the same Safari issue as noted on one of the other tests previously.  Older iOS devices put the nav bar at the top rather than the bottom, but the in-page side effects were the same.  If the nav bar hadn't appeared, the globe key would likely be in view.

**Comment by jahorton** [comment]
Come to think on it... if the 'worst' user test failure we're getting is that the OSK isn't showing after a rotation... as long as it shows again when the element is reselected, that doesn't seem too bad of an issue.  Also, even that is only happening intermittently at that, so far as we've seen, right?

**Comment by bharanidharanj** [comment]
As per Makara's suggestion I have retested this (GROUP_OLD_IOS: - try to find an iOS 12 or iOS 13 device to test with- TEST_BROWSER_ROTATE_L-TO-P )in iOS 12.4 and here is my observation:
1. Tested the Landscape to Portrait mode in iPhone 7 Plus Simulator and I was able to see the OSK on the Screen in the landscape mode. However, the bottom of the OSK has been cropped. 

   

2. In iPhone X Simulator after clicking the text area, the globe key is not visible on the Screen. 

   

3. In iPhone xs Max Simulator, after scrolling down the page I could able to see the globe key. However, scrolling up the page will hide the globe key on the screen. 



4. Tested the same in iOS 16.0, the OSK is fully visible on the Screen. Seems to be working fine in the latest iOS verion.

**Comment by mcdurdin** [comment]
My feeling on this, is if the issue is less severe than previously, we should merge this. In particular, if this rotation issue only impacts Keyman Web on mobile, and only impacts rotation, and is easily resolved by the user by refocusing the edit control, that's a much smaller user base, with a much less severe impact, so we should merge.

Then we should open a new issue to correct the remaining rotation issues!

**Comment by mcdurdin** [comment]
One fail on the old version of iOS, modern iOS versions seem to work fine.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.271](https://keyman.com/downloads/releases/stable/15.0.271)
