### PR TITLE
fix(android): Refactor bottom inset calculations for in-app and system keyboard

### LINKED ISSUE #14864: bug(android): Top of system keyboard covering up text area
Follows #14794

#14808 fixed the issue where the navigation bar was covering up the bottom of the Keyman system keyboard.
But @dinakaranr and @rc-swag report issues where the top of the keyboard is covering up the app

Image

Things to check in testing:
* Using gesture navigation bar instead of 3-button navigation bar (@rc-swag was using gesture navigation bar)
* portrait and landscape orientation

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #14864 and follows #14808

The Keyman height seems to behave differently when the navigation bar is set to gesture navigation vs 3-button navigation. Sometimes, the top of the keyboard covers up the underlying text area, or sometimes there's an extra gap above the keyboard.

Based on changes from the Keyboard App Builder team, this PR pulls in similar changes from
sillsdev/app-builders@1fc2f36797fe52051480a4f218ba23df8cd2bfef and sillsdev/app-builders@96f6ba77246d698751d7f520863a3c7cd7f0914c

to update the system keyboard insets.
Reference:
https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/package-summary#(androidx.compose.foundation.layout.WindowInsets.Companion).systemGestures()

## API Change
`getNavigationBarHeight()` was a late change to adjust the keyboard for the bottom inset. This PR needs the additional parameter for KeyboardType. Documented in 7226d271456e0292a285d28b85eafc3e5f1d6aac

## User Testing

**Setup** - Install the PR build of Keyman for Android on a device/emulator Android API 35 (Android 15.0 Vanilla Ice Cream).
In Keyman settings, set "Show On-Screen Keyboard" (when a physical keyboard is connected) to ON.
**Note:** GROUP_GESTURE_2_BUTTON_NAVIGATION is optional as some devices don't offer this navigation mode.

GROUP_GESTURE_NAVIGATION - Set Device --> Display --> Navigation Mode --> Gesture navigation

GROUP_GESTURE_2_BUTTON_NAVIGATION - Set Device --> Display --> Navigation Mode --> 2-button navigation
Note: This test grouping is optional, as some devices don't have this option

GROUP_3_BUTTON_NAVIGATION - Set Device --> Display --> Navigation Mode --> 3-button navigation

* **TEST_INAPP** - Verifies in-app keyboard
1. Launch Keyman for Android and dismiss getting started menu
2. Verify the in-app keyboard works:
  a. base keys
  b. longpress keys
  c. suggestion banner

* **TEST_SYSTEM** - Verifies system keyboard
1. Lauinch Keyman for Android.
2. In the "Get Started" menu, set Keyman as the default system keyboard 
3. Launch the Contacts app and create a new contact
4. Scroll to the bottom of the new contact form and observe the bottom
5. Select a text area near the bottom and select Keyman as the keyboard (if not already)
6. Verify you can scroll the form so the text area is not obscured
7. Verify Keyman system keyboard works:
  a. base keys
  b. longpress keys
  c. suggestion banner

### CODE REVIEW

**Comment by mcdurdin** [comment]
I ran through some tests of https://build.palaso.org/buildConfiguration/KeymanAndroid_TestPullRequests/582061 on my phone. I did not encounter any sizing errors, either in-app or system. Looking good. Well done. Look forward to seeing results from @ermshiperete, @dinakaranr, @rc-swag too.

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java [hunk 1]
```diff
@@ -884,47 +889,46 @@ public static void closeParentAppOnShowKeyboardPicker() {
...
     keyboardLayout.addView(SystemKeyboard);
 
     mainLayout.addView(keyboardLayout);
     //mainLayout.addView(overlayLayout);
+
+    installSystemKeyboardInsetsListener(mainLayout);
     return mainLayout;
   }
 
+  private static void installSystemKeyboardInsetsListener(View anchor) {
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:917]: Is this idempotent?

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java [hunk 2]
```diff
@@ -2495,21 +2499,19 @@ private static void calculateDefaultKeyboardHeights(Context context) {
...
-    return (resourceId > 0) ? context.getResources().getDimensionPixelSize(resourceId) : 0;
+  public static int getNavigationBarHeight(Context context, KeyboardType keyboardType) {
+    // bottomInset already updated from the inset listener
+    if (keyboardType == KeyboardType.KEYBOARD_TYPE_INAPP) {
+      return inappBottomInset;
+    } else if (keyboardType == KeyboardType.KEYBOARD_TYPE_SYSTEM) {
+      return sysBottomInset;
+    }
+
+    return inappBottomInset;
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java]: Can we guarantee that the `inappBottomInset` and `sysBottomInset` values will be set when this is called? Is it possible to calculate them here if they have not already been set?

**Review by mcdurdin — APPROVED** [review]
LGTM pending those two questions

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java (hunk 1 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:917]: I think so - I can trigger this multiple times when switching from Keyman to other system keyboard and back, and the values still work.

Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:917]: I am more concerned that it could be installing multiple listeners?

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java (hunk 2 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java]: I wonder if we fallback to the previous computation of the navigation bar height.
It's inconsistent between gesture vs 3-button navigation mode, but still maybe better than uninitialized...

https://github.com/keymanapp/keyman/blob/c5b3598ab6ae99ea51b9f2ee9d2e7d928f351ccc/android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java#L2509-L2512

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java (hunk 1 above)
Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:917]: Answering my own question, it seems not, although the documentation is a bit unclear.

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java (hunk 2 above)
Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java]: If we do that, can we log an event to Sentry, so that we can hopefully track if this is arising as a problem anywhere?

**Comment by dinakaranr** [comment]
# Test Results
I tested this PR in the "Keyman 19.0.134-alpha-test-14873" build on Android Pixel 8 pro API 35. Here I am sharing my observation.

Prerequisites setup: 
Install the PR build as directed on an Android emulator /device of Android pixel 8 pro API 35(Android 15.0). 
In Keyman settings, set "Show On-Screen Keyboard" (when a physical keyboard is connected) to ON.

### GROUP_GESTURE_NAVIGATION: - Set Device --> Display --> Navigation Mode --> Gesture navigation

* **TEST_INAPP (Passed):** 
1. Launch Keyman for Android 15 and dismiss getting started menu
2. Verified the keyboard functions correctly with below options.
    a. base keys
    b. longpress keys
    c. suggestion banner

* **TEST_SYSTEM (Passed):** 
1. Launch Keyman for Android 15.
2. In the "Get Started" menu, set Keyman as the default system keyboard
3. Launch the Contacts app and create a new contact
4. Scroll to the bottom of the new contact form and observe the bottom
5. Select a text area near the bottom and select Keyman as the keyboard (if not already)
6. Verified if scroll the form so the text area is not obscured
7. Verified the keyboard functions correctly with below options.
    a. base keys
    b. longpress keys
    c. suggestion banner

### GROUP_GESTURE_2_BUTTON_NAVIGATION: - Set Device --> Display --> Navigation Mode --> 2-button navigation

* **TEST_INAPP (Passed):** 
1. Launch Keyman for Pixel 8 pro API 35 Android 15(this device does not provide the 2-button navigation) and dismiss getting started menu
2. Verified the keyboard functions correctly with below options.
    a. base keys
    b. longpress keys
    c. suggestion banner

* **TEST_SYSTEM (Passed):** 
1. Launch Keyman for Android 15.
2. In the "Get Started" menu, set Keyman as the default system keyboard
3. Launch the Contacts app and create a new contact
4. Scroll to the bottom of the new contact form and observe the bottom
5. Select a text area near the bottom and select Keyman as the keyboard (if not already)
6. Verified if scroll the form so the text area is not obscured
7. Verified the keyboard functions correctly with below options.
    a. base keys
    b. longpress keys
    c. suggestion banner

### GROUP_3_BUTTON_NAVIGATION: - Set Device --> Display --> Navigation Mode --> 3-button navigation

* **TEST_INAPP (Passed):** 
1. Launch Keyman for Android 15 and dismiss getting started menu
2. Verified the keyboard functions correctly with below options.
    a. base keys
    b. longpress keys
    c. suggestion banner

* **TEST_SYSTEM (Passed):** 
1. Launch Keyman for Android 15.
2. In the "Get Started" menu, set Keyman as the default system keyboard
3. Launch the Contacts app and create a new contact
4. Scroll to the bottom of the new contact form and observe the bottom
5. Select a text area near the bottom and select Keyman as the keyboard (if not already)
6. Verified if scroll the form so the text area is not obscured
7. Verified the keyboard functions correctly with below options.
    a. base keys
    b. longpress keys
    c. suggestion banner
It works well in the contact app while creating a contact & search a number or name.

**Comment by ermshiperete** [comment]
Works on my phone in the different scenarios I tried.

**Review by ermshiperete — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 19.0.136-alpha](https://keyman.com/downloads/releases/alpha/19.0.136)
