### PR TITLE
fix(common/core/desktop): Add num and scroll lock mask to VKeyToChar

### LINKED ISSUE #6204: bug(windows): Capslock key on does not produce uppercase characters
Found in pre-beta acceptance testing: #6192.
Keyman 15.0.189 alpha build

Capslock does not work. 
Using the `caplock.kmn` keyboard found in the manual tests repo.
It can also be seen not to work with keyboards such as Euro Latin SIL

This was introduced by clearing the high bytes of the shift state when calling the cores process event function. in `kmprocess.cpp`

```km_kbp_process_event(_td->lpActiveKeyboard->lpCoreKeyboardState, _td->state.vkey,
                                  static_cast<uint16_t>(Globals::get_ShiftState() & K_MODIFIERFLAG),
                                                    (uint8_t)_td->state.isDown))
```

It should not do this as it also clears the caplock flag.

The correct solution is to clear the Numlock flag in `VKeyToChar` in `kmx_processevent.cpp` something like 
```  if ((modifiers & ~(K_SHIFTFLAG | CAPITALFLAG | NUMLOCKFLAG )) != 0) {
    return 0;
  }
```
Note need to consider if SCROLLFLAG should also be cleared.

This the Keyman for Windows 15 latest alpha builds.

### PR DESCRIPTION
**Pull request by rc-swag**
Fixes #6204
This change removes the `K_MODIFIERFLAG` from the windows platforms call to the core processor's process_event call.
It then adds a mask for num and scroll lock to the `VKeyToChar` function.

### CODE REVIEW

**Comment by rc-swag** [comment]
# User Testing

## SUITE_CL: Caps Lock

The test keyboard layouts are found in the keyman repo at `app/windows/src/test/manual-tests/caps-lock-stores`. There is a project file for the 3 keyboards only 2 are required for this test. The project file can be used to build the keyboard packages required for the following tests. The 2 keyboards are attached to this PR.
 
The test cases below expect the usage of the `capslock.kmp` keyboard. That keyboard outputs _pass_ or _fail_ if following the test cases.

### Prerequisites before each test

- System keyboard layout is **en-US**
- Install a keyboard that doesn't use any of the caps lock stores, e.g. `capslock.kmp`.
- CapsLock is currently **on**
- Currently active keyboard is the **capslock.kmp** keyboard

### Test cases

- **TEST_CAPSLOCK-1**: uppercase with virtual key
  - press and release `a`

  Expected result:
  - `pass.` (with other keyboards uppercase `A`)

- **TEST_CAPSLOCK-2**: lowercase with virtual key
  - press and hold 'Shift'
  - press and release `b`
  - release `Shift`

  Expected result:
  - `pass.` (with other keyboards lowercase `b`)

- **TEST_CAPSLOCK-3**: capslock ignored for numbers
  - press and hold 'Shift'
  - press and release `3`
  - release `Shift`

  Expected result:
  - `pass.` (with other keyboards `#`)

- **TEST_CAPSLOCK-4**: uppercase
  - press and release `c`

  Expected result:
  - `pass.` (with other keyboards uppercase `C`)

- **TEST_CAPSLOCK-5**: lowercase
  - press and hold 'Shift'
  - press and release `d`
  - release `Shift`

  Expected result:
  - `pass.` (with other keyboards lowercase `d`)

## SUITE_SHIFT: CapsOnOnly/ShiftFreesCaps

For these tests, use a keyboard with the `CapsOnOnly` and `ShiftFreesCaps` stores set. We call this keyboard _shift_frees_caps_ below.

Any keyboard with these stores set will work; if you don't have one at hand you can use the `shift_frees_caps.kmp` keyboard.

The _shift_frees_caps.kmp_ keyboard will enable caps lock by pressing the `CapsLock` key, and will turn capslock off by pressing the `Shift` key. The keyboard outputs _pass_ or _fail_ if following the test cases.

**Note:** When testing in a virtual machine, use an on-screen keyboard (in VirtualBox: Input/Keyboard/Soft Keyboard) and observe the caps lock indicator of the on-screen keyboard. Using the hardware keyboard might show side effects with caps lock.

### Prerequisites before each test

- Install a keyboard that has the `CapsOnOnly` and `ShiftFreesCaps` stores set, e.g.
   `shift_frees_caps.kmp`.
- CapsLock is currently off
- Currently active keyboard is _shift_frees_caps_ keyboard

### Test cases

- **TEST_CAPSONLY-1**: no caps
  - press and release `1`

  Expected result:
  - output: `pass.`

- **TEST_CAPSONLY-2**: caps
  - press and release `CapsLock`
  - press and release `2`

  Expected result:
  - caps lock indicator turned on
  - output: `pass.`

- **TEST_CAPSONLY-3**: caps doesn't toggle
  - press and release `CapsLock`
  - press and release `CapsLock`
  - press and release `6`

  Expected result:
  - caps lock indicator turned on
  - output: `pass.`

- **TEST_CAPSONLY-4**: shift turns off
  - press and release `CapsLock`
  - press and hold `Shift`
  - press and release `3`
  - release `Shift`

  Expected result:
  - caps lock indicator turned off
  - output: `pass.`

**Comment by bharanidharanj** [comment]
##  SUITE_CL: Caps Lock

   * **TEST_CAPSLOCK-1: PASSED** Verified and it is showing 'pass' result. Performed the test on Notepad. 
   * **TEST_CASPLOCK-2: PASSED** Verified and it is showing 'pass' result. Performed the test on Notepad. 
   * **TEST_CAPSLOCK-3: FAILED** Verified and it is showing 'fail' result. Performed the test on Notepad. 
   * **TEST_CAPSLOCK-4: PASSED** Verified and it is showing 'pass' result. Performed the test on Notepad. 
   * **TEST_CAPSLOCK-5: FAILED** Verified and it is  showing 'fail' result. Performed the test on Notepad.

File: common/core/desktop/src/kmx/kmx_processevent.cpp [hunk 1]
```diff
@@ -33,9 +33,10 @@ KMX_ProcessEvent::~KMX_ProcessEvent() {
 }
 
 char VKeyToChar(KMX_UINT modifiers, KMX_UINT vk) {
-  // We only map SHIFT and UNSHIFTED, and CAPS LOCK
+  // We only map keys that are unmodified, shifted, or caps locked
 
-  if ((modifiers & ~(K_SHIFTFLAG | CAPITALFLAG)) != 0) {
+  // Test for modifier flags excluding Shift, Caps, Num and Scroll Lock
+  if ((modifiers & ~(K_SHIFTFLAG | CAPITALFLAG | NUM_SCROLL_LOCK_MASK)) != 0) {
```
[the remark this answers is not in the document]
Comment (mcdurdin) [reply common/core/desktop/src/kmx/kmx_processevent.cpp:39]: I think it might be better to mask out those bits from `modifiers` on input to the function, and document, and simplify the test accordingly:

```
  // We are not interested in Num Lock and Scroll Lock state
  modifiers = modifiers & ~NUM_SCROLL_LOCK_MASK;
```

File: windows/src/engine/keyman32/kmprocess.cpp [hunk 2]
```diff
@@ -153,14 +153,14 @@ BOOL ProcessHook()
...
-        (km_kbp_status_codes)km_kbp_process_event(_td->lpActiveKeyboard->lpCoreKeyboardState, _td->state.vkey,
-                                  static_cast<uint16_t>(Globals::get_ShiftState() & K_MODIFIERFLAG),
-                                                    (uint8_t)_td->state.isDown)) {
-        SendDebugMessageFormat(0, sdmGlobal, 0, "ProcessEvent CoreProcessEvent Result:False %d ",FALSE);
+      SendDebugMessageFormat(
+          0, sdmGlobal, 0, "ProcessEvent: vkey[%d] ShiftState[%d] isDown[%d]", _td->state.vkey,
+          static_cast<uint16_t>(Globals::get_ShiftState()), (uint8_t)_td->state.isDown);
+      if (KM_KBP_STATUS_OK != (km_kbp_status_codes)km_kbp_process_event(
+                                  _td->lpActiveKeyboard->lpCoreKeyboardState, _td->state.vkey,
+                                  static_cast<uint16_t>(Globals::get_ShiftState()),
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/kmprocess.cpp:161]: We need to be sure that passing in the unadulaterated shift state mask doesn't have side-effects elsewhere in `km_kbp_process_event`! Have you verified this?

**Review by mcdurdin — CHANGES_REQUESTED** [review]
I wonder if we just update the call to `km_kbp_process_event` to pass `get_ShiftState() & (K_MODIFIERFLAG | CAPITALFLAG)` and avoid other potential ripple effects of changing `VKeyToChar`? Would that have the same effect as the changes you've made?

File: windows/src/engine/keyman32/kmprocess.cpp (hunk 2 above)
Comment (rc-swag) [reply windows/src/engine/keyman32/kmprocess.cpp:161]: Only in the fact that it was like that up until around a week ago when I added in the `K_MODIFIERFLAG`. 

How about this working of `keyboardprocessor_vkeys.h`  and the   `km_kbp_modifier_state` enum (which has dead code of the scroll lock etc by the way). 

``` 
//  Mask out the bits not supported according to `km_kbp_modifier_state` enum, Update the mask if this enum is expanded.
 if (KM_KBP_STATUS_OK != (km_kbp_status_codes)km_kbp_process_event(
                                  _td->lpActiveKeyboard->lpCoreKeyboardState, _td->state.vkey,
                                  static_cast<uint16_t>(Globals::get_ShiftState() & (KM_KBP_MODIFIER_MASK_ALL | KM_KBP_MODIFIER_MASK_CAPS) ),
```

**Comment by rc-swag** [comment]
@bharanidharanj  I have some changes to this. However, the reason it failed with the Windows Search Bar is because using a different text input method called (Text Services Framework). We have a bug for that which is addressed in this PR #6219
Therefore, for this test, we can only use apps that don't use the TSF such as `notepad`.  I will update the test to specify using `notepad`. Then I will set it for re-test

File: windows/src/engine/keyman32/kmprocess.cpp (hunk 2 above)
Comment (mcdurdin) [reply windows/src/engine/keyman32/kmprocess.cpp:161]: Yeah, I like this -- it's a more targeted fix and means `km_kbp_process_event` never receives the num lock and scroll lock modifiers which it doesn't actually support -- and so then we don't need to change `VkToChar` :grin:

File: common/core/desktop/src/kmx/kmx_processevent.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (mcdurdin) [reply common/core/desktop/src/kmx/kmx_processevent.cpp:39]: This change should not be necessary if we go with the other fix 😸

File: windows/src/engine/keyman32/kmprocess.cpp (hunk 2 above)
Comment (rc-swag) [reply windows/src/engine/keyman32/kmprocess.cpp:161]: Oh ok I was going to make VkeyToChar handle a broken pre-condition. However, if the core api is honoured it shouldn't be a problem.

Comment (mcdurdin) [reply windows/src/engine/keyman32/kmprocess.cpp:161]: Yep. We could add a debug-only assertion as an input condition to `km_kbp_process_event` if we want to be pure.

**Comment by rc-swag** [comment]
@keymanapp-test-bot retest SUITE_CL 

Please use the Notepad application

**Comment by bharanidharanj** [comment]
> @bharanidharanj I have some changes to this. However, the reason it failed with the Windows Search Bar is because it uses a different text input method called (Text Services Framework). We have a bug for that which is addressed in this PR #6219 Therefore, for this test, we can only use apps that don't use the TSF such as `notepad`. I will update the test to specify using `notepad`. Then I will set it for re-test

@rc-swag Okay. I will test it.

**Comment by bharanidharanj** [comment]
## SUITE_CL: Caps Lock

* **TEST_CAPSLOCK-1: PASSED** Performed the test on Notepad application. 
* **TEST_CAPSLOCK-2: FAILED**  Performed the test on Notepad application. 
* **TEST_CAPSLOCK-3: PASSED** Performed the test on Notepad application.
* **TEST_CAPSLOCK-4: PASSED** Performed the test on Notepad application. 
* **TEST_CAPSLOCK-5: PASSED** Performed the test on Notepad application

**Comment by bharanidharanj** [comment]
## SUITE_SHIFT: CapsOnOnly/ShiftFreesCaps

* **TEST_CAPSONLY-1: PASSED** It shows 'pass' result on the Notepad application. 
* **TEST_CAPSONLY-2: PASSED** It shows 'pass' result on the Notepad application. 
* **TEST_CAPSONLY-3: PASSED** It shows 'pass' result on the Notepad application.
* **TEST_CAPSONLY-4: PASSED** It shows 'pass' result on the Notepad application. Noticed that Capslock indicator turned On.
* **TEST_CAPSONLY-5: PASSED** It shows 'pass' result on the Notepad application. Noticed that Capslock indicator turned Off.

**Comment by rc-swag** [comment]
@bharanidharanj  I have rebased this on master which fixed another bug around input. It shouldn't make a difference but it would hurt.  I am not sure why test `TEST_CAPSLOCK-2` failed for you. Can I you please download the build again a re-test it thanks. Also make sure CapsLock is on before starting this test.

@keymanapp-test-bot retest SUITE_CL TEST_CAPSLOCK-2

**Review by mcdurdin — APPROVED** [review]

**Comment by bharanidharanj** [comment]
> @bharanidharanj I have rebased this on master which fixed another bug around input. It shouldn't make a difference but it would hurt. I am not sure why test `TEST_CAPSLOCK-2` failed for you. Can I you please download the build again a re-test it thanks. Also make sure CapsLock is on before starting this test.
> 
> @keymanapp-test-bot retest SUITE_CL TEST_CAPSLOCK-2

@rc-swag Sure. I will re-test it and will post my comment accordingly. Thanks.

**Comment by bharanidharanj** [comment]
## SUITE_CL: Caps Lock

* **TEST_CAPSLOCK-2: FAILED**  Retested this issue with Keyman 15.0.196-alpha-test-2611 and I am seeing the same result. Attached my Screenshot for your reference.

**Comment by rc-swag** [comment]
@bharanidharanj 
I, unfortunately, attached an old build of the capslock test keyboard. It was still on my PC. I have rebuilt the keyboard from what is checked in at the repo you can download with this link 
[caps_feb_2022.zip](https://github.com/keymanapp/keyman/files/8102357/caps_feb_2022.zip)

it is also available the Test Instructions.  I have removed the incorrect keyboard.  You will have to uninstall the `Caps Lock` keyboard the configuration menu. Then install the `capslock.kmp` found in `caps_feb_2022


More detailed info these are the lines that were switched on the incorrect keyboard. That is `NCAPS` and `CAPS` were switched.

+ [NCAPS SHIFT K_B] > 'fail.'
+ [CAPS SHIFT K_B] > 'pass.'

@keymanapp-test-bot retest SUITE_CL TEST_CAPSLOCK-2

**Comment by MakaraSok** [comment]
## SUITE_CL: Caps Lock

* **TEST_CAPSLOCK-2: PASSED** The out is `pass.` as indicated.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.202-alpha](https://keyman.com/downloads/releases/alpha/15.0.202)
