### PR TITLE
fix(android): verify browser before starting activity

### LINKED ISSUE #6899: bug(android): we need to verify that a browser is available before attempting to open links
**Describe the bug**

There may be circumstances where we cannot open an URL because the browser is not available. We should test that the intent will resolve:

```java
  if (i.resolveActivity(getPackageManager()) != null) {
    startActivity(i);
  }
```

instead of just having:

```java
  startActivity(i);
```

## Source locations

I found the following places where this is needed:

https://github.com/keymanapp/keyman/blob/0bff16a643475f1e4c8be5b99a776d222f0e4bcd/android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeyboardSettingsActivity.java#L176-L178

https://github.com/keymanapp/keyman/blob/93b7814b6ce720b61841930303f51a0be08fdf30/android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java#L112-L117

https://github.com/keymanapp/keyman/blob/d5aa61fdc06a7acd7aed78010d0ad2f96c2eb72f/android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java#L763-L769

https://github.com/keymanapp/keyman/blob/3066c1f24680b9275596b85584d003825a549779/android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardInfoActivity.java#L137-L139

https://github.com/keymanapp/keyman/blob/49b099c26f11af059c899ea939092e4e4f296fea/oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/FVShared.java#L252-L255

https://github.com/keymanapp/keyman/blob/29d32bc0e6d87deceb83e241ad86c9e4d0b964e4/oem/firstvoices/android/app/src/main/java/com/firstvoices/keyboards/MainActivity.java#L107-L108

## Reporting

This was reported in a [Play Store Prelaunch Report](https://play.google.com/console/u/2/developers/7336157154804555928/app/4973304378908433194/pre-launch-report/details?tab=stability&artifactId=4859700830783191672) for FV Keyboards:

```
  ...
  com.firstvoices.keyboards.MainActivity$1.shouldOverrideUrlLoading(MainActivity.java:108)
  ...
```

Error message received:

```
FATAL EXCEPTION: main
Process: com.firstvoices.keyboards, PID: 9193
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://fpcf.ca/... }
```

## More information

https://stackoverflow.com/a/58954933/1836776

---

**Keyman for Android:**
 - Device: any 
 - OS: any 
 - Keyman version: any

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #6899.

@keymanapp-test-bot skip

### CODE REVIEW

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java [hunk 1]
```diff
@@ -762,10 +762,15 @@ public void onClick(View v) {
...
+            if (intent.resolveActivity(getPackageManager()) != null) {
+              startActivity(intent);
+            }
           } catch (android.content.ActivityNotFoundException e) {
             // Link to Chrome if user is not signed in to Play Store
-            startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://play.google.com/store/apps/details?id=com.android.chrome")));
+            Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse("https://play.google.com/store/apps/details?id=com.android.chrome"));
+            if (intent.resolveActivity(getPackageManager()) != null) {
+              startActivity(intent);
+            }
```
Comment (jahorton) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java:773]: For this one, I'm fairly certain that inserting the `if` statement in the first section ought nullify the `catch` statement; instead, shouldn't the `catch` be turned into an `else`?

**Review by jahorton — CHANGES_REQUESTED** [review]
I could be wrong, but wouldn't this cause a lot of errors to simply become 'silent errors' from the user perspective?  Like, they'd try to use the UI elements that trigger this code... and then nothing would happen.  I'm pretty sure that'd still qualify as a "bug".

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java (hunk 1 above)
Comment (mcdurdin) [reply android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java:773]: Yes, you are right, Line 765 should have an `if`. I'm inclined to leave the catch there in case there are scenarios we are not covering with the resolveActivity test around the Play Store, but will tweak the rest accordingly.

**Comment by mcdurdin** [comment]
> I could be wrong, but wouldn't this cause a lot of errors to simply become 'silent errors' from the user perspective? 

True. This scenario seems unlikely to happen in "real life" -- how many Android devices don't have a browser installed? -- but it happens in the Play Store test environment. I could go ahead and add a toast notification, if you think that is important?

**Comment by jahorton** [comment]
> I could go ahead and add a toast notification, if you think that is important?

I'm not sure if it's needed for every case, but that does seem to be wise for at least some of them.  For example, if the user's already in a WebView (for help, keyboard search, etc), that's definitely worth a notification - otherwise the user'll be like "why isn't this working?"

I can't say that any of the change locations are spots to _not_ include a Toast.  I'm just not clear on role a few of the spots play, thus can't really say one way or the other.

**Review by jahorton — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.51-alpha](https://keyman.com/downloads/releases/alpha/16.0.51)
