### PR TITLE
[Windows] Canonicalize and complete language tags during keyboard installation and when adding languages to keyboards via Keyman Configuration

### LINKED ISSUE #886: [Windows] Auto-fix incomplete language tags when installing keyboards in Keyman Desktop
If a keyboard is installed with an incomplete language tag (e.g. no script tag), then use the same global data we use in the manual add-lang dialog to programmatically determine an appropriate script.

Also:

* Ensure that Developer is giving good hints on this. #885
* Validate keyboards in repo for their lang-script tag suitability in .kps. #885 also

This is particularly relevant for legacy keyboards that may have `&ethnologuecode` data but not .kps language data.

### LINKED ISSUE #887: [windows] Add language dialog does not honour suppress-script
For example if you try adding `en-Latn-pg`, it should suppress `Latn` and give just `en-PG`. This is a regression coming from the fix made earlier in #827.

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #886. Fixes #887. BCP 47 tags will now be canonicalized and scripts applied where possible and needed, automatically, during keyboard installation

### CODE REVIEW

File: windows/src/engine/kmcomapi/processes/keyboard/kpinstallkeyboardlanguageprofiles.pas [hunk 1]
```diff
@@ -340,22 +338,15 @@ function TKPInstallKeyboardLanguageProfiles.RegisterLocale(KeyboardName, BCP47Ta
...
   FTag := TBCP47Tag.Create(BCP47Tag);
   try
-    FScripts.Text := SuppressScriptSubtagRegistry;
-    if SameText(FTag.Script, FScripts.Values[FTag.Language]) then
-    begin
-      FTag.Script := '';
-      Result := FTag.Tag;
-    end;
+    FTag.Canonicalize;
+    Result := FTag.Tag;
```
Comment (darcywong00) [inline windows/src/engine/kmcomapi/processes/keyboard/kpinstallkeyboardlanguageprofiles.pas]: What happens if `FTag.Canonicalize` returns `''`?

Comment (mcdurdin) [reply windows/src/engine/kmcomapi/processes/keyboard/kpinstallkeyboardlanguageprofiles.pas]: Okay, testing return value now during the install.
