### PR TITLE
fix(web): Increase size of spacebar text

### LINKED ISSUE #7940: bug(web): spacebar text sometimes overly small without good reason
### Describe the bug

See repro + screenshot below.

### Reproduce the bug

1. Go to the "Prediction - robust testing" test page in Chrome.
2. Launch developer mode and set it to emulate an iPhone SE.
3. Set the emulation scale to better match the relative size to a physical handheld iPhone SE.

Note how the spacebar text becomes near-unreadably small; something's off with the settings there.

image

### Expected behavior

_No response_

### Related issues

_No response_

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

_No response_

### Operating system

_No response_

### Device

_No response_

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ermshiperete**
Fixes #7940.

The caption on the spacebar used to be 60% (0.6em). This change increases it to 100%.

One reason for the sometimes small text on the spacebar described in #7940 besides the too small font size on `kmw-spacebar-caption` was that the calculation of the ideal font size added double padding: it added two pixels of
padding to the height, but also multiplied the height value by 0.9 which effectively added more padding. This change removes the 2 pixel padding from the calculation.

Note that it is still possible for the text on the spacebar to become unreasonably small if the keyboard/language name is too long. However, that is outside of the scope of this PR.

Screenshot from 2023-11-07 19-26-53

# User Testing

**TEST_EMULATOR**: 

- Go to the "Prediction - robust testing" test page in Chrome.
- Launch developer mode and set it to emulate an iPhone SE.
- Set the emulation scale to better match the relative size to a physical handheld iPhone SE.
- verify that the keyboard name on the spacebar has a reasonable size

**TEST_HARDWARE**:

- Install Keyman on an Android or iPhone device
- Open the Keyman app and install a Keyman keyboard
- verify that the keyboard name on the spacebar has a reasonable size

**TEST_WEB**:

- Go to the "Prediction - robust testing" test page in Chrome.
- verify that the keyboard name on the spacebar has a reasonable size

### CODE REVIEW

**Comment by mcdurdin** [comment]
> This change increases it to 100%, but that might be sometimes too big. On the other hand, 80% still seemed to be too small.

I think we need to verify this across a range of keyboards and devices, because I expect that this is going to be too big for some of them. So we might need a cleverer solution, such as scaling it to fit?

**Comment by mcdurdin** [comment]
I'm not also 100% sure that this is the entire cause of the tiny font size issue. The rest of the keyboard in the #7940 shows text at a sensible size, and it's only the spacebar which is mis-scaled. But all of the text elements on the keyboard use `em` scaling, so they should all be consistent in scale to each other?

**Comment by ermshiperete** [comment]
Ah, you're right. It gets dynamically changed. Would have been too easy 😀.

**Comment by ermshiperete** [comment]
> I think we need to verify this across a range of keyboards and devices, because I expect that this is going to be too big for some of them. So we might need a cleverer solution, such as scaling it to fit?

It already does downscaling so that the text will always fit in the available size. However, this can lead to the font size becoming unreasonably small if the language/keyboard name is too long, but that's a different issue.

**Comment by ermshiperete** [comment]
> I'm not also 100% sure that this is the entire cause of the tiny font size issue. The rest of the keyboard in the #7940 shows text at a sensible size, and it's only the spacebar which is mis-scaled. But all of the text elements on the keyboard use `em` scaling, so they should all be consistent in scale to each other?

I added another commit to address the underlying cause of #7940 and updated the PR description.

File: web/src/engine/osk/src/keyboard-layout/oskKey.ts [hunk 1]
```diff
@@ -239,14 +240,15 @@ export default abstract class OSKKey {
...
 
     var fontHeight: number, keyHeight: number;
     if(metrics.fontBoundingBoxAscent) {
       fontHeight = metrics.fontBoundingBoxAscent + metrics.fontBoundingBoxDescent;
     }
 
-    let textHeight = fontHeight ? fontHeight + Y_PADDING : 0;
+    // Don't add extra padding to height - multiplying with MAX_Y_PROPORTION already gives
+    // padding
+    let textHeight = fontHeight ? fontHeight : 0;
```
Comment (mcdurdin) [inline web/src/engine/osk/src/keyboard-layout/oskKey.ts:251]:
```suggestion
    let textHeight = fontHeight ?? 0;
```

**Review by mcdurdin — APPROVED** [review]

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_EMULATOR (PASSED):** Tested with the Keyman developer 17.0.207-alpha-test-9954 on Windows 10 OS and here is my observation: 1. Opened a Keyboard project. 2. Compiled it. Launched it in developer mode and set it to emulate an iPhone SE. 3. Verified that the keyboard name on the spacebar has a reasonable size.

..itransdevnagari keyboard

   

..silcameroonqwerty

   
 
..khmerangkor

   


* **TEST_HARDWARE (PASSED):** Installed PR build in the Android Mobile device (Samsung Galaxy A23 5g) and here is my observation: 1. Verified that the keyboard name on the spacebar has a reasonable size. 

   


* **TEST_WEB (PASSED):** 1. Opened the "Prediction - robust testing" test page in Chrome browser. 2. Set it to emulation mode. 3. Verified that the keyboard name on the space has a reasonable size.

**Comment by mcdurdin** [comment]
> * Launched it in developer mode and set it to emulate an iPhone SE.

@bharanidharanj, note that you need to reload the page after switching to Developer mode in Chrome (press Ctrl+R or F5). Otherwise, you get the desktop on screen keyboard in a phone form factor, which we can see is what has happened in your screenshots 😁.

@keymanapp-test-bot retest TEST_EMULATOR

**Comment by bharanidharanj** [comment]
> > * Launched it in developer mode and set it to emulate an iPhone SE.
> 
> @bharanidharanj, note that you need to reload the page after switching to Developer mode in Chrome (press Ctrl+R or F5). Otherwise, you get the desktop on screen keyboard in a phone form factor, which we can see is what has happened in your screenshots 😁.
> 
> @keymanapp-test-bot retest TEST_EMULATOR

Thanks for the Clarification, @mcdurdin . I will retest and add my comment.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_EMULATOR (PASSED):** Retested as per Marc's suggestion and here is my observation: 1. Opened test page and set it to emulation mode in Chrome browser. 2. Verified that the keyboard name on the space has a reasonable size.

..English Keyboard

   

..English - EuroLatin(SIL) Keyboard

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.209-alpha](https://keyman.com/downloads/releases/alpha/17.0.209)

**Comment by MayuraVerma** [comment]
Also the labels for alpha/number special keys, shift key, return key and global icon and text size should be increased 

image

image

**Comment by mcdurdin** [comment]
> Also the labels for alpha/number special keys, shift key, return key and global icon and text size should be increased

@MayuraVerma this needs to be a separate issue.
