### PR TITLE
fix(windows): check if permissions for thread to access file

### LINKED ISSUE #6412: bug(windows): File not available to elevated admin - Exception EZipException in module kmcomapi.dll at 00539B6D.
Sentry Issue: [KEYMAN-WINDOWS-10N](https://sentry.io/organizations/keyman/issues/3112375141/?referrer=github_integration)

```
Exception EZipException in module kmcomapi.dll at 00539B6D.
File must be open.

  kmcomapi            0x2f939b6d   System.Zip.TZipFile.GetFileCount (System.Zip.pas:1)
  kmcomapi            0x2f66b30a   utilhandleexception.CaptureStackTrace (utilhandleexception.pas:59)
  kmcomapi            0x2f66b434   utilhandleexception.LogException (utilhandleexception.pas:81)
  kmcomapi            0x2f958781   keymanautoobject.TKeymanAutoObject.SafeCallException (keymanautoobject.pas:173)
  kmcomapi            0x2f4095ef   System.@HandleAutoException (System.pas:1)
  ntdll               0x779cfc23   ExecuteHandler
  ntdll               0x779c9e45   KiUserExceptionDispatcher
  kmcomapi            0x2f939b6c   System.Zip.TZipFile.GetFileCount (System.Zip.pas:1)
  kmcomapi            0x2f94ef56   keymanpackagesinstalled.TKeymanPackagesInstalled.Install2 (keymanpackagesinstalled.pas:139)
  kmshell             0x2c8cff01   Keyman.Configuration.UI.InstallFile.TInstallFile.Execute (Keyman.Configuration.UI.InstallFile.pas:168)
  kmshell             0x2c8cf7ee   Keyman.Configuration.UI.InstallFile.TInstallFile.Execute (Keyman.Configuration.UI.InstallFile.pas:50)
  kmshell             0x2c97e539   initprog.RunKMCOM (initprog.pas:533)
  kmshell             0x2c97de50   initprog.Run (initprog.pas:340)
  kmshell             0x2c992cee   kmshell.kmshell
  KERNEL32.DLL        0x766988b7   $push_thunk$cdecl$u$u
  KERNEL32.DLL        0x765fed7b   BaseThreadInitThunk
  ntdll               0x778c595f   #__RtlUserThreadStart
  ntdll               0x778c5917   #_RtlUserThreadStart
  ntdll               0x779857cb   _RtlUserThreadStart$pop_thunk

```

### PR DESCRIPTION
**Pull request by rc-swag**
Fixes #6412

The fix addresses the crash by testing for file existence before continuing, in the admin account run, it show a message to the user if not in Silent mode. 

# User Testing Under Contsruction
Testing this is quite tricky. The way I was able to test this was to have a mapped network drive that was accessed with a different user than the user of my local machine.  See. [windows troubleshooting note](https://learn.microsoft.com/en-us/troubleshoot/windows-client/networking/mapped-drives-not-available-from-elevated-command)

I can run this test if you are not able to replicate it. 

**TEST_INSTALL_KMP_MAPPED_DRIVE**

1. Install the Keyman associated with this PR.
2. Download a Keyboard file `sil_ipa.kmp` and copy it to a folder on a mapped network drive.
3. Double-click the `sil_ipa.kmp` file on the mapped network drive.
4. Follow all the dialogs that appear. 
5. The window do you want to allow this app to make changes to your device? Select Yes
6.  All the windows will close. The keyboard will not be installed
7. No crash dialog appears.

**TEST_INSTALL_KMP_LOCAL_DRIVE**  Insure the normal case still works

1. Install the Keyman associated with this PR.
2. Download a Keyboard file `sil_ipa.kmp`  ensure it is in a location on your local drive.
3. Double-click the `sil_ipa.kmp` file .
4. Follow all the dialogs that appear. 
5. The window do you want to allow this app to make changes to your device? Select Yes
6. The keyboard should install as per normal with the help file for the keyboard being displayed.

### CODE REVIEW

File: windows/src/engine/kmcomapi/processes/package/kpinstallpackage.pas [hunk 1]
```diff
@@ -161,10 +161,10 @@ procedure TKPInstallPackage.Execute(const FileName: string; Options: TKPInstallP
       FTempOutPath := buf; FTempOutPath := FTempOutPath + '\';
 
       inf := nil;
+
```
Comment (rc-swag) [inline windows/src/engine/kmcomapi/processes/package/kpinstallpackage.pas:164]:
```suggestion
```

File: windows/src/engine/kmcomapi/processes/package/kpinstallpackage.pas [hunk 2]
```diff
@@ -161,10 +161,10 @@ procedure TKPInstallPackage.Execute(const FileName: string; Options: TKPInstallP
...
       FZip := TZipFile.Create;
       try
         FZip.Open(FileName, TZipMode.zmRead);
```
Comment (rc-swag) [inline windows/src/engine/kmcomapi/processes/package/kpinstallpackage.pas:167]:
```suggestion
        FZip.Open(FileName, TZipMode.zmRead);
        
```

**Review by mcdurdin — APPROVED** [review]

**Comment by bharanidharanj** [comment]
* **TEST_INSTALL_KMP_LOCAL_DRIVE (PASSED):** Tested with the attached PR build and here is my observation: Able to install sil_ipa keyboard from local folder.

**Review by ermshiperete — APPROVED** [review]

**Comment by rc-swag** [comment]
@bharanidharanj  The first test it installed ok because you have permission for that network share as the same user as your  local user. It really needs to be a mapped network drive in which you login in using a different user then your local system user.

Right-click on "This PC" in windows explorer and select mapped network drive 
image
image
Then connect using different credentials - those credentials being a user with access to the network drive.  

I think maybe I do this one as a self-test. @mcdurdin  what do you think?

**Comment by mcdurdin** [comment]
> I think maybe I do this one as a self-test. @mcdurdin what do you think?

Yes, that sounds like a good plan for this

**Comment by rc-swag** [comment]
@keymanapp-test-bot retest TEST_INSTALL_KMP_MAPPED_DRIVE

**Comment by rc-swag** [comment]
TEST_INSTALL_KMP_MAPPED_DRIVE (PASSED):  I set this up with a mapped network drive, that had different user credentials than my local user. It did not crash, and the keyboard was not installed as expected.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.103-beta](https://keyman.com/downloads/releases/beta/16.0.103)
