### PR TITLE
feat(developer): fixes to kmc-package for keyboard support 🙀

### LINKED ISSUE #7277: feat(developer): share kmlmc package compiler with kmc

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #7277.

kmc-package had a number of gaps and errors. This fixes a bunch of problems:

* Wrong case on XML elements
* Wrong metadata in system element
* Missing kmp.json in `files` array (needs test in consumer apps later)
* Missing `displayFont`, `oskFont` in `keyboard` elements
* Including `copyLocation` when == 0
* Including an empty `startMenu` element
* Incorrect assumptions about location of source files in `source/` folder

Also fixes up test fixtures accordingly (mostly version numbers)

Note that support for `followKeyboardVersion` will come later; for now, it uses the possibly-stale value from the Keyboard element in the .kps file. See #7340 for tracking issue.

TODO: 
- [ ] Given the number of faults here, we will need to review our generation of lexical model packages at some point.
- [ ] Regression test lexical model packages built against Android & iOS

@keymanapp-test-bot skip

### CODE REVIEW

File: developer/src/kmc-package/src/kmp-compiler.ts [hunk 1]
```diff
@@ -37,117 +40,227 @@ export default class KmpCompiler {
...
+
+  private kpsInfoToKmpInfo(info: KpsFileInfo): KmpJsonFileInfo {
+    let ni: KmpJsonFileInfo = {};
+
+    const keys: [(keyof KpsFileInfo), (keyof KmpJsonFileInfo)][] = [
+      ['author','author'],
+      ['copyright','copyright'],
+      ['name','name'],
+      ['version','version'],
+      ['webSite','website']
```
Comment (srl295) [inline developer/src/kmc-package/src/kmp-compiler.ts:169]: capital `S` answers 'why is this not a one dimensional list'

**Review by srl295 — APPROVED** [review]
LGTM, although are `developer/src/kmc-package/test/fixtures/khmer_angkor/build/khmer_angkor.js` and such (build directory) really supposed to be checked in?

File: developer/src/kmc-package/src/kmp-compiler.ts (hunk 1 above)
Comment (mcdurdin) [reply developer/src/kmc-package/src/kmp-compiler.ts:169]: Yeah, gross right? It keeps me awake at night. Note that there is a camel-casify thing that I asked the xml2js wrapper to do when I wrote this code originally which I now regret and will back out in the future, which will mean more of these tables (but then at least it will say `WebSite` and `ID` just like the XML rather than this weird hybrid `webSite` and `iD` which matches nothing in any format!)

**Comment by mcdurdin** [comment]
> are `developer/src/kmc-package/test/fixtures/khmer_angkor/build/khmer_angkor.js` and such (build directory) really supposed to be checked in?

In this case, yes. When building this we don't have access to the compiler, and we want to verify that the packaging phase will succeed when given files in various folders (../source, . (build/), etc).

File: developer/src/kmc-package/src/kmp-compiler.ts (hunk 1 above)
Comment (mcdurdin) [reply developer/src/kmc-package/src/kmp-compiler.ts:169]: --> tracking in #7353
