### PR TITLE
fix(ios): long-held backspace handling

### LINKED ISSUE #10204: bug(ios): Backspace is not predictable
### Describe the bug

Backspace stops randomly at newline, white space, ?, 

Remedy is to reposition the cursor to the same location,  backspace work start functioning again

### Reproduce the bug

_No response_

### Expected behavior

_No response_

### Related issues

_No response_

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.227

### Operating system

iOS 17.1.3

### Device

iPhone 13 Pro max

### Target application

Any

### Browser

_No response_

### Keyboard name

Sil_EuroLatin

### Keyboard version

2.0.4

### Language name

English

### Additional context

https://github.com/keymanapp/keyman/assets/30884806/873e21cb-8ab0-4566-8595-bb24c6b0e585

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #10204.  Continues from #10584.

While this isn't a 100% perfect fix, it should present a marked improvement in the iOS Keyman app's handling of large-scale text deletion.  That said, there's no reasonably simple way to reach 100% perfection with the interfaces Apple gives us due to the internal mechanisms at play and the limited API.

Known remaining issues:
- When deleting large amounts of text...
    - ... within a large paragraph, on rare occasions the keyboard may change layer as if the context were empty, even when it isn't.  
    - ... on rare occasions, a backspace may not properly delete a character (for keyboards with scripts in the Unicode SMP range).
    - Similarly, keyboard rules with special backspace handling may occasionally not trigger if large amounts of text was deleted between the last directly user-set caret position and its current position.
        - Such "last positions" also include "position after pasting text", as long as the text-insertion point has only been manipulated by typing since then.

In either case, correct behavior will resume either on the following backspace or the backspace after that (the latter is more likely when "mashing" the backspace key than when not).

Sadly, any alternative solution I could find... required quite finicky manipulation of the caret and context.  The resulting "feel" was off - the manipulation had results that could easily feel unexpected and/or glitchy due to related timing issues - and those issues would cause such solutions to be more fragile than desired.

## User Testing

**TEST_LONG_DELETION_BMP**:  Using the iOS Keyman app on a real iPhone or iPad, delete a _lot_ of pre-existing text from within a third-party application.

1. Ensure that Keyman is enabled for use as a system keyboard.
2. Open a third party application **and swap to the default iOS system keyboard**.
3. Copy the following text (to be pasted on the device, in a later step):
    ```
    Testing testing one two three one two three

    Even more random text typed here. Lots and lots and lots of text. Like, way too much text. I want to trigger a context window, and we're going to make certain of it.

    And yeah, another one to be safe. Gonna start within this one, so I can fall back on the last one and see if it triggers across THOSE boundaries. That could totally happen, right?
    ```
4. Open the Notes app and create a new note.
5. Paste the text copied from step 3 as the content of the new note.
6. While still in the Notes app, use the globe key keyboard-selection menu to **activate Keyman as your system keyboard**.
7. Hold down BKSP until no further deletions occur.
8. If any visible text remains that refuses to be deleted, FAIL this test.

**TEST_LONG_DELETION_SMP**:  Using the iOS Keyman app on a real iPhone or iPad, delete a _lot_ of pre-existing text from within a third-party application.

1. Ensure that Keyman is enabled for use as a system keyboard.
2. Open a third party application **and swap to the default iOS system keyboard**.
3. Copy the following text (to be pasted on the device, in a later step):
    ```
    𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖

    𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖

    𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖 𝕒𝕓𝕔𝕕𝕖
    ```
    - For future reference, `𝕒` = `U+1D552`.  ("Mathematical double-struck small A")  Similar for the other "letters".
4. Open the Notes app and create a new note.
5. Paste the text copied from step 3 as the content of the new note.
6. While still in the Notes app, use the globe key keyboard-selection menu to **activate Keyman as your system keyboard**.
7. Hold down BKSP until no further deletions occur.
    - If the first BKSP does not act as expected, FAIL this test.
    - If a random symbol appears after _many_ deletions but is deleted shortly thereafter, _ignore_ the random symbol and continue the test.  (This is a known limitation.)
8. If any visible text remains that refuses to be deleted, FAIL this test.

Additional test resource:

The following QR code will open this PR's GitHub page on a mobile device:

pr qr code

I figured this might make visiting this page on the test device, to copy each test's text blocks, less complicated.

### CODE REVIEW

File: ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift [hunk 1]
```diff
@@ -294,18 +294,65 @@ open class InputViewController: UIInputViewController, KeymanWebDelegate {
...
+
+      os_log("setContextState(text: `%@`, range initializer location: %d, range.location: %d", log: KeymanEngineLogger.engine, type: .debug, contextWindowText, before.count, range.location)
+      self.setContextState(text: contextWindowText, range: range)
+    }
+
+    updater(preCaretContext, postCaretContext)
+
+    if preCaretContext == "" {
+      /* The `textDocumentProxy` abstraction is documented (in passing) as involving
+       * inter-process communication.  It is thus asynchronous.  Despite all attempts to prod
```
Comment (jahorton) [inline ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift:331]: Source: https://developer.apple.com/documentation/uikit/keyboards_and_input/creating_a_custom_keyboard#3570264

> Custom keyboards run in an isolated process that doesn’t have direct access to the text input view. [...]

Also https://developer.apple.com/documentation/uikit/keyboards_and_input/creating_a_custom_keyboard/handling_text_interactions_in_custom_keyboards#overview.

Note:  neither is the actual documentation for `TextDocumentProxy`.

File: ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift [hunk 2]
```diff
@@ -294,18 +294,65 @@ open class InputViewController: UIInputViewController, KeymanWebDelegate {
...
-    
+
     let contextBeforeInput = textDocumentProxy.documentContextBeforeInput ?? ""
     let selection = textDocumentProxy.selectedText ?? ""
     let contextAfterInput = textDocumentProxy.documentContextAfterInput ?? ""
     let context = "\(contextBeforeInput)\(selection)\(contextAfterInput)"
-    let bLength = contextBeforeInput.utf16.count
-    let sLength = selection.utf16.count
+    let bLength = contextBeforeInput.count
+    let sLength = selection.count
```
Comment (mcdurdin) [inline ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift:303]: What's the purpose of this change? What is it fixing? I note there is no documentation on what units `setContextState` is expecting (UTF-16 code units, USV codepoints, something else?), nor any documentation on KeymanWeb's `keyman.context.setSelection()` either -- which is what is ultimately called here.

From my analysis, it _looks_ like `keyman.context.setSelection()` should be taking USV -- definitely not Swift's 'character' count which is based on graphemes.

```suggestion
    let bLength = contextBeforeInput.unicodeScalars.count
    let sLength = selection.unicodeScalars.count
```

File: ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift [hunk 3]
```diff
@@ -294,18 +294,65 @@ open class InputViewController: UIInputViewController, KeymanWebDelegate {
...
+    let preCaretContext = textDocumentProxy.documentContextBeforeInput ?? ""
+    let postCaretContext = textDocumentProxy.documentContextAfterInput ?? ""
+
+    let updater = { (_ before: String, _ after: String) -> Void in
+      let contextWindowText = "\(before)\(after)"
+
+      // On the KMW app/webview side, `location` is SMP-aware.
+      // .utf16:  treats SMPs as two char.  (Tested with U+1D5BA)
+      // Without .utf16 - treats SMPs as one char.
+      let range = NSRange(location: before.count, length: 0)
```
Comment (mcdurdin) [inline ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift:321]:
```suggestion
      let range = NSRange(location: before.unicodeScalars.count, length: 0)
```

File: ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift [hunk 4]
```diff
@@ -294,18 +294,65 @@ open class InputViewController: UIInputViewController, KeymanWebDelegate {
...
+
+      os_log("setContextState(text: `%@`, range initializer location: %d, range.location: %d", log: KeymanEngineLogger.engine, type: .debug, contextWindowText, before.count, range.location)
```
Comment (mcdurdin) [inline ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift:323]:
```suggestion
      os_log("setContextState(text: `%@`, range initializer location: %d, range.location: %d", log: KeymanEngineLogger.engine, type: .debug, contextWindowText, before.unicodeScalars.count, range.location)
```

File: ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift [hunk 5]
```diff
@@ -294,18 +294,65 @@ open class InputViewController: UIInputViewController, KeymanWebDelegate {
...
+       *
+       * 33ms seemed sufficient.  Can we go lower? (~30 Hz rate)
+       * Success with 20ms. (50 Hz rate)
+       * 1ms is not sufficient, nor is 10ms.   :(
+       *
+       * Note:  these notes were taken via Simulator, not on a physical device;
+       * there's no guarantee (yet) that the times will be the same.
+       * But something refresh-rate related is a fairly reasonable assumption.
+       */
+      DispatchQueue.main.asyncAfter(deadline: .now() + 0.33) { //0.033) {  // contrast:  held backspace - every 0.1.
```
Comment (mcdurdin) [inline ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift:345]: I can't imagine that this will be reliable -- if the device is busy for any reason then it's quite likely that we'll miss the deadline.

Also, isn't this 1/3 of a second, not 33 msec?

File: web/src/app/webview/src/contextManager.ts [hunk 6]
```diff
@@ -36,7 +36,11 @@ class ContextHost extends Mock {
   // changing the context's text.
   setText(text: string): void {
     this.text = text;
-    this.setSelection(this.text._kmwLength());
+    // Regardless of keyboard, we should check the SMP-aware length of the string.
+    // Our host app will not know whether or not the keyboard uses SMP chars,
+    // and we want a consistent interface for context synchronization between
+    // host app + app/webview KMW.
+    this.setSelection(this.text.kmwLength());
```
Comment (mcdurdin) [inline web/src/app/webview/src/contextManager.ts:43]: :+1:

**Review by mcdurdin — CHANGES_REQUESTED** [review]
I understand what you are aiming for here, but the timeout feels decidedly fragile.

I know that it may be that it is as good as we can get for now ... so would like some testing on various iOS devices. But given that this feels like a real bug in iOS, we should also open a bug report for Apple.

Requesting changes due to character vs unicodeScalars issues, from what I can tell.

File: ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift (hunk 5 above)
Comment (jahorton) [reply ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift:345]: > Also, isn't this 1/3 of a second, not 33 msec?

Oh, whoops.  Can fix that.

> I can't imagine that this will be reliable -- if the device is busy for any reason then it's quite likely that we'll miss the deadline.

And that's _**fine**_.  

If we miss it, we miss it and will require +1 backspace before the new context window becomes fully available.  That's the only penalty.  It would be _much_ worse if we tried to directly prod / manipulate the context, as _that_ would result in side-effects and far, far higher fragility due to the manipulations.

Comment (jahorton) [inline ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift:345]:
```suggestion
      DispatchQueue.main.asyncAfter(deadline: .now() + 0.033) { //0.033) {  // contrast:  held backspace - every 0.1.
```

Comment (mcdurdin) [reply ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift]: ok

File: ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift [hunk 7]
```diff
@@ -294,18 +294,65 @@ open class InputViewController: UIInputViewController, KeymanWebDelegate {
...
+       *
+       * 33ms seemed sufficient.  Can we go lower? (~30 Hz rate)
+       * Success with 20ms. (50 Hz rate)
+       * 1ms is not sufficient, nor is 10ms.   :(
+       *
+       * Note:  these notes were taken via Simulator, not on a physical device;
+       * there's no guarantee (yet) that the times will be the same.
+       * But something refresh-rate related is a fairly reasonable assumption.
+       */
+      DispatchQueue.main.asyncAfter(deadline: .now() + 0.033) { //0.033) {  // contrast:  held backspace - every 0.1.
```
Comment (mcdurdin) [inline ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift:345]:
```suggestion
      DispatchQueue.main.asyncAfter(deadline: .now() + 0.033) { // 33msec; contrast: held backspace - every 100 msec.
```

File: ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift (hunk 4 above)
Comment (jahorton) [reply ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift:323]:
```suggestion
```

I meant to remove this.

File: ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift (hunk 2 above)
Comment (jahorton) [reply ios/engine/KMEI/KeymanEngine/Classes/Keyboard/InputViewController.swift]: Ooh, good catch with the `.unicodeScalars` bit.  That does seem to be behaving more in line with what we want.

**Comment by jahorton** [comment]
> I know that it may be that it is as good as we can get for now ... so would like some testing on various iOS devices. But given that this feels like a real bug in iOS, we should also open a bug report for Apple.

Sadly, I doubt they'd consider it a bug.  It feels more like an API design limitation to me, easily interpretable as a feature request on our end.  Perhaps we can frame the `.hasText` detail as a bug - it really should say `true` even if there's no text within the current window.  It'd also help if `textDocumentProxy` updated as we got _close_ to a context window boundary, not just when we make edits beyond it.

That said, we can totally frame it in terms of normal held-backspace behaviors:  the Apple-provided system keyboard eventually does word-level, then phrase/sentence/paragraph level (not sure which) deletion the longer backspace is held.  Based on my observations, third-party keyboards literally cannot do so consistently - we can't tokenize context we can't see, so we'll land at bad locations periodically during held backspaces.  That wouldn't match behavior Apple users expect from the normal keyboard, and framing it _that_ way - consistency of user experience, like with their globe-key guidelines - might elicit a decent response.

**Comment by jahorton** [comment]
I have submitted FB13589120 via Apple's feedback assistant.

**Comment by mcdurdin** [comment]
Given this is @sgschantz's area of responsibility, I'd like him to approve this, thanks!

**Comment by jahorton** [comment]
> Given this is @sgschantz's area of responsibility, I'd like him to approve this, thanks!

So... should I just dismiss your review then, since it'll preserve your "changes requested" flag otherwise?

**Review by mcdurdin — APPROVED** [review]

**Comment by mcdurdin** [comment]
> So... should I just dismiss your review then, since it'll preserve your "changes requested" flag otherwise?

It LGTM but it needs to LGT@sgschantz as well :grin:

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_LONG_DELETION_SMP (PASSED):** Tested with the attached PR build (17.0.258-alpha-test-10633) in the iPhone 13 mobile device (iOS 17.1) and here is my observation: 1. Opened the PR page by scanning the QR code given in this PR. 2. Installed the PR build. 3. Opened the Keyman app and set Keyman as the system keyboard. 4. Opened Safari browser and switched to the default iOS system keyboard. 5. Opened the PR page, copied the given (long)text (eg., abc abc abc..), and pasted it into a new note / Notes app. 6. Switched to Keyman keyboard by using the globe key. 7. Hold down the Backspace key until no further deletions occur. 8. Verified that no texts appeared on the screen. Seems to be working fine.

**Review by sgschantz — APPROVED** [review]
LGTM

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.262-alpha](https://keyman.com/downloads/releases/alpha/17.0.262)
