### PR TITLE
chore(developer): validate emitted .keyboard_info and fix keys 🎺

### LINKED ISSUE #9620: chore(developer): Use keyboard_info.schema.json to validate output from kmc-keyboard-info 🎺

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #9620.

.keyboard_info keys emitted from kmc-keyboard-info had the wrong format for the example.keys object, which I discovered when I applied the validation to the kmc-keyboard-info output.

Other work arising from this PR, scheduled for a follow-up PR:
- [ ] #9640

@keymanapp-test-bot skip

### CODE REVIEW

File: common/web/types/src/package/kps-file.ts [hunk 1]
```diff
@@ -184,7 +184,17 @@ export interface KpsFileLanguageExample {
      */
     ID: string;
     /**
-     * A space-separated list of keys, modifiers indicated with "+", spacebar is "space", plus key is "shift+=" or "plus"
+     * A space-separated list of keys.
```
Comment (darcywong00) [inline common/web/types/src/package/kps-file.ts:187]: Is this now an array of KeyboardInfoFileExampleKey?

Comment (mcdurdin) [reply common/web/types/src/package/kps-file.ts:187]: No, this is as the comment describes. It gets converted by kmc-keyboard-info to KeyboardInfoFileExampleKey when building the .keyboard_info file.

File: developer/src/kmc-keyboard-info/test/fixtures/khmer_angkor/build/khmer_angkor.keyboard_info [hunk 2]
```diff
@@ -15,7 +15,13 @@
...
       },
       "examples": [{
-        "keys": "x j m E r",
+        "keys": [
+          { "key": "x" },
+          { "key": "j" },
+          { "key": "m" },
+          { "key": "E" },
+          { "key": "r" }
+        ],
```
Comment (jahorton) [inline developer/src/kmc-keyboard-info/test/fixtures/khmer_angkor/build/khmer_angkor.keyboard_info:24]: So, this was the main point of this PR, right?

It would be nice to have a test fixture that tests the modifiers part of `packageKeysExamplesToKeyboardInfo`; we're only testing the raw 'key' part of it with this specific test.

**Review by jahorton — APPROVED** [review]

File: developer/src/kmc-keyboard-info/test/fixtures/khmer_angkor/build/khmer_angkor.keyboard_info (hunk 2 above)
Comment (mcdurdin) [reply developer/src/kmc-keyboard-info/test/fixtures/khmer_angkor/build/khmer_angkor.keyboard_info:24]: Made this into a future issue: #9621.
