### PR TITLE
change(web): revert #11174, which loads keyboards before initializing the OSK

### LINKED ISSUE #11962: bug(web): Console error reading `modifierCodes` of undefined after installing custom Greek keyboard package
A user reports on the Community site forum experiencing Toast errors in Keyman for Android 18 after installing her [Greek keyboard package](https://www.tonizo.gr/keymangreek17/keymangr_all/build/keymangr_all.kmp).

She doesn't experience the error on iOS.
Keyboard functions fine though.

I can repro on the current master build on my Android 13 device.

Chrome console errors

image

```javascript
other-polyfills.js:1
Failed to load resource: net::ERR_FILE_NOT_FOUND 

keymangr_all.js:9 
Uncaught 
TypeError: Cannot read properties of undefined (reading 'modifierCodes')
    at new Keyboard_keymangr_all (keymangr_all.js:9:29)
    at keymangr_all.js:5:14

keyboardLoaderBase.ts:64 
Uncaught (in promise) 
Error: Error registering the keymangreek keyboard for Modern Greek (1453-); keyboard script at /data/user/0/com.tavultesoft.kmapro.debug/app_data/packages/keymangr_all/keymangr_all.js may contain an error.
    at _StubBasedErrorBuilder.scriptError (keyboardLoaderBase.ts:64:12)
    at script.onload (domKeyboardLoader.ts:58:39)

sentry.min.js:2 
range unchanged
```

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #11962.
Reverts #11174.
Reverts: #11258.

Debug-mode keyboards are not safe to load before the OSK is initialized due to certain debug APIs being published _through_ `keyman.osk`.  The cleanest way to remedy #11962 is thus to revert the PR that attempts to load keyboards before the OSK is initialized.

There were a few merge conflicts that resulted when reverting a few of the commits, though nothing terribly extensive.  Still, it'd be best to test and verify that the reversion process was handled correctly.

## User Testing

**TEST_REPRO**:  Attempt to reproduce #11962 using Keyman for Android.

- Install the package provided within that issue.
- Force-quit the app.
- Relaunch the app.
    - If the issue is not properly fixed, an error notification will appear on app-relaunch.

**TEST_ANDROID**:   Do simple general-use testing with Keyman for Android and report back if any odd behaviors occur.

**TEST_IOS**: Do simple general-use testing with Keyman for iOS and report back if any odd behaviors occur.

**TEST_WEB**:  Do simple general-use testing with the "Test unminified Web" test page and report back if any odd behaviors occur.

### CODE REVIEW

**Comment by dinakaranr** [comment]
# Test Results

I tested this issue with the attached "Keyman 18.0.75" build on the Android 14 & iPhone and the web(Chrome & Firefox) Here is my observation.

* **TEST_REPRO (Passed):** 
1. Install the "Keyman 18.0.75-alpha-test-12015" build.
2. Relaunch the app after a force quit. 
No error notification appears when forced to quit the app.

* **TEST_ANDROID (passed):**
1. Installed the "Keyman-18.0.75.apk" file and gave all permissions to the application.
2. Checked the "Enable Keyman as system-wide keyboard" and set the keyboard as the default keyboard box on the settings page.
3. Open the Keyman app. Enable the "Predictions" and install the "Dictionary."
4. Added a sentence to the notepad and Chrome (search).
5. Enter a word and observe that the word is highlighted on the banner. 
6. Press the "Spacebar" and then the word added. 
7. The word is selecting using a cursor from left to right and right to left. 
8. Keyboard works on portarit and landscape viewport. Keyboard set as system keyboard.
9. Installed/uninstalled multiple keyboards.
It works as per expected behavior.

* **TEST_IOS (passed):**
1. Installed the "Keyman-18.0.75" build from testflight app and gave all permissions to the application.
2. Checked the "Enable Keyman as system-wide keyboard" and set the keyboard as the default keyboard box on the settings page.
3. Open the Keyman app. Enable the "Predictions" and install the "Dictionary."
4. Added a sentence to the notepad and Chrome (search).
5. You can just enter a word and observe that the word is highlighted on the banner. 
6. Press the "Spacebar" and then the word added. 
7. The word is selected using a cursor from left to right and right to left. 
8. The keyboard works on portrait and landscape viewport. Keyboard set as system keyboard.
9. Installed/uninstalled multiple keyboards.
It works as per expected behavior.

* **TEST_WEB (Passed):**
1. Navigate to the "Tests unminified Keymanweb" --> "KeymanWeb Sample Page - Unminified Source" pages.
2. "English - English": It works well in the text box and OSK keyboard.
3. "Lao - Lao Basic": It works well in the text box and OSK keyboard.
4. "English - Classic 10-key": OSK board appears but it is blank now. An alert window appears for very few seconds.
It works in Khmer and French keyboard too. Thank you.

**Review by ermshiperete — APPROVED** [review]

File: web/src/app/browser/src/keymanEngine.ts
Comment (mcdurdin) [inline web/src/app/browser/src/keymanEngine.ts:1]: ll.78-80 are technically not rolled back. Not harmful, but makes it harder to compare rollback completeness.

File: web/src/engine/osk/src/views/oskView.ts [hunk 1]
```diff
@@ -254,22 +253,10 @@ export default abstract class OSKView
...
-    if(modelState) {
-      this.bannerController.selectBanner(modelState);
-    }
-
     this.setBaseMouseEventListeners();
     if(this.hostDevice.touchable) {
       this.setBaseTouchEventListeners();
     }
-
-    this._Box.style.display = 'none';
```
Comment (mcdurdin) [inline web/src/engine/osk/src/views/oskView.ts:271]: This line was not added in #11174; it was added in #11258. So, this PR should note: 

Reverts: #11258

**Review by mcdurdin — APPROVED** [review]
LGTM, additionally:
* Somewhat unimportant changes to oskKey.ts were not rolled back (ll.321,324,334), see #11174

File: web/src/engine/osk/src/views/oskView.ts (hunk 1 above)
Comment (jahorton) [reply web/src/engine/osk/src/views/oskView.ts:271]: Good catch, but in the other direction; I believe this line should not be reverted, then.  Keeping `display: none` active on initialization helps prevent layout reflow / thrashing while we want on the "true" first keyboard to be set for loading.

Comment (mcdurdin) [reply web/src/engine/osk/src/views/oskView.ts:271]: I'd want to see that come in as a separate PR with its own testing. My purpose here is to revert to a known-good state, not a presumably-good state.

Comment (jahorton) [reply web/src/engine/osk/src/views/oskView.ts:271]: I'd like to point out that when I built the reversion, I did have to resolve a few merge conflicts.  I'd have to double-check, but there's a decent chance that this may have been one of the spots I had to resolve.

As you've pointed out, that line's removal is from a different PR than was intended for reversion - one which _precedes_ the reversion target in history.  These facts make me suspect that deleting this line would quality for the "presumably-good state" instead.

Comment (jahorton) [reply web/src/engine/osk/src/views/oskView.ts:271]: Had a comment here I just deleted; got my history order wrong; please ignore any email notifications about that.

Comment (jahorton) [reply web/src/engine/osk/src/views/oskView.ts:271]: Yay for an incoming reversion-reversion in the near future, then.

Comment (mcdurdin) [reply web/src/engine/osk/src/views/oskView.ts:271]: Probably, that's life. But given that PR built on this one and seems linked to the change, I still would like to err on the side of caution, particularly because we are back-porting to 17.0.

Really happy to see it reintroduced in 18.0 alpha and go through test.

File: web/src/app/browser/src/keymanEngine.ts
Comment (jahorton) [reply web/src/app/browser/src/keymanEngine.ts:1]: Yeah, I felt it would be _more_ harmful to roll back the null-guard.

**Comment by jahorton** [comment]
> * Somewhat unimportant changes to oskKey.ts were not rolled back (ll.321,324,334), see

Keep in mind that #11174 predates the TS-strictness PR set.  I left those parts in place because they aligned quite well with the TS-strictness efforts.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.78-alpha](https://keyman.com/downloads/releases/alpha/18.0.78)
