### PR TITLE
[iOS] Model installation - use of package version (12.0 stable)

### LINKED ISSUE #2192: [iOS] Lexical models fail to install because lexical model version no longer generated
This parallels #2190, but for iOS instead of Android.

**Describe the bug**
User reported issue from [community site](https://community.software.sil.org/t/installation-of-predictive-text-package-in-keyman-for-android/2649)

Lexical models built with Keyman Developer 12.0.50 stable no longer include lexical model versions (they use the lexical model package version).

However, the Android and iOS apps were developed to expect a lexical model version, so this is causing the new model packages to fail at installation.

(The published models on downloads.keyman.com/models haven't been updated with the new lexical model compiler so they currently contain model version info)

Install a Mozhi Malayalam keyboard for testing.

Testing with a model package built from
https://my.pcloud.com/publink/show?code=kZlX3LkZpVxg32Gpk4BRIGIW5M7hhBSpWXik

### Fix
The fix is to use the package version "info/version/description" for the lexical model version.
If package version doesn't exist, fall back to "1.0"

### Configuration
Keyman Developer 12.0.50 Stable
Keyman iOS 12.0.50 Stable

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #2192 for 12.0 stable.

### CODE REVIEW

File: ios/engine/KMEI/KeymanEngine/Classes/Manager.swift [hunk 1]
```diff
@@ -697,11 +697,26 @@ public class Manager: NSObject, UIGestureRecognizerDelegate {
...
+          if let versionEntry = info["version"] as? [String:AnyObject] {
+            if let description = versionEntry["description"] as? String {
+              version = description;
+            }
+          }
+        }
+
+        // Version uses a 'conditional initializer'.  If it fails, the version info is invalid.
+        guard let _ = Version(version) else {
+          // Marc's decision - lazy-handle the error and replace version with 1.0.
```
Comment (mcdurdin) [inline ios/engine/KMEI/KeymanEngine/Classes/Manager.swift]: Hmph. Just so you know, I made that decision in about 2005.
