### PR TITLE
fix(web): clear longpress timeout if user does a flick up

### LINKED ISSUE #5950: bug(web): highlights may not be cleared on base keys if user flicks to a longpress menu
**Describe the bug**

If the user flicks up to access a longpress menu before the longpress delay expires, the base key may become 'stuck' highlighted after they end the touch gesture:

image

Originally discovered by @sgschantz.

---

**KeymanWeb:**
 - KeymanWeb Version: 15.0-alpha

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #5950.

If a user starts a longpress gesture and then flicks up, that immediately brings up the longpress menu, and the timeout for display of the menu should be cancelled -- otherwise the end result is a key that stays 'stuck' on.

# User Testing

1. Test longpress menus in a keyboard such as sil_euro_latin, both by waiting for the menu to appear, and also by flicking up.
2. Try various combinations to get it to leave a highlighted key.
3. These tests pass if no key is ever left highlighted after ending the touch gesture.

* TEST_IOS: Run the test above in Keyman for iOS (system and/or in-app keyboard).
* TEST_ANDROID: Run the test above in Keyman for Android (system and/or in-app keyboard).
* TEST_WEB: Run the test above in KeymanWeb (testing/unminified), on a mobile device or emulating in Chrome.

### CODE REVIEW

File: web/source/osk/visualKeyboard.ts [hunk 1]
```diff
@@ -819,7 +819,7 @@ namespace com.keyman.osk {
       }
 
       if (this.keyPending) {
-        if (key0 != key1 || key1.className.indexOf('kmw-key-touched') < 0) {
+        if (key0 != key1 || key1.className.indexOf(OSKKey.HIGHLIGHT_CLASS) < 0) {
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:822]: This is just a consistency update to use a constant instead of inline string; no functional change.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by MakaraSok** [comment]
* **TEST_IOS: PASSED** No key left highlighted after triggering the subkeys and flicking up.
* **TEST_ANDROID: PASSED** No key left highlighted after triggering the subkeys and flicking up.
* **TEST_WEB: PASSED** No key left highlighted after triggering the subkeys and flicking up.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.155-alpha](https://keyman.com/downloads/releases/alpha/15.0.155)
