### PR TITLE
fix(web): sticky special-key highlighting

### LINKED ISSUE #10687: bug(ios): The keys turned blue after being dragged upward from the space bar key to any other key
### Describe the bug

I noticed that when I dragged a key upward from the space bar to any other key while keeping it pressed down, the keys turned blue.

### Reproduce the bug

1. Install Keyboard 17.0.164-alpha build.
2. Open Keyman In-App.
3. Close the "Get Started" menu.
4. Long press any key, then drag up while keeping the key pressed, then release doesn't show up impact on the keys. 
5. Long press the Space bar key, and drag upwards (while keeping the key pressed) to any key impact that key to change its color into blue.

Here, I noticed that the key we touched, changed to blue color. 

I have attached the Screenshot as well as the Video file for reference. 

..Key changed to blue color

   

..Key color changed

https://github.com/keymanapp/keyman/assets/19683143/f32dbf8e-08cd-4437-8f72-18dcd56b5d95

### Expected behavior

The key should remain unaffected after being dragged up from the spacebar key to any other key.

### Related issues

_No response_

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.164-alpha

### Operating system

ios 15.5, ios 17.0

### Device

iPhone 13, iphone 15 Pro Max Simulator (iOS 17.0)

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### LINKED ISSUE #10703: bug(web): roaming touch from spacebar over frame keys leaves sticky highlighting
image

Starting a touch on the space bar and dragging it over the highlighted keys before reaching the banner leaves those keys highlighted.  Notably, these are all the keys that don't do key previews.

_Originally posted by @jahorton in https://github.com/keymanapp/keyman/issues/10695#issuecomment-1942938873_

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #10687.
Fixes #10703.

## User Testing

TEST_STICKY_SPECIAL_HIGHLIGHTS:  Verify that special key highlighting is no longer 'sticky'.

1. Using the EuroLatin (SIL) keyboard within the Keyman for Android app...
2. Start a touch on the space bar...
3. ...and drag it over the globe and shift keys before reaching the banner leaves those keys highlighted.
4. Verify that no keys are highlighted at the end of this sequence.
5. Verify that there was no point in time where two keys were simultaneously highlighted.

### CODE REVIEW

File: web/src/engine/osk/src/visualKeyboard.ts [hunk 1]
```diff
@@ -489,8 +489,8 @@ export default class VisualKeyboard extends EventEmitter<EventMap> implements Ke
           if(previewHost) {
             this.gesturePreviewHost = previewHost;
             trackingEntry.previewHost = previewHost;
-            sourceTrackingMap[source.identifier].key = key;
           }
+          sourceTrackingMap[source.identifier].key = key;
```
Comment (jahorton) [inline web/src/engine/osk/src/visualKeyboard.ts:493]: Note line 481 - we need to update the key we just highlighted even if we don't show a preview for it.  That's the only change needed.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_STICKY_SPECIAL_HIGHLIGHTS (PASSED):** Tested with the attached PR build (17.0.269-beta-test-10729) on an iPhone 13 Mobile device and here are my observation: 1. Started a touch on the space bar and dragged it over the globe and shift keys (ie., dragged it from clockwise direction) before reaching the banner and verified that no keys were highlighted at the end of this sequence. 2. Confirmed that there was no moment when two keys were simultaneously highlighted. Seems to be working fine.

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.271-beta](https://keyman.com/downloads/releases/beta/17.0.271)
