### PR TITLE
fix(android/engine): Skip updating selection range if invalid

### LINKED ISSUE #11360: bug(android): selected-text handling crashes, continued
Sentry event: https://keyman.sentry.io/share/issue/a08bf2d9be184cc9b6de5d0ae31b5924/

> ### StringIndexOutOfBoundsException
> begin 0, end -1, length 0
>
> _java.lang.String in substring at line 2517_
> _com.keyman.engine.KMKeyboard in updateSelectionRange at line 207_

_After_ merging in #11345, we're still getting crashing events - the link above is based on 17.0.319-beta.

```
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
    at java.lang.String.checkBoundsBeginEnd(String.java:4466)
    at java.lang.String.substring(String.java:2517)
    at com.keyman.engine.KMKeyboard.updateSelectionRange(KMKeyboard.java:207)
    at com.keyman.engine.KMManager.updateSelectionRange(KMManager.java:2173)
    at com.keyman.android.SystemKeyboard.onStartInput(SystemKeyboard.java:173)
    at android.inputmethodservice.InputMethodService.doStartInput(InputMethodService.java:3206)
    at android.inputmethodservice.InputMethodService$InputMethodImpl.startInput(InputMethodService.java:832)
    at android.inputmethodservice.InputMethodService$InputMethodImpl.dispatchStartInput(InputMethodService.java:861)
    at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:197)
    at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:257)
    at android.os.Looper.loop(Looper.java:368)
    at android.app.ActivityThread.main(ActivityThread.java:8826)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

Following the stack trace, we reach the following sections:

https://github.com/keymanapp/keyman/blob/0a28678c5324fbe5ea8aec5e129df48f9c8b080c/android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java#L188-L193

https://github.com/keymanapp/keyman/blob/0a28678c5324fbe5ea8aec5e129df48f9c8b080c/android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java#L206-L209

... so, `selMin` - either `selectionStart` or `selectionEnd` - can be -1?  That doesn't sound right... and unfortunately, there's nothing about the possibility in official documentation.  It doesn't sound like something that should be possible... but that's the only way I can see getting the negative value here.  We may need to prod around a bit and see if we can get confirmation about this.

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #11360

@mcdurdin went spelunking in the Android code and found `getSelectionStart()` and `getSelectionEnd()` return -1 if there's no selection or cursor.
Reference https://developer.android.com/reference/android/text/Selection#getSelectionEnd(java.lang.CharSequence

In those cases (likely a race condition), we should no-op on `updateSelectionRange()` since there's no valid selection to pass to KeymanWeb.

## User Testing (from #11360)
**Setup** - Install PR build of Keyman for Android and enable Keyman as the default system keyboard

* **TEST_INVERTED_SELECTION_RANGE**: Using Keyman for Android as a system keyboard, ensure that backwards selection ranges do not crash the keyboard.
1. Select text, then drag one of the end points through and past the other one.
2. If the keyboard immediately disappears, or you see an error notification, FAIL this test.

### CODE REVIEW

**Review by jahorton — APPROVED** [review]

File: android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java [hunk 1]
```diff
@@ -185,6 +185,12 @@ protected boolean updateSelectionRange() {
       int selStart = icText.selectionStart;
       int selEnd = icText.selectionEnd;
 
+      if (selStart < 0 || selEnd < 0) {
+        // There is no selection or cursor
+        // Reference https://developer.android.com/reference/android/text/Selection#getSelectionEnd(java.lang.CharSequence)
+        return false;
+      }
+
       int selMin = selStart, selMax = selEnd;
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java:194]: Personally, I'd like to eliminate the `selStart` and `selEnd` variables. They just add potential for error.

```suggestion
      int selMin = icText.selectionStart, selMax = icText.selectionEnd;

      if (selMin < 0 || selMax < 0) {
        // There is no selection or cursor
        // Reference https://developer.android.com/reference/android/text/Selection#getSelectionEnd(java.lang.CharSequence)
        return false;
      }

      if(selMin > selMax) {
        selMin = icText.selectionEnd;
        selMax = icText.selectionStart;
      }
```

I can't do this suggestion across the whole range of this.

Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java:194]: Similarly, we should eliminate the `result` variable, and short-circuit the input conditions:

```java
    InputConnection ic = KMManager.getInputConnection(this.keyboardType);
    if (ic == null) {
      // TODO: please explain
      return true;
    }

    ExtractedText icText = ic.getExtractedText(new ExtractedTextRequest(), 0);
    if (icText == null) {
      // TODO: please explain
      return false;
    }

    // ... the rest of the function goes here ...

    return true;
```

Why do we return true when ic == null?

**Comment by dinakaranr** [comment]
# Test Results

* **TEST_INVERTED_SELECTION_RANGE (PASSED):** I tested this issue with the attached "Keyman 17.0.320-beta-test-11384" build on an Android 14 environment: Here is my observation.
1. Installed the "keyman-17.0.320.apk" file and gave all permissions to the application.
2. Checked the "Enable Keyman as system-wide keyboard" and set the keyboard as the default keyboard box on the settings page. 
3. Open the Chrome browser and then enter some text in the address bar.
4. The keyboard did not disappear when selecting some text from right to left and left to right. The keyboard stays on the screen while dragging the text selection.

Note: The reverse text selection does not happen from one point to another. It's restricted to the last letter of the word. I observed this behavior in Android 13 (Physical Device) and emulator devices in Android 9 and 12 versions.
However, it worked well, and I passed this test case. Thanks.

File: android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java (hunk 1 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java:194]: Refactoring addressed in #11389. Also fixes to return false if ic == null.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.321-beta](https://keyman.com/downloads/releases/beta/17.0.321)
