### PR TITLE
fix(web): OSK key preview positioning

### LINKED ISSUE #3953: bug(web/engine): native-mode iOS key preview mispositioning
**Describe the bug**
If a web page has been vertically scrolled, key previews for the keyboard will not be positioned correctly.  (In particular, the y-coordinate.)

**To Reproduce**
1. Load the in-repo testing page found at `web/testing/unminified.html` on an iOS device.
2. Scroll down the page a bit.  (A smaller device, such as an iPhone SE, may facilitate this - the page may be too short on larger devices.)
2. Click and hold a key.
3. The key preview will be incorrectly positioned.

**Expected behavior**
The key preview should appear to 'pop out' of the key being pressed.  (Compare against the key preview positioning seen when no page scrolling has occurred.)

**Screenshots**

Image from iOS (3)

---

**KeymanWeb:**
 - Device: any
 - OS: (probably) any
 - Keyman version: 14.0 (current alpha, _possibly_ 13.0?  I remember seeing this type of behavior before.)
 - URL:  (probably) any; `web/testing/unminified.html` will suffice.

This is easily replicated by Chrome emulation of an iOS device.

---
 
**Keyboard**
 - Any keyboard providing popup keys.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #3953.

This changes the key preview positioning logic to better parallel the subkey-display positioning logic, as only the former was affected by the bug being fixed.

### CODE REVIEW

File: web/source/osk/visualKeyboard.ts [hunk 1]
```diff
@@ -2365,7 +2365,8 @@ namespace com.keyman.osk {
       canvas.height = 2.3 * xHeight;
 
       kts.top = 'auto';
-      kts.bottom = (y0 + h0 - xTop - xHeight)+'px';
+      // Matches how the subkey positioning is set.
+      kts.bottom = (parseInt(key.style.bottom, 10))+'px';
```
Comment (jahorton) [inline web/source/osk/visualKeyboard.ts:2369]: Compare against the `showSubKeys` version:

https://github.com/keymanapp/keyman/blob/4da1454937c498c9cf59a55afbabd14bffa89dba/web/source/osk/visualKeyboard.ts#L1509-L1512

The key preview's 'bottom' needs to match the bottom of the base key, not the top - this is why the "height" part of the line is not included here.

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.222-beta](https://keyman.com/downloads/releases/beta/14.0.222)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.9-alpha](https://keyman.com/downloads/releases/alpha/15.0.9)
