### PR TITLE
fix(developer): compiler mismatch on currentLine

### LINKED ISSUE #7122: bug(developer): Debugger doesn't step through normalise rules in Khmer Angkor keyboard
When using the debugger it's possible to step through the rules after a keystroke and see which one applies. However when the processing gets to the normalise group the location shows up in line 227 between a comment and a rule in the main group instead of showing the normalise rule that gets applied.

- Keyman Developer 15.0.268
- Khmer Angkor keyboard from [keyboards repo](https://github.com/keymanapp/keyboards/tree/master/release/k/khmer_angkor)

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #7122.

The compiler was updating currentLine when checking for unreachable rules, but not restoring it afterwards. This led to mismatches in the debugger and in compiler warnings.

# User Testing

TEST_SINGLE_STEP: Verify that single step in the debugger no longer ends up on the wrong line

1. Load khmer_angkor.kmn in Keyman Developer, and start debugging (<kbd>F5</kbd>).
2. Type <kbd>x</kbd><kbd>E</kbd><kbd>j</kbd>
3. Turn on the Single Step mode from Debug menu.
4. Type <kbd>m</kbd>, and step through with Debug/Step Forward.
5. Step forward through to the `normalise` group, and then verify that the next step shows the correct rule that is applied, not a blank line.

### CODE REVIEW

**Comment by mcdurdin** [comment]
@SabineSIL we will need to cherry-pick this fix into your kmcompx branch. Let me know if you would like assistance with that :grin:.

**Comment by bharanidharanj** [comment]
* **TEST_SINGLE_STEP (PASSED):** Tested this with Keyman Developer 16.0.55-alpha-test-7190 build as per the instructions. Verified that the next step shows a rule and not showing any blank line in the window.

File: developer/src/kmcmpdll/DeprecationChecks.cpp [hunk 1]
```diff
@@ -25,7 +25,7 @@ BOOL CheckForDeprecatedFeatures(PFILE_KEYBOARD fk) {
       // Keyman 7
       #define TSS_WINDOWSLANGUAGES 29
   */
-  int currentLineBackup = currentLine;
+  int oldCurrentLine = currentLine;
```
Comment (mcdurdin) [inline developer/src/kmcmpdll/DeprecationChecks.cpp:28]: Just making the backup variable name consistent -- same pattern used in three places. The currentLine change is made for error reporting.

**Review by rc-swag — APPROVED** [review]
lgtm

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.61-alpha](https://keyman.com/downloads/releases/alpha/16.0.61)
