### PR TITLE
fix(web): inferred key text + spacebar caption scaling

### LINKED ISSUE #7615: bug(web): inferred key text does not get scaled correctly
### Describe the bug

It is possible, although somewhat hidden, to infer the key cap text on a touch layout key from the identifier, if the ID starts with `U_`. (I say hidden, because the touch layout editor tends to mask this by filling in the text.)

While oskKey.ts supports this through `generateKeyText`, in `getIdealFontSize`, `spec.text` is used rather than the correct calculated value as used in `generateKeyText`:

https://github.com/keymanapp/keyman/blob/badf5e6d4b30e3bc5e4a55d6c5d82b11bf6aaab4/web/source/osk/oskKey.ts#L429-L445

A secondary, more minor issue is that `unicodeKeyIdToString()` may crash if the key id is malformed (we should be testing `!isNaN(codePointValue)` as well before calling `String.kmwFromCharCode()`.

For example, the key on the left is using inferred key text, from key id `U_1234_1234_1234_1234_1234`, whereas the key on the right has the key text value `U+1234 U+1234 U+1234 U+1234 U+1234`. This font size difference is also be reflected in the key preview.

image

### Reproduce the bug

_No response_

### Expected behavior

The best way to fix this may be to fill in the inferred data at touch layout load time.

### Related issues

_No response_

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [X] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.271

### Operating system

_No response_

### Device

_No response_

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

The following keyboards in the repo may be impacted by this, found in a cursory search (possibly incomplete). It seems likely that they will not have significant font scaling issues. But worth checking them when we address this.

---

Search regex: `"text": "".*\n.*"id": "U_`
```
13 results - 1 file  

release\sil\sil_sahu\source\sil_sahu.keyman-touch-layout:
   23                    {
   24:                     "text": "",
   25:                     "id": "U_025B"
   26                    }

   41                    {
   42:                     "text": "",
   43:                     "id": "U_0272"
   44                    }

   51                    {
   52:                     "text": "",
   53:                     "id": "U_028A"
   54                    }

   61                    {
   62:                     "text": "",
   63:                     "id": "U_0268"
   64                    }

   71                    {
   72:                     "text": "",
   73:                     "id": "U_0254"
   74                    }

   91                    {
   92:                     "text": "",
   93:                     "id": "U_0276"
   94                    }

  101                    {
  102:                     "text": "",
  103:                     "id": "U_02A7"
  104                    }

  115                    {
  116:                     "text": "",
  117:                     "id": "U_0257"
  118                    }

  150                    {
  151:                     "text": "",
  152:                     "id": "U_02A5"
  153                    }

  192                    {
  193:                     "text": "",
  194:                     "id": "U_02A6"
  195                    }

  210                    {
  211:                     "text": "",
  212:                     "id": "U_0253"
  213                    }

  220                    {
  221:                     "text": "",
  222:                     "id": "U_014B"
  223                    }

  248                    {
  249:                     "text": "",
  250:                     "id": "U_02A1"
  251                    },
```

Search regex: `"id": "U_.+\n.*"text": ""`

```
27 results - 7 files

release\basic\basic_kbdbe\source\basic_kbdbe.keyman-touch-layout:
  598                {
  599:                 "id": "U_00B0",
  600:                 "text": "",
  601                  "layer": "rightalt"

  603                {
  604:                 "id": "U_005F",
  605:                 "text": "",
  606                  "layer": "rightalt"

release\basic\basic_kbdhe\source\basic_kbdhe.keyman-touch-layout:
  743                {
  744:                 "id": "U_003C",
  745:                 "text": ""
  746                },

release\i\indigenous_nt\source\indigenous_nt.keyman-touch-layout:
  1256                {
  1257:                 "id": "U_00A0",
  1258:                 "text": "",
  1259                  "width": "520"

release\j\jawa\source\jawa.keyman-touch-layout:
   749                {
   750:                 "id": "U_0020",
   751:                 "text": "",
   752                  "width": "215"

  1030                {
  1031:                 "id": "U_0020",
  1032:                 "text": "",
  1033                  "pad": "",

  1235                {
  1236:                 "id": "U_0020",
  1237:                 "text": "",
  1238                  "width": "215"

release\nrc\nrc_crk_cans\source\nrc_crk_cans.keyman-touch-layout:
   116                {
   117:                 "id": "U_202F",
   118:                 "text": "",
   119                  "sp": "1",

   320                {
   321:                 "id": "U_202F",
   322:                 "text": "",
   323                  "sp": "1",

   526                {
   527:                 "id": "U_202F",
   528:                 "text": "",
   529                  "sp": "1",

   733                {
   734:                 "id": "U_202F",
   735:                 "text": "",
   736                  "sp": "1",

   939                {
   940:                 "id": "U_202F",
   941:                 "text": "",
   942                  "sp": "1",

  1146                {
  1147:                 "id": "U_202F",
  1148:                 "text": "",
  1149                  "sp": "1",

  1352                {
  1353:                 "id": "U_202F",
  1354:                 "text": "",
  1355                  "sp": "1",

  1559                {
  1560:                 "id": "U_202F",
  1561:                 "text": "",
  1562                  "sp": "1",

  1765                {
  1766:                 "id": "U_202F",
  1767:                 "text": "",
  1768                  "sp": "1",

  1972                {
  1973:                 "id": "U_202F",
  1974:                 "text": "",
  1975                  "sp": "1",

  2178                {
  2179:                 "id": "U_202F",
  2180:                 "text": "",
  2181                  "sp": "1",

  2385                {
  2386:                 "id": "U_202F",
  2387:                 "text": "",
  2388                  "sp": "1",

  2591                {
  2592:                 "id": "U_202F",
  2593:                 "text": "",
  2594                  "sp": "1",

  2798                {
  2799:                 "id": "U_202F",
  2800:                 "text": "",
  2801                  "sp": "1",

  3004                {
  3005:                 "id": "U_202F",
  3006:                 "text": "",
  3007                  "sp": "1",

  3211                {
  3212:                 "id": "U_202F",
  3213:                 "text": "",
  3214                  "sp": "1",

  3417                {
  3418:                 "id": "U_202F",
  3419:                 "text": "",
  3420                  "sp": "1",

  3624                {
  3625:                 "id": "U_202F",
  3626:                 "text": "",
  3627                  "sp": "1",

release\o\old_hungarian\source\old_hungarian.keyman-touch-layout:
  997                {
  998:                 "id": "U_0023",
  999:                 "text": ""
  1000                },

release\sil\sil_torwali\source\sil_torwali.keyman-touch-layout:
  1133                {
  1134:                 "id": "U_08FF",
  1135:                 "text": "",
  1136                  "sp": "9"
```

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #7615.

Also fixes a highly-related issue with spacebar captions; I've noted that the text will often overflow in embedded contexts.  It's not a perfect fix, as there appears to be a minimum text size allowed by browsers, but it's definitely an improvement for affected cases.  `gff_amharic` makes a fantastic example for this due to its relatively narrow spacebar; I'd noticed this tidbit while working on other recent issues.

With the fix:

image

Without it:

image

----

Meanwhile, when there is sufficient space:

With the fix:
image

Without it:
image

Here, the padding-maintenance logic kicked in and shrunk this case a bit more than necessary, but it at least demonstrates the level of effect to expect.

----

Finally, for an extremely contrived but obvious example...

image

Note that I've retooled the old test page (for the  _highly_ related #382, which kicked off the key-cap scaling feature) and its keyboard to better test #7615.

----

## User Testing

- **TEST_KEYCAP_SCALING**
    1. Using Chrome's remote-device emulation... 
    2. Load Web's "Test page for automatic key-cap scaling".
    3. Click the "Type here" element to display the keyboard.
    4. Verify that the first two keys between the "g" and "l" keys appear identical, with both displaying the same character 5 times.
    5. Verify that the full word "Keyman" is visible on the key immediately left of the "l".

- **TEST_SPACEBAR_SCALING**
    1. Using Chrome's remote-device emulation...
    2. Load Web's "Test page for automatic key-cap scaling".
    3. Click the "Type here" element to display the keyboard.
    4. Verify that no text runs off either edge of the spacebar.
       - The full text: `English - Keycap Scaling Test with a really long name in order to also test captions`

- **TEST_IN_APP_SPACEBAR_SCALING**
    1. Using the Android app on a **tablet** form-factor device...
    2. Go to Settings => Spacebar caption and select "Language + Keyboard".
    3. Using Settings => Install Keyboard or Dictionary => Install from keyman.com, install `gff_amharic`.
    4. Verify that no text runs off either edge of the spacebar.

### CODE REVIEW

**Comment by mcdurdin** [comment]
> as there appears to be a minimum text size allowed by browsers

There's also a minimum text size that is readable. I'm not sure I can read the text on the first Amharic image, but whether that's downscaling in the emulator or because it's too small I don't know!

File: web/source/osk/oskKey.ts [hunk 1]
```diff
@@ -399,42 +399,19 @@ namespace com.keyman.osk {
...
       // Add OSK key labels
-      var keyText;
-      var t = document.createElement('span'), ts=t.style;
+      let keyText = null;
       if(spec['text'] == null || spec['text'] == '') {
-        keyText='\xa0';  // default:  nbsp.
         if(typeof spec['id'] == 'string') {
           // If the ID's Unicode-based, just use that code.
-          keyText = this.unicodeKeyIdToString(spec['id']) || keyText;
+          keyText = keyboards.ActiveKey.unicodeIDToText(spec['id']) || DEFAULT_BLANK;
```
Comment (mcdurdin) [inline web/source/osk/oskKey.ts:411]:
```suggestion
          keyText = keyboards.ActiveKey.unicodeIDToText(spec['id']);
```

Line 414 does `|| DEFAULT_BLANK` again anyway.

File: web/source/osk/oskKey.ts [hunk 2]
```diff
@@ -513,8 +500,19 @@ namespace com.keyman.osk {
...
+        if(!this.label.classList.contains('kmw-spacebar-caption')) {
+          this.label.style.fontSize = this.getIdealFontSize(vkbd, this.keyText, this.btn.style);
+        } else {
+          // Remove any custom setting placed on it before recomputing its inherited style info.
+          this.label.style.fontSize = '';
+          const fontSize = this.getIdealFontSize(vkbd, this.label.textContent, getComputedStyle(this.label), true);
+
+          // Since the kmw-spacebar-caption version uses !important, we must specify
+          // it directly on the element too; otherwise, scaling gets ignored.
+          this.label.style.setProperty("font-size", fontSize, "important");
```
Comment (mcdurdin) [inline web/source/osk/oskKey.ts:514]: Is line 509 redundant given line 514? And if not, does that mean that line 506 will have problems if line 514 is ever run?

**Review by mcdurdin — APPROVED** [review]
Only nits, LGTM

File: web/source/osk/oskKey.ts (hunk 2 above)
Comment (jahorton) [reply web/source/osk/oskKey.ts:514]: See line 508 and contrast with this part of 510:  `getComputedStyle(this.label)`.

509 is preventing 510's "computed style" op from reusing a previous font size setting applied to the label.  This matters when it comes to resize events, rotation events, etc.  Key cap scaling should be based on the styles _inherited_ by the label element **_and from kmwosk.css_**.  This last part is the important thing to catch - `kmw-spacebar-caption` applies font-size scaling, while `kmw-key-text` does not:

https://github.com/keymanapp/keyman/blob/f3788d86be2ea6dcdc4420f964fb0653cf049764/web/source/resources/osk/kmwosk.css#L530

Well, re `kmw-key-text`, there is one exception:

https://github.com/keymanapp/keyman/blob/f3788d86be2ea6dcdc4420f964fb0653cf049764/web/source/resources/osk/kmwosk.css#L326-L328

So, when `kmw-key-text` _does_ set font-scaling, it's actually to _prevent_ scaling, so the base assumption of "1 em" unit default scaling holds everywhere... but for the spacebar caption.  Line 509 simply enforces this assumption for consistency.

Our existing key-text / caption scaling logic assumes that style information provided to it defines the original (and maximum) desired font size.  So... if the caption's scale was set in 'portrait' (which will generally require smaller size) and then set to landscape, that would likely cause landscape to reuse the smaller 'portrait' scaling rather than the scaling it would have had if the keyboard were first loaded in landscape.  That's an inconsistency that would appear buggy to end users.

Also, line 509 prevents us from having to combine 'old' and 'new' scaling with extra logic, like might occur going from landscape to portrait.  Setting the initial scale to 1 means we can let the browser handle those calculations for us.

------

Now, that said...

Comment (mcdurdin) [reply web/source/osk/oskKey.ts:514]: Gotcha.

**Comment by bharanidharanj** [comment]
* **TEST_KEYCAP_SCALING (FAILED):** Tested this in Chrome-device emulator and I noticed that after clicking the 'Type here' element, no keyboard is displayed on the emulator. Seems to be an issue.

**Comment by jahorton** [comment]
> * **TEST_KEYCAP_SCALING (FAILED):** Tested this in Chrome-device emulator and I noticed that after clicking the 'Type here' element, no keyboard is displayed on the emulator. Seems to be an issue.
>        

That formatting pattern - the way that the two input areas have mismatching font - indicates that there was a JS error when initializing KMW.  I'll look into that.

**Comment by jahorton** [comment]
There were a few other testing pages that had the same `href` pattern, so I fixed 'em all while I was at it.

**Comment by mcdurdin** [comment]
> ... and it turns out, all you need to do is append a `/` to the URL for the page to work fine.

Is this something we can fix more generally in the test pages, given the URL without a final `/` is actually legit? I presume it was just a relative-path thing?

**Comment by jahorton** [comment]
Eh, the test pages (rightly) assume it's safe to use relative pathing to the compiled version of KMW.  Unfortunately, at least on our TC servers, the presence of that `/` changes whether the final component of the path is interpreted to be a file or a folder, even if it's absolutely a folder on the actual filesystem.

https://github.com/keymanapp/keyman/blob/086557e089ec07bcd07062fdf75e109573dbb93e/web/testing/issue382/index.html#L25-L35

Those two paths fail to resolve if the `/` is missing, as it bases the URL one folder higher than expected.  I'm not aware of how we could fix that in-repo.

**Comment by jahorton** [comment]
Extra details on that last commit, since I maintained a link to the errant version...

URL: https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/351158:id/testing/issue382

Resulting script-path resolutions:
```
GET https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/release/unminified/web/keymanweb.js

GET https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/release/unminified/web/kmwuitoggle.js
```

Note the lack of `351158:id/` in their paths.

Compare to...

URL: https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/351158:id/testing/issue382/

Here, the previously-missing portion is present, and so the paths resolve nicely and KMW loads successfully.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_KEYCAP_SCALING (PASSED):** 1. Verified that the first two keys between the "g" and "l" keys appear identical, with both displaying the same character 5 times. 2. Verified that the full word "Keyman" is visible on the key. 

   



* **TEST_SPACEBAR_SCALING (PASSED):** Verified that no text runs off either edge of the space. 


   



* **TEST_IN_APP_SPACEBAR_SCALING (FAILED):** It seems that the text runs off either edge of the spacebar.

**Comment by jahorton** [comment]
> TEST_IN_APP_SPACEBAR_SCALING
>
> 1.   Using the Android app on a tablet form-factor device...

The test report above indicates that a phone form-factor device was used.  The screenshot in the report is a known limitation for this keyboard on phone devices.  This is _not a failure._  Please retest.

@keymanapp-test-bot retest TEST_IN_APP_SPACEBAR_SCALING

**Comment by bharanidharanj** [comment]
> > TEST_IN_APP_SPACEBAR_SCALING
> > 
> > 1. Using the Android app on a **tablet** form-factor device...
> 
> The test report above indicates that a phone form-factor device was used. The screenshot in the report is a known limitation for this keyboard on **phone** devices; it's even shown off in this PR's description. While certainly not ideal... this is _not a failure._
> 
> @bharanidharanj Please retest _with a **tablet** form-factor device._ (Emulated is fine; it just needs to use a tablet form-factor.)
> 
> @keymanapp-test-bot retest TEST_IN_APP_SPACEBAR_SCALING

@jahorton Oops..Sorry for tested it in wrong device. I will retest it and will post my result. Thanks.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IN_APP_SPACEBAR_SCALING (PASSED):** Retested this as per Josh's suggestion and here is my observation: 1. This time I've tested it in Android 12.0 tablet (emulator) and verified that no text runs off either edge of the spacebar. Seems to be working as expected.

**Comment by mcdurdin** [comment]
> I'm not aware of how we could fix that in-repo.

Given these are local tests, we could do this by looking for `build.palaso.org` in the url and special-casing. Not pretty but would work. But also low-priority I think!

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.110-beta](https://keyman.com/downloads/releases/beta/16.0.110)
