### PR TITLE
fix(web): blocks modifier key fat-fingering

### LINKED ISSUE #6005: bug(common/models): pressing modifier keys breaks suggestions
**Describe the bug**

This is a regression from 14.0. Changing layers with the Shift key seems to have a negative impact on the banner, as the choices available keep changing each time you press Shift. In version 14.0, this display was stable.

Tested with Keyman 14.0.282-stable and Keyman 15.0.159-alpha on Android, and repro in KeymanWeb 15.0.159-alpha. Discovered while working on #5963 and its interactions with the banner.

**Screenshots**

Version 15.0 repro:

https://user-images.githubusercontent.com/4498365/144541532-c507f33f-18e1-4041-928e-1783c4df4bcb.mp4

Version 14.0 showing no issue:

https://user-images.githubusercontent.com/4498365/144541551-8e7bdfe0-595b-47ca-baef-99c59336bf9a.mp4

---

**Keyman for iPhone/iPad/Android/web:**
 - Keyman version: 15.0.159-alpha

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #6005.
Also reverts #6457.

A long-dormant contributor to issue #6005 lay here:

https://github.com/keymanapp/keyman/blob/fb3d9c3eb02bddde2f5e2377a27aa43c63bda646/common/core/web/keyboard-processor/src/keyboards/activeLayout.ts#L534-L553

These are keys that our current implementation of the fat-finger algorithm will not consider as fat-finger targets.  What, then, occurs when one of those keys is allowed to trigger said algorithm?  Well... "bad things."

What happened in #5553 accidentally allowed modifier keys to trigger the fat-finger algorithm based on the logic found here:

https://github.com/keymanapp/keyman/blob/fb3d9c3eb02bddde2f5e2377a27aa43c63bda646/common/core/web/input-processor/src/text/inputProcessor.ts#L133-L144

As a raw `SHIFT` keypress never matches a keyboard rule, it's always subject to a version of default key behavior - the fact that it should shift layers.  Before, we believed that we could easily return a `null` `RuleBehavior` without worry for any and all keystrokes that didn't match **any** keyboard rule.  However, since it is possible to have rule-matching text output that doesn't trigger a **final** rule, we shouldn't just remove ANY key (from fat-finger consideration) that relies on default key behavior to trigger - like for word-final sigma on Greek keyboards.  When #5553 prevented conflating "no matches at all" with "no _final_ matches", the issue allowing `SHIFT` to trigger fat-fingering crept in.

**So, the core cause of issue #6005:**
Now that `SHIFT` could trigger fat-fingering, the fact that it itself couldn't appear in its own fat-finger distribution caused the predictive text engine to believe that the nearest-neighbor emitting key was the actual key pressed, triggering suggestions based on it to appear.  Furthermore, when conflated with the advanced context-tracking engine from 14.0 work, this resulted in a context desync between KeymanWeb and the LMLayer.  (The reason that the suggestions differ on each press of the modifier key.)

So, a two-fold solution to the problem:

https://github.com/keymanapp/keyman/blob/8e5641d1afb26ea3b3eb5a51dadae7be4dabff6a/common/core/web/input-processor/src/text/inputProcessor.ts#L142-L159

That said, the second part (with the niche caveat) should be safe to leave out, if we don't mind those keys generating fat-finger events that may trigger predictions.  (They won't cause rotating suggestions, at least.  Just... more processing than desired.)

That said, there _is_ a simpler alternative fix:
We _could_ simply just not remove modifier keys from the key distribution generation process at all.  This would mean even modifier keys would trigger predictive-text engine events.  We'd no longer the "random" or "rotating" suggestions, but it would be a performance hit due to the unnecessary events.

------

# User Testing

All tests should be done on the new, dedicated test page at `web/testing/issue6005/index.html`.  The keyboards and lexical models for testing are all preconfigured on that page.

## SUITE_DESKTOP:  desktop-only user tests.  Chrome browser advised.

- **TEST_HEBREW**:  Using the "Hebrew, Galaxie Hebrew" keyboard, type the following:
 
  - `m`:  You should see `מ`.
  - Follow that with ` ` (a space):  you should now see `ם`, with the newly-typed space on the left (as it's an RTL language)

- **TEST_ANTIVOWEL**:  Using the "Unmatched Vowel Rule" keyboard, type the keystrokes for the following:
  - `tried`: the word should be output as expected
  - `queue`:  only `que` should be output 
  - `try`:  should output `tryy`.

- **TEST_ARROWS**:  Using any keyboard, do the following:
  1. type `attempt`
  2. hit ENTER
  3. type `try`
  4. use the left, then up arrow key of your keyboard.
      - the text caret should move intuitively.

## SUITE_PREDICTION:  Use either Firefox's or Chrome's mobile device emulation.

Note:  predictive text should activate for all keyboards but the Hebrew one.
Also note:  the predictive text for the "Pinyin" language is a total hack - it's just the English MTNT model.

- **TEST_HEBREW**:  Using the "Hebrew" (Galaxie Hebrew) keyboard, type the following:
 
  - `m`:  You should see `מ`.
  - Follow that with ` ` (a space):  you should now see `ם`, with the newly-typed space on the left (as it's an RTL language)

**NOTE**:  Please refresh the page after the previous test.

- **TEST_ANTIVOWEL_TRIED**:  Using the "English" > "Unmatched Vowel Rule" keyboard...
  1. Type the keystrokes for `tried`.
      - The final output should be `tried`.  Predictive text should operate normally, presenting reasonable predictions at all steps.
  2.  Select a suggestion.  The resulting text should match the selected suggestion.

- **TEST_ANTIVOWEL_QUEUE**:  Using the "English" > "Unmatched Vowel Rule" keyboard...
  1. Type the keystrokes for `queue`.
      - The final output should be `que`.  Predictive text should operate normally, presenting reasonable predictions based on the current state of the output.  Predictions should not change after the first `e`.
  2.  Select a suggestion.  The resulting text should match the selected suggestion.

- **TEST_ANTIVOWEL_TRY**:  Using the "English" > "Unmatched Vowel Rule" keyboard, type the keystrokes for `try`.  Be precise for 'y' keystroke, aiming for the key's center.

  The final output should be `tryy`.  Predictive text should operate normally, presenting reasonable predictions based on the current state of the output.  Predictions should be based on `try`, since `tryy` doesn't start any English words.

- **TEST_TRICOLOR**:  Using the "Pinyin" (Cameroon QWERTY) keyboard...

  1. Type `th`.  Suggestions based on `th` for English should appear.
  2. Press the keyboard's tri-color key - the final one in the third row.  The suggestions should not change, no matter how many times it is pressed.
  3. Type `e`.  Suggestions based on `the` should appear, no matter how many times the tri-color key was pressed on the previous step.
  4. Select a suggestion.  The text should change to match the suggestion's text.

- **TEST_NUMERIC**:  Using the "English" > "EuroLatin (SIL)" keyboard...

  1. Type `th`.  Suggestions based on `th` for English should appear.
  2. Press the keyboard's numeric key - the first one in the final row.  The suggestions should not change, no matter how many times it is pressed.
  3. Return to the base layer and type `e`.  Suggestions based on `the` should appear, no matter how many times the numeric-layer key was pressed on the previous step.
  4. Select a suggestion.  The text should change to match the suggestion's text.

- **TEST_ARROWS**:  Using the "English" > "EuroLatin (SIL)" keyboard, do the following:
  1. type `attempt`
  2. hit ENTER
  3. type `try`
  5. use the left, then up arrow key **of your physical keyboard**.
      - the text caret should not move (a limitation of how we handle input on touch)
      - the predictions should be unchanged whenever an arrow key is pressed (the *important* part of this test)

- **TEST_CAPS**:  Using the "English" > "EuroLatin (SIL)" keyboard, do the following:
  1. type `attempt`
  2. press SHIFT.
      - the second and third suggestion should become capitalized.
  3. press SHIFT again, returning to the base layer.
      - the second and third suggestions should no longer be capitalized.

### CODE REVIEW

**Review by mcdurdin — COMMENTED** [review]
Changes LGTM. This makes sense -- fat fingering interacting with modifier keys was something I had not anticipated. Good to have you back @jahorton!

> This should pass the user text from https://github.com/keymanapp/keyman/pull/6457 without issue. I should probably draft another test (and/or test resource) or two before finalizing a suite, though.

If this is not ready for review though, please put it in draft :grin:

You'll need to copy the User Testing spec from #6457 into this PR and add any additional tests that you think are necessary.

**Comment by jahorton** [comment]
Whoops - merged with `master` rather than `beta` for a moment there.  😖

**Comment by jahorton** [comment]
> You'll need to copy the User Testing spec from #6457 into this PR and add any additional tests that you think are necessary.

Since a different PR was merged before this one, affecting how SHIFT operates (shifting between default and caps layers), the test would likely not function identically now.  I've written a different test to accomplish the same results.

File: common/core/web/keyboard-processor/src/text/outputTarget.ts [hunk 1]
```diff
@@ -18,6 +18,13 @@ namespace com.keyman.text {
     }
 
     public static readonly nil = new TextTransform('', 0, 0);
+
+    public isNoOp(): boolean {
+      if(this.insert != '') {
+        return false;
+      }
+      return this.deleteLeft == 0 && this.deleteRight == 0;
```
Comment (mcdurdin) [inline common/core/web/keyboard-processor/src/text/outputTarget.ts:26]:
```suggestion
      return this.insert === '' && this.deleteLeft === 0 && this.deleteRight === 0;
```

File: web/testing/issue6005/vowel_hater/source/vowel_hater.kmn [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+any(vowels) any(vowels) + [K_E] > context(1) context(2)
+any(vowels) any(vowels) + [K_I] > context(1) context(2)
+any(vowels) any(vowels) + [K_O] > context(1) context(2)
+any(vowels) any(vowels) + [K_U] > context(1) context(2)
+
+any(vowels) any(vowels) + [SHIFT K_A] > context(1) context(2)
+any(vowels) any(vowels) + [SHIFT K_E] > context(1) context(2)
+any(vowels) any(vowels) + [SHIFT K_I] > context(1) context(2)
+any(vowels) any(vowels) + [SHIFT K_O] > context(1) context(2)
+any(vowels) any(vowels) + [SHIFT K_U] > context(1) context(2)
```
Comment (mcdurdin) [inline web/testing/issue6005/vowel_hater/source/vowel_hater.kmn:96]:
```suggestion
any(vowels) any(vowels) + any(vowel_keys) > context
```

File: web/testing/issue6005/vowel_hater/source/vowel_hater.kmn [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+
+store(&VERSION) '10.0'
+store(&NAME) 'Vowel Hater'
+store(&COPYRIGHT) '© SIL Int' U+0027 'l'
+store(&KEYBOARDVERSION) '1.0'
+store(&TARGETS) 'any'
+store(&VISUALKEYBOARD) 'vowel_hater.kvks'
+store(&LAYOUTFILE) 'vowel_hater.keyman-touch-layout'
+
+store(vowels) 'aeiouAEIOU' c Doesn't hate 'y' or 'Y'.
```
Comment (mcdurdin) [inline web/testing/issue6005/vowel_hater/source/vowel_hater.kmn:18]:
```suggestion
store(vowels)     'aeiouAEIOU' c Doesn't hate 'y' or 'Y'.
store(vowel_keys) [K_A] [K_E] [K_I] [K_O] [K_U] \
                  [SHIFT K_A] [SHIFT K_E] [SHIFT K_I] [SHIFT K_O] [SHIFT K_U] 
store(cons)       'bcdfghjklmn' \
                  'pqrstvwxz' \
                  'BCDFGHJKLMN' \
                  'PQRSTVWXZ'
store(consKeys)   [SHIFT K_B] [SHIFT K_C] [SHIFT K_D] [SHIFT K_F] [SHIFT K_G] [SHIFT K_H] \
                    [SHIFT K_J] [SHIFT K_K] [SHIFT K_L] [SHIFT K_M] [SHIFT K_N] \
                  [SHIFT K_P] [SHIFT K_Q] [SHIFT K_R] [SHIFT K_S] [SHIFT K_T] [SHIFT K_V] \
                    [SHIFT K_W] [SHIFT K_X] [SHIFT K_Z]
```

Or this has identical behaviour because the chars are translated to vkeys:

```
store(vowels)     'aeiouAEIOU' c Doesn't hate 'y' or 'Y'.
store(vowel_keys) 'aeiouAEIOU'

store(cons)       'bcdfghjklmn' \
                  'pqrstvwxz' \
                  'BCDFGHJKLMN' \
                  'PQRSTVWXZ'
store(cons_keys)  'bcdfghjklmn' \
                  'pqrstvwxz' \
                  'BCDFGHJKLMN' \
                  'PQRSTVWXZ'
```

File: web/testing/issue6005/vowel_hater/source/vowel_hater.kmn [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
++ [K_A] > use(vowel_tolerance)
++ [K_E] > use(vowel_tolerance)
++ [K_I] > use(vowel_tolerance)
++ [K_O] > use(vowel_tolerance)
++ [K_U] > use(vowel_tolerance)
++ [SHIFT K_A] > use(vowel_tolerance)
++ [SHIFT K_E] > use(vowel_tolerance)
++ [SHIFT K_I] > use(vowel_tolerance)
++ [SHIFT K_O] > use(vowel_tolerance)
++ [SHIFT K_U] > use(vowel_tolerance)
```
Comment (mcdurdin) [inline web/testing/issue6005/vowel_hater/source/vowel_hater.kmn:74]:
```suggestion
+ any(vowel_keys) > use(vowel_tolerance)
```

File: web/testing/issue6005/vowel_hater/source/vowel_hater.kmn [hunk 5]
```diff
@@ -0,0 +1,96 @@
...
++ [K_H] > 'h'
++ [K_G] > 'g'
++ [K_F] > 'f'
++ [K_D] > 'd'
++ [K_S] > 's'
++ [K_P] > 'p'
++ [K_T] > 't'
++ [K_R] > 'r'
++ [K_W] > 'w'
++ [K_Q] > 'q'
```
Comment (mcdurdin) [inline web/testing/issue6005/vowel_hater/source/vowel_hater.kmn:62]:
```suggestion
+ any(cons_keys) > index(cons, 1)
```

**Review by mcdurdin — APPROVED** [review]
This is looking good. Appreciate the detailed background.

Can we add another user test around arrow keys / default key behaviours? See  #6512 and related issue #6507 and this is touching some of the same code paths (not that I think it'll be a problem, but for completeness).

The keyboard source should be moved to /common/test/keyboards and just the .js copied into this folder (in the future, /common/test/keyboards keyboards will be copied automatically for tests, but they are only built during the Windows/Developer build currently...).

Please rename the vowel_hater keyboard to reference the issue number directly, similar to how we have named most other keyboards in the common/test/keyboards folder. I've given examples on how to simplify the .kmn code for clarity which I think we should apply to the code for future maintainers even though it's just a test keyboard.

File: web/testing/issue6005/vowel_hater/source/vowel_hater.kmn (hunk 2 above)
Comment (jahorton) [reply web/testing/issue6005/vowel_hater/source/vowel_hater.kmn:96]: Ah, I didn't realize I could use stores in the `+` section of keyboard rules; that'll definitely help.  :+1:

**Comment by jahorton** [comment]
> The keyboard source should be moved to /common/test/keyboards and just the .js copied into this folder (in the future, /common/test/keyboards keyboards will be copied automatically for tests, but they are only built during the Windows/Developer build currently...).

Ah, okay.  Is that kinda new?  I could only remember how we used to store the source directly with the tests instead, so I went that direction.  Can definitely change it, though.

**Comment by bharanidharanj** [comment]
## SUITE_DESKTOP: desktop-only user tests.  Chrome browser advised.

* **TEST_HEBREW (PASSED):** Tested this in the Keyman Web Page in Chrome browser and it seems to be working as expected. 

Test 1:
 

Test 2:
 


* **TEST_ANTIVOWEL (PASSED):** Tested this in the Keyman Web Page in Chrome browser and it seems to be working as expected. 

Test 1:
 

Test 2:
 

Test 3:

**Comment by bharanidharanj** [comment]
## SUITE_PREDICTION: Use either Firefox's or Chrome's mobile device emulation.

* **TEST_HEBREW (PASSED):** Tested in Chrome Mobile emulator as per the instructions and it seems to be working as expected.

Test 1:
 


Test 2:
 

* **TEST_ANTIVOWEL_TRIED (PASSED):** Tested in Chrome Mobile emulator as per the instructions and it seems to be working as expected. 
 


* **TEST_ANTIVOWEL_QUEUE (PASSED):** Tested in Chrome Mobile emulator as per the instructions and it seems to be working as expected.
 

* **TEST_ANTIVOWEL_TRY (PASSED):** Tested in Chrome Mobile emulator as per the instructions and it seems to be working as expected. 
 

* **TEST_TRICOLOR (FAILED):** Tested in Chrome Mobile emulator as per the instructions and the Suggestions are not appear in the banner. 
 

* **TEST_NUMERIC (FAILED):** Tested in Chrome Mobile emulator as per the instructions and the Suggestions are not appear in the banner.

**Comment by jahorton** [comment]
> Can we add another user test around arrow keys / default key behaviours? See #6512 and related issue #6507 and this is touching some of the same code paths (not that I think it'll be a problem, but for completeness).

Tests added.  Hopefully **TEST_ARROWS** and **TEST_CAPS** cover what you were looking for?

**Comment by jahorton** [comment]
Found a pathing issue or two trying to use the test page when hosted by our CI; that may have caused the user test errors from before.

@keymanapp-test-bot retest SUITE_PREDICTION TEST_TRICOLOR TEST_NUMERIC

File: web/testing/issue6005/vowel_hater/source/vowel_hater.kmn [hunk 6]
```diff
@@ -22,10 +22,14 @@ store(cons)       'bcdfghjklmn' \
...
-store(consKeys)   [SHIFT K_B] [SHIFT K_C] [SHIFT K_D] [SHIFT K_F] [SHIFT K_G] [SHIFT K_H] \
+store(cons_keys)   [K_B] [K_C] [K_D] [K_F] [K_G] [K_H] \
+                    [K_J] [K_K] [K_L] [K_M] [K_N] \
+                  [K_P] [K_Q] [K_R] [K_S] [K_T] [K_V] \
+                    [K_W [K_X] [K_Z] \
+                  [SHIFT K_B] [SHIFT K_C] [SHIFT K_D] [SHIFT K_F] [SHIFT K_G] [SHIFT K_H] \
                     [SHIFT K_J] [SHIFT K_K] [SHIFT K_L] [SHIFT K_M] [SHIFT K_N] \
                   [SHIFT K_P] [SHIFT K_Q] [SHIFT K_R] [SHIFT K_S] [SHIFT K_T] [SHIFT K_V] \
-                    [SHIFT K_W] [SHIFT K_X] [SHIFT K_Z]
+                    [SHIFT K_W [SHIFT K_X] [SHIFT K_Z]
```
Comment (mcdurdin) [inline web/testing/issue6005/vowel_hater/source/vowel_hater.kmn]: Sorry!

File: common/test/keyboards/issue6005/HISTORY.md [hunk 7]
```diff
@@ -0,0 +1,6 @@
+Vowel Hater Change History
```
Comment (mcdurdin) [inline common/test/keyboards/issue6005/HISTORY.md:1]: I think we should avoid the word 'Hater' in the repo. It just doesn't look good... (Can you do a global Search+Replace?)

File: common/test/keyboards/issue6005/issue6005.keyboard_info [hunk 8]
```diff
@@ -0,0 +1,7 @@
+{
+    "license": "mit",
+    "languages": [
+        
+    ],
+	  "description": "Vowel Hater generated from template"
```
Comment (mcdurdin) [inline common/test/keyboards/issue6005/issue6005.keyboard_info:6]: Ditto (actually we don't need the .keyboard_info file at all, as this is only for keyboards that will be deployed to keyman.com)

File: common/test/keyboards/issue6005/README.md [hunk 9]
```diff
@@ -0,0 +1,30 @@
+Vowel Hater keyboard
```
Comment (mcdurdin) [inline common/test/keyboards/issue6005/README.md:1]: ...

File: common/test/keyboards/issue6005/README.md [hunk 10]
```diff
@@ -0,0 +1,30 @@
...
+==============
+
+Version 1.0
+
+Description
+-----------
+Vowel Hater generated from template
```
Comment (mcdurdin) [inline common/test/keyboards/issue6005/README.md:8]: ...

**Review by mcdurdin — APPROVED** [review]
I wonder if we really need a whole new test page for the keyboard -- there are a lot of pages in the manual testing area now, and most (not all) of those could be consolidated down into a single page with multiple keyboards available?

Code generally LGTM now. `issue6005` is perhaps a little unclear; is there something like `modifier-key-model-interactions-6005` that would be helpful into the future?

File: web/testing/issue6005/vowel_hater/source/vowel_hater.kmn (hunk 6 above)
Comment (jahorton) [reply web/testing/issue6005/vowel_hater/source/vowel_hater.kmn]: Must've gotten to push that; I did catch it.

Comment (jahorton) [reply web/testing/issue6005/vowel_hater/source/vowel_hater.kmn]: Ah, I missed the SHIFT variant.

**Comment by jahorton** [comment]
Would something like `issue-6005-vowel-group-shenanigans` be acceptable?

**Comment by mcdurdin** [comment]
> Would something like `issue-6005-vowel-group-shenanigans` be acceptable

It doesn't say anything about what it is testing, so not really helpful... That's why I went with bland but hopefully describes what the keyboard is testing. Note also the pattern `kebab-case-name-<issue#>`: `modifier-key-model-interactions-6005`

**Comment by jahorton** [comment]
> > Would something like `issue-6005-vowel-group-shenanigans` be acceptable
> 
> It doesn't say anything about what it is testing, so not really helpful... That's why I went with bland but hopefully describes what the keyboard is testing. Note also the pattern `kebab-case-name-<issue#>`: `modifier-key-model-interactions-6005`

Ended up going with `unmatched_final_group_model_interactions_6005`.

The new test keyboard **is not** designed for testing _modifier key_ interactions - both `sil_cameroon_qwerty` and `sil_euro_latin` are better for that.  (The former has a custom "modifier" key, while the latter has numeric and symbolic layers.)

This keyboard **is** designed to test how predictions work when the final rule group for a keystroke is unmatched when an _earlier_ group matches.  To facilitate ease of use and predictability, it's themed on vowel manipulations.

**Comment by mcdurdin** [comment]
> Ended up going with `unmatched_final_group_model_interactions_6005`.

💯

**Comment by bharanidharanj** [comment]
## SUITE_DESKTOP: desktop-only user tests.  Chrome browser advised.

* **TEST_ARROWS (PASSED):** Tested this in the corresponding web page and the text caret moves intuitively.

 



## SUITE_PREDICTION: Use either Firefox's or Chrome's mobile device emulation.

* **TEST_TRICOLOR (PASSED):** Tested this in the corresponding web page in Chrome's mobile emulator and it is working as expected.
 

* **TEST_NUMERIC (PASSED):** Tested this in the corresponding web page in Chrome's mobile emulator and it is working as expected.
 

* **TEST_ARROWS (PASSED):** Tested this in the corresponding web page in Chrome's mobile emulator and it is working as expected.
 


* **TEST_CAPS (PASSED):** Tested this in the corresponding web page in Chrome's mobile emulator and it is working as expected.

with Shift Key Pressed:

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.236-beta](https://keyman.com/downloads/releases/beta/15.0.236)
