### PR TITLE
fix(web): position popups correctly in landscape mode on Android and during Chrome emulation

### LINKED ISSUE #4930: bug(web): popup key is not shown right on the base
**Describe the bug**

**Additional context**

When test on Chrome emulator - iPad, the long press characters on the key on the top right corner of the "0" key on numeric layer, pop way too far from the key it's based on:

image

**Expected behavior**

The popup key should be on the key it's based on.

---

**KeymanWeb:**
 - OS: Windows 10 Pro 20H2 x64
 - Browser: Chrome Version 89.0.4389.128 (Official Build) (64-bit)
 - KeymanWeb Version: ??

**Keyman Developer:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman Developer version: 14.0.271

---

**Keyboard**
 - Keyboard name: thai_qwerty
 - Keyboard version: 1.0 (under development)
 - Language name: Thai

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #4930.

To ensure this doesn't break anything for Android...

## User Testing
@MakaraSok 

I'm requesting two sets of tests.  That said, I'd only expect an issue from the second (non-embedded) set if any issue occurs.

### In-app test

Just fire up the Android app (from this PR's build) and ensure subkeys work as expected in landscape mode, both in-app and in system-keyboard mode.  Behavior should be unaffected and match your default expectations.

### Non-embedded test

This one's going to be a bit more involved, but reflects the actually-changed parts of the code.

1. Ensure that KeymanWeb's test pages are accessible through `localhost` on your machine.
    - In case you don't yet have a localhost setup:  [instructions](https://github.com/sillsdev/keyman/wiki/How-to-set-up-a-local-web-server-for-the-Keyman-web-pages) 
2. In your local copy of the repo, navigate to `web/source` and run `./build.sh`.
3. Once complete, in Chrome navigate to the unminified testing page using your `localhost` setup.
    - For my setup, that's `http://localhost/testing/unminified.html`.
4. Activate device emulation and ensure that the subkeys display where you expect them to be.
    - For both Android and iOS device types, both phone and tablet form factors.
5. _Then_, use Android Studio to launch an emulated Android device.
6. Launch the Chrome app and navigate to the same testing URL, **_but_** in place of `localhost`, [type `10.0.2.2`](https://stackoverflow.com/a/6310592).
    - For my setup, that's `10.0.2.2/localhost/testing/unminified.html`.
7. Ensure that the popup keys position properly on the emulated Android device.

A similar test may be run for steps 5 through 7 for those developing on Mac in order to test iOS device setups.  (But without replacing `localhost` with `10.0.2.2`.)

Once the PR lands on `master`, this will become possible to test directly with keymanweb.com.

### CODE REVIEW

File: web/source/osk/visualKeyboard.ts [hunk 1]
```diff
@@ -1789,8 +1789,12 @@ namespace com.keyman.osk {
 
       // And correct its position with respect to that element
       ss=subKeys.style;
-      var x=dom.Utils.getAbsoluteX(e)+0.5*(e.offsetWidth-subKeys.offsetWidth), y,
-        xMax=(util.landscapeView()?screen.height:screen.width)-subKeys.offsetWidth;
+      var x=dom.Utils.getAbsoluteX(e)+0.5*(e.offsetWidth-subKeys.offsetWidth);
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:1792]: `var y` is no longer defined?

File: web/source/osk/visualKeyboard.ts [hunk 2]
```diff
@@ -1789,8 +1789,12 @@ namespace com.keyman.osk {
...
+      
+      // https://stackoverflow.com/questions/28083715/how-to-detect-if-a-mobile-device-is-emulated-by-google-chrome
+      // (Note the last reply to the accepted answer.)
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:1795]:
```suggestion
      // Note in particular https://stackoverflow.com/questions/28083715/#comment108747578_28084346:
      // The definitive way to determine this is to check for `navigator.maxTouchPoints > 1` Because Chrome 
      // emulated devices will always have only 1 touchpoint (ie. your mouse cursor), while actual (modern)
      // mobile devices will always have more than 1, and devices without touch support will always have 
      // 0. – Ivan [CC-BY-SA 4.0]
```

And yet I wonder if this is true on a Windows computer with a touch screen.

I will try and test this on my wife's touch-screen laptop shortly.

**Comment by mcdurdin** [comment]
Suggest changing title to clarify what this is fixing, e.g. "fix(web): position popups correctly in landscape mode on Android and Chrome emulation"?

File: web/source/osk/visualKeyboard.ts (hunk 1 above)
Comment (jahorton) [reply web/source/osk/visualKeyboard.ts:1792]: VS Code indicates that the variable was unused, so yes.

**Comment by jahorton** [comment]
> Suggest changing title to clarify what this is fixing, e.g. "fix(web): position popups correctly in landscape mode on Android and Chrome emulation"?

Except that's not entirely accurate - it also fixes popups correctly on Android in unembedded contexts - a real use case for users.  (That is, when _not_ emulated.)  At that point, getting precise and explicit means being rather unconcise, hence the title I chose.

File: web/source/osk/visualKeyboard.ts (hunk 2 above)
Comment (jahorton) [reply web/source/osk/visualKeyboard.ts:1795]: If `false` in that case, it'll still fail during Chrome _emulation_ of an iOS device.  Fortunately, all standard user use-cases will be fine, though it could affect keyboard developers like Makara when using the Developer test host.

**Comment by mcdurdin** [comment]
Position is better but width of popup seems incorrect on right side of screen. The p popup should be a single row, for example.

**Comment by mcdurdin** [comment]
I'm trying to get a full picture of the possible scenarios we are trying to support, and the differences between them:

- iPhone/iPad - portrait
- iPhone/iPad - landscape
- Android phone/tablet - portrait
- Android phone/tablet - landscape
- (Windows/mac) Chrome emulation of iPhone/iPad - portrait
- (Windows/mac) Chrome emulation of iPhone/iPad - landscape
- (Windows/mac) Chrome emulation of Android phone/tablet - portrait
- (Windows/mac) Chrome emulation of Android phone/tablet - landscape

Is that a comprehensive list? Is there a table we can draw up of the differences between the values we are relying on? (If possible, we should file a bug against Chrome if its emulation of iPhone/iPad mismatches.)

Also:
- Firefox emulation of above (future)

**Comment by jahorton** [comment]
OK, I can repro _that_ effect when targeting a Pixel 2.  (It didn't show up when targeting a Nexus.)

**Comment by MakaraSok** [comment]
> ### In-app test
> Just fire up the Android app (from this PR's build) and ensure subkeys work as expected in landscape mode, both in-app and in system-keyboard mode. Behavior should be unaffected and match your default expectations.

Tested on Android Emulator (Pixel 2 API 29, Android 10). The popped key on the top right corner behaves as expected within Keyman app on landscape mode. The same normal/expected behavior is observed when using it as a system keyboard on landscape mode.

Still figure out how to test "Non-embedded test". I will get back to this first thing this afternoon.

File: web/source/osk/visualKeyboard.ts (hunk 2 above)
Comment (mcdurdin) [reply web/source/osk/visualKeyboard.ts:1795]: I have verified that `navigator.maxTouchPoints` is 10 on my wife's computer when mobile emulation is *not* running, but it is 1 when mobile emulation is running. So that's good news.

File: web/source/osk/visualKeyboard.ts [hunk 3]
```diff
@@ -1789,8 +1789,8 @@ namespace com.keyman.osk {
 
       // And correct its position with respect to that element
       ss=subKeys.style;
-      var x=dom.Utils.getAbsoluteX(e)+0.5*(e.offsetWidth-subKeys.offsetWidth), y,
-        xMax=(util.landscapeView()?screen.height:screen.width)-subKeys.offsetWidth;
+      var x = dom.Utils.getAbsoluteX(e)+0.5*(e.offsetWidth-subKeys.offsetWidth);
+      var xMax = keyman.osk.getWidth() - subKeys.offsetWidth;
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:1793]: Hmm, liking this more than the previous iteration! 😂

**Comment by jahorton** [comment]
I usually prefer to not have `VisualKeyboard` refer to its owning `OSKManager` when possible, but it looks like the latter's width-calc function is more robust here; `screen.width` doesn't give the _available_ width on Android devices.  As the base OSK was built correctly, we can tell that `osk.getWidth()` is getting the right values.

**Comment by MakaraSok** [comment]
### Non-embedded test

Tested using `https://ecb5a861dbca.ngrok.io/keymanweb/testing/unminified.html` and iPad/Pixel 2/iPhone emulated on Chrome `90.0.4430.212` in landscape mode.

The popped up keys are shown directly on the based key on the top right corner. It is working as expected.

**Comment by MakaraSok** [comment]
Screenshots:
image

image

image

**Review by mcdurdin — APPROVED** [review]
LGTM. Tested on Android physical device now with good results as well as on Chrome with various devices all in landscape and portrait, and no problems encountered.

**Comment by mcdurdin** [comment]
> I usually prefer to not have `VisualKeyboard` refer to its owning `OSKManager` when possible

Does this potentially indicate a refactor of that code is in the future?

**Comment by mcdurdin** [comment]
I think we should cherry-pick to stable-14.0 :)

**Comment by jahorton** [comment]
> > I usually prefer to not have `VisualKeyboard` refer to its owning `OSKManager` when possible
> 
> Does this potentially indicate a refactor of that code is in the future?

I mean, yeah.  OSK-Core work's going to affect more than a few things.  There are other parts of the code that have been using the same approach; this just adds an extra to the list.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.48-alpha](https://keyman.com/downloads/releases/alpha/15.0.48)
