### PR TITLE
fix(developer): Use US base layout for debugger

### LINKED ISSUE #7529: bug(developer): debugger should use scan codes rather than vk codes to ensure consistent mapping
### Describe the bug

We need to always use kbdus.dll virtual key codes under the hood for the debugger, so that positional keyboards work correctly. The cleanest way to do this is to use our existing scan code mapping tables from Keyman Engine for Windows for kbdus virtual keys.

Don't forget the Brazilian ABNT2 103rd key.

### Reproduce the bug

_No response_

### Expected behavior

_No response_

### Related issues

This is precursor work for #1225, #1074.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.271

### Operating system

_No response_

### Device

_No response_

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #7529.

We must always use the US base layout for the debugger, as positional keyboards are not affected by the active Windows system keyboard. This fix ensures that the behaviour in the debugger matches what the user experiences in Keyman for Windows.

Note that this does not address support for mnemonic layouts, tracked in issue #1074.

# User Testing

For these tests, we want to ensure that every key emits the expected US English key, no matter what the underlying keyboard is. To do this:

1. Create a brand new basic keyboard with no rules.
2. Compile the keyboard (F7), and start the debugger (F5).
3. Press each key in turn on the keyboard: the character emitted should match the character for the US English hardware keyboard.

**TEST_US:** Select the English (US) keyboard in the Windows language picker. Verify each key on the keyboard matches US English.
**TEST_FRENCH:** Select the French (AZERTY) keyboard in the Windows language picker. Verify each key on the keyboard matches US English.

### CODE REVIEW

File: developer/src/tike/child/UfrmDebug.pas [hunk 1]
```diff
@@ -448,19 +449,23 @@ function TfrmDebug.ProcessKeyEvent(var Message: TMessage): Boolean;
...
 var
-  modifier: uint16_t;
+  vkey, modifier: uint16_t;
 begin
   Assert(Assigned(FDebugCore));
+
+  // We always use the US virtual key code as a basis for our keystroke
+  // mapping; the best way to do this is to extract the scan code from
+  // the message data and work from that
+  vkey := MapScanCodeToUSVK((Message.LParam and $FF0000) shr 16);
```
Comment (darcywong00) [inline developer/src/tike/child/UfrmDebug.pas:459]: Since the debugger is processing scan codes, does this mean the user testing involves keyboard hardware (e.g. a physical AZERTY keyboard)?

Comment (mcdurdin) [reply developer/src/tike/child/UfrmDebug.pas:459]: An AZERTY keyboard produces identical scan codes to a QWERTY keyboard. There are two differences: the extra key (D00) to right of the left shift key (D99), and the movement of B13 (backslash on US English) from ANSI/QWERTY to A13, to the left of backspace.

It is fine to test on US English hardware, so long as we select the French AZERTY keyboard in Windows language preferences.

**Comment by bharanidharanj** [comment]
* **TEST_US (PASSED):**  Tested this with the attached Keyman Developer 16.0.89-alpha-test-7531 build in Windows 10 OS and here is my observations: Verified each key on the keyboard matches US English after selecting the English (US) Keyboard. 


   


* **TEST_FRENCH (FAILED):** I have changed the Keyboard from English (US)  to French (AZERTY) keyboard from the Windows task bar (language menu). After changing the keyboard into French, the Keyboard layout is changed to French Keyboard layout. While pressing 'q' letter from the English hardware keyboard, it produces 'a' output on the corresponding key in the French Keyboard layout. Seems to be not working as expected.

**Comment by mcdurdin** [comment]
Apologies @bharanidharanj, the test steps were not clear -- the test needed to be run in the keyboard debugger. I have updated the steps so hopefully they are clearer now. Can you retest please?

@keymanapp-test-bot retest all

**Comment by bharanidharanj** [comment]
> Apologies @bharanidharanj, the test steps were not clear -- the test needed to be run in the keyboard debugger. I have updated the steps so hopefully they are clearer now. Can you retest please?
> 
> @keymanapp-test-bot retest all

Sure, @mcdurdin . I will do it.

**Comment by bharanidharanj** [comment]
* **TEST_US (PASSED):** Retested this as per the instructions and it seems that each key on the keyboard matches US English after selecting the English (US) Keyboard.

**Comment by bharanidharanj** [comment]
* **TEST_FRENCH (FAILED):** Retested this as per the instructions and I noticed that pressing 'q' key on the English US hardware keyboard, it is showing letter 'a' in the debugger window. (this happens, after changing to French keyboard). Seems to be an issue.

**Comment by mcdurdin** [comment]
@bharanidharanj I think you were typing into the Editor window rather than the Debugger window 😁 

image

@keymanapp-test-bot retest all

**Comment by bharanidharanj** [comment]
> @bharanidharanj I think you were typing into the Editor window rather than the Debugger window 😁
> 
> image
> 
> @keymanapp-test-bot retest all

@mcdurdin   Oops! Apologies for misunderstanding the step. I will retest and will add my comment.

**Comment by bharanidharanj** [comment]
* **TEST_US (PASSED):** Retested this as per Marc's suggestion and I was able to see that after pressing any key from the English hardware keyboard produces the corresponding letters on the debugger window. 

   



* **TEST_FRENCH (PASSED):** Retested this as per Marc's suggestion and here is my observation. 1. Selected the French (AZERTY) keyboard from the windows keyboard picker menu. 2. Opened Keyman Developer 16.0.89-alpha-test-7531 build. 3. If I type English keys from the English hardware keyboard it produces the corresponding English letters on the debugger window. Seems to be working as expected. Thanks.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.95-beta](https://keyman.com/downloads/releases/beta/16.0.95)
