### PR TITLE
fix(android): Removes Closure's auto-polyfills, adds test case bypass

### LINKED ISSUE #2323: [Android] Blank keyboard on Android 4.4.2
A user updated to Keyman 12.0.4206 stable but gets a blank SIL Euro Latin keyboard. All other Keyman keyboards also fail to load.

When connected with a test build, Chrome listed console errors
```
Uncaught SyntaxError: Unexpected identifier keyboard.html:270
Uncaught ReferenceError: Map is not defined keyman.js:18986
```

The SyntaxError is the use of `let` (ES6) and I think the browser for 4.4.2 is ES5.

The ReferenceError correponds to lm-layer's use of Map():
```
var PromiseStore = function() {
  this._promises = new Map();
```

Perhaps the webView on that version of Android doesn't support Map()?

I loaded Keyman for Android 11.0.2106 stable and that keyboard loaded fine.

### Configuration
Device: Samsung S4
OS: Android 4.4.2 (SDK 19)
Keyman: 12.0.4206
Keyboards: SIL Euro Latin (user also wanted SIL IPA and Greek)

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #2323.

So, it turns out that the final issue for #2323 was being caused by the Closure minifier, which tries to be helpful by adding polyfills for us.  Just... that actually broke things on API 19, which apparently is too old for one of its polyfills.

This also adds a simple "build without testing" option to Android's build.sh, allowing for easier compilation of the entire app whenever unit tests fail.  Sometimes this is useful for narrowing things down with live testing.

Note that this issue originally wasn't caught because it doesn't show up with the `debug_embedded` flag for KMW, which itself is set by using the `-debug` flag when compiling the Android app.  Testing locally may require the state seen in commit https://github.com/keymanapp/keyman/commit/4600e2a4069b7db6dce6f8d1f51514b245a7b652, where the responsible lines have been commented out.

### CODE REVIEW

File: android/KMEA/build.sh [hunk 1]
```diff
@@ -71,6 +73,9 @@ while [[ $# -gt 0 ]] ; do
         -h|-?)
             display_usage
             ;;
+        -no-test)
```
Comment (darcywong00) [inline android/KMEA/build.sh]: Can you echo DO_TEST in line 85?

File: android/KMEA/build.sh [hunk 2]
```diff
@@ -7,12 +7,13 @@
...
 
 display_usage ( ) {
-    echo "build.sh [-no-kmw-build] | [-no-kmw] [-no-daemon]"
+    echo "build.sh [-no-kmw-build] | [-no-kmw] [-no-daemon] | [-no-test]"
     echo
     echo "Build Keyman Engine Android (KMEA) using Keyman Web (KMW) artifacts"
     echo "  -no-kmw-build           Don't build KMW. Just copy existing artifacts"
     echo "  -no-kmw                 Don't build KMW. Don't copy artifacts"
     echo "  -no-daemon              Don't start the Gradle daemon. Use for CI"
+    echo "  -no-test                Don't run the unit-test suite."
```
Comment (darcywong00) [inline android/KMEA/build.sh]: btw, I believe **release** builds always run tests, There, the gradle task runs `build` which depends on `check` which depends on `test`.

Per gradle plugin [documentation](https://docs.gradle.org/current/userguide/java_plugin.html)

File: web/source/build.sh [hunk 3]
```diff
@@ -83,7 +83,8 @@ minifier="$CLOSURECOMPILERPATH/compiler.jar"
 # `jsDocMissingType` prevents errors on type documentation Closure thinks is missing.  TypeScript may not
 # have the same requirements, and we trust TypeScript over Closure.
```
Comment (darcywong00) [inline web/source/build.sh]: Maybe add a short note to document the closure issues with older Android API levels. 
Then when we deprecate API 19, maybe we can safely revert this

File: android/KMEA/build.sh (hunk 2 above)
Comment (jahorton) [reply android/KMEA/build.sh]: So... this should be noted as a `-debug`-only option?  Or am I interpreting this wrong?
