### PR TITLE
Mac high sierra config workaround

### LINKED ISSUE #368: Keyman Crash in High Sierra (mac0S Version 10.13)
The Keyman configuration doesn't respond.

### PR DESCRIPTION
**Pull request by tombogle**
Fixes #368

### CODE REVIEW

File: mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m [hunk 1]
```diff
@@ -695,6 +695,14 @@ - (NSWindowController *)oskWindow {
     return _oskWindow;
 }
 
+- (void)showConfigurationWindow {
+    NSLog(@"At start of showConfigurationWindow");
+    [self.configWindow.window centerInParent];
+    [[self.configWindow window] makeKeyAndOrderFront:nil];
+    [[self.configWindow window] setLevel:NSFloatingWindowLevel];
```
Comment (gabrielwong) [inline mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m]: The config window should probably have normal level

File: mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/KMConfigurationWindowController.m [hunk 2]
```diff
@@ -26,9 +26,10 @@ - (KMInputMethodAppDelegate *)AppDelegate {
 }
 
 - (id)initWithWindowNibName:(NSString *)windowNibName {
+    NSLog(@"Initializing KMConfigurationWindowController with nib: %@", windowNibName);
     self = [super initWithWindowNibName:windowNibName];
     if (self) {
-        self.AppDelegate.configWindow = self;
+        //self.AppDelegate.configWindow = self;
```
Comment (gabrielwong) [inline mac/Keyman4MacIM/Keyman4MacIM/KMConfiguration/KMConfigurationWindowController.m]: Can just remove this line

File: mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/KMAboutWindowController.m [hunk 3]
```diff
@@ -38,7 +38,9 @@ - (void)windowDidLoad {
 }
 
 - (IBAction)configAction:(id)sender {
-    [self.AppDelegate.inputController showPreferences:sender];
+    NSLog(@"Calling showPreferences from About window (i.e., the old way)...");
```
Comment (gabrielwong) [inline mac/Keyman4MacIM/Keyman4MacIM/KMAboutWindow/KMAboutWindowController.m]: I forgot to change this log statement now that we're not calling `showPreferences:`

**Comment by gabrielwong** [comment]
Confirming that the configuration menu works on my laptop running macOS 10.13.1.
