### PR TITLE
[Android] Add notifications when font/keyboard fails to download

### LINKED ISSUE #1552: [Android] Keyboard installation silently fails if font missing
**Describe the bug**
From investigation after keymanapp/keyboards#598 was merged
The keyboard embera_north failed to install on Keyman for Android because it was expecting the Charis SIL font, which currently didn't exist on s.keyman.com.

After the download confirmation, the UI just returns to the keyboards list, with no change.

**To Reproduce**
1. In Keyman for Android, add the new keyboard for "Embera, Northern (Latin)" 
2. Click to confirm downloading
3. When the download completes, the UI returns to the "Add New Keyboard" menu, and the keyboard is not installed

**Expected behavior**
The app should give an error that the font failed to download.

**Android
 - Device: Pixel emulator in Android Studio
 - OS: [Android 8.1]
 - Keyman version [e.g. 11.0 beta]

---
 
**Keyboard**
 - Keyboard name: embera_north
 - Keyboard version: 10.0.2
 - Language name: Embera Northern (Latin)

Currently, Charis font doesn't exist on s.keyman.com. But a PR is adding that...

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #1552 

Currently when downloading a keyboard from the cloud, the download activity silently fails if the font or keyboard fails to download.
 
* This PR add a toast warning when font fails to download. (Keyboard is still installed)
keyboard font warning

* Also adds an error dialog if the keyboard fails to download
From the LanguageListActivity
language list error

* From the KeyboardListActivity
keyboard list error

(test code used to induce the above scenarios)

* The toast notifications in MainActivity and KeyboardListActivity also removed since they're handled in LanguageListActivity

* Finally, fixed null string exception when FileUtils.download() fails

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/140301:id/kvk/index.html)

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java [hunk 1]
```diff
@@ -344,8 +342,13 @@ protected int downloadNonKMPKeyboard(String remoteUrl) throws Exception {
 
         result = FileUtils.download(context, url, destination, filename);
         if (result < 0) {
-          ret = -1;
-          break;
+          if (FileUtils.hasFontExtension(url)) {
+            // Propogate warning about font failing to download
+            ret = 2;
```
Comment (jahorton) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: Should probably add this in the function's documentation comment as a possibility.

Also, maybe make it a custom exception instead?  Then catch that exception later where we expect to see it as a possibility.  That's probably better design than the old C-era error code strat.

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: I've updated the header comment. Hesitant to make it a custom exception though.
a) It's a "warning" condition where the keyboard downloads but not the font
b) The async task is meant to use `res` for the "result".

Comment (jahorton) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: Ah, if it's part of something async, that makes sense then.
