### PR TITLE
fix(developer): support for char + code font in LDML keyboard editor 🌱

### LINKED ISSUE #10456: bug(developer): LDML keyboard editor does not remember char/code font

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #10456.

@keymanapp-test-bot skip

### CODE REVIEW

File: developer/src/tike/actions/dmActionsDebugger.pas [hunk 1]
```diff
@@ -439,12 +457,14 @@ procedure TmodActionsDebugger.actDebugViewElementsUpdate(Sender: TObject);
 
 function TmodActionsDebugger.IsDebuggerInTestMode: Boolean;
 begin
-  Result := (ActiveKmnKeyboardEditor <> nil) and (ActiveKmnKeyboardEditor.DebugForm.UIStatus = duiTest);
+  Result := ((ActiveKmnKeyboardEditor <> nil) and (ActiveKmnKeyboardEditor.DebugForm.UIStatus = duiTest)) or
+    (ActiveLdmlKeyboardEditor <> nil);
```
Comment (darcywong00) [inline developer/src/tike/actions/dmActionsDebugger.pas:461]: Is there an `(ActiveLdmlKeyboardEditor.DebugForm.UIStatus = duiTest)` to check?

Comment (mcdurdin) [reply developer/src/tike/actions/dmActionsDebugger.pas:461]: No, because the ldml debugger only runs in Test mode -- we don't have line-by-line debugging in 17.0 for ldml keyboards.

**Review by darcywong00 — APPROVED** [review]
lgtm
