### PR TITLE
fix(ios/engine): banner inconsistency

### LINKED ISSUE #2907: [iOS] inconsistent banner and chopped off key preview
**Describe the bug**
Hide the banner. Outside the app: the first time the Keyman keyboard is launched, no banner is displayed (correctly) but the key preview of the top row is cut off. At any subsequent time (whether by switching the app or inputting in a different text box or just tapping elsewhere and then the same text box to show the keyboard again), the banner returns. Now with the banner there, the key previews fit within the table and wouldn't be cut off now.

Within the Keyman app everything behaves as expected.

**To Reproduce**
1. Untick "Show Banner"
2. Open Notes
3. Select Keyman
4. See an overtall keyboard 
5. Press a key on the top row
6. See the key preview popup cut off
7. Hide the keyboard and activate it again
8. See a normal height keyboard with banner shown
9. Press a key on the top row
10. See the key preview popup contained within the keyboard perimeters

**Expected behavior**
Expected: the banner is hidden with the popup displayed in full

**Screenshots**.
F0E20619-EFBB-452D-869E-2C37F271A863
F1DF579E-CE65-4CC4-AD4B-6F18CC1AE1E3

---
**iPhone/iPad/Android:**
 - Device: iPhone X
 - OS: iOS 13.4
 - Keyman version 13.0.105
 - Target application: Notes, Safari, etc

**Additional comments**
This is a minor bug for sure, so I'm not too bothered if it isn't fixed.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #2907.

These changes ensure that the banner always displays correctly upon initial load of the keyboard.

### CODE REVIEW

File: web/source/osk/visualKeyboard.ts [hunk 1]
```diff
@@ -1868,7 +1868,7 @@ namespace com.keyman.osk {
         this.hkKey=this.getSpecialKey(nLayer,'K_ROPT');
 
         // Always adjust screen height if iPhone or iPod, to take account of viewport changes
-        if(device.OS == 'iOS' && device.formFactor == 'phone') {
+        if(device.OS == 'iOS') {
           this.adjustHeights();
         }
```
Comment (jahorton) [inline web/source/osk/visualKeyboard.ts:1873]: I'm curious why the removed condition was put in place; removing it restores the original comment's context and also is critical for resolving the issue, which tended to show up on iPad rather than iPhone.

Note that the `adjustHeights` function is also used during device rotation to resize the keyboard, and rotation had been the workaround to get the banner to display if hidden on initial load.

File: ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift [hunk 2]
```diff
@@ -130,6 +130,9 @@ private class CustomInputView: UIInputView, UIInputViewAudioFeedback {
     }
     let topBarDelta = hideBanner ? 0 : InputViewController.topBarHeight
 
+    // Sets height before the constraints, as it's the height constraint that triggers OSK resizing.
+    keymanWeb.setBannerHeight(to: Int(InputViewController.topBarHeight))
```
Comment (mcdurdin) [inline ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift:134]: Does this reduce the banner flicker as well?

**Review by mcdurdin — APPROVED** [review]

File: ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift (hunk 2 above)
Comment (jahorton) [reply ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift:134]: This does nothing to address keyboard/banner flicker.
