### PR TITLE
fix(linux): Fix installation of keyboards with lang tag `mul`

### LINKED ISSUE #8620: bug(linux): Installed keyboard with language tag `mul` specified doesn't show up in available keyboards
I created a keyboard with BCP47 tag `mul` to indicate that it supports multiple languages. After installing that with `km-package-install -f itrans_devanagari_sanskrit_vedic.kmp -l mul` I noticed that it doesn't show up in the keyboards dropdown. Looking in the system keyboard settings shows that it gets installed with `mul-Zyyy`. Manually changing that in dconf Editor to `mul` will make it show up.

### PR DESCRIPTION
**Pull request by ermshiperete**
We now use the canonical tag without appending the script (unless necessary).

Also minimize bcp47 language tags in engine before adding the keyboards to ibus so that it matches the tags `km-config` installs.

Fixes #8620.

# User Testing

## Preparations

- The tests can be run on any Linux version

- [Install build artifacts of this PR](https://github.com/keymanapp/keyman/wiki/How-to-test-artifacts-from-pull-requests-for-Keyman-for-Linux)
- Reboot

## Tests

**TEST_INST_MUL**: Installation of keyboard with lang tag `mul`

- Download the attached keyboard ([itrans_devanagari_sanskrit_vedic.kmp.zip](https://github.com/keymanapp/keyman/files/11766968/itrans_devanagari_sanskrit_vedic.kmp.zip)) to your Downloads folder
- unzip the keyboard
- open a terminal window and run
  ```
  km-package-install -f ~/Downloads/itrans_devanagari_sanskrit_vedic.kmp -l mul
  ```
- verify that a keyboard _"Multiple languages (Vedic Sanskrit Devanagri Phonetic (ITRANS))"_ shows up in the keyboard dropdown

**TEST_INST_FUF**: Installation of keyboard with non-canonical language tag

- open Keyman Configuration
- click Downloads button and search for _Pular_
- install _"Fulfulde Latin (QWERTY)"_ keyboard
- verify that a keyboard _"Pular (Fulfulde Latin (QWERTY))"_ shows up in the keyboard dropdown

**TEST_INST_FUF2**: Installation of keyboard with language tag with script

- open Keyman Configuration
- click Downloads button and search for _Pular_
- install _"Fulfulde Ajami (QWERTY)"_ keyboard
- verify that a keyboard _"Pular (Fulfulde Ajami (QWERTY))"_ shows up in the keyboard dropdown

**TEST_INST_DYO**: Fix for #3399 still works

- open Keyman Configuration
- click Downloads button and search for _Jola_
- install _"EuroLatin (SIL)"_ keyboard for Jola-Fonyi language
- verify that a keyboard _"Jola-Fonyi (EuroLatin (SIL))"_ shows up in the keyboard dropdown

**TEST_INST_IPA**: Installation of IPA keyboard

- open Keyman Configuration
- download and install _"IPA (SIL)"_ keyboard
- verify that a keyboard _"Undetermined (IPA (SIL))"_ shows up in the keyboard dropdown

### CODE REVIEW

File: linux/ibus-keyman/src/bcp47util.c [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+  int capacity = 255;
+  char localeId[capacity];
+  uloc_forLanguageTag(tag, localeId, capacity, NULL, &status);
+  if (U_FAILURE(status)) {
+    g_error("%s: uloc_forLanguageTag returned %0x", __FUNCTION__, status);
+    return -1;
+  }
+
+  char minimizedLocaleId[capacity];
+  uloc_minimizeSubtags(localeId, minimizedLocaleId, capacity, &status);
```
Comment (darcywong00) [inline linux/ibus-keyman/src/bcp47util.c:19]: Does Keyman Developer use langtags.json to determine canonical tags? Wondering if we use that instead of icu? (would require more code though

Comment (mcdurdin) [reply linux/ibus-keyman/src/bcp47util.c:19]: We are moving towards using ICU for canonicalization everywhere. But we have work to do.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_INST_MUL (PASSED):** Tested with the attached PR build (keyman 17.0.143-alpha-local (package version 17.0.143-1~PR-9027+kinetic82) in Buntu Kinetic Kudu 22.10 OS (VM) and here is my observation: 1. Downloaded the attached keyboard (itrans_devanagari..) in the system. 2. Run the above mentioned command in the terminal and I was able to see the 'Multiple langauges..' keyboard in the keyboard dropdown. 

   

* **TEST_INST_FUF (PASSED):** Verified that "Pular (Fulfulde Latin (QWERTY))" keyboard in the keyboard dropdown. 

   


* **TEST_INST_FUF2 (PASSED):** Verified that "Pular (Fulfulde Ajami (QWERTY))" keyboard in the keyboard dropdown.

   

* **TEST_INST_DYO (PASSED):** Verified that "Jola-Fonyi (EuroLatin (SIL))" keyboard appears in the keyboard dropdown.

   

* **TEST_INST_IPA (PASSED):** Verified that "Undetermined (IPA(SIL))" keyboard appears in the keyboard dropdown.

File: linux/ibus-keyman/src/bcp47util.c [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+  if (strcmp(tag, "und-Latn") == 0) {
+    strncpy(minimizedTag, "und-Latn", tagCapacity);
+    return strlen(minimizedTag);
+  }
+
+  int capacity = 255;
+  char workingTag[capacity];
+
+  // special treatment for tags that start with `und`: replace `und` with `en`.
+  // ICU 70 doesn't properly treat `und`.
```
Comment (mcdurdin) [inline linux/ibus-keyman/src/bcp47util.c:30]: @srl295 any thoughts here?

**Review by mcdurdin — APPROVED** [review]
LGTM

File: linux/ibus-keyman/src/bcp47util.c (hunk 2 above)
Comment (srl295) [reply linux/ibus-keyman/src/bcp47util.c:30]: properly? `und` corresponds to `root` that is the base locale.

Comment (srl295) [reply linux/ibus-keyman/src/bcp47util.c:30]: sorry, i saw this earlier but didn't get to review

File: linux/ibus-keyman/src/bcp47util.c [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+  if (isUnd) {
+    strcpy(workingTag, "en");
+    strncat(&workingTag[2], &tag[3], capacity - 3);
+  } else {
+    strncpy(workingTag, tag, capacity - 1);
+  }
+  workingTag[capacity - 1] = 0;
+
+  char localeId[capacity];
+  uloc_forLanguageTag(workingTag, localeId, capacity, NULL, &status);
```
Comment (srl295) [inline linux/ibus-keyman/src/bcp47util.c:41]: uloc_forLanguageTag(`und`) will be interesting, maybe not what's expected - may be root

File: linux/ibus-keyman/src/bcp47util.c (hunk 1 above)
Comment (srl295) [reply linux/ibus-keyman/src/bcp47util.c:48]: what was it returning with `und` as input?

**Review by srl295 — COMMENTED** [review]
LGTM definitely improvement although i'd like to revisit und/mul/en

which ICU is it using? is it puling from system or using the embedded one from kmckmplib?

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.145-alpha](https://keyman.com/downloads/releases/alpha/17.0.145)
