### PR TITLE
fix(developer): requote font names

### LINKED ISSUE #4810: bug(developer): Font with quote in name breaks compiler
**Describe the bug**

sil_nko keyboard was updated and compiled with an error except a warning of having non canonical tag, i.e. 

```
sil_nko.kps: Keyboard with ID 'sil_nko' has a BCP 47 warning: 'emk-Nkoo' is a valid tag but is not canonical: it should be 'man-GN'.
sil_nko.kps: Keyboard with ID 'sil_nko' has a BCP 47 warning: 'man-Nkoo' is a valid tag but is not canonical: it should be 'man-GN'.
```

Now, when testing this keyboard on Chrome emulator, an error occurs "Error registering the sil_kno keyboard for sil_nko."
image

The same kind of error is experienced on mobile emulator as well:

First this message:
Screenshot_1616989911

Then this:
Screenshot_1616989914

The keyboard seems to be installed, but when switching over it, the same error messages occur.

**To Reproduce**

**Expected behavior**

**Screenshots**

---

**Keyman for Android:**
 - OS: Android 10 API 29
 - Keyman for Android: 14.0.270 stable

**Keyman Developer:**
 - OS: Windows Pro 10 2004 x64
 - Keyman Developer version: 14.0.270 stable

---

**Keyboard**
 - Keyboard name: [sil_nko](https://github.com/keymanapp/keyboards/pull/1501)
 - Keyboard version: 1.1
 - Language name: N'Ko

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4810.

### CODE REVIEW

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 1]
```diff
@@ -1367,14 +1367,15 @@ procedure TCompileKeymanWeb.ReportError(line: Integer; msgcode: LongWord; const
...
-function TCompileKeymanWeb.RequotedString(s: WideString): string;
+function TCompileKeymanWeb.RequotedString(s: WideString; RequoteSingleQuotes: Boolean = False): string;
 var
   i: Integer;
 begin
   i := 1;
   while i <= Length(s) do
   begin
     if (s[i] = '"') or (s[i] = '\') then begin s := Copy(s, 1, i-1)+'\'+Copy(s, i, Length(s)); Inc(i); end   // I4368
+    else if (s[i] = '''') and RequoteSingleQuotes then begin s := Copy(s, 1, i-1)+'\'+Copy(s, i, Length(s)); Inc(i); end
```
Comment (darcywong00) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas:1378]: Could this have been added to the `if` in l.1377?

**Review by darcywong00 — APPROVED** [review]
lgtm

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas (hunk 1 above)
Comment (mcdurdin) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas:1378]: I could have done -- but made the if statement more complicated than I wanted...
