### PR TITLE
[Android] Fix api.keyman.com/cloud query for BCP 47 language tags

### LINKED ISSUE #992: [android] exceptions switching to certain keyboards
I'm getting intermittent weirdness switching to certain keyboards.
Screenshot below is from [sil_bwe_karen]. In the keyboard catalog, it's listed under "Karen, Bwe".

Is there some KMW issue with BCP 47 tags involving script tags?

Using Keyman Android 10.0.401 beta
Android 7.1 Nougat

screenshot_20180616-141116

Once this happens, it seems to trigger switching to every currently installed keyboard . even the default EuroLatin2.  The keyboards seem to still type in the app.

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #992 

Update api.keyman.com query to:
* ~Update to cloud 4.0~ Reverted to 3.0
* Include `&languageidtype=bcp47

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java [hunk 1]
```diff
@@ -44,7 +44,7 @@
   public static final String ARG_URL = "KMKeyboardActivity.url";
   public static final String ARG_FILENAME = "KMKeyboardActivity.filename";
 
-  public static final String kKeymanApiBaseURL = "https://api.keyman.com/cloud/3.0/";
+  public static final String kKeymanApiBaseURL = "https://api.keyman.com/cloud/4.0/languages";
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: Please stick with api 3.0 for now.
