### PR TITLE
fix(ios): bad initial in-app layout, delayed banner, deprecated banner toggle

### LINKED ISSUE #10847: bug(ios): The Keyman banner only appears in landscape view after one additional device rotation
### Describe the bug

I noticed that the Keyman banner only appears in landscape view after one more rotation of the device.

### Reproduce the bug

1. Install Keyman 17.0.275-beta 
2. Open Keyman In-app. 
3. Download and Install sil_ipa or any other keyboard that does not have a dictionary feature. 
4. Enable as a system-wide keyboard. 
5. Open any browser. 
6. Change the Orientation into Landscape. 
7. Long the press the globe key. Switch Keyman Keyboard. 
8. Switch to sil_ipa keyboard. 

Here, I noticed that the Keyman banner was missing. 

9. Change the Orientation to Portrait. Revert to Landscape view. 

Now, the Keyman banner is visible. Seems to be a cosmetic issue. 

https://github.com/keymanapp/keyman/assets/19683143/115bf8f9-485f-4a58-9448-d85bda3e475f

### Expected behavior

Keyman banner should be visible for the keyboards (that do not have dictionary features) in landscape mode. 

### Related issues

_No response_

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.275-beta

### Operating system

ios 15.5, ios 17.0

### Device

iPhone 13 Mobile device, iphone 15 Pro Max Simulator (iOS 17.0)

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### LINKED ISSUE #10859: bug(ios): The predictive text goes beyond the border of the suggestion banner
### Describe the bug

I noticed that the predictive text appear on the suggestion banner is not displaying correctly.

### Reproduce the bug

1. Install Keyman 17.0.276-beta
2. Open Keyman In-app.
3. Enable "Don't show again" radio button from the Get Started menu.
4. Close the application.
5. Open Keyman In-app. 

Here, I noticed that the predictive text goes beyond the border of the suggestion banner. 

   

### Expected behavior

The predictive text should appear inside the suggestion banner. 

### Related issues

_No response_

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.276-beta

### Operating system

iOS 17.0, iOS 15.5

### Device

iPhone 13 Mobile

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #10859.

This fixes a layout issue that, upon the app's first load, can cause the keyboard to receive twice the intended adjustment for its vertical placement as intended, which tended to result in a clipped banner.

Additionally, now that we _always_ show a banner no matter what, this PR also removes the logic that enabled us to change the keyboard size based upon whether or not we were showing it.  (Before, that logic assumed "no banner" for its initial size values; the space was then allocated for the banner later.)  This prevents the component of the issue in which the keyboard would be too short on the first load.

## User Testing

TEST_IPHONE_13: Using the original test device from which #10859 was reported, verify that the issue is resolved.

1. Install this PR's test artifact.
2. Open Keyman In-app.
3. Enable "Don't show again" radio button from the Get Started menu.
    - If it is already enabled from a prior install, disable that toggle, force-quit the application, and restart from step 1.
4. Force-quit the application.
    - To force-quit an app on an iPhone X-style device, drag up from the bottom about halfway and release.  You should see a "carousel" of all apps open on the device.
        <details><summary>Visual aid (dropdown)</summary>
    
        iOS app force-quit

        </details>
        
        - If using Simulator, you can also double-tap the Home button.
        - If you return to the Home screen, you dragged too far.
    - From there, flick upward on the app (Keyman) you wish to close.
5. Open Keyman In-app. 
6. Verify that the keyboard is properly laid out and looks "correct".
7. Rotate the device to landscape and verify that the keyboard displays correctly.
8. Return to portrait orientation and verify that the keyboard displays correctly.
9. Verify that the system keyboard also displays correctly in both orientations.

TEST_IPHONE_SE:  Using an iPhone SE test target (real or Simulated), verify that the keyboard displays correctly.
1. Install this PR's test artifact.
2. Open Keyman In-app.
3. Enable "Don't show again" radio button from the Get Started menu.
    - If it is already enabled from a prior install, disable that toggle, force-quit the application, and restart from step 1.
4. Force-quit the application.
    - To force-quit an app on an iPhone SE-style device, simply double-tap the Home button.  You should see a "carousel" of all apps open on the device.
        <details><summary>Visual aid (dropdown)</summary>
    
        iOS app force-quit

        </details>
    - From there, flick upward on the app (Keyman) you wish to close.
5. Open Keyman In-app. 
6. Verify that the keyboard is properly laid out and looks "correct".
7. Rotate the device to landscape and verify that the keyboard displays correctly.
8. Return to portrait orientation and verify that the keyboard displays correctly.
9. Verify that the system keyboard also displays correctly in both orientations.

**Note**: this PR does _not_ fix #10847.  You may experience related issues when swapping the active keyboard in system-keyboard mode; that should not fail these user tests.

### CODE REVIEW

File: ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift [hunk 1]
```diff
@@ -131,6 +131,14 @@ class KeymanWebViewController: UIViewController {
     webView!.navigationDelegate = self
     webView!.scrollView.isScrollEnabled = false
 
+    // Disable WKWebView default layout-constraint manipulations. We ensure
+    // safe-area boundaries are respected via InputView / InputViewController
+    // constraints.
+    //
+    // Fixes #10859.
```
Comment (jahorton) [inline ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift:138]: If you want a complete, fully-technical explanation of how this helps to fix things, you may want to cross-reference  behavior documented here: https://github.com/keymanapp/keyman/issues/6595#issuecomment-1128575563

**Comment by jahorton** [comment]
Ack, merged a child PR into this one early.  Only realized after the fact.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IPHONE_13 (PASSED):** Tested with the attached PR build (17.0.281-beta-test-10929) on an iPhone 13 Mobile device (iOS 17.3.1) and here is my observation: 1. Opened the Keyman In-app. 2. Enable the "Don't show again" radio button from the Get Started menu. 3. Closed the application. 4. Re-opened Keyman In-app and verified that the predictive text appeared properly and the keyboard layout appeared correctly. 5. Rotate the device to landscape and verified that the keyboard is displayed correctly. 6. Returned to portrait orientation and verified that the keyboard displayed correctly. Also, verified that the system keyboard displayed correctly in both orientations. 

..Keyboard layout appeared correctly

   


..System keyboard displayed correctly

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IPHONE_SE (PASSED):** Tested with the attached PR build (17.0.281-beta-test-10929) on an iPhone SE (3rd generation / iOS 17.0) and here is my observation: 1. Opened the Keyman In-app. 2. Enable the "Don't show again" radio button from the Get Started menu. 3. Closed the application. 4. Re-opened Keyman In-app and verified that the predictive text appeared properly and the keyboard layout appeared correctly. 5. Rotate the device to landscape and verified that the keyboard is displayed correctly. 6. Returned to portrait orientation and verified that the keyboard displayed correctly. Also, verified that the system keyboard displayed correctly in both orientations.

..Keyman in Portrait view

   

..System Keyman keyboard in Landscape view

**Review by mcdurdin — APPROVED** [review]
LGTM; @sgschantz should probably also approve

**Comment by jahorton** [comment]
@sgschantz

**Comment by jahorton** [comment]
> Ack, merged a child PR into this one early. Only realized after the fact.

🎶 Oops, I did it again... 🎶 

Of course I spot-checked the base branch _after_ clicking the big green button.  Thanks, jetlag.

File: ios/engine/KMEI/KeymanEngine/Classes/Constants.swift [hunk 2]
```diff
@@ -61,6 +61,7 @@ public enum Key {
 
   // Settings-related keys
   static let optShouldReportErrors = "ShouldReportErrors"
+  // Deprecated - no longer used
   static let optShouldShowBanner = "ShouldShowBanner"
```
Comment (sgschantz) [inline ios/engine/KMEI/KeymanEngine/Classes/Constants.swift:65]: Should you just go ahead and remove this since it is no longer used?

File: ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift [hunk 3]
```diff
@@ -749,16 +749,6 @@ extension KeymanWebViewController: KeymanWebDelegate {
     }
   }
 
-  func updateShowBannerSetting() {
-    let userData = Storage.active.userDefaults
-    let alwaysShow = userData.bool(forKey: Key.optShouldShowBanner)
```
Comment (sgschantz) [inline ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift:754]: Now that this setting is no longer supported, it seems the key be removed from userDefaults when we see it. Is that cleaned up anywhere or is it an ignored remnant that lives on?

Comment (jahorton) [reply ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift:754]: Currently:  ignored remnant.  It'd only matter if we decide to use it again in some form at some point down the road.

File: ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js [hunk 4]
```diff
@@ -88,7 +86,7 @@ function setBannerImage(path) {
     }
 
     // If an inactive banner is set, update its image.
-    bc.inactiveBanner = bc.inactiveBanner ? new bc.ImageBanner(bannerImgPath) : null;
+    bc.inactiveBanner = new bc.ImageBanner(bannerImgPath);
```
Comment (sgschantz) [inline ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js:89]: what is meant by an inactiveBanner? is that one that doesn't do predictive text? that's my best guess -- or maybe it doesn't wave in the breeze on windy days

**Review by sgschantz — APPROVED** [review]
a couple questions but looks good

File: ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js (hunk 4 above)
Comment (jahorton) [reply ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js:89]: > is that one that doesn't do predictive text?

Bingo.  "Banner to use when predictive-text is inactive".

File: ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift (hunk 3 above)
Comment (sgschantz) [reply ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift:754]: I don't know if there is a good place to document this, but it would be a good comment to include somewhere in the code. The userdefaults is kind of like our settings document but with an undocumented file format, so it would be good to know what things could be floating around in there if anyone ever is trying to decipher real user data.

Comment (jahorton) [reply ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift:754]: Yeah... that was the intent behind leaving the deprecated key noted here: https://github.com/keymanapp/keyman/pull/10929#discussion_r1542337274 - that _is_ in the "Settings-related keys" section, after all.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.297-beta](https://keyman.com/downloads/releases/beta/17.0.297)
