### PR TITLE
fix(developer): force ES3 code generation for LMs

### LINKED ISSUE #7926: bug(developer): const variables may cause LM _importScripts to throw on Android 5.0
Some further investigation needed.
Const variables in lexical-models might be causing _importScripts to throw exceptions on Android 5.0

I experienced after installing fv_sencoten keyboard and dictionary.
(nrc.en.mtnt and sil.km.cnd do not throw on loading)

I made an engineering build of [nrc.str.sencoten](https://darcywong00.github.io/examples/nrc/nrc.str.sencoten.model.kmp) using `var` instead of `const` and it loaded fine

TODO - check if these lexical-models also throw exception on load on Android 5.0:
- [x] dotland.ru.russian
- [x] iles.chp.indigenous_nt
- [x] iles.dgr.indigenous_nt
- [x] sil.bcc-arab.upp_ptwl1
- [x] sil.glk-arab.ptwl1
- [x] sil.kjg-laoo.ptwl1
- [x] wyc_eth.mym-latn.me_en

For testing, I suggest search keyman.com by language ID
```
l:id:<bcp-47>
```

For contrast, I could install keyboard for mnw and `ait.mnw.mon.model.ts` successfully downloads and loads.

Sentry Issue: [KEYMAN-WEB-8E](https://sentry.io/organizations/keyman/issues/3726484232/?referrer=github_integration)

```
Error:  Error: Script error.
    at Error (native)
    at LMLayerWorker.loadModelFile (blob:null/1fdab8e8-d321-41da-a0bb-673e9b7ed29a:7295:22)
    at Object.state.handleMessage (blob:null/1fdab8e8-d321-41da-a0bb-673e9b7ed29a:7345:31)
    at LMLayerWorker.on...
  at Error (native)
  at LMLayerWorker.loadModelFile (blob:null/1fdab8e8-d321-41da-a0bb-673e9b7ed29a:7295:22)
  at Object.state.handleMessage (blob:null/1fdab8e8-d321-41da-a0bb-673e9b7ed29a:7345:31)
  at LMLayerWorker.onMessage (blob:null/1fdab8e8-d321-41da-a0bb-673e9b7ed29a:7226:24)
  at reduceConsoleArgs (/data/data/com.tavultesoft.kmapro.debug/app_data/keyman-sentry.js:879:36)
...
(2 additional frame(s) were not displayed)
```

This seems pretty consistent on 16.0 beta and 17.0 master branches of Keyman for Android.

May also impact documentation of
https://help.keyman.com/developer/16.0/guides/lexical-models/advanced/search-term-to-key

SO link
https://stackoverflow.com/questions/57532151/web-worker-importscripts-fails-to-place-script-variables-in-global-scope

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #7926.

Android 5.0 (Chrome 37) only supports ES3. Thus, we should transpile our lexical models to ES3 rather than ES2015, for now at least.

For example, this forces constructs such as `const` to be replaced with `var`.

@keymanapp-test-bot skip

(I have verified that the code generation is correct; this will require version bumps on all affected LMs in order to deploy an updated version with the new version of the compiler once it lands.)

### CODE REVIEW

File: developer/src/kmlmc/source/util/util.ts [hunk 1]
```diff
@@ -41,8 +41,8 @@ export function loadFromFilename(filename: string): LexicalModelSource {
   // NOTE: transpile module does a very simple TS to JS compilation.
   // It DOES NOT check for types!
   let compilationOutput = ts.transpile(sourceCode, {
-    // Our runtime should support ES6 with Node/CommonJS modules.
-    target: ts.ScriptTarget.ES2015,
+    // Our runtime only supports ES3 with Node/CommonJS modules on Android 5.0
```
Comment (jahorton) [inline developer/src/kmlmc/source/util/util.ts:44]: Was the `const` keyword the main notable thing?  

Also, would we leave this in place when we decide to shift our minimum requirements higher than Android 5.0?  If we think we might lift the JS target in the future, it might be wise to add related notes here.

**Review by eddieantonio — APPROVED** [review]
LGTM!

This PR can always be reverted if support for Android 5.0 is dropped.

File: developer/src/kmlmc/source/util/util.ts (hunk 1 above)
Comment (mcdurdin) [reply developer/src/kmlmc/source/util/util.ts:44]: Yes, `const` was the main thing we saw. But obviously given we accept arbitrary TS code, other ES2015+isms could easily creep in...

Comment (mcdurdin) [inline developer/src/kmlmc/source/util/util.ts:44]:
```suggestion
    // Our runtime only supports ES3 with Node/CommonJS modules on Android 5.0.
    // When we drop Android 5.0 support, we can update this to a `ScriptTarget` 
    // matrix against target version of Keyman, here and in 
    // lexical-model-compiler.ts.
```

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.128-beta](https://keyman.com/downloads/releases/beta/16.0.128)
