### PR TITLE
fix(developer): enable line breaks in debugger

### LINKED ISSUE #9444: bug(developer): enter key does not add a new line in the debugger
### Describe the bug

When testing a keyboard, the enter key  does not start a new line in the output.
The debugger says I pressed 000d, but the cursor is not on a new line.

image

### Reproduce the bug

1. Create keyboard layout that does not modify the Enter key
2. Compile and go to test (keyboard > test keyboard
3. Type some text
4. press Enter

### Expected behavior

The enter key would start  a new line in the output. 

### Related issues

_No response_

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.141

### Operating system

Windows 11 22H2

### Device

Windows laptop

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #9444.

# User Testing

* **TEST_DEBUGGER_ENTER_KEY:** In the Keyman Developer keyboard debugger, type text, then press Enter. Verify that a new line is inserted, and that the debugger character grid shows `000D` and `000A` values.
* **TEST_DEBUGGER_BKSP_KEY:** In the Keyman Developer keyboard debugger, type text, then press Enter. Press Bksp to delete the new line. Verify that both `000D` and `000A` values are deleted with a single press of Bksp.

### CODE REVIEW

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_DEBUGGER_ENTER_KEY (PASSED):** Tested with the attached PR build (Keyman Developer 17.0.203-alpha-test-9906) on Windows 11 OS (VM) and here is my observation: 1. Verified that a new line is inserted and the debugger character grid showed 000D and 000A values.

   


* **TEST_DEBUGGER_BKSP_KEY (PASSED):** 1. Verified that when the backspace key is pressed, it removes the new line. 2. Also, verified that both 000D and 000A values are deleted with a single press of Backspace.

File: developer/src/tike/child/UfrmDebug.pas [hunk 1]
```diff
@@ -894,7 +900,8 @@     TMemoSelectionState = record
     state: TMemoSelectionState;
   begin
     state := SaveMemoSelectionState;
-    memo.SelText := Text;
+    // Line breaks: replace \n with \r\n so line breaks work
+    memo.SelText := ReplaceStr(Text, #$0D, #$0D#$0A);
```
Comment (jahorton) [inline developer/src/tike/child/UfrmDebug.pas:904]: What keeps this from turning `#$0D#$0A` into `#$0D#$0D#$0A` (and so forth)?  And isn't this replacing `\r`, not `\n`?

Comment (mcdurdin) [reply developer/src/tike/child/UfrmDebug.pas:904]: > What keeps this from turning `#$0D#$0A` into `#$0D#$0D#$0A` (and so forth)? 

The `Text` parameter will never have `#$0D#$0A`; it will only ever have `#$0D`.

> And isn't this replacing `\r`, not `\n`?

Yes, right.

File: developer/src/tike/child/UfrmDebug.pas [hunk 2]
```diff
@@ -894,7 +900,8 @@     TMemoSelectionState = record
     state: TMemoSelectionState;
   begin
     state := SaveMemoSelectionState;
-    memo.SelText := Text;
+    // Line breaks: replace \n with \r\n so line breaks work
```
Comment (mcdurdin) [inline developer/src/tike/child/UfrmDebug.pas:903]:
```suggestion
    // Line breaks: replace \r (0x0D) with \r\n (0x0D 0x0A) so line breaks work
```

**Review by rc-swag — APPROVED** [review]
lgtm - once suggestion committed

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.204-alpha](https://keyman.com/downloads/releases/alpha/17.0.204)
