### PR TITLE
fix(android/app): Verify extracted text is not null

### LINKED ISSUE #11479: bug(android/app): NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null...
Sentry Issue: [KEYMAN-ANDROID-49Z](https://keyman.sentry.io/issues/4602655936/?referrer=github_integration)

```
NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
    at com.keyman.android.SystemKeyboard.onStartInput(SystemKeyboard.java:173)
    at android.inputmethodservice.InputMethodService.doStartInput(InputMethodService.java:2817)
    at android.inputmethodservice.InputMethodService$InputMethodImpl.startInput(InputMethodService.java:786)
    at android.inputmethodservice.InputMethodService$InputMethodImpl.dispatchStartInputWithToken(InputMethodService.java:817)
    at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:210)
...
(8 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #11479 - 
Will :cherries: pick to stable-17.0

Adds additional null check since getExtractedText 
> may fail either if the input connection has become invalid or the client is taking too long to respond with the text...

This was causing the crash:
> Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference

@keymanapp-test-bot skip

### CODE REVIEW

File: android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java [hunk 1]
```diff
@@ -169,7 +169,7 @@ public void onStartInput(EditorInfo attribute, boolean restarting) {
     InputConnection ic = getCurrentInputConnection();
     if (ic != null) {
       ExtractedText icText = ic.getExtractedText(new ExtractedTextRequest(), 0);
-      if (icText != null) {
+      if (icText != null && icText.text != null) {
```
Comment (mcdurdin) [inline android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java:172]:
```suggestion
      /*
        We do sometimes receive null `icText.text`, even though
        getExtractedText() docs does not list this as a possible 
        return value, so we test for that as well (#11479)
      */
      if (icText != null && icText.text != null) {
```

**Review by mcdurdin — APPROVED** [review]
LGTM

Adding a comment because this test diverges from Android documented expectations

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.39-alpha](https://keyman.com/downloads/releases/alpha/18.0.39)
