### PR TITLE
fix(web/ui): Fix check on indexOf

### LINKED ISSUE #4102: bug(web/ui) TypeError: Cannot read property 'indexOf' of undefined
Sentry Issue: [KEYMAN-WEB-19](https://sentry.keyman.com/organizations/keyman/issues/2131/?referrer=github_integration)

```
TypeError: Cannot read property 'indexOf' of undefined
  at VisualKeyboard.findNearestKey (/keyman.js:25563:53)
  at VisualKeyboard.<anonymous> (/keyman.js:25041:42)
```

```javascript
        if(childNode.className !== undefined  && (childNode.className.indexOf('key-hidden') >= 0)
             || (childNode.className.indexOf('key-blank') >= 0)){
          continue;
        }
```

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #4102 
Fixes KEYMAN-WEB-19

This fixes  the linked Sentry issue

### CODE REVIEW

File: web/source/osk/visualKeyboard.ts [hunk 1]
```diff
@@ -1317,8 +1317,8 @@ namespace com.keyman.osk {
         // Find the actual key element.
         let childNode = keySquare.firstChild ? keySquare.firstChild as HTMLElement: keySquare;
 
-        if(childNode.className !== undefined  && (childNode.className.indexOf('key-hidden') >= 0)
-             || (childNode.className.indexOf('key-blank') >= 0)){
+        if(childNode.className !== undefined  && ((childNode.className.indexOf('key-hidden') >= 0)
+             || (childNode.className.indexOf('key-blank') >= 0))){
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:1321]:
```suggestion
        if(childNode.className !== undefined
            && (childNode.className.indexOf('key-hidden') >= 0
             || childNode.className.indexOf('key-blank') >= 0)) {
```

Can reduce parens rather than increasing?

**Review by jahorton — APPROVED** [review]

**Review by mcdurdin — APPROVED** [review]
LGTM
