### PR TITLE
fix(developer): strip .kvk extension 🗜

### LINKED ISSUE #9152: bug(developer): kmc emits visual keyboard with .kvk.kvk extension when source file has .kvk extension 🗜
This can be seen with the following:

```
INFO 5002: Building C:\Projects\keyman\keyboards\release\packages\gff_amh_powerpack_7\source\gff_amh_powerpack_7.kps
WARN 20401a: Keyboard gff_amh_7 targets touch devices but corresponding gff_amh_7.js file is not in the package.
WARN 20401a: Keyboard gff_ethiopic_7 targets touch devices but corresponding gff_ethiopic_7.js file is not in the package.
WARN 20401b: The keyboard gff_ethiopic_7 should have at least one language specified.
ERROR 304003: File C:\Projects\keyman\keyboards\release\packages\gff_amh_powerpack_7\build\gff_amh_7.kvk does not exist.
ERROR 304003: File C:\Projects\keyman\keyboards\release\packages\gff_amh_powerpack_7\build\gff_ethiopic_7.kvk does not exist.
INFO 5007: gff_amh_powerpack_7.kps failed to build.
```

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #9152.

@keymanapp-test-bot skip

### CODE REVIEW

File: developer/src/kmc-kmn/src/compiler/compiler.ts [hunk 1]
```diff
@@ -385,7 +388,7 @@ export class KmnCompiler implements UnicodeSetParser {
     let writer = new KvkFileWriter();
     return {
       filename: this.callbacks.path.join(this.callbacks.path.dirname(kmxFilename),
-        this.callbacks.path.basename(kvksFilename, KeymanFileTypes.Source.VisualKeyboard) + KeymanFileTypes.Binary.VisualKeyboard),
+        basename + KeymanFileTypes.Binary.VisualKeyboard),
```
Comment (jahorton) [inline developer/src/kmc-kmn/src/compiler/compiler.ts:391]: Uh... isn't this going to result in a filename with two extensions?  As far as I can see, `basename` gets assigned either a `.kvks` or a `.kvk` filename, assuming I'm properly inferring what `this.callbacks.path.basename` does.

To clarify what I'm inferring:

```javascript
this.callbacs.path.basename('my_keyboard.kmn', KeymanFileTypes.Binary.VisualKeyboard')
```

would return `my_keyboard.kvk` - stripping off the base file-extension (`kmn`) and replacing it with the constant `KeymanFileTypes.Binary.VisualKeyboard`, which resolves to `.kvk`.

In which case... at line 391, as there is no `.basename` call, we could get `my_keyboard.kvk.kvk`.  Unless I'm missing something?

File: developer/src/kmc-kmn/src/compiler/compiler.ts [hunk 2]
```diff
@@ -345,10 +345,12 @@ export class KmnCompiler implements UnicodeSetParser {
     // The compiler detected a .kvks file, which needs to be captured
     kvksFilename = this.callbacks.resolveFilename(kmnFilename, kvksFilename);
     const filename = this.callbacks.path.basename(kvksFilename);
+    let basename = null;
     let vk: VisualKeyboard.VisualKeyboard = null;
     if(filename.endsWith('.kvk')) {
```
Comment (mcdurdin) [inline developer/src/kmc-kmn/src/compiler/compiler.ts:350]:
```suggestion
    if(filename.endsWith(KeymanFileTypes.Binary.VisualKeyboard)) {
```

This should have been done before... oops my bad.

File: developer/src/kmc-kmn/src/compiler/compiler.ts (hunk 1 above)
Comment (mcdurdin) [reply developer/src/kmc-kmn/src/compiler/compiler.ts:391]: `paths.basename` strips off an extension if it matches the provided extension. It's ugly, but that's what it does, so:

```js
const KeymanFileTypes.Binary.VisualKeyboard = '.kvk';
this.callbacks.path.basename('my_keyboard.kvk', KeymanFileTypes.Binary.VisualKeyboard) == 'my_keyboard'
```

**Review by jahorton — APPROVED** [review]
