### PR TITLE
fix(web): documentation keyboard style application + layout

### LINKED ISSUE #7691: bug(web): Keyboard CSS Not Applied in PHP Help Page
### Describe the bug

The PHP help page that is part of a keyboard project does not appear to apply the keyboard's CSS file when presenting layout tables.  For example, the following is the table as created by the web tester, it shows colored keys which come from the CSS definitions:

GFF-Amharic-Default-Layer-Web-Test

The same table as seen in the processed PHP page under the [keyman website](https://help.keyman.com/keyboard/gff_amharic/3.0/gff_amharic) , where the HTML code was:

`<div id='osk-phone' data-states='default ...' ></div>`

GFF-Amharic-Default-Layer-PHP-Help

Based on this visual contrast, it is assumed that the keyboard CSS file has not been included and applied to the layout presentation.

### Reproduce the bug

1. Create a keyboard that uses CSS to stylize keys.
2. View the stylized keys in the Keyman Developer web tester, and verify the style is present.
3. View the corresponding layout under the help PHP page, the style will not be applied.

### Expected behavior

The CSS visual effects will be seen in the layout views created by the PHP processor.

### Related issues

_No response_

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [X] Other - give details at bottom of form

### Keyman version

15.0.270

### Operating system

Any

### Device

Any

### Target application

_No response_

### Browser

Chrome

### Keyboard name

gff_amharic

### Keyboard version

3.0

### Language name

Amharic

### Additional context

I expect that the issue is universal and not specific to Amharic.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #7691.
Also provides some initial exploration & experimentation toward #4881.
Addresses a couple of points from #7268.

There are four total bugs addressed by this PR:

1.  Keyboard documentation elements were not being given their appropriate styling.
    a. The top-level keyboard-documentation object was not marked with a CSS class corresponding to the keyboard.
    b. Even if it were, the corresponding CSS stylesheet was never applied; it had only ever been inserted as part of a live, non-static OSK.  (The code was in `OSKView`, not `VisualKeyboard`, and so the doc-keyboard functionality never touched it.)

2. Row height was not being properly set for documentation keyboards, leaving an ugly 'blank row" on four-row layouts.

3.  The layer ID specified for documentation keyboards was never validated, with errors being "silently handled"... and returning a malformed "default" layer instead.  (Noted in #7268.)

4. Certain cases could cause a `NaN` value to appear in layout logic, which can easily lead to unintended side-effects if not properly caught and handled properly.

------

To help validate these changes, I've tweaked the "Tests keyboard documentation rendering" test page.

image

I did run into a fun issue while making the test page - displaying documentation for multiple different keyboards at once would result in font styling being stomped on by the last keyboard to be processed.  The cleanest way to resolve that tidbit... was to experiment with and utilize Shadow DOM on the test page to isolate each one's stylesheet within its own "shadow root" that also contained the OSK.  (This is **only** for the testing page, not within KeymanWeb itself.)  So, parts of this should be _very_ useful for #4881; it just makes the necessary changes "in post" on an isolated test page, rather than within KMW.

## User Testing

These tests should utilize the following two test pages:
- "Tests keyboard documentation rendering"
- "Test unminified Keymanweb"

**TEST_AMHARIC**:  Compare `gff_amharic`'s phone form-factor _default_ layer for the two test pages.

1. Load the "Tests keyboard documentation rendering" test page and verify that an OSK is rendered for `gff_amharic` under its header.
2. Load the keyboard on the "Test unminified Keymanweb" test page on an Android or iOS phone form-factor device.
    1. Type `gff_amharic` into the text box beside the first "Add" button, then click "Add".
    2.  Click the "Type here" textbox and swap to the Amharic keyboard to display its OSK.
3. Compare the two renders of the OSK.  If any special formatting is missing from the version on "Tests keyboard documentation rendering" page, _**FAIL**_ this test.
    - If testing via iOS (simulated or not), the two versions should be near-perfect matches.
    - **_Do not fail_** if there is no spacebar text.
    - **_FAIL_** if the font used for the keys does not match.

**TEST_EUROLATIN**:  Compare `sil_euro_latin`'s phone form-factor _shift_ layer for the two test pages.

1. Load the "Tests keyboard documentation rendering" test page and verify that an OSK is rendered for `sil_euro_latin` under its header.
2. Load the keyboard on the "Test unminified Keymanweb" test page on an Android or iOS phone form-factor device.
    1. `sil_euro_latin` should be pre-loaded.
    2.  Click the "Type here" textbox and swap to Norwegian (the SIL EuroLatin keyboard) to display its OSK.
    3. Activate the _shift_ layer.
4. Compare the two renders of the OSK.
    - If testing via iOS (simulated or not), the two versions should be near-perfect matches.
    - **_Do not fail_** if there is no spacebar text.
    - **_FAIL_** if the font used for the keys does not match.

**TEST_LAO_TABLET**:  Compare `lao_2008_basic`'s tablet form-factor _default_ layer for the two test pages.

1. Load the "Tests keyboard documentation rendering" test page and verify that an OSK is rendered for `lao_2008_basic` under its header.
2. Load the keyboard on the "Test unminified Keymanweb" test page on an Android or iOS tablet form-factor device.
    1.  `lao_2008_basic` should be pre-loaded.
    2.  Click the "Type here" textbox and swap to Lao to display its OSK.
3. Compare the two renders of the OSK.
    - If testing via iOS (simulated or not), the two versions should be near-perfect matches.
    - **_Do not fail_** if there is no spacebar text.
    - **_FAIL_** if the font used for the keys does not match.

**TEST_LAO_DESKTOP**:  Compare `lao_2008_basic`'s desktop form-factor _default_ layer for the two test pages.

1. Load the "Tests keyboard documentation rendering" test page and verify that an OSK is rendered for `lao_2008_basic` under its header.
2. Load the keyboard on the "Test unminified Keymanweb" test page via standard desktop browser (Chrome / Firefox / Edge / Safari).
    1.  `lao_2008_basic` should be pre-loaded.
    2.  Click the "Type here" textbox and swap to Lao to display its OSK.
3. Compare the two renders of the OSK.
    - If testing via iOS (simulated or not), the two versions should be near-perfect matches.
    - **_Do not fail_** if the orange border elements are missing; we're only testing the actual keyboard part of the OSK.
    - **_FAIL_** if the font used for the keys does not match.

**TEST_CAM_AZERTY**:  Compare `sil_cameroon_azerty`'s tablet form-factor _default_ layer for the two test pages.

1. Load the "Tests keyboard documentation rendering" test page and verify that an OSK is rendered for `gff_amharic` under its header.
2. Load the keyboard on the "Test unminified Keymanweb" test page on an Android or iOS tablet form-factor device.
    1. Type `sil_cameroon_azerty` into the text box beside the first "Add" button, then click "Add".
    2.  Click the "Type here" textbox and swap to the first language entry (Afade) to display its OSK.
3. Compare the two renders of the OSK.  If any special formatting is missing from the version on "Tests keyboard documentation rendering" page, _**FAIL**_ this test.
    - If testing via iOS (simulated or not), the two versions should be near-perfect matches.
    - **_Do not fail_** if there is no spacebar text.
    - **_FAIL_** if the font used for the keys does not match.

**TEST_KHMER**:  Compare `khmer_angkor`'s desktop form-factor _default_ layer for the two test pages.

1. Load the "Tests keyboard documentation rendering" test page and verify that an OSK is rendered for `khmer_angkor` under its header.
2. Load the keyboard on the "Test unminified Keymanweb" test page via standard desktop browser (Chrome / Firefox / Edge / Safari).
    1.  `khmer_angkor` should be pre-loaded.
    2.  Click the "Type here" textbox and swap to Khmer to display its OSK.
3. Compare the two renders of the OSK.
    - If testing via iOS (simulated or not), the two versions should be near-perfect matches.
    - **_Do not fail_** if the orange border elements are missing; we're only testing the actual keyboard part of the OSK.
    - **_FAIL_** if the font used for the keys does not match.

### CODE REVIEW

File: web/source/osk/oskRow.ts [hunk 1]
```diff
@@ -56,9 +56,7 @@ namespace com.keyman.osk {
       const rs = this.element.style;
 
       const rowHeight = vkbd.internalHeight.scaledBy(this.heightFraction);
-      if(vkbd.usesFixedHeightScaling) {
-        rs.maxHeight=rs.lineHeight=rs.height=rowHeight.styleString;
-      }
+      rs.maxHeight=rs.lineHeight=rs.height=rowHeight.styleString;
```
Comment (jahorton) [inline web/source/osk/oskRow.ts:60]: Fixes point 2 from the top-level description:

> Row height was not being properly set for documentation keyboards, leaving an ugly 'blank row" on four-row layouts.

File: web/source/osk/visualKeyboard.ts [hunk 2]
```diff
@@ -1304,7 +1326,12 @@ namespace com.keyman.osk {
     private getVerticalLayerGroupPadding(): number {
       // For touch-based OSK layouts, kmwosk.css may include top & bottom padding on the layer-group element.
       const computedGroupStyle = getComputedStyle(this.layerGroup.element);
-      return parseInt(computedGroupStyle.paddingTop, 10) + parseInt(computedGroupStyle.paddingBottom, 10);
+      let pt = parseInt(computedGroupStyle.paddingTop, 10);
+      let pb = parseInt(computedGroupStyle.paddingBottom, 10);
+
+      pt = isNaN(pt) ? 0 : pt; // parseInt('') == NaN; handle such cases!
+      pb = isNaN(pb) ? 0 : pb;
+      return pt + pb;
```
Comment (jahorton) [inline web/source/osk/visualKeyboard.ts:1334]: Fixes point 4 from the top-level description:

> Certain cases could cause a NaN value to appear in layout logic, which can easily lead to unintended side-effects if not properly caught and handled properly.

File: web/source/osk/visualKeyboard.ts [hunk 3]
```diff
@@ -1491,17 +1518,29 @@ namespace com.keyman.osk {
       kbd.style.border = '1px solid #ccc';
 
       // Once the element is inserted into the DOM, refresh the layout so that proper text scaling may apply.
-      const refreshInterval = window.setInterval(function () {
-        let computedStyle = getComputedStyle(kbd);
-        if (computedStyle.fontSize) {
-          if (kbd.style.fontSize) {
-            // Preserve the new setting (provided by CSS)
-            kbdObj.fontSize = new ParsedLengthStyle(kbd.style.fontSize);
+      const detectAndHandleInsertion = () => {
```
Comment (jahorton) [inline web/source/osk/visualKeyboard.ts:1521]: I remember a comment or two from recent reviews of other PRs that the use of a timeout here is somewhat suboptimal.  After a bit of thought and brainstorming, I realized the same goals could be handled via `MutationObserver` instead.

File: web/source/osk/visualKeyboard.ts [hunk 4]
```diff
@@ -1491,17 +1518,29 @@ namespace com.keyman.osk {
...
+          // Yay, insertion!
+
+          try {
+            // Are there font-size attributes we may safely adjust?  If so, do that!
+            if(getComputedStyle(kbd) && kbd.style.fontSize) {
+              kbdObj.fontSize = new ParsedLengthStyle(kbd.style.fontSize);
+            }
+
+            // Make sure that the stylesheet is attached, now that the keyboard-doc's been inserted.
+            kbdObj.appendStyleSheet();
```
Comment (jahorton) [inline web/source/osk/visualKeyboard.ts:1532]: Either way, re: `MutationObserver` vs `repeatInterval`, this section is the right place to ensure that the keyboard's stylesheet is properly appended.

File: web/testing/build-visual-keyboard/index.html [hunk 5]
```diff
@@ -50,56 +51,103 @@
                 platform == 'phone' ? 240 : 360;
       };
 
+      let shadowfy = function(container, style) {
```
Comment (jahorton) [inline web/testing/build-visual-keyboard/index.html:54]: @ #4881

**Comment by mcdurdin** [comment]
> The cleanest way to resolve that tidbit... was to experiment with and utilize Shadow DOM on the test page to isolate each one's stylesheet within its own "shadow root" that also contained the OSK. (This is only for the testing page, not within KeymanWeb itself.) So, parts of this should be very useful for https://github.com/keymanapp/keyman/issues/4881; it just makes the necessary changes "in post" on an isolated test page, rather than within KMW.

I like this. Excellent way to start experimenting without introducing shadow dom across the board too early!

File: web/source/osk/visualKeyboard.ts [hunk 6]
```diff
@@ -110,7 +110,16 @@ namespace com.keyman.osk {
...
+      const changedLayer = value != this._layerId;
+      if(this.layerGroup.layers[value]) {
+        this._layerId = value;
+      } else {
+        throw new Error(`Keyboard ${this.layoutKeyboard.id} does not have a layer with id ${value}`);
+      }
+
+      if(changedLayer) {
+        this.updateState();
+      }
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:122]:
```suggestion
      if(!this.layerGroup.layers[value]) {
        throw new Error(`Keyboard ${this.layoutKeyboard.id} does not have a layer with id ${value}`);
      }
      if(value == this._layerId) {
        return;
      }
      this._layerId = value;
      this.updateState();
```

Suggest we try and use the [return early pattern](https://gomakethings.com/the-early-return-pattern-in-javascript/).

File: web/source/osk/visualKeyboard.ts [hunk 7]
```diff
@@ -207,7 +216,20 @@ namespace com.keyman.osk {
         this.inputEngine.registerEventHandlers();
       }
 
-      Lkbd.className = device.formFactor + ' kmw-osk-inner-frame';
+      Lkbd.classList.add(device.formFactor);
+      Lkbd.classList.add('kmw-osk-inner-frame');
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:220]:
```suggestion
      Lkbd.classList.add(device.formFactor, 'kmw-osk-inner-frame');
```

See [spec](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/add).

File: web/source/osk/visualKeyboard.ts [hunk 8]
```diff
@@ -207,7 +216,20 @@ namespace com.keyman.osk {
...
+
+      // Tag the VisualKeyboard with a CSS class corresponding to its ID.
+      var kbdID: string = this.layoutKeyboard?.id.replace('Keyboard_','') ?? '';
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:223]:
```suggestion
      let kbdID: string = this.layoutKeyboard?.id.replace('Keyboard_','') ?? '';
```

File: web/source/osk/visualKeyboard.ts [hunk 9]
```diff
@@ -207,7 +216,20 @@ namespace com.keyman.osk {
...
+
+      if(kbdID.indexOf('::') != -1) { // We used to also test if we were in embedded mode, but... whatever.
+        // De-namespaces the ID for use with CSS classes.
+        // Assumes that keyboard IDs may not contain the ':' symbol.
+        kbdID = kbdID.substring(kbdID.indexOf('::') + 2);
+      }
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:229]:
```suggestion
      const separatorIndex = kbdID.indexOf('::');
      if(separatorIndex != -1) { // We used to also test if we were in embedded mode, but... whatever.
        // De-namespaces the ID for use with CSS classes.
        // Assumes that keyboard IDs may not contain the ':' symbol.
        kbdID = kbdID.substring(separatorIndex + 2);
      }
```

File: web/source/osk/visualKeyboard.ts [hunk 10]
```diff
@@ -1304,7 +1326,12 @@ namespace com.keyman.osk {
     private getVerticalLayerGroupPadding(): number {
       // For touch-based OSK layouts, kmwosk.css may include top & bottom padding on the layer-group element.
       const computedGroupStyle = getComputedStyle(this.layerGroup.element);
-      return parseInt(computedGroupStyle.paddingTop, 10) + parseInt(computedGroupStyle.paddingBottom, 10);
+      let pt = parseInt(computedGroupStyle.paddingTop, 10);
+      let pb = parseInt(computedGroupStyle.paddingBottom, 10);
+
+      pt = isNaN(pt) ? 0 : pt; // parseInt('') == NaN; handle such cases!
+      pb = isNaN(pb) ? 0 : pb;
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:1333]: I think we can [shorten this](https://stackoverflow.com/a/6736521/1836776) with `||`:

```suggestion
      const pt = parseInt(computedGroupStyle.paddingTop, 10) || 0; // parseInt('') -> NaN, fallback to 0
      const pb = parseInt(computedGroupStyle.paddingBottom, 10) || 0;
```

File: web/source/osk/visualKeyboard.ts [hunk 11]
```diff
@@ -1461,19 +1488,24 @@ namespace com.keyman.osk {
...
       let kbd = kbdObj.kbdDiv.childNodes[0] as HTMLDivElement; // Gets the layer group.
 
+      // Models CSS classes hosted on the OSKView in normal operation.  We can't do this on the main
+      // layer-group element because of the CSS rule structure for keyboard styling.
+      //
+      // For example, `.ios .kmw-keyboard-sil_cameroon_azerty` requires the element with the keyboard
+      // ID to be in a child of an element with the .ios class.
+      let classWrapper = document.createElement('div');
+      classWrapper.classList.add(device.OS.toLowerCase());
+      classWrapper.classList.add(device.formFactor.toLowerCase());
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:1503]:
```suggestion
      classWrapper.classList.add(device.OS.toLowerCase(), device.formFactor);
```

We are inconsistent between `OS` and `formFactor` already but let's at least keep `formFactor` consistent with its `-static` class name?

File: web/source/osk/visualKeyboard.ts [hunk 12]
```diff
@@ -1491,19 +1523,48 @@ namespace com.keyman.osk {
...
+          } finally {
+            insertionObserver.disconnect();
           }
-          kbdObj.refreshLayout();
-          window.clearInterval(refreshInterval);
         }
-      }, 10);
+      }
+
+      let insertionObserver = new MutationObserver(detectAndHandleInsertion);
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:1560]:
```suggestion
      const insertionObserver = new MutationObserver(detectAndHandleInsertion);
```

File: web/source/osk/visualKeyboard.ts [hunk 13]
```diff
@@ -1491,19 +1523,48 @@ namespace com.keyman.osk {
...
+            }
+
+            // Make sure that the stylesheet is attached, now that the keyboard-doc's been inserted.
+            // The stylesheet is currently built + constructed in the same code that attaches it to
+            // the page.
+            kbdObj.appendStyleSheet();
+
+            // Grab a reference to the stylesheet.
+            const stylesheet = kbdObj.styleSheet;
+            const stylesheetHead = stylesheet.parentElement;
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:1543]:
```suggestion
            const stylesheetParentElement = stylesheet.parentElement;
```

I got confused by `head` :grin:

File: web/source/osk/visualKeyboard.ts [hunk 14]
```diff
@@ -1491,19 +1523,48 @@ namespace com.keyman.osk {
...
+
+            // Don't reset top-level stuff; just the visible layer.
+            kbdObj.currentLayer.refreshLayout(kbdObj, kbdObj.height);
+
+            // We no longer need a reference to the constructing VisualKeyboard, so we should let
+            // it clean up its <head> stylesheet links.  This detaches the stylesheet, though.
+            kbdObj.shutdown();
+
+            // Now that shutdown is done, re-attach the stylesheet.
+            stylesheetHead.appendChild(stylesheet);
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:1553]:
```suggestion
            stylesheetParentElement.appendChild(stylesheet);
```

File: web/source/osk/visualKeyboard.ts [hunk 15]
```diff
@@ -1491,19 +1523,48 @@ namespace com.keyman.osk {
...
+            // Grab a reference to the stylesheet.
+            const stylesheet = kbdObj.styleSheet;
+            const stylesheetHead = stylesheet.parentElement;
+
+            // Don't reset top-level stuff; just the visible layer.
+            kbdObj.currentLayer.refreshLayout(kbdObj, kbdObj.height);
+
+            // We no longer need a reference to the constructing VisualKeyboard, so we should let
+            // it clean up its <head> stylesheet links.  This detaches the stylesheet, though.
+            kbdObj.shutdown();
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:1550]: Is this an opportunity for future cleanup? Why do we need to do this little dance of attach-detach-re-attach?

File: web/source/osk/visualKeyboard.ts [hunk 16]
```diff
@@ -1461,19 +1488,24 @@ namespace com.keyman.osk {
...
+      kbdObj.layerGroup.element.classList.add(device.formFactor + '-static');
 
       let kbd = kbdObj.kbdDiv.childNodes[0] as HTMLDivElement; // Gets the layer group.
 
+      // Models CSS classes hosted on the OSKView in normal operation.  We can't do this on the main
+      // layer-group element because of the CSS rule structure for keyboard styling.
+      //
+      // For example, `.ios .kmw-keyboard-sil_cameroon_azerty` requires the element with the keyboard
+      // ID to be in a child of an element with the .ios class.
+      let classWrapper = document.createElement('div');
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:1501]: My only concern here is that we are changing the DOM structure. I guess that it is supposed to be black-box, but I wonder if there will be existing code or CSS that fails because of the extra `<div>` in the tree?

File: web/testing/build-visual-keyboard/index.html [hunk 17]
```diff
@@ -50,56 +51,103 @@
...
+
+        label.textContent = `${keyman.getKeyboard(kbdid).Name} - ${formFactor} - ${layer} layer`;
+        idLabel.textContent = `${kbdid.replace(/^Keyboard_/)}`;
+        container.appendChild(docBase);
+
+        docTarget.appendChild(container);
+
+        await Promise.resolve(); // Trigger message queue:  let the mutation observer do its thing.
+
+        // Grab the stylesheet element that was inserted; there should be no intervening additions,
```
Comment (mcdurdin) [inline web/testing/build-visual-keyboard/index.html:92]: > there should be no intervening additions

This may be true for this page, but not generally true. Anything can happen when we `await` :grin:

**Review by mcdurdin — APPROVED** [review]
I've got a bunch of nits here but they're all just stylistic I think.

LGTM

File: web/source/osk/visualKeyboard.ts (hunk 16 above)
Comment (jahorton) [reply web/source/osk/visualKeyboard.ts:1501]: Actually, the CSS (on the testing page, at least) fails _without_ the extra `<div>` in the tree.  This change was necessary to support `sil_cameroon_azerty` and mimics the standard OSK `_Box` element that previously _did not exist_ for doc-keyboards.

File: web/source/osk/visualKeyboard.ts (hunk 13 above)
Comment (jahorton) [reply web/source/osk/visualKeyboard.ts:1543]: Well... in the current implementation, it quite literally is `<head>` for the active document.  Can still change the name over, though.

File: web/source/osk/visualKeyboard.ts (hunk 16 above)
Comment (mcdurdin) [reply web/source/osk/visualKeyboard.ts:1501]: Yep. We're doomed either way -- either it works consistently for keyboard CSS, and breaks for existing sites that use CSS with very specific selectors, or vice versa.

For some reason, I'm inclined to aim for consistency 😂

File: web/source/osk/visualKeyboard.ts (hunk 13 above)
Comment (mcdurdin) [reply web/source/osk/visualKeyboard.ts:1543]: Sure. But that's secret implementation knowledge :grin:

File: web/source/osk/visualKeyboard.ts (hunk 15 above)
Comment (jahorton) [reply web/source/osk/visualKeyboard.ts:1550]: If we didn't `shutdown`, we wouldn't need to re-attach.  Actually, in the current form of the codebase, I don't know that it does anything extra.

Still, since there are times where we do need to have aspects manually turned off when discarding an instance, I thought consistency in instance disposal would be best.

**Comment by bharanidharanj** [comment]
* **TEST_AMHARIC (PASSED):** Tested this PR as per the instructions in Windows Chrome browser and my Android Mobile device and here is my observation: 1. Compared the two renders of the OSK. It seems that both the versions are near-perfect matches. 2. Did not find any missing formatting from the version on "Tests keyboard documentation rendering"page.

..gff_amharic keyboard from Windows

   


..gff_amharic keyboard from Android Mobile

**Comment by bharanidharanj** [comment]
* **TEST_EUROLATIN (PASSED):** Compared the "Tests keyboard documentation rendering" test page for sil_euro_latin OSK with the "Test unminified Keymanweb"test page on an Android 12.0 emulator: Rendering both the versions of the OSK are near-perfect matches. Seems to be working as expected. 

Tests keyboard documentation rendering:




Test unminified Keymanweb:

**Comment by bharanidharanj** [comment]
* **TEST_LAO_TABLET (PASSED):** Compared the "Tests keyboard documentation rendering" test page for Lao 2008 Basic -tablet- OSK with the "Test unminified Keymanweb"test page on an Android 12.0 tablet emulator: Rendering in both the versions are near-perfect matches. 

..Tests keyboard documentation rendering:

   


..Test unminified Keymanweb:

**Comment by bharanidharanj** [comment]
* **TEST_LAO_DESKTOP (PASSED):** Compared the "Tests keyboard documenttion rendering" test page for lao_2008_basic OSK with the "Test uniminified Keymanweb"test page on a Mozilla Firefox browser: Rendering in both the versions are near-perfect matches. 

..Tests keyboard documentation rendering

   


..Test unminified Keymanweb

**Comment by bharanidharanj** [comment]
* **TEST_KHMER (PASSED):** Compared the "Tests keyboard documentation rendering" test page for khmer_angkor OSK with the "Test unminified Keymanweb"test page in a desktop (firefox) browser: Rendering in both the versions are near-perfect matches. 

..Tests keyboard documentation rendering

   


..Test unminified Keymanweb

**Comment by mcdurdin** [comment]
> ..Tests keyboard documentation rendering:
> 
> 

The key caps appear to have wrongly scaled text on most of these documentation images -- text is too small.

**Comment by jahorton** [comment]
> > ..Tests keyboard documentation rendering:
> > 
> 
> The key caps for touch keyboards appear to have wrongly scaled text on most of these documentation images -- text is too small.

Ah, there _is_ one font scaling factor that was missing until now.  Note that adding it back in doesn't make a big impact on 'phone' form factor doc-keyboards (x1.152), but it definitely makes a difference for tablets (x2):

image

image

**Comment by dyacob** [comment]
Just a note of caution, which may _not_ be applicable, if testing with the recent GFF Amharic v3.1 keyboard, you might encounter a false-positive test result.  The v3.1 PHP help page includes a local "kb.css" file that is a clone of the gff_amharic.css file from two directory levels up.  The v3.0 and earlier PHP help pages _do not_ make the inclusion.

**Comment by jahorton** [comment]
> Just a note of caution, which may _not_ be applicable, if testing with the recent GFF Amharic v3.1 keyboard, you might encounter a false-positive test result. The v3.1 PHP help page includes a local "kb.css" file that is a clone of the gff_amharic.css file from two directory levels up. The v3.0 and earlier PHP help pages _do not_ make the inclusion.

Fortunately, the test page you see above is completely divorced from the PHP help pages.  It's a completely separate rigging that can currently be found in-repo at [web/testing/build-visual-keyboard/index.html](https://github.com/keymanapp/keyman/blob/0836093170f5a3cfd5177f22c6e69ee6cbf00f92/web/testing/build-visual-keyboard/index.html).

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.107-beta](https://keyman.com/downloads/releases/beta/16.0.107)
