### PR TITLE
[web] Fix default mapping of external keyboard keys for "tab" and "backspace" in mobile apps

### LINKED ISSUE #1473: [web] Investigate external keyboard mapping for "tab" and "backspace"
As part of #1291 for the Android app, the mapping of external keyboard `tab` and `backspace` keys got passed to KMW (previously they defaulted to `0`).
This allows these sample Keyman rules to trigger:
```
+ [K_BKSP] > '[GO BACK]'
+ [K_TAB] > '[TAB]'
```

But as of 11.0.32 alpha, the external backspace key doesn't delete a character.
External tab key also doesn't insert whitespace.

~Perhaps we should revert those mappings?~
Per team discussion, keep the Android key mappings intact and update KMW

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #1473 by adding default handling of "tab" and "backspace" keys.

If there's keyboard rules for `K_TAB` or `K_BKSP`, they'll continue to be handled by KMW.

Otherwise, the default mapping inserts `\t` and default backspace respectively.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/138062:id/kvk/index.html)

File: web/source/kmwembedded.ts [hunk 1]
```diff
@@ -582,12 +582,17 @@
...
         return true;
+    } else if (code == osk.keyCodes.K_TAB) {
+        kbdInterface.output(0, Lelem, '\t');
+        return true;
+    } else if (code == osk.keyCodes.K_BKSP) {
+        kbdInterface.defaultBackspace();
+        return true;
     }
-    var ch = osk.defaultKeyOutput(keyName, code, shift, false);
+    var ch = osk.defaultKeyOutput(keyName, code, shift, false, null);
```
Comment (darcywong00) [inline web/source/kmwembedded.ts]: The signature is expecting `Lelem` as the last parameter.
Should we use `Lelem` or `null`?

Comment (jahorton) [reply web/source/kmwembedded.ts]: Leaving out the parameter makes it `undefined`, which is usually about the same as `null` but has different implications in certain scenarios.  Looking at the method being called, just go with `undefined`.

**Comment by darcywong00** [comment]
And I note the default mapping for the 102nd key doesn't happen either :/

File: web/history.md [hunk 2]
```diff
@@ -1,11 +1,7 @@
 # KeymanWeb Version History
 
-## 2019-01-03 11.0.201 beta
-* New Feature:
-  * Adds the alignInputs() API function to facilitate touch-alias element work-arounds in case of future issues. (#69)
-  
-* Bug Fix:
-  * Fixed keyboard layer transition bug on mobile devices. (#978)
+## 2019-01-04 11.0.202 beta
+* Fixed external keyboard keys "tab" and "backspace" for embedded platforms (#1474)
```
Comment (jahorton) [inline web/history.md]: Why are we removing these recent lines from history?

Comment (darcywong00) [reply web/history.md]: ack, I missed it in my rebase

File: web/source/kmwembedded.ts [hunk 3]
```diff
@@ -582,12 +582,17 @@
...
         return true;
+    } else if (code == osk.keyCodes.K_TAB) {
+        kbdInterface.output(0, Lelem, '\t');
+        return true;
+    } else if (code == osk.keyCodes.K_BKSP) {
+        kbdInterface.defaultBackspace();
+        return true;
     }
-    var ch = osk.defaultKeyOutput(keyName, code, shift, false);
+    var ch = osk.defaultKeyOutput(keyName, code, shift, false, undefined);
```
Comment (jahorton) [inline web/source/kmwembedded.ts]: The original line would have the same effect, but whatever.

File: web/source/kmwembedded.ts [hunk 4]
```diff
@@ -582,12 +582,17 @@
     if (code == osk.keyCodes.K_SPACE) {
         kbdInterface.output(0, Lelem, ' ');
         return true;
-    }
-    else if (code == osk.keyCodes.K_ENTER) {
+    } else if (code == osk.keyCodes.K_ENTER) {
         kbdInterface.output(0, Lelem, '\n');
         return true;
+    } else if (code == osk.keyCodes.K_TAB) {
+        kbdInterface.output(0, Lelem, '\t');
```
Comment (mcdurdin) [inline web/source/kmwembedded.ts]: Does this have the same behaviour when Keyman is not active? I would expect TAB to move between fields on a form, and ENTER to submit the form (unless in a multi-line text field). Concerned now that this changes that behaviour?
