### PR TITLE
fix(web): Suggestion reordering for RTL languages

### LINKED ISSUE #2523: Word suggestions from the dictionary should be in reverse order for RTL language keyboard.
I'm using the dictionary (word list) feature for a right-to-left language (Balochi). The keyboard is called Balochi phonetic. When I start typing a word, i.e. I type one letter, I see 3 suggestions. The one on the left with quotes is the first one you see when reading left to right. My users read right to left so I think it would be best to put the quoted word on the right and best matches continue from right to left. See screenshot.
Screenshot 2020-01-23 at 10 42 05 AM

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #2523.
Adds a patch (of sorts) toward #2522, but doesn't outright fix it. 

Screen Shot 2020-01-30 at 12 38 15 PM

While we can get _close_ to a fix for #2522 within the KeymanWeb engine (bypassing the LMLayer), properly handling the quotes still isn't perfect.  (Note the wrong ordering of the quote marks in the image above.)  The LMLayer sets the quotes, so the LMLayer needs to know whether or not the model is LTR or RTL.

There are arguments that can be made for two different directions to resolve the remaining issue:

1. Have KMW tell the LMLayer "use RTL mode"
    - Doing this will somewhat break the functional paradigm that currently exists within the LMLayer
2. Have a RTL flag be compiled into the model
    - This means more work for proper support, but the resulting coding patterns would be cleaner and not break the current structure of the LMLayer.

Since there's potential room for debate on which design to follow, the full-fledged fix will be handled in a later (dependent) PR.

### CODE REVIEW

File: web/source/osk/banner.ts [hunk 1]
```diff
@@ -320,7 +320,10 @@ namespace com.keyman.osk {
       if(suggestion.displayAs == null || suggestion.displayAs == '') {
         suggestionText = '\xa0';  // default:  nbsp.
       } else {
-        suggestionText = suggestion.displayAs;
+        // Default the LTR ordering to match that of the active keyboard.
+        let rtl = keyman.keyboardManager.isRTL();
+        let orderCode = rtl ? 0x202e /* RTL */ : 0x202d /* LTR */;
```
Comment (darcywong00) [inline web/source/osk/banner.ts]: Why does l. 332 use `\u200f` for rtl marker?

Comment (jahorton) [reply web/source/osk/banner.ts]: Huh.  It was supposed to accomplish a similar goal, but obviously it didn't quite get the RTL job done.  I should probably remove that section in favor of the newer one.

**Comment by darcywong00** [comment]
I ran this in the Android emulator for Balochi and the suggestions work
