### PR TITLE
[Web] Fix K_TAB from external keyboard

### LINKED ISSUE #2540: [Android] Tab key on physical keyboard not responding
Found during 13.0 pre-beta testing in #2529 

When the physical keyboard is connected, the Tab button fails to generate input (either tab character or navigate field)

Ctrl-Tab does bring up the keyboard picker menu.

### Configuration ###
master build
Android 8.1 device
external keyboard (either bluetooth or usb)
Applications tested: Chrome on textfields, Google Keep, Google sheets in Chrome

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #2540

This fixes KMW for embedded devices to not process `K_TAB` so the device will handle it.

### User Testing
Hardware needed: Android device, external keyboard (either via Bluetooth or USB). This won't work in Android Studio emulator

* Rebuild and load the Keyman app
* Set Keyman as the system keyboard

### Verify Tab navigates
* Open an Android app like Chrome or Google Keep
* Using the external keyboard, type in a text field and verify they appear
* Hit the "Tab" key
* Verify the app navigates to another field
* Hit Shift+Tab
* Verify the app navigates to a previous field

Note: if Google Chrome goes to a page like https://downloads.keyman.com/android/beta
Tabbing will highlight different release folders

I haven't seen an app that will insert `\t` when tab is hit yet...

### CODE REVIEW

**Comment by darcywong00** [comment]
The use of `K_TAB` to navigate to the next field does create this interesting scenario:

As a system app and suggestion banner enabled, K_TAB can eventually navigate to the first suggestion and all future keystrokes manually edit the far left suggestion.

**Comment by jahorton** [comment]
> The use of `K_TAB` to navigate to the next field does create this interesting scenario:
> 
> As a system app and suggestion banner enabled, K_TAB can eventually navigate to the first suggestion and all future keystrokes manually edit the far left suggestion.

Wait... tabbing allows navigating to elements of the keyboard?  That sounds _all kinds_ of wrong.  Or is this talking about something else?

**Comment by darcywong00** [comment]
> tabbling allows navigating to elements of the keyboard?

I only experienced tabbing into the first field in the suggestion banner.

**Comment by darcywong00** [comment]
Side effect 2: The tab navigation seems to jump 2 fields at a time

**Comment by jahorton** [comment]
> Side effect 2: The tab navigation seems to jump 2 fields at a time

Wait... two fields at once?  Sounds like it may be once from the '\t' character, and once from a different condition?  Maybe simply returning something caused the app to think "default handler" vs "ignore", and that's the other?

**Comment by darcywong00** [comment]
> two fields at once?

ah, it's cause my initial change had KMW generating `\t`, but the embedded app still had code to generate an additional tab event

**Comment by darcywong00** [comment]
OK, this latest change seems to bring K_TAB functionality back to how 12.0.18 alpha was.
Let KMW pass `K_TAB` to the lm-layer, but don't process the key event so the embedded device will handle it.

File: web/source/text/processor.ts [hunk 1]
```diff
@@ -519,6 +519,12 @@ namespace com.keyman.text {
         keyman.uiManager.setActivatingUI(false);	// I2498 - KeymanWeb OSK does not accept clicks in FF when using automatic UI
       }
 
+      // Special case for embedded to pass K_TAB back to device to process
+      if(keyman.isEmbedded && (keyEvent.Lcode == Codes.keyCodes["K_TAB"] ||
+          keyEvent.Lcode == Codes.keyCodes["K_TABBACK"] || keyEvent.Lcode == Codes.keyCodes["K_TABFWD"])) {
```
Comment (jahorton) [inline web/source/text/processor.ts]: I think this would fit better inserted near [line 159 of kmwembedded.ts](https://github.com/keymanapp/keyman/pull/2546/files/cbc243e30cfd856c7aec3d444133a3c2a0876409..90c441857d921d40075e97e1b53ea408a3a81216#diff-0b102a616ca81cfcf2c978ee673383d3R159) instead, modifying the return value there.

Comment (darcywong00) [reply web/source/text/processor.ts]: from what I can tell, that only returns strings, so I didn't have a way to return `false`

Comment (jahorton) [reply web/source/text/processor.ts]: Right, it's about JS event processing management.  My mistake.

**Comment by darcywong00** [comment]
Regarding the earlier scenario where it seemed like Tab would navigate into the suggestion banner,
I think what's really happening is the lm-layer isn't resetting context so the  keys continue to get added to the current suggestion.

File: web/source/text/processor.ts (hunk 1 above)
Comment (mcdurdin) [reply web/source/text/processor.ts]: I'm curious why this wouldn't eventually fall through to the embedded app anyway? What if we had a keyboard that wanted to do processing on TAB?
