### PR TITLE
fix(developer): EncodeURL was not handling spaces

### LINKED ISSUE #7810: bug(developer): Edits to KMDev Touch Visual Editor don't get saved/compiled until touch code has been opened and edited once.
### Describe the bug

Recently, I copied a test KMDev project to a dozen computers using 16.0.107. Once we opened the correct KMN file, we tried edit the touch layout via the visual editor. We would edit a field, save, compile, and open the browser. The touch changes were NOT showing up. As they fiddled with the project, one here and there started working and updating. We all upgraded to 16.0.110, and the same problem continued on the machines that had the problem. There were no console errors in the browser. 

Eventually, I clicked over to the touch code, and realized that the touch code had not been updated. When I returned to the touch editor, it had reverted. I went back and made the change in the code, saved, compiled and tested, and it worked. After this, I could make any [valid] change in the visual or code editor, and it would update. I did this on the remaining half-dozen machines to unlock them.

To rule out oddities specific to my project, it happened with others. My colleague opened a different keyboard he had created on his machine last year, made changes to the touch, saved, and compiled. The changes were not reflected in the browser. Clicking on the touch code showed that the changes were not retained. We made a minor change in the code, saved, returned to the visual editor, compiled, and all was well from then on.

### Reproduce the bug

Steps to reproduce:
1. Install KM Dev 16.0.107 or 16.0.110.
2. Open a project that hasn't been opened in Keyman 16 (or restore the attached one).
3. Try to make a change to the touch layout in the editor, save, compile, and test. No compile errors.
	-It will not have been updated.
4. Open the touch code and notice that it doesn't contain the change you just made. (It does seem to get reformatted on load.)
5. Make any valid change in the code, return to the visual touch editor. 
6. Compile and test to see that the problem is resolved.
7. Make more changes in the vidual editor and compile and it will work.

### Expected behavior

Expectation:
I expect that changes in either the code or the visual editor will be maintained. 

### Related issues

_No response_

### Keyman apps

- [X] Keyman Developer
- [X] KeymanWeb

### Keyman version

KMDev 16.0.107-16.0.110

### Operating system

Windows 10 21H1 through Windows 11 22H2

### Device

Windows Laptops

### Target application

Chrome and Edge

### Browser

Chrome and Edge

### Keyboard name

French Model

### Keyboard version

0

### Language name

_No response_

### Additional context

Because the touch code resets and "jumps" when opened, I suspect that there is some formatting normalisation happening on opening the code that finally makes it readable/editable by the visual touch editor (but that this reformatting doesn't happen just by using the touch editor. Maybe it's the comversion between quoted and unquoted numbers.

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #7810.

This addresses a regression introduced in #7631, where URL parameters with spaces would be encoded into `+` instead of `%20`. Looking a bit deeper at the Delphi `TNetEncoding.URL.Encode` function I realised that it was entirely inadequate. Some guy named Marc Durdin wrote a [blog](https://marc.durdin.net/2015/08/an-update-for-encodeuricomponent/) a good few years ago about the problem, and that's what I ended up using to fix this.

This encoding issue caused filenames with spaces (by default, project paths in Developer have spaces) to give a 404 when editing a touch layout, which meant that the touch keyboards could not be saved.

Also fixes [KEYMAN-DEVELOPER-74](https://sentry.io/organizations/keyman/issues/3081965404/?project=5983519), where the `+` encoding caused multiple entries to appear in the filename cache.

Amusing to Google this problem, find solid answer on SO, which pointed to my very own blog. Embarrassing that my own code didn't already include my own fix.

A secondary issue is also fixed here, where request parameters were double-decoded for formencoded POST requests. The fix for broken URL encodings was only required for GET requests.

This also showed up in KEYMAN-DEVELOPER-74, with double-encoded paths being registered as source files.

# User Testing

We need to verify that files are being loaded and saved correctly in the keyboard editor, keyboard project, and touch editor.

* **TEST_PATHS_WITH_SPACES:** Create a folder that contains spaces and English letters. Create a new keyboard project within that folder. In the Project view, press F12 to verify that no errors are raised in the Developer console. Do a basic regression test on working with the keyboard project, including editing, in particular the touch layout. Ensure that you make a change to the touch layout, save, compile and test it -- and make sure the change appears in the tested code.

* **TEST_NON_ASCII_PATHS:** Create a folder that contains non-ASCII letters, e.g. Khmer, Tamil or European diacritics. Create a new keyboard project within that folder. In the Project view, press F12 to verify that no errors are raised in the Developer console. Do a basic regression test on working with the keyboard project, including editing, in particular the touch layout. Note that keyboard compile may fail due to #7688; please don't fail this test on this basis.

### CODE REVIEW

File: common/windows/delphi/general/utilhttp.pas [hunk 1]
```diff
@@ -43,14 +43,63 @@ function ConvertPathToFileURL(s: WideString): WideString;
...
+  begin
+    if IsSafeChar(Bytes[I]) then
+    begin
+      Result[J] := Char(Bytes[I]);
+      Inc(J);
+    end
+    else
+    begin
+      Result[J] := '%';
+      Result[J+1] := HexMap[(Bytes[I] shr 4) + Low(HexMap)];
```
Comment (rc-swag) [inline common/windows/delphi/general/utilhttp.pas:90]: Can you please explain this line, including what the `Low(HexMap)` does?

**Comment by bharanidharanj** [comment]
* **TEST_PATHS_WITH_SPACES (PASSED):** Tested with that attached PR build (Keyman Developer 16.0.112-beta-test-7820) in Windows 11 (VM) and here is my observation: 1. Created a folder that contains spaces and English letters. Then, created a project within that folder. 2. Did some basic regression test with the keyboard project and verified that the changes that I made in the touch layout was reflected in the code view.

**Comment by bharanidharanj** [comment]
* **TEST_NON_ASCII_PATHS (PASSED):** 1. Created a folder that contains Tamil letters. 2. Created a new keyboard project within that folder. No errors are raised in the Developer console after pressing F12 Key. Also, did some basic regression test in the touch layout. Did not find any new errors except the compile error. Seems to be working as expected.

**Review by rc-swag — APPROVED** [review]
lgtm
