### PR TITLE
fix(web): fixes build number reference of API call

### LINKED ISSUE #2785: bug(web): bookmarklet does not work for full BCP 47 codes
**Describe the bug**
Clicking on bookmarklet on bookmark toolbar while on https://keyman.com/bookmarklet/ produces error
image
**To Reproduce**
1. Add language bookmarklet for a language as described in https://keyman.com/bookmarklet. I tried Newar(newa_traditional) and Kurumba, Kannada to see if this is specific to this particular language
2. click on a text box (I tried text box at bottom of https://keyman.com/bookmarklet)
3. Click on newly added bookmark 

4. While on gmail compose if you click on the bookmarklet, no error is seen but selected keyboard is not operational

**Expected behavior**
Keyman bookmarklet should work as described in https://keyman.com/bookmarklet

---

**KeymanWeb:**
 - OS: windows 10, Archlinux
 - Browser: Chrome 80, Firefox 73
 - KeymanWeb Version: [e.g. 10.0.201]
 - URL: https://keyman.com/bookmarklet,  gmail/compose 
---
 
**Keyboard**
 - Keyboard name: newa_traditional
 - Keyboard version: 1.1
 - Language name: Newa

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #2785.

I'd actually noticed this behavior recently on the KMW local testing pages, but just hadn't gotten around to making an issue for it in the midst of everything else last week.  It turns out that a change intended only for 14.0 got backported to 13.0 - how the old `_BUILD_` property is now relocated to `keyman.build` so that it can be set by environment.inc.ts.

The resulting issue is best highlighted by the two following API calls, both requesting `sil_euro_latin@no` - a Norwegian-tagged request for use of the SIL EuroLatin keyboard:
- (Current) https://api.keyman.com/cloud/4.0/keyboards?jsonp=keyman.register&languageidtype=bcp47&version=14.0.undefined&keyboardid=sil_euro_latin@no&timerid=7
- (Fixed) https://api.keyman.com/cloud/4.0/keyboards?jsonp=keyman.register&languageidtype=bcp47&version=14.0.18&keyboardid=sil_euro_latin@no&timerid=7

There's something about the API query that breaks when _both_ the keyboard ID _and_ the language ID are specified for a single keyboard whenever the build-number component is `undefined`.  Unfortunately, this is _**exactly**_ the use case that the KMW Bookmarklet uses.

### CODE REVIEW

File: web/source/kmwkeyboards.ts [hunk 1]
```diff
@@ -1212,7 +1212,7 @@ namespace com.keyman {
         Lscript = this.keymanweb.util._CreateElement('script');
       
       URL = URL + ((arguments.length > 1) && byLanguage ? 'languages' : 'keyboards')
-        +'?jsonp=keyman.register&languageidtype=bcp47&version='+this.keymanweb['version']+'.'+KeymanBase['__BUILD__'];
+        +'?jsonp=keyman.register&languageidtype=bcp47&version='+this.keymanweb['version']+'.'+this.keymanweb['build'];
```
Comment (darcywong00) [inline web/source/kmwkeyboards.ts]: Several of our platforms have had recent issues passing invalid versions to api.keyman.com

Can you add a regex to `+this.keymanweb['version']+'.'+this.keymanweb['build']`:
1. to ensure it's valid
2. generate a warning/error for troubleshooting when invalid?

Comment (darcywong00) [reply web/source/kmwkeyboards.ts]: Re-reading https://help.keyman.com/developer/cloud/4.0/ on `version`
> The version of Keyman Engine, e.g. "10.0". If absent, uses "2.0". The server will filter keyboards that are available for that version of Keyman Engine. (See KeymanWeb Versioning for details on valid version numbers.)

Maybe we only need `#.#` in the query?
e.g.
https://api.keyman.com/cloud/4.0/keyboards?jsonp=keyman.register&languageidtype=bcp47&version=14.0&keyboardid=sil_euro_latin@no&timerid=7

Comment (jahorton) [reply web/source/kmwkeyboards.ts]: @mcdurdin Any preference?

Comment (mcdurdin) [reply web/source/kmwkeyboards.ts]: I think we only need `#.#` in the query.
