### PR TITLE
fix(web): unexpected errors in OSK / banner position calculations

### LINKED ISSUE #3991: bug(web): TypeError: Cannot read property 'offsetTop' of null
During Keyman for Android 14.0 Beta acceptance testing #3989
The System keyboard would intermittently give a blank screen

(at some point during testing, I also turned off Predictions cause the banner covered up much of the screen. I believe at these crashes, the banner was off in sil_euro_latin)

Separately, might need to remove so many Android breadcrumbs going to the Sentry log...

Sentry Issue: [KEYMAN-WEB-Y](https://sentry.keyman.com/organizations/keyman/issues/1977/?referrer=github_integration)

```
TypeError: Cannot read property 'offsetTop' of null
  at a.<anonymous> (source/osk/visualKeyboard.ts:1214:56)
```

source/osk/visualKeyboard.ts at line 1214
```javascript
// We need to adjust the offset properties by any offsets related to the active banner
var yMin = Math.max(5, this.kbdDiv.offsetTop + _Box.offsetTop - 0.25*height);
```

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #3991.

As noted by https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent,

> `offsetParent` returns null in the following situations:
>
>    * The element or its parent element has the `display` property set to `none`.
>    * The element has the position property set to fixed (firefox returns `<body>`).
>    * The element is `<body>` or `<html>`.

The `_Box` element certainly uses the `fixed` position property, and noting that we've seen cases with opacity at 0, it's not a _huge_ stretch to imagine that said cases could be treated the same way as `display = 'none'` from the first point above.

Both the banner and the keyboard layer group elements are direct children of `_Box`, so we'd be better off relying on that fact and just using `parentElement` instead of `offsetParent`.  Along with a couple of null-guards and failsafe assignments, for extra robustness.

### CODE REVIEW

File: web/source/dom/uiTouchHandlerBase.ts [hunk 1]
```diff
@@ -425,7 +425,11 @@ namespace com.keyman.dom {
         // Cancel touch if moved up and off keyboard, unless popup keys visible
       } else {
         let base = this.baseElement;
-        let top = (base.offsetParent as HTMLElement).offsetTop + base.offsetTop;
+        let parent = this.baseElement.parentElement;
```
Comment (mcdurdin) [inline web/source/dom/uiTouchHandlerBase.ts:428]:
```suggestion
        let parent = base.parentElement;
```

But [`offsetParent` and `parentElement` are not the same](https://stackoverflow.com/a/17975012/1836776) so I don't think this change is going to be correct. It may be worth considering using [`Element.getBoundingClientRect`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) as an alternative?

**Review by mcdurdin — CHANGES_REQUESTED** [review]

File: web/source/dom/uiTouchHandlerBase.ts (hunk 1 above)
Comment (jahorton) [reply web/source/dom/uiTouchHandlerBase.ts:428]: I tested it as-is in the following situations:

- Emulation in Chrome, KMW's 'native' mode:
    - "Moto G4" (Android) emulation
    - iPhone SE (iOS) emulation
- 'native' mode on an iPhone SE 2
- embedded within the iOS app (via Xcode's Simulator)

Seems to work flawlessly in all cases listed above.  While I agree that the approach won't work for literally all uses of `offsetParent` that may exist, it _*does*_ appear to work for _this_ use quite well.  The OSK `_Box` element literally is the `offsetParent`... except when browsers decide `offsetParent` should return `null` instead b/c of current rendering / page-state conditions.

Comment (jahorton) [reply web/source/dom/uiTouchHandlerBase.ts:428]: It might break if used by the element hierarchy returned by the `buildDocumentationKeyboard` method (used for keyboard help)... except that 'keyboard' is explicitly non-interactive, meaning key previews don't exist there - and thus that there's nothing to break there.

Comment (mcdurdin) [reply web/source/dom/uiTouchHandlerBase.ts:428]: I see.

```suggestion
        let parent = base.parentElement; // parentElement is _Box
```

**Review by mcdurdin — APPROVED** [review]
Given the discussion above, I'm okay with approving this now.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.223-beta](https://keyman.com/downloads/releases/beta/14.0.223)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.9-alpha](https://keyman.com/downloads/releases/alpha/15.0.9)
