### PR TITLE
fix(web): documentation-keyboard font size, font scaling ⛲

### LINKED ISSUE #10444: bug(web): layout font size not being properly applied
When replying to https://community.software.sil.org/t/change-font-size-of-mobile-key-caps/8305/, we found that the 'proper' way to set fontsize for a layout isn't being handled properly by Keyman Engine for Web; at a minimum, it's getting overwritten whenever the OSK's layout is refreshed.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #10444.  (Covers remaining cases.)

As the keyboard-documentation element structure removes the layer group from the main element of a `VisualKeyboard`, font-size handling requires specialized logic to ensure all relevant bits land in the correct location.

This PR admittedly also includes some specialized handling for one of the documentation-keyboard Web test pages, looking forward to #4881:
- There had been a regression here from 16.0 related to the notes about @font-face within Shadow DOM, causing the fonts to not display properly on the test page.
- Stylesheet management is now better-structured for transition to Shadow DOM hosting.
- Before, if kmwosk.css wasn't properly available within the Shadow DOM setup at the time that the layout-refresh was called, it was possible for taller characters to be overly shrunk due to the lack of proper positioning and structure that resulted.

I used breakpoints to verify that the final layout-refresh used to build documentation keyboards now occurs after all related fonts are properly loaded, with _all_ relevant styles fully in-place and loaded.

@keymanapp-test-bot skip

### CODE REVIEW

File: web/src/engine/osk/src/visualKeyboard.ts [hunk 1]
```diff
@@ -1406,7 +1408,14 @@ export default class VisualKeyboard extends EventEmitter<EventMap> implements Ke
    *                                              (currently required for legacy reasons)
```
Comment (mcdurdin) [inline web/src/engine/osk/src/visualKeyboard.ts:1408]: documentation is out of sync with function signature

**Review by mcdurdin — APPROVED** [review]

**Review by ermshiperete — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.257-alpha](https://keyman.com/downloads/releases/alpha/17.0.257)
