### PR TITLE
fix(windows): #5336 appcontext get to handle small buffer

### LINKED ISSUE #5336: bug(windows): AppContext::Get incorrectly handles buffersizes smaller then CurContext buffer
**Describe the bug**

Get should copy the current context into the supplied buffer managed by the caller of size n. If size n is smaller than the AppContext buffer (source buffer) it should ensure it is returning the charters closest to the caret position and as many characters next to this as size n allows.  Currently, it returns the characters furthest from the caret and is truncated when it reaches the size n of the caller's buffer. 
Part 2 of this bug is that it could write past the end of the caller's buffer.

**Unit Test Required**
A unit test should be written that fails with the current implementation. That will then be used to verify the fix to both these bugs

**Implementation Hints:**
A solution for Get would be to use AppContext::Buf passing in the buffer size as the argument to get a pointer to the position in the CurContext to start the copy.  (as buf already handles sentinel and unit16 pairs) copy from the returned pointer to the termination of the buffer. 

**Keyman for Windows:**
 - Keyman version:

### PR DESCRIPTION
**Pull request by rc-swag**
Get correctly handles caller buffers smaller than the current context buffer. Ensuring the last code point is not truncated
Fixes  #5336

### CODE REVIEW

File: windows/src/engine/keyman32/appint/appint.cpp [hunk 1]
```diff
@@ -107,16 +107,40 @@ void AppContext::Reset()
...
-		*buf = *p; buf++;
-		if(*p >= 0xD800 && *p <= 0xDBFF) { *buf = *(++p); bufsize--; buf++; }
-	}
-	//wcsncpy(buf, CurContext, bufsize);
-	*buf = 0;
-	//buf[bufsize-1] = 0;
+  // surrogate pairs need to be treated as a single unit, therefore use
+  // BuffMax to find the startIndex.
+  // Buff Max handles the case where the surrogate pairs is split
+  // by the buff size
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/appint.cpp:113]:
```suggestion
  // BufMax to find a start index.
  // BufMax handles the case where a surrogate pair at the
  // start of the buffer is split by bufsize
```

File: windows/src/engine/keyman32/appint/appint.cpp [hunk 2]
```diff
@@ -107,16 +107,40 @@ void AppContext::Reset()
...
+  WCHAR* startIndex = this->BufMax(bufsize);
+
+  for (WCHAR* p = startIndex; *p && bufsize > 0; p++, bufsize--)
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/appint.cpp:116]:
```suggestion
  for (WCHAR *p = this->BufMax(bufsize); *p && bufsize > 0; p++, bufsize--)
```

File: windows/src/engine/keyman32/appint/appint.cpp [hunk 3]
```diff
@@ -107,16 +107,40 @@ void AppContext::Reset()
...
+  {
+    *buf = *p;
+    if ((*p >= 0xD800 && *p <= 0xDBFF) && (bufsize - 2 > 0)) { buf++;  *buf = *(++p); bufsize--; }
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/appint.cpp:119]: This is making the assumption that we don't have an unpaired surrogate in the buffer. Is that a harmful assumption? I don't think so.

Comment (mcdurdin) [reply windows/src/engine/keyman32/appint/appint.cpp:119]:
```suggestion
    if(Uni_IsSurrogate1(*p) && bufsize - 2 > 0) { 
      buf++; p++;
      *buf = *p;
      bufsize--;
    }
```

File: windows/src/engine/keyman32/appint/appint.cpp [hunk 4]
```diff
@@ -107,16 +107,40 @@ void AppContext::Reset()
...
+ // {
+//    *buf = *p; 
+//    if ((*p >= 0xD800 && *p <= 0xDBFF) && (bufsize - 2 > 0)) { buf++;  *buf = *(++p); bufsize--; }
+//    buf++;
+//  }
+
+//  *buf = 0;
+
+//}
+
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/appint.cpp:143]: Please remove commented code 😀

File: windows/src/engine/keyman32/appint/appint.h [hunk 5]
```diff
@@ -74,28 +74,97 @@ class AppActionQueue
...
+
   BOOL IsQueueEmpty() { return QueueSize == 0; }
   int GetQueueSize() { return QueueSize; }
 };
 
 class AppContext
 {
 private:
-	WCHAR CurContext[MAXCONTEXT];
+	WCHAR CurContext[MAXCONTEXT]; //!< CurContext[0] is furthest from the caret and is null terminated.
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/appint.h:85]:
```suggestion
	WCHAR CurContext[MAXCONTEXT]; //!< CurContext[0] is furthest from the caret and buffer is null terminated.
```

File: windows/src/engine/keyman32/appint/appint.h [hunk 6]
```diff
@@ -74,28 +74,97 @@ class AppActionQueue
...
+   * @brief  Add a single code unit to the Current Context. Not necessarily a complete code point
+   *
+   * @param Code unit to add
+   */
+  void Add(WCHAR ch);
+
+  /**
+   * @brief Removes a single code point from the end of the CurContext closest to the caret
+   *  - ie it will be both code units if a surrogate pair. If it is a deadkey it will remove
+   * the deadkey code point and the sentinal code point.
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/appint.h:107]:
```suggestion
   * @brief  Removes a single code point from the end of the CurContext closest to the caret;
   *         i.e. it will be both code units if a surrogate pair. If it is a deadkey it will
   *         remove three code points: UC_SENTINEL, CODE_DEADKEY and deadkey value.
```

File: windows/src/engine/keyman32/appint/appint.h [hunk 7]
```diff
@@ -74,28 +74,97 @@ class AppActionQueue
...
+   *
+   */
+  void Reset();
+
+  /**
+   * @brief Copies the characters in CurContext to supplied buffer.
+   * If bufsize is reached before the entire context was copied, the buf
+   * will be truncated to number of valid characters possible with null character
+   * termination. e.g. it will be one code unit less than buffsize if that would
+   * have meant spliting a surrogate pair
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/appint.h:122]:
```suggestion
   * @brief  Copies the characters in CurContext to supplied buffer.
   *         If bufsize is reached before the entire context was copied, the buf
   *         will be truncated to number of valid characters possible with null character
   *         termination. e.g. it will be one code unit less than bufsize if that would
   *         have meant splitting a surrogate pair
```

File: windows/src/engine/keyman32/appint/appint.h [hunk 8]
```diff
@@ -74,28 +74,97 @@ class AppActionQueue
...
+   * @param buf  The data buffer to copy current context
+   * @param bufsize the number of code units ie size of the WCHAR buffer - not the code points
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/appint.h:124]:
```suggestion
   * @param buf      The data buffer to copy current context
   * @param bufsize  The number of code units ie size of the WCHAR buffer - not the code points
```

File: windows/src/engine/keyman32/appint/appint.h [hunk 9]
```diff
@@ -74,28 +74,97 @@ class AppActionQueue
...
 	void Set(const WCHAR *buf);
+
+  /**
+   * @brief Returns a pointer to the character in the current context buffer which
+   * will have at most n valid characters remaining until the the null terminating character.
+   * eg it will be one code unit less than buffsize if that would
+   * have meant spliting a surrogate pair
+   *
+   * @param n The maximum number of valid characters - (code points) not WCHAR size (code units)
+   * @return WCHAR* Pointer to the start postion for a buffer of maximum n characters
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/appint.h:142]:
```suggestion
   * @brief  Returns a pointer to the character in the current context buffer which
   *         will have at most n valid xstring units remaining until the null terminating
   *         character. It will be one code unit less than bufsize if that would
   *         have meant splitting a surrogate pair or deadkey.
   *
   * @param n        The maximum number of valid xstring units (not code points or code units)
   * @return WCHAR*  Pointer to the start postion for a buffer of maximum n xstring units
```

File: windows/src/engine/keyman32/appint/appint.h [hunk 10]
```diff
@@ -74,28 +74,97 @@ class AppActionQueue
...
 	WCHAR *BufMax(int n);
+
+  /**
+   * @brief Returns a pointer to the character in the current context buffer which
+   * will have at most n characters remmaining until the the null terminating character.
+   * Note: Unlike BufMax there is no checking for truncation of code points.
+   * e.g. the pointer may point to a code unit that its half of a surrogate pair
+   *
+   * @param n
+   * @return WCHAR* Pointer to the start postion for a buffer of maximum n characters
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/appint.h:153]:
```suggestion
   * @brief  Returns a pointer to the character in the current context buffer which
   *         will have at most n code units remaining until the the null terminating character.
   *         Note: Unlike BufMax there is no checking for truncation of code points.
   *         e.g. the pointer may point to a code unit that is half of a surrogate pair.
   *
   * @param n
   * @return WCHAR* Pointer to the start postion for a buffer of maximum n characters
```

File: windows/src/engine/keyman32/appint/appint.h [hunk 11]
```diff
@@ -74,28 +74,97 @@ class AppActionQueue
...
+   */
 	WCHAR *Buf(int n);
+
+  /**
+   * @brief Returns TRUE if the latest code unit in the context is a deadkey
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/appint.h:158]:
```suggestion
   * @brief Returns TRUE if the last xstring unit in the context is a deadkey
```

File: windows/src/engine/keyman32/appint/appint.h [hunk 12]
```diff
@@ -74,28 +74,97 @@ class AppActionQueue
...
+   *
+   * @return BOOL
+   */
 	BOOL CharIsDeadkey();
+
+  /**
+  * @brief Returns TRUE if the latest code unit in the CurContext is a surrogate pair.
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/appint.h:165]:
```suggestion
  * @brief Returns TRUE if the last xstring unit in the CurContext is a surrogate pair.
```

File: windows/src/engine/keyman32/appint/appint.h [hunk 13]
```diff
@@ -74,28 +74,97 @@ class AppActionQueue
...
+   */
   void CopyFrom(AppContext *source);
-	void Add(WCHAR ch);
+
+  /**
+   * @brief  Add a single code unit to the Current Context. Not necessarily a complete code point
+   *
+   * @param Code unit to add
+   */
+  void Add(WCHAR ch);
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/appint.h:102]: I can see us rewriting Add to be `Add(DWORD ch)`, and `AddDeadkey(UINT deadkeyCode)`... For the future. That would make this much better encapsulated!

**Review by mcdurdin — CHANGES_REQUESTED** [review]
This is looking good. Changes requested are all cosmetic.

Have you validated current usage of `AppContext::Get` to ensure that its changed behaviour won't have any side-effects?

File: windows/src/engine/keyman32/appint/appint.cpp (hunk 3 above)
Comment (rc-swag) [reply windows/src/engine/keyman32/appint/appint.cpp:119]: > This is making the assumption that we don't have an unpaired surrogate in the buffer. Is that a harmful assumption? I don't think so.
Nice edit.  I don't think it is a harmful assumption as it will still copy an unpaired surrogate (it will not skip or anything). If Get returned an error code it would be a different story.

**Comment by rc-swag** [comment]
> This is looking good. Changes requested are all cosmetic.
> 
> Have you validated current usage of `AppContext::Get` to ensure that its changed behaviour won't have any side-effects?

Yes I have now :)

**Review by mcdurdin — APPROVED** [review]
LGTM

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.77-alpha](https://keyman.com/downloads/releases/alpha/15.0.77)
