### PR TITLE
[web] Pressing between keys gives wrong key

### LINKED ISSUE #863: [web] Between-key touch sometimes triggers unrelated key
For example, pressing between Q and W can sometimes trigger P.

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #863.

This was observed most frequently on iOS in-app. It was not observed in other apps. It seems there is a compatibility difference between the different web views -- see comments inline

Before merge, this therefore needs to be tested in:

- [x] Android app
- [x] iOS web
- [x] Android web
- [x] Chrome emulator on Windows

### CODE REVIEW

File: web/source/kmwosk.ts [hunk 1]
```diff
@@ -2863,8 +2863,8 @@ if(!window['keyman']['initialized']) {
       for(k = 0; k < t.childNodes.length; k++)
       {
         if(t.childNodes[k].firstChild.className.indexOf('key-hidden') >= 0) continue;
-        x1 = t.childNodes[k].firstChild.offsetLeft;
-        x2 = x1 + t.childNodes[k].firstChild.offsetWidth;
+        x1 = t.childNodes[k].offsetLeft;
```
Comment (mcdurdin) [inline web/source/kmwosk.ts]: Note: WKWebView treated this differently to all other browsers in testing. `t.childNodes[k].firstChild.offsetLeft` was always calculated relative to its parent element (i.e. `offsetParent != null`). However, for all other browsers `offsetParent == null` was `true`. We should consider moving to using `getBoundingClientRect()` everywhere in the future for better compatibility?
