### PR TITLE
fix(ios): fixes sys-kbd setup help link for iOS 9 and 10

### LINKED ISSUE #4770: bug(ios): bad link on iOS 9 / 10 devices for sys kbd installation
**Describe the bug**
For iOS 11 onward, Keyman supports a direct link into the app's Settings menu.  Unfortunately, the API doesn't exist on older iOS versions, which instead have long relied upon giving the user help instructions in an embedded page.

With the change to app help (which is now generated from Markdown), we forgot to maintain that link for use on older devices, resulting in this when choosing the appropriate option from the "Getting Started" menu:

Screen Shot 2021-03-24 at 9 34 20 AM

**Expected behavior**
It should link (properly) to `start/installing-system-keyboard.html` on such devices.

### PR DESCRIPTION
**Pull request by jahorton**
While we did think to fix the `InfoViewController` class, we'd simply forgotten to make the same changes for the `SetUpViewController`.

Fixes #4770.

### CODE REVIEW

File: ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift [hunk 1]
```diff
@@ -62,16 +65,16 @@ class SetUpViewController: UIViewController, UIWebViewDelegate {
 
     // Yes, .php.html.  That's how `wget` is set to retrieve it, since Safari won't recognize the contents
     // without the .html ending, it seems.
```
Comment (darcywong00) [inline ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift:67]: The .php.html comment can be updated

**Review by darcywong00 — APPROVED** [review]
lgtm. Nit on maintenance comment

File: ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift [hunk 2]
```diff
@@ -44,12 +44,15 @@ class SetUpViewController: UIViewController, UIWebViewDelegate {
...
-    switch networkStatus {
-    case Reachability.Connection.none?:
+    if let networkStatus = networkReachable?.connection {
+      switch networkStatus {
+      case Reachability.Connection.none, Reachability.Connection.unavailable:
+        loadFromLocal()
+      default:
+        loadFromServer()
+      }
+    } else {
```
Comment (mcdurdin) [inline ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift:54]: I can see a case for always loading help from local now that we have it locally -- that means the help will be in sync with the product. But no need to make that change just now.

File: ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift [hunk 3]
```diff
@@ -62,16 +65,16 @@ class SetUpViewController: UIViewController, UIWebViewDelegate {
...
-                                          inDirectory: nil)
+                                          inDirectory: "start")
     webView.loadRequest(URLRequest(url: URL.init(fileURLWithPath: filePath!)))
   }
 
   private func loadFromServer() {
     let appVersion = Version.current.majorMinor
     let url = "https://help.keyman.com/products/iphone-and-ipad/\(appVersion.plainString)"
-      + "/installing-system-keyboard.php?embed=ios"
+      + "/start/installing-system-keyboard"
```
Comment (mcdurdin) [inline ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift:77]: Even if we aren't currently using the `embed` param, I'd like to keep it in so that we can use it in the future on the site, if we are going to use the online help from the app.

**Review by mcdurdin — CHANGES_REQUESTED** [review]

File: ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift [hunk 4]
```diff
@@ -74,7 +72,7 @@ class SetUpViewController: UIViewController, UIWebViewDelegate {
   private func loadFromServer() {
     let appVersion = Version.current.majorMinor
     let url = "https://help.keyman.com/products/iphone-and-ipad/\(appVersion.plainString)"
-      + "/start/installing-system-keyboard"
+      + "/start/installing-system-keyboard?embed=ios"
```
Comment (darcywong00) [inline ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift:75]: I wonder if you wanted to set the help site based on the tier
alpha, beta -> help.keyman-staging
stable -> help.keyman.com ?

Comment (mcdurdin) [reply ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift:75]: I'd love to see a centralised location for URLs. And then a centralised location for the host names so a switch is easy as pie.

**Review by mcdurdin — APPROVED** [review]

File: ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift (hunk 4 above)
Comment (jahorton) [reply ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift:75]: I mean... that actually exists.  https://github.com/keymanapp/keyman/blob/a55b084ad5e2971b27eb1bfbe0882fc3354c64aa/ios/engine/KMEI/KeymanEngine/Classes/KeymanHosts.swift#L64-L69

It's half that I forgot about it when writing this PR and half that making such a change _is_ more substantial... and since this PR is meant for 🍒-picking, I wanted to keep the changeset as simple as possible.

Comment (jahorton) [reply ios/keyman/Keyman/Keyman/SetUpViewController/SetUpViewController.swift:75]: Newest commit fixes this.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.23-alpha](https://keyman.com/downloads/releases/alpha/15.0.23)
