### PR TITLE
fix(windows): avoid invalid language codes in Add Language dialog

### LINKED ISSUE #4343: bug(windows): Using invalid language codes in Add Language can cause misleading errors
Yes, the issue has not diverged. OSK toolbar is alright, but adding a language to a keyboard causes this:
image

_Originally posted by @MakaraSok in https://github.com/keymanapp/keyman/issues/4167#issuecomment-763332970_

We determined that this was due to the `cmo` language code being invalid.

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4343.

This patch makes all language codes from the langtags.json dataset visible through the Add Language dialog. This avoids situations where an incomplete code such as "cmo" can result in an error (a script is required for "cmo" as it is written in either Latn or Khmr).

## Searching for `cm`:

image

## Searching for `cmo`:

image

### CODE REVIEW

File: windows/src/desktop/kmshell/install/UfrmInstallKeyboardLanguage.pas [hunk 1]
```diff
@@ -413,6 +415,25 @@ procedure TfrmInstallKeyboardLanguage.FillLanguageGrid;
...
+      // Let's lookup the lang - script - region and get a good name
+      Result.Tag := Tag;
+      if not TLanguageCodeUtils.BCP47Languages.TryGetValue(Language, Result.LanguageName) then
+        Result.LanguageName := '';
+      if not TLanguageCodeUtils.BCP47Scripts.TryGetValue(Script, Result.ScriptName) then
+        Result.ScriptName := '';
+      if not TLanguageCodeUtils.BCP47Regions.TryGetValue(Region, Result.RegionName) then
+        Result.RegionName := '';
+      Result.FullName := TLanguageCodeUtils.LanguageName(Result.LanguageName,
+        Result.ScriptName, '');
```
Comment (darcywong00) [inline windows/src/desktop/kmshell/install/UfrmInstallKeyboardLanguage.pas:432]: You don't want to include the region name in the `FullName`?

Comment (mcdurdin) [reply windows/src/desktop/kmshell/install/UfrmInstallKeyboardLanguage.pas:432]: No, because the region name is shown elsewhere in the grid - see the screenshots above

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.234-beta](https://keyman.com/downloads/releases/beta/14.0.234)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)
