### PR TITLE
fix(ios): support for direct downloads of .kmp packages from within the in-app browser

### LINKED ISSUE #2197: [iOS] Attempting to install a package from within Keyman Browser gives error "Cannot open page" / "Frame load interrupted"
**Describe the bug**
.kmp packages cannot be installed from within the Keyman Browser -- they result in an error as shown below. The packages can be installed from an external browser okay.

Reported at https://community.software.sil.org/t/can-not-install-kmp-in-ios-13/2645/3

**To Reproduce**
1. Go to Keyman App, open the Keyman Browser.
2. Visit https://keyman.com/ and attempt to download a package
3. See error

**Screenshots**

image

**Workaround**

Install the package via another browser.

---

**iPhone:**
 - Device: iPhone 7
 - OS: 12.4.1
 - Keyman version 12.0.51
 - Target application: Keyman Browser

### PR DESCRIPTION
**Pull request by jahorton**
~~Fixes~~ Mitigates #2197.

Seems that the root issue was that the `UIWebView` type is more restrictive in how links are followed.  Since it's an in-app WebView, it doesn't want to perform downloads that good ol' Safari's perfectly happy to perform.  So... we need to be more proactive and intercept .kmp links.

Then... it turns out that with all the nifty, type-aware KMP installation functionality from earlier in 14.0's development... I accidentally made _non-type-aware_ KMP installation significantly trickier.  Ah well.

### CODE REVIEW

File: ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift [hunk 1]
```diff
@@ -204,6 +204,36 @@ class WebBrowserViewController: UIViewController, UIWebViewDelegate, UIAlertView
...
+      userData.set(nil as String?, forKey: webBrowserLastURLKey)
+      userData.synchronize()
+
+      // The user is trying to download a .kmp, but the standard
+      // UIWebView can't handle it properly.
+
+      ResourceDownloadManager.shared.downloadRawKMP(from: request.url!) { file, error in
+        // do something!
+        if let error = error {
+          let alert = ResourceFileManager.shared.buildSimpleAlert(title: "Error", message: error.localizedDescription)
```
Comment (jahorton) [inline ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift:221]: Yes, that `"Error"` should be localized.  Sadly, I noted that there are a couple of other matching, non-localized spots yet to handle... which are actually rather related:

https://github.com/keymanapp/keyman/blob/0801d69bbc80c6129974688d347e31fc851042d4/ios/engine/KMEI/KeymanEngine/Classes/Resource%20Management/ResourceFileManager.swift#L267-L282

(Lines 268 and 274, in particular.)

May as well address all three together, whether that be within this PR or a separate one.

File: ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift [hunk 2]
```diff
@@ -222,13 +252,25 @@ class WebBrowserViewController: UIViewController, UIWebViewDelegate, UIAlertView
...
+    let nsError = error as NSError
+    if let url = nsError.userInfo["NSErrorFailingURLKey"] as? NSURL {
+      signalError = !(url.path?.hasSuffix(".kmp") ?? false)
+    }
+
+    if signalError {
+      let alertController = UIAlertController(title: "Cannot Open Page",
+                                              message: error.localizedDescription,
+                                              preferredStyle: UIAlertController.Style.alert)
+      alertController.addAction(UIAlertAction(title: "OK",
```
Comment (jahorton) [inline ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift:269]: And probably these, too.

**Comment by jahorton** [comment]
The noted i18n spots have been rounded up as part of https://github.com/keymanapp/keyman/pull/4577.

File: ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift [hunk 3]
```diff
@@ -204,6 +204,38 @@ class WebBrowserViewController: UIViewController, UIWebViewDelegate, UIAlertView
   func webView(_ webView: UIWebView,
                shouldStartLoadWith request: URLRequest,
                navigationType: UIWebView.NavigationType) -> Bool {
+    if request.url?.lastPathComponent.hasSuffix(".kmp") ?? false {
```
Comment (mcdurdin) [inline ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift:207]: This may not be 100% correct. We should be looking at the [content-disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) header if it exists to determine the filename. We cannot assume that a URL will have a .kmp extension (e.g. it might be called something like `file-downloader.php`)

**Review by mcdurdin — CHANGES_REQUESTED** [review]

File: ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift (hunk 3 above)
Comment (jahorton) [reply ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift:207]: When using the keyman.com language search. the initial link _is_ PHP, though that ends up resolving to a .kmp that this can then intercept.

I'm _completely_ unfamiliar with such headers; have any good example ones you could point me at for this?

Comment (jahorton) [reply ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift:207]: Like, for an actual .kmp.

Comment (mcdurdin) [reply ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift:207]: I don't have one handy, but you could throw this onto a local website together with khmer_angkor.kmp (which you can even rename if you want, e.g. in the script below I renamed the copy I am reading from to example_khmer_angkor.dat just to illustrate). You could save this as `download.php`.

```php
<?php
  $file = './example_khmer_angkor.dat';
  header('Content-Type: application/octet-stream');
  header('Content-Disposition: attachment; filename=khmer_angkor.kmp');
  header('Content-Length: ' . filesize($file));
  readfile($file);
```

Comment (jahorton) [reply ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift:207]: I'll test with that shortly, but first I wanted to see what I can get from the keyboard search.

From the [keyboard page for `sil_ipa`](https://keyman.com/keyboards/sil_ipa), the link seems to process in three stages:

Stage 1:

```
▿ https://keyman.com/keyboard/download?id=sil_ipa&platform=ios&mode=standalone&cid=760108319.1607477546
  ▿ url : Optional<URL>
    ▿ some : https://keyman.com/keyboard/download?id=sil_ipa&platform=ios&mode=standalone&cid=760108319.1607477546
      - _url : https://keyman.com/keyboard/download?id=sil_ipa&platform=ios&mode=standalone&cid=760108319.1607477546
  - cachePolicy : 0
  - timeoutInterval : 2147483647.0
  ▿ mainDocumentURL : Optional<URL>
    ▿ some : https://keyman.com/keyboard/download?id=sil_ipa&platform=ios&mode=standalone&cid=760108319.1607477546
      - _url : https://keyman.com/keyboard/download?id=sil_ipa&platform=ios&mode=standalone&cid=760108319.1607477546
  - networkServiceType : __C.NSURLRequestNetworkServiceType
  - allowsCellularAccess : true
  ▿ httpMethod : Optional<String>
    - some : "GET"
  ▿ allHTTPHeaderFields : Optional<Dictionary<String, String>>
    ▿ some : 3 elements
      ▿ 0 : 2 elements
        - key : "Accept"
        - value : "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      ▿ 1 : 2 elements
        - key : "User-Agent"
        - value : "Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"
      ▿ 2 : 2 elements
        - key : "Referer"
        - value : "https://keyman.com/keyboards/sil_ipa"
  - httpBody : nil
  - httpBodyStream : nil
  - httpShouldHandleCookies : true
  - httpShouldUsePipelining : true
``` 

Stage 2:

```
▿ https://keyman.com/keyboards/download?id=sil_ipa&platform=ios&mode=standalone&cid=760108319.1607477546
  ▿ url : Optional<URL>
    ▿ some : https://keyman.com/keyboards/download?id=sil_ipa&platform=ios&mode=standalone&cid=760108319.1607477546
      - _url : https://keyman.com/keyboards/download?id=sil_ipa&platform=ios&mode=standalone&cid=760108319.1607477546
  - cachePolicy : 0
  - timeoutInterval : 2147483647.0
  ▿ mainDocumentURL : Optional<URL>
    ▿ some : https://keyman.com/keyboards/download?id=sil_ipa&platform=ios&mode=standalone&cid=760108319.1607477546
      - _url : https://keyman.com/keyboards/download?id=sil_ipa&platform=ios&mode=standalone&cid=760108319.1607477546
  - networkServiceType : __C.NSURLRequestNetworkServiceType
  - allowsCellularAccess : true
  ▿ httpMethod : Optional<String>
    - some : "GET"
  ▿ allHTTPHeaderFields : Optional<Dictionary<String, String>>
    ▿ some : 5 elements
      ▿ 0 : 2 elements
        - key : "Accept-Encoding"
        - value : "gzip, deflate, br"
      ▿ 1 : 2 elements
        - key : "Accept"
        - value : "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      ▿ 2 : 2 elements
        - key : "Referer"
        - value : "https://keyman.com/keyboards/sil_ipa"
      ▿ 3 : 2 elements
        - key : "User-Agent"
        - value : "Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"
      ▿ 4 : 2 elements
        - key : "Accept-Language"
        - value : "en-us"
  - httpBody : nil
  - httpBodyStream : nil
  - httpShouldHandleCookies : true
  - httpShouldUsePipelining : true
```

Stage 3:

```
▿ https://downloads.keyman.com/keyboards/sil_ipa/1.8.4/sil_ipa.kmp
  ▿ url : Optional<URL>
    ▿ some : https://downloads.keyman.com/keyboards/sil_ipa/1.8.4/sil_ipa.kmp
      - _url : https://downloads.keyman.com/keyboards/sil_ipa/1.8.4/sil_ipa.kmp
  - cachePolicy : 0
  - timeoutInterval : 2147483647.0
  ▿ mainDocumentURL : Optional<URL>
    ▿ some : https://downloads.keyman.com/keyboards/sil_ipa/1.8.4/sil_ipa.kmp
      - _url : https://downloads.keyman.com/keyboards/sil_ipa/1.8.4/sil_ipa.kmp
  - networkServiceType : __C.NSURLRequestNetworkServiceType
  - allowsCellularAccess : true
  ▿ httpMethod : Optional<String>
    - some : "GET"
  ▿ allHTTPHeaderFields : Optional<Dictionary<String, String>>
    ▿ some : 5 elements
      ▿ 0 : 2 elements
        - key : "Accept-Encoding"
        - value : "gzip, deflate, br"
      ▿ 1 : 2 elements
        - key : "Accept-Language"
        - value : "en-us"
      ▿ 2 : 2 elements
        - key : "Referer"
        - value : "https://keyman.com/keyboards/sil_ipa"
      ▿ 3 : 2 elements
        - key : "Accept"
        - value : "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      ▿ 4 : 2 elements
        - key : "User-Agent"
        - value : "Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"
  - httpBody : nil
  - httpBodyStream : nil
  - httpShouldHandleCookies : true
  - httpShouldUsePipelining : true
```

Comment (jahorton) [reply ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift:207]: Setting that up under my local keymanweb.com development 'server' setup...

```
▿ http://keymanweb.com.local/test.php
  ▿ url : Optional<URL>
    ▿ some : http://keymanweb.com.local/test.php
      - _url : http://keymanweb.com.local/test.php
  - cachePolicy : 0
  - timeoutInterval : 60.0
  ▿ mainDocumentURL : Optional<URL>
    ▿ some : http://keymanweb.com.local/test.php
      - _url : http://keymanweb.com.local/test.php
  - networkServiceType : __C.NSURLRequestNetworkServiceType
  - allowsCellularAccess : true
  ▿ httpMethod : Optional<String>
    - some : "GET"
  ▿ allHTTPHeaderFields : Optional<Dictionary<String, String>>
    ▿ some : 2 elements
      ▿ 0 : 2 elements
        - key : "Accept"
        - value : "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      ▿ 1 : 2 elements
        - key : "User-Agent"
        - value : "Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"
  - httpBody : nil
  - httpBodyStream : nil
  - httpShouldHandleCookies : true
  - httpShouldUsePipelining : true
```

There are no further stages; the next thing that occurs is a "Frame load interrupted" error.  So that's _all_ iOS will give me without _very_ significant changes, unless I'm missing something.

Comment (jahorton) [reply ios/keyman/Keyman/Keyman/KMWebBrowser/WebBrowserViewController.swift:207]: Just to make clear the testing setup I used:

Screen Shot 2021-03-04 at 2 59 46 PM

**Comment by jahorton** [comment]
So... while the solution implemented by this PR isn't optimal, as you've well pointed out... I think something only _partly_ broken is still much better than something _entirely_ broken.  We can always implement a follow-up, altering our perspective on this PR from "fixes" to a "mitigates".

**Comment by jahorton** [comment]
Alternatively, if you feel comfortable addressing this, please be my guest; I feel like I'm in over my head with your request.

**Review by mcdurdin — APPROVED** [review]
> So... while the solution implemented by this PR isn't optimal, as you've well pointed out... I think something only _partly_ broken is still much better than something _entirely_ broken. We can always implement a follow-up, altering our perspective on this PR from "fixes" to a "mitigates".

I did some more research online and it seems like this is an open problem with both WKWebView and UIWebView. All sorts of esoteric ideas on how to work around it but no simple `onFileDownload` approach such as one would hope for. 

Given that, let's go ahead with your implementation as it stands.
