### PR TITLE
fix(android): Localize Toast notifications

### LINKED ISSUE #4475: bug(android): Khmer string found when English is chosen as the UI language
**Describe the bug**

While testing ML, I got to install, uninstall and reinstall the dictionary of a keyboard manually. In this case, when trying to "Check for a available dictionary," a notification in Khmer appears even though the UI language is set to English.

Screenshot_1613013601

**To Reproduce**

1. Go to 'Settings' > 'Installed Languages'
2. Click on 'Central Khmer'
3. Scroll down to the bottom and click on 'Dictionary' to check for associate dictionary to download

**Expected behavior**

The message should be in English -- 'No dictionary to download'.

---

**Keyman for Android:**
 - Device: Pixel 2 API 29
 - OS: Android 10
 - Keyman version 14.0.241-beta
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.7
 - Language name: Khmer

**Additional Context**
This behavior can also be experienced when a keyboard without a dictionary is completing the installation. Try and install "Mongolian Cyrillic Basic" keyboard and observe this behavior when the installation is looking for available dictionary to download, but fail.

Screenshot_1613026925

### PR DESCRIPTION
**Pull request by darcywong00**
Follow-on to #4261 and fixes #4475

Currently, overriding string resources to use the chosen display language only work for classes that extend `BaseActivity` (`AppCompatActivity`). For the remaining classes, Toast notifications end up using the device's default locale.

This PR adds a helper method `BaseActivity.makeToast()` so the Toast messages will be consistent with the display language. ~I had to simplify some Toast strings to avoid `makeToast` needing to `String.format` with variable parameters.~

(updated): The Toast strings optionally handle formatted strings. Note, messages to Sentry aren't localized.

### Other cleanup
* Remove unused string `failed_to_access_downloaded_file`

## User Testing
@MakaraSok , please test with the scenarios you reported in the issue

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/BaseActivity.java [hunk 1]
```diff
@@ -18,6 +20,20 @@
...
+   * in the updated locale.
+   * @param defaultContext - the context to fallback if localeUpdatedContext is null
+   * @param resID - resource ID of the string
+   * @param duration - length of the Toast notification (Toast.LENGTH_LONG or Toast.LENGTH_SHORT)
+   */
+  public static void makeToast(Context defaultContext, int resID, int duration) {
+    Context context = (localeUpdatedContext != null) ? localeUpdatedContext : defaultContext;
+    String msg = context.getString(resID);
+    Toast.makeText(context, msg, duration).show();
+  }
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/BaseActivity.java:36]:
```suggestion
  /**
   * Some classes aren't an AppCompatActivity and need this helper to localize Toast notifications
   * in the updated locale.
   * @param defaultContext - the context to fallback if localeUpdatedContext is null
   * @param resID - resource ID of the string
   * @param duration - length of the Toast notification (Toast.LENGTH_LONG or Toast.LENGTH_SHORT)
   * @param args - format parameters for the string
   */
  public static void makeToast(Context defaultContext, int resID, int duration, Object... args) {
    Context context = (localeUpdatedContext != null) ? localeUpdatedContext : defaultContext;
    String msg = context.getString(resID);
    Toast.makeText(context, String.format(msg, args), duration).show();
  }
```

**Review by mcdurdin — CHANGES_REQUESTED** [review]
I think it should be fairly straightforward to support format strings in the makeToast function, which means we avoid losing useful information. Apart from that change, I think this all looks fine.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/BaseActivity.java (hunk 1 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/BaseActivity.java]: Thanks! That wasn't as painful as I thought.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/HelpFile.java [hunk 2]
```diff
@@ -47,8 +49,11 @@ public static Intent toActionView(Context context, String helpFile, String packa
         i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
         i.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
       } catch (NullPointerException e) {
-        String message = "FileProvider undefined in app to load" + customHelp.toString();
-        Toast.makeText(context, message, Toast.LENGTH_LONG).show();
+        // Localize Toast error
+        BaseActivity.makeToast(context, R.string.fileprovider_undefined, Toast.LENGTH_LONG);
```
Comment (darcywong00) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/HelpFile.java:53]: I chose not to use the formatted string for the Toast here, since the full path to the help file will just be gibberish to the user (and quite long)

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.253-beta](https://keyman.com/downloads/releases/beta/14.0.253)

**Comment by MakaraSok** [comment]
Tested with Keyman 14.0.259-beta.

Confirm that this fixes the issue.
