### PR TITLE
fix(web): re-establishes web srcmap uploading

### LINKED ISSUE #9176: bug(web): Sentry error reports are not being properly matched against the source
Looks like some of the changes from the ES module work have led to a significant reduction in detail in the quality of our Sentry error reports.

Example report:
https://keyman.sentry.io/share/issue/0500abcd12734ba18d7399b764c57a02/

image

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #9176.

So, I'd disabled the Sentry sourcemap-uploads a bit before ES module work took place during 17.0-alpha in #7474.  It's been that way since then for 17.0 alpha, but 16.0 alpha still did proper sourcemap-uploading.

This PR seeks to re-establish that uploading so we can get nice stacktraces in our Sentry reports again.

@keymanapp-test-bot skip

### CODE REVIEW

File: web/ci.sh [hunk 1]
```diff
@@ -42,6 +42,21 @@ builder_parse "$@"
...
+  elif [ $1 = "browser" ]; then
+    ARTIFACT_FOLDER="$KEYMAN_ROOT/web/build/publish/release/"
+  fi
+
+  pushd "$ARTIFACT_FOLDER"
+  echo "Uploading to Sentry..."
+  npm run sentry-cli -- releases files "$SENTRY_RELEASE_VERSION" upload-sourcemaps --strip-common-prefix "@keymanapp/keyman/" --rewrite --ext js --ext map --ext ts || fail "Sentry upload failed."
+  echo "Upload successful."
+  popd
+}
```
Comment (jahorton) [inline web/ci.sh:58]: For comparison, from our current `stable-16.0` build script:

https://github.com/keymanapp/keyman/blob/7a67894bbbdfe53b0da1c85dfc5b3d9a1965c74d/web/source/build.sh#L553-L560

Comment (jahorton) [reply web/ci.sh:58]: Note that post-modularization, to ensure that pathing to all components (even outside `web/`) works correctly, the "sourcesRoot" is set to `@keymanapp/keyman/<repo path>` as of #8995.

Comment (jahorton) [reply web/ci.sh]: I've since nixed the `npm run` and `--` parts of the `sentry-cli` command.  I'd forgotten that it's not a npm script anymore and that we can run it directly now.

File: web/ci.sh [hunk 2]
```diff
@@ -42,6 +42,21 @@ builder_parse "$@"
...
+function web_sentry_upload () {
+  if [ $1 = "webview" ]; then
+    # There is no "publish" version for app/webview; it's "published" inside our mobile apps.
+    ARTIFACT_FOLDER="$KEYMAN_ROOT/web/build/app/webview/release/"
+  elif [ $1 = "browser" ]; then
+    ARTIFACT_FOLDER="$KEYMAN_ROOT/web/build/publish/release/"
+  fi
+
+  pushd "$ARTIFACT_FOLDER"
+  echo "Uploading to Sentry..."
```
Comment (mcdurdin) [inline web/ci.sh:54]:
```suggestion
  echo "Uploading $1 to Sentry..."
```

**Review by mcdurdin — APPROVED** [review]

**Comment by jahorton** [comment]
Dang it, meant to include that suggested change... ah well.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.134-alpha](https://keyman.com/downloads/releases/alpha/17.0.134)
