### PR TITLE
fix(android): Use alert dialog when package is missing touch keyboards

### LINKED ISSUE #10132: bug(android): 'no touch optimized keyboards' message is a toast that disappears too quickly
### Describe the bug

When installing a keyboard package that is missing a touch-optimized .js keyboard file, a toast appears indicating that there is an error, but it is truncated and disappears too quickly. It should be a message box because it's an error the user should respond to.

Screenshot_20231205_123245_Keyman Alpha-test-10103

### Reproduce the bug

_No response_

### Expected behavior

_No response_

### Related issues

_No response_

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.217-alpha-test-10103

### Operating system

_No response_

### Device

_No response_

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #10132

> When installing a keyboard package that is missing a touch-optimized .js keyboard file, a toast appears indicating that there is an error, but it is truncated and disappears too quickly. It should be a message box because it's an error the user should respond to.

This changes the error message from a Toast notification that disappears to an alert dialog that remains until the User closes it.

## User Testing
**Setup**
1. Install the PR build of Keyman for Android on Android device/emulator.
2. On the device/emulator, download a keyboard package (.kmp) file that's missing a touch-optimized .js keyboard file. An example .kmp file is at https://darcywong00.github.io/examples/invalid/sil_ethiopic.kmp

* **TEST_ALERT_DIALOG** - Verifies alert dialog is displayed when keyboard package is missing a touch-optimized .js keyboard file
1. Launch Keyman for Android and dismiss the "Get Started" menu.
2. From the Keyman settings menu, attempt to install the local keyboard package file (saved in Setup above):
  a. Keyman settings --> Install Keyboard or Dictionary --> Install from local file
  b. In the file browser, navigate to where sil_ethiopic.kmp was saved (typically Downloads --> sil_ethiopic.kmp) and click the .kmp file
3. Verify the keyboard package fails to install with an alert dialog
alert - no touch keyboard

4. Click "Close"
5. Verify the alert dialog is dismissed.

### CODE REVIEW

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java [hunk 1]
```diff
@@ -340,7 +341,11 @@ public void onClick(DialogInterface dialog,int id) {
           if (dialog != null) {
             dialog.dismiss();
           }
+          // Setting result to 1 so calling activity will finish too
+          setResult(1);
           cleanup();
+          finish();
+          MainActivity.cleanupPackageInstall();
```
Comment (darcywong00) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java:348]: This matches the cleanup done in `showErrorToast` (ll. 242-245)

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_ALERT_DIALOG (PASSED):** 1. Installed the attached PR build Keyman 17.0.240-alpha-test-10335 on the Android emulator. (Android 12 / API 31). 2. Downloaded sil_ethiopic.kmp file. 3. Got an error message while trying to install the sil_ethiopic.kmp file. 4. Click the Close button. Verified that the alert dialog was dismissed. It seems to be working fine.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.241-alpha](https://keyman.com/downloads/releases/alpha/17.0.241)
