### PR TITLE
fix(android/engine): Handle parsing empty JSONArray as JSONObject

### LINKED ISSUE #7564: bug(android/engine): JSONException: Value [] of type org.json.JSONArray cannot be converted to JSONObject
Hopefully this is low-hanging fruit that can be fixed early in B16S1

Sentry Issue: [KEYMAN-ANDROID-MH](https://sentry.io/organizations/keyman/issues/2955404458/?referrer=github_integration)

```
JSONException: Value [] of type org.json.JSONArray cannot be converted to JSONObject
    at org.json.JSON.typeMismatch(JSON.java:112)
    at org.json.JSONObject.<init>(JSONObject.java:172)
    at org.json.JSONObject.<init>(JSONObject.java:185)
    at com.tavultesoft.kmea.JSONParser.getJSONObjectFromReader(JSONParser.java:46)
    at com.tavultesoft.kmea.JSONParser.getJSONObjectFromFile(JSONParser.java:89)
...
(17 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #7564 
I'm not sure the circumstances, but from the Sentry logs it appears there's times the Cloud catalog queries return `[]` and the Keyman Engine JSON parsing code throws an exception treating it as a JSONObject.

This updates the JSON parser to treat `[]` as an empty JSON Object.

@keymanapp-test-bot skip

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/JSONParser.java [hunk 1]
```diff
@@ -43,6 +45,13 @@ public <T extends Object> T getJSONObjectFromReader(BufferedReader reader, Class
       }
       jsonStr = strBuilder.toString();
       if (type == JSONObject.class) {
+        String EMPTY_JSONARRAY_FORMATSTR = "^\\[\\](\\n)?$";
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/JSONParser.java:48]:
```suggestion
        String EMPTY_JSONARRAY_FORMATSTR = "^\\[\\](\\n)*$";
```

Allow for more than one blank end line?

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.96-beta](https://keyman.com/downloads/releases/beta/16.0.96)

**Comment by mcdurdin** [comment]
> I'm not sure the circumstances, but from the Sentry logs it appears there's times the Cloud catalog queries return `[]` and the Keyman Engine JSON parsing code throws an exception treating it as a JSONObject.

I think I'd like to verify the root cause of this on api.keyman.com as well -- and make sure that there are not circumstances where this is happening, wrongly.
