### PR TITLE
fix(developer): keyboard_info merge mobile wrong

### LINKED ISSUE #2199: [Developer] Keyboard_info merge incorrectly assumes sil_myanmar_mywinext has mobile keyboards
**Describe the bug**

While https://github.com/keymanapp/keyboards/tree/master/release/sil/sil_myanmar_mywinext targets desktop + web, it does not currently target mobile devices. However, the .keyboard_info merge generates the following `platformSupport` object:

```
  "platformSupport": {
    "windows": "full",
    "macos": "full",
    "linux": "full",
    "desktopWeb": "full",
    "mobileWeb": "full",
    "android": "full",
    "ios": "full"
  }
```

**To reproduce**
`./build.sh release/sil/sil_myanmar_mywinext` in the keyboards repo root. The resulting `release/sil/sil_myanmar_mywinext/build/sil_myanmar_mywinext.keyboard_info` has the incorrect `platformSupport`.

**Expected behavior**
The entries for `mobileWeb`, `android`, and `ios` should either be `none` or not present.

---

**Keyman Developer**:
 - Keyman Developer version: 11.0.1356.0

(That version should be updated to 12.0 now as well...)

### PR DESCRIPTION
**Pull request by mcdurdin**
The .keyboard_info merge of `platformSupport` would not always give the
right result, for .js keyboards. We have a certain lack of information
in the .js which makes it a little tricky to determine precisely what
the set of supported platforms are. Thus, if we find a .js within a
.kmp, we'll assume it supports mobile; if we find a .js by itself,
we'll assume it supports web. (Thus, a keyboard that builds a .js
is assumed to always support web -- but not necessarily mobile now).

Some keyboards that have incorrectly added a .js into a package, e.g.
sil_cipher_music, will be marked as supporting mobile even though they
don't. The correct fix here is to remove the .js from the package for
that keyboard.

Fixes #2199.

### CODE REVIEW

**Comment by mcdurdin** [comment]
Once this lands, we'll update the kmcomp.exe in the keyboards repository so that we get the benefit.

# User testing:

Not required.

**Comment by darcywong00** [comment]
> Once this lands, we'll update the kmcomp.exe in the keyboards repository so that we get the benefit.

After 🍒 -picking to stable-12.0, right?

**Comment by mcdurdin** [comment]
> After 🍒 -picking to stable-12.0, right?

I guess ... :)

File: windows/src/developer/TIKE/compile/MergeKeyboardInfo.pas [hunk 1]
```diff
@@ -976,8 +978,6 @@ procedure TMergeKeyboardInfo.AddPlatformSupport;
       AddNewPair('windows', 'full');
       AddNewPair('macos', 'full');
       AddNewPair('linux', 'full');
-      AddNewPair('desktopWeb', 'full');
```
Comment (darcywong00) [inline windows/src/developer/TIKE/compile/MergeKeyboardInfo.pas]: Should the web checks be removed in the block at line 957?
```
      // Validate web/mobile targets. No kmx implies web/mobile targets
      if ((numberKMXFiles = 0) or (p.GetValue('web') <> nil) or
          (p.GetValue('iphone') <> nil) or (p.GetValue('ipad') <> nil) or
          (p.GetValue('androidphone') <> nil) or (p.GetValue('androidtablet') <> nil) or
          (p.GetValue('mobile') <> nil) or (p.GetValue('tablet') <> nil)) and
          (numberJSFiles = 0) then
        raise EInvalidKeyboardInfo.Create(
          'Web/mobile targets should have at least 1 .js keyboard file in the package');
```

**Comment by mcdurdin** [comment]
With this fix, the following keyboards no longer incorrectly report that they are available for mobile:

galaxie_greek_mnemonic
galaxie_hebrew_mnemonic
galaxie_hebrew_positional
sil_bengali_phonetic
sil_devanagari_phonetic
sil_dzongkha
sil_kayah_latn
sil_kayah_mymr
sil_myanmar_my3
sil_myanmar_mywinext
sil_shan

**Comment by LornaSIL** [comment]
@marc So, at one point I thought I was told to always include the .js file in the kps even if it didn't support mobile. It sounds like my understanding was wrong.

If a keyboard just supports Desktop and OSK, the kps should **not** include the .js file. Is that right?

**Comment by mcdurdin** [comment]
> If a keyboard just supports Desktop and OSK, the kps should **not** include the .js file. Is that right?

Correct. I'm sorry if it was me who gave the wrong idea earlier. We have no current plans to support .kmp for web -- it is in theory possible but it actually doesn't make a lot of sense to do so.

File: windows/src/developer/TIKE/compile/MergeKeyboardInfo.pas (hunk 1 above)
Comment (mcdurdin) [reply windows/src/developer/TIKE/compile/MergeKeyboardInfo.pas]: Good pick. Probably!

Comment (mcdurdin) [reply windows/src/developer/TIKE/compile/MergeKeyboardInfo.pas]: This is a little tricky. Currently the test checks for .js outside the package as well as inside. I think I'd like to leave changes to this for a rainy day -- it is working as is without breaking the build.
