### PR TITLE
fix(android): Update KMSample1 layout when changing orientation

### LINKED ISSUE #14677: bug(android): KMSample1 text area obstructed when rotating to landscape
_Originally posted by @Nnyny in https://github.com/keymanapp/keyman/issues/14663#issuecomment-3244135913_
            
Nyny reported the KMSample1 issue in user testing

> 4. Turn to landscape, missing text raea

Sounds like we need to update the KMSample1 project with some of the rotation changes that have been added to the Keyman for Android app

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #14677 

This updates the KMSample1 app with several of the fixes in the Keyman for Android app for handling device orientation changes. (notably part of #8704)

The text area also needs to be resized to accommodate banner/keyboard dimensions which are different between portrait and landscape orientation.

## User Testing
**Setup** - Install the PR build of KMSample1 on an Android device/emulator

* **TEST_ROTATION** - Verifies text area not covered when rotating device
1. Start KMSample1 with the device in portrait orientation
2. Verify text area visible and keyboard and suggestions work
3. Rotate the device to landscape
4. Verify text area visible and keyboard and suggestions work]

### CODE REVIEW

**Comment by Nnyny** [comment]
# Test Results
_Before testing:_ 
_- Install KMSample1 from `Build #19.0.112-alpha-test-14678` on API 34_

* **TEST_ROTATION (PASSED):** notes
1. Launch KMSample 1
2. Messages: `data/user/...` and `error on keyboard...` 
3. Verify the keyboard and dictionary are working fine 
4. Rotate to landscape 
5. Verify the keyboard and dictionary are working fine

File: android/Samples/KMSample1/app/src/main/java/com/keyman/kmsample1/MainActivity.java [hunk 1]
```diff
@@ -131,11 +150,44 @@ public void onKeyboardChanged(String newKeyboard) {
...
+    if (isKeyboardVisible) {
+      bannerHeight = KMManager.getBannerHeight(this);
+      keyboardHeight = KMManager.getKeyboardHeight(this);
+    }
+
+    TypedValue outValue = new TypedValue();
+    getTheme().resolveAttribute(android.R.attr.actionBarSize, outValue, true);
+    int actionBarHeight = getResources().getDimensionPixelSize(outValue.resourceId);
+
+    // *** TO DO: Try to check if status bar is visible, set statusBarHeight to 0 if it is not visible ***
```
Comment (jahorton) [inline android/Samples/KMSample1/app/src/main/java/com/keyman/kmsample1/MainActivity.java:174]: There an issue for this?

Comment (darcywong00) [reply android/Samples/KMSample1/app/src/main/java/com/keyman/kmsample1/MainActivity.java:174]: That TODO has been around since the original version 2.8
https://github.com/keymanapp/keyman/blob/2b3fa63cea49f47201226d74d35ad57f25d2385e/android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java#L288-L292

Tracking as #14682

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 19.0.113-alpha](https://keyman.com/downloads/releases/alpha/19.0.113)
