### PR TITLE
fix(android): restores DOMRect polyfill for old Chrome support

### LINKED ISSUE #11652: bug(android): DOMRect polyfill needed for early ES6 devices
Sentry Issue: [KEYMAN-WEB-JD](https://keyman.sentry.io/issues/5140089969/?referrer=github_integration)

```
Error:  Error from queued closure: DOMRect is not defined

ReferenceError: DOMRect is not defined
    at se.getBoundingClientRect (file:///data/user/0/com.tavultesoft.kmapro/app_data/keymanweb-webview.js:15:6053)
    at itemIdentifier (file:///data/user/0/c...
  at Nr.<anonymous> (@keymanapp/keyman/common/web/gesture-recognizer/src/engine/headless/asyncClosureDispatchQueue.ts:60:7)
  at Generator.next (<anonymous>)
  at Promise (<anonymous>)
  at AsyncClosureDispatchQueue.triggerNextClosure (@keymanapp/keyman/common/web/gesture-recognizer/src/engine/headless/asyncClosureDispatchQueue.ts:39:38)
  at Nr.<anonymous> (@keymanapp/keyman/common/web/gesture-recognizer/src/engine/headless/asyncClosureDispatchQueue.ts:83:10)
...
(23 additional frame(s) were not displayed)
```

Per MDN, `DOMRect` requires Chrome 61, which is later than full ES6 support was added.  Despite this, the ES6 version of the keyboard host-page does not include the `DOMRect` polyfill that the ES5 version does.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #11652.

From our current `master`:

https://github.com/keymanapp/keyman/blob/486807fd7d3fe09390154837648093331f85f921/android/docs/help/about/system-requirements.md?plain=1#L11-L15

`DOMRect` has native support starting in Chrome 61.

@keymanapp-test-bot skip

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java [hunk 1]
```diff
@@ -921,6 +921,9 @@ private static void copyAssets(Context context) {
       copyAsset(context, KMFilename_KmwCss, "", true);
       copyAsset(context, KMFilename_KmwGlobeHintCss, "", true);
       copyAsset(context, KMFilename_Osk_Ttf_Font, "", true);
+      
+      // Needed until our minimum version of Chrome is 61.0+.
+      copyAsset(context, KMFilename_JSPolyfill2, "", true);
```
Comment (darcywong00) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:926]: This corresponds to the KeymanWeb artifact
https://github.com/keymanapp/keyman/blob/486807fd7d3fe09390154837648093331f85f921/android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java#L356

Does the KMEA/build.sh section copy this? (I'm not sure I see it)
https://github.com/keymanapp/keyman/blob/486807fd7d3fe09390154837648093331f85f921/android/KMEA/build.sh#L76-L90

Comment (jahorton) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:926]: It doesn't need to.  It's checked in.

https://github.com/keymanapp/keyman/blob/486807fd7d3fe09390154837648093331f85f921/android/KMEA/app/src/main/assets/other-polyfills.js

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:926]: ah, that's where it was

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
For 19.0, we should raise the minimum version to 95? (That's the last version that runs on Android 5.0)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.177-alpha](https://keyman.com/downloads/releases/alpha/18.0.177)
