### PR TITLE
fix(android): Fix NullPointerException in package installation

### LINKED ISSUE #4789: bug(android): Unhandled NullPointerException in PackageProcessor
Sentry Issue: [KEYMAN-ANDROID-SF](https://sentry.keyman.com/organizations/keyman/issues/4399/?referrer=github_integration)

```
NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference
    at com.tavultesoft.kmapro.PackageActivity.installPackage(PackageActivity.java:249)
    at com.tavultesoft.kmapro.PackageActivity.onLanguagesSelected(PackageActivity.java:213)
    at com.tavultesoft.kmapro.SelectLanguageFragment.onCompleteClicked(SelectLanguageFragment.java:265)
...
(14 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #4789 from the Sentry logs where some users were experiencing NullPointerException during package installation.

This also improves the UX on errors:
* the download dialog can be dismissed (when errors occur)
* change from Error dialog to Toast notifications so they'll be displayed when the package activity finishes.

Will cherry-pick to stable-14.0

### CODE REVIEW

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java [hunk 1]
```diff
@@ -517,7 +517,7 @@ private void downloadKMP(String scheme) {
           if (progressDialog == null) {
             progressDialog = new ProgressDialog(MainActivity.this);
             progressDialog.setMessage(String.format(getString(R.string.downloading_keyboard_package), filename));
-            progressDialog.setCancelable(false);
+            progressDialog.setCancelable(true); // Cancelable in case there's exceptions
```
Comment (jahorton) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java:520]: Question - what happens if the user cancels it while displayed and operating successfully?

Comment (jahorton) [reply android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java:520]: Is there any way to adjust this value after the fact if/when we detect an exception?

Comment (darcywong00) [reply android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java:520]: > Question - what happens if the user cancels it while displayed and operating successfully?

The download dialog is hidden by the package installer until it finishes (readme.htm -> language picker -> welcome.htm)

Comment (jahorton) [reply android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java:520]: Is it also displayed before the package installer launches?  What happens if the user cancels due to poor internet connection, but the initial package's download then succeeds?

Comment (darcywong00) [reply android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java:520]: Yes, the Download dialog is shown before the package installer launches.
I tested what happens if the user cancels the "Download dialog", and the .kmp still downloads.

The .kmp file launches the package installer which can proceed as normally

**Review by jahorton — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.23-alpha](https://keyman.com/downloads/releases/alpha/15.0.23)
