### PR TITLE
fix(android): Standardize language ID in language picker menu

### LINKED ISSUE #6732: bug(android): default language for keyboard installs even after unselected
**Describe the bug**
Detected while addressing https://github.com/keymanapp/keyman/issues/6698. Original notes may be found @ https://github.com/keymanapp/keyman/issues/6698#issuecomment-1149501856.

When using keyboard search to find a package, it is possible for keyboards to be language tagged as part of the search results.  For multi-lingual keyboards, it is possible for the user to prefer a different language selection, though.

When the package installer displays, it will auto-select the default language... but the user is allowed to deselect it.  However... deselection of that language may be ignored by the app/engine!

**To Reproduce**

While this is likely reproducible with other searches, I will describe the exact search & results that led to the detection of this bug.

1. On the device, enable internet connectivity
2. Touch "Install from keyman.com"
3. In the search bar, type `cameroon`.
4. Select `sil_cameroon_qwerty`.
5. The package installer should then display.
6. Note the language that has been automatically selected, then deselect it.
    - Possibly-important note:  the auto-selected language was "Baka".
    - If there is no auto-selected language... we'll need a new repro, obviously.
7. Select a different language.
    - I selected "Pinyin".
8. Click the "Install" button at the bottom right.
9. Dismiss the "welcome" page that displays after installation.
10. Open the Settings menu, then Installed Languages.
11. Note that despite selecting installation for only one language... the keyboard was installed for two!
    - In the original sequence, there was an installation for both "Baka" and "Pinyin".

**Expected behavior**
`sil_cameroon_qwerty` should not have been installed for the "Baka" language, as its language option was explicitly deselected.

---

**Keyman for Android**:

- Device: Galaxy Tab A
- OS: Android 6.0
- Keyman version: 16.0.11-alpha-test-6525.
    - Note that there is no real difference in the Android code here from that found in 15.0.258-beta.
- Target application: Keyman

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #6732 

Currently, if a keyboard package installation involves selecting language(s), the default language tag isn't being standardized (lower-cased). This causes the temporary language list to contain duplicates of the same language (e.g. `bkc-latn` and `bkc-Latn`).

This PR adds utilities to make BCP47.languageEquals() comparisons to the language/keyboard lists.
Regrettably, this is WET because
1. I couldn't figure out how to make the method generic for ArrayList<Keyboard> and ArrayList<String>
2. com.taveultesoft.kmea.util.BCP47 doesn't have access to com.tavultesoft.kmea.data.Keyboard type

## User Testing
Setup - Use any Android device / emulator of Android SDK >= 21

* **TEST_ASSOCIATED_LANGUAGE_WORKS** - Verifies existing functionality of installing keyboard and associated lexical-model
1. On the Android device, install the PR build of Keyman for Android
2. Dismiss the "Get Started" menu
3. In Keyman Settings --> Install Keyboard or Dictionary --> Install from keyman.com --> Search for sil_jarai
4. Install the **sil_jarai** keyboard package
5. Wait a few minutes for the associated dictionary to install (for jra-Latn language)
6. Verify suggestions appear on top of the sil_jarai keyboard

* **TEST_ADD_LANGUAGE** - Verifies existing functionality of adding a language for an already installed keyboard
1. On the Android device, install the PR build of Keyman for Android
2. Dismiss the "Get Started" menu
3. In Keyman Settings --> Install Keyboard or Dictionary --> Add languages to installed keyboard
4. Select EuroLatin (SIL) Keyboard
5. In the language picker, scroll down and select "Crimean Tatar" --> Install.  This adds the language tag `crh-latn`
6. Return to Keyman Settings --> Installed languages
7. Verify "Crimean Tatar" appears as an installed language

* **TEST_DEFAULT_LANGUAGE_UNSELECTED** - Verifies the fix to #6732
1. On the Android device, install the PR build of Keyman for Android
2. Dismiss the "Get Started" menu
3. In Keyman Settings --> Install Keyboard or Dictionary --> Install from keyman.com
4. Search for "`l:id:bkc`" which searches for associated language Baka (`bkc-Latn`). Note, beware if Gboard keyboard auto-corrects the query and changes your search string, which could cause the keyboard search to return 0 results.
5. In the search results, select and install "**sil_cameroon_qwerty**"
6. During the sil_cameroon_qwerty keyboard package installation, scroll down and verify the default language "Baka") is selected.
7. De-select "Baka" and attempt to hit "install"
8. Verify a toast notification "no languages selected" appears and the language picker is still visible
9. With Baka unselected, select a different language (e.g. Pinyin) and finish the keyboard installation
10. When the keyboard package installation finishes, go back to Keyman Settings --> Installed languages
11. Verify Baka does not appear

### CODE REVIEW

**Comment by bharanidharanj** [comment]
* **TEST_ASSOCIATED_LANGUAGE_WORKS (PASSED):** Tested this with the attached PR build in Redmi Note 8 Pro mobile, Version 11.0 and verified that the suggestions appear on top of the sil_jarai keyboard.

   


* **TEST_ADD_LANGUAGE (PASSED):** Tested this with the attached PR build in Redmi Note 8 Pro mobile, Version 11.0 and verified "Crimean Tatar" appears as an installed language. 
   


* **TEST_DEFAULT_LANGUAGE_UNSELECTED (PASSED):** Tested this with the attached PR build in Redmi Note 8 Pro mobile, Version 11.0 and verified Baka does not appear in the Installed languages window.

**Review by srl295 — APPROVED** [review]
FWIW LGTM, noting that you can use `java.util.Locale.forLanguageTag()` and `…toLanguageTag()` for bcp47

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/SelectLanguageFragment.java [hunk 1]
```diff
@@ -190,6 +190,41 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container,
...
+            }
+            index++;
+          }
+
+          if (languageExists && index < keyboardList.size()) {
+            keyboardList.remove(index);
+          } else {
+            k.setLanguage(k.getLanguageID().toLowerCase(), k.getLanguageName());
+            keyboardList.add(k);
+          }
```
Comment (mcdurdin) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/SelectLanguageFragment.java:224]:
```suggestion
          // See if languageID already exists in the keyboardList
          for (Keyboard l: keyboardList) {
            if (BCP47.languageEquals(l.getLanguageID(), k.getLanguageID())) {
              keyboardList.remove(l);
              return;
            }
          }

          k.setLanguage(k.getLanguageID().toLowerCase(), k.getLanguageName());
          keyboardList.add(k);
```

I think this removes the need for the variables which makes it easier to read and maintain.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/BCP47.java [hunk 2]
```diff
@@ -18,4 +20,36 @@ public static boolean languageEquals(String id1, String id2) {
...
+          break;
+        }
+        index++;
+      }
+
+      if (languageExists && index < languageList.size()) {
+        languageList.remove(index);
+      } else {
+        languageList.add(languageID.toLowerCase());
+      }
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/BCP47.java:52]:
```suggestion
      // See if languageID already exists in the languageList
      for (String l: languageList) {
        if (languageEquals(l, languageID)) {
          languageList.remove(l);
          return;
        }
      }

      languageList.add(languageID.toLowerCase());
```

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/BCP47.java [hunk 3]
```diff
@@ -18,4 +20,36 @@ public static boolean languageEquals(String id1, String id2) {
...
+   * If languageID exists in the list, remove it. Otherwise, add languageID to the list.
+   * @param languageList
+   * @param languageID
+   */
+  public static void toggleLanguage(ArrayList<String> languageList, String languageID) {
+    if (languageList != null) {
+      if (languageList.size() == 0) {
+        languageList.add(languageID.toLowerCase());
+        return;
+      }
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/BCP47.java:35]:
```suggestion
```

This is additional logic which is not needed -- the loop will be a no-op in this case and we'll do the add immediately afterwards.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/BCP47.java [hunk 4]
```diff
@@ -18,4 +20,36 @@ public static boolean languageEquals(String id1, String id2) {
...
\ No newline at end of file
+
+  /**
+   * Utility to modify languageList.
+   * If languageID exists in the list, remove it. Otherwise, add languageID to the list.
+   * @param languageList
+   * @param languageID
+   */
+  public static void toggleLanguage(ArrayList<String> languageList, String languageID) {
+    if (languageList != null) {
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/BCP47.java:31]: I'd prefer to see this as an input parameter assertion.


```suggestion
    if (languageList == null) {
      throw new InvalidParameterException("languageList must not be null");
    }
    if (languageID == null) {
      throw new InvalidParameterException("languageID must not be null");
    }
```

And then remove the indent for the rest of the function. Otherwise we would get improper behavior masked and a weird bug that's hard to diagnose.


I could see a case for wrapping this in a helper function:

```
    assertParameterContract(languageList != null);
    assertParameterContract(languageID != null);

    void assertParameterContract(boolean v) {
      if(!v) {
        throw new InvalidParameterException("An input parameter was invalid.");
      }
    }
```

We don't really need a specific message for each assertion because hopefully we can rely on the stack trace to tell us which specific line triggered the exception.

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/SelectLanguageFragment.java [hunk 5]
```diff
@@ -190,6 +190,41 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container,
...
 
+      /**
+       * Utility to modify keyboardList. Based on BCP47.toggleLanguage
+       * If keyboard's languageID exists in the list, remove the keyboard.
+       * Otherwise, add the keyboard to the list.
+       * @param keyboardList
+       * @param k
+       */
+      private void toggleLanguage(ArrayList<Keyboard> keyboardList, Keyboard k) {
+        if (keyboardList != null) {
```
Comment (mcdurdin) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/SelectLanguageFragment.java:201]: See my other comment on `toggleLanguage` on validating input parameters. Furthermore, you are only testing `keyboardList` and not `k` which is certainly insufficient :grin:

**Review by mcdurdin — CHANGES_REQUESTED** [review]
Logic looks good. I'd like to see a little polish on the functions :grin:

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/SelectLanguageFragment.java [hunk 6]
```diff
@@ -190,6 +190,41 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container,
...
+          if (keyboardList.size() == 0) {
+            k.setLanguage(k.getLanguageID().toLowerCase(), k.getLanguageName());
+            keyboardList.add(k);
+            return;
+          }
```
Comment (mcdurdin) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/SelectLanguageFragment.java:206]: This isn't needed -- see same discussion on `toggleLanguage` :)

**Comment by darcywong00** [comment]
I've applied the review comments.

@keymanapp-test-bot retest

**Review by mcdurdin — APPROVED** [review]
LGTM

**Comment by bharanidharanj** [comment]
* **TEST_ASSOCIATED_LANGUAGE_WORKS (PASSED):** Retested this with the attached PR build (Keyman 16.0.58-alpha-test-7239) in my Android Mobile device Version 11.0 and verified the suggestions appear on the top of the sil_jarai keyboard. 

   


* **TEST_ADD_LANGUAGE (PASSED):** Retested this as per the instructions and verified that the  "Crimean Tatar" language appears in the Installed languages menu. 

   


* **TEST_DEFAULT_LANGUAGE_UNSELECTED (PASSED):** Retested this as per the instructions and verified a toast notification "no languages selected" appeas on the screen and langauge picker is still visible. Also, verified 'Baka' language is not appear on the Installed languages menu. Instead of the installed 'Pinyin' language appears. Seems to be working as expected.

**Comment by darcywong00** [comment]
Will 🍒 pick this to 15.0 next week

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.60-alpha](https://keyman.com/downloads/releases/alpha/16.0.60)
