### PR TITLE
fix(android/app): Fix welcome.htm responsiveness

### LINKED ISSUE #4511: bug(android): the welcome page does not go away when tapping on "OK"
**Describe the bug**

In the installation process of a keyboard (either from device or keyman.com), the welcome page does not go away after clicking on "OK" button on the bottom right corner.

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Install a Keyboard or a Dictionary'
3. Choose a keyboard to install either from keyman.com or device
4. Tap on "Install" 
5. Tap on "OK" 
6. See error - nothing happens even after tapping on the "OK" button multiple times

**Expected behavior**

The welcome page should go away after clicking on "OK".

**Screenshots**

Screenshot_1614141277

---

**Keyman for Android:**
 - Device: Pixel 2 API 29
 - OS: Android 10 - emulator
 - Keyman version 14.0.244-beta
 - Target application: Keyman

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #4511 where the welcome.htm page in the webView is unresponsive and can't be closed (either back button or "OK" button)

## PackageActivity
* Remove extra keyboard package install notification (this was triggering the help file to be displayed twice)

## WebView activities
* Use separate process names
* Fix `appendChild()` exception in viewport injection
* Improve the cleanup onDestroy() so that
    * webView is blanked (avoids spurious keyboard downloads
    * webView is then cleaned up

## KMHelpFileActivity
* Allow back button to finish activity

Note:
There's still lag when displaying sil_cameroon_qwerty.htm with Chrome 88 (as listed on the issue).
Since Chrome is also unresponsive with the large page, I can't address that on this PR.

## User Testing
@makarasok

### Setup
1. For each of the Android SDK devices (emulator or physical device), load a clean install of the test build
    * Android P+ ( SDK 28.0+) - these can use the Android call `WebView.setDataDirectorySuffix()` to use separate directories for multiple webviews
    * Android 5.0 (SDK 21.0) - 8.1 (SDK 27.0) - these do not have the call available. @MakaraSok - any 1 device in this range is fine for testing
 

### Run
1. Start the Keyman app
2. Download and install a keyboard package (e.g. sil_madi from the issue)
3. Go through the installation steps
4. Verify the welcome.htm file from keyboard package installation is displayed
5. Verify the welcome.htm file can be dismissed by:
    * Clicking the "OK" button or
    * Hitting the back (triangle) button
6. Exit out of Keyman menus and verify in-app keyboard appears
7. Verify the keyboard help (welcome.htm file) can also be accessed from other paths and dismissed:
    * globe button --> **ⓘ** help icon of the installed keyboard --> Help link
    * Settings --> Installed languages --> navigate to installed keyboard --> Help link

### CODE REVIEW

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java [hunk 1]
```diff
@@ -137,7 +137,7 @@ public void onPageFinished(WebView view, String url) {
         // Inject a meta viewport tag into the head of the file if it doesn't exist
         webView.loadUrl(
           "javascript:(function() {" +
-            "if(!document.querySelectorAll('meta[name=viewport]').length) {"+
+            "if(document.head && !document.querySelectorAll('meta[name=viewport]').length) {"+
```
Comment (darcywong00) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java:140]: If the page was lagging enough, this would throw a console error at l. 144 about `appendChild()` failing

File: android/KMEA/app/src/main/AndroidManifest.xml [hunk 2]
```diff
@@ -47,6 +41,17 @@
             android:label="@string/app_name"
             android:theme="@style/Theme.AppCompat.Light.Dialog" >
         </activity>
+
+        <!-- Put other WebViewActivities in a separate process so the Keyboard WebView doesn't lag.
+        Ref https://stackoverflow.com/questions/40650643/timed-out-waiting-on-iinputcontextcallback-with-custom-keyboard-on-android -->
+        <activity
+            android:name="com.tavultesoft.kmea.KMHelpFileActivity"
+            android:process=":KMHelpFileActivity"
```
Comment (darcywong00) [inline android/KMEA/app/src/main/AndroidManifest.xml:49]: Just moved the KMHelpFileActivity element and added a unique process name

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java [hunk 3]
```diff
@@ -170,6 +194,7 @@ public void onBackPressed() {
       webView.goBack();
     } else {
       super.onBackPressed();
+      finish();
```
Comment (darcywong00) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java:197]: Dismiss help file with the back button

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java (hunk 1 above)
Comment (jahorton) [reply android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java:140]: Hmm.  So there's no easy way to detect this scenario and retry later?

Maybe we could adapt this into a keyboard.html function that sets a timeout or an event against `document.readyState` (see https://developer.mozilla.org/en-US/docs/Web/API/Document/readystatechange_event) to call this when it _is_ possible to handle?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java [hunk 4]
```diff
@@ -42,13 +43,27 @@
...
   @SuppressLint({"SetJavaScriptEnabled", "InflateParams"})
   @Override
   protected void onCreate(Bundle savedInstanceState) {
     super.onCreate(savedInstanceState);
     final Context context = this;
 
+    // Teardown keyboards to free up webView
+    KMManager.onDestroy();
+
+    // Difference processes in the same application cannot directly share WebView-related data
```
Comment (jahorton) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java:57]:
```suggestion
    // Different processes in the same application cannot directly share WebView-related data
```

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java [hunk 5]
```diff
@@ -132,7 +147,7 @@ public void onPageFinished(WebView view, String url) {
         // Inject a meta viewport tag into the head of the file if it doesn't exist
         webView.loadUrl(
           "javascript:(function() {" +
-            "if(!document.querySelectorAll('meta[name=viewport]').length) {"+
+            "if(document.head && !document.querySelectorAll('meta[name=viewport]').length) {"+
```
Comment (jahorton) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java:150]: Hmm... this is basically a duplicate of https://github.com/keymanapp/keyman/pull/4531/files#r584485255's block, right?

I feel that lends more weight to the idea of abstracting it into a common function.

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java:150]: Yeah, I'll refactor them to a helper method

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java (hunk 1 above)
Comment (darcywong00) [reply android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java]: I think I'll defer this to see how you implement #4555

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java [hunk 6]
```diff
@@ -162,6 +163,15 @@ protected void onPause() {
   @Override
   protected void onDestroy() {
     super.onDestroy();
+    // Blank the webView and destroy completely
+    if (webView != null) {
+      webView.loadUrl("about:blank");
+      ((ViewGroup) webView.getParent()).removeView(webView);
+      webView.removeAllViews();
+      webView.clearCache(true);
```
Comment (mcdurdin) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java:171]: This is not necessary: we don't need to clear the cache...

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java [hunk 7]
```diff
@@ -162,6 +163,15 @@ protected void onPause() {
   @Override
   protected void onDestroy() {
     super.onDestroy();
+    // Blank the webView and destroy completely
+    if (webView != null) {
+      webView.loadUrl("about:blank");
+      ((ViewGroup) webView.getParent()).removeView(webView);
```
Comment (mcdurdin) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java:169]: Is there ever a chance that parent could be null?

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java [hunk 8]
```diff
@@ -162,6 +163,15 @@ protected void onPause() {
   @Override
   protected void onDestroy() {
     super.onDestroy();
+    // Blank the webView and destroy completely
```
Comment (mcdurdin) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java:166]: Did you snarf this pattern from somewhere online? If so, good to reference that.

It looks similar to https://stackoverflow.com/a/17458577/1836776

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java [hunk 9]
```diff
@@ -42,13 +44,27 @@
...
+  private static boolean didSetDataDirectorySuffix = false;
 
   @SuppressLint({"SetJavaScriptEnabled", "InflateParams"})
   @Override
   protected void onCreate(Bundle savedInstanceState) {
     super.onCreate(savedInstanceState);
     final Context context = this;
 
+    // Teardown keyboards to free up webView
+    KMManager.onDestroy();
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java:56]: I think we should probably rename the function and call it from `onDestroy` -- `onDestroy` should be reserved for the event handler.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java [hunk 10]
```diff
@@ -162,6 +169,15 @@ protected void onPause() {
...
     super.onDestroy();
+    // Blank the webView and destroy completely
+    if (webView != null) {
+      webView.loadUrl("about:blank");
+      ((ViewGroup) webView.getParent()).removeView(webView);
+      webView.removeAllViews();
+      webView.clearCache(true);
+      webView.destroy();
+      webView = null;
+    }
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java:180]: Given this code is repeated, is it possible to put it into a helper class?

**Review by mcdurdin — CHANGES_REQUESTED** [review]

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java (hunk 9 above)
Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java:56]: After some thought, I'm even more concerned about this pattern. Should we be setting `KMManager` to `null` after this? What state is it in after calling `onDestroy`? Do we have any API contract around this?

**Comment by darcywong00** [comment]
Back to wip to address issues. And it's still lagging on my 8.1 device 😞

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java (hunk 7 above)
Comment (darcywong00) [reply android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java]: Added a null check

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java (hunk 8 above)
Comment (darcywong00) [reply android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KMPBrowserActivity.java]: Documented in WebViewUtil.java

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java (hunk 9 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMHelpFileActivity.java]: Turns out this wouldn't help with rendering sil_cameroon_qwerty. So I've opted not to keep this change

**Comment by MakaraSok** [comment]
Tested. Confirm that the welcome page goes away once the OK button is clicked on.

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java (hunk 1 above)
Comment (mcdurdin) [reply android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java]: That sounds fine to me; @darcywong00 can you open an issue on that? I think we should do the same pattern for iOS and Android.

**Review by mcdurdin — APPROVED** [review]

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java (hunk 1 above)
Comment (darcywong00) [reply android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/WebViewFragment.java]: > can you open an issue on that?

Android will implement in #4556. I'll make a copy for iOS

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.253-beta](https://keyman.com/downloads/releases/beta/14.0.253)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.19-alpha](https://keyman.com/downloads/releases/alpha/15.0.19)

**Comment by MakaraSok** [comment]
Tested with Keyman 14.0.255-beta.

> * Android P+ ( SDK 28.0+) - these can use the Android call `WebView.setDataDirectorySuffix()` to use separate directories for multiple webviews

Confirm that things work as expected. The help page can be closed and visited from both Settings and the globe key.

> * Android 5.0 (SDK 21.0) - 8.1 (SDK 27.0) - these do not have the call available. @MakaraSok - any 1 device in this range is fine for testing

Confirm that things work as expected, but `.kmp` seems to be unrecognizable by the OS. The screenshot below shows two versions of the `sil_madi.kmp` imported into the device by means of (1) downloading from Google Drive - first on the list and (2) loading to the device directly from the Device File Explorer of Android Studio - second file on the list.
image

**Comment by MakaraSok** [comment]
Thanks to @darcywong00 for the walkthrough.

The file management is done differently on 5.0.2. To see the files loaded to the emulator via Android Studio, go to install from device and then click on the three little dots on the top right to see "Show SD card".
image

Then go to the three horizontal lines on the top left to click on SD card.
image

Now navigate to the download folder on the SD card to see the loaded .kmp files:
image

Now, with access to the local file, it's confirmed that the installation get through as expected and the help file is accessible without any apparent issue.
