### PR TITLE
fix(web): fixes lack of respect for underlying-key display settings

### LINKED ISSUE #3950: bug(web): underlying key display flags not being respected
**Describe the bug**
Web emulator shows a keyboard layout without underlying characters, while the Android emulator shows all underlying characters.

image

**To Reproduce**
This behavior was encountered when working on this project: 
[bj_naskapi_classic.zip](https://github.com/keymanapp/keyman/files/5594687/bj_naskapi_classic.zip)

**Expected behavior**
The touch layouts should be shown consistently on both web and Android emulators.

---

**Android emulator:**
 - Device: Pixel 2
 - OS: Android 10
 - Keyman version 14.0.188
 - Target application: [Keyman for Android]

**KeymanWeb:**
 - OS: Windows 10 Pro 1909
 - Browser: Chrome 87.0.4280.66 (Official Build) (64-bit)
 - KeymanWeb Version: [?]
 - URL: N/A
 
**Keyman Developer:**
 - OS: Windows 10 Pro 1909
 - Keyman Developer version: 13.0.115
 
**Additional context**
The Desktop OSK in .KMN has `Display underlying layout characters` checked.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #3950.

Yeah, I missed the mark on my understanding of `KDU` and `displayUnderlying` while doing the Web-core refactor.  This should patch it all up.

Not noted on #3950 - `KDU` was completely ignored when displaying desktop layouts; it was being overridden to `true` for them.

### CODE REVIEW

File: common/core/web/keyboard-processor/src/keyboards/defaultLayouts.ts [hunk 1]
```diff
@@ -176,6 +176,11 @@ namespace com.keyman.keyboards {
       if(formFactor == 'desktop') {
         invalidIdList = Layouts.generateLayerIds(chiral);
 
+        // Only display these by default for the desktop layout.
+        // Mobile form-factors must have a pre-defined layout in order 
+        // to display underlying keys.
+        layout["displayUnderlying"] = !!keyboard.scriptObject['KDU'];
```
Comment (jahorton) [inline common/core/web/keyboard-processor/src/keyboards/defaultLayouts.ts:182]: This is a bit of an assumption on my part, which will be affected by whatever the right answer to [this comment](https://github.com/keymanapp/keyman/issues/3950#issuecomment-789358087) from the base issue is:

> Hmm... that does leave one last question. Suppose the following scenario:
> 
> A keyboard that:
> 
>     * does not specify a touch layout, relying upon KMW defaults
> 
>     * does specify the `KDU` property
> 
>     * is being used on a touch device.
> 
> 
> Since the resulting layout is "desktop-based", and there is no layout pre-defined for that form factor, should this scenario utilize the flag or not?

This particular code line is specifically for that exact scenario.

Comment (mcdurdin) [reply common/core/web/keyboard-processor/src/keyboards/defaultLayouts.ts:182]: Yes. In a scenario where there is no touch layout defined, use the `KDU` property from the desktop layout.

**Review by mcdurdin — APPROVED** [review]
LGTM, although I can't see where the KDU flag is copied to the touch layout when it is converted from the KVKL data?

**Comment by jahorton** [comment]
> LGTM, although I can't see where the KDU flag is copied to the touch layout when it is converted from the KVKL data?

I chose the opposite direction; it currently won't affect touch layouts, which is why I made sure to highlight that as an assumption.  I'll go ahead and make the correction now.

**Comment by jahorton** [comment]
> > LGTM, although I can't see where the KDU flag is copied to the touch layout when it is converted from the KVKL data?
> 
> I chose the opposite direction; it currently won't affect touch layouts, which is why I made sure to highlight that as an assumption. I'll go ahead and make the correction now; I knew it was only a "best guess."

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.252-beta](https://keyman.com/downloads/releases/beta/14.0.252)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.19-alpha](https://keyman.com/downloads/releases/alpha/15.0.19)
