### PR TITLE
fix(core): Fix nuances when updating context 🌱

### LINKED ISSUE #10100: bug(core): `km_core_state_context_set_if_needed` needs more nuance for when to update cache 🌱
Now I am having worries about the algorithm here. There are multiple scenarios, and just want to make sure that I am covering them all.

Ignoring markers..., these are the scenarios I can see:

1. cached context identical to app context
2. cached context same length as app context but content is different
3. cached context is shorter than app context, but content is same as far as it goes
4. cached context is shorter than app context, but content is different
5. cached context is longer than app context, but content is same as far as it goes
6. cached context is longer than app context, but content is different.

I think those are the only 6 scenarios. What do we want to do for each one?

1. unchanged
2. changed, set cache to app context
3. lengthen to app context, but keep markers, consider unchanged?
4. changed, set cache to app context
5. shorten to app context, but keep markers, consider unchanged? or changed + set to app context?
6. changed, set cache to app context

We have to consider the rolling buffer that we'll have as we add new content, and that will impact whether or not the app context is longer than cache (remembering that the cached context may have markers which will shorten the overall non-marker content of it).

So number 3 and number 5 ~~6~~ need careful consideration.

Relates to #10098.

### PR DESCRIPTION
**Pull request by ermshiperete**
Fixes #10100.

# User Testing

## Preparations

- The tests should be run on Linux, Windows and Mac.
- Install build artifacts of this PR. [(Instructions for Linux)](https://github.com/keymanapp/keyman/wiki/How-to-test-artifacts-from-pull-requests-for-Keyman-for-Linux)
- on Linux install the .deb version of Firefox and/or Chrome/Chromium and remove the snap version
- Reboot

## Tests

- GROUP_WIN: Windows
- GROUP_MAC: macOS
- GROUP_LINUX: Ubuntu 22.04 with X11

Open https://keyman.com/keyboards in a browser and run the following tests:

   * TEST_KHMER_ANGKOR: Khmer Angkor
      * Ensure the key combination <kbd>AltGr</kbd> <kbd>B</kbd> produces `ឞ`. Note that on macOS, the function key to use is right `option`.
      * Type the following (US) keys in sequence: <kbd>s</kbd> <kbd>u</kbd> <kbd>j</kbd> <kbd>r</kbd> <kbd>k</kbd>. You should see `ស្រុក`.
   * TEST_SIL_EURO_LATIN: SIL Euro Latin
      * Type <kbd>%</kbd> <kbd>a</kbd>. Ensure the output is `ǎ`
   * TEST_GALAXIE_HEBREW: Galaxie Hebrew or another good SIL RTL keyboard
      * Type <kbd>b</kbd> <kbd>\\</kbd> <kbd>=</kbd> <kbd>r</kbd> <kbd>@</kbd> <kbd>a</kbd> <kbd>v</kbd> <kbd>!</kbd> <kbd>y</kbd> <kbd>t</kbd> (note the third-last key is the exclamation mark!) to output `בְּרֵאשִׁית`. FAILED if the output is different.
   * TEST_SIL_IPA: sil_ipa
      * Ensure the key sequence <kbd>n</kbd> <kbd>></kbd> produces `ŋ`.
   * TEST_CJK_IMX: Korean KORDA Jamo (SIL)
      * Type <kbd>h</kbd> <kbd>a</kbd> <kbd>n</kbd> `<space>` <kbd>g</kbd> <kbd>e</kbd> <kbd>u</kbd> <kbd>l</kbd> `<space>`. Verify that the result is `한글`.

### CODE REVIEW

File: core/src/km_core_state_context_set_if_needed.cpp [hunk 1]
```diff
@@ -26,115 +26,226 @@
...
+  CONTEXT_SHORTER = 2,
+  // internal context is longer, but content is same as far as it goes
+  CONTEXT_LONGER = 3,
+};
+
+typedef struct {
+  uint8_t type;
+  // the number of characters/context items (from beginning of context)
+  // that are missing from the new/internal context.
+  uint8_t end_difference;
```
Comment (mcdurdin) [inline core/src/km_core_state_context_set_if_needed.cpp:44]: Can we make `end_difference` a larger type? I don't think we need to limit ourselves here for the future.

File: core/src/km_core_state_context_set_if_needed.cpp [hunk 2]
```diff
@@ -26,115 +26,226 @@
...
+  // new and internal contexts differ
+  CONTEXT_DIFFERENT = 1,
+  // internal context is shorter, but content is same as far as it goes
+  CONTEXT_SHORTER = 2,
+  // internal context is longer, but content is same as far as it goes
+  CONTEXT_LONGER = 3,
+};
+
+typedef struct {
+  uint8_t type;
```
Comment (mcdurdin) [inline core/src/km_core_state_context_set_if_needed.cpp:41]: why not use `enum context_changed_type type;`?

File: core/src/km_core_state_context_set_if_needed.cpp [hunk 3]
```diff
@@ -26,115 +26,226 @@
...
+) {
+  if (context_changed.type == CONTEXT_DIFFERENT) {
+    if (set_context_from_string(context, new_context) != KM_CORE_STATUS_OK) {
+      return false;
+    }
+  } else if (context_changed.type == CONTEXT_SHORTER) {
+    km_core_context_item *new_context_items;
+    if (context_items_from_utf16(new_context, &new_context_items) != KM_CORE_STATUS_OK ||
+        context_prepend(context, new_context_items, context_changed.end_difference) != KM_CORE_STATUS_OK) {
+      km_core_context_items_dispose(new_context_items);
```
Comment (mcdurdin) [inline core/src/km_core_state_context_set_if_needed.cpp:136]: This could do a dispose on an uninitialized new_context_items.

File: core/src/km_core_state_context_set_if_needed.cpp [hunk 4]
```diff
@@ -26,115 +26,226 @@
...
  */
-bool is_context_valid(km_core_cp const * new_app_context, km_core_cp const * app_context) {
-  if (new_app_context == nullptr || app_context == nullptr || *app_context == '\0') {
+context_change_type
+is_context_unchanged(
+  km_core_cp const *new_context_string,
+  km_core_context *context
+) {
+  context_change_type change_type({CONTEXT_DIFFERENT, 0});
+  if (new_context_string == nullptr || context == nullptr) {
```
Comment (mcdurdin) [inline core/src/km_core_state_context_set_if_needed.cpp:188]: Suggest we add assert(new_context_string != nullptr) and assert(context != nullptr) for debug builds

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_KHMER_ANGKOR (FAILED):** Tested with the attached PR build (Keyman 17.0.245-alpha-local (package version 17.0.245-1~PR-10439-2102.1+mantic1) in Ubuntu 23.10 Mantic Minotaur Linux OS (VM) and here is my observation: 1. Installed Khmer Angkor keyboard. 2. Opened Slate.js text editor page. 3. Typed "sujrk" showed the wrong output in Chrome browser. 

..working in Firefox browser and not working in Chrome browser

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_GALAXIE_HEBREW (PASSED):** Tested with the attached PR build (Keyman 17.0.245-alpha-local (package version 17.0.245-1~PR-10439-2102.1+mantic1) in Ubuntu 23.10 Mantic Minotaur Linux OS (VM) and here is my observation : 1. Installed Galaxy_Hebrew keyboard. 2. Opened Slate.js text editor page. 3. Typed "b\=r@av!yt" showed the correct output in both Mozilla Firefox and Chrome browsers.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_SIL_IPA (FAILED):** Tested with the attached PR build (Keyman 17.0.245-alpha-local (package version 17.0.245-1~PR-10439-2102.1+mantic1) in Ubuntu 23.10 Mantic Minotaur Linux OS (VM) and here is my observation: 1. Installed sil_ipa keyboard. 2. Opened Slate.js text editor page. 3. Typed "n>" showed the wrong output in both Mozilla Firefox and Chrome browsers.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_INTERACTION_WITH_TEXT_FORMATTING (OPEN):** Tested with the attached PR build (Keyman 17.0.245-alpha-local (package version 17.0.245-1~PR-10439-2102.1+mantic1) in Ubuntu 23.10 Mantic Minotaur Linux OS (VM) and here is my observation: 1. Installed khmer_angkor keyboard. 2. Opened Slate.js text editor page. 3. Pressed Ctrl+B to make the letter bold. 4. Typed "sujrk" or "b" showed the texts that appeared in bold letters in both Mozilla Firefox and Chrome browsers.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_CJK_IMX (PASSED):** Tested with the attached PR build (Keyman 17.0.245-alpha-local (package version 17.0.245-1~PR-10439-2102.1+mantic1) in Ubuntu 23.10 Mantic Minotaur Linux OS (VM) and here is my observation : 1. Installed Korean_Korda Jamo (SIL) keyboard. 2. Opened Slate js text editor page. 3. Typed "han<space>geul<space>" showed wrong output in both Mozilla Firefox and Chrome browsers.

**Comment by ermshiperete** [comment]
@bharanidharanj It looks like you're using the snap version of Firefox and Chrome/Chromium. Please remove them and install the .deb versions. You can run these commands in a terminal:

```bash
sudo snap remove firefox
sudo add-apt-repository ppa:mozillateam/ppa
echo '
Package: *
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1001
' | sudo tee /etc/apt/preferences.d/mozilla-firefox
echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";'  | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox
sudo apt install firefox
```

and

```bash
sudo snap remove chromium-browser
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb
```

Also, make sure you're testing with X11 (on Wayland there's a different bug #10476 that affects testing of this PR).

@keymanapp-test-bot retest

**Comment by bharanidharanj** [comment]
> @bharanidharanj It looks like you're using the snap version of Firefox and Chrome/Chromium. Please remove them and install the .deb versions. You can run these commands in a terminal:
> 
> ```shell
> sudo snap remove firefox
> sudo add-apt-repository ppa:mozillateam/ppa
> echo '
> Package: *
> Pin: release o=LP-PPA-mozillateam
> Pin-Priority: 1001
> ' | sudo tee /etc/apt/preferences.d/mozilla-firefox
> echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";'  | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox
> sudo apt install firefox
> ```
> 
> and
> 
> ```shell
> sudo snap remove chromium-browser
> wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
> sudo apt install ./google-chrome-stable_current_amd64.deb
> ```
> 
> Also, make sure you're testing with X11 (on Wayland there's a different bug #10476 that affects testing of this PR).
> 
> @keymanapp-test-bot retest

@ermshiperete Sure. Thanks for your suggestion.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_WIN: Windows

* **TEST_KHMER_ANGKOR (FAILED):** Tested with the attached PR build (Keyman 17.0.245-alpha-test-10439) on Window 10 OS and here is my observation: 1. Installed Khmer_Angkor keyboard. 2. Opened Slate Examples page. 3.  Typed 'sujrk' and it is showing the wrong output. 

   


* **TEST_SIL_EURO_LATIN (FAILED):** It is showing the wrong output. 

   

* **TEST_GALAXIE_HEBREW (FAILED):** It is showing the wrong output.

   


* **TEST_SIL_IPA (FAILED):** It is showing the wrong output. 

   

* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** It is showing the correct output. 

   

* **TEST_CJK_IMX (FAILED):** It is showing the wrong output.

**Comment by bharanidharanj** [comment]
### GROUP_LINUX: Linux

* **TEST_KHMER_ANGKOR (FAILED):** Tested with the attached PR build (Keyman 17.0.245-alpha-local (package version 17.0.245-1~PR-10439-2114.1+mantic1) on Ubuntu 23.10 Mantic Linux OS (VM) and here is my observation: 1. Installed Mozilla Firefox and Chromium browsers (.deb versions) as per your suggestions. 2. Installed the Keyboard as mentioned in the PR. 3. Verified it in both Mozilla Firefox and Chrome browsers showing the wrong output in Chrome browser. 

   

* **TEST_SIL_EURO_LATIN (FAILED):** Tested with the attached PR build (Keyman 17.0.245-alpha-local (package version 17.0.245-1~PR-10439-2114.1+mantic1) on Ubuntu 23.10 Mantic Linux OS (VM) and here is my observation: 1. Installed Mozilla Firefox and Chromium browsers (.deb versions) as per your suggestions. 2. Installed the Keyboard as mentioned in the PR. 3. Verified it in both Mozilla Firefox and Chrome browsers showing the wrong output in Chrome browser. 

   

* **TEST_GALAXIE_HEBREW (PASSED):** It is showing the correct output.

   

* **TEST_SIL_IPA (FAILED):** Tested with the attached PR build (Keyman 17.0.245-alpha-local (package version 17.0.245-1~PR-10439-2114.1+mantic1) on Ubuntu 23.10 Mantic Linux OS (VM) and here is my observation: 1. Installed Mozilla Firefox and Chromium browsers (.deb versions) as per your suggestions. 2. Installed the Keyboard as mentioned in the PR. 3. Verified it in both Mozilla Firefox and Chrome browsers showing the wrong output in Chrome browser. 

   

* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** It is showing the correct output. 

   

* **TEST_CJK_IMX (FAILED):** Tested with the attached PR build (Keyman 17.0.245-alpha-local (package version 17.0.245-1~PR-10439-2114.1+mantic1) on Ubuntu 23.10 Mantic Linux OS (VM) and here is my observation: 1. Installed Mozilla Firefox and Chromium browsers (.deb versions) as per your suggestions. 2. Installed the Keyboard as mentioned in the PR. 3. Verified it in both Mozilla Firefox and Chrome browsers showing the wrong output in Chrome browser.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_MAC: macOS

* **TEST_KHMER_ANGKOR (FAILED):** Tested with the attached PR build (Keyman 17.0.245-alpha-test-10439 on macOS Sonoma and here is my observation: 1. Installed the above-mentioned keyboards in the system. 2. Opened Chrome browser. 3. Opened Slatejs test page. 4. Switched to Khmer_Angkor keyboard. 5. Verified it is showing the wrong output. 

   

* **TEST_SIL_EURO_LATIN (PASSED):** Tested with the attached PR build (Keyman 17.0.245-alpha-test-10439 on macOS Sonoma and here is my observation: 1. Installed the above mentioned keyboards in the system. 2. Opened Chrome browser. 3. Opened Slatejs test page. 4. Switched to sil_eurolatin keyboard. 5. Verified it is showing the correct output. 

   


* **TEST_GALAXIE_HEBREW (PASSED):** Tested with the attached PR build (Keyman 17.0.245-alpha-test-10439 on macOS Sonoma and here is my observation: 1. Installed the above mentioned keyboards in the system. 2. Opened Chrome browser. 3. Opened Slatejs test page. 4. Switched to Galaxie_Hebrew keyboard. 5. Verified it is showing the correct output. 

   

* **TEST_SIL_IPA (PASSED):** Tested with the attached PR build (Keyman 17.0.245-alpha-test-10439 on macOS Sonoma and here is my observation: 1. Installed the above mentioned keyboards in the system. 2. Opened Chrome browser. 3. Opened Slatejs test page. 4. Switched to sil_ipa keyboard. 5. Verified it is showing the correct output. 

   

* **TEST_INTERACTION_WITH_TEXT_FORMATTING (PASSED):** Tested with the attached PR build (Keyman 17.0.245-alpha-test-10439 on macOS Sonoma and here is my observation: 1. Installed the above mentioned keyboards in the system. 2. Opened Chrome browser. 3. Opened Slatejs test page. 4.  Verified it is showing the bold letters. 


* **TEST_CJK_IMX (FAILED):** Tested with the attached PR build (Keyman 17.0.245-alpha-test-10439 on macOS Sonoma and here is my observation: 1. Installed the above mentioned keyboards in the system. 2. Opened Chrome browser. 3. Opened Slatejs test page. 4. Switched to Korean KORDA keyboard. 5. Verified it is showing the wrong output.

**Comment by ermshiperete** [comment]
@bharanidharanj Sorry, should have told you not to test with slate.js since that has [bug](https://github.com/keymanapp/keyman/issues/7938#issuecomment-1361452798). Could you please retest using the input field in keyman.com/keyboards instead? Thanks!

@keymanapp-test-bot retest GROUP_WIN TEST_KHMER_ANGKOR TEST_SIL_EURO_LATIN TEST_GALAXIE_HEBREW TEST_SIL_IPA TEST_CJK_IMX GROUP_MAC TEST_KHMER_ANGKOR TEST_CJK_IMX GROUP_LINUX TEST_KHMER_ANGKOR TEST_SIL_EURO_LATIN TEST_SIL_IPA TEST_CJK_IMX

**Comment by bharanidharanj** [comment]
> @bharanidharanj Sorry, should have told you not to test with slate.js since that has [bug](https://github.com/keymanapp/keyman/issues/7938#issuecomment-1361452798). Could you please retest using the input field in keyman.com/keyboards instead? Thanks!
> 
> @keymanapp-test-bot retest GROUP_WIN TEST_KHMER_ANGKOR TEST_SIL_EURO_LATIN TEST_GALAXIE_HEBREW TEST_SIL_IPA TEST_CJK_IMX GROUP_MAC TEST_KHMER_ANGKOR TEST_CJK_IMX GROUP_LINUX TEST_KHMER_ANGKOR TEST_SIL_EURO_LATIN TEST_SIL_IPA TEST_CJK_IMX

@ermshiperete Sure, I will do it.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_WIN: Windows

* **TEST_KHMER_ANGKOR (PASSED):** Retested with the attached PR build (Keyman 17.0.245-alpha-test-10439 on Windows 10 OS and here is my observation: 1. Installed the above mentioned keyboards in the system. 2. Opened Mozilla Firefox and Chrome browsers. 3. Opened  https://keyman.com/keyboards test page. 4. Switched to khmer_angkor keyboard. 5. Verified it is showing the correct output. 

   

* **TEST_SIL_EURO_LATIN (PASSED):** Retested with the attached PR build (Keyman 17.0.245-alpha-test-10439 on Windows 10 OS and here is my observation: 1. Installed the above mentioned keyboards in the system. 2. Opened Mozilla Firefox and Chrome browsers. 3. Opened  https://keyman.com/keyboards test page. 4. Switched to sil_eurolatin keyboard. 5. Verified it is showing the correct output. 

   

* **TEST_GALAXIE_HEBREW (PASSED):** Retested with the attached PR build (Keyman 17.0.245-alpha-test-10439 on Windows 10 OS and here is my observation: 1. Installed the above mentioned keyboards in the system. 2. Opened Mozilla Firefox and Chrome browsers. 3. Opened  https://keyman.com/keyboards test page. 4. Switched to glaxie_hebrew keyboard. 5. Verified it is showing the correct output. 

  

* **TEST_SIL_IPA (PASSED):** Retested with the attached PR build (Keyman 17.0.245-alpha-test-10439 on Windows 10 OS and here is my observation: 1. Installed the above mentioned keyboards in the system. 2. Opened Mozilla Firefox and Chrome browsers. 3. Opened  https://keyman.com/keyboards test page. 4. Switched to sil_ipa keyboard. 5. Verified it is showing the correct output. 

   

* **TEST_CJK_IMX (PASSED):** Retested with the attached PR build (Keyman 17.0.245-alpha-test-10439 on Windows 10 OS and here is my observation: 1. Installed the above mentioned keyboards in the system. 2. Opened Mozilla Firefox and Chrome browsers. 3. Opened  https://keyman.com/keyboards test page. 4. Switched to Korean_KORDA keyboard. 5. Verified it is showing the correct output.

**Comment by bharanidharanj** [comment]
### GROUP_LINUX: Ubuntu 22.04 with X11

* **TEST_KHMER_ANGKOR (PASSED):** Retested with the attached PR build (Keyman 17.0.245-alpha-local (package version 17.0.245-1~PR-10439-2114.1+jammy1) in Ubuntu 22.04 Jammy Jelly Fish Linux OS (VM) and here is my observation: 1. Installed khmer_angkor keyboard. 2. Opened keyman.com/keyboards page. 3. Switched to Khmer_Angkor keyboard. 5. Verified it is showing the correct output. 

* **TEST_SIL_EURO_LATIN (PASSED):** Retested with the attached PR build (Keyman 17.0.245-alpha-local (package version 17.0.245-1~PR-10439-2114.1+jammy1) in Ubuntu 22.04 Jammy Jelly Fish Linux OS (VM) and here is my observation: 1. Installed khmer_angkor keyboard. 2. Opened keyman.com/keyboards page. 3. Switched to sil_eurolatin keyboard. 5. Verified it is showing the correct output. 

* **TEST_SIL_IPA (PASSED):** Retested with the attached PR build (Keyman 17.0.245-alpha-local (package version 17.0.245-1~PR-10439-2114.1+jammy1) in Ubuntu 22.04 Jammy Jelly Fish Linux OS (VM) and here is my observation: 1. Installed khmer_angkor keyboard. 2. Opened keyman.com/keyboards page. 3. Switched to sil_ipa keyboard. 5. Verified it is showing the correct output. 

* **TEST_CJK_IMX (PASSED):** Retested with the attached PR build (Keyman 17.0.245-alpha-local (package version 17.0.245-1~PR-10439-2114.1+jammy1) in Ubuntu 22.04 Jammy Jelly Fish Linux OS (VM) and here is my observation: 1. Installed khmer_angkor keyboard. 2. Opened keyman.com/keyboards page. 3. Switched to Korean_KORDA keyboard. 5. Verified it is showing the correct output.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_MAC: macOS

* **TEST_KHMER_ANGKOR (PASSED):** Retested with the attached PR build (Keyman 17.0.245-alpha-test-10439) in macOS Sonoma and here is my observation: 1. Installed khmer_angkor keyboard. 2. Opened keyman.com/keyboards page. 3. Switched to Khmer_Angkor keyboard. 5. Verified it is showing the correct output.

* **TEST_CJK_IMX (PASSED):** Retested with the attached PR build (Keyman 17.0.245-alpha-test-10439) in macOS Sonoma and here is my observation: 1. Installed khmer_angkor keyboard. 2. Opened keyman.com/keyboards page. 3. Switched to Korean_KORDA keyboard. 5. Verified it is showing the correct output.
