### PR TITLE
[Web] Removes default key cap text behavior

### LINKED ISSUE #1460: [Web] OSK displays keys that it shouldn't
Moving from https://github.com/sillsdev/keyman-keyman.com/issues/216

Keyman OSK files do not have a keystroke assigned and don't show anything on Keycap
capture

When I go to the KeymanWeb page (https://keymanweb.com/?_ga=2.140668978.1275583547.1542643542-227799419.1521670190#ug-Arab,Keyboard_basic_kbdughr):
I see this:
image
where QWERTY... is displayed even though those keys do not work (intentionally).
Is this a bug in the keyboard or in the KeymanWeb site? It affects quite a few keyboards.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #1460.

As determined in conversation in other channels, we've decided to use the keyboard `KVER` property to do a version check, allowing us to preserve the original behavior for legacy keyboards while allowing those compiled with Developer 12.0+ to no longer auto-provide default keycaps.

### CODE REVIEW

File: web/source/osk/defaultLayouts.ts [hunk 1]
```diff
@@ -250,7 +252,7 @@ namespace com.keyman.osk {
 
               // Fall back to US English keycap text as default for the base two layers if not otherwise defined.
```
Comment (darcywong00) [inline web/source/osk/defaultLayouts.ts]: Maybe also update the comment about checking versions earlier than X

File: web/source/osk/defaultLayouts.ts [hunk 2]
```diff
@@ -114,7 +116,7 @@ namespace com.keyman.osk {
     * @param   {string}  formFactor
```
Comment (darcywong00) [inline web/source/osk/defaultLayouts.ts]:
```
* @param   {utils.Version} kbdDevVersion
```

File: web/unit_tests/cases/versions.js [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+
+  it('Should properly compare two versions.', function() {
+    var v9_0_1 = new com.keyman.utils.Version("9.0.1");
+    var v9_1_0 = new com.keyman.utils.Version("9.1.0");
+    var v10_0_0 = new com.keyman.utils.Version("10.0.0");
+
+    assert.isTrue(v9_0_1.precedes(v9_1_0));
+    assert.isTrue(v9_1_0.precedes(v10_0_0));
+    assert.isTrue(v9_0_1.precedes(v10_0_0));
+  });
```
Comment (darcywong00) [inline web/unit_tests/cases/versions.js]: Maybe add a test case for
```
assert.isTrue(v12_0.precedes(v12_0_0));
```

File: web/source/osk/visualKeyboard.ts [hunk 4]
```diff
@@ -591,7 +592,9 @@ namespace com.keyman.osk {
 
       // Build a layout using the default for the device
       if(typeof layout != 'object' || layout == null) {
-        layout=Layouts.buildDefaultLayout(PVK,kbdBitmask, formFactor);
+        // Using 9.0.0 as a fallback Developer version for keyboards.
+        let kbdDevVersion = utils.Version.parseWithDefault(activeKeyboard['KVER'], "9.0.0");
```
Comment (darcywong00) [inline web/source/osk/visualKeyboard.ts]: Should we define "9.0.0" as a fallback constant in version.ts since you also use it in line 2100?

Comment (mcdurdin) [reply web/source/osk/visualKeyboard.ts]: The default version should be moved to `utils.Version` I think, given it is likely to arise again.

File: web/source/utils/version.ts [hunk 5]
```diff
@@ -0,0 +1,77 @@
+namespace com.keyman.utils {
+  // Dotted-decimal version
+  export class Version {
+    public static readonly NO_DEFAULT_KEYCAPS = new Version("12.0");
+
+    private readonly components: number[]
+
+    constructor(text: String) {
```
Comment (mcdurdin) [inline web/source/utils/version.ts]: You could have an alternate which is passed an array of integers to avoid having to parse it, e.g. `Version([12,0])` when passed as a constant from code.

File: web/source/utils/version.ts [hunk 6]
```diff
@@ -0,0 +1,77 @@
...
+          }
+        }
+
+        return true;
+      }
+    }
+
+    precedes(other: Version): boolean {
+      // If the version info depth differs, we need a flag to indicate whether or not 'this' instance wins ties.
+      // 12.0 is considered to precede 12.0.0.
```
Comment (mcdurdin) [inline web/source/utils/version.ts]: I think `12.0.0` = `12.0`. `12.0.1` would succeed `12.0.0`. But missing should be the same as zero.

Comment (jahorton) [reply web/source/utils/version.ts]: 👍

I wasn't sure exactly how we wanted this handled, but figured this would easily be enough to spark the discussion.  Can do.

File: web/source/osk/visualKeyboard.ts (hunk 4 above)
Comment (jahorton) [reply web/source/osk/visualKeyboard.ts]: Along this line - any chance you know offhand when `KVER` was introduced?  I have seen actual `9.0.xxx` values, but nothing earlier.  Not that flawless accuracy on the default actually matters, though.

Comment (mcdurdin) [reply web/source/osk/visualKeyboard.ts]: I can't find the specific version it was introduced, sorry. Pre-git days, anyway...

File: web/source/utils/version.ts (hunk 6 above)
Comment (mcdurdin) [reply web/source/utils/version.ts]: Comment reflects old behaviour. Code looks correct.
