### PR TITLE
fix(android/engine): Fix Backspace key to delete without errant subkeys

### LINKED ISSUE #7069: bug(android): Pressing Backspace key for a while make the cursor stuck on the text pane
**Describe the bug**
After entering a word in the text pane I tried to delete all the characters by long pressing the Backspace key leads to stuck the cursor on the text pane. 

**To Reproduce**
1. Install Keyman 16.0.45 alpha build. 
2. Open Keyman In-App. 
3. Enter a word in the text pane.
4. Try to delete all the characters in the word by long pressing the Backspace Key. 

Here, I noticed that the cursor on the text pane get stuck and I was not able to delete any one of the character. I have attached the Screenshot as well as the Video file for reference. 

**Expected behavior**
Long pressing with the Backspace key should delete all the characters one by one. 

**Screenshots**

**Video**

https://user-images.githubusercontent.com/19683143/184367700-2cd4fac0-3387-460c-8eb9-785096d43b83.mp4

**Related issues**
https://github.com/keymanapp/keyman/issues/6544

---

**Keyman for Android:**
   Device:      Android Mobile
 - OS:            Android 11.0 
 - Keyman version:    16.0.45-alpha
 - Target Application: Keyman In-App

---

**Keyboard**
 - Keyboard name:   English - EuroLatin(SIL)
 - Keyboard version: 2.0
 - Language name:   English

**Additional context**
1. I was able to reproduce this issue in API 29 / Android 10 emulator. 
2. I was not able to reproduce this issue in iOS 15.5 / iPhone 13 Pro Max Simulator.

### LINKED ISSUE #7155: bug(android): Holding backspace also seems to trigger a longpress on another random key
From a team review of the Keyman for Android UX (#7161)

It was noted after accepting a suggestion, typing a character, and **holding** the backspace key,
* The backspace sometimes failed to delete and
* the longpress menu of the previous key would appear as long

Fixing the deletion will be addressed on a  separate issue. This one is for the longpress menu. 

**To Reproduce**
Use latest Keyman 16.0 alpha or released 15.0 stable
1. In the Keyman app with the default sil_euro_latin keyboard and lexical model enabled, start typing a word
2. Accept a suggestion
3. Type another letter
4. Hold the backspace key
5. The previous letter is deleted
6. Observe the longpress menu of the previous letter appearing

### LINKED ISSUE #7172: bug(android): Holding backspace appears to desync context between web and app.
**Describe the bug**

From a team review of the Keyman for Android UX (#7161)

Holding backspace appears to desync context between web and app. After the first backspace, subsequent letters are not deleted from the textarea, but holding for a few seconds shows the keyboard going to upper case, suggesting web thinks it is at start of context. After that, even tapping the backspace key then does nothing, suggesting same thing.

Per @jahorton, does not appear to repro on iOS (15.0.268-stable).

**Expected behavior**

Backspace should work. Holding backspace should delete more rapidly.

**Screenshots**

https://user-images.githubusercontent.com/4498365/187533541-587a3aa1-7b88-48e2-998d-632f36bd2f96.mp4

**Related issues**

* #7069 
* #7155 is also visible in the video above.

---

**Keyman for Windows/macOS/Linux/iPhone/iPad/Android:**
 - Device:             Samsung A90 5G 
 - OS:                 Android 12 
 - Keyman version:     15.0.269-stable

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #7069, fixes #7172, and fixes #7155 and follow-on to #6984

When the subkeys window is dismissed, the subKeysList isn't cleared, so holding backspace key would end up displaying the previous longpress menu.

# User Testing

We need to re-run the main test from #6984, first, to verify that this does not re-introduce new bugs.

Setup - A physical Android device. Don't use emulator because the scenario involves typing fast on the OSK (e.g. two thumbs)

* **TEST_POPUPS** - Verify popup keys don't get stuck on
1. On the Android device, install the PR build of Keyman for Android
2. Dismiss the "Get Started" menu
3. In the Keyman app, start typing with the default sil_euro_latin.
4. Type on the OSK using the following scenarios and verify expected output:
    * Clicking a suggestion on the suggestion banner - should insert the suggestion
    * short-press a key and release - should insert the base key
    * long-press a key, select a long-press key, and release - should insert the long-press key (**note:** there should be a 0.5 second delay before the menu appears)
    * long-press a key, while keeping the finger down, move off the long-press options, and release - should **not** output
    * long-press a key, while keeping the finger down, move off the long-press options, then move back on a long-press option so it's highlighted, and release - should output the long-press key
    * quickly type a long paragraph (e.g. repeat the word "reply") - verify long-press keys don't get stuck (displayed when not touching a key)

* **TEST_UP_FLICK** - Verify that the up-flick gesture reliably opens the longpress menu
1. On the Android device, install the PR build of Keyman for Android
2. Dismiss the "Get Started" menu
3. In the Keyman app, start typing with the default sil_euro_latin.
4. Touch a key such as `e` and immediately swipe upwards to access the long-press menu, keeping your finger down. This should show long-press options without the 0.5 second delay.
   * You should be able to select an option from the long-press menu.
   * You should be able to move back onto the base key to select the base key letter again.
   * You should also be able to move your finger away from the menu to cancel the input.
5. Please run this test a number of times to verify that the behaviour remains consistent.

* **TEST_HELD_BACKSPACE** - Verify spurious longpress menu doesn't appear while holding backspace key
1. On the Android device, install the PR build of Keyman for Android
2. Dismiss the "Get Started" menu
3. In the Keyman app, start typing with the default sil_euro_latin.
4. Accept a suggestion
5. Type another letter
6. Touch and hold the backspace key
7. Verify the previous letter is deleted
8. Verify longpress menus for that letter do **not** appear
Note, if the backspace key fails to delete, that's a separate issue #7069 not fixed on this PR

* **TEST_HELD_GLOBE** - Verify spurious longpress menu doesn't appear while holding globe key
1. On the Android device, install the PR build of Keyman for Android
2. Dismiss the "Get Started" menu
3. In the Keyman app, start typing with the default sil_euro_latin.
4. Touch and hold the globe key
5. Verify longpress menus for other letters do **not** appear
6. Release the globe key and verify the Keyboard menu appears (default globe key action when only 1 Keyman keyboard is installed)

01 Sept - 
Adding additional tests to verify if this PR fixes other corresponding issues

* **TEST_HELD_BACKSPACE_DELETES** - Verify holding the backspace key deletes characters (issue #7069) 
1. On the Android device, install the PR build of Keyman for Android
2. In the Keyman app start typing a sentence
3. While holding the backspace key
  * Verify there's no spurious longpress keys displayed
  * Verify the backspace continually deletes characters

* **TEST_NO_BACKSPACE_DESYNC** - Verify backsapce doesn't cause desync between web and app (issue #7172)
1. On the Android device, install the PR build of Keyman for Android
2. In the Keyman app, start typing the sentence "Here is some text"
3. Move the cursor to "some" and then back to the end of "text"
4. While holding the backspace key
  * Verify the context is deleted one character at a time until the entire context is deleted

### CODE REVIEW

**Comment by bharanidharanj** [comment]
* **TEST_POPUPS (PASSED):** Tested this with Keyman 16.0.54-alpha-test-7156 build in my Android Mobile device Version 11.0 and verified that the POPUP keys does not stuck up while testing it. 
* **TEST_UP_FLICK (PASSED):** Tested this with Keyman 16.0.54-alpha-test-7156 build in my Android Mobile device Version 11.0 and verified that the UP FLICK gestures reliably opens the long press menu. 
* **TEST_HELD_BACKSPACE (PASSED):** Tested this with Keyman 16.0.54-alpha-test-7156 build in my Android Mobile device Version 11.0 and verified that the spurious long press menu does not appear while holding the backspace key. seems to be working fine.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java [hunk 1]
```diff
@@ -372,8 +372,12 @@ public void run() {
 
   public void dismissSubKeysWindow() {
     try {
-      if (subKeysWindow != null && subKeysWindow.isShowing())
+      if (subKeysWindow != null && subKeysWindow.isShowing()) {
         subKeysWindow.dismiss();
+      }
+      if (subKeysList != null) {
+        subKeysList = null;
+      }
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java:380]:
```suggestion
      subKeysList = null;
```

Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java:380]: I also wonder why this is wrapped in an exception handler, although I know that isn't new -- what possible crash can we get from `subKeysWindow.isShowing()` or `subKeysWindow.dismiss()`?

**Review by mcdurdin — APPROVED** [review]
Minor cleanup, one related question, but LGTM. Change makes sense. Did you audit the rest of the code for similar patterns?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java (hunk 1 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java:380]: Hmm, I see it's always been in an exception handler from v2.8. Maybe it's just following the pattern from dissmissKeyPreview, though that block is inside a Runnable()

https://github.com/keymanapp/keyman/blob/2b3fa63cea49f47201226d74d35ad57f25d2385e/android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java#L758-L771

**Comment by darcywong00** [comment]
> Did you audit the rest of the code for similar patterns?

Of the four PopupWindows, only subKeysWindow involves an ArrayList of data that needs to be cleared on dismiss.
* subKeysWindow
* keyPreviewWindow
* helpBubbleWindow
* suggestionMenuWindow

**Comment by darcywong00** [comment]
@keymanapp-test-bot retest TEST_GLOBE

**Comment by bharanidharanj** [comment]
* **TEST_HELD_GLOBE (PASSED):** Tested this with the attached PR build (16.0.54-alpha-test-7156) in my Android Mobile device Version 11.0 and verified longpress menus for other letters do not appear and releasing the globe key, the keyboard menu appears on the screen. Seems to be working as expected.

**Comment by mcdurdin** [comment]
In my tests of this update, this also appears to fix #7172.

**Comment by mcdurdin** [comment]
Does this also fix #7169? I can no longer repro that bug on this build.

**Comment by mcdurdin** [comment]
**DONT-MERGE:** need to add tests for other presumed-fixed issues here before merge.

**Comment by darcywong00** [comment]
@keymanapp-test-bot retest TEST_HELD_BACKSPACE_DELETES

**Comment by bharanidharanj** [comment]
* **TEST_HELD_BACKSPACE_DELETES (PASSED):** Tested this with the attached PR build (16.0.54-alpha-test-7156) in my Android Mobile device Version 11.0 and verified long press the Backspace key does not make the cursor stuck on the text pane. Instead of that it removes all the characters while long pressing the Backsapce key. Seems to be fixed and working fine with the recent build.

**Comment by darcywong00** [comment]
@keyamnapp-test-bot retest TEST_NO_BACKSPACE_DESYNC

**Comment by bharanidharanj** [comment]
* **TEST_NO_BACKSPACE_DESYNC (PASSED):** Tested this with Keyman 16.0.54-alpha-test-7156 PR build and followed the steps as it mentioned above User Testing. Verified that the context is deleted one character at a time until the entire context is deleted while holding the backsapce key.

**Comment by mcdurdin** [comment]
> Does this also fix #7169? I can no longer repro that bug on this build.

Note: #7169 was not fixed by this PR; see that issue for more details of resolution.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.57-alpha](https://keyman.com/downloads/releases/alpha/16.0.57)
