### PR TITLE
fix(android/app): Toggle keyboard update notifications for landscape and tablets

### LINKED ISSUE #6731: bug(android): "update pending" icon on tablets is not responsive
**Describe the bug**
Detected while addressing #6698.  Original notes may be found @ https://github.com/keymanapp/keyman/issues/6698#issuecomment-1149501856.

Pretty much what the title says; the batch-update icon displayed on tablets doesn't actually _do_ anything when a user attempts to interact with it.

**To Reproduce**

1. Download an [old version of sil_cameroon_qwerty](https://downloads.keyman.com/keyboards/sil_cameroon_qwerty/6.0.4/sil_cameroon_qwerty.kmp)
2. On the device, set airplane mode on (turns off internet access)
3. On the device, go to settings, and manually set the date to 1 year in the past (e.g. May 2021)
4. Start Keyman for Android
5. From the Keyman Settings, install the local kmp file sil_cameroon_qwerty.kmp (will be an old version 6.0.4)
6. Close Keyman
7. On the device, go to settings and set the date to automatically update from internet
8. On the device, turn off airplane mode (turns on internet access)
9. On the device, go to settings and verify the date is updated
10. Launch Keyman for Android
11. Dismiss "Get Started" and wait for the catalog to update
12. After a while, there should be a notification of a keyboard update being available
13. Verify keyboard update is available; there should be an icon of a cloud with a down arrow at the top right.
14. Click on that button - "Install Updates"
15. ... watch it do nothing.

**Expected behavior**

15. A confirmation dialogue should appear.
16. Accept "Download" on the dialogue
17. Verify resource is updated after background download complete

**Other Notes**
It is still possible to update the resource by going to its specific section in the Installed Languages menu.  It's just not possible for a user to batch-update through that icon.

---

**Keyman for Android:**
 - Device: Galaxy Tab A
 - OS: Android 6.0
 - Keyman version: 16.0.11-alpha-test-6525.
     - Note that there is no real difference in the Android code here from that found in 15.0.258-beta.
 - Target application: Keyman

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #6731

Previously, the Keyman notification of keyboard updates could appear on 3 form factors:
* phone (portrait orientation) - notification on overflow menu
* phone (landscape orientation) - notification on menu
* tablet (> 600dp, either orientation) - notification on menu

The landscape and tablet layouts had a complexity of a dynamic layout "update_count_view" which turned out to be un-clickable.

This PR removes the usage of "update_count_view", and toggles the update icon when updates are available. (This removes the feature of a dynamic count of updates available). The minor loss in feature should be acceptable since long-term we plan to just automatically download keyboard/dictionary updates as they're available (#7171).

## User Testing
Setup - For each group, use the Android device and orientation as specified in the test.
1. On the device, download the old version [1.0 of sil_nko Keyman keyboard](https://downloads.keyman.com/keyboards/sil_nko/1.0/sil_nko.kmp)
2. Install the PR build of Keyman for Android

**GROUP_PHONE_PORTRAIT** - Verifies update installs for phone in portrait orientation
**GROUP_PHONE_LANDSCAPE** - Verifies update installs for phone in landscape orientation. Note - Keyman always starts up in portrait orientation, so you may need to re-orient the device back and forth to get Keyman in landscape orientation
**GROUP_TABLET_LANDSCAPE** - Verifies update installs for tablet (either orientation)

**TEST_KEYBOARD_UPDATE**
1. Launch Keyman for Android and dismiss the "Get Started" menu
2. From the Keyman settings menu, install the version 1.0 of the sil_nko keyboard package (Install from local file).
3. During installation of sil_nko, choose "Mandingo" language
4. When sil_nko finishes installing, completely exit Keyman
5. Relaunch Keyman for Android
6. After a while, see if notifications appear about keyboard updates being available. If they don't appear, completely exit Keyman and try re-launching Keyman for Android.
7. When there's notifications about Keyman updates being available, click the appropriate menu to "Install Updates"
    * phone portrait - icon from the overflow menu
    * phone landscape - icon on the top menu next to "Settings"
    * tablet - icon on the top menu next to "Settings"
 8. Verify Keyman prompts confirmation to download a keyboard update for sil_nko
 9. Accept the dialog
 10. Verify after a while, the keyboard updates in the background.
 11. Long-press the globe key to display the keyboard picker menu.
 12. Verify the version of sil_nko is now 1.1.

### CODE REVIEW

**Comment by bharanidharanj** [comment]
### GROUP_PHONE_LANDSCAPE: - Verifies update installs for phone in landscape orientation. Note - Keyman always starts up in portrait orientation, so you may need to re-orient the device back and forth to get Keyman in landscape orientation

* **TEST_KEYBOARD_UPDATE (PASSED):** Tested this in my Android Mobile device Ver 11.0 with the attached PR build and here is my observation: 1. Verified the Install Updates for phone in landscape orientation and it seems to be working as expected.

**Comment by darcywong00** [comment]
@bharanidharanj - the crash you experienced was related to Android S, and I've created issue #7843 to address that.

Can you retest with Android tablet using Android 11.0 (API 30)?

@keymanapp-test-bot retest GROUP_TABLET_LANDSCAPE

**Comment by bharanidharanj** [comment]
> @bharanidharanj - the crash you experienced was related to Android S, and I've created issue #7843 to address that.
> 
> Can you retest with Android tablet using Android 11.0 (API 30)?
> 
> @keymanapp-test-bot retest GROUP_TABLET_LANDSCAPE

@darcywong00 Sure, I will retest it in Android 11.0 emulator.

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java [hunk 1]
```diff
@@ -452,6 +453,11 @@ public boolean onOptionsItemSelected(MenuItem item) {
         KMManager.getUpdateTool().executeOpenUpdates();
         // Dismiss icon
         updateUpdateCountIndicator(0);
+        final MenuItem _keyboardupdate = menu.findItem(R.id.action_update_keyboards);
```
Comment (mcdurdin) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java:456]: Is it possible for `menu` to be uninitialized at this point?

**Review by mcdurdin — APPROVED** [review]

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java (hunk 1 above)
Comment (darcywong00) [reply android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java:456]: The system should have called onCreateOptionsMenu() the first time menu is displayed

https://developer.android.com/reference/android/app/Activity#onCreateOptionsMenu(android.view.Menu)

**Comment by bharanidharanj** [comment]
### GROUP_TABLET_LANDSCAPE: - Verifies update installs for tablet (either orientation)

* **TEST_KEYBOARD_UPDATE (PASSED):** Retested this in API 30 / Android 11.0 emulator (as per Darcy's suggestion) and here is my observation: 1. Tested this in Landscape orientation. 2. Not able to see the 'Install Update' option near the Settings option. 3. However, I noticed this option is available in the Keyboard menu. 4. By clicking on this would update the Keyboard version from 1.0 to 1.1. Note: In the Portrait orientation, I was able to see the 'Install Update' button near Settings button. 

..Landscape Orientation

   


..Portrait Orientation

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.116-beta](https://keyman.com/downloads/releases/beta/16.0.116)
