### PR TITLE
fix(web, ios): better SMP, emoji handling with frequent keyboard swaps

### LINKED ISSUE #4868: bug(android): Typing Emoji in Messaging app causes bug when tried to backspace.
**Describe the bug**

https://community.software.sil.org/t/emoji-delete-bug/4610

I'm typing a post in WhatsApp (also Telegram) using my keyboard Jawa_Latin (https://github.com/keymanapp/keyboards/pull/1495). Use Messaging app's emoji button, input an emoji. Go back to my keyboard, try to delete (backspace) the emoji, results in three tofus (���). Backspace again clear the tofus.

Try to add letters after emoji, then pressing backspace would result in nasty bug, the number of characters in the text field won't reduce, but pressing backspace resulted in a random character to pop up, essentially rendering backspace useless. I can only select all text and backspace to clear it, or post the buggy message, and delete it.

Edit 1: Confirming the bug exist in my WhatsApp, Telegram, and Keyman for Android (if I copy paste an emoji from somewhere else)

Edit 2: Confirming the bug exist in other keyboards, such as default EuroLatin SIL keyboard

Super nasty bug!

**To Reproduce**

1. Go to WhatsApp or Telegram, right now I'm using my keyboard, https://github.com/keymanapp/keyboards/pull/1495, but will try other keyboards after I submit this.
2. Compose any message, start with an emoji, using emoji provided by WhatsApp. Then exit the emoji screen, try backspace, you'll see ���; if you add some text after the emoji, more chaos ensued.
3. See error

**Expected behavior**

Emoji should be deleted with no tofus.

**Screenshots**

If the repro steps doesn't work, I'll post a video. Screenshots cannot describe the effect.

---

**Keyman for iPhone/iPad/Android:**
 - Device: Nokia 2.2
 - OS: Android 10, 5 March 2021
 - Keyman version 14.0.270
 - Target application: WhatsApp 2.20.201.23 or Telegram 7.6.0
 - 
---

**Keyboard**
 - Keyboard name: Latin Jawa https://github.com/keymanapp/keyboards/pull/1495
 - Keyboard version: 1.0
 - Language name: Basa Jawa (Javanese)

**Additional context**

The bug appear whenever there's at least 1 emoji on the text. It doesn't matter where: on the same line, same sentence, different lines/paragraph. As long as there's 1 emoji while typing, and I press backspace (on any character, any language/script, selecting random part of the sentence, i.e. not a sequence bug), the bug happens.

If the emoji is deleted by any mean (usually by select part of text and press backspace), then the rest of the text resumes to normal. 

As long as the backspace is not pressed, I can still compose the text normally, no problem.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #4868.  No Android-specific changes appear to be needed, though extra testing in that regard would be wise.

------

When in scenarios where users may frequently swap keyboards - especially between keyboards where some use SMP characters but some don't - attempting to backspace into context typed by previous keyboards can prove tricky if trying to optimize out SMP logic.  This was done far in the past for performance reasons, but the additional complexity it brings (and the resulting bugs, like #4868) is no longer worth it.  For comparison, while testing the iOS changes, I noted that Apple's default backspace handling function near-certainly always makes SMP checks.

Permanently enabling KMW's SMP processing logic is the first step.  However, within our iOS engine, it turns out additional work was needed to properly delete some emojis, such as skintoned variants, which are represented as multiple combining code points - many of which are themselves comprised of two code units.  Apple's default backspace auto-removes the entire combining set, rather than a single code point of the multi-point emoji... something that KMW is simply not equipped to do right now.  So, to ensure proper context synchronization, we ensure that only the part KMW knows to delete is deleted.

------

## User Testing
@MakaraSok 

Test out how well Keyman + predictive text work with pre-existing context.

1.  Before activating Keyman, type "hello the ", then add the emoji "👍🏻".  So, `hello the 👍🏻`.
2. Activate Keyman and set `sil_euro_latin` as the active keyboard.
3. Hit backspace.  `hello the 👍` should result.  (Note the different skintone.)
4. Hit backspace twice more.  `hello the` should result, along with suggestions prefixed with "the".
5. Apply a suggestion.  As `there` is usually available, pick that one if possible - `hello there ` should result.

Test some similar pre-existing strings, possibly with multiple emoji in sequence after some typed text.  Ensure that when the caret does reach the end of a word, appropriate suggestions result (if any appear).  Applying suggestions should give the expected result.

### CODE REVIEW

File: common/core/web/keyboard-processor/src/keyboards/keyboard.ts [hunk 1]
```diff
@@ -246,6 +246,12 @@ namespace com.keyman.keyboards {
       return true;
     }
 
+    get usesSupplementaryPlaneChars(): boolean {
+      let kbd = this.scriptObject;
+      // I3319 - SMP extension, I3363 (Build 301)
+      return kbd && ((kbd['KS'] && kbd['KS'] == 1) || kbd['KN'] == 'Hieroglyphic');
+    }
+
```
Comment (jahorton) [inline common/core/web/keyboard-processor/src/keyboards/keyboard.ts:254]: This is used within the first two commits, where SMP handling was only permanently-enabled when in embedded mode.

That said... it's also good to preserve the original logic somewhere in case a Web-Core consumer needs to know this about a keyboard's ruleset for some reason.

File: ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift [hunk 2]
```diff
@@ -371,13 +371,18 @@ open class InputViewController: UIInputViewController, KeymanWebDelegate {
...
-                                                  offsetBy: newContext.utf16.count)
-          let upperIndex = oldContext.utf16.index(lowerIndex, offsetBy: unitsDeleted - 1)
-          textDocumentProxy.insertText(String(oldContext[lowerIndex..<upperIndex]))
-        }
+      let unitsInPoint = InputViewController.isSurrogate(oldContext.utf16.last!) ? 2 : 1
+
+      // This CAN happen when a surrogate pair is deleted.
+      // For example, the emoji 👍🏻 is made of TWO surrogate pairs.
+      // Apple's .deleteBackward() implementation will delete both simultaneously,
+      // but our internal KMW engine can't do that b/c it's not emoji-aware.
```
Comment (mcdurdin) [inline ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift:379]: We should certainly have a TODO issue to properly support deletion of emoji...

File: web/source/keyboards/kmwkeyboards.ts [hunk 3]
```diff
@@ -589,9 +589,7 @@ namespace com.keyman.keyboards {
       }
 
       var Pk=keyman.core.activeKeyboard;  // I3319
-      if(Pk !== null)  // I3363 (Build 301)
-        Pk = Pk.scriptObject;
-        String.kmwEnableSupplementaryPlane(Pk && ((Pk['KS'] && (Pk['KS'] == 1)) || (Pk['KN'] == 'Hieroglyphic'))); // I3319
+      String.kmwEnableSupplementaryPlane(true);
```
Comment (mcdurdin) [inline web/source/keyboards/kmwkeyboards.ts:592]: Do we need this if it is being done in keymanweb.ts during init?

File: web/source/keyboards/kmwkeyboards.ts [hunk 4]
```diff
@@ -664,7 +662,8 @@ namespace com.keyman.keyboards {
               manager.keymanweb.domManager._SetTargDir(manager.keymanweb.domManager.getLastActiveElement());
             }
 
-            String.kmwEnableSupplementaryPlane(kbd && ((kbd['KS'] && kbd['KS'] == 1) || kbd['KN'] == 'Hieroglyphic')); // I3319 - SMP extension, I3363 (Build 301)
+            String.kmwEnableSupplementaryPlane(true);
```
Comment (mcdurdin) [inline web/source/keyboards/kmwkeyboards.ts:665]: Do we need this if it is being done in keymanweb.ts during init?

**Review by mcdurdin — CHANGES_REQUESTED** [review]
Nice and simple; just a couple of questions.

File: web/source/keyboards/kmwkeyboards.ts (hunk 3 above)
Comment (jahorton) [reply web/source/keyboards/kmwkeyboards.ts:592]: If there's no code that would ever turn it off... not in this form, no.  Could 'optimize' that out.

I'd still want to leave a comment saying "if toggling SMP support based on the active keyboard, do that here" at least.

Comment (mcdurdin) [reply web/source/keyboards/kmwkeyboards.ts:592]: But I think we are removing the idea of ever turning off SMP support, no?

File: web/source/keyboards/kmwkeyboards.ts (hunk 4 above)
Comment (jahorton) [reply web/source/keyboards/kmwkeyboards.ts:665]: Same response as before.

File: ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift (hunk 2 above)
Comment (jahorton) [reply ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift:379]: Documented as #4956.

**Review by mcdurdin — APPROVED** [review]

**Comment by mcdurdin** [comment]
Please 🍒-pick to stable-14.0

**Comment by MakaraSok** [comment]
Just tested and everything is working as expected every step of the way. My two cents for the removal of the skin tone seems unnecessary, I'd rather delete the whole things instead of only removing the color. :)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.33-alpha](https://keyman.com/downloads/releases/alpha/15.0.33)
