### PR TITLE
fix(web): default multitap logic for shift-layer shift multitaps

### LINKED ISSUE #10272: bug(web): shift on- double tap behavior (cycling back to shift on), expected to go to "caps lock state"
### Describe the bug

current behavior.

**shift key from normal:**
single tap -> shift on
double tap -> caps lock

**shift key from shift on:**
_single tap -> caps state_
_double tap -> back to shift state_

Expected behavior.
**shift key from shift on:**
**_single tap -> normal_**
**_double tap -> caps lock_**

### Reproduce the bug

_No response_

### Expected behavior

Expected behavior.
**shift key from shift on:**
**_single tap -> normal_**
**_double tap -> caps lock_**

### Related issues

_No response_

### Keyman apps

- [X] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [X] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.231 aplha

### Operating system

_No response_

### Device

_No response_

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #10272.

When on the shift layer, our default 'caps' layer multitap logic should act as follows:
1. First tap:  default layer
2. Second tap:  caps layer
3. Third tap: return to shift layer
4. Return to step 1 - default layer.  (Things rotate from here.)

In 16.0, steps 1 and 2 (at a minimum) were in place... and I missed this fact when migrating the default multitap logic to the new gesture engine.  This PR fixes the regression.  (Rota behavior - steps 3+ - wasn't expected or implemented at the time, though.)

**NOTE**: The fact that _both_ the `default` and `shift` layer SHIFT keys get multitaps when relying on Keyman multitap defaults suggests to me that we should condition on both SHIFT keys, not just one of them - and so I moved the logic to a location that can check against the properties of both.  It is possible that this point should be debated a bit, though.

## User Testing

TEST_MULTITAP_FROM_SHIFT:  Using the Keyman for Android app and the "EuroLatin (SIL)" keyboard, verify that this fixes the issue.

1. If not already on the keyboard's `shift` layer, activate the `shift` layer.  Wait 1 second before proceeding.
2. Double-tap the SHIFT key.
3. Verify that the `caps` layer is active - there should be a small underline beneath the SHIFT key's up-arrow.
4. Type `CAPS`, verifying that the layer does not change while typing.

TEST_SHIFT_ROTA:  Using the Keyman for Android app and the "EuroLatin (SIL)" keyboard...

1. If not already on the keyboard's `shift` layer, activate the `shift` layer.  Wait 1 second before proceeding.
2. Triple-tap the SHIFT key.
3. Verify that the `shift` layer is once again active.
4. Type `Caps` - after the `C`, the layer should return to `default` automatically.

TEST_MULTITAP_FROM_DEFAULT:  Using the Keyman for Android app and the "EuroLatin (SIL)" keyboard...

1. If not already on the keyboard's `default` layer, activate the `default` layer.  Wait 1 second before proceeding.
2. Double-tap the SHIFT key.
3. Verify that the `caps` layer is active - there should be a small underline beneath the SHIFT key's up-arrow.
4. Type `CAPS`, verifying that the layer does not change while typing.

TEST_DEFAULT_ROTA:  Using the Keyman for Android app and the "EuroLatin (SIL)" keyboard...

1. If not already on the keyboard's `default` layer, activate the `default` layer.  Wait 1 second before proceeding.
2. Triple-tap the SHIFT key.
3. Verify that the `default` layer is once again active.
4. Type `caps`, verifying that the layer does not change while typing.

### CODE REVIEW

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_MULTITAP_FROM_SHIFT (PASSED):** Tested with attached PR build (Keyman 17.0.233-alpha-test-10281) in the Android Mobile (Samsung Galaxy - ver 13) and here is my observation: 1. Verified that a small underline beneath the SHIFT key's up-arrow appear in the 'caps' layer, when the SHIFT key is double-tapped in the 'caps' layer. Also, verified that the caps layer did not changed after typing the word 'CAPS' on the text input screen.

**Comment by darcywong00** [comment]
> When on the shift layer, our default 'caps' layer multitap logic should act as follows:
>
>First tap: default layer
Second tap: caps layer
Third tap: return to shift layer
Return to step 1 - default layer. (Things rotate from here.)

The user test verifies the 2nd tap to caps layer. Should we add some steps to verify 3rd tap returns to shift and another to return to default layer?

File: common/web/keyboard-processor/src/keyboards/defaultLayouts.ts [hunk 1]
```diff
@@ -535,15 +535,22 @@ export class Layouts {
...
-    id: "T_*_MT_SHIFT_ROTA_TO_DEFAULT",
+    id: "T_*_MT_SHIFT_TO_DEFAULT",
     text: '*Shift*',
     sp: 1,
     nextlayer: 'default'
   }
 
+  static dfltShiftToShift: LayoutSubKey = {
+    id: "T_*_MT_SHIFT_TO_SHIFT",
+    text: '*Shift*',
```
Comment (darcywong00) [inline common/web/keyboard-processor/src/keyboards/defaultLayouts.ts:549]: Do we use `*Shifted*` on the shift layer?

File: common/web/types/src/keyman-touch-layout/keyman-touch-layout-file.ts [hunk 2]
```diff
@@ -52,8 +52,9 @@ export const PRIVATE_USE_IDS = [
    * Private-use identifiers used by KeymanWeb for the default multitap-into-caps-layer key
```
Comment (darcywong00) [inline common/web/types/src/keyman-touch-layout/keyman-touch-layout-file.ts:52]: These have grown into more than just multitap-into-caps...  Maybe multitap-shift-into other layers?

File: common/web/keyboard-processor/src/keyboards/defaultLayouts.ts (hunk 1 above)
Comment (jahorton) [reply common/web/keyboard-processor/src/keyboards/defaultLayouts.ts:549]: There doesn't technically _need_ to be text for the keycap here, since modifier keys don't get multitap preview hints.  The main reason I have anything here is that a string is required as part of the standard subkey-structure typing.

File: common/web/types/src/keyman-touch-layout/keyman-touch-layout-file.ts (hunk 2 above)
Comment (jahorton) [reply common/web/types/src/keyman-touch-layout/keyman-touch-layout-file.ts:52]: Not really... it's still pretty accurate.  These only provide for caps-related multitap defaults.

**Comment by jahorton** [comment]
... fine, I'll add a few more user tests.  I'm not terribly worried about 'em, though.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by jahorton** [comment]
Huh, so auto-merge _doesn't_ wait on all of the checks?  Good to know for the future.  But yeah, not terribly worried about those extra tests, and the main (original) one did pass already.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.234-alpha](https://keyman.com/downloads/releases/alpha/17.0.234)

**Comment by mcdurdin** [comment]
> Huh, so auto-merge _doesn't_ wait on all of the checks? Good to know for the future. But yeah, not terribly worried about those extra tests, and the main (original) one did pass already.

I think that relying on auto-merge for user test passes is problematic, because we really need to review the user test results before merging anyway. Our testers do report passes with caveats and notes and we are liable to miss the results.

That's aside from the fact that the auto-merge happened before user testing completed -- because user testing is not a 'required status check'. We would need to do some infrastructure work before that could happen.
