### PR TITLE
fix(windows): Refresh settings on 64-bit apps

### LINKED ISSUE #4289: bug(windows): Simulate AltGr with Ctrl+Alt - checked, but no output when triggered
**Describe the bug**

The expected character is not produced when Ctrl+Alt+(anyKey) is triggered while the "Simulate AltGr with Ctrl+Alt" is checked.

**To Reproduce**

1. Install Khmer Angkor keyboard
2. Press AltGr+`K_A` and confirm that a plus sign is output
3. Now, go to the Option tab in the Configuration and check 'Simulate AltGr with Ctrl+Alt'
4. Press 'Ctrl+Alt+`K_A`' and see error (OSK does show the appropriate layout, but nothing is output as expected)

**Expected behavior**

The expected character should be output. In this case, when the option is checked, a plus sign should be produced.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 1909 x64
 - Keyman version: 14.0.221-beta
 - Target Application: self

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: e.g. 1.0.7
 - Language name: Khmer

**Additional context**

https://github.com/keymanapp/keyman/issues/4188

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4289.

Some settings changes would not apply immediately for 64-bit apps, as the refresh was not being processed until keymanx64 received focus (i.e. never, as keymanx64 does not have a visible window!)

### CODE REVIEW

File: windows/src/engine/keyman32/Keyman32.cpp [hunk 1]
```diff
@@ -755,7 +764,7 @@ void LoadBaseLayoutSettings() {   // I4552   // I4583
 
     Globals::SetBaseKeyboardFlags(underlyingLayout, reg->ReadInteger(REGSZ_SimulateAltGr), !reg->ValueExists(REGSZ_DeadkeyConversionMode) || reg->ReadInteger(REGSZ_DeadkeyConversionMode));
 	} else {
-    Globals::SetBaseKeyboardFlags("", 0, 0);
+    Globals::SetBaseKeyboardFlags("", 0, 1);
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/Keyman32.cpp:767]: This is unlikely to ever be called, but just noting that the default for deadkeyconversionmode should be TRUE, not FALSE

**Comment by MakaraSok** [comment]
This works in Keyman's Text Editor, browser and LibreOffice writer; but not in the Windows' Notepad.

**Comment by mcdurdin** [comment]
> This works in Keyman's Text Editor, browser and LibreOffice writer; but not in the Windows' Notepad.

Which Notepad app was it -- the default 64-bit one, or the \windows\syswow64\notepad.exe instance? Also, which browser, and is LibreOffice 32 or 64 bit? It sounds like there are some inconsistencies in the results... (I assume you were testing with the build artifact version)

**Comment by MakaraSok** [comment]
nts: this was happening with the x64 version of Notepad. The browser and LibreOffice are also x64.

**Comment by mcdurdin** [comment]
@MakaraSok Can you test the next build when it finishes? I think it should resolve the inconsistency.

File: windows/src/engine/keyman32/Keyman32.cpp [hunk 2]
```diff
@@ -695,9 +695,9 @@ void HandleRefresh(int code, LONG tag)
     // This is sent by Keyman COM API, ApplyToRunningKeymanEngine
     SendDebugMessageFormat(0, sdmGlobal, 0, "#### Refresh Requested ####");
 
-    // We ask any controller window to tell all instances of keyman32/keyman64
-    // that a refresh is coming through
-    Globals::PostControllers(wm_keyman_refresh, KR_PRE_REFRESH, 0);
+    // We ask the master controller window to tell all instances
+    // of keyman32/keyman64 that a refresh is coming through
+    Globals::PostMasterController(wm_keyman_refresh, KR_PRE_REFRESH, 0);
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/Keyman32.cpp:700]: There is no need to ask any controller, just ask the master controller, and this reduces duplicate refresh requests yet further.

File: windows/src/engine/keyman32/Keyman32.cpp [hunk 3]
```diff
@@ -679,9 +679,9 @@ BOOL UpdateRefreshTag(LONG tag)   // I1835 - Reduce chatter
 {
   PKEYMAN64THREADDATA _td = ThreadGlobals();
   if(!_td) return FALSE;
-  if(_td->RefreshTag_Process < tag)
+  if(_td->RefreshTag_Thread != tag)
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/Keyman32.cpp:682]: When Keyman is restarted, the global `RefreshTag` is reset to `0`, so we need to do a `!=` comparison rather than a `<` comparison to ensure that apps with an existing keyman32.dll/keyman64.dll in memory get refresh notifications (as their local `RefreshTag_Process` will likely already be greater than `0`).

**Review by jahorton — APPROVED** [review]

**Comment by MakaraSok** [comment]
> @MakaraSok Can you test the next build when it finishes? I think it should resolve the inconsistency.

This build (`14.0.233-beta-test-4378`) has been tested on both x32 and x64 of Windows 10 Pro.

In Notepad:
|  | Windows 10 Pro x32 | Windows 10 Pro x64 |
| ---- | ---- | ---- | 
| 'Simulate AltGr with Ctrl+Alt' checked | v | x |
| 'Simulate AltGr with Ctrl+Alt' unchecked | v | v |

_v - work as intended (Ctrl+Alt or AltGr key combo outputs the expected character)
x - doesn't work as intended_

In LibreOffice/Chrome:
|  | Windows 10 Pro x32 | Windows 10 Pro x64 |
| ---- | ---- | ---- | 
| 'Simulate AltGr with Ctrl+Alt' checked | v | v |
| 'Simulate AltGr with Ctrl+Alt' unchecked | v | v |

**Comment by mcdurdin** [comment]
> This build (`14.0.233-beta-test-4378`)

Is that buildId 250605? https://build.palaso.org/viewLog.html?buildId=250605&buildTypeId=KeymanDesktop_TestPullRequests (will require uninstall and reinstall because it has the same version tag).

**Comment by MakaraSok** [comment]
> > This build (`14.0.233-beta-test-4378`)
> 
> Is that buildId 250605? https://build.palaso.org/viewLog.html?buildId=250605&buildTypeId=KeymanDesktop_TestPullRequests (will require uninstall and reinstall because it has the same version tag).

Yes, `https://build.palaso.org/buildConfiguration/KeymanDesktop_TestPullRequests/250605?` of the Details link on "Test-14.0 (Keyman - Windows (Desktop/Developer))".

**Comment by mcdurdin** [comment]
Despite the note about Notepad not refreshing settings, I am going to merge this, and follow up on that separately, because this is a much better situation than before.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.248-beta](https://keyman.com/downloads/releases/beta/14.0.248)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.19-alpha](https://keyman.com/downloads/releases/alpha/15.0.19)

**Comment by MakaraSok** [comment]
Tested with Keyman 14.0.259-beta.

Confirm that this issue has been fixed in https://github.com/keymanapp/keyman/issues/4557.
