### PR TITLE
fix(windows): Start Keyman on Demand - keyman32

### LINKED ISSUE #3562: feat(windows): help user start Keyman if it isn't running
With Keyman 14, keyboard TIPs are always registered and installed; if the user selects a Keyman keyboard when Keyman is not running, the TIP attempts to start Keyman, and if it can't, prompts the user to start Keyman.

Relates to #3512.

### PR DESCRIPTION
**Pull request by mcdurdin**
This is the first half of a two-part update to Keyman for Windows. There are two significant changes here. These changes apply to keyman32/keyman64, as well as kmtip/kmtip64, but will refer to the 32-bit equivalents for simplicity:

1. Instead of using `GetProcAddress` to connect to keyman32.dll, we now have an import library connection. This removes one particularly suspect piece of architecture for Keyman, as using `GetProcAddress` could lead to a race condition, where keyman32.dll is unloaded after that function is called but before we use the handle. This makes the kmtip.dll build dependent on keyman32.dll; loading kmtip.dll (by selecting a Keyman input method) also loads keyman32.dll.

2. It's not enough (yet) to load kmtip.dll. We also need to be running keyman.exe itself, due to global hooks that we still require (it may be possible, one day, to avoid these, but it doesn't look very hopeful). To that end, kmtip calls new function `TIPIsKeymanRunning` to check whether keyman32.dll is initialised (and hence keyman.exe has initialised it). Then, if keyman.exe is not running, it issues an event to the Windows Event Log, which we will pick up with a scheduled task in the next PR.

The first part of this is an architectural change which may lead to some change in behaviours, as keyman32.dll now may not be unloaded from a process when keyman.exe exits, due to the lock that kmtip.dll now has on it. It will be important to test this (@MakaraSok) by running through various startup and shutdown scenarios. In my initial testing, I found that there were some situations after restarting keyman.exe where I needed to switch in and out of the Keyman TIP, but those were not all critical.

This change also lays groundwork for an eventual ability to run the Keyman input method without keyman.exe running, which will be helpful e.g. on login screen, even if missing certain additional functionality such as the serialised input queue.

* keymanmc.dll is required to provide a message template for the event log. This new component makes up 5 of the file changes. (A future task may be to move the ETW template to keymanmc.dll as well).

Fixes #3562.

### CODE REVIEW

**Comment by jahorton** [comment]
> This change also lays groundwork for an eventual ability to run the Keyman input method without keyman.exe running, which will be helpful e.g. on login screen, even if missing certain additional functionality such as the serialised input queue.

... isn't that kind of an important bit of functionality to have?  I recall there being input instabilities when typing without said queue.

File: windows/src/engine/kmtip/keyman32interface.cpp [hunk 1]
```diff
@@ -1,24 +1,42 @@
...
-  if (hKeyman) {
-    PKEYMAN_WRITEDEBUGEVENT pWriteDebugEvent = (PKEYMAN_WRITEDEBUGEVENT)GetProcAddress(hKeyman, "Keyman_WriteDebugEvent");
-    if (pWriteDebugEvent) {
-      (*pWriteDebugEvent)(file, line, msg);
-    }
-    // Don't DebugLastError here because it depends on WriteDebugEvent...
-  }
+  ::Keyman_WriteDebugEvent(file, line, msg);
+  // Don't DebugLastError here because it depends on WriteDebugEvent...
+}
```
Comment (jahorton) [inline windows/src/engine/kmtip/keyman32interface.cpp:21]: I've noticed this pattern shift a few times during the review.  I assume it accomplishes the same goal, just in a more polished way?

File: windows/src/engine/kmtip/kmkey.cpp [hunk 2]
```diff
@@ -126,13 +98,13 @@ BOOL CKMTipTextService::_KeymanProcessKeystroke(ITfContext *pContext, WPARAM wPa
     return FALSE;   // I4378
   }
 
-  if (!_CheckKeymanLoaded()) {   // I4274
-    Log(L"_KeymanProcessKeystroke: _CheckKeymanLoaded failed");
+  if (!Keyman32Interface::TIPIsKeymanRunning()) {
```
Comment (jahorton) [inline windows/src/engine/kmtip/kmkey.cpp:101]: I see that `TIPIsKeymanRunning` is replacing a number of checks that used to be internal code for the `kmtip` module, and that it's an `extern`.  I presume this is provided by `keyman32.dll`, given this part of the description?

> This makes the kmtip.dll build dependent on keyman32.dll; loading kmtip.dll (by selecting a Keyman input method) also loads keyman32.dll.

**Review by jahorton — COMMENTED** [review]
A few clarification questions before I approve, since I'm not too familiar with this part of the codebase...

File: windows/src/engine/kmtip/kmkey.cpp (hunk 2 above)
Comment (jahorton) [reply windows/src/engine/kmtip/kmkey.cpp:101]: I ask because the definition doesn't appear within this PR's changelog.

File: windows/src/engine/kmtip/kmtip.cpp [hunk 3]
```diff
@@ -248,12 +245,11 @@ STDAPI CKMTipTextService::Activate(ITfThreadMgr *pThreadMgr, TfClientId tfClient
...
-  if(_LoadKeyman()) {   // I4274
-    if(!_InitKeyman())	{
-		  Log(L"Could not initialise Keyman");
-      goto ExitError;
-	  }
-  }
+  if(!_InitKeyman())	{
+    _TryAndStartKeyman();
+		Log(L"Could not initialise Keyman");
+    //goto ExitError;
```
Comment (mcdurdin) [inline windows/src/engine/kmtip/kmtip.cpp:251]: Plus I should delete this...

File: windows/src/engine/kmtip/kmkey.cpp (hunk 2 above)
Comment (mcdurdin) [reply windows/src/engine/kmtip/kmkey.cpp:101]: Yes, see https://github.com/keymanapp/keyman/pull/3772/files#diff-0f6686cdf0b3a08d6ced71b454d40bb11e3d0c7b242536563d056cf16e0b1ffeR63 for the `TIPIsKeymanRunning` definition. A deeper refactor should allow us to eliminate it entirely from kmtip in the future, but I don't want to do that at this point in the release cycle.

**Review by mcdurdin — COMMENTED** [review]
> ... isn't that kind of an important bit of functionality to have? I recall there being input instabilities when typing without said queue.

The serialised input means that input order is guaranteed with rapid typing. It occurs somewhat infrequently (enough to be a hassle) but Keyman did not have it for many years and was still useful. For a context like the login screen, it would not be essential (although there are other challenges with the login screen, like how do you configure which keyboards you want available).

**Comment by mcdurdin** [comment]
Apologies. I clicked merge on the wrong approved PR there. That mixes up #3772 and #3773 a bit...

**Review by jahorton — APPROVED** [review]
