### PR TITLE
fix(android/engine): URIEncode strings passed to Javascript

### LINKED ISSUE #11182: bug(android): Can't backspace after pasting string with encoded URI components
### Describe the bug

I have the link below in the address bar in the Chrome browser and the IP at the end of the string. When I press Backspace (with EuroLatin keyboard active) nothing happens.

https://cdn.retailads.net/tc.php?t=151238C2287900209D&deepurl=https%3A%2F%2Fa.nonstoppartner.net%2Fa%2F%3Fi%3Dclick%26l%3Dde%26client%3Daldi%26camp%3Ddeep%26nw%3Dread%26deepid%3D101012640&subid=1712319X100149708X67035X29711X86818X181XtextlinkXyahl6byko6csX

https://github.com/keymanapp/keyman/assets/181336/05b4f5b7-b9fe-446b-a5df-ef29f942e40d

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.301-beta

### Operating system

Android 12

### Device

realme X3 SuperZoom (RMX2086)

### Target application

_No response_

### Browser

Chrome

### Keyboard name

EuroLatin (SIL)

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #11182

PR Description updated to reflect usage of JSON Objects for passing strings safely from Java to Javascript.
This follows the convention from KMKeyboard.setKeymanLanguage()
https://github.com/keymanapp/keyman/blob/c79487f706348a35ab538d00057d6e480e9d3d7b/android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java#L640-L658

In addition, a final URI.encode() is done on the entire string passed for the Javscript call
https://github.com/keymanapp/keyman/blob/c79487f706348a35ab538d00057d6e480e9d3d7b/android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java#L354-L355

This only affects Javascript calls with string parameters.

(original PR description)
~In the reported issue, backspace failed to work because the Java context length didn't match the Javascript context length because we weren't escaping `%` characters.
We already have special handling for literal `\`, `'`, and `\n` characters, so this adds escaping `%` .~

~I tried using URLEncoder and that went horribly wrong. We don't want to replace spaces with `+`, and all the `{` `}` characters passed to Javascript got mismatched.~

User Tests updated:

## User Testing
**Setup** - Install PR builds specified in the tests on an Android device/emulator

* **TEST_EDITING** - Verifies context can be edited and backspaced
1. Install the PR build of Keyman for Android and launch the app
2. From "Get Started", enable Keyman as the default system keyboard
3. Launch Chrome browser and select the text field
4. With Keyman sil_euro_latin system keyboard type in the textfield:
    a. Press and key and verify it gets inserted
    b. Long-press a key and verify it gets inserted
    c. Type more text, then move the cursor. Press a key and verify it gets inserted
    d. Type more text so suggestions appear. Press a suggestion and verify it gets inserted
5. Clear the Chrome text field
6. Copy and Paste the following long string into the text field (from the reported issue) 
`https://cdn.retailads.net/tc.php?t=151238C2287900209D&deepurl=https%3A%2F%2Fa.nonstoppartner.net%2Fa%2F%3Fi%3Dclick%26l%3Dde%26client%3Daldi%26camp%3Ddeep%26nw%3Dread%26deepid%3D101012640&subid=1712319X100149708X67035X29711X86818X181XtextlinkXyahl6byko6csX`
7. Press backspace key and verify the final character is deleted
8. Return to Keyman app, and open the Keyman settings -> adjust the spacebar caption
9. Verify the spacebar caption is updated accordingly

* **TEST_SPACEBAR_CAPTION** - Verifies special characters appear on spacebar caption
1. Install the PR build of the Android test app KeyboardHarness
2. In the KeyboardHarness app, longpress the globe key and select the `longpress '"\|5% +` keyboard (note the special characters)
3. On the OSK, verify the spacebar caption correctly shows `English - longpress '"\|5% +`
longpress

### CODE REVIEW

**Review by jahorton — APPROVED** [review]

**Review by srl295 — APPROVED** [review]

**Comment by mcdurdin** [comment]
> I tried using URLEncoder and that went horribly wrong. We don't want to replace spaces with `+`, and all the `{` `}` characters passed to Javascript got mismatched.

It's not appropriate for us to be rolling our own URL encoding -- so I think we need to do more work here. Note that these are _not_ query parameters that are being passed through. It's all a `javascript:` URI, and we may need to actually double-encode bits of this -- first of all for Javascript strings, and then for the URI encoding.

This bit needs to be encoded for Javascript strings (I would hope there is an existing Java library function we can use?), and then the `javascript:` concatenation should be using `URLEncoder`.

https://stackoverflow.com/a/10786112/1836776

**Comment by mcdurdin** [comment]
i.e.

```
 loadUrl("javascript:" + URLENCODE(allCalls.toString())); 
```

**Comment by darcywong00** [comment]
> It's not appropriate for us to be rolling our own URL encoding -- so I think we need to do more work here. Note that these are _not_ query parameters that are being passed through. It's all a `javascript:` URI, and we may need to actually double-encode bits of this -- first of all for Javascript strings, and then for the URI encoding.
> 
> This bit needs to be encoded for Javascript strings (I would hope there is an existing Java library function we can use?), and then the `javascript:` concatenation should be using `URLEncoder`.
> 
> https://stackoverflow.com/a/10786112/1836776

hmm - is the `KMString.format()` in l. 158 why we've had to do some DIY escaping?
https://github.com/keymanapp/keyman/blob/ab0d22539750f8fe09469db5272d4756c32fa03a/android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java#L150-L164

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_EDITING (PASSED):** Tested with the attached PR build (Keyman 17.0.307-beta-test-11206) on an Android 12 / API 31 emulator and here is my observation: 1. Set Keyman as the default system keyboard. 2. Launched Chrome browser. Selected the text field. 3. Followed the steps as mentioned in Step 4 and verified that pressing any letter key or long-pressed letter key or suggestion was inserted on the text field. 4. Cleared the Chrome text field. 5. Copied and then pasted the given link into the text field. 6. Pressed the backspace key and verified that the final character was deleted on the text field. Seems to be working as expected.

File: android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java [hunk 1]
```diff
@@ -149,13 +150,19 @@ protected void setShouldIgnoreSelectionChange(boolean ignore) {
...
+    JSONObject reg = new JSONObject();
     String kmText = "";
     if (text != null) {
-      kmText = text.toString().replace("\\", "\\u005C").replace("'", "\\u0027").replace("\n", "\\n");
+      // Use JSON to handle passing string to Javascript
+      try {
+        reg.put("text", text.toString());
+      } catch (JSONException e) {
+        KMLog.LogException(TAG, "", e);
+      }
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java:161]: We shouldn't be needing to catch this, I can't see any scenarios in which this could happen.

File: android/KMEA/app/src/main/assets/android-host.js [hunk 2]
```diff
@@ -230,10 +231,8 @@ function setNumericLayer() {
   }
 }
 
-function updateKMText(text) {
-  if(text == undefined) {
-      text = '';
-  }
+function updateKMText(k) {
+  var text = (k == undefined) || !k.text ? '' : k.text;
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/assets/android-host.js:235]: k should never be undefined. We should probably be logging if it is.

File: android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java [hunk 3]
```diff
@@ -1092,8 +1100,17 @@ public void reloadAfterError() {
...
-    String jsString = KMString.format("setSpacebarText('%s')", mode.toString());
-    loadJavascript(jsString);
+    JSONObject reg = new JSONObject();
+    if (mode != null) {
+      // Use JSON to handle passing string to Javascript
+      try {
+        reg.put("text", mode.toString());
+      } catch (JSONException e) {
+        KMLog.LogException(TAG, "", e);
+      }
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java:1110]: Again, shouldn't need to be catching these

**Review by mcdurdin — APPROVED** [review]
This looks fine, I wonder if we need to be wrapping the JSON exception possibilities?

File: android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java (hunk 1 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java:161]: The Gradle build fails if I remove these:

```
error: unreported exception JSONException; must be caught or declared to be thrown
       reg.put("text", text.toString());
```

Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java:161]: ah yeah okay

File: android/Tests/KeyboardHarness/app/src/main/assets/keyboardharness.kps [hunk 4]
```diff
@@ -20,13 +20,13 @@
...
     <File>
-      <Name>..\..\..\..\..\..\..\web\testing\chirality\chirality.js</Name>
+      <Name>..\..\..\..\..\..\..\web\src\test\manual\web\chirality\chirality.js</Name>
       <Description>File chirality.js</Description>
       <CopyLocation>0</CopyLocation>
       <FileType>.js</FileType>
     </File>
     <File>
-      <Name>..\..\..\..\..\..\..\web\testing\platform\platformtest.js</Name>
+      <Name>..\..\..\..\..\..\..\web\src\test\manual\web\platform\platformtest.js</Name>
```
[the remark this answers is not in the document]
Comment (mcdurdin) [reply android/Tests/KeyboardHarness/app/src/main/assets/keyboardharness.kps:29]: we should really avoid referencing files across projects like this (future issue)

File: android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java (hunk 1 above)
Comment (jahorton) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java:161]: Yep, that's Java for you.  Thou shalt declare all unhandled exceptions, one way or another.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_EDITING (PASSED):** Tested with the attached PR build (Keyman 17.0.307-beta-test-11206) on an Android 12 / API 31 emulator and here is my observation: 1. Set Keyman as the default system keyboard. 2. Launched Chrome browser and selected the text field. 3. Switched to sil_euro_latin system keyboard. Pressed any key and verified that it get inserted. 4. Long-pressed a key and verified that it gets inserted. 5. Typed more text, then moved the cursor. Pressed any key and verified that it gets inserted. 6. Typed more texts to appear suggestions. Pressed a suggestion and verified that it gets inserted. Cleared the Chrome text field. 7. Copied the given long string and pasted it in the text field. Pressed the backspace key and verified the final characters was deleted. 8. Returned to the Keyman app and adjusted the spacebar caption. Verified that the spacebar caption was updated accordingly. Seems to be working as expected.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_SPACEBAR_CAPTION (PASSED):** 1. Installed the PR build of the Android test app KeyboardHarness. 2. Got an error message after opening the KeyboardHarness app. 3. Long pressed the globe key and selected the longpress '"\|5% + keyboard. 4. Verified the spacebar caption correctly showed English - longpress '"\|5% + on the OSK. 

..error in opening the keyboard

   


..spacebar caption correctly showed

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.314-beta](https://keyman.com/downloads/releases/beta/17.0.314)
