### PR TITLE
Addresses cross-frame instanceof issues.

### LINKED ISSUE #544: IFrame attachment issues in Chrome
Regression: Some of the changes in #516 have resulted in IFrames not properly attaching when viewing pages in Google Chrome.

Source: https://stackoverflow.com/questions/43587286/why-does-instanceof-return-false-on-chrome-safari-and-edge-and-true-on-firefox

It's the `instanceof` operator, which is thus not safe to use across the `IFrame` boundary.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #544.

As speculated, #544's underlying issue is that, by convention, HTML-related JavaScript object classes are redefined within each `Window` - and `IFrame` elements support their own `Window` instance.  As a result, Chrome and Safari return `false` for simple `instanceof HTMLElement` checks on elements from within an `HTMLIFrameElement`.

Addressing this issue led to the development of a `Util.instanceof` function that can discern between `Window`, `Document`, any `Node` subclass, and any `Event` subclass.  Use of it _does_ require manual casts on branches dependent on the check, unlike the built-in `instanceof` operator, but it better covers our use cases.  This is only used where necessary - in particular, with the handling of `Event` objects, which can `target` any of the other types.  Elsewhere, `instanceof` code is checked against its containing Window's constructor for the type.

Additionally, an interesting bug was noted when testing with the EuroLatin2 keyboard that necessitated a bugfix when attached to an element in an iframe; the 'toggle' controller would jump to any 'key' pressed on the visual help displayed.

Tested on the following:
* Windows
    - Firefox
    - IE (9+, at least in compatibility mode)
    - Edge
    - Chrome
* Mac
    - Safari
* iOS (native mode)
    - Safari (no `IFrame` support, but it doesn't break KMW there)
* iOS (embedded)
    - Keyman app
* Android (native mode)
    - WebView browser
    - Chrome
* Android (embedded)
    - Keyman app

### CODE REVIEW

File: web/source/kmwdomevents.ts [hunk 1]
```diff
@@ -948,8 +951,8 @@ class DOMTouchHandlers extends DOMEventHandlers {
       target?: EventTarget;
     };
 
-    if(e instanceof TouchEvent) {
-        tEvent=e.touches[0];
+    if(Util.instanceof(e, "TouchEvent")) {
```
Comment (mcdurdin) [inline web/source/kmwdomevents.ts]: One thing we need to be careful of here is the current context - for an event on an element in an `iframe`, the context would be the iframe's `window` and not the parent document's `window`. We can still do `e instanceof e.target.ownerDocument.defaultView.MouseEvent` though, I think.

Comment (jahorton) [reply web/source/kmwdomevents.ts]: ?  How is this not mindful of the current context?  That's exactly what `Util.instanceof` is designed to address.

**Comment by jahorton** [comment]
OK, they have an existing issue I couldn't think of the right search term for:

https://github.com/Microsoft/TypeScript/issues/19816

They're not going to implement the global declarations.  :(

File: web/source/kmwbase.ts [hunk 2]
```diff
@@ -162,10 +162,11 @@ class KeymanBase {
       if(!e) {
         var elem: HTMLElement|Document = this.domManager.getLastActiveElement();
         if(elem) {
+          console.log("Hello world.");
```
Comment (mcdurdin) [inline web/source/kmwbase.ts]: I think this needs to die :)

File: web/source/kmwdom.ts [hunk 3]
```diff
@@ -720,15 +676,20 @@ class DOMManager {
    * @return      {Array<Element>}        A list of potentially-editable controls.  Further filtering [as with isKMWInput() and
    *                                      isKMWDisabled()] is required.
    */
-  _GetDocumentEditables(Pelem: HTMLElement|Document) {
+  _GetDocumentEditables(Pelem: HTMLElement|Document): (HTMLElement|Document)[] {
```
Comment (mcdurdin) [inline web/source/kmwdom.ts]: I think we could potentially make this clearer by defining something like: 

```
type DocumentEditableElement = HTMLInputElement | HTMLTextAreaElement | HTMLIFrameElement | Document;

_GetDocumentEditables(Pelem: DocumentEditableElement): DocumentEditableElement[] {
}
```

File: web/source/kmwdom.ts [hunk 4]
```diff
@@ -720,15 +676,20 @@ class DOMManager {
...
+    // Document.ownerDocument === null, so we better check that it's not null before proceeding.
+    if(Pelem.ownerDocument && Pelem instanceof Pelem.ownerDocument.defaultView.HTMLElement) {
+      var dv = Pelem.ownerDocument.defaultView;
+
+      if(Pelem instanceof dv.HTMLInputElement || Pelem instanceof dv.HTMLTextAreaElement) {
+        possibleInputs.push(Pelem);
+      } else if(Pelem instanceof dv.HTMLIFrameElement) {
+        possibleInputs.push(Pelem);
+      }
     } else if(Pelem.nodeName == "#text") {
```
Comment (mcdurdin) [inline web/source/kmwdom.ts]: Is this even possible if `Pelem` is a `HTMLElement` and not a `Node`?

File: web/source/kmwdom.ts (hunk 3 above)
Comment (mcdurdin) [reply web/source/kmwdom.ts]: I'm not sure if we need to go this deep for this PR, but it would clarify the inputs and outputs to define union types for this (ab)use of typing for the whole project; later we'll then be able to see the patterns of use.

File: web/source/kmwdomevents.ts [hunk 5]
```diff
@@ -1206,7 +1178,8 @@ class DOMTouchHandlers extends DOMEventHandlers {
     var e=DOMEventHandlers.states.lastActiveElement, s=null;
     if(e && e.className != null && e.className.indexOf('keymanweb-input') >= 0) {
       // Always copy text back to underlying field on blur
-      if(Util.instanceof(e.base, "HTMLTextAreaElement") || Util.instanceof(e.base, "HTMLInputElement")) {
+      if(e.base instanceof e.base.ownerDocument.defaultView.HTMLTextAreaElement
+          ||e.base instanceof e.base.ownerDocument.default.HTMLInputElement) {
```
Comment (mcdurdin) [inline web/source/kmwdomevents.ts]: `defaultView` not `default`

File: web/source/kmwdom.ts (hunk 3 above)
Comment (jahorton) [reply web/source/kmwdom.ts]: Yeah, I only just discovered the ability to use that pattern.  The thing is, though, we also return contentEditable elements of whatever type:  divs, spans, etc.

My preference would be to create a wrapper for each type - input, textarea, iframe, and contenteditable - that handles the DOM aspects for the particularities of each.  That'd be a PR after fixing up the OSK, though, which is way down the road.

File: web/source/kmwdom.ts (hunk 4 above)
Comment (jahorton) [reply web/source/kmwdom.ts]: Probably not; it's inherited there from legacy stuffs, and I was hesitant to cut it b/c of the current HTMLElement/Document ambiguities to be resolved in the future.  It's probably safe to kill, so sure, I'll nix it.
