### PR TITLE
fix(android): Sanitize version for API query

### LINKED ISSUE #2298: [android] Cloud keyboard searches incomplete for PR builds
On a PR build of the Android app, we noticed Khmer Angkor (khmer_angkor) wasn't available in the languages list.

This api.keyman.com query shows khmer_angkor missing:
https://api.keyman.com/cloud/4.0/keyboards?version=10.0.2127.pull.2281&device=androidphone&languageidtype=bcp47

Can we tweak the keyboard query to handle PR versions?

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #2298

Sanitize the app version to `#.#.#` to match the API query spec

## User Testing
- [ ] Test for presence of fv_sencoten keyboard
1. Load the PR test build
2. start Keyman
3. Go "Settings" --> "Languages" to bring up the language picker
4. Search for "Salish, Straits" / "SENĆOŦEN" keyboard and install
5. Return to language picker
6. Search for "SENĆOŦEN" / "SENĆOŦEN" keyboard and install (this is fv_sencoten version 9.1)

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java [hunk 1]
```diff
@@ -123,9 +125,18 @@ public void invalidateLexicalModelCache(@NonNull Context context) {
   {
     String deviceType = CloudDataJsonUtil.getDeviceTypeForCloudQuery(aContext);
 
+    // Sanitize appVersion to #.#.# to match the API spec
+    // Regex needs to match the entire string
+    String appVersion = BuildConfig.VERSION_NAME;
+    Pattern pattern = Pattern.compile("(\\d+\\.\\d+\\.\\d+).*");
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java]: Am I right in thinking that this could match anywhere in the string? Suggest adding a `^` to force start-of-string match.
```suggestion
    Pattern pattern = Pattern.compile("^(\\d+\\.\\d+\\.\\d+)");
```

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java]: The Matcher [documentation](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Matcher.html) says it will attempt to match the entire string with the Pattern. But I've gone ahead and added the starting anchor.

Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/CloudRepository.java]: Yes, I read that and thought it was ambiguous -- after all, a regex pattern match is always done against the entire string... So I decided to learn: https://code.sololearn.com/cVRUy2BwauK8 and you were right :) -- the `.*` is needed on the end and the `^` is not needed on the front. Ah consistency!
