### PR TITLE
fix(mac): check package fileVersion during install

### LINKED ISSUE #6253: bug(mac): test fileVersion during package install
> @mcdurdin I built a test keyboard with Developer 15 that has a longpress of U_xxxx_yyyy on a key. kmp.json has
> 
> ```
>     "fileVersion": "7.0"
> ```
> 
> Should fileVersion be 15.0 for Keyman 15 features?

Yes, with #6145, the `fileVersion` will be `"15.0"`. From the testing in that PR, we can see that we have to fix several platforms:

2. macOS - Silent failure to install? (@sgschantz)

I think we should try and fix this in 15.0 for better file safety going forward. Linux and macOS *should* test the .kmx version anyway at runtime, but it really should be blocked at install time.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/5992#issuecomment-1037584657_

### PR DESCRIPTION
**Pull request by keyman-server**
Fixes #6253. This will only show a message indicating failure to install but will not give a reason, which would require significantly more engineering.

# User Testing

Note, you may want to enable "Debug Logging" in Keyman Configuration / Options tab, and capture process:Keyman messages from Console, if there are issues completing these tests.

* **TEST_99:** Try installing package [the_99.kmp](https://downloads.keyman.com/developer/beta/15.0.219/keyboards/the_99.kmp). It should not be installable

* **TEST_KHMER:** Try installing Khmer Angkor -- it should install successfully

### CODE REVIEW

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_99 (PASSED):** Tested this with attached PR build in Mac OS (Monterey 12.3) and the Keyboard Installation failed. Seems to be working as expected. 

the_99 Keyman Package Failed:


* **TEST_KHMER (PASSED):** Tested this with the attached PR build in Mac OS and Khmer Angkor Keyboard Installed successfully. Seems to be working as expected. 

Khmer Angkor Keyboard has been downloaded and  Installed Successfully:

File: mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m [hunk 1]
```diff
@@ -1165,42 +1178,111 @@ - (void)postKeyboardEventWithSource: (CGEventSourceRef)source code:(CGKeyCode) v
...
+        NSLog(@"Unzipped file: %@", filePath);
+
+    BOOL didInstall = NO;
+
+    // Check the package info to ensure that we support this version
+    KMPackageInfo *packageInfo = [self loadPackageInfo:tempDestFolder];
+    if(packageInfo == nil) {
+        NSLog(@"Could not find kmp.json in %@", filePath);
+    } else {
+        NSString* requiredVersion = [packageInfo.fileVersion shortenedVersionNumberString];
```
Comment (darcywong00) [inline mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m:1225]: Is `packageInfo` the entire kmp.json file?
Would we be checking `packageInfo.system.fileVersion`?

File: mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m [hunk 2]
```diff
@@ -34,6 +34,19 @@
 
 NSString *const kKeymanKeyboardDownloadCompletedNotification = @"kKeymanKeyboardDownloadCompletedNotification";
 
+@implementation NSString (VersionNumbers)
+- (NSString *)shortenedVersionNumberString {
+    static NSString *const unnecessaryVersionSuffix = @".0";
```
Comment (sgschantz) [inline mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m:39]: It would be nice if this function name were a little more clear so we don't have to study the code to find out what it means by 'shortened'. (I don't know what you all think about function name length, but I prefer to read a long function name that is more representative of exactly what the code is doing rather than be compelled to read all the code.)
Also, it would be super helpful to have a comment that shows how an example version string would be shortened.

File: mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m [hunk 3]
```diff
@@ -1165,42 +1178,111 @@ - (void)postKeyboardEventWithSource: (CGEventSourceRef)source code:(CGKeyCode) v
     }
 }
 
+
+// TODO: This seriously needs to be refactored out of the app delegate and into
+//       a keyboard install module
```
Comment (sgschantz) [inline mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m:1183]: Aside from a complete refactoring, would it be possible to have some of the new version-check specific code be isolated to a separate function so that this one doesn't become more unwieldy?

**Review by sgschantz — APPROVED** [review]
this looks ok but I have a couple suggestions

File: mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m (hunk 1 above)
Comment (mcdurdin) [reply mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m:1225]: `packageInfo` is a translation of the file, not the raw json structure.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.228-beta](https://keyman.com/downloads/releases/beta/15.0.228)
