### PR TITLE
fix(common/models): prediction threshold when count is low, unintentional aliasing

### LINKED ISSUE #4743: bug(common/models): corrections partially broken
**Describe the bug**
A spot of aliasing with "keep" suggestions is causing unexpected side-effects within the context-tracking system part of the lm-layer.  The side effect that results is, unfortunately, quite nasty; certain correction types (like transpositions!) are completely broken as a result.  (Rule of thumb:  the 'graph edge' leading to the correction must have been computed in a previous pass, before the aliasing was able to affect the results.)

I've traced the issue to these two blocks:

https://github.com/keymanapp/keyman/blob/6c9fe2c9fe3cedfc9917c59867a4e83a8d300c88/common/predictive-text/worker/model-compositor.ts#L342-L346

In the block above, one of the suggestions was actually using the same `Transform` _instance_ as the keystroke that triggered the prediction.  Modifying that instance thus modified the keystroke's `Transform`... which naturally led to nasty side-effects.

https://github.com/keymanapp/keyman/blob/6c9fe2c9fe3cedfc9917c59867a4e83a8d300c88/common/predictive-text/worker/model-compositor.ts#L292-L300

The block above is the culprit.

**To Reproduce**
Seriously... just type a keystroke whenever a lexical model is active.  A breakpoint near the beginning of the method and at the end of the method will provide sufficient comparison.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes two bugs that were contributing to #4743.  In fact, after a bit more investigation...
Fixes #4743.

1. Generation of the 'keep' option was causing aliasing effects in the context-management system, causing issues with the search-algorithm's graph generation system.
2. The `bestCorrectionCost` thresholding parameter was being set in an inappropriate place, causing thresholding to be overzealously strict - especially closer to the start of words.

Furthermore...

3. Thresholding also neglected to consider a case where few predictions had been found before significant edits were required, a case that can arise from transposition typos or from accidental extra keystrokes.

Fixing all three of these points yields a much better prediction experience in certain early-word transposition scenarios.  Example "bxo" (instead of "box) has no good, near-neighbor fat-finger edits.  (Either 'a' or 'e' is the closest vowel to 'x', depending on press location, with both at very low probability for very precise keypresses on 'x'.)

Screen Shot 2021-03-23 at 9 21 32 AM

As it turns out, the ability to properly consider 'x' as an extra, unintended keystroke provides the bump needed for transpositions to be picked up properly on the next search layer.  (I verified this via debugger inspection, just to be certain.)  The core issue was, in fact, the overly-aggressive thresholding.

Worth noting:  for this example, the intended ("box") suggestion doesn't always appear; it seems that the algorithm's timeout sometimes triggers before the search considers the necessary search path.  Perhaps some sort of improvement that would cause that path to be considered earlier might be possible in the future?  (The bit about the 'traversal' limitation in the base issue's comments _might_ be a lead.)

### CODE REVIEW

File: common/predictive-text/worker/model-compositor.ts [hunk 1]
```diff
@@ -291,11 +298,21 @@ class ModelCompositor {
...
     if(!keepOption && keepOptionText != '') {
-      let keepTransform = models.transformToSuggestion(inputTransform, 1);  // 1 is a filler value; goes unused b/c is for a 'keep'.
+      // IMPORTANT:  duplicate the original transform.  Causes nasty side-effects
+      // for context-tracking otherwise!
+      let keepTransform: Transform = {
+        insert: inputTransform.insert,
+        deleteLeft: inputTransform.deleteLeft,
+        deleteRight: inputTransform.deleteRight,
+        id: inputTransform.id
+      };
```
Comment (mcdurdin) [inline common/predictive-text/worker/model-compositor.ts:308]: Can we just use a spread operator?

```suggestion
      let keepTransform: Transform = { ...inputTransform };
```

That also improves forward compat. Only danger: setters not called, if that's something to be concerned about?

File: web/source/osk/visualKeyboard.ts [hunk 2]
```diff
@@ -1055,6 +1055,11 @@ namespace com.keyman.osk {
       //        update their geometries to the actual display values, and use the results here.
       let touchKbdPos = this.getTouchCoordinatesOnKeyboard(touch);
       let layerGroup = this.kbdDiv.firstChild as HTMLDivElement;  // Always has proper dimensions, unlike kbdDiv itself.
+      let width = layerGroup.offsetWidth, height = layerGroup.offsetHeight;
+      // Prevent NaN breakages.
+      if(!width || !height) {
+        return null;
+      }
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:1062]: Is this a known issue that is being addressed here?

**Review by mcdurdin — APPROVED** [review]
I am a little nervous about the changes to the algorithm -- I don't have enough of a handle on the ins and outs of what is happening there to be confident of the improvement!

The `keepTransform` fix makes sense.

Just asking a question also about the other change!

File: web/source/osk/visualKeyboard.ts (hunk 2 above)
Comment (jahorton) [reply web/source/osk/visualKeyboard.ts:1062]: It showed up sometimes during my debugging runs, as I tested this one more proactively inside of iOS, rather than on the bootstrapping page.  Given that associated issues don't show up in Sentry, I'm guessing that it's something that arises due to the combination of breakpoint use and running within a `WKWebView`.  Unless Sentry's failing to capture it somehow?

So... it makes iOS testing a bit more stable.

----

Keep in mind, this scenario _should_ only arise if `layerGroup` isn't visible, but this method triggers on keystrokes _against `layerGroup`'s child elements_.  I, the user, am triggering keystrokes against the (visible) layer, yet the layer group's being reported invisible somehow?

I could make an issue about investigating this, I suppose.

Comment (jahorton) [reply web/source/osk/visualKeyboard.ts:1062]: Android isn't generating any associated errors for its embedded KMW, which would be expected if it weren't iOS-dependent.

iOS should also report unhandled console errors, so the fact that it _also_ hasn't had anything show up, suggests it's something that currently requires an Xcode debugging session.  I've tried reproducing sequences that caused the console errors I saw on my physical device, with error reporting on, and nothing shows up in Sentry.

Comment (jahorton) [reply web/source/osk/visualKeyboard.ts:1062]: Maaaybe I should run a test with Android + Android Studio debugging, to be sure it wouldn't arise there either.  Not sure if that info would be particularly useful at the moment though.

Comment (mcdurdin) [reply web/source/osk/visualKeyboard.ts:1062]: OK. It may be worth investigating one day if you are feeling bored!

**Comment by mcdurdin** [comment]
I note the LM Layer tests failed

**Comment by jahorton** [comment]
Oh right... use of the spread operator _would_ undo the need for the unit test change.  *sigh*

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.268-beta](https://keyman.com/downloads/releases/beta/14.0.268)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.21-alpha](https://keyman.com/downloads/releases/alpha/15.0.21)
