### PR TITLE
fix(windows): support kmxplus in mcompile 🙀 

### LINKED ISSUE #9064: feat(windows): support kmx-plus in mcompile 🙀
installing an ldml kmx file in current windows seems to mangle it.  File is 212 bytes instead of 10,680

- on the left is c:/programData/keyman/keyman\ engine/keyboard/k_010_mt/k_010_mt.kmx

- on the right is the k_010_mt.kmx that was originally installed (it's in c:/programData/keyman/keyman\ engine/keyboard/k_010_mt/k_010_mt.kmx or similar after a test build)

```
0000000 4b 58 54 53 00 10 00 00 00 00 00 00 00 00 00 00         0000000 4b 58 54 53 00 10 00 00 00 00 00 00 00 00 00 00
0000020 01 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00         0000020 01 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00
0000040 40 00 00 00 d4 00 00 00 ff ff ff ff ff ff ff ff       | 0000040 48 00 00 00 00 00 00 00 ff ff ff ff ff ff ff ff
0000060 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00         0000060 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000100 07 00 00 00 00 00 00 00 70 00 00 00 14 00 00 00       | 0000100 dc 00 00 00 bc 29 00 00 07 00 00 00 00 00 00 00
0000120 00 00 00 00 8e 00 00 00 24 00 00 00 00 00 00 00       | 0000120 78 00 00 00 14 00 00 00 00 00 00 00 96 00 00 00
0000140 b8 00 00 00 26 00 00 00 00 00 00 00 c4 00 00 00       | 0000140 24 00 00 00 00 00 00 00 c0 00 00 00 26 00 00 00
0000160 4d 00 61 00 6c 00 74 00 65 00 73 00 65 00 20 00       | 0000160 00 00 00 00 cc 00 00 00 4d 00 61 00 6c 00 74 00
0000200 34 00 37 00 2d 00 6b 00 65 00 79 00 00 00 31 00       | 0000200 65 00 73 00 65 00 20 00 34 00 37 00 2d 00 6b 00
0000220 37 00 2e 00 30 00 2e 00 31 00 32 00 30 00 2d 00       | 0000220 65 00 79 00 00 00 31 00 37 00 2e 00 30 00 2e 00
0000000 4b 58 54 53 00 10 00 00 00 00 00 00 00 00 00 00         0000000 4b 58 54 53 00 10 00 00 00 00 00 00 00 00 00 00
0000020 01 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00         0000020 01 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00
0000040 40 00 00 00 d4 00 00 00 ff ff ff ff ff ff ff ff       | 0000040 48 00 00 00 00 00 00 00 ff ff ff ff ff ff ff ff
0000060 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00         0000060 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000100 07 00 00 00 00 00 00 00 70 00 00 00 14 00 00 00       | 0000100 dc 00 00 00 bc 29 00 00 07 00 00 00 00 00 00 00
0000120 00 00 00 00 8e 00 00 00 24 00 00 00 00 00 00 00       | 0000120 78 00 00 00 14 00 00 00 00 00 00 00 96 00 00 00
0000140 b8 00 00 00 26 00 00 00 00 00 00 00 c4 00 00 00       | 0000140 24 00 00 00 00 00 00 00 c0 00 00 00 26 00 00 00
0000160 4d 00 61 00 6c 00 74 00 65 00 73 00 65 00 20 00       | 0000160 00 00 00 00 cc 00 00 00 4d 00 61 00 6c 00 74 00
```

### PR DESCRIPTION
**Pull request by srl295**
mcompile:
- copy keyboards if KMXPlus is detected
- give an error if -u is used on a KMXPlus file

@keymanapp-test-bot skip

Fixes #9064

### CODE REVIEW

File: windows/src/engine/mcompile/mcompile.cpp [hunk 1]
```diff
@@ -474,3 +487,8 @@ void LogError(PWSTR fmt, ...) {
 	fmtbuf[255] = 0;
   _putws(fmtbuf);
 }
+
+BOOL CopyKeyboard(PWSTR source, PWSTR target)
+{
+  return CopyFileW(source, target, FALSE /*overwrite*/);
```
Comment (mcdurdin) [inline windows/src/engine/mcompile/mcompile.cpp:493]:
```suggestion
  return CopyFile(source, target, TRUE /*overwrite*/);
```

I think we should use the same overwrite semantics that `SaveKeyboard` uses (it calls [`CreateFile`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea) with `CREATE_ALWAYS`).

We don't need the `W` suffix because we are compiling with `#define UNICODE`, and we are not using it in most other places.

**Review by mcdurdin — APPROVED** [review]
LGTM, minor nits. Love how we can be specific about our code review when the change is only a handful of lines!

https://twitter.com/iamdevloper/status/397664295875805184

File: windows/src/engine/mcompile/mcompile.cpp (hunk 1 above)
Comment (srl295) [reply windows/src/engine/mcompile/mcompile.cpp:493]: - I saw a warning without the W, but could have been intellisense getting confused.
- Is the target file expected to not already exist? I wasn't sure.

Comment (mcdurdin) [reply windows/src/engine/mcompile/mcompile.cpp:493]: Target file could exist for a reinstall or where there is install over broken earlier install (which has been known to happen). We are happy to clobber existing file in either situation.

Comment (srl295) [reply windows/src/engine/mcompile/mcompile.cpp:493]: yeah, the 3rd argument is `bFailIfExists` which needs to be `FALSE` for overwriting. Updated the comment, because I see how my previous comment might look like the _argument_ was 'overwrite' when it's the opposite.

Comment (mcdurdin) [reply windows/src/engine/mcompile/mcompile.cpp]: Ah ... yes, sorry my bad!
