### PR TITLE
fix(windows): When uninstalling, exit Keyman

### LINKED ISSUE #4185: bug(windows): Keyman is not shutting down in uninstall
**Describe the bug**

Keyman used to shut down when the uninstaller started, but starting in 14.0, it appears to not be doing so. This leaves the running Keyman in a very broken state.

**To Reproduce**

1. Start Keyman
2. Uninstall Keyman

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 20H2 x64 
 - Keyman version: 14.0.215-alpha

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4185.

Make sure Keyman is shut down during the uninstall so that it isn't left in a weird state with missing files. This also reduces the need for a reboot after uninstall.

### CODE REVIEW

File: windows/src/desktop/insthelp/main.pas [hunk 1]
```diff
@@ -46,7 +46,22 @@ implementation
...
+var
+  hwnd: THandle;
+const
+  KMC_StopProduct = 1;  // from UfrmKeyman7Main.pas
+begin
+  hwnd := FindWindow('TfrmKeyman7Main', nil);
+  if hwnd <> 0 then
+  begin
+    PostMessage(hwnd, WM_USER_ParameterPass, KMC_StopProduct, 0);
+    Sleep(1000); // We'll wait 1 second to give Keyman Engine time to shut down
```
Comment (jahorton) [inline windows/src/desktop/insthelp/main.pas:62]: Why not a polling loop?

I don't know Delphi, so something like the following pseudocode:

```
var
  iterationsUntilFail = 10;

  // ...

while hwnd <> 0 && iterationsUntilFail > 0
  begin
    PostMessage(hwnd, WM_USER_ParameterPass, KMC_StopProduct, 0);
    Sleep(1000);
    iterationsUntilFail--;
    hwnd := FindWindow('TfrmKeyman7Main', nil);
end;

// loop auto-exits after enough iterations have passed.

Comment (jahorton) [reply windows/src/desktop/insthelp/main.pas:62]: Right now, it looks like you're assuming that Keyman will always exit within that 1000ms timeframe without issue... which is a bit of an assumption.

Comment (mcdurdin) [reply windows/src/desktop/insthelp/main.pas:62]: Yep. So is 10 seconds, of course, but it's a bit more graceful. Internally, the destruction of the window does not guarantee that the process has shut down, but in normal circumstances, it will be gone very shortly thereafter. I think this is fine. In abnormal circumstances, well, not much we can do but let them restart...

File: windows/src/desktop/insthelp/main.pas [hunk 2]
```diff
@@ -52,14 +52,20 @@ implementation
...
   if hwnd <> 0 then
   begin
     PostMessage(hwnd, WM_USER_ParameterPass, KMC_StopProduct, 0);
-    Sleep(1000); // We'll wait 1 second to give Keyman Engine time to shut down
+    Counter := 0;
+    while (FindWindow('TfrmKeyman7Main', nil) <> 0) and (Counter < 10) do
+    begin
+      Sleep(1000); // We'll wait up to 10 seconds to give Keyman Engine time to shut down
+      Inc(Counter);
+    end;
```
Comment (jahorton) [inline windows/src/desktop/insthelp/main.pas:68]: If we want to be really forthright:

```
if Counter == 0 then
begin
    // Warn user that a restart may be necessary (b/c shutdown unconfirmed)
end
```

But it's probably fine as-is anyway.

**Review by jahorton — APPROVED** [review]

File: windows/src/desktop/insthelp/main.pas (hunk 2 above)
Comment (mcdurdin) [reply windows/src/desktop/insthelp/main.pas:68]: They'll be warned anyway by Windows Installer, so don't think we need to do it here.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.240-beta](https://keyman.com/downloads/releases/beta/14.0.240)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)
