### PR TITLE
[Android] Use lexical model package version for lexical model version

### LINKED ISSUE #2190: [Android] Lexical models fail to install because lexical model version no longer generated
**Describe the bug**
User reported issue from [community site](https://community.software.sil.org/t/installation-of-predictive-text-package-in-keyman-for-android/2649)

Lexical models built with Keyman Developer 12.0.50 stable no longer include lexical model versions (they use the lexical model package version).

However, the Android and iOS apps were developed to expect a lexical model version, so this is causing the new model packages to fail at installation.

(The published models on downloads.keyman.com/models haven't been updated with the new lexical model compiler so they currently contain model version info)

Install a Mozhi Malayalam keyboard for testing.

Testing with a model package built from
https://my.pcloud.com/publink/show?code=kZlX3LkZpVxg32Gpk4BRIGIW5M7hhBSpWXik

### Fix
The fix is to use the package version "info/version/description" for the lexical model version.
If package version doesn't exist, fall back to "1.0"

### Configuration
Keyman Developer 12.0.50 Stable
Keyman Android 12.0.4201 Stable

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #2190

For lexical model packages, use the package version for the lexical model version.

Keyboard packages will continue to use the keyboard versions in kmp.json.

Screenshot showing the installed lexical model
Screenshot_1570692301

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java [hunk 1]
```diff
@@ -420,6 +422,10 @@ public boolean accept(File pathname) {
     JSONObject newInfoJSON = loadPackageInfo(tempPath);
     String packageId = getPackageID(path);
 
+    // For lexical model packages, lexical model version is determined by the package version
+    // (Default to "1.0")
+    String packageVersion = getPackageVersion(newInfoJSON);
```
Comment (darcywong00) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java]: If you "Expand Up", you'll see this change is in the method `processKMP()`

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java]: `getPackageVersion()` also falls back to "1.0" if "version" isn't defined.
