### PR TITLE
fix(windows): start keymanx64 with ShellExecute

### LINKED ISSUE #5196: bug(windows): keymanx64 no longer starts since 15.0.43-alpha
**Describe the bug**

Keyman 15.0.43-alpha and later versions no longer start keymanx64.exe successfully, following #5002.

We are receiving the following error: `EOSError(740): Error starting keymanx64: System Error. Code: 740. The requested operation requires elevation` (KEYMAN-WINDOWS-5K). Procmon confirms the error.

However, if I start keymanx64 manually with the same parameters as passed from keyman.exe, it starts successfully, suggesting that the problem may be to do with the flags passed in to `CreateProcess`.

**To Reproduce**

1. Start Keyman.
2. Discover that keymanx64 is not running.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 
 - Keyman version: 15.0.43-alpha

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #5196.
Fixes KEYMAN-WINDOWS-5K.

It is complicated to start a `UIAccess=true` process with `CreateProcess`, so instead we'll use `ShellExecute`. This means passing a PID instead of a process handle to keymanx64.

I took the opportunity to refactor slightly the main function in keymanx64, as the failure modes were pretty WET.

### CODE REVIEW

File: windows/src/engine/keyman/UfrmKeyman7Main.pas [hunk 1]
```diff
@@ -1948,36 +1948,33 @@ procedure TfrmKeyman7Main.CreateWnd;
...
   try
-    FillChar(si, sizeof(TStartupInfoW), 0);
-    FillChar(pi, sizeof(TProcessInformation), 0);
-    si.cb := sizeof(TStartupInfo);
-    si.dwFlags := STARTF_USESHOWWINDOW;
-    si.wShowWindow := SW_HIDE;
-
-    if not DuplicateHandle(GetCurrentProcess, GetCurrentProcess,
-        GetCurrentProcess, @processHandle, 0, True, DUPLICATE_SAME_ACCESS) then
+    // TODO: use TKeymanPaths to find keymanx64?
```
Comment (rc-swag) [inline windows/src/engine/keyman/UfrmKeyman7Main.pas:1957]: Shouldn't this TODO be removed since you didn't use TKeymanPaths?

Comment (mcdurdin) [reply windows/src/engine/keyman/UfrmKeyman7Main.pas:1957]: It's a low-priority TODO for the future 😁

**Review by rc-swag — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.60-alpha](https://keyman.com/downloads/releases/alpha/15.0.60)
