### PR TITLE
fix(web): Don't throw errors after detach

### LINKED ISSUE #10031: bug(web): `detachFromControl` causes subsequent hardware keystrokes to throw an error
### Describe the bug

If you call `detachFromControl` on an element in a webpage, then subsequently type with the hardware keyboard into that element, the following error is raised:

```
Uncaught TypeError: Cannot read properties of null (reading 'interface')
    at Ue (outputTargetForElement.ts:45:31)
    at he (outputTargetForElement.ts:11:10)
    at l._KeyDown (hardwareEventKeyboard.ts:301:20)
```

This appears to be a regression in 17.0, because I cannot repro with 16.0.142.

### Reproduce the bug

The following page was sufficient to reproduce the problem.

1. Click in the textarea, type, see that Keyman is not active.
2. Click Attach button, type again into text area, see that Keyman is active (may need to switch to Thai keyboard in KeymanWeb to prove)
3. Click Detach button, type again into text area, see that Keyman is not active, but error is raised on each keystroke.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>

    <!-- Set the viewport width to match iOS device widths -->
    <meta name="viewport" content="width=device-width,user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />

    <title>detachFromControl</title>

    <!-- <script src='https://s.keyman.com/kmw/engine/16.0.142/keymanweb.js'></script>
    <script src='https://s.keyman.com/kmw/engine/16.0.142/kmwuitoggle.js'></script> -->
    <script src='https://s.keyman.com/kmw/engine/17.0.213/keymanweb.js'></script>
    <script src='https://s.keyman.com/kmw/engine/17.0.213/kmwuitoggle.js'></script>
    <script>
      (function(kmw) {
        kmw.init({attachType:'manual'});
        kmw.addKeyboards('@en'); // Loads default English keyboard from Keyman Cloud (CDN)
        kmw.addKeyboards('@th'); // Loads default Thai keyboard from Keyman Cloud (CDN)
      })(keyman);
    </script>

  </head>

<body>

  <textarea id="ta1" style="width:80%; height: 200px"></textarea>
  <br>
  <button id="attach">Attach</button>
  <button id="detach">Detach</button>

  <script>
    const ta1 = document.getElementById('ta1');
    document.getElementById('attach').addEventListener('click',() => {
      keyman.attachToControl(ta1);
      ta1.focus();
    });
    document.getElementById('detach').addEventListener('click',() => {
      keyman.detachFromControl(ta1);
      ta1.focus();
    });

  </script>
</body>
</html>
```

### Expected behavior

_No response_

### Related issues

_No response_

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [X] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.213-alpha

### Operating system

Windows 10

### Device

_No response_

### Target application

_No response_

### Browser

Chrome 119.0.6045.124 

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ermshiperete**
Fixes #10031.

# User Testing

## Preparations

**TEST_FIXED**: follow the repro instructions in #10031 to test if this is fixed. You can use the ["KeymanWeb Sample Page - Tests the new Attachment/Enablement API functionality"](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/426988:id/src/test/manual/web/attachment-api/index.html?mode=auto) (in manual mode) instead of the code listed in #10031.

### CODE REVIEW

**Comment by mcdurdin** [comment]
These changes look like they address the symptom and are good failsafes to include, but not sure if they are addressing the root cause -- we shouldn't be receiving events on the elements at all once we detach.

File: web/src/app/browser/src/hardwareEventKeyboard.ts [hunk 1]
```diff
@@ -335,7 +335,7 @@ export default class HardwareEventKeyboard extends HardKeyboard {
   _KeyUp: (e: KeyboardEvent) => boolean = (e) => {
     const target = eventOutputTarget(e);
     var Levent = preprocessKeyboardEvent(e, this.processor, this.hardDevice);
-    if(Levent == null) {
+    if(Levent == null || target == null) {
```
Comment (jahorton) [inline web/src/app/browser/src/hardwareEventKeyboard.ts:338]: If `target == null` here, that in itself is an error we should probably log in some manner.  The keystroke handler should only activate for elements that are currently in an attached & enabled state.

The attachment engine is supposed to ensure that the handler is only set for such elements, removing an element's event listeners when not attached.  I feel like this change only masks the actual error.

File: web/src/engine/attachment/src/outputTargetForElement.ts [hunk 2]
```diff
@@ -40,6 +40,10 @@ export function outputTargetForElement(Ltarg: HTMLElement) {
     }
   }
 
+  if (Ltarg._kmwAttachment == null) {
+    return null;
+  }
+
   // Step 2:  With the most likely host element determined, obtain the corresponding OutputTarget
   // instance.
   return Ltarg._kmwAttachment.interface;
```
Comment (jahorton) [inline web/src/engine/attachment/src/outputTargetForElement.ts:49]: A null / undefined check here is pretty reasonable.  We can make it a bit more compact, though.

```suggestion
  // Step 2:  With the most likely host element determined, obtain the corresponding OutputTarget
  // instance.
  return Ltarg._kmwAttachment?.interface;
```

**Review by jahorton — COMMENTED** [review]
IMO, this only masks #10031 - it does not actually fix it.  I'd prefer something that actually fixes the root of the problem (in addition to warning about there _being_ a problem if it arises at the point of the current would-be fix).

**Comment by mcdurdin** [comment]
> IMO, this only masks #10031 - it does not actually fix it

In other words, you are agreeing with [my comment](https://github.com/keymanapp/keyman/pull/10086#issuecomment-1832794568) :grin:

**Comment by jahorton** [comment]
Thought I'd look for a pointer for you.

This codeblock should be highly-relevant:  https://github.com/keymanapp/keyman/blob/d08453862262a12f4caad6606f849892fca7e263/web/src/app/browser/src/hardwareEventKeyboard.ts#L254-L283

For "some reason," the `'disabled'` event handler isn't getting called when the 'detach' button from the repro page is clicked.  That's the core of the bug.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_FIXED (PASSED):** Tested with the attached KeymanWeb Sample page in the Chrome browser and here is my observation: 1. Followed the steps as mentioned in #10031. 2. When typing in the text area, the Keyman is not active. 3. Then, clicked the Attach button. Again typed in the text area, this time I could see Keyman is active. 4. Clicked the Detach button. Typed again into the text area, this time Keyman was not active. But, I did not see any error message during this process. Seems to be working as expected.

..Text Area 1

   

..text area after clicking the Attach button

   

..text area after clicking the Detach button

File: web/src/app/browser/src/hardwareEventKeyboard.ts (hunk 1 above)
Comment (ermshiperete) [reply web/src/app/browser/src/hardwareEventKeyboard.ts:338]: So should I remove the `target == null` check again so that we see the error on the console? Or how should we log?

**Review by jahorton — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.221-alpha](https://keyman.com/downloads/releases/alpha/17.0.221)
