### PR TITLE
[Android] Validate keyboard ID when downloading keyboard from Keyman cloud

### LINKED ISSUE #1120: [Android] Validate keyboard ID before downloading keyboard
cf sillsdev/keyman-keyman.com#184

When trying to download a Cheyenne keyboard **EuroLatin (SIL)**, the cloud endpoint is returning an array of keyboards, so `sil_cheyenne` incorrectly gets installed.

As a sanity check, we should validate the keyboard ID when downloading a keyboard.

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #1120 

Instead of downloading the first keyboard returned by the Keyman cloud 3.0 API, validate that the keyboard matches the keyboard ID before downloading.

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java [hunk 1]
```diff
@@ -267,7 +267,15 @@ protected int downloadNonKMPKeyboard(String remoteUrl) throws Exception {
           throw new Exception(exceptionStr);
         }
 
-        keyboard = keyboards.getJSONObject(0);
+        // In case keyboards array contains multiple keyboards, get the one with matching keyboard ID
+        int index = 0;
+        while (index < keyboards.length()) {
```
Comment (tombogle) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: Is there a reason why this isn't just a for loop?
