### PR TITLE
[Mac] Fixes #894 - Fixed invocation of keyAction (missing self param)

### LINKED ISSUE #894: [Mac] Exception: NSInvalidArgumentException (probably memory problem)
Fatal Exception: NSInvalidArgumentException
-[__NSTaggedDate key]: unrecognized selector sent to instance 0x____

NSTaggedDate is a private type. From what I read on-line, is is almost certainly a memory management issue, where a pointer is referring to a memory location now occupied by a different object. There is one place (in resetKeyLabels) in Keyman engine where we use the 'key' selector to attempt to retrieve the key from a KeyView, so I'm guessing that is the source of this crash.
The call stack looks like this, but (currently) we don't have the symbols available for the Keyman engine code, so it's not very helpful.

0 | CoreFoundation | (Missing)
-- | -- | --
1 | libobjc.A.dylib | (Missing)
2 | CoreFoundation | (Missing)
3 | CoreFoundation | (Missing)
4 | CoreFoundation | (Missing)
5 | KeymanEngine4Mac | (Missing)
6 | KeymanEngine4Mac | (Missing)
7 | KeymanEngine4Mac | (Missing)
8 | AppKit | (Missing)
9 | AppKit | (Missing)
10 | AppKit | (Missing)
11 | AppKit | (Missing)
12 | AppKit | (Missing)
13 | Keyman | main.m line 21main

### PR DESCRIPTION
**Pull request by tombogle**
Finally a real solution!!!

### CODE REVIEW

File: mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m [hunk 1]
```diff
@@ -232,17 +232,14 @@ - (void)mouseUp:(NSEvent *)theEvent {
 }
 
 -(void)processKeyClick {
-    ((void (*)(id, SEL))[self.target methodForSelector:self.action])(self.target, self.action);
+    SEL selector = self.action;
+    IMP imp = [self.target methodForSelector:selector];
+    void (*func)(id, SEL, id) = (void *)imp;
```
Comment (mcdurdin) [inline mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m]: I guess hard casting a function prototype caused this problem in the first place. Is there any way we can avoid a hard cast, or document it more clearly?

Comment (tombogle) [reply mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m]: I talked to ChrisH about it and he suggested that there were probably several better approaches. I agree. As it is I only barely understand this code, and given where were are in the game, I was reluctant to try anything more aggressive.
