### PR TITLE
fix(web): keyboardchange event should defer until successful

### LINKED ISSUE #5730: bug(web): when a keyboard is activated it may not be reflected in `.activeKeyboard` if not yet loaded
**Describe the bug**

It is possible to call `setActiveKeyboard()` for a keyboard that is registered but not yet loaded. In that situation, an event handler on `kmw.keyboardchange` that calls `keyman.getActiveKeyboard()` will find that it does not match the keyboard passed in to the event handler.

**Expected behavior**

The keyboard should be marked as active in KeymanWeb at the time that the event handler is called.

**Screenshots**

This log shows the current behaviour, logging parameter passed in to the event, result of `keyman.getActiveKeyboard()` and `keyman.core.activeKeyboard`:

```
keyboardregistered:{"internalName":"Keyboard_khmer_angkor","language":"khmer_angkor","keyboardName":"khmer_angkor","languageCode":"en"} [active=;undefined]
keyboardchange:{"internalName":"Keyboard_khmer_angkor","languageCode":"en","indirect":false} [active=;null]
keyboardregistered:{"internalName":"Keyboard_nko","language":"nko","keyboardName":"nko","languageCode":"en"} [active=;null]
keyboardloaded:{"keyboardName":"Keyboard_khmer_angkor"} [active=;null]
keyboardloaded.afterTimeout:{"keyboardName":"Keyboard_khmer_angkor"} [active=Keyboard_khmer_angkor;[object Object]]
```

Note also how even on the `keyboardloaded` event, we don't get the active keyboard set; only after control returns (a 10ms timeout) do we see the correct value.

---

**KeymanWeb:**
 - OS: any 
 - Browser: any 
 - KeymanWeb Version: 15.0

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #5730.

A `kmw.keyboardchange` event should only occur once the keyboard has been successfully changed.  For initial loads of a keyboard, this is an asynchronous process - so it must interact with the `Promise` system.  Fortunately, `Promise`s (and our `setActiveKeyboard()` implementations of them) make this fairly simple.

Note that it _is_ currently expected that on a keyboard's first load, `beforekeyboardchange` will be called twice - once for the initial change attempt, then another once the keyboard's script has actually been loaded:

https://github.com/keymanapp/keyman/blob/bb4887387729a2ea5761e4e0d7d19c118eac6d9f/web/source/keyboards/kmwkeyboards.ts#L753-L757

(More context may prove useful, but I didn't want it to overwhelm this description.)

------

To facilitate testing these changes, I've made modifications to the old Promise API test page for Web.  In particular, check out this new zone of the page:

Screen Shot 2022-04-18 at 10 22 44 AM

The text box and button will only display under two conditions:
- Logging has been enabled
- Existing log text (once disabled) has not been cleared.

------

# User Testing

First, please note the details above regarding the "Promise API testing" page.  We'll be using that for these tests.
- Also known as `web/testing/promise-api`.

Feel free to use your preferred desktop browser for these tests.  Any one of the following should do:
- Edge
- Firefox
- Chrome
- Safari

## Actual Tests

- TEST_FIRST_LOAD:  Tests the initial load of a keyboard, which is performed asynchronously.

  1.  Enable event logging.  Be sure the logging text area and "Clear Event Logs" button appear.
  2. Click the text area beneath the text "Type in your language in this text area".
      - Do not fail this test if log entries appear at this step.
  3. Use the keyboard selection menu to swap to "French - French".
  
  Expected result:
  
  ```
  beforekeyboardchange: {"internalName":"Keyboard_french","languageCode":"fr"}
  - active keyboard: Keyboard_us
  keyboardloaded: {"keyboardName":"Keyboard_french"}
  - active keyboard: 
  beforekeyboardchange: {"internalName":"Keyboard_french","languageCode":"fr"}
  - active keyboard: 
  keyboardchange: {"internalName":"Keyboard_french","languageCode":"fr","indirect":false}
  - active keyboard: Keyboard_french
  ```

  Again, do not fail the test if there are extra lines before these as a result of step 2.  Simply ensure that the final lines of the log match the lines shown above, in this order.

- TEST_SECOND_LOAD:  Tests subsequent loads of a keyboard, which should occur synchronously.

  1.  If enabled, **disable** event logging.  "Clear" the logs if the logging text area does not disappear.
  2. Click the text area beneath the text "Type in your language in this text area".
  3. Use the keyboard selection menu to swap to "French - French".
  5. Use the keyboard selection menu to swap to "English - English".
  6. **Now** enable event logging.  Be sure the logging text area and "Clear Event Logs" button appear.
  7. Click the text area beneath the text "Type in your language in this text area".
      - Do not fail this test if log entries appear at this step.
  8. Use the keyboard selection menu to swap to "French - French".
  
  Expected result:
  
  ```
  beforekeyboardchange: {"internalName":"Keyboard_french","languageCode":"fr"}
  - active keyboard: Keyboard_us
  keyboardchange: {"internalName":"Keyboard_french","languageCode":"fr","indirect":false}
  - active keyboard: Keyboard_french
  ```
  
  Again, do not fail the test if there are extra lines before these as a result of step 7.  Simply ensure that the final lines of the log match the lines shown above, in this order.

### CODE REVIEW

**Comment by mcdurdin** [comment]
Please rebase to or merge latest beta branch -- that will fix the iOS build.

**Comment by mcdurdin** [comment]
> Note that it _is_ currently expected that on a keyboard's first load, `beforekeyboardchange` will be called twice - once for the initial change attempt, then another once the keyboard's script has actually been loaded

This sounds like a caveat that should be in the documentation for this event -- especially if we don't plan to change this.

File: web/source/keyboards/kmwkeyboards.ts [hunk 1]
```diff
@@ -477,7 +477,12 @@ namespace com.keyman.keyboards {
       // if(!PLgCode && (<KeymanBase>keymanweb).keyboardManager.activeStub) {
       //   PLgCode = (<KeymanBase>keymanweb).keyboardManager.activeStub['KLC'];
       // }
-      this.doKeyboardChange(PInternalName, PLgCode);
+      let _this = this;
```
Comment (mcdurdin) [inline web/source/keyboards/kmwkeyboards.ts:480]:
```suggestion
      const _this = this;
```

Let's go with using `const` where possible :grin: -- it transpiles down to `var` anyway...

File: web/source/keyboards/kmwkeyboards.ts [hunk 2]
```diff
@@ -477,7 +477,12 @@ namespace com.keyman.keyboards {
...
+      p.then(function() {
+        // Only mark the keyboard as having changed once the setActiveKeyboard op
+        // is successful.
+        _this.doKeyboardChange(PInternalName, PLgCode);
+      })
```
Comment (mcdurdin) [inline web/source/keyboards/kmwkeyboards.ts:485]:
```suggestion
      p.then(function() {
        // Only mark the keyboard as having changed once the setActiveKeyboard op
        // is successful.
        _this.doKeyboardChange(PInternalName, PLgCode);
      });
```

Is there a difference with `this` if we use an arrow function here? (Something that's still a little fuzzy in my mind)

File: web/testing/promise-api/eventLogging.js [hunk 3]
```diff
@@ -0,0 +1,49 @@
+function attachLoggingEvents() {
+
+  keyman.addEventListener('beforekeyboardchange', beforeChange);
+  keyman.addEventListener('keyboardchange', change);
+  keyman.addEventListener('keyboardloaded', loaded);
+  keyman.addEventListener('keyboardregistered', registered);
+}
+
+function appendLog(logText) {
+  if(this.loggingElement === undefined) {
```
Comment (mcdurdin) [inline web/testing/promise-api/eventLogging.js:10]: `this` is a little ambiguous here. It could be `window` or it could be `keyman.xxx` it seems because it depends on the caller. Can we just make `loggingElement` a global in this script?

File: web/testing/promise-api/index.html [hunk 4]
```diff
@@ -36,15 +38,41 @@
...
+
+        loggingDiv.style.display = active || hasLoggingText ? 'block' : 'none';
+      }
+
+      function flushLogs() {
+        const loggingElement = document.getElementById('eventLogging');
+        loggingElement.value = '';
+
+        eventLogChange();
+      }
```
Comment (mcdurdin) [inline web/testing/promise-api/index.html:74]: Can we put this new js in eventLogging.js? It seems to belong there?

File: web/testing/promise-api/index.html [hunk 5]
```diff
@@ -53,12 +81,26 @@
       }).then(function() {
         loadKeyboards();
       });
+
+      function onLoad() {
```
Comment (mcdurdin) [inline web/testing/promise-api/index.html:85]: Can we go with `window.addEventListener('load')` instead of `body.onload`? And then this also probably belongs in eventLogging.js yes?

**Review by mcdurdin — APPROVED** [review]
LGTM.

A few nits on the test page, mostly around structure which hopefully makes maintenance easier in the future?

File: web/source/keyboards/kmwkeyboards.ts (hunk 2 above)
Comment (jahorton) [reply web/source/keyboards/kmwkeyboards.ts:485]: The issue is that within the anonymous function, `this` refers to the Promise that will be resolving, if my understanding is correct - not the current class.  Hence `const _this = this;` beforehand.

File: web/testing/promise-api/eventLogging.js (hunk 3 above)
Comment (jahorton) [reply web/testing/promise-api/eventLogging.js:10]: I... uh... we could.  Not usually one for unnecessary globals though... and I lifted this trick from you:

https://github.com/keymanapp/keyman/blob/bb4887387729a2ea5761e4e0d7d19c118eac6d9f/web/source/osk/oskKey.ts#L265-L295

Granted... yeah, encapsulation isn't so much a concern for the test page.

File: web/testing/promise-api/index.html (hunk 4 above)
Comment (jahorton) [reply web/testing/promise-api/index.html:74]: I thought about it, but decided against it because this one deals far more directly with the UI aspects, whereas those are about the event interception and logging aspects.  Like, both are completely page-UI focused.

Still, totally can move it if you'd prefer; it is admittedly more code inlined on the main page.

File: web/testing/promise-api/index.html (hunk 5 above)
Comment (jahorton) [reply web/testing/promise-api/index.html:85]: I decided against that in part for the review process; some of the "removed code" was moved into this function.  As it's harder to track changes across files, and also because that code was part of the page's UI management, I left it.

Though, now that you've reviewed it and are comfortable with the changes, it'll be less of a jump to move it now if preferred.

**Comment by bharanidharanj** [comment]
* **TEST_FIRST_LOAD (PASSED):** Tested this in Chrome, Mozilla Firefox in Windows 10 OS & Safari in Mac OS and  it seems to be working as expected. Note: Not able to test it in Edge browser since it does not open the right page.   

First Load in Chrome:
 



* **TEST_SECOND_LOAD (PASSED):** Tested this in Chrome, Mozilla Firefox in Windows 10 OS & Safari in Mac OS and  it seems to be working as expected. Note: Not able to test it in Edge browser since it does not open the right page.  

Second Load in Chrome:

File: web/testing/promise-api/eventLogging.js (hunk 3 above)
Comment (jahorton) [reply web/testing/promise-api/eventLogging.js:10]: Ah, I'd have had to do it more directly on the function to do the 'trick' right.

Comment (mcdurdin) [reply web/testing/promise-api/eventLogging.js]: :grin: Changes LGTM as encapsulation is not important here as you noted.

File: web/testing/promise-api/index.html (hunk 4 above)
Comment (mcdurdin) [reply web/testing/promise-api/index.html]: I like the reorg. Less inline code is better.

File: web/source/keyboards/kmwkeyboards.ts (hunk 2 above)
Comment (mcdurdin) [reply web/source/keyboards/kmwkeyboards.ts]: The reason I asked about arrow functions is that [they inherit `this` from the lexical scope](https://www.codementor.io/@dariogarciamoya/understanding-this-in-javascript-with-arrow-functions-gcpjwfyuc) (so much more sensibler). [more yada-yada that may be relevant](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)!

Comment (jahorton) [reply web/source/keyboards/kmwkeyboards.ts]: Oh, interesting.  I do remember issues with TS arrow-function compilation, though - I feel like they had an issue with certain older browsers we still aim to support.  I can't point to anything specific, though.
