### PR TITLE
fix(web): prevents selection-clear for pure layer-switching multitaps

### LINKED ISSUE #11230: bug(web): layer-switching key multitaps clear selected text
From https://community.software.sil.org/t/keyman-17-0-beta-release/8388/23:

> If you select text, and double-tap (with the intention of switching to CAPS LOCK layer) the selected text gets deleted. Switching to other layers (default, shift, alt, num) does not delete the selected text.

Confirmed on my personal device, and I'm pretty sure I know the cause - I forgot to filter the multitap-rewind mechanism when the only thing changed is the layer.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #11230.

Previously, we _always_ cleared the selection as part of resetting the context-state for multitaps.  Problem is... that has unwanted cross-effects if the _only_ thing the multitap is doing is to layer-switch.

It's possible to shorten the changes with a "naive" fix, but naive solutions don't account for potential deadkey solutions very well.  I figure it's best to nip all such issues in the bud now, especially since I don't think there are related preventative warnings and/or errors for keyboard developers in Developer.

## User Testing

Any Web-based touch-platform will suffice for these tests.

**TEST_CAPS_WITH_SELECTION**:  Verify that selected text is not erased when double-tapping SHIFT to enter a keyboard's caps-lock state.  (A direct repro attempt for #11230.)

**TEST_MULTITAP_ROTA**: Using a keyboard with multitap keys that output text, verify that the output text is properly replaced on each tap.
- `ye_old_ten_key` and `diacritic_rota` from https://jahorton.github.io/ should work.

### CODE REVIEW

File: common/web/input-processor/src/text/inputProcessor.ts [hunk 1]
```diff
@@ -107,8 +107,20 @@ export default class InputProcessor {
       if(keyEvent.baseTranscriptionToken) {
         const transcription = this.contextCache.get(keyEvent.baseTranscriptionToken);
         if(transcription) {
-          // Restores full context, including deadkeys in their exact pre-keystroke state.
-          outputTarget.restoreTo(transcription.preInput);
+          // Has there been a context change at any point during the multitap?  If so, we need
+          // to revert it.  If not, we assume it's a layer-change multitap, in which case
+          // no such reset is needed.
+          if(!isEmptyTransform(transcription.transform) || !transcription.preInput.isEqual(Mock.from(outputTarget))) {
```
Comment (jahorton) [inline common/web/input-processor/src/text/inputProcessor.ts:113]: Why both?

1. `transcription.transform` (and in fact, `transcription` in general) does not provide any indication of deadkey changes.
2. While certainly "bad keyboard design", there's nothing preventing a multitap component of a layer-switch key from manipulating the context.  Should that occur, the correct thing to do is still to rewind the context.

Note that it is _technically_ possible to have altered the context since the base tap... but if the current context state matches the original one anyway, there's no need to perform a reset - we've already done the rewind in one manner or other.

----

We're only safe to bypass the context-rewind mechanism if there truly has been _no_ change to the context whatsoever.  Deadkey changes are context changes, and to handle them requires the some of the special handling newly added by this PR.

File: common/web/keyboard-processor/src/text/outputTarget.ts [hunk 2]
```diff
@@ -446,6 +446,18 @@ export class Mock extends OutputTarget {
...
+  /**
+   * Indicates if this Mock represents an identical context to that of another Mock.
+   * @param other
+   * @returns
+   */
+  isEqual(other: Mock) {
+    return this.text == other.text
+      && this.selStart == other.selStart
+      && this.selEnd == other.selEnd
+      && this.deadkeys().equal(other.deadkeys());
```
Comment (jahorton) [inline common/web/keyboard-processor/src/text/outputTarget.ts:458]: If someone goes and makes a multitap key that only does deadkey stuff, the final check is required to be able to rewind deadkey manipulations.  Otherwise, we'd get a lot of excess deadkeys during such a multitap due to not erasing deadkeys from taps before the final one.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_CAPS_WITH_SELECTION (PASSED):** Tested with the attached PR build (Keyman 17.0.309-beta-test-11232) on an iPhone 13 mobile device and here is my observation: 1. Opened the Keyman In-app. 2. Entered some texts. 3. Selected a word from it. 4. Double-tapped the Shift key and verified that the selected word still appeared on the text input screen. Seems to be working as expected.

**Review by mcdurdin — APPROVED** [review]
LGTM

**Comment by bharanidharanj** [comment]
@jahorton Tested the same in an Android 13 Mobile and it seems to be working as expected.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.309-beta](https://keyman.com/downloads/releases/beta/17.0.309)
