### PR TITLE
fix(android/app): Check Play Store release notes less than 500 chars

### LINKED ISSUE #5533: bug(android): release notes too long for Play Store
**Describe the bug**

Release build 15.0.90 failed for Android because release notes were too long (546 chars instead of 500). We need a way to reduce the release note content (perhaps making it static?)

https://build.palaso.org/viewLog.html?buildId=283126&buildTypeId=KeymanAndroid_Build&tab=buildLog

```
[08:32:13][Step 5/6] Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
[08:32:13][Step 5/6] POST https://androidpublisher.googleapis.com/androidpublisher/v3/...
[08:32:13][Step 5/6] {
[08:32:13][Step 5/6]   "code": 403,
[08:32:13][Step 5/6]   "errors": [
[08:32:13][Step 5/6]     {
[08:32:13][Step 5/6]       "domain": "global",
[08:32:13][Step 5/6]       "message": "The release created has notes in language en-US with length 546, which is too long (max: 500).",
[08:32:13][Step 5/6]       "reason": "forbidden"
[08:32:13][Step 5/6]     }
[08:32:13][Step 5/6]   ],
[08:32:13][Step 5/6]   "message": "The release created has notes in language en-US with length 546, which is too long (max: 500).",
[08:32:13][Step 5/6]   "status": "PERMISSION_DENIED"
[08:32:13][Step 5/6] }
```

---

**Keyman for iPhone/iPad/Android:**
 - Device: n/a 
 - OS: n/a 
 - Keyman version: 15.0.90

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #5533 

#5132 copied `whatsnew.md` to use as Play Store release notes. However, there's a 500 character limit.

This updates `build-help.sh` to: 
* Only use lines starting with `*` or indented `*`
* Check the character count < 500. If more, then add a general note `* Additional bug fixes and improvements`

### CODE REVIEW

**Comment by mcdurdin** [comment]
Could we have it instead just copy full `*` lines until we have ~ `500 chars - len('additional bug fixes and improvements')`, and append that?

**Comment by darcywong00** [comment]
> Could we have it instead just copy full `*` lines until we have ~ `500 chars - len('additional bug fixes and improvements')`, and append that?

OK, I've modified the Bash script to copy a line at a time (still parsing for lines that start with `*`).

File: android/build-help.sh [hunk 1]
```diff
@@ -117,4 +117,23 @@ if [ $TIER = "stable" ]; then
...
+for line in $FILTERED_LINES
+do
+  CHARS_IN_RELEASE_NOTES=$( wc -m < $PLAY_RELEASE_NOTES )
+  CHARS_IN_CURRENT_LINE=$( wc -m <<< $line )
+  if (( CHARS_IN_RELEASE_NOTES + CHARS_IN_CURRENT_LINE + 1 < 450 )); then
+    # Copy line to Play Store release notes
+    echo $line >> $PLAY_RELEASE_NOTES
+  else
+    # 450 chars reached
+    break
```
Comment (mcdurdin) [inline android/build-help.sh:137]:
```suggestion
    echo '* Additional bug fixes and improvements' >> $PLAY_RELEASE_NOTES
    break
```

File: android/build-help.sh [hunk 2]
```diff
@@ -117,4 +117,23 @@ if [ $TIER = "stable" ]; then
...
+wc=0
+FILTERED_LINES=`grep '^\s*\*.*$' "$KEYMAN_ROOT/android/help/about/whatsnew.md"`
+IFS=$'\n'      # Change IFS to new line
+for line in $FILTERED_LINES
+do
+  CHARS_IN_RELEASE_NOTES=$( wc -m < $PLAY_RELEASE_NOTES )
+  CHARS_IN_CURRENT_LINE=$( wc -m <<< $line )
+  if (( CHARS_IN_RELEASE_NOTES + CHARS_IN_CURRENT_LINE + 1 < 450 )); then
+    # Copy line to Play Store release notes
+    echo $line >> $PLAY_RELEASE_NOTES
```
Comment (mcdurdin) [inline android/build-help.sh:134]:
```suggestion
    echo "$line" >> $PLAY_RELEASE_NOTES
```

File: android/build-help.sh [hunk 3]
```diff
@@ -117,4 +117,23 @@ if [ $TIER = "stable" ]; then
   PLAY_RELEASE_NOTES="$KEYMAN_ROOT/android/KMAPro/kMAPro/src/main/play/release-notes/en-US/default.txt"
 fi
 echo "Generating Play Store release notes to $PLAY_RELEASE_NOTES"
-cp $KEYMAN_ROOT/android/help/about/whatsnew.md $PLAY_RELEASE_NOTES
+echo "" > "$PLAY_RELEASE_NOTES"
+
+# Copy whatsnew.md to release notes 1 line at a time,
+# filtering for lines that start with "*".
+# Play Store release notes have a limit of 500 characters
+wc=0
```
Comment (mcdurdin) [inline android/build-help.sh:125]:
```suggestion
```

**Review by mcdurdin — APPROVED** [review]
Minor tweaks suggested. LGTM.

(Have you run tests on this script?)

**Comment by darcywong00** [comment]
> (Have you run tests on this script?)

1. The script does strip off the header in whatsnew.md
```
---
title: What's New
---
Here are some of the new features we have added to Keyman 15.0 for Android:
```
(the last line is also not included in the regex)
2. I manually copied the content in `whatsnew.md` a few times  and the script does truncate the file

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.92-alpha](https://keyman.com/downloads/releases/alpha/15.0.92)
