### PR TITLE
fix(web): adds null guards for two Sentry errors

### LINKED ISSUE #3930: bug(web): TypeError: Cannot read property 'spec' of undefined
Sentry Issue: [KEYMAN-DEVELOPER-3R](https://sentry.keyman.com/organizations/keyman/issues/1906/?referrer=github_integration)

```
TypeError: Cannot read property 'spec' of undefined
  at Function.PreProcessor.clickKey (/resource/keymanweb.js:24364:82)
  at VisualKeyboard.<anonymous> (/resource/keymanweb.js:24999:52)
```

### LINKED ISSUE #3931: bug(web): TypeError: Cannot read property 'refreshLayouts' of undefined
Sentry Issue: [KEYMAN-DEVELOPER-3S](https://sentry.keyman.com/organizations/keyman/issues/1911/?referrer=github_integration)

```
TypeError: Cannot read property 'refreshLayouts' of undefined
  at RotationManager.resolve (/resource/keymanweb.js:30017:49)
  at None (/resource/keymanweb.js:30078:41)
```

It's not clear to me that this is the same error as #3927.

Build: release-14.0.186-alpha

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #3930.
Fixes #3931.

### CODE REVIEW

File: web/source/osk/preProcessor.ts [hunk 1]
```diff
@@ -47,8 +47,14 @@ namespace com.keyman.osk {
         // Deadkey matching continues to be troublesome.
         // Deleting matched deadkeys here seems to correct some of the issues.   (JD 6/6/14)
         outputTarget.deadkeys().deleteMatched();      // Delete any matched deadkeys before continuing
-  
-        let Lkc = PreProcessor._GetClickEventProperties(e['key'].spec as keyboards.ActiveKey, Lelem);
+
+        let keySpec = (e['key'] ? e['key'].spec : null) as keyboards.ActiveKey;
+        if(!keySpec) {
+          console.error("OSK key with ID '" + e.id + "', keyID '" + e.keyId + "' missing needed specification");
```
Comment (mcdurdin) [inline web/source/osk/preProcessor.ts:53]: How could this happen? Can you give an example so we can avoid producing keyboards that trigger this issue?

**Review by mcdurdin — APPROVED** [review]
LGTM

File: web/source/osk/preProcessor.ts (hunk 1 above)
Comment (jahorton) [reply web/source/osk/preProcessor.ts:53]: Your guess is as good as mine; that's exactly why I added the console log.

My first thought is that _maybe_ a spacing element is somehow "getting clicked". OSK elements not intended for input (internal spacing, formatting, etc) don't usually have the `'key'` property set, after all - only key elements that _are_ intended for input get that.

That being said, I can only guess... so I figured I'd add logging that should hopefully make the underlying issue more explicit.  I don't think I've ever seen the bug during personal tests, but it obviously can occur... somehow.
