### PR TITLE
[Android] Workaround to fix left deletions

### LINKED ISSUE #2250: [Android] Context manipulation is working incorrectly in Gmail app
Originally from [community site forum](https://community.software.sil.org/t/rotas-eat-characters-in-android-gmail-app/2713)

**Describe the bug**
The character rotation feature does not give the expected outputs. It instead deletes character (s) before the character which has to be rotated leaving incomplete string of characters, i.e. gibberish.

**To Reproduce**
1. Go to 'Gmail app'
2. Click to compose a new email
3. Start to type the character in the following orders using Khmer Angkor keyboard.
- (Type: `sea`)  ស េ ា > ោ not the expected សោ
- (Type: `seu`) ស  េ ុ > ុ not សុ  
- (Type: `suI`)  សុ ី > ស៊ី
- (Type `kNjd`) ក ណ ្ត > ណ្ដ not កណ្ដ
- (Type `xEjm`) ខ ែ ្ម > ្ម not ខ្មែ

**Expected behavior**
The rotation should not delete any character which does not belong in the rules. 

**Screenshots**
https://youtu.be/MpU7VAmhpB8

---

  
**Android:**
 - Device: [Galaxy S9+]
 - OS: [Android 9.0]
 - Keyman version [12.0.4205]
 - Target application: [Gmail for Android version 2019.09.15.270135155.release]
 
---
 
**Keyboard**
 - Keyboard name: [khmer_angkor]
 - Keyboard version: [1.0.1]
 - Language name: [Khmer]

**Additional context**
* I've tested this behavior in Google Keep, and it works fine there.
* Typing in Gmail subject field works fine

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #2250 
Due to a Chromium bug in the implementation of deleteSurroundingText, we need to save off the original context and re-insert characters that shouldn't have been deleted.

This is only done for System Keyboard

TODO
- [x] When inserting between left and right context, the cursor is overshooting
- [x] In some instances, backspace on `p̂p̂` is deleting an entire `p̂` unit
- [x] Cursor overshoots in Firefox text field on the `p` rota

## User Testing
1. Load the PR build of the apk
2. From the "Settings" page, install the "[moo](https://darcywong00.github.io/examples/moo/moo.kmp)" keyboard
    * 'p' will rotate through: `p`, `ṗ`, `p̂`, `p̂p̂`, `p`, ...
  (number of code points are: 1, 2, 2, 4, 1, ...)
    * 's' inputs grinning face emoji U+1F600
    * 'w' inputs winking face emoji U+1F609

3. Enable Keyman as a system keyboard
4. Switch to the "moo" keyboard and test in various places:
    * Verify backspace on empty context doesn't crash the app
    * Verify 'p' correctly rotates (previous characters in context don't get deleted)
    * Verify backspace removes `p` diacritics, not entire characters
    * Verify backspace removes entire emoji and doesn't split surrogate pairs 
  (The emoji in the suggestion banner does seem to get split?)
    * Verify a long context of 8 emojis and p̂p̂ followed by backspace only removes the circumflex.

5. Test in the following scenarios:
   - [x] Text field from a web [form](https://darcywong00.github.io/examples/form.html)
   - [x] Gmail app
   - [x] Gmail within Chrome browser on Android device
   - [x]  Gmail within Firefox browser on Android device (this didn't seem to show the original issue)

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java [hunk 1]
```diff
@@ -308,6 +308,52 @@ private static void initSystemKeyboard(Context appContext) {
...
+  /*
+  // TODO: Chromium has a bug where deleteSurroundingText deletes an entire grapheme cluster
+  // instead of one code-point.
+  // We'll retrieve up to (dn*2+16) characters before the cursor to collect enough characters
+  // for surrogate pairs + a long grapheme cluster.
+  // This buffer will be used to put back characters as-needed
+  //
+  // Visibility public so we can run a unit test
+  */
+  public static void performLeftDeletions(InputConnection ic, int dn) {
```
Comment (darcywong00) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: We currently can't run input connections in a unit test, so I intend to make this private

**Comment by MakaraSok** [comment]
> * Text field from a web form

OK

> * Gmail app

Running Android 9.0 on Samsung device, the `bksp` remove the entire character, not just the diacritic. The rota works fine though.

> * Gmail within Chrome browser (on Windows 10)

OK

> * Gmail within Firefox browser (on Windows 10)

Behave like it does in Gmail app on Android. The entire character is removed when the backspace is triggered.

I've also tried on Gmail on Chrome for mobile, and it also deletes the entire character. And the keyboard seems to disappear when a key is triggered.

**Comment by darcywong00** [comment]
One curiosity on deleting the emoji is the lmlayer seems to display a split surrogate pair

Before
before delete

After
after delete

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java [hunk 2]
```diff
@@ -2063,7 +2056,30 @@ public void run() {
 
           if (s.length() > 0) {
             SystemKeyboardShouldIgnoreSelectionChange = true;
-            ic.commitText(s, s.length());
+
+            // Using BreakIterator to count grapheme clusters
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: I don't understand why we need to move the cursor at all? If we are deleting left and then inserting text, surely no cursor movement is required?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java [hunk 3]
```diff
@@ -2075,5 +2091,65 @@ private void keyDownUp(int keyEventCode) {
       IMService.getCurrentInputConnection().sendKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN, keyEventCode));
       IMService.getCurrentInputConnection().sendKeyEvent(new KeyEvent(KeyEvent.ACTION_UP, keyEventCode));
     }
+
+    /*
+    // TODO: Chromium has a bug where deleteSurroundingText deletes an entire grapheme cluster
+    // instead of one code-point.
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: Please add a reference to the bug.
```suggestion
    // instead of one code-point. https://bugs.chromium.org/p/chromium/issues/detail?id=1024738
```

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java (hunk 2 above)
Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: I am concerned that using `BreakIterator` won't work if we are on a different version of Unicode than the target app. We shouldn't need to use `BreakIterator` at all: we should be able to do the calculation based purely on what changes we see happening in the text, shouldn't we?

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: There's just no consistency when specifying lengths between Chrome and Firefox for left deletions and commit text.

For a context `s*😃` where the * is  cursor:
Originally on Chrome, we would commitText(p̂p̂, 4) because it's 4 code points. Chrome would then advance the cursor 4 places, causing it to overshoot.
With break iterator, I specify length of 2, but even then the cursor overshoots past the 😄 .

The cursor adjustment is similar to how we have to restore characters after a "deletion". Because the OS is inconsistent in the behavior.

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: Using newCursorPosition `1` fixed the cursor position and also removed the use of BreakIterator
`ic.commitText(s, 1);`

Tested on Chrome and Firefox

Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: 🥂

**Comment by mcdurdin** [comment]
Can @MakaraSok re-test before we do the cherry-pick to 12.0 as well please?

**Comment by darcywong00** [comment]
> Can @MakaraSok re-test before we do the cherry-pick to 12.0 as well please?

The latest PR build is https://build.palaso.org/repository/download/KeymanAndroid_TestPullRequests/168770:id/release/kMAPro-debug.apk

Note, this PR is already on stable-12.0 so the 🍒 will go to master

**Comment by MakaraSok** [comment]
@darcywong00 All tested and everything is working as expected on Android 9.0 and 6.0.1.

-  Text field from a web form:
**PASSED**
-  Gmail app:
**PASSED**
-  Gmail within Chrome browser on Android device:
-  Gmail within Firefox browser on Android device (this didn't seem to show the original issue)
**PASSED, but Gmail on `Chrome and FireFox for mobile` in HTML view show boxes on the p instead of the expected diacritics**

___________
**The issue of crash when do left delete on empty text field is still there on Android 9.0, but not 6.0.1. The error message says, "Fatal Error with en_moo. Loading default keyboard".**

Error on Android 9.0
image

Error on Android 6.0.1
image

> (The emoji in the suggestion banner does seem to get split?)
Yeah, it does not look right to have them all strung together with other characters.

**Comment by darcywong00** [comment]
> The issue of crash when do left delete on empty text field is still there on Android 9.0, but not 6.0.1.

Good catch, @MakaraSok ! I'll have a fix for that soon

**Comment by darcywong00** [comment]
@MakaraSok The scenario turned out to be
`😄 😄 😄 😄 😄 😄 😄 😄 p̂ p̂`

Where the updated context was getting a split surrogate pair at the beginning. That's now fixed with the latest commit

**Comment by mcdurdin** [comment]
Okay, so those code changes look great. Can @MakaraSok do another test run please? 🙏 Once we have the ✔️ of approval from Makara, we should cherry pick this one to 12.0.

**Comment by darcywong00** [comment]
As of 2019-11-22 @MakaraSok here is the latest [apk]
(https://build.palaso.org/repository/download/KeymanAndroid_TestPullRequests/169858:id/release/kMAPro-debug.apk)
