### PR TITLE
fix(mac): Improve detection of non-compliant apps

### LINKED ISSUE #10247: bug(mac): compliance check unreliable when selection API location greater than zero is returned
### Describe the bug

Most applications that have non-compliant text APIs can be identified by getting the current selection with the API `selectionRange` which returns the location and length of the selection. 

A location of NSNotFound is usually returned for non-compliant apps.
If a location of zero is returned after inserting a character, then the app can be identified as non-compliant.
When checking browser for compliance, the results may vary if running an app like Google Docs inside the browser. In that case, when typing in Google Docs a location of 1 may be returned regardles of location.
Currently, when 1 is returned for the location after typing a character, the app is considered to be compliant. But if 1 is always returned regardless of what is typed, then it is obviously non-compliant. To fix, the location after the insert must be compared to the location before the insert to confirm that it has changed. If it has, then the app can be assumed to be compliant.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17+

### Operating system

_No response_

### Device

_No response_

### Target application

Browser apps running Google Docs and possibly other web applications

### PR DESCRIPTION
**Pull request by sgschantz**
This addresses two cases with non-compliance:
1) apps that report a seemingly valid selection (location and length) but the selection does not change after a character is inserted
2) apps for which the compliance varies when the context changes from one text field to another within the same application (e.g. Safari, switching from the URL field to the content area of Google Docs)

Fixes #10247

@keymanapp-test-bot skip

### CODE REVIEW

File: mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m [hunk 1]
```diff
@@ -319,14 +319,17 @@ - (void)postKeyPressToFrontProcess:(CGKeyCode)code from:(CGEventSourceRef) sourc
...
   
-  if ((self.apiCompliance == nil) || (![self.apiCompliance.clientApplicationId isEqualTo:self.clientApplicationId])) {
+  if ((self.apiCompliance == nil) ||
+      (![self.apiCompliance.clientApplicationId isEqualTo:self.clientApplicationId]) ||
+      self.contextChanged) {
     self.apiCompliance = [[TextApiCompliance alloc]initWithClient:client applicationId:self.clientApplicationId];
     [self.appDelegate logDebugMessage:@"KMInputMethodHandler initWithClient checkTextApiCompliance: %@", _apiCompliance];
   } else if (self.apiCompliance.isComplianceUncertain) {
-    // if it is valid but compliance is uncertain, then test it
+    // We have a TextApiCompliance object is valid, but compliance is uncertain, so test it
```
Comment (jahorton) [inline mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m:332]:
```suggestion
    // We have a valid TextApiCompliance object, but compliance is uncertain, so test it
```

**Review by jahorton — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.234-alpha](https://keyman.com/downloads/releases/alpha/17.0.234)
