### PR TITLE
fix(windows): tsysinfox64 not signed

### LINKED ISSUE #4484: bug(windows): tsysinfox64 does not appear to be signed
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 
 - Keyman version: 14.0.241-beta, 13.0.115.0 (stable)

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4484.

tsysinfox64 was being signed, but too late in the build process as it is embedded into tsysinfo.exe. There was code to sign it earlier, but that was being skipped due to a missing build flag. This has been a problem for some time.

It is possible to test this by doing a full release build locally, but I will test on the next beta anyway once it merges, which might be a more efficient approach.

### CODE REVIEW

File: resources/build/version/src/fixupHistory.ts [hunk 1]
```diff
@@ -223,17 +223,19 @@ export const sendCommentToPullRequestAndRelatedIssues = async (
   // https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-abuse-rate-limits
```
Comment (mcdurdin) [inline resources/build/version/src/fixupHistory.ts:223]: This was not intended to come along in this PR but it doesn't hurt. Just cleans up the logging in the nightly build trigger to show the correct pull request log entry with the correct timing (otherwise all the log entries are shown at once, but there is still a 10 sec delay between comment submissions)

**Comment by mcdurdin** [comment]
Build log looks good: https://build.palaso.org/viewLog.html?buildId=253003&buildTypeId=KeymanDesktop_TestPullRequests&tab=buildLog&_focus=5051#_state=134

**Comment by mcdurdin** [comment]
Signed successfully (note filename changes as it is extracted from tsysinfo.exe and I then copied it before it was deleted again to check it):

image

[No issues detected](https://www.virustotal.com/gui/file/64e32347871d1978f525654636ff69a32fbf5bf1b8bb761ff8292cb80f49db52/detection) by VirusTotal either now:

image

File: resources/build/version/src/fixupHistory.ts [hunk 2]
```diff
@@ -223,17 +223,19 @@ export const sendCommentToPullRequestAndRelatedIssues = async (
...
-      .then(() => octokit.issues.createComment({
+      .then(() => {
+        console.log(`Creating comment on Pull Request #${pull}`);
+        return octokit.issues.createComment({
         owner: 'keymanapp',
         repo: 'keyman',
         issue_number: pull,
         body: messagePull,
-      }));
+      })});
```
Comment (darcywong00) [inline resources/build/version/src/fixupHistory.ts:238]: nit: indenting ll. 234-237

**Comment by darcywong00** [comment]
> There was code to sign it earlier, but that was being skipped due to a missing build flag. This has been a problem for some time.

Should the missing build flag be corrected upstream?

**Comment by mcdurdin** [comment]
> Should the missing build flag be corrected upstream?

No, this fixes the issue here.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.243-beta](https://keyman.com/downloads/releases/beta/14.0.243)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.17-alpha](https://keyman.com/downloads/releases/alpha/15.0.17)
