### PR TITLE
fix(android): disable early keyboard-loading when not feasible

### LINKED ISSUE #13000: bug(android): Java exception raised during host-page load
Sentry Issue: [KEYMAN-WEB-F9](https://keyman.sentry.io/issues/4641110290/?referrer=github_integration)

```
Error: Java exception was raised during method invocation
  at init (/data/user/0/com.tavultesoft.kmapro/app_data/android-host.js:40:49)
```

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #13000.

I find it quite interesting that the JS-side error "due to Java error" doesn't have any corresponding Java error reports.  Either way, that particular line should be safe to bypass even when such an error occurs.

Said line was originally implemented as an optimization technique in #10022.  That PR helped reduce the 'flashing' behavior seen during keyboard load in which a basic placeholder keyboard was loading before the actually-desired keyboard was able to load.  Allowing that behavior is better than letting the keyboard page crash, though.

## User Testing

TEST_ANDROID_GENERAL_USE:  Do some simple tests with the Keyman for Android app, verifying that the keyboard acts normally.  Just a few keystrokes should be fine.

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java [hunk 1]
```diff
@@ -75,7 +75,10 @@ public String initialKeyboard() {
     Keyboard kbd = Keyboard.getDefaultKeyboard(context);
     int index = prefs.getInt(KMManager.KMKey_UserKeyboardIndex, -1);
     if (index >= 0) {
-      kbd = KMManager.getKeyboardInfo(this.context, index);
+      // It is possible for this method to return `null` - especially
+      // if the KeyboardController instance hasn't yet been initialized.
+      Keyboard lastKbd = KMManager.getKeyboardInfo(this.context, index);
+      kbd = lastKbd != null ? lastKbd : kbd;
```
Comment (jahorton) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java:81]: There are no matching error reports that I could find within Sentry, by the way.  That said, this is the only logical way I could determine for an error to be generated within this method to trigger the Web Sentry event; some of the methods involved do have `null` return paths.

**Comment by dinakaranr** [comment]
# Test Results
I tested this issue with the attached "18.0.175-alpha-test-13001" build(23/01/2025) on Android 14(Physical Device) and Android 13(Emulator). Here is my observation.

* **TEST_ANDROID_GENERAL_USE (Passed):**
1. Downloaded the khmer_angkor.kmp file from this PR task.
2. Installed the "Keyman-18.0.175.apk" file from this PR build.
3. Open the Keyman app.
4. Checked the "Enable Keyman as system-wide keyboard". Set the keyboard as the default keyboard box on the settings page.
5. Installed the khmer_angkor, Tamil99, gff_amharic and telugu.
6. Verified that the keyman keyboards were installed successfully and worked with good keystrokes.
It works well. Thank you.

File: android/KMEA/app/src/main/assets/android-host.js [hunk 2]
```diff
@@ -37,7 +37,20 @@ function init() {
...
   // Readies the keyboard stub for instant loading during the init process.
-  KeymanWeb.registerStub(JSON.parse(jsInterface.initialKeyboard()));
+  try {
+    let starterStubStr = jsInterface.initialKeyboard();
+    if(starterStubStr) {
+      KeymanWeb.registerStub(JSON.parse(starterStubStr));
+    }
+  } catch (err) {
+    // If a Java exception triggers during this time... okay, we can't
+    // load a keyboard during startup.  Rely on older loading techniques.
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/assets/android-host.js:47]: Why does the Java exception happen?

File: android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java (hunk 1 above)
Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java:81]: Does this mean that this function will return information for the wrong keyboard sometimes? Does that just shift the problem sideways rather than resolving it?

Comment (jahorton) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java:81]: There's a specific point at which the app and keyboard initialize the `KeyboardController` instance, which is managed as a singleton.  I don't see a hard-and-fast guarantee that the code above won't run before that instance is initialized - and if it isn't, that's when we get a `null`.

I don't think it means we get info for the wrong keyboard - we just don't get info for _any_ keyboard.  The WebView will still send a request for the keyboard later, at a later point after the host page has loaded (and after that initialization has had ample time to complete).  That's my understanding of the situation, anyway.

File: android/KMEA/app/src/main/assets/android-host.js (hunk 2 above)
Comment (jahorton) [reply android/KMEA/app/src/main/assets/android-host.js:47]: Inside the WebView, we get no data about the exception - just a message that one occurred.

On the Java side of things, well... 

https://github.com/keymanapp/keyman/pull/13001#discussion_r1926393934

> There are no matching error reports that I could find within Sentry, by the way.

I really wish I had something more concrete to give here; it kinda weirds me out that the Android side of Sentry didn't seem to catch anything relevant.

File: android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java (hunk 1 above)
Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java:81]: If we get no info for any keyboard, won't we get an exception on line 83 below when we call `kbd.toStub()`?

Comment (jahorton) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboardJSHandler.java:81]: Oh wait, now I see what you mean.  If we don't get a "previous" keyboard, we just get the "default" keyboard, resetting selection to whatever acts as the default.  Later in the load, we can try again for the "last loaded keyboard".

**Comment by mcdurdin** [comment]
Commit messages should have had trailers:

```
Fixes: #13000 
Fixes: KEYMAN-WEB-F9
```

File: android/KMEA/app/src/main/assets/android-host.js [hunk 3]
```diff
@@ -37,7 +37,20 @@ function init() {
   keyman.beepKeyboard = beepKeyboard;
 
   // Readies the keyboard stub for instant loading during the init process.
-  KeymanWeb.registerStub(JSON.parse(jsInterface.initialKeyboard()));
+  try {
+    let starterStubStr = jsInterface.initialKeyboard();
```
Comment (darcywong00) [inline android/KMEA/app/src/main/assets/android-host.js:41]: I vaguely remember Android 5.0 forcing us to use `var` instead of `let`

Comment (mcdurdin) [reply android/KMEA/app/src/main/assets/android-host.js:41]: Fixed in Chrome 49. https://caniuse.com/let

Comment (jahorton) [reply android/KMEA/app/src/main/assets/android-host.js:41]: Pretty sure that was an ES5 vs ES6 limitation.  Chrome 49+ is fine with let, and we currently state a minimum of Chrome 53.

https://github.com/keymanapp/keyman/blob/486807fd7d3fe09390154837648093331f85f921/android/docs/help/about/system-requirements.md?plain=1#L11-L15

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.178-alpha](https://keyman.com/downloads/releases/alpha/18.0.178)
