### PR TITLE
fix(android/engine): Fix OSK widths

### LINKED ISSUE #10241: bug(android): swapping keyboards via picker in landscape results in poor kbd layout
From user-testing of #7324:

> * **TEST_REGRESSION_ANDROID_KBD (FAILED):** Retested with the attached PR build (Keyman 17.0.227-alpha-test-7324 in the Android Mobile device (ver 13) and here is my observation: 1. While testing  TEST_INAPP_LATIN_KEYBOARD_LANDSCAPE test in the lanscape mode the OSK shrinks it width after using the globe key. Here, What I did is :
> 1. In the Landscape mode, typed some letter using the OSK. 
> 2. Used Backspace and Enter button after typing each words. 
> 3. Clicked the globe key. 
> 4. Selected the same keyboard from the Picker menu. 
>
> Here, I noticed that the OSK shrinks its width on the Keyman home page. Seems to be an issue. 
> 
> 

_Originally posted by @bharanidharanj in https://github.com/keymanapp/keyman/issues/7324#issuecomment-1851940191_

I have reproduced this on `master` - thus it is not a `feature-gestures` issue.  There's a chance this is related to recent ✨ Android optimizations.

Of note:  simply tapping the globe-key to swap keyboards does _not_ cause the issue.  Using the picker menu causes it.

### PR DESCRIPTION
**Pull request by darcywong00**
Follows #10373 and fixes #10241

This applies two things to fix OSK width to be full screen
* Disables multi-window mode for the entire Keyman app
* Refactors detection of device orientation so MainActivity.onResume() has the correct dimensions for the OSK

## User Testing

**Setup** - Install the PR build of Keyman for Android on an Android 12.0 device /emulator (SDK 31)

* **TEST_OSK** - Verifies OSK is full width after using keyboard picker
1. Launch Keyman for Android in landscape
2. Type some letters on the input text screen. 
3. Longpress the globe key to open the Keyboard picker menu. 
4. Click the default keyboard. 
5. Verify the app shows the OSK full-width.

### CODE REVIEW

**Review by mcdurdin — DISMISSED** [review]

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_OSK (FAILED):** Tested with the attached PR build (Keyman 17.0.248-alpha-test-10442) in the Android emulator (ver 12 / AP31)  and here is my observation: 1. Keyman app abruptly closed after launching it from the landscape mode. 2. However, it works fine after restarting the emulator. 3. Tried the same steps in the Android Mobile and I am getting the same issue.

**Comment by darcywong00** [comment]
Sigh - this needs more investigation. I also notice when rotating to landscape, the menu options don't display the landscape layout :confounded:

**Comment by darcywong00** [comment]
The refactoring of detecting the device orientation seems to work now.

@keymanapp-test-bot retest

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java [hunk 1]
```diff
@@ -267,9 +267,11 @@ protected void onResume() {
 
     // onConfigurationChanged() only triggers when device is rotated while app is in foreground
     // This handles when device is rotated while app is in background
+    // using KMManager.getOrientation() since getConfiguration().orientation is unreliable #10241
```
Comment (darcywong00) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java:270]: getResources().getconfiguration() was sometimes reporting PORTRAIT when the device was in LANDSCAPE orientation.

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java [hunk 2]
```diff
@@ -267,9 +267,11 @@ protected void onResume() {
...
     Configuration newConfig = this.getResources().getConfiguration();
-    if (newConfig != null && newConfig.orientation != lastOrientation) {
-      lastOrientation = newConfig.orientation;
+    int newOrientation = KMManager.getOrientation(context);
+    if (newOrientation != lastOrientation) {
+      lastOrientation = newOrientation;
       KMManager.onConfigurationChanged(newConfig);
     }
```
Comment (mcdurdin) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java:276]: This retrieves `newConfig` but never tests it. Given it may have a wrong orientation, is this going to cause grief when passing it to `onConfigurationChanged()`.
Also, I would move line 271 `... newConfig = ...` inside the `if() {` statement before line 275 in order to keep its scope limited

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java [hunk 3]
```diff
@@ -1998,6 +1998,17 @@ public static void removeKeyboardEventListener(OnKeyboardEventListener listener)
...
+  public static int getOrientation(Context context) {
+    Display display = ((WindowManager) context.getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay();
+    int rotation = display.getRotation();
+    if (rotation == Surface.ROTATION_0 || rotation == Surface.ROTATION_180) {
+      return Configuration.ORIENTATION_PORTRAIT;
+    } else if (rotation == Surface.ROTATION_90 || rotation == Surface.ROTATION_270) {
+      return Configuration.ORIENTATION_LANDSCAPE;
+    }
+    return Configuration.ORIENTATION_UNDEFINED;
+  }
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2010]: Did you find a reference for using this pattern?

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2010]: Here's one
https://developer.android.com/reference/android/view/Display#getRotation()

and a gist
https://gist.github.com/SammyVimes/92c0627195c4c55ea800

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java (hunk 2 above)
Comment (darcywong00) [reply android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java:276]: I retested the scenarios from #8704 and they seemed fine (restarting the app after rotating the device while the app is in the background).
lastOrientation is undefined so the app goes into this branch and refreshes with the correct dimensions. Maybe getOrientation() is the only buggy part?

**Comment by darcywong00** [comment]
Answer @mcdurdin 's question from standup: 
> How is the OSK handled if the device is rotated when the orientation is locked into PORTRAIT or LANDSCAPE?

I tested with my physical device locked in PORTRAIT and then locked in LANDSCAPE. Good news is the app and OSK remain locked in the orientation.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_OSK (PASSED):** Tested with the attached PR build (Keyman 17.0.251-alpha-test-10442) in the Android 12 / API 31 emulator and here is my observation: 1. Launched the Keyman in Landscape. 2. Closed the "Get Started" dialog. 3. Typed some letters on the text input screen. 4. Opened the Keyboard picker menu by long-pressing the globe key. 5. Clicked the default keyboard. 6. Verified that the app shows the OSK in full-width.

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/AdjustKeyboardHeightActivity.java [hunk 4]
```diff
@@ -110,9 +107,8 @@ public boolean onTouch(View view, MotionEvent event) {
             break;
           case MotionEvent.ACTION_UP:
             // Save the currentHeight when the user releases
-            Display display = ((WindowManager) context.getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay();
-            int rotation = display.getRotation();
-            String keyboardHeightKey = (rotation == Surface.ROTATION_90 || rotation == Surface.ROTATION_270) ?
+            int orientation = KMManager.getOrientation(context);;
```
Comment (mcdurdin) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/AdjustKeyboardHeightActivity.java:110]:
```suggestion
            int orientation = KMManager.getOrientation(context);
```

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java [hunk 5]
```diff
@@ -2012,11 +2023,10 @@ public static int getKeyboardHeight(Context context) {
...
     SharedPreferences prefs = context.getSharedPreferences(context.getString(R.string.kma_prefs_name), Context.MODE_PRIVATE);
 
-    Display display = ((WindowManager) context.getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay();
-    int rotation = display.getRotation();
-    if (rotation == Surface.ROTATION_0 || rotation == Surface.ROTATION_180) {
+    int orientation = getOrientation(context);
+    if (orientation == Configuration.ORIENTATION_PORTRAIT) {
       return prefs.getInt(KMManager.KMKey_KeyboardHeightPortrait, defaultHeight);
-    } else if (rotation == Surface.ROTATION_90 || rotation == Surface.ROTATION_270) {
+    } else if (orientation == Configuration.ORIENTATION_LANDSCAPE) {
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2029]: What do we do if ORIENTATION_UNDEFINED is returned? Seems like we fall into a hole?

**Review by mcdurdin — APPROVED** [review]

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java (hunk 5 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2029]: The `defaultHeight` initializes in l. 2023 so that value gets returned in l. 2033. I think typically that will be the portrait dimensions

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.252-alpha](https://keyman.com/downloads/releases/alpha/17.0.252)
