### PR TITLE
fix(windows): cleanup pointer to int typecasts

### LINKED ISSUE #3084: [Windows] Audit use of pointer casts in Keyman32/Keyman64
We should audit the rest of keyman32/keyman64 for use of improper casts of pointers to `int`.

It is unlikely to cause a problem presently because we currently have a base address fixed in the keyman64.dll below 2GB (which itself is not recommended...) so we should probably put this in as a maintenance issue. It could arise if Windows needs to relocate the dll I guess.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/3076_

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #3084.

This does two things:

1. Cleans up a bunch of places where we used to use `(int)` typecasts for pointer math, which was problematic. We now use `(INT_PTR)` per MSDN https://docs.microsoft.com/en-us/windows/win32/winprog64/rules-for-using-pointers and then cast that down to `(int)` where necessary, e.g. when storing string lengths which are never going to be more than a few hundred characters! Doing this explicitly helps to clarify that we are aware of the typecast and believe it to be safe.

2. Adds in some build infrastructure for future use of Coverity Scan https://scan.coverity.com/ which we plan to use for further code quality updates. I have submitted the project to Coverity and are now waiting for approval so we can check results. Once we have approval, I do plan to add this to the nightly build (we need to keep submissions under 3 builds/day).

Note: I have not yet added Keyman Core (Windows) to this project, nor are we currently building Keyman Core (macOS) or Keyman for Linux, but we should consider adding those in future.

### CODE REVIEW

File: windows/src/engine/keyman32/kmprocess.cpp [hunk 1]
```diff
@@ -770,14 +770,14 @@ BOOL ContextMatch(LPKEY kkp)
...
-          s->dpString[6], s->dpString[7], s->dpString[8], 
+        /*SendDebugMessageFormat(state.msg.hwnd, sdmKeyboard ,kkp->Line, "ContextMatch: CODE_ANY [%x %x %x %x %x %x %x %x %x %x] [%x %x %x] %d",
+          s->dpString[0], s->dpString[1], s->dpString[2],
+          s->dpString[3], s->dpString[4], s->dpString[5],
+          s->dpString[6], s->dpString[7], s->dpString[8],
           s->dpString[9],
           q[0], q[1], q[2],
-          (temp ? (int)(temp-s->dpString) : 0));*/
-        
+          (temp ? (INT_PTR)(temp-s->dpString) : 0));*/
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/kmprocess.cpp:779]: Yeah, I know this code is currently commented out ... but I didn't want to skip it nor delete it at this point in time.

File: windows/src/Makefile [hunk 2]
```diff
@@ -186,6 +186,39 @@ test-uiaccess:
     $(MAKE) test-uiaccess
     cd $(ROOT)\src
 
+#
+# Build Keyman projects for coverity; call this with
+#   make test-coverity
+# * Set environment variable COVBUILD to path to cov-build.exe
```
Comment (darcywong00) [inline windows/src/Makefile:192]: Would developers ever need to install coverity locally? If so, can you include notes in windows/src/README.md?

**Comment by darcywong00** [comment]
I'm inclined to approve this. But I had a hard time keeping track when the pointer should be
```
(INT_PTR)
(int)(INT_PTR)
(DWORD)(INT_PTR)
```

File: windows/src/Makefile (hunk 2 above)
Comment (mcdurdin) [reply windows/src/Makefile:192]: Yep. I will be doing coverity as a separate PR once I've sorted out how it all works. This is groundwork for that.

**Comment by mcdurdin** [comment]
> But I had a hard time keeping track when the pointer should be

I understand the challenge. I have added the `(int)(INT_PTR)` and `(DWORD)(INT_PTR)` casts where we are doing pointer arithmetic where we can be certain that it will resolve to a small number (e.g. string lengths) and we are storing in either an `int` or a `DWORD` field. Compiler warnings helped determine which needed the additional downcast and which cast it should be.

The two-part cast is technically unnecessary but helps to document that we are not accidentally downcasting where we shouldn't be.

**Review by darcywong00 — APPROVED** [review]
lgtm
