### PR TITLE
fix(core): memory management of options in action struct

### LINKED ISSUE #10067: bug(core): when calling km_core_state_get_actions, persist_options contains unexpected values
### Describe the bug

After processing a key with Keyman Core, calling km_core_state_get_actions does not return a valid key value pair in the persist_options field as expected. 

### Reproduce the bug

1. use the Armenian Mnemonic keyboard
2. type[alt-v]
3. expected: "√"
4. type[w]
5. expected: "" -- ("√" is deleted)

This should toggle the option 'option_ligature_ew' from a value of 0 (zero) to 1 (one)

However, calling the API returns invalid values, so they will not be persisted correctly on the platform and may cause the app to crash while attempting to parse them.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyboard name

Armenian Mnemonic

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #10067.

Management of memory for persisted options was wrong in the action struct, as the members key and value would be freed immediately after being added to the temporary vector (because the vector was of the struct rather than of the class).

Given the struct is a C struct, we need the memory management to be explicit, so we now release() each option into the vector as we create it, which means that its member values will not be freed when the option is then immediately deleted. (This allows us to use the initial copy of the members of option that option() constructor does.)

Added the release() function as that was a relatively clear way of indicating that the contents of the structure are now owned by the caller, following the pattern from std::unique_ptr.

Finally, the unit test for persisted options was in the action_api.cpp test module, but it was never called, so this was not being tested. Now it is.

@keymanapp-test-bot skip

### CODE REVIEW

File: core/src/option.cpp [hunk 1]
```diff
@@ -43,6 +43,14 @@ option::option(km_core_option_scope s, char16_t const *k, char16_t const *v)
   }
 }
 
+km_core_option_item
+option::release() {
```
Comment (darcywong00) [inline core/src/option.cpp:47]: nit - the code style in this file seems to have open braces on a new line.
Maybe also add a short documententation of the memory complexity😄

Comment (darcywong00) [reply core/src/option.cpp:47]: nvm I see you have it in the header

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.217-alpha](https://keyman.com/downloads/releases/alpha/17.0.217)
