### PR TITLE
fix(ios): fixes accidental logo / cancel button overlap during package installation

### LINKED ISSUE #4328: bug(ios): unexpected image in package-installer toolbar
**Describe the bug**

When using "Install from File", selecting a package to install will provide the following view:

Screen Shot 2021-01-25 at 1 45 16 PM

Compare/contrast to selecting the file from outside of the app:

Screen Shot 2021-01-25 at 1 46 54 PM

**Expected behavior**

The former should look like the latter.  Ideally, with the same presentation style - with the installer's view overlaid above the main view controller.

**Keyman for iPhone/iPad:**
 - Device: iPhone SE 2, probably others
 - OS: iOS 14.2, 14.3, probably earlier
 - Keyman version: 14.0.228-beta
 - Target application: Keyman

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #4328.

The issue arose due to the view hierarchy in which the package installer was being displayed when using "Install From File" for package installation.  The old implementation had a "hard requirement" that it be displayed from the top-level view, which isn't ideal.  Reworking it to fully and properly accept an arbitrary `UINavigationView` root and then using the Settings menu's instance allows us to keep the top-level-only logo away from the package installer.

I've tested the UX via all three standard install paths:

1. Opened a .kmp from outside the Keyman app.  (Safari download, iOS Files app)
2. Used our "install from file" menu option from within the app
3. Downloaded from keyboard search

There was also an issue with the 'activity spinner' not displaying during installation from Install From File as well, so I rolled that into this PR.

### CODE REVIEW

File: ios/keyman/Keyman/Keyman/MainViewController.swift [hunk 1]
```diff
@@ -110,14 +110,14 @@ class MainViewController: UIViewController, TextViewDelegate, UIActionSheetDeleg
     // We have to gerry-rig this so that the framework-based SettingsViewController
     // can launch the app-based DocumentViewController.
     if #available(iOS 11.0, *) {
-      Manager.shared.fileBrowserLauncher = { _ in
+      Manager.shared.fileBrowserLauncher = { navVC in
```
Comment (jahorton) [inline ios/keyman/Keyman/Keyman/MainViewController.swift:113]: Declaration: https://github.com/keymanapp/keyman/blob/b205d1efff970babb0eb5aea5ef89b6a69f97a77/ios/engine/KMEI/KeymanEngine/Classes/Manager.swift#L47

Turns out the parameter was declared for a reason.  Who knew?

**Comment by darcywong00** [comment]
Can you post some screens of the fixed views?

**Comment by jahorton** [comment]
Before:

Screen Shot 2021-01-25 at 1 45 16 PM

After:

Screen Shot 2021-01-26 at 1 46 29 PM

Also, once finished with the Welcome page, if installation is still ongoing in the background:

Screen Shot 2021-01-26 at 1 46 40 PM

The spinner was missing "before".  (Full disclaimer:  picture taken with changes from child PR #4338 as well; otherwise, the keyboard would be visible at the bottom.)

File: ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift [hunk 2]
```diff
@@ -346,9 +346,8 @@ public class PackageInstallViewController<Resource: LanguageResource>: UIViewCon
 
     let dismissalBlock = {
       if let nvc = self.navigationController {
-        self.dismiss(animated: true) {
-          nvc.popToRootViewController(animated: true)
-        }
+        self.dismiss(animated: true)
+        nvc.popToRootViewController(animated: false)
```
Comment (mcdurdin) [inline ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift:350]: Why the change away from a closure?

File: ios/keyman/Keyman/Keyman/PackageBrowserViewController.swift [hunk 3]
```diff
@@ -85,19 +85,32 @@ class PackageBrowserViewController: UIDocumentPickerViewController, UIDocumentPi
...
         activitySpinner.stopAnimating()
         activitySpinner.removeFromSuperview()
-        self.view.isUserInteractionEnabled = true
-        self.dismiss(animated: true, completion: nil)
+
+        // Do not animate the dismissal:  the welcome-page's dismissal
+        // already provides enough animation.
+        if let navVC = self.navVC {
+          navVC.dismiss(animated: true, completion: nil)
+        }
```
Comment (mcdurdin) [inline ios/keyman/Keyman/Keyman/PackageBrowserViewController.swift:113]: You say `Do not animate the dismissal` but the `dismiss()` call has parameter `animated: true`?

File: ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift (hunk 2 above)
Comment (jahorton) [reply ios/engine/KMEI/KeymanEngine/Classes/Resource Management/PackageInstallViewController.swift:350]: Note the other difference:  `animated: true` -> `animated: true` is now `animated: true` -> `animated: false`.

We're cutting out the second 'animation' so running the second dismissal concurrently with the first dismissal allows the first's animation to (visually) act for both dismissals simultaneously.  This also reduces the user's wait time.  If the closure pattern was preserved, there would still be a second animation... just abbreviated.

I'd noticed in testing that there was an awkward wait while all the view shuffling occurred, so I figured it best to reduce that if possible.  I wasn't able to remove it all, but this spot was a possible optimization.

File: ios/keyman/Keyman/Keyman/PackageBrowserViewController.swift (hunk 3 above)
Comment (jahorton) [reply ios/keyman/Keyman/Keyman/PackageBrowserViewController.swift:113]: ... guess I removed that comment in the child PR; thought I'd removed it in this one as well.  Oops.

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.229-beta](https://keyman.com/downloads/releases/beta/14.0.229)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.230-beta](https://keyman.com/downloads/releases/beta/14.0.230)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)
