### PR TITLE
fix(developer): handle shortcut keys in debugger

### LINKED ISSUE #5718: bug(developer): debugger should capture all key events, even shortcuts such as Ctrl+A
Key events that have shortcuts associated are not making it into the keyboard debugger. We need to be capturing these key events before the shortcuts get a look-in, as this is what Keyman does within apps. If the key combo is not handled by the keyboard under debugging, then it can fall through to the shortcut.

Per @makarasok: 

```
+ [RCTRL K_A] > 'RightCtrl+A works!'  c not working
+ [LCTRL K_A] > 'LeftCtrl+A works!'   c not working

+ [RCTRL K_L] > 'RightCtrl+L works!'
+ [LCTRL K_L] > 'LeftCtrl+L works!'
```

Probably it is conflicting with the common shortcut "Ctrl+A". 

_Originally posted by @MakaraSok in https://github.com/keymanapp/keyman/issues/5697#issuecomment-920743502_

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #5718.

The debugger memo control will now filter out action shortcut keys such as Ctrl+A, Ctrl+O, so that the keyboard being debugged can get the first chance to look at them and handle them if it wishes.

If the keyboard does not handle the keystroke, then a set of editor shortcut keys will be handled by the debugger, namely:

* Ctrl+A - select all
* Ctrl+C - copy
* Ctrl+V - paste
* Ctrl+X - cut
* Ctrl+Z - undo

Note that undo semantics are a little weird with the debugger, but that is not related to this fix. By a little weird, I mean that characters emitted by the keyboard being debugged do not flow into the undo buffer, so undo often has no effect. I am not planning to fix this idiosyncrasy at this time.

# User Testing

All these tests should be performed in the debugger.

* **TEST_BASELINE:** Make sure that general debugging works in a Keyman keyboard, and that text selection keys work.
* **TEST_SHORTCUT:** When debugging a keyboard that does not define Ctrl+A, press Ctrl+A and verify that it selects all text in the debug window.
* **TEST_HANDLED:** Create a keyboard that defines `+ [CTRL K_A]`. Test it and verify that Ctrl+A is handled by the keyboard and *doesn'* select all.

### CODE REVIEW

File: windows/src/developer/TIKE/main/RedistFiles.pas [hunk 1]
```diff
@@ -124,8 +124,15 @@ function GetWixPath: string;
...
+var
+  root: string;
+const
+  DevProjectTemplatePath = 'windows\src\developer\kmconvert\data\';
 begin
-  Result := GetDebugPath('Debug_RedistTemplatePath', ExtractFilePath(ParamStr(0))+'projects\templates\');
+  if TKeymanPaths.RunningFromSource(root)
+    then Result := root + DevProjectTemplatePath
+    else Result := ExtractFilePath(ParamStr(0))+'projects\templates\';
+  Result := GetDebugPath('Debug_RedistTemplatePath', Result);
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/main/RedistFiles.pas:135]: This allows us to create new projects while debugging Keyman Developer from source, without fiddling with registry settings. I just threw it in here as a rider; it matches similar patterns in RedistFiles.pas and KeymanPaths.pas.

File: windows/src/developer/TIKE/child/UfrmDebug.pas [hunk 2]
```diff
@@ -1124,13 +1147,15 @@ procedure TfrmDebug.SetUIStatus(const Value: TDebugUIStatus);
           StartBatch;
           StatusText := 'Debugging';
           memo.ReadOnly := True;
+          memo.IsDebugging := False;
```
Comment (darcywong00) [inline windows/src/developer/TIKE/child/UfrmDebug.pas:1150]: Why is this `False` in the duiDebugging case?

Comment (mcdurdin) [reply windows/src/developer/TIKE/child/UfrmDebug.pas:1150]: Yeah, this one is a little tricky. The thing is, while single-step debugging, the control temporarily switches modes so characters can be inserted, etc, if these are a part of the action being debugged. But we don't want the user to make changes to the content of the control while single-step debugging -- if they are on a breakpoint and press Ctrl+X to delete content, then that will mess things up quite badly!

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by MakaraSok** [comment]
* **TEST_BASELINE: BLOCKED** Please clarify and illustrate what `text selection keys` are. Are they all listed right above the instructions?
* **TEST_SHORTCUT: PASSED** `Ctrl A` does select all texts in the debugger.

   

* **TEST_HANDLED: PASSED** The key defined does output the expected character and not selecting all texts in the debugger.

**Comment by mcdurdin** [comment]
> * Please clarify and illustrate what `text selection keys` are. Are they all listed right above the instructions?

There would be two categories: text movement and text selection:
* Text movement keys would be all arrow keys <kbd>←</kbd>, <kbd>→</kbd>, <kbd>↑</kbd>, <kbd>↓</kbd>, <kbd>home</kbd>, <kbd>end</kbd>, <kbd>pgup</kbd>, <kbd>pgdn</kbd>, <kbd>ctrl</kbd>+<kbd>home</kbd>, <kbd>ctrl</kbd>+<kbd>end</kbd>.
* Then text selection keys are <kbd>shift</kbd>+any text movement combination from above, as well as <kbd>Ctrl</kbd>+<kbd>A</kbd>.

There may be other text movement keys but they would be less critical, and would probably work in any case :grin:

@keymanapp-test-bot retest TEST_BASELINE

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.143-alpha](https://keyman.com/downloads/releases/alpha/15.0.143)
