### PR TITLE
fix(android/engine,android/app) Notify when invalid keyboard package fails to install

### LINKED ISSUE #3958: bug(android/engine): Installing certain legacy keyboard packages can silently fail
@mcdurdin was trying to install the legacy MBSindhi keyboard package on 14.0 alpha, but it failed to install silently.

The [mbsindhi.kmp](https://downloads.keyman.com/keyboards/mbsindhi/1.0/mbsindhi.kmp) package erroneously doesn't include the .js file, and the language is missing in kmp.json
```
"keyboards" : [
    {
      "name" : "Sindhi Keyboard",
      "id" : "mbsindhi",
      "version" : "1.0",
      "languages" : [
      ]
    }
```

Will need to investigate why the Toast notification doesn't appear.

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #3958 

Some of the legacy keyboard packages are invalid because they
* don't include .JS touch-optimized keyboard
* don't have languages assigned in kmp.json

This adds additional checks during a package installation and provides the notification when a keyboard package fails

### Screenshot
Screenshot_1606369371

### Testing
Test by attempting to install "mbsindhi" keyboard.

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java [hunk 1]
```diff
@@ -270,16 +274,31 @@ public static Keyboard getKeyboard(JSONObject json, String packageID, int index)
...
+        String filename = file.getString(PP_FILES_NAME_KEY);
+        if (FileUtils.hasJavaScriptExtension(filename)) {
+          jsKeyboardExists = true;
+          break;
+        }
+      }
+      if (!jsKeyboardExists) {
+        return count;
+      }
+
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java:301]: Instead of just looking for a .js file (which could be, for example, part of a welcome.htm), we should check that there is an associated .js for each of the entries in the `keyboards` array.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java [hunk 2]
```diff
@@ -753,6 +772,10 @@ public Keyboard getKeyboard(String packageID, String keyboardID, String language
         Map<String, String>[] maps;
         ArrayList<String> preferredLanguageList;
         JSONArray languages = entries.getJSONObject(i).getJSONArray(PP_LANGUAGES_KEY);
+        if (languages != null && languages.length() == 0) {
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java:775]:
```suggestion
        if (languages == null || languages.length() == 0) {
```

**Review by mcdurdin — CHANGES_REQUESTED** [review]

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java (hunk 1 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java]: I changed `getKeyboardCount()` to count the number of keyboard ID's with a matching .js file.

It's possible for a keyboard ID to have a .kmx file but not .js file in the package.
During the actual package installation, only the keyboard entries where `touchKeyboardExists()` (l. 194) get processed.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java [hunk 3]
```diff
@@ -270,18 +275,35 @@ public static Keyboard getKeyboard(JSONObject json, String packageID, int index)
...
-      count = keyboards.length();
+      for (int k = 0; k <  keyboards.length(); k++) {
+        JSONObject keyboardObj = keyboards.getJSONObject(k);
+        String keyboardID = keyboardObj.getString(PP_KEYBOARD_ID_KEY);
+        String expectedKeyboardFilename = keyboardID + FileUtils.JAVASCRIPT;
+        JSONArray files = json.getJSONArray(PP_FILES_KEY);
+        for (int f = 0; f < files.length(); f++) {
+          JSONObject file = files.getJSONObject(f);
+          String filename = file.getString(PP_FILES_NAME_KEY);
+          if (FileUtils.hasJavaScriptExtension(filename) && filename.equals(expectedKeyboardFilename)) {
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java:301]:
```suggestion
          if (filename != null && filename.equals(expectedKeyboardFilename)) {
```

The first test is redundant but the replacement here is probably good for safety?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java [hunk 4]
```diff
@@ -270,18 +275,35 @@ public static Keyboard getKeyboard(JSONObject json, String packageID, int index)
...
+            count++;
+            break;
+          }
+        }
+      }
     } catch (JSONException e) {
       KMLog.LogException(TAG, "", e);
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java:308]: Probably add `count = 0` here as the package is presumably invalid.

**Review by mcdurdin — APPROVED** [review]
LGTM
