### PR TITLE
fix(developer): improve 'does not exist' error message

### LINKED ISSUE #8508: bug(developer): confusing kmc message on file not found 🙀
```shell
$ kmc build does-not-exist.xml
Building does-not-exist.xml
ERROR 300007: The source file has an invalid structure: Unable to read XML file
An error occurred compiling does-not-exist.xml
```

Yes, technically the message is true, it _was_ unable to read.  But the same message shows up if the XML was just scrambled.
It shouldn`t be talking about the structure if the file just doesn't exist.

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #8508.

Now shows:

```
$ node . build does-not-exist.xml
Building does-not-exist.xml
File does-not-exist.xml does not exist
```

(Note, full error message cleanup and consolidation is a separate issue, part of #5283)

@keymanapp-test-bot skip

### CODE REVIEW

File: developer/src/kmc/src/commands/build.ts [hunk 1]
```diff
@@ -27,6 +27,12 @@ export function declareBuild(program: Command) {
 async function build(infile: string, options: BuildActivityOptions): Promise<boolean> {
   console.log(`Building ${infile}`);
 
+  if(!fs.existsSync(infile)) {
+    // TODO: consolidate errors
```
Comment (jahorton) [inline developer/src/kmc/src/commands/build.ts:31]: We have an issue for this TODO?

> (Note, full error message cleanup and consolidation is a separate issue, part of https://github.com/keymanapp/keyman/issues/5283)

Ah, there it is.

File: developer/src/kmc/src/commands/build.ts [hunk 2]
```diff
@@ -27,6 +27,12 @@ export function declareBuild(program: Command) {
...
+    console.error(`File ${infile} does not exist`);
+    process.exit(2);
```
Comment (jahorton) [inline developer/src/kmc/src/commands/build.ts:33]: Is there documentation on why the exit code of 2 was selected?

**Review by jahorton — APPROVED** [review]

File: developer/src/kmc/src/commands/build.ts (hunk 2 above)
Comment (mcdurdin) [reply developer/src/kmc/src/commands/build.ts:33]: No, but will be considered with error message cleanup.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.87-alpha](https://keyman.com/downloads/releases/alpha/17.0.87)
