### PR TITLE
fix(windows): keep online update in focus

### LINKED ISSUE #4554: bug(windows): UAC does not stay in focus amid Keyman upgrade
**Describe the bug**

When trying to upgrade from an older version of 14 beta to another, the UAC gets buried in the taskbar. The blinking UAC icon on the taskbar has to be clicked on to reveal its window for one to click on to continue the upgrade.

**Expected behavior**

The UAC should be taken over the screen for one to click on the continue the upgrade.

**Screenshots**

image

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.244-beta
 - Target Application: Configuration

**Additional context**

cf: https://github.com/keymanapp/keyman/issues/3936#issuecomment-787559762

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4554.

The Online Update form did not have the correct owner window for some operations, meaning that the elevation dialog would not get foreground.

### CODE REVIEW

File: windows/src/desktop/kmshell/main/UfrmOnlineUpdateIcon.pas [hunk 1]
```diff
@@ -123,7 +123,7 @@ procedure TfrmOnlineUpdateIcon.trayClick(Sender: TObject);
 begin
   tmrShowBalloon.Enabled := False;
   tray.Visible := False;
-  with TOnlineUpdateCheck.Create(True, False) do
+  with TOnlineUpdateCheck.Create(nil, True, False) do
```
Comment (darcywong00) [inline windows/src/desktop/kmshell/main/UfrmOnlineUpdateIcon.pas:126]: Why is this `nil` instead of `Self`?

Comment (mcdurdin) [reply windows/src/desktop/kmshell/main/UfrmOnlineUpdateIcon.pas:126]: Because `Self` here is an invisible window, so making it owner doesn't really work.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.260-beta](https://keyman.com/downloads/releases/beta/14.0.260)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.20-alpha](https://keyman.com/downloads/releases/alpha/15.0.20)
