### PR TITLE
[Windows] Fix support for Caps Lock headers

### LINKED ISSUE #1480: [Windows] Caps Lock system stores do not appear to be working in 11.0

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #1480.

The system stores `&shiftfreescaps`, `&capsononly` and `&capsalwaysoff` were no longer
working in Keyman 11. This fixes support for them.

### CODE REVIEW

File: windows/src/engine/keyman32/appint/aiTIP.cpp [hunk 1]
```diff
@@ -100,14 +100,17 @@ void ProcessToggleChange(UINT key) {   // I4793
...
     case VK_CAPITAL: flag = CAPITALFLAG; break;
     case VK_NUMLOCK: flag = NUMLOCKFLAG; break;
+    default: return;
   }
 
-  if(*Globals::ShiftState() & flag)  {
-    *Globals::ShiftState() &= ~flag; 
-  }
-  else { 
+  if (GetKeyState(key) & 1) {
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/aiTIP.cpp]: This reads the current key state rather than relying on a local flag. It's a bad idea to maintain two flags any more than you have to :)

File: windows/src/engine/keyman32/appint/aiTIP.cpp [hunk 2]
```diff
@@ -154,10 +162,10 @@ extern "C" __declspec(dllexport) BOOL WINAPI TIPProcessKey(WPARAM wParam, LPARAM
     switch(wParam) {
     case VK_CAPITAL:
       if(!isUp) ProcessToggleChange((UINT) wParam);   // I4793
-      KeyCapsLockPress(isUp);   // I4548
+      if(!Updateable) KeyCapsLockPress(isUp);   // I4548
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/aiTIP.cpp]: We only want to process the Caps Lock key event once -- in the first pass (!Updateable).

File: windows/src/engine/keyman32/appint/aiWin2000Unicode.h [hunk 3]
```diff
@@ -30,9 +30,6 @@ class AIWin2000Unicode:public AppIntegration
 {
 private:
 
-	BYTE kbstate[256];
-	BOOL FUnicharOkay;
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/appint/aiWin2000Unicode.h]: Old unused variables

File: windows/src/engine/keyman32/capsstate.cpp [hunk 4]
```diff
@@ -26,12 +26,6 @@
 */
 #include "pch.h"
 
-static BYTE kbstate[256];
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/capsstate.cpp]: Old unused variables

File: windows/src/engine/keyman32/capsstate.cpp [hunk 5]
```diff
@@ -63,15 +57,17 @@ void KeyCapsLockPress(BOOL FIsUp)  // I3284 - void   // I3529
 
 	if(_td->lpActiveKeyboard->Keyboard->dwFlags & KF_CAPSONONLY)
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/capsstate.cpp]: Will fixup legacy tabs later (not in this PR)

File: windows/src/engine/keyman32/capsstate.cpp [hunk 6]
```diff
@@ -86,11 +82,10 @@ void KeyShiftPress(BOOL FIsUp)  // I3284 - void   // I3529
   if(!_td) return;
 	if(!_td->lpActiveKeyboard) return;		// pass through to window
 			
-	if((GetKeyState(VK_CAPITAL) & 1) == 0) return;
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/capsstate.cpp]: Refactoring so we get the debug logging

File: windows/src/engine/kmtip/keys.cpp [hunk 7]
```diff
@@ -168,7 +174,8 @@ STDAPI CKMTipTextService::OnTestKeyDown(ITfContext *pContext, WPARAM wParam, LPA
 {
   LogKey("CKMTipTextService::OnTestKeyDown", 0, wParam, lParam);
   // If the keystroke is a Keyman-generated key, ignore it
-  if((lParam & 0x00FF0000L) == 0xFF0000L)   // I3566
+  if((lParam & 0x00FF0000L) == 0xFF0000L &&
+    wParam != VK_CAPITAL)   // I3566
```
Comment (mcdurdin) [inline windows/src/engine/kmtip/keys.cpp]: We always need to pass Caps Lock through to the engine for processing, even if we generated it (so we track the state reliably)

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/138347:id/kvk/index.html)

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/138434:id/kvk/index.html)

File: windows/src/engine/keyman32/capsstate.cpp [hunk 8]
```diff
@@ -63,15 +57,17 @@ void KeyCapsLockPress(BOOL FIsUp)  // I3284 - void   // I3529
 
 	if(_td->lpActiveKeyboard->Keyboard->dwFlags & KF_CAPSONONLY)
 	{
-		if(FIsUp && !(GetKeyState(VK_CAPITAL) & 1))		// I267 - 24/11/2006 invert GetKeyState test
+    SendDebugMessageFormat(0, sdmAIDefault, 0, "KeyCapsLockPress: KF_CAPSONONLY: FIsUp=%d CapsState=%d", FIsUp, GetKeyState(VK_CAPITAL) & 1);
+    if(FIsUp && !(GetKeyState(VK_CAPITAL) & 1))		// I267 - 24/11/2006 invert GetKeyState test
```
Comment (darcywong00) [inline windows/src/engine/keyman32/capsstate.cpp]: 1. It seems there's a lot of `GetKeyState(VK_CAPITAL) & 1` in this function. Is it possible to just call it once above the `if()` block?

2. tabspace is making the indents look off.

File: windows/src/test/manual-tests/caps_lock_headers/source/caps_lock_headers.kps [hunk 9]
```diff
@@ -0,0 +1,95 @@
...
+      <Name>caps_lock_caps_on_only</Name>
+      <ID>caps_lock_caps_always_off</ID>
+      <Version>1.0</Version>
+      <Languages/>
+    </Keyboard>
+    <Keyboard>
+      <Name>caps_lock_caps_always_off</Name>
+      <ID>caps_lock_caps_on_only</ID>
+      <Version>1.0</Version>
+      <Languages/>
```
Comment (darcywong00) [inline windows/src/test/manual-tests/caps_lock_headers/source/caps_lock_headers.kps]: Do these test keyboards need an associated language?

Comment (mcdurdin) [reply windows/src/test/manual-tests/caps_lock_headers/source/caps_lock_headers.kps]: No, because they'll go with the default Windows language if none is specified.

File: windows/src/engine/keyman32/capsstate.cpp (hunk 8 above)
Comment (mcdurdin) [reply windows/src/engine/keyman32/capsstate.cpp]: 1. I opted to make a function `IsCapsLockOn()` rather than introduce locals to cache what is a very quick call.

2. Fixed tab stops on this file

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/138452:id/kvk/index.html)
