### PR TITLE
fix: Temporarily disable dictionary when entering password field

### LINKED ISSUE #2251: [Android] Temporarily disable dictionary when entering password fields
Keyman 12 includes the nrc.en.mtnt.model that runs with the default SIL EuroLatin keyboard.

This means when the system keyboard is entering a password field, the password context is displayed as the left suggestion.

When the app is entering a password field, we should temporarily disable the dictionary.

password

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #2251 
On entering a hidden password field, disable the dictionary so the password won't appear as the left suggestion.

On entering a non-password field, re-enable the dictionary

### CODE REVIEW

**Comment by darcywong00** [comment]
## User Testing
* Uses default SIL EuroLatin keyboard and nrc.en.mtnt dictionary
* Default system keyboard, preferably one with suggestions like Gboard
* Test webpage with text and password input fields (Example [page](https://darcywong00.github.io/examples/form.html))

### Setup
- [ ] Load the test apk
- [ ] From the "Get Started" menu, enable Keyman as a system keyboard
- [ ] Open Chrome and browse to the test webpage

### Verify suggestions appear for normal input fields
- [ ] Using the default system keyboard, click on a normal input field and start typing
- [ ] Verify the text is visible
- [ ] Verify suggestions appear on the keyboard (if Gboard)
- [ ] From the keyboard selector, switch to the Keyman SIL EuroLatin keyboard and start typing
- [ ] Verify the text is visible
- [ ] Verify suggestions appear on the keyboard (delete the context and restart typing if no suggestions appear)

### Verify suggestions do not appear for hidden password fields
- [ ] From the keyboard selector, switch to the default Gboard keyboard
- [ ] Click on the password field and start typing
- [ ] Verify the text is obfuscated with `*`
- [ ] Verify suggestions do not appear on the keyboard
- [ ] From the keyboard selector, switch to the Keyman SIL EuroLatin keyboard
- [ ] Verify the text is obfuscated with '*'
- [ ] Verify suggestions do not appear on the keyboard
- [ ] Click on a normal text field and start typing
- [ ] Verify the text is visible
- [ ] Verify the suggestions appear on the keyboard

### Verify suggestions do not appear when disabled from "Settings"
- [ ] Open the Keyman app
- [ ] Go to the "Settings" --> Installed Languages --> English -->
- [ ] Disable corrections for nrc.en.mtnt.model
- [ ] Go back to test page with Keyman selected
- [ ] Click on text field
- [ ] Verify suggestions do not appear
- [ ] Click on password field
- [ ] Verify suggestions do not appear
- [ ] Click on text field
- [ ] Verify suggestions do not appear (this verifies even though the nrc.en.mtnt.model gets registered, the suggestion banner isn't activated because of the Settings)

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java [hunk 1]
```diff
@@ -330,9 +330,20 @@ public static View createInputView(InputMethodService inputMethodService) {
...
+
+    // Temporarily disable lm-layer if entering a hidden password field
+    if (currentLexicalModel != null && isHiddenPasswordInputType(inputType)) {
+      deregisterLexicalModel(currentLexicalModel.get(KMKey_LexicalModelID));
+    } else if (currentLexicalModel == null) {
+      // Check if lm-layer needs to be re-enabled
+      HashMap<String, String> kbInfo = getCurrentKeyboardInfo(appContext);
+      String langId = kbInfo.get(KMKey_LanguageID);
+      registerAssociatedLexicalModel(langId);
+    }
```
Comment (jahorton) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: Note that KMW's `com.keyman.text.prediction.ModelManager` class has the property `mayPredict` that was designed for this sort of case; rather than completely dumping the model, it may simply be turned off and on selectively once registered.

Of course, the approach above works too.

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: ah, I'll update to use `mayPredict` since that's better.

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: > ah, I'll update to use `mayPredict`

Well, I tried. The problem is the initial time the system keyboard gets loaded, it calls `registerAssociatedLexicalModel` again and pulls `mayPredict` with whatever the setting is. (default true). I'll keep the code as it is.

**Comment by mcdurdin** [comment]
@darcywong00 small note on User Testing checklists -- suggest a single checkbox for a macro task rather than a long line of them, e.g. 

```
  - [ ] Setup:
    * Foo
    * Bar
    * Baz
  - [ ] ...
```

Because the checklists are a hassle to check off one at a time.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java (hunk 1 above)
Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: It sounds like `mayPredict` would be better in theory -- cleaner than a de-reg and re-reg. Is it possible to fix the underlying design issue there?

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: ok, I've updated so `mayPredict` will override to `false` when entering a password field.

File: android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java [hunk 2]
```diff
@@ -112,6 +117,21 @@ public void onStartInput(EditorInfo attribute, boolean restarting) {
       KMManager.setNumericLayer(KeyboardType.KEYBOARD_TYPE_SYSTEM);
     }
 
+    // Temporarily disable predictions if entering a hidden password field
+    if (KMManager.isHiddenPasswordInputType(inputType)) {
```
Comment (mcdurdin) [inline android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java]: I am a little concerned that this has the side effect of setting a global state variable (`shouldOverrideMayProtect`) which is not great for maintenance in the future. Is it possible to either (a) rename, or (b) preferably, refactor this so no global variable is required?

Comment (darcywong00) [reply android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java]: I've separated the getter / setter of the private state variable.

**Comment by MakaraSok** [comment]
@darcywong00 
_All tests completed_ and every thing works as expected according to the steps provided.
