### PR TITLE
fix(android): rotation is not updating keyboard

### LINKED ISSUE #5211: bug(android): Inconsistent OSK dimensions on rotation - system keyboard
During testing of #5201, I noticed the OSK height doesn't reliably resize to the correct height when toggling between portrait and landscape orientation. (landscape usually ends up "taller" than what the default dimension specifies)

Going into the globe button menu and existing seems to refresh OSK to the correct dimensions.
This affects both in-app and system keyboard; this issue is about the system keyboard. See #5252 for in-app.

Keyman 15

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #5211.

### CODE REVIEW

**Comment by mcdurdin** [comment]
# User Testing

* Please verify that rotation of the system keyboard works in a variety of apps - physical and virtual devices.
* Can you also test with existing 14.0 stable and see if that goes wrong; if so, we'll need to cherry-pick this to stable-14.0.

@MakaraSok

File: android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java [hunk 1]
```diff
@@ -165,6 +165,7 @@ public void onStartInput(EditorInfo attribute, boolean restarting) {
   @Override
   public void onStartInputView(EditorInfo attribute, boolean restarting) {
     super.onStartInputView(attribute, restarting);
+    setInputView(onCreateInputView());
```
Comment (darcywong00) [inline android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java:168]: Is there a fix for the in-app keyboard because I had issues while rotating that one too?

Comment (mcdurdin) [reply android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java:168]: I haven't seen the rotation issues for the in-app keyboard? We'll need to investigate that separately I think. Can you document a repro?

Comment (darcywong00) [reply android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java:168]: @MakaraSok attached some screenshots while testing https://github.com/keymanapp/keyman/pull/5201#issuecomment-853650978

Comment (darcywong00) [reply android/KMAPro/kMAPro/src/main/java/com/keyman/android/SystemKeyboard.java:168]: We probably also want this on SystemKeyboard for KMSample2 and FV app

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
> We probably also want this on SystemKeyboard for KMSample2 and FV app

Patched.

> @MakaraSok attached some screenshots while testing [#5201 (comment)](https://github.com/keymanapp/keyman/pull/5201#issuecomment-853650978)

I've split this to a new issue for in-app keyboard rotation, #5252.

Once @MakaraSok has completed testing, I will merge this and cherry-pick this one to stable-14.0.

**Comment by MakaraSok** [comment]
Both versions were tested as a system keyboard on a physical and virtual device and their behavior are consistent:
- the keyboard disappears in some apps such as FB messenger, Twitter, Google News.
- the keyboard seems to take a moment to load and rearrange itself (see: https://www.youtube.com/watch?v=b53zVwFDZCQ)

Other than these, nothing is found to be out of the normal. The black bar above the keyboard doesn't stay even though it does appear for brief moment.

**Comment by mcdurdin** [comment]
> * the keyboard disappears in some apps such as FB messenger, Twitter, Google News.

This does not appear to be specific to Keyman -- I replicated it with other keyboard apps.

**Comment by MakaraSok** [comment]
> This does not appear to be specific to Keyman -- I replicated it with other keyboard apps.

Gboard stays on Twitter, while consistently disappears on FB Messenger and Google News.

**Comment by mcdurdin** [comment]
> Gboard and Samsung Keyboard stays on Twitter, while consistently disappear on FB Messenger and Google News.

The Twitter experience is kinda weird. Doesn't look like Keyman is working correctly in landscape there. Let's look at that as a separate thing.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.66-alpha](https://keyman.com/downloads/releases/alpha/15.0.66)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.75-alpha](https://keyman.com/downloads/releases/alpha/15.0.75)
