### PR TITLE
fix(common/models): fixes quote-adjacent pred-text suggestions

### LINKED ISSUE #6900: bug(common/models): LM replaces left quote and character(s) with the selected option
https://user-images.githubusercontent.com/28331388/176589116-07c5b8b2-39bb-42a1-8455-ff3f7a9d935f.mov

The clip above shows that the left quote and a character being typed get replaced with the word selected off of the suggestion banner. 

This behavior is not unique to the language script being used. EuroLatin (SIL) keyboard also exhibits this behavior when testing on mobile devices, i.e. iOS and Android. In the Keyman app with the default keyboard on, type a double quote `"` and then <kbd>t</kbd>, now select `the` of of the suggestion banner to see that `the` replace both `"` and `t`.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #6900.  The actual internal issue was technically a bit more general, theoretically capable of happening in more than just "quote-adjacent" scenarios, but the behavior has been most evident there.

The predictive-text engine previously assumed that wordbreaking should only occur after whitespace characters (like a space or a newline).  However, here's one common case where this assumption is wrong when using the default Unicode wordbreaker: the text `"Hello"` gets word-broken into `['"', 'Hello', '"']`.  (That is, quotes on the side of a word like that, rather than inside of it, are treated as a different "word" - without whitespace.)

To distill what caused the problem:  internally... the predictive-text engine was expecting the leading `"` character to be whitespace whenever this occurred, and so _assumed_ it to _be_ whitespace, ignoring reality, causing a one-character context-desync with the main Web engine, and leading to the reported erroneous behavior.  (With a couple of other nits here and there on the side, to boot.)

## User Testing

GROUP_ANDROID:  Test using any Android device (or simulated device) supporting Keyman.
GROUP_WEB_HOST:  Test using the "Predictive Text: robust testing" Web test page

TEST_QUOTE_O:  Using the default English keyboard for your test environment, type `'` followed immediately by `o`.
- If most of the displayed suggestions do not begin with an 'o', _**FAIL**_ this test.
  - Do not fail if "I" is one of them - it's a super-common word, and 'o' does neighbor 'i'.
- Apply any of the displayed suggestions.  If the `'` mark is replaced, _**FAIL*__ this test.

TEST_QUOTE_OP:  Using the default English keyboard for your test environment, type `'` followed immediately by `o`, then `p`.
- If most of the displayed suggestions do not begin with an 'op', _**FAIL**_ this test.
  - Do not fail if "OP" is suggested, despite its capitalization.
- Apply any of the displayed suggestions.  If the `'` mark is replaced, _**FAIL**_ this test.

TEST_OP:  Using the default English keyboard for your test environment, type `you`, add a space, then type `o`, then `p`.
- If most of the displayed suggestions do not begin with an `op`, _**FAIL**_ this test.
  - Do not fail if "OP" is suggested, despite its capitalization.
- Apply any of the displayed suggestions.  If unwanted effects occur, _**FAIL**_ this test.
  - No prior whitespace should be deleted and the suggestion should be cleanly applied.
  - Example:  applying `open` to `you op` should result in `you open ` for the full context.

### CODE REVIEW

**Comment by jahorton** [comment]
... fully posted it, then realized part of the first drafted unit test still fails.  Still a lot better than before; just the one last nit to get, I guess.

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID: Test using any Android device (or simulated device) supporting Keyman.

* **TEST_QUOTE_O (PASSED):** Tested this with the attached PR build (keyman 16.0.56-alpha-test-7205)in the Android Mobile device Ver 11.0 and I noticed most of the displayed suggestions begin with an 'o'. Applied suggestions did not replaced by the ' mark. 

   


* **TEST_QUOTE_OP (PASSED):** Tested this with the attached PR build in the Android Mobile device Ver 11.0 and I noticed that most of the displayed suggestions begin with an 'op'. Applied suggestions did not replaced by the ' mark. 

   


* **TEST_OP (PASSED):** Tested this as per the instructions and most the of the displayed suggestions begin with an op. Applying 'open' to 'you op' results 'you open' for the full context.

**Comment by bharanidharanj** [comment]
### GROUP_WEB_HOST: Test using the "Predictive Text: robust testing" Web test page

* **TEST_QUOTE_O (PASSED):** Tested as per the instructions using the "Predictive Text: robust testing" Web test page and it is working as expected. 

   


* **TEST_QUOTE_OP (PASSED):** Tested as per the instructions using the "Predictive Text: robust testing" Web test page and it is working as expected. 

   

* **TEST_OP (PASSED):** Tested as per the instructions using the "Predictive Text: robust testing" Web test page and it is working as expected.

File: common/web/lm-worker/src/transformUtils.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+    return insert == '';
+  }
+
+  static isBackspace(transform: Transform): boolean {
+    return transform.insert == "" && transform.deleteLeft > 0 && !transform.deleteRight;
+  }
+
+  static isEmpty(transform: Transform): boolean {
+    return transform.insert == '' && transform.deleteLeft == 0;
```
Comment (darcywong00) [inline common/web/lm-worker/src/transformUtils.ts:23]: Should this also check `transform.deleteRight`?

**Comment by mcdurdin** [comment]
I notice both web and lm test builds failed. Not sure if that is new to this PR or longstanding instability. We need to get on top of these failures (even if it means disabling tests because we can't get them stable).

File: common/web/lm-worker/src/correction/context-tracker.ts [hunk 2]
```diff
@@ -139,8 +140,10 @@ namespace correction {
 
       // Track the Transform that resulted in the whitespace 'token'.
       // Will be needed for phrase-level correction/prediction.
-      whitespaceToken.transformDistributions = [transformDistribution]; 
-      
+      if(transformDistribution) {
+        whitespaceToken.transformDistributions = [transformDistribution];
+      }
```
Comment (mcdurdin) [inline common/web/lm-worker/src/correction/context-tracker.ts:145]: What will `whitespaceToken.transformDistributions` be if `transformDistribution` is falsy? Is it handled correctly elsewhere?

File: common/web/lm-worker/src/correction/context-tracker.ts [hunk 3]
```diff
@@ -27,13 +27,14 @@ namespace correction {
   export class TrackedContextToken {
     raw: string;
     replacementText: string;
+    newFlag: boolean = false;
```
Comment (mcdurdin) [inline common/web/lm-worker/src/correction/context-tracker.ts:30]: What is `newFlag`? Can you add a code comment?

File: common/web/lm-worker/src/model-compositor.ts [hunk 4]
```diff
@@ -160,12 +136,15 @@ class ModelCompositor {
...
+      let newToken = false;
       // Detect if we're starting a new context state.
       let contextTokens = contextState.tokens;
       if(contextTokens.length == 0 || contextTokens[contextTokens.length - 1].isNew) {
-        if(this.isEmpty(inputTransform) || this.isWhitespace(inputTransform)) {
-          newEmptyToken = true;
+        // Always note if we have a new token (so that we don't try to delete existing context)
+        newToken = true;
+        // If the new token is due to whitespace, or if we had a context-reset trigger this (thus, no input...)
+        // (Lingering question:  do we need the .isEmpty check here?  Track `prefixTransform` and find out.)
```
Comment (mcdurdin) [inline common/web/lm-worker/src/model-compositor.ts:146]: Is this a TODO? Do we need to sort this out now? Can we mark it as a TODO if we don't need to sort it out now?

File: common/web/lm-worker/src/transformUtils.ts [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+    if(transform.insert == '') { // Can actually register as 'whitespace'.
+      return false;
+    }
+
+    let insert = transform.insert;
+
+    insert = insert.replace(whitespaceRemover, '');
+
+    return insert == '';
+  }
```
Comment (mcdurdin) [inline common/web/lm-worker/src/transformUtils.ts:16]: This seems a little convoluted.

* I'm really not sure exactly what we are testing here. It seems like you are looking for `insert.match(/[\u0009...]$/)`? Is it intended to match having a single whitespace character on the end of the text? If so, then the function name is not very clear. If not, then AFAICT the function is not correct.

* `i` modifier should not be necessary on the regex -- there's no case to be insensitive about 🤣.

* Can we use a [character class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes) for the regex match rather than a set of characters? (e.g. `insert.match(/[\p{Z}\r\n]$/u)`. Note Chrome 50+ though (so we could have the shorter regex as a comment if we can't use it for back-compat reasons).

* Finally, can we have a javadoc comment rather than the in-function comment?

File: common/web/lm-worker/src/transformUtils.ts [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+
+  static isBackspace(transform: Transform): boolean {
+    return transform.insert == "" && transform.deleteLeft > 0 && !transform.deleteRight;
```
Comment (mcdurdin) [inline common/web/lm-worker/src/transformUtils.ts:19]:
```suggestion
    return transform.insert == "" && transform.deleteLeft > 0 && transform.deleteRight == 0;
```

Let's use the numeric comparisons consistently here and in `isBackspace`.

File: common/web/lm-worker/src/transformUtils.ts [hunk 7]
```diff
@@ -0,0 +1,25 @@
...
+  }
+
+  static isEmpty(transform: Transform): boolean {
+    return transform.insert == '' && transform.deleteLeft == 0 && !transform.deleteRight;
```
Comment (mcdurdin) [inline common/web/lm-worker/src/transformUtils.ts:23]:
```suggestion
    return transform.insert == '' && transform.deleteLeft == 0 && transform.deleteRight == 0;
```

**Review by mcdurdin — CHANGES_REQUESTED** [review]
So I am not entirely clear on the rationale behind some of the algorithm changes. It seems to make sense but I don't have a deep enough understanding of the whole module to really be 100% on it. Code itself looks okay, apart from the `isWhitespace` function which seems weird. Appreciate the refactoring of the three related functions into new TransformUtils class.

**Comment by jahorton** [comment]
> I notice both web and lm test builds failed. Not sure if that is new to this PR or longstanding instability. We need to get on top of these failures (even if it means disabling tests because we can't get them stable).

For the LMLayer, it's the test failure addressed by #7037 again.  (It happens on lmlayer worker + hosted-in-browser integration.)
Web's is similarly unrelated.

File: common/web/lm-worker/src/transformUtils.ts (hunk 5 above)
Comment (jahorton) [reply common/web/lm-worker/src/transformUtils.ts:16]: Keep in mind that I did not edit this function _at all_.  I simply extracted it from its prior home.  From `master`:

https://github.com/keymanapp/keyman/blob/80d7ce78bedccda20f73982ac74d26da73b5c63c/common/web/lm-worker/src/model-compositor.ts#L19-L33

This all dates back to #1851, and @eddieantonio was the one responsible for that regex: https://github.com/keymanapp/keyman/pull/1851#discussion_r300022560

Can't speak to why he didn't use a character class here, but I figure that there was some reason or other.  For what it's worth, following that character class link and drilling down to the actual classes:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes

I don't see a compatibility chart there.  Now, there are other ways to search for this...

https://caniuse.com/mdn-javascript_builtins_regexp_property_escapes

Note the minimum Chrome version listed there - if desktop Chrome didn't support these property escapes before version 64, I doubt that mobile had it implemented at that time.  This, to me, implies a strong chance that using them would break predictive text outright on non-updated Android 5.0 devices, at the least.

------

Where do you see a `$` in the regex string here?  Is it implied with the flags on the pattern?  It's certainly not present in plain-text.

File: common/web/lm-worker/src/transformUtils.ts (hunk 7 above)
Comment (jahorton) [reply common/web/lm-worker/src/transformUtils.ts:23]: Similar to the previous comment - this change will break things.

File: common/web/lm-worker/src/transformUtils.ts (hunk 6 above)
Comment (jahorton) [reply common/web/lm-worker/src/transformUtils.ts:19]: Check this commit and compare to the previous one & the unit-test results:  https://github.com/keymanapp/keyman/pull/7205/commits/9be8839685ae8d65fbae37ff5eb9ab836f863804

File: common/web/lm-worker/src/transformUtils.ts (hunk 5 above)
Comment (jahorton) [reply common/web/lm-worker/src/transformUtils.ts:16]: So... feel free to make an issue about the function feeling weird to you, but since there are no edits to this function within this PR, any potential changes should be considered out of scope here.

File: common/web/lm-worker/src/correction/context-tracker.ts (hunk 2 above)
Comment (jahorton) [reply common/web/lm-worker/src/correction/context-tracker.ts:145]: So, this is part of the `pushWhitespaceToTail` function.   We don't do predictions on whitespace 'tokens' presently, so nothing's trying to access it right now.

It may matter when we start looking at phrase-level suggestions.  That's part of why a whitespace token is even tracked; it's part of the foundation work I laid out back in 12.0 to ensure the design wouldn't need a major overhaul if and when we start on that potential feature.  But... we aren't there yet.

Not that it'd hurt much to put an `else { ... = [] }` in there for now, admittedly.  (Aside from maybe needing a unit test tweak or two.)

Comment (mcdurdin) [reply common/web/lm-worker/src/correction/context-tracker.ts:145]:
```suggestion
      whitespaceToken.transformDistributions = transformDistribution ? [transformDistribution] : [];
```

File: common/web/lm-worker/src/transformUtils.ts (hunk 5 above)
Comment (mcdurdin) [reply common/web/lm-worker/src/transformUtils.ts:16]: Yep, happy to postpone fixing it. Wonder if this function may be causing issues though because it seems weird...

> Where do you see a `$` in the regex string here? Is it implied with the flags on the pattern? It's certainly not present in plain-text.

It's implied by `return insert == '';` -- so this will only be true if the regex deletes everything in the string, which means it must be the last char in the string.

**Comment by mcdurdin** [comment]
> For the LMLayer, it's the test failure addressed by #7037 again. (It happens on lmlayer worker + hosted-in-browser integration.)
> Web's is similarly unrelated.

OK. Think we need to get #7037 merged. I'm not excited about it because it's hard to 100% verify, being timing-based, but the noise is causing trouble in dev processes. And I think we need another round on fixing the web failing tests because again, it's really hard to tell the relationship in failed tests.

**Comment by jahorton** [comment]
Just swapped the approach for something clearer (and less fiddly, to boot!).  So...

@keymanapp-test-bot retest all

File: common/web/lm-worker/src/correction/context-tracker.ts (hunk 2 above)
Comment (jahorton) [reply common/web/lm-worker/src/correction/context-tracker.ts]: And... yep, doesn't even break any unit tests to do so.  May as well indeed.

File: common/web/lm-worker/src/transformUtils.ts (hunk 5 above)
Comment (jahorton) [reply common/web/lm-worker/src/transformUtils.ts:16]: Keep in mind that we're dealing with incoming transforms - in essence, this is used on incoming keystrokes, not existing context.  (Hence the classname of `TransformUtils`.  (Emphasis on **Transform**)

```typescript
isWhitespace({
  insert: 'a ',
  deleteLeft: 0
)
```

will yield `false` - after all, that 'a' will remain.

Meanwhile, this one:

```typescript
isWhitespace({
  insert: '\u{0020}\u{0020}\u{0020}\u{0020}', // four spaces in a row; doesn't format well
  deleteLeft: 0                               // on web without the \u stuff
)
```

will yield `true`.  The design is meant to check if any prediction-triggering keystroke is _fully_ whitespace or not.

Its uses do imply a few assumptions, though - we're not doing any `hasWhitespace` checks, which might be more valid for niche, likely-unintuitive scenarios.

Comment (mcdurdin) [reply common/web/lm-worker/src/transformUtils.ts:16]: Are you sure? I just ran this:

```ts
let foo = [
  'a ',
  ' ',
  '   ',
  ' x x ',
  'xxx   ',
  'xxx'
];

for(let f of foo) {
  console.log(`"${f}": `, isWhitespace(f));
}
```

and the result was:

```
$ node foo.js
"a ":  true
" ":  true
"   ":  true
" x x ":  true
"xxx   ":  true
"xxx":  false
```

Comment (mcdurdin) [reply common/web/lm-worker/src/transformUtils.ts:16]: If it is supposed to check if a given transform is 100% whitespace and not empty, then:

```js
let whitespace = /^[\u0009\u000A\u000D\u0020\u00a0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u200b\u2028\u2029\u202f\u205f\u3000]+$/; 

return transform.insert.match(whitespace) !== null;
```

File: common/web/lm-worker/src/transformUtils.ts (hunk 7 above)
Comment (mcdurdin) [reply common/web/lm-worker/src/transformUtils.ts:23]: Okay then -- but `transform.deleteLeft == 0` is okay? It's just a little inconsistent, that's all :grin:

File: common/web/lm-worker/src/transformUtils.ts (hunk 5 above)
Comment (jahorton) [reply common/web/lm-worker/src/transformUtils.ts:16]: Oh right... regex matching by default gets _the portion_, rather than checking against the whole.  I tend to forget that sometimes.

Comment (jahorton) [reply common/web/lm-worker/src/transformUtils.ts]: Sorry on the delay.  Just got back to this.

Though, I did go ahead and add unit testing for the function while I was at it.

File: common/web/lm-worker/src/transformUtils.ts [hunk 8]
```diff
@@ -1,18 +1,14 @@
...
   static isWhitespace(transform: Transform): boolean {
     // Matches prefixed text + any instance of a character with Unicode general property Z* or the following: CR, LF, and Tab.
-    let whitespaceRemover = /.*[\u0009\u000A\u000D\u0020\u00a0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u200b\u2028\u2029\u202f\u205f\u3000]/i;
+    const whitespaceRemover = /^[\u0009\u000A\u000D\u0020\u00a0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u200b\u2028\u2029\u202f\u205f\u3000]+$/i;
 
     // Filter out null-inserts; their high probability can cause issues.
-    if(transform.insert == '') { // Can actually register as 'whitespace'.
+    if(transform.insert == '') {
       return false;
     }
```
Comment (mcdurdin) [inline common/web/lm-worker/src/transformUtils.ts:9]: This shouldn't be needed as the regex match will exclude it.

File: common/web/lm-worker/src/transformUtils.ts [hunk 9]
```diff
@@ -1,18 +1,14 @@
 class TransformUtils {
   static isWhitespace(transform: Transform): boolean {
     // Matches prefixed text + any instance of a character with Unicode general property Z* or the following: CR, LF, and Tab.
```
Comment (mcdurdin) [inline common/web/lm-worker/src/transformUtils.ts:3]:
```suggestion
    // Matches a string that is entirely one or more characters with Unicode general property Z* or the following: CR, LF, and Tab.
```

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.64-alpha](https://keyman.com/downloads/releases/alpha/16.0.64)
