### PR TITLE
fix(linux): start system service when switching keyboards

### LINKED ISSUE #13171: bug(linux): delayed output with Keyman keyboard
After a reboot and switching to a Keyman keyboard, with #11535 merged, the first keypress doesn't output anything. The second keypress then outputs the result of the first keypress and so on.

### PR DESCRIPTION
**Pull request by ermshiperete**
This change fixes #13171 where we failed to output after the first keypress because the keyman system service had to be started. This change introduces a new method `Ping` that we call to force keyman-system-service to be started.

Fixes: #13171

# User Testing

Can be tested on Ubuntu with Gnome Shell and X11, e.g. Ubuntu 24.04 Noble with Gnome Shell and X11.

**TEST_TERMINAL_IPA:** Open a terminal, then switch to "IPA (SIL)" keyboard. Type `an>`. Verify that the result is "aŋ".

### CODE REVIEW

File: linux/ibus-keyman/src/KeymanSystemServiceClient.cpp [hunk 1]
```diff
@@ -111,6 +112,23 @@ KeymanSystemServiceClient::CallOrderedOutputSentinel() {
   }
 }
 
+void KeymanSystemServiceClient::Ping() {
```
Comment (darcywong00) [inline linux/ibus-keyman/src/KeymanSystemServiceClient.cpp:115]: Maybe a little more descriptive
```suggestion
void KeymanSystemServiceClient::PingKeymanSystemService() {
```

File: linux/keyman-system-service/src/KeymanSystemService.cpp [hunk 2]
```diff
@@ -76,11 +76,22 @@ on_call_ordered_output_sentinel(
...
 }
 
+static int32_t
+on_ping(
+  sd_bus_message *msg,
+  void *user_data,
+  sd_bus_error *ret_error
+) {
+  *ret_error = SD_BUS_ERROR_NULL;
+  return sd_bus_reply_method_return(msg, "s", "pong");
```
Comment (darcywong00) [inline linux/keyman-system-service/src/KeymanSystemService.cpp:86]: Where is this handled?
> Verifies that the keyman-system-service is started and available

Is this not needed?
```cpp
KeymanSystemService *service = static_cast<KeymanSystemService *>(user_data);
  service->Ping();
```

**Review by mcdurdin — APPROVED** [review]
I think LGTM. I guess this adds another IPC round trip to each keystroke, which is not ideal but not sure I see an obvious way around it.

There may still be a race where the system service stops between ping and keystroke but that seems esoteric enough that we can probably ignore it.

From what I understand, otherwise, the ping dbus call is guaranteed to return before the keystroke event, which should ensure that the keystroke is not dropped.

**Comment by dinakaranr** [comment]
# Test Results
I tested this issue with the attached Keyman"18.0.188-alpha-test-13172" build(11/02/2025) on the Ubuntu noble 24.04 X11 environment. Here, I am sharing my observation.

* **TEST_TERMINAL_IPA (Passed):**
1. Install Keyman the "Keyman-18.0.188-alpha-test-13172" attached from this PR.
2. Launch the Keyman app.
3. Open the "Configuration" window.
4. Install the "ipa_sil" keyboard.
5. Open a terminal.
6. Switch to the "IPA (SIL)" keyboard. 
7. Type an>. 
8. Verified that the result is "aŋ".
Thank you.

**Comment by ermshiperete** [comment]
> I guess this adds another IPC round trip to each keystroke, which is not ideal but not sure I see an obvious way around it.

No, this only gets called when the user switches keyboards.

File: linux/ibus-keyman/src/KeymanSystemServiceClient.cpp (hunk 1 above)
Comment (ermshiperete) [reply linux/ibus-keyman/src/KeymanSystemServiceClient.cpp:115]: Currently this matches the method names on the DBus interface, so I think I leave it as `Ping`. But thinking of it, `CallOrderedOutputSentinel` isn't probably that good of a method name, but I can't think of  a better one.

**Comment by mcdurdin** [comment]
> No, this only gets called when the user switches keyboards.

OK, great, then no concerns at all!

File: linux/keyman-system-service/src/KeymanSystemService.cpp (hunk 2 above)
Comment (ermshiperete) [reply linux/keyman-system-service/src/KeymanSystemService.cpp:86]: We could add a `KeymanSystemService::Ping` method, but since the method does nothing (it's only purpose is to get keyman-system-service started if isn't running already) I don't see much value in doing that.

**Review by darcywong00 — APPROVED** [review]
lgtm
