### PR TITLE
fix(web): banner scroll positioning after reversions

### LINKED ISSUE #10642: bug(web): `TypeError: null is not an object (evaluating 'this.predictionContext.accept(d.suggestion).then')`
Sentry Issue: [KEYMAN-WEB-H6](https://keyman.sentry.io/issues/4886295380/?referrer=github_integration)

```
TypeError: null is not an object (evaluating 'this.predictionContext.accept(d.suggestion).then')
  at <anonymous> (@keymanapp/keyman/web/src/engine/osk/src/banner/suggestionBanner.ts:609:62)
  at <anonymous> (@keymanapp/keyman/common/web/gesture-recognizer/src/engine/headless/gestures/matchers/gestureSequence.ts:254:10)
...
(1 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #10642.

@keymanapp-test-bot skip

### CODE REVIEW

File: common/web/input-processor/src/text/prediction/predictionContext.ts [hunk 1]
```diff
@@ -188,7 +188,8 @@ export default class PredictionContext extends EventEmitter<PredictionContextEve
         this.recentAccept = false;
         this.recentRevert = true;
       }
-      return null;
+
+      return Promise.resolve(null);
```
Comment (jahorton) [inline common/web/input-processor/src/text/prediction/predictionContext.ts:192]: Why this matters:

https://github.com/keymanapp/keyman/blob/e8949831da5b71cdebcc09330a57d82779890272/web/src/engine/osk/src/banner/suggestionBanner.ts#L609-L612

Making sure we always return a Promise, even if it doesn't contain anything notable, is the simplest solution.

The Promise otherwise exists to facilitate unit testing, and that's something safe to tweak in response.

File: common/web/input-processor/tests/cases/predictionContext.js [hunk 2]
```diff
@@ -285,7 +285,7 @@ describe("PredictionContext", () => {
     let returnValue = predictiveContext.accept(reversion);
 
     // 'accepting' a reversion performs a rewind; there's no need for async ops here.
-    assert.isNull(returnValue); // as per the method's spec.
+    assert.isNull(await returnValue); // as per the method's spec.
```
Comment (mcdurdin) [inline common/web/input-processor/tests/cases/predictionContext.js:288]: It would be cleaner to put the await in the original call rather than bury it in the assertion I think.

```
 let returnValue = await predictiveContext.accept(reversion);
```

File: common/web/input-processor/src/text/prediction/predictionContext.ts (hunk 1 above)
Comment (mcdurdin) [reply common/web/input-processor/src/text/prediction/predictionContext.ts:192]: Agree this is better and more consistent.

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.262-alpha](https://keyman.com/downloads/releases/alpha/17.0.262)
