### PR TITLE
fix(ios): prevents post-restore kbd issues by refreshing kbd

### LINKED ISSUE #2184: [iOS] App unresponsive on re-entry
@jahorton reports with the latest Keyman 12.0 stable build
> looks like the app goes unresponsive on re-entry. Force-quitting and starting the app fresh works around the issue.
> Fortunately, it doesn't seem to affect the system keyboard. Just in-app

### LINKED ISSUE #2292: [iOS] Locked keyboard orientation
**Describe the bug**
There are a few system interactions with the Keyman app that can result in a locked and internally-misaligned keyboard orientation.  This only affects the in-app keyboard, but when it triggers, the problem will persist until the app is force-quit or the user enters and exits one of the settings screens (as this action generally results in a full reload of the embedded keyboard).

**To Reproduce**
The easiest reproduction I've found:
1. Put your device in "portrait" orientation.
2. Open the Keyman app.  Feel free to type a bit, but it shouldn't be necessary.
3. Lock your device.
4. Put your device in landscape orientation.
5. Unlock your device - and do NOT change its orientation.

When you've done so, you should be greeted by the following (minus the blue rectangle):

Screen Shot 2019-11-05 at 8 31 50 AM

So yeah, what's up with the blue rectangle?  That's from a debug session with Safari's "Inspector" tool - it turns out that not only is the keyboard poorly sized, _**all keyboard touch targets are incorrectly located**_ when the bug triggers.  Basically, it breaks the app until an unintuitive resetting action occurs.

Fun side note - in testing this on a real iPhone SE, this repro _may_ also trigger #2184.  Unfortunately, it's not a reliable trigger.

---
  
**iPhone/iPad:**
 - Device: Simulator (pick a device), verified on a real iPhone SE
 - OS: iOS 13.1
 - Keyman version: 12.0.53
 - Target application: Keyman

---

An alternate potential reproduction (less reliable):
1. Put your device in "portrait" orientation.
2. Open the Keyman app.  Feel free to type a bit; it seems to help somewhat, but this may be a 'placebo'.
3. Click the "Share" button.
4. Put your device in landscape mode.
5. Back out of the "Share" activity.

This was the first repro I found, as I was investigating #2260 at the time.  Even when the repro doesn't fully succeed, you can usually observe a possibly-enlightening detail:  events will trigger slowly enough that you should see the same configuration as the screenshot above before the keyboard self-corrects.  So, it's usually a "near-repro," if that makes any sense.

It's also far harder to reproduce the issue on a real device with this "near repro" - the Simulator's your best bet here.  I've noticed that Simulator generally does run slower than a real device b/c of emulation or something similar... so there's probably something timing-related here.  The first repro _may_ also result in some nasty graphical artifacting within Simulator.

So, possible app re-entry race condition?

### LINKED ISSUE #6542: bug(ios/engine): predictive text stability after restoring from background
**Describe the bug**
I've never bothered to write this up until now, but I've long-noted interesting... "stability" issues arise within the Keyman app (at minimum) whenever it has been restored from a background state.  Just to be clear on that...

1.  I've opened the Keyman app and used it.
2. Then, I used the Home button to return to the main iOS screen.
    - It may help to use another app for about a minute before continuing.
    - I strongly suspect that OS behaviors / how the app's managed in the background is a major contributing factor
3. After that, I re-opened the Keyman app. 

No launch screen was shown; it was clearly restored from a background state.

I have a feeling this may be somewhat indicative of some sort of WebView bug, possibly related to WebWorkers.  Reasoning:

- Keyboards seem to be pretty stable and suffer no issues whatsoever.
- Predictive text, however, is usually outright broken.

It's almost as if the WebWorker 'dumped' the predictive text model when it was forced to background.  Or perhaps something in the pipeline forced a major context desync?

Worth note:
- no amount of whitespace and/or backspace will restore predictive text while it's in that broken state.
- despite that... you _can_ see brief flashes as if it were trying to show suggestions.  But then it almost immediately clears them.
- There is a chance you may need to leave the caret after whitespace / with an empty context when following step 1.  It seems more consistent when your first keystroke after restoring the app starts a new word.
- However:
    - If I swap keyboards and return, the problem disappears.  (Note:  have not tested swapping between keyboards using the same model.)
    - If I access the app's menu and return the problem disappears.
        - If entering the Settings menu, this should have a side-effect of reloading the model, so... kinda expected.
        - That said... I think just pressing the `...` to have the menu drop down (hides the keyboard) and cancelling (redisplaying it) is enough to restore functionality.

**To Reproduce**
See above.  Predictive text will usually break on the first keystroke after the app is restored.

**Expected behavior**
Predictive text should work immediately, without issue, rather than breaking.

---

**Keyman for iPhone/iPad:**
 - Device: iPhone SE, likely others
 - OS: iOS 15.4.1, also earlier.  (Pretty sure I also saw it in 14.x, if not even before.)
 - Keyman version:  15.0.234-beta
 - Target application:  Keyman

---

Other notes:

- There's a good chance that this is in-app only; the app-extension life cycle generally will not reuse old copies of the system keyboard in different apps.  I'm pretty sure you can see the keyboard load process on the first keyboard use in an app after it has been restored from background, which would further support this hypothesis.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #6542.
Fixes #2184.

This works around a longstanding behavior we've noted on certain iOS devices where our keyboards and/or predictive text become "unstable" in one manner or another after the Keyman app has been restored from a backgrounded state.  While not the most elegant of solutions (it has user-perceivable effects), simply refreshing the keyboard host page will remove that "instability".

My personal device has always been affected in one way or another when restoring the Keyman app from the background, though the manner has varied at times.  Either way, I'm aiming to finally get that fixed.

## User Testing

TEST_IOS_APP_RESTORE:  Using the Keyman app for iPhone and iPad, verify that the keyboard works correctly after the app is restored from a background state.

- At a minimum, do the following tests with `sil_euro_latin`:
    - Use a longpress + select a subkey
    - Use a downward flick
    - Try a multitap on the numeric key to change layers.
    - Try holding a layer-switching key and typing with the temporarily-active layer.
- If standard gesture visualizations do not show up or operate correctly, FAIL this test.
- If the output or layer-switches do not act as expected, FAIL this test.

### CODE REVIEW

File: ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift [hunk 1]
```diff
@@ -74,6 +74,14 @@ class KeymanWebViewController: UIViewController {
     super.init(nibName: nil, bundle: nil)
 
     _ = view
+
+    NotificationCenter.default.addObserver(
+      forName: UIApplication.willEnterForegroundNotification,
```
Comment (jahorton) [inline ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift:79]: Sadly, I don't believe this can affect #11202 - this is an _app_ notification, rather than a notification intended for use by app-extensions (like third-party keyboards).

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_IOS_APP_RESTORE (PASSED):** Tested with the attached PR build (Keyman 17.0.305-beta-test-10952) on an iPhone 13 Mobile device (iOS 17.4) and here is my observation: 1. In the default keyboard, verified that the longpress mend and selecting the sub key is working as expected. 2. Confirmed that the downward flick gesture displayed the special characters.. 3. Verified the multitap on the numeric key to change layers is working correctly. 4. Verified holding a layer-switching key and typing with the temporarily-active layer is working as expected.

**Review by mcdurdin — APPROVED** [review]
This looks like a reasonable stop-gap, but it would be good to figure out what is causing the instability rather than just bypassing it, long term.

**Comment by jahorton** [comment]
After a bit more searching... maybe I've found something this time?

- https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455639-webviewwebcontentprocessdidtermi

We'd need to test and see if this is being called when our app is restored in this scenarios to be sure it's tied to the behavior that's been seen, of course.

Ref: https://github.com/ionic-team/capacitor/discussions/5488#Potential_solution

> The thing we need to be sensitive to is that when a WebView background termination occurs, webViewWebContentProcessDidTerminate() is invoked when the app is coming back into the foreground  [...]

Noting other issues from ionic and from react, they've seen cases where the WebView is 100% crashed, showing a blank page.  We haven't had _that_ issue, though we also aren't navigating across pages or doing other fancy web-server stuff on the back-end - it's just one page for us.  There's a fair shot that iOS's WebView is doing its best to restore our page after such a termination but is coming up short.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.311-beta](https://keyman.com/downloads/releases/beta/17.0.311)
