### PR TITLE
[Mac] support double clicking kmp

### LINKED ISSUE #511: Double-clicking on a .kmp on macOS should install the keyboard
I'm seeing reports that double-clicking a .kmp file on macOS shows an error: https://community.software.sil.org/t/amharic-font-not-installing/515

It should be installing the keyboard. If this is not supported, this is a new feature; otherwise it is a bug...

### PR DESCRIPTION
**Pull request by tombogle**
Fixes #511

### CODE REVIEW

File: mac/Keyman4MacIM/Keyman4MacIM/KMPackage.m [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+    }
+    [[NSFileManager defaultManager] removeItemAtPath:tempFile error:nil];
+    return didUnzip;
+}
+
+-(BOOL)userConfirmsInstallationOfPackageFile:(NSString *)fileName {
+    NSAlert *alert = [[NSAlert alloc] init];
+    [alert addButtonWithTitle:NSLocalizedString(@"Yes", @"Alert button")];
+    [alert addButtonWithTitle:NSLocalizedString(@"No", @"Alert button")];
+    [alert setMessageText:NSLocalizedString(@"Install Keyman Package?", @"Alert message text when user double-clicks a KMP file.")];
```
Comment (darcywong00) [inline mac/Keyman4MacIM/Keyman4MacIM/KMPackage.m]: I'm not familiar with the dialogs used on Keyman Mac. Do we want some consistency with the Keyman Desktop experience? 

On Windows, the confirmation buttons are "Install" / "Cancel".

install confirmation

Comment (tombogle) [reply mac/Keyman4MacIM/Keyman4MacIM/KMPackage.m]: At least currently, I don't even unzip the KMP before asking the question. I could try to make it more like that, but it would be a bit more work. Just changing the button text is easy enough. I'm kind of thinking that if someone double clicks a KMP, they either did it on purpose and know what they're trying to install, or they did it by accident and will click No (or cancel). My inclination is to go ahead and merge what I have working and then consider additional enhancements down the road (possibly for version 10, but given the number of other things that need to be done, probably later).

Comment (mcdurdin) [reply mac/Keyman4MacIM/Keyman4MacIM/KMPackage.m]: Agree with @tombogle's assessment here. Let's move extra enhancements into a future version.

Comment (mcdurdin) [reply mac/Keyman4MacIM/Keyman4MacIM/KMPackage.m]: The main reason to have the dialog is to give some continuity when the user clicks it and then it appears in KM Configuration window, correct?

File: mac/Keyman4MacIM/Keyman4MacIM/KMPackage.m [hunk 2]
```diff
@@ -82,4 +74,51 @@ -(BOOL)readFromData:(NSData *)data ofType:(NSString *)typeName error:(NSError *
...
+    BOOL result = [alert runModal] == NSAlertFirstButtonReturn;
+    return result;
+}
+
+// This tells the system that we aren't reading the Keyman Package file lazily.
+-(BOOL) isEntireFileLoaded {
+    return YES;
+}
+
+//-(BOOL)readFromData:(NSData *)data ofType:(NSString *)typeName error:(NSError * _Nullable __autoreleasing *)outError {
```
Comment (mcdurdin) [inline mac/Keyman4MacIM/Keyman4MacIM/KMPackage.m]: It'd be good to remove this commented code before merge.

Comment (tombogle) [reply mac/Keyman4MacIM/Keyman4MacIM/KMPackage.m]: Thanks for the reminder. I wanted to include it in an intermediate commit just in case I ever needed to go back.
