### PR TITLE
Fix shift key text

### LINKED ISSUE #643: Fix styling for shift-on on touch layouts
On mobile layouts, the styling on the shift layer results in a washed out shift button.

From https://keymanweb.com/?tier=alpha#fr,Keyboard_french in mobile viewport

shift layer

And on Alt-Gr

alt gr

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #643 

Ensure shift key always has some text. `osk.modifierSpecials` doesn't have text defined for basic `shift` so the *shift* key on the shift layer was previously getting `undefined` for text.

### CODE REVIEW

**Comment by darcywong00** [comment]
If a keyboard doesn't specify text for `K_SHIFT`, should KMW auto-fill that in to `*Shift*`?

This came up in the issue115 keyboard

**Comment by mcdurdin** [comment]
No, we only treat the special cases `*Shift*` etc for replacement. If the key is blank, it is blank. That's the developer's choice.

**Comment by mcdurdin** [comment]
This looks okay to me but I'd like @jahorton to check the fix before merge.

File: web/source/kmwosk.ts [hunk 1]
```diff
@@ -3276,7 +3276,7 @@ if(!window['keyman']['initialized']) {
           if(n > 0 && shiftKey != null) {
             shiftKey['sp']=osk.buttonClasses['SHIFT-ON'];
             shiftKey['sk']=null;
-            shiftKey['text'] = osk.modifierSpecials[layers[n].id];
+            shiftKey['text'] = osk.modifierSpecials[layers[n].id] ? osk.modifierSpecials[layers[n].id] : "*Shift*";
```
Comment (jahorton) [inline web/source/kmwosk.ts]: I think it would be a far better idea to simply extend the `osk.modifierSpecials` array to include non-chiral layer special key definitions.  That, or do both and use this as a last-case catch.

As this is, alternate layer shift keys for things like, say, `ctrl-alt`, will simply use the base `*Shift*` character at present as well rather than the more-consistent `*AltGr*` character that represents the CTRL+ALT shifting state.

Comment (darcywong00) [reply web/source/kmwosk.ts]: I've added labels for: `shift`, `ctrl`, `alt`, and `ctrl-alt` (`*AltGr*`)
