### PR TITLE
fix(web): banner suggestion resizing after device rotation

### LINKED ISSUE #10477: bug(android): The predictive text does not completely adjust its width after changing the mobile to landscape orientation
### Describe the bug

It seems like there is an issue with adjusting the width of predictive text after changing the orientation from portrait to landscape mode.

### Reproduce the bug

1. Install Keyman 17.0.249-alpha build.
2. Open Keyman In-App.
3. We may observe that the predictive texts appear from left to right, filling the width of the suggestion banner.
4. Change the Mobile Orientation from Portrait to Landscape. 
5. Here, I observed that the predictive text is visible, but it doesn't extend to the full width of the suggestion banner. Seems to be an issue. 

..Predictive text in Portrait view

   

..Predictive text in Landscape view

   

### Expected behavior

When we change the mobile to landscape orientation, the predictive texts should occupy the entire width of the suggestion banner.

### Related issues

_No response_

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.249-alpha

### Operating system

Android 5.0, 9.0, 12.0

### Device

Android 12.0 /  API 31 emulator, Redmi Note 8 Pro

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #10477.

The predictive banner's suggestions are now automatically resized when rotating device orientation.  It's more complex than it was before #7934, when basic width-% styling was sufficient.   Fortunately, the fancy-banner layout logic was relatively easy to separate from the suggestion-update logic for use in layout refreshes.

## User Testing

TEST_BANNER_ROTATION:

1. Open Keyman In-App.
2. Verify that the predictive texts appear from left to right, filling the width of the suggestion banner.
3. Change the Mobile Orientation from Portrait to Landscape. 
4. Verify that suggestions extend to the full width of the suggestion banner with comparatively even padding/width for each (with more on longer words).

### CODE REVIEW

File: web/src/engine/osk/src/banner/suggestionBanner.ts [hunk 1]
```diff
@@ -704,28 +704,35 @@ export class SuggestionBanner extends Banner {
...
+    this.refreshLayout();
+  }
+
+  readonly refreshLayout = () => {
+    let collapsedOptions: BannerSuggestion[] = [];
+    let totalWidth = 0;
+
+    let displayCount = Math.min(this.currentSuggestions.length, 8);
+    for(let i=0; i < displayCount; i++) {
+      const opt = this.options[i];
```
Comment (mcdurdin) [inline web/src/engine/osk/src/banner/suggestionBanner.ts:727]: is it possible to do this?

```suggestion
    for(const opt of this.options) {
      const opt = this.options[i];
```

**Review by mcdurdin — APPROVED** [review]

File: web/src/engine/osk/src/banner/suggestionBanner.ts (hunk 1 above)
Comment (jahorton) [reply web/src/engine/osk/src/banner/suggestionBanner.ts:727]: `this.options.length` (locked by literal constant to `8`) does not necessarily equal `displayCount` (the number of available and displayable suggestions; 1 if none are available).

That tripped me up a bit when implementing the change.

Comment (jahorton) [reply web/src/engine/osk/src/banner/suggestionBanner.ts:727]: https://github.com/keymanapp/keyman/blob/c2474bd2e525af7352278dc91415b73d47f6a855/web/src/engine/osk/src/banner/suggestionBanner.ts#L381

https://github.com/keymanapp/keyman/blob/c2474bd2e525af7352278dc91415b73d47f6a855/web/src/engine/osk/src/banner/suggestionBanner.ts#L426-L436

We simply hide ones that don't have a useful suggestion to display.

Comment (mcdurdin) [reply web/src/engine/osk/src/banner/suggestionBanner.ts:727]: Ouch. That's definitely a trap for young future maintainers. Can you add a source comment accordingly?

**Review by ermshiperete — APPROVED** [review]

File: web/src/engine/osk/src/banner/suggestionBanner.ts [hunk 2]
```diff
@@ -704,28 +704,39 @@ export class SuggestionBanner extends Banner {
...
     }
 
+    this.refreshLayout();
+  }
+
+  readonly refreshLayout = () => {
+    let collapsedOptions: BannerSuggestion[] = [];
+    let totalWidth = 0;
+
+    let displayCount = Math.min(this.currentSuggestions.length, 8);
```
Comment (ermshiperete) [inline web/src/engine/osk/src/banner/suggestionBanner.ts:725]:
```suggestion
    let displayCount = Math.min(this.currentSuggestions.length, SuggestionBanner.SUGGESTION_LIMIT);
```

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_BANNER_ROTATION (PASSED):** Tested with the attached PR build (Keyman 17.0.252-alpha-test-10508) in the Android mobile device ver 13.0 and here is my observation:  1. Verified that the suggestions extend to the full width of the suggestion banner in the landscape orientation.

..Predictive text in Portrait Orientation

   


..Predictive text in Landscape Orientation

File: web/src/engine/osk/src/banner/suggestionBanner.ts (hunk 2 above)
Comment (jahorton) [reply web/src/engine/osk/src/banner/suggestionBanner.ts:725]: Ack, should've checked this before the late-night merge.  Ah well.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.252-alpha](https://keyman.com/downloads/releases/alpha/17.0.252)
