### PR TITLE
10.0 Deadkey compilation for Web

### LINKED ISSUE #281: Deadkeys that are supposed to prevent matches are not working in KeymanWeb
<a href="https://github.com/mcdurdin"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Wednesday Oct 9, 2013 at 22:31 GMT_
_Originally opened as KD-157_

----

When a deadkey is in the middle of a context string, a context should not match if it does not reference that deadkey. For example, if the backing store is:
```
  a<dk(0)>b
```
Then:
```
  'ab' + 'c' > 'match'
```
Should not fire. This is the Keyman Engine behaviour. The reason the rule is firing is that we don't ever test deadkeys within the context match rules.

## Keyboard which replicates this bug in KeymanWeb 
```
store(&VERSION) '8.0'
store(&NAME) 'Test missing deadkey'
begin Unicode > use(main)

group(main) using keys

'ab' + 'c' > 'match'
+ 'b' > dk(1) 'b'

+ 'd' > 'd' dk(2)
'd' + 'e' > 'fail'
```

## Test cases

**Type:** "abc".
**Expected (Keyman Engine):** "a<dk>bc"
**Actual (KeymanWeb):** "match"

**Type** "de".
**Expected (Keyman Engine):** "d<dk>e"
**Actual (KeymanWeb):** "fail"

I do not have an immediate answer for a fix. It will probably require a compiler change, because updating KCM to test for deadkeys within the text will work, but testing for a deadkey at the end of the text is not going to work. This is due to the way the compiler assembles the tests, e.g.
```
  'd' dk(2) + 'E' > 'pass'
```
Compiles to:
```
  if(k.KKM(e,16400,69)&&k.KCM(1,t,"d",1)&&k.KDM(0,t,1))
```
But:
```
  'd' + 'e' > 'fail'     
```
Compiles to:
```
  if(k.KKM(e,16384,69)&&k.KCM(1,t,"d",1))
```

So we need to have some way of validating the deadkey state even for rules that don't specifically test for a deadkey.

----
MD and JD add:

One keyboard that exhibits this issue is ISIS Devangari, typing 'kxi' or 'kxh'.
We expect कइ and कह respectively. But we get the default form of कि and ख instead.

This behaviour was confirmed on 2 May 2014.
If it is a Keyman compiler bug, then the issue should be moved to KM Dev. But if it needs changes to the KMEW code, then it should stay here.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #281.

With these changes, Keyman Developer will now target the new API functions for builds targeted at Keyman 10.0+.  These functions allow much better handling of deadkeys, along with deadkeys in stores and the `contextex`/`index` statements as part of a rule's context as supported by Desktop.

Checklist:
- [x] `test_deadkeys` keyboard - ensure the in-repo .js is compiled from the updated Developer.
- [x] Integrate the new `fullContextMatch` function into KMW 10+ compiled keyboards.
    - [ ] Include a hint/warning if any rule attempts to use neighboring deadkeys and version 9-.
- [x] Integrate the new store format for deadkey stores.
    - [x] Remove warning about deadkeys being incompatible with `any` and `index` for version 10+.

It's quite likely that there will need to be some style changes, as this is my first direct contribution to Developer and it appears the style conventions in Delphi are a bit different than with the other projects due to its syntax.

### CODE REVIEW

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 1]
```diff
@@ -506,9 +508,115 @@ function TCompileKeymanWeb.JavaScript_ContextValue(fkp: PFILE_KEY; pwsz: PWideCh
...
+  FullContext, Suffix: string;
+begin
+  Result := '';
+  FullContext := '';
+  Suffix := '';
+  Len := xstrlen(pwsz);
+
+	while pwsz^ <> #0 do
+  begin
+    if FullContext <> ''
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: Normal patterns we use for if/then/else:

```pascal
if condition then
  singleLineFunction;

if condition
  then shortFunction
  else shortFunction2;

if condition then
begin
  multiLine1;
  multiLine2;
end
else
begin
  // so on
end;

if condition1 then
  result1
else if condition2 then
  result2
else
  result3;
```

Comment (mcdurdin) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: The inconsistent one is the second example with `then` and `else` on separate lines. We've used this for a long time and it's actually quite readable, so we'll stick with it, even though it is different to the other patterns (and a somewhat unusual pattern generally speaking).

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 2]
```diff
@@ -506,9 +508,115 @@ function TCompileKeymanWeb.JavaScript_ContextValue(fkp: PFILE_KEY; pwsz: PWideCh
...
+          end;
+        else
+
+        begin
+          ReportError(fkp.Line, CERR_NotSupportedInKeymanWebContext, Format('Statement %s is not currently supported in context', [GetCodeName(rec.Code)]));  // I1971   // I4061
+          //CODE_NUL: ;     // todo: check if context is longer than that...
+          Result := Result + '/*.*/ 0 ';
+        end;
+      end;
+		end
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: Whitespace?

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 3]
```diff
@@ -506,9 +508,115 @@ function TCompileKeymanWeb.JavaScript_ContextValue(fkp: PFILE_KEY; pwsz: PWideCh
...
+		else
+    begin // Simple context character.
+      FullContext := FullContext + '''';
+      if rec.ChrVal in [Ord('"'), Ord('\')]
+        then FullContext := FullContext + '\';
+      FullContext := FullContext + Javascript_String(rec.ChrVal) + '''';  // I2242
+		end;
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: whitespace?

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 4]
```diff
@@ -506,9 +508,115 @@ function TCompileKeymanWeb.JavaScript_ContextValue(fkp: PFILE_KEY; pwsz: PWideCh
...
+          //CODE_NUL: ;     // todo: check if context is longer than that...
+          Result := Result + '/*.*/ 0 ';
+        end;
+      end;
+		end
+		else
+    begin // Simple context character.
+      FullContext := FullContext + '''';
+      if rec.ChrVal in [Ord('"'), Ord('\')]
+        then FullContext := FullContext + '\';
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: `then` on previous line.

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 5]
```diff
@@ -506,9 +508,115 @@ function TCompileKeymanWeb.JavaScript_ContextValue(fkp: PFILE_KEY; pwsz: PWideCh
...
+      FullContext := FullContext + Javascript_String(rec.ChrVal) + '''';  // I2242
+		end;
+
+		pwsz := incxstr(pwsz);
+	end;
+
+  if FullContext <> ''
+    then Result := Format('k.KFCM(%d,t,[%s])', [Len, FullContext]);
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: `then` on previous line.

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 6]
```diff
@@ -506,9 +508,115 @@ function TCompileKeymanWeb.JavaScript_ContextValue(fkp: PFILE_KEY; pwsz: PWideCh
...
+
+  if (Result <> '') and (Suffix <> '')
+    then Result := Result + '&&' + Suffix
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: `then` on previous line

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 7]
```diff
@@ -687,9 +795,20 @@ function TCompileKeymanWeb.JavaScript_OutputString(fkp: PFILE_KEY; pwszOutput: P
 
   pwsz := pwszOutput;
 
-  if Assigned(fkp)
-    then len := xstrlen_printing(fkp.dpContext)
-    else len := -1;
+  if Assigned(fkp) then
+    begin
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: `begin` should be on the same indent as its parent `if` statement (and likewise `end`) - so we only get a single level of indent for the contained statements.

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 8]
```diff
@@ -909,24 +1028,65 @@ function TCompileKeymanWeb.JavaScript_ShiftAsString(fkp: PFILE_KEY; FMnemonic: B
...
+      rec := ExpandSentinel(pwsz);
+      if rec.IsSentinel then
+      begin
+        if rec.Code = CODE_DEADKEY then
+        begin
+          Result := Result + Format('{d:%d}', [rec.Deadkey.DeadKey]);
+        end
+        else
+        begin
+          // How to report this error?  We should never see this.
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: We have an error code for unexpected in global/inc/comperr.h:
````c++
#define CERR_SomewhereIGotItWrong		0x00008009
````

You'll need to add the definition to global/delphi/general/CompileErrorCodes.pas, then use it viz:

````pascal
ReportError(fkp.Line, CERR_SomewhereIGotItWrong...
````

File: web/source/kmwcallback.ts [hunk 9]
```diff
@@ -452,7 +452,8 @@ class KeyboardInterface {
           case 'a':
             // TODO:  Remove the `string` requirement.
             var lookup = (typeof(context[i]) == 'string' ? context[i] as string : {'d': context[i] as number});
-            if(!this.any(i, lookup, r.a)) {
+            var result = this.any(i, lookup, r.a);
+            if(r.n ? result && context[i] !== "\uFFFE" : !result) {  // 'n' for 'notany', flipping the result.
```
[the remark this answers is not in the document]
Comment (jahorton) [reply web/source/kmwcallback.ts]: Latter part: `notany` does not match on `nul`.

[the remark this answers is not in the document]
Comment (mcdurdin) [reply web/source/kmwcallback.ts]: Please comment appropriately (or use a symbol instead of a string constant) :)

File: web/unit_tests/resources/keyboards/test_deadkeys.js [hunk 10]
```diff
@@ -34,284 +34,376 @@ function Keyboard_test_deadkeys()
   this.KM=0;
   this.KBVER="1.0";
   this.KMBM=modCodes.SHIFT /* 0x0010 */;
-  this.s_deadnums="..........";
+  this.s_deadnums=[{d:0},{d:1},{d:2},{d:3},{d:4},{d:5},{d:6},{d:7},{d:8},{d:9}];
```
Comment (mcdurdin) [inline web/unit_tests/resources/keyboards/test_deadkeys.js]: Can we go a step further for debug compilation? I'd like to see `this.d_0=0; ... this.d_a=10; ...` in the top part of the file, then reference deadkeys accordingly:

```
this.s_deadnums=[{d:this.d_0},...];
```

This helps the developer to track their deadkeys much better. Obviously, for the non-debug compile, just use integers as you already are.

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 11]
```diff
@@ -506,9 +508,115 @@ function TCompileKeymanWeb.JavaScript_ContextValue(fkp: PFILE_KEY; pwsz: PWideCh
     Result := Result + Format('",%d)', [Cur - StartQuotes]);
 end;
 
+// Used when targeting 10.0+, after the introduction of FullContextMatch/KFCM.
+function TCompileKeymanWeb.JavaScript_FullContextValue(fkp: PFILE_KEY; pwsz: PWideChar): string;
+
+  function IsRegExpSpecialChar(ch: WideChar): Boolean;
+  begin
+    Result := Pos('"\^$*+?{}.()|[]/', ch) > 0;
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: Good to have a source reference comment for this. e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions has an example that includes the same set.

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 12]
```diff
@@ -687,9 +795,20 @@ function TCompileKeymanWeb.JavaScript_OutputString(fkp: PFILE_KEY; pwszOutput: P
 
   pwsz := pwszOutput;
 
-  if Assigned(fkp)
-    then len := xstrlen_printing(fkp.dpContext)
-    else len := -1;
+  if Assigned(fkp) then
+    begin
+      if IsKeyboardVersion10OrLater
+        then len := xstrlen(fkp.dpContext)
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: Let's add a comment here as well

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 13]
```diff
@@ -909,24 +1028,65 @@ function TCompileKeymanWeb.JavaScript_ShiftAsString(fkp: PFILE_KEY; FMnemonic: B
...
-      Result := Result + '.'; {TODO: fill in .}
-    end
-    else
-    begin
-      ch := GetSuppChar(pwsz);
-      if ch in [Ord('"'), Ord('\')] then Result := Result + '\';
-      Result := Result + Javascript_String(ch);  // I2242
+      if PWord(pwsz)^ = UC_SENTINEL then
+      begin
+        Result := Result + '.'; {TODO: fill in .}
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: Comment needs to change to reflect that UC_SENTINEL values are not supported in stores in KMW<10

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 14]
```diff
@@ -909,24 +1028,65 @@ function TCompileKeymanWeb.JavaScript_ShiftAsString(fkp: PFILE_KEY; FMnemonic: B
...
+        else
+        begin
+          // How to report this error?  We should never see this.
+        end;
+      end
+      else
+      begin
+        ch := GetSuppChar(pwsz);
+        Result := Result + '"';
+        if ch in [Ord('"'), Ord('\')] then Result := Result + '\';
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: This is not be the time to do this, but this should clearly be refactored into Javascript_String! Perhaps add a comment to that effect.

File: web/source/kmwcallback.ts [hunk 15]
```diff
@@ -42,6 +42,11 @@ class ContextAny {
    * Value:  the store to search.
    */
   ['a']: KeyboardStore; // For 'a'ny statement.
+
+  /**
+   * If set to true, negates the 'any'.
+   */
+  ['n']: boolean|0|1;
```
Comment (darcywong00) [inline web/source/kmwcallback.ts]: So if set to true, this becomes `notany`?

I'm also curious why include `|0|1`

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas (hunk 11 above)
Comment (jahorton) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: Uh, okay... but that's copied straight from the parallel existing legacy function, so I guess I should add it there too?

File: web/source/kmwcallback.ts (hunk 15 above)
Comment (jahorton) [reply web/source/kmwcallback.ts]: > why include `0|1`

Because those take a single character, while `true|false` take 4 and 5 characters, respectively.  It's a simple keyboard size optimization, while the `boolean` indicates the true purpose for the values.

File: web/unit_tests/resources/keyboards/test_deadkeys.js (hunk 10 above)
Comment (jahorton) [reply web/unit_tests/resources/keyboards/test_deadkeys.js]: While that would be lovely to do, it turns out that the deadkey name information isn't available to the Web compiler at this time; the relevant field (`fk.dpDeadKeyArray`) is `nil` and does not contain name data for the deadkeys.  I'll mark it as an issue for Developer enhancement.

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas (hunk 11 above)
Comment (mcdurdin) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: Righto. In that case, carry on.

**Comment by jahorton** [comment]
Upon merge of this PR, also merge https://github.com/sillsdev/keyman-help.keyman.com/pull/140 for the help site.

**Comment by mcdurdin** [comment]
`KDC` length calculation update looks good.
