### PR TITLE
fix(developer): debug information with unicode identifiers

### LINKED ISSUE #4250: bug(developer): include debug information can break identifiers with non-ansi names in the web compiler
**Describe the bug**

From https://community.software.sil.org/t/touch-layout-debugging-with-keyman-developer/4236. A sample keyboard can be found at https://drive.google.com/drive/u/1/folders/1C1EOhWTGXvZlBEmvW8Y4o1QArEyI4-th

If a keyboard includes identifiers (stores or groups) that include characters outside the `a-z A-Z 0-9 _` range, these characters are replaced by `_` by the compiler when Include Debug Information is set to avoid potential issues with invalid characters in identifiers.

When no debug information is included, the store names are replaced with integer identifiers so this problem does not arise.

For example, given the following Keyman source:

```keyman
c ---------------------Maps of Syllabic Forms---------------------------------------------------
c the following is universal (language neutral) these mappings can be overridden by
c language specific mappings
  store(ግዕዝ)  'ሀለሐመሠረሰሸቀበቨተቸኀነኘከኸወዐዘዠየደጀገጠጨጰጸፀፈፐ'
  store(ካዕብ)  'ሁሉሑሙሡሩሱሹቁቡቩቱቹኁኑኙኩኹዉዑዙዡዩዱጁጉጡጩጱጹፁፉፑ'
  store(ሣልስ)  'ሂሊሒሚሢሪሲሺቂቢቪቲቺኂኒኚኪኺዊዒዚዢዪዲጂጊጢጪጲጺፂፊፒ'
  store(ራብዕ)  'ሃላሓማሣራሳሻቃባቫታቻኃናኛካኻዋዓዛዣያዳጃጋጣጫጳጻፃፋፓ'
  store(ኃምስ)  'ሄሌሔሜሤሬሴሼቄቤቬቴቼኄኔኜኬኼዌዔዜዤዬዴጄጌጤጬጴጼፄፌፔ'
  store(ሳድስ)  'ህልሕምሥርስሽቅብቭትችኅንኝክኽውዐዝዥይድጅግጥጭጵጽፅፍፕ'
  store(ሳብዕ)  'ሆሎሖሞሦሮሶሾቆቦቮቶቾኆኖኞኮኾዎዖዞዦዮዶጆጎጦጮጶጾፆፎፖ'

c QWERTY keymappings
  store(keys)  'hlHm_rsxqbvtc_nNkKw_zZydjgTCPS_fp'
```

The compiler produces:

```
  this.s____="ሀለሐመሠረሰሸቀበቨተቸኀነኘከኸወዐዘዠየደጀገጠጨጰጸፀፈፐ";
  this.s____="ሁሉሑሙሡሩሱሹቁቡቩቱቹኁኑኙኩኹዉዑዙዡዩዱጁጉጡጩጱጹፁፉፑ";
  this.s____="ሂሊሒሚሢሪሲሺቂቢቪቲቺኂኒኚኪኺዊዒዚዢዪዲጂጊጢጪጲጺፂፊፒ";
  this.s____="ሃላሓማሣራሳሻቃባቫታቻኃናኛካኻዋዓዛዣያዳጃጋጣጫጳጻፃፋፓ";
  this.s____="ሄሌሔሜሤሬሴሼቄቤቬቴቼኄኔኜኬኼዌዔዜዤዬዴጄጌጤጬጴጼፄፌፔ";
  this.s____="ህልሕምሥርስሽቅብቭትችኅንኝክኽውዐዝዥይድጅግጥጭጵጽፅፍፕ";
  this.s____="ሆሎሖሞሦሮሶሾቆቦቮቶቾኆኖኞኮኾዎዖዞዦዮዶጆጎጦጮጶጾፆፎፖ";
  this.s_keys="hlHm_rsxqbvtc_nNkKw_zZydjgTCPS_fp";
```

Thus, later stores clobber earlier ones, breaking future rules.

**Expected behavior**

Each store should be unique. The easiest way to resolve this may be to include the integer identifier for each store as well as its name. Also for groups.

---

**Keyman Developer:**
 - OS: Windows 10 20H2 x64 
 - Keyman Developer version: 14.0.220-beta

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4250.

This implements @jahorton's suggestion of including the original name in a comment alongside the munged name, as well as appending the unique integer identifier of each symbol.

Note: the error reporting code needed a massage to support Unicode error strings; in the future we should update the C++ compiler to emit Unicode error strings also.

### CODE REVIEW

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 1]
```diff
@@ -873,11 +890,31 @@ function TCompileKeymanWeb.JavaScript_Name(i: Integer; pwszName: PWideChar; UseN
...
+    begin
+      // Ensure each transformed name is still unique
+      Result := Result + '_' + IntToStr(i);
+      if FChanged then
+        Result := Result + '/*'+string(p).Replace('*/', '*-/')+'*/'
+    end
+    else if FChanged then
+    begin
+      // For named option stores, we are only supporting the valid identifier
+      // character set, which is a breaking change in 14.0.
```
Comment (darcywong00) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas:914]: We should add this to https://github.com/keymanapp/keyman/wiki/Keyman-13.0-to-14.0-Migration#developer-and-keyboards

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 2]
```diff
@@ -873,11 +890,31 @@ function TCompileKeymanWeb.JavaScript_Name(i: Integer; pwszName: PWideChar; UseN
...
+      end;
       Inc(pwszName);
     end;
+    if not UseNameForRelease then
+    begin
+      // Ensure each transformed name is still unique
+      Result := Result + '_' + IntToStr(i);
+      if FChanged then
+        Result := Result + '/*'+string(p).Replace('*/', '*-/')+'*/'
+    end
```
Comment (jahorton) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas:910]: I may be missing something here.  We're emitting the original name when `not UseNameForRelease`?

I'd have thought the plan was that when `UseNameForRelease` is true but the option store's name isn't in the "valid identifier set", we'd use non-named JS variable names but inline the original name as a comment.

Comment (jahorton) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas:910]: Would avoid the need for a "breaking change" note, too.

Comment (mcdurdin) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas:910]: `UseNameForRelease` is perhaps a poor name for the parameter. When this flag is set, we need to emit the original name of the store, because it is being used as a string parameter for `KSAVE()`, `KLOAD()` -- so the store can persist across versions of the keyboard where the store indices may change. This is why I figured it safest to require "valid identifier characters" for these stores -- to reduce potential complications for saving them, e.g. character set woes in cookies, etc. It may be we can use the original name with appropriate escaping but I wonder if it is worth the effort?

Comment (jahorton) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas:910]: But this PR's description says:

> This implements @jahorton's suggestion of including the original name in a comment alongside the munged name, as well as appending the unique integer identifier of each symbol.

That suggestion was to _allow_ a partially-munged name (when necessary) to be used for `UseNameForRelease` (when true) by pairing it with an in-lined comment of the true name at all points of reference.  Then, the inlined comment can serve as said "appropriate escaping" while not causing store name overrides.

Comment (mcdurdin) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas:910]: Unless I am completely misunderstanding you, I don't think you are understanding what `UseNameForRelease` is doing. `UseNameForRelease` has nothing to do with debug mode or Javascript identifiers. It is set to true by the caller when we need a *string* representation of the store identifier to use for variable stores, to persist or load the value of the variable store.

So, this line of code:

```
+ 'a' > set(foo='1')
```

Gives us:

```
if(k.KKM(e, modCodes.VIRTUAL_KEY /* 0x4000 */, keyCodes.K_A /* 0x41 */)) {
      if(1){
        r=m=1;   // Line 23
        k.KDC(0,t);
        k.KSAVE("foo",this.s_foo_10);
      }
    }
```

See how the `k.KSAVE` function handles this with debug mode on. Now, with debug mode off:

```
if(k.KKM(e,16384,65)) {if(1){r=m=1;k.KDC(0,t);k.KSAVE("foo",this.s10);}}
```

The `"foo"` is preserved here because it's used as an identifier for persistence.

That's the only use of `UseNameForRelease`. The parameter name does makes sense, if you think of it as saying, use the store's name even when we are generating a release build (i.e. non-debug). But it's a bit confusing all the same.

Comment (jahorton) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas:910]: Ah, I see.   Yeah, the flag could _definitely_ use a better name, then.

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas (hunk 1 above)
Comment (jahorton) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas:914]: So this is a new restriction on stores used with `KSAVE` and `KLOAD`, then?

If a store isn't used with a rule that forces use of its name through those two, it's still allowed to exist?

Comment (mcdurdin) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas:914]: Yes, this restriction is just on stores used with `save()` and `reset()` (aka `KSAVE` and `KLOAD` in the compiled form). I have checked, and there are no keyboards in the keymanapp/keyboards repository that fall foul of this restriction.

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas (hunk 2 above)
Comment (mcdurdin) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas:910]: @mcdurdin is currently accepting suggestions for better names

Comment (jahorton) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas:910]: Since it's main use is for persistent storage / cookies, some ideas:

- `UsePersistentName`
- `AsPersistentID`
- `UseNameForCookie`
- `UseNameForPersistentStorage`

**Review by jahorton — APPROVED** [review]
Now that I better understand the code and that `UseNameForRelease` flag's intent, LGTM.

Might be nice to sneak in a rename for it first.

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas (hunk 2 above)
Comment (mcdurdin) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: `KeepNameForPersistentStorage` won for today.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.239-beta](https://keyman.com/downloads/releases/beta/14.0.239)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)
