### PR TITLE
fix(ios): delayed banner

### LINKED ISSUE #10847: bug(ios): The Keyman banner only appears in landscape view after one additional device rotation
### Describe the bug

I noticed that the Keyman banner only appears in landscape view after one more rotation of the device.

### Reproduce the bug

1. Install Keyman 17.0.275-beta 
2. Open Keyman In-app. 
3. Download and Install sil_ipa or any other keyboard that does not have a dictionary feature. 
4. Enable as a system-wide keyboard. 
5. Open any browser. 
6. Change the Orientation into Landscape. 
7. Long the press the globe key. Switch Keyman Keyboard. 
8. Switch to sil_ipa keyboard. 

Here, I noticed that the Keyman banner was missing. 

9. Change the Orientation to Portrait. Revert to Landscape view. 

Now, the Keyman banner is visible. Seems to be a cosmetic issue. 

https://github.com/keymanapp/keyman/assets/19683143/115bf8f9-485f-4a58-9448-d85bda3e475f

### Expected behavior

Keyman banner should be visible for the keyboards (that do not have dictionary features) in landscape mode. 

### Related issues

_No response_

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.275-beta

### Operating system

ios 15.5, ios 17.0

### Device

iPhone 13 Mobile device, iphone 15 Pro Max Simulator (iOS 17.0)

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #10847.

This PR ensures that the banner displays consistently when it is supposed to do so, and in its intended manner.  The image banner should no longer be distorted or smaller than intended at any time.

## User Testing

**TEST_SYSTEM_KBD**:  Attempt to reproduce the errors documented in #10847 and verify that they are now fixed.

1. Install this PR's test artifact.
2. Open Keyman In-app. 
3. Download and Install sil_ipa or any other keyboard that does not have a dictionary feature. 
4. Enable as a system-wide keyboard. 
5. Open any browser. 
6. Change the Orientation into Landscape. 
7. Long the press the globe key. Switch Keyman Keyboard. 
8. Switch to sil_ipa keyboard.

### CODE REVIEW

File: ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift [hunk 1]
```diff
@@ -744,6 +742,8 @@ extension KeymanWebViewController: KeymanWebDelegate {
     // Reset the keyboard's size.
     keyboardSize = kbSize
 
+    setBannerHeight(to: Int(InputViewController.topBarHeight))
```
Comment (jahorton) [inline ios/engine/KMEI/KeymanEngine/Classes/Keyboard/KeymanWebViewController.swift:745]: This call has been relocated; it will now be triggered consistently upon the host page's load.  We never turn the banner off, and we keep the image banner and suggestion banner at the same height.

The image banner's distortion occurred because the original height-setting location... was only ever called when a lexical model was activated.  That doesn't happen for image banners.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_SYSTEM_KBD (PASSED):** Tested with the attached PR build (Keyman 17.0.281-beta-test-10930) on an iPhone 15 Pro Max Simulator/ios 17.0 and here is my observation: 1. Opened the Keyman In-App. 2. Installed sil_ipa keyboard (which doesn't have a dictionary feature). 3. Enabled as a system-wide keyboard. 4. Opened Safari browser. 5. Changed the orientation into landscape. 6. Long pressed the globe key. Switched to Keyman Keyboard. 7. Switched to sil_ipa keyboard. Verified that it is showing the keyman banner on the OSK. Seems to be working as expected.
