### PR TITLE
fix(windows): avoid disabling Keyman when speech recognition starts

### LINKED ISSUE #4856: bug(windows): the keyboard is not working even though activated
**Describe the bug**

On a particular user's machine, a custom keyboard does not work as expected even though it was correctly set as default input method. Here is the whole account of the [issue ](https://community.software.sil.org/t/keyboard-shows-as-on-but-doesnt-work-until-it-is-turned-off-and-on-again/4336/15) from the community site:

> The issue persists even when having the right language tag set to “qu-PE”. Despite the fact that the keyboard works for me, the keyboard keeps misbehaving. ;a output ;a instead of ä in Microsoft Office Word 365 (including even Notepad) on Diane’s machine.
> 
> What I do that works for me but not for her
> 
> Install the keyboard [quechua_unicode2.1.kmp](https://community.software.sil.org/uploads/short-url/80Iqy8CCFO0IajYwJJZw1JgI7Mg.kmp) (1.6 KB)
> Go to the Language Preferences and move Quechua keyboard to the top of list of “Preferred Language” so the keyboard will be used for any apps.
> Go to “Keyboard” and choose “Quechua Unicode” to Override for default input method.
> Doing these proves to work on my Machine. Open LibreOffice, Notepad or Chrome to type away in Quechua without any issue nor having to switch the keyboard on and off.
> 
> As you have mentioned earlier, there might be something getting in the way before Keyman gets to work in per particular machine. I would suggest that you look into it when time allows.

**Expected behavior**

The keyboard should work (i.e. `;a` output ä) at any given application on startup without having to switch to an different keyboard and back to it to activate the keyboad.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.270
 - Target Application: MS Office 365, Notepad, Chrome (any at all)

---

**Keyboard**
 - Keyboard name: quechua_unicode
 - Keyboard version: 2.1
 - Language name: Quechua

### LINKED ISSUE #4965: bug(windows): If alternative TIPs are installed, Keyman may fail to activate on first use
**Describe the bug**

If alternative TIPs such as speech recognition are installed, Keyman may fail to start on first use in a newly started application. Switching the keyboard off and on again will normally work around this.

This issue was first noted in diagnostic investigation at https://community.software.sil.org/t/keyboard-shows-as-on-but-doesnt-work-until-it-is-turned-off-and-on-again/4336

The problem relates to function `STDAPI CKMTipTextService::OnActivated(REFCLSID clsid, REFGUID guidProfile, BOOL fActivated)` in tmgrsink.cpp:

https://github.com/keymanapp/keyman/blob/03c230c4e7c6e53320921ed91e15e11d8abe8fcc/windows/src/engine/kmtip/tmgrsink.cpp#L150-L172

If a non-keyboard TIP is activated, then we should be detecting that on line 167 above and ignoring the activation. Only if a keyboard-type TIP is activated should we be deactivating Keyman.

**To Reproduce**

Installing speech recognition may trigger this behaviour but that may not be deterministic if the activation order differs.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10
 - Keyman version: 14.0.271 
 - Target Application: any

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4965.
Fixes #4856.

When speech recognition is enabled, it sometimes activates after a Keyman keyboard is selected. This would cause Keyman to think it is being deactivated. We needed to check in `CKMTipTextService::OnActivated` that it was a keyboard-type TIP that was being activated, and only deactivate the Keyman hooks in that situation.

This commit also adds a little logging helper function, and removes an unused variable `guidActiveProfile`.

I will cherry-pick to stable-14.0 once approved.

### CODE REVIEW

File: windows/src/engine/kmtip/tmgrsink.cpp [hunk 1]
```diff
@@ -151,21 +151,51 @@ STDAPI CKMTipTextService::OnActivated(REFCLSID clsid, REFGUID guidProfile, BOOL
...
+            }
+            pEnumTfInputProcessorProfiles->Release();
+            pEnumTfInputProcessorProfiles = NULL;
+          }
+          pInputProcessorProfileMgr->Release();
+          pInputProcessorProfileMgr = NULL;
+        }
+        pInputProcessorProfiles->Release();
+        pInputProcessorProfiles = NULL;
+      }
```
Comment (mcdurdin) [inline windows/src/engine/kmtip/tmgrsink.cpp:194]: It would be nice if we didn't need to enumerate all the language profiles in order to discover this single property `catid` (TIP Category ID) but I have not found any alternative way of doing this...

File: windows/src/engine/kmtip/tmgrsink.cpp [hunk 2]
```diff
@@ -151,21 +151,51 @@ STDAPI CKMTipTextService::OnActivated(REFCLSID clsid, REFGUID guidProfile, BOOL
...
+
+    if (fActivated) {
+      BOOL bIsDeactivating = TRUE;
+      ITfInputProcessorProfiles *pInputProcessorProfiles = NULL;
+
+      /* Look up the profile which is being activated, and only deactivate ourselves if it is a
+         Keyboard type TIP.
+      */
+      if (LogSUCCEEDED(CoCreateInstance(CLSID_TF_InputProcessorProfiles, NULL, CLSCTX_INPROC_SERVER,
+        IID_ITfInputProcessorProfiles, (void**)&pInputProcessorProfiles))) {
```
Comment (mcdurdin) [inline windows/src/engine/kmtip/tmgrsink.cpp:172]: Query whether it is safe to call `CoCreateInstance` here or if we should call [`TF_CreateInputProcessorProfiles`](https://docs.microsoft.com/en-us/windows/win32/api/msctf/nf-msctf-tf_createinputprocessorprofiles)

Comment (mcdurdin) [reply windows/src/engine/kmtip/tmgrsink.cpp:172]: As far as I know, this will be okay. We should not be constrained from running COM functions within the auspices of the TIP as it is itself a COM object.

File: windows/src/engine/kmtip/tmgrsink.cpp [hunk 3]
```diff
@@ -151,21 +151,51 @@ STDAPI CKMTipTextService::OnActivated(REFCLSID clsid, REFGUID guidProfile, BOOL
...
+          }
+          pInputProcessorProfileMgr->Release();
+          pInputProcessorProfileMgr = NULL;
+        }
+        pInputProcessorProfiles->Release();
+        pInputProcessorProfiles = NULL;
+      }
+      if (bIsDeactivating) {
+        TIPNotifyActivate(NULL);
+      }
```
Comment (darcywong00) [inline windows/src/engine/kmtip/tmgrsink.cpp:197]: Comparing to l. 160
```
TIPNotifyActivate(fActivated ? (GUID *)&guidProfile : NULL);
```

Is `TIPNotifyActivate(GUID *)&guidProfile)` not applicable to this block because it didn't match any profile, hence nothing to activate?

Comment (mcdurdin) [reply windows/src/engine/kmtip/tmgrsink.cpp:197]: If you look at l. 158:

```
if(IsEqualGUID(clsid, c_clsidKMTipTextService)) {
```

We only want to pass in the `guidProfile` that is being activated when it is a profile for the Keyman Text Service that is being activated. Any other keyboard-type profile (e.g. Chinese IME) needs Keyman to be disabled.

Comment (rc-swag) [reply windows/src/engine/kmtip/tmgrsink.cpp:197]: I don't follow the big picture here. at l.160 if the clsid is our serivce then it needs to be activated or deactivted based on the `fActivated`.   Whereas by 196 we will not be activating and are only deactivating if the category tip of the text service is a keyboard OR if we can't access the profiles.  I say this because `bIsDeactivating  `is initialised to `TRUE`.
 I think the difference is calling TIPNotifyActive with NULL disables keyman. If we reach that if block I.196 we only want to disable because  either a) the porfile

**Review by rc-swag — APPROVED** [review]
lgtm but only looking at surface level.

File: windows/src/engine/kmtip/tmgrsink.cpp (hunk 3 above)
Comment (mcdurdin) [reply windows/src/engine/kmtip/tmgrsink.cpp:197]: @rc-swag Yep, that's correct. Three(four) scenarios:

1. If another keyboard text service is activated, then we want to disable Keyman.
2. If Keyman text service is activated, then we want to enable Keyman.
3. If Keyman text service is deactivated, then we want to disable Keyman.
(4. if we are unable to enumerate profiles in scenario 1 above, then we want to disable Keyman to maintain existing behaviour. Error situation that's unlikely to occur.)

Ironically, I don't think `OnActivated` is ever called with `fActivated == FALSE` (for scenario 3). I've never seen it. But proper handling suggests we should do so.

**Comment by mcdurdin** [comment]
Adding a comment

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.43-alpha](https://keyman.com/downloads/releases/alpha/15.0.43)
