### PR TITLE
[Web] OSK bulk renderer

### LINKED ISSUE #100: Allow init() to work with Promises
https://developers.google.com/web/fundamentals/getting-started/primers/promises

We want (and have) a non-blocking init, but there are certain API calls or page code setups that rely upon `init()` having been called and fail if we don't wait until initialization has already occurred.  Promises provide a way to have Javascript reliably execute a block of explicitly post-initialization code and could be used to handle these cases.

### PR DESCRIPTION
**Pull request by jahorton**
Partially parallels #1428.

Fixes #100.  This happened to be useful for simplifying the code involved.

The aim of this PR is to provide a web page for us developers that's useful for validating any changes made to the OSK's backing code.  This will be done by procedurally rendering _every_ keyboard and _every_ layer so that visual inspection can detect possible inconsistencies.

Note that there are a _lot_ of necessary asynchronous operations here due to the nature of the problem and how JavaScript operates.  The page (bulk_rendering/index.html) will necessarily take quite a while to load when complete.  Make sure to call the `bulk_rendering` folder's build.sh before viewing the page!

When the rendering operations complete, the resulting page can be easily saved by a desktop browser and reloaded with no loss, as the images will be embedded into the page's source as img64 data.  (It may be handy to use Chrome emulation for validation of rendering on mobile devices for this reason.)

### CODE REVIEW

**Comment by jahorton** [comment]
A look at a single keyboard's renders under Chrome's iOS emulation:

image

**Comment by darcywong00** [comment]
Is it possible to reuse some of the OSK rendering in help.keyman.com? 
In the cdn/deploy/js/kbd-docs.js

See https://help.keyman.com/keyboard/sil_bwe_karen/1.0/sil_bwe_karen.php

When the js keyboard is loaded and you know the layer names, you just call
```
<div id='osk-phone' data-states='default shift Symbol'></div>

<div id='osk-tablet' data-states='default shift Symbol'></div>

```

File: web/bulk_rendering/build.sh [hunk 1]
```diff
@@ -0,0 +1,54 @@
+#! /bin/bash
+# 
+# Compile the KeymanWeb Recorder module for use with developing/running engine tests.
```
Comment (darcywong00) [inline web/bulk_rendering/build.sh]: bulk_rendering module

Comment (jahorton) [reply web/bulk_rendering/build.sh]: Copy-paste, my arch-nemesis... we meet again.

**Comment by jahorton** [comment]
Potential issue:  during execution, a number of keyboards may fail to load in a timely manner due to responsiveness with the cloud server, especially over a heavy batch run.  It's possible that `setActiveKeyboard`'s timeout settings (10 sec) should be adjusted higher... or should be made adjustable for batch runs.  (Basically, it timed out a lot of keyboards that _did_ load, but after the timer had already said 'long enough!')

Of course, in a development environment, we might could simply 'hotwire' KMW through options to extract keyboards from a local copy of the keymanapp/keyboards repo, bypassing this issue (and expediting batch runs).

File: web/source/kmwkeyboards.ts [hunk 2]
```diff
@@ -305,7 +305,7 @@ namespace com.keyman {
 
       // Fixed OSK font issue Github #7 (9/1/2015)
       if(typeof(lp['oskFont']) != 'undefined') {
-        sp['KOskFont'] = (typeof sp['KOskFont'] === 'undefined') ? new KeyboardFont(lp['oskfont'], fontPath) : sp['KOskFont'];
+        sp['KOskFont'] = (typeof sp['KOskFont'] === 'undefined') ? new KeyboardFont(lp['oskFont'], fontPath) : sp['KOskFont'];
```
Comment (mcdurdin) [inline web/source/kmwkeyboards.ts]: Does this mean OSK font has not been working properly since 2015?

Comment (jahorton) [reply web/source/kmwkeyboards.ts]: It's hard to say at this point.  It may have been broken and overlooked during the TypeScript refactor of this section, or it might not.
