### PR TITLE
fix(windows): Trigger language sync after changes

### LINKED ISSUE #4222: bug(windows): uncheck the keyboard after a restart doesn't get updated the keyboard menu automatically
**Describe the bug**

The keyboard menu from the taskbar does not get updated automatically and/or immediately when the keyboard is unchecked from the Configuration.

Do a refresh install of Keyman for Windows (v14.0.217-beta) and install Hebrew Basic and Lao Basic keyboards. Restart the machine and from the Configuration check Hebrew Basic keyboard to see the error.

image

**Expected behavior**

The update should take effect immediately.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.217-beta
 - Target Application: self

---

**Keyboard**
 - Keyboard name: Hebrew Basic, Lao Basic
 - Keyboard version: 1.1
 - Language name: Hebrew, Lao

---

**Additional Context**
Uncheck and recheck the keyboard again may trigger expected behavior.

### LINKED ISSUE #4447: bug(windows): OSK, keyboard menu on taskbar and Configuration do not get sync immediately
**Describe the bug**

Swampy Cree (Tataskweyak) was unchecked, rechecked and then unchecked again. Now the keyboard is still shown in the keyboard menu and the OSK toolbar.

image

**Expected behavior**

Unchecked keyboard should not be visible in the keyboard menu.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.239-beta
 - Target Application: Configuration, OSK toolbar and keyboard menu

---

**Keyboard**
 - Keyboard name: Swampy Cree (Tataskweyak)
 - Keyboard version: 1.1
 - Language name: Cree

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4447.
Fixes #4222.

The symptoms for these two issues are related: the language associations change and keyboards stop functioning correctly. The issue is described in detail in #4447.

Although this fix should be considered 'experimental', we should probably include it in the release of 14.0, because it fixes a longstanding issue with Keyman and Windows languages.

Note that this is required even if sync is switched off: the sync task still runs on login and resets language settings from its local cache.

### CODE REVIEW

File: windows/src/engine/kmcomapi/com/keyboards/keymankeyboardsinstalled.pas [hunk 1]
```diff
@@ -182,6 +187,46 @@ procedure TKeymanKeyboardsInstalled.Apply;
...
+// overwritten on a subsequent reboot of the system.
+//
+// See #4447 and kmrefresh.cpp for additional detail.
+//
+// Although the sync function is not supported on Windows 7, 8.1,
+// we'll call kmrefresh.exe anyway, as we cannot be sure which version
+// of Windows we are running on -- the calling process may be lied to
+// if it does not have an appropriate manifest. kmrefresh.exe is safe
+// to run as it will simply exit if it does not find the appropriate
+// endpoint to call.
```
Comment (darcywong00) [inline windows/src/engine/kmcomapi/com/keyboards/keymankeyboardsinstalled.pas:205]: Does it quietly exit when Windows is offline too?

**Comment by mcdurdin** [comment]
# User Testing

* Attempt to reproduce the issues as described in #4447 and #4222.

* Upgrade scenario
1. Do a clean install of 13.0
2. Install at least 2 keyboards and at least one transient language (e.g. `cmo-Khmr`)
3. In PowerShell, run `Get-WinUserLanguageList` to get a list of installed languages and save the results.
4. Upgrade to this build (without restarting). `Get-WinUserLanguageList` and save results again.
5. THEN restart and validate that keyboards are still present in `Get-WinUserLanguageList` - comparing to original results.

@MakaraSok

File: windows/src/engine/kmcomapi/com/keyboards/keymankeyboardsinstalled.pas (hunk 1 above)
Comment (mcdurdin) [reply windows/src/engine/kmcomapi/com/keyboards/keymankeyboardsinstalled.pas:205]: Yes. The sync still needs to run even if Windows is offline and sync is disabled, because it syncs to a local cache which is what is used to overwrite the user settings on next boot (even if sync is disabled!)

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by MakaraSok** [comment]
Tested on Windows 10 Pro x64. 

Results of `Get-WinUserLanguageList` on:

- 13.0.118 Stable
```
LanguageTag     : en-US
Autonym         : English (United States)
EnglishName     : English
LocalizedName   : English (United States)
ScriptName      : Latin
InputMethodTips : {0409:00000409}
Spellchecking   : True
Handwriting     : False

LanguageTag     : aal-Latn-CM
Autonym         :
EnglishName     : Afade (aal-Latn-CM)
LocalizedName   :
ScriptName      : Latin
InputMethodTips : {2000:00000409}
Spellchecking   : True
Handwriting     : False

LanguageTag     : btc-Latn-CM
Autonym         :
EnglishName     : Bati (Cameroon) (btc-Latn-CM)
LocalizedName   :
ScriptName      : Latin
InputMethodTips : {2400:00000409}
Spellchecking   : True
Handwriting     : False

LanguageTag     : bcw-Latn-CM
Autonym         :
EnglishName     : Bana (bcw-Latn-CM)
LocalizedName   :
ScriptName      : Latin
InputMethodTips : {2800:00000409}
Spellchecking   : True
Handwriting     : False

LanguageTag     : hbo-Hebr
Autonym         :
EnglishName     : Ancient Hebrew (hbo-Hebr)
LocalizedName   :
ScriptName      : Hebrew
InputMethodTips : {2C00:0002040D}
Spellchecking   : True
Handwriting     : False

LanguageTag     : grc-Grek
Autonym         :
EnglishName     : Ancient Greek (to 1453) (grc-Grek)
LocalizedName   :
ScriptName      : Greek
InputMethodTips : {}
Spellchecking   : True
Handwriting     : False

LanguageTag     : aae-Latn
Autonym         :
EnglishName     : Arbëreshë Albanian (aae-Latn)
LocalizedName   :
ScriptName      : Latin
InputMethodTips : {}
Spellchecking   : True
Handwriting     : False

LanguageTag     : cmo-Khmr
Autonym         :
EnglishName     : Central Mnong (cmo-Khmr)
LocalizedName   :
ScriptName      : Khmer
InputMethodTips : {}
Spellchecking   : True
Handwriting     : False
```
- 14.0.258-beta (before restarting)
```
LanguageTag     : en-US
Autonym         : English (United States)
EnglishName     : English
LocalizedName   : English (United States)
ScriptName      : Latin
InputMethodTips : {0409:00000409}
Spellchecking   : True
Handwriting     : False

LanguageTag     : aal-Latn-CM
Autonym         :
EnglishName     : Afade (aal-Latn-CM)
LocalizedName   :
ScriptName      : Latin
InputMethodTips : {2000:00000409}
Spellchecking   : True
Handwriting     : False

LanguageTag     : btc-Latn-CM
Autonym         :
EnglishName     : Bati (Cameroon) (btc-Latn-CM)
LocalizedName   :
ScriptName      : Latin
InputMethodTips : {2400:00000409}
Spellchecking   : True
Handwriting     : False

LanguageTag     : bcw-Latn-CM
Autonym         :
EnglishName     : Bana (bcw-Latn-CM)
LocalizedName   :
ScriptName      : Latin
InputMethodTips : {2800:00000409}
Spellchecking   : True
Handwriting     : False

LanguageTag     : hbo-Hebr
Autonym         :
EnglishName     : Ancient Hebrew (hbo-Hebr)
LocalizedName   :
ScriptName      : Hebrew
InputMethodTips : {2C00:0002040D}
Spellchecking   : True
Handwriting     : False

LanguageTag     : grc-Grek
Autonym         :
EnglishName     : Ancient Greek (to 1453) (grc-Grek)
LocalizedName   :
ScriptName      : Greek
InputMethodTips : {}
Spellchecking   : True
Handwriting     : False

LanguageTag     : aae-Latn
Autonym         :
EnglishName     : Arbëreshë Albanian (aae-Latn)
LocalizedName   :
ScriptName      : Latin
InputMethodTips : {}
Spellchecking   : True
Handwriting     : False

LanguageTag     : cmo-Khmr
Autonym         :
EnglishName     : Central Mnong (cmo-Khmr)
LocalizedName   :
ScriptName      : Khmer
InputMethodTips : {}
Spellchecking   : True
Handwriting     : False
```
- 14.0.258-beta (after restarting)
```
LanguageTag     : en-US
Autonym         : English (United States)
EnglishName     : English
LocalizedName   : English (United States)
ScriptName      : Latin
InputMethodTips : {0409:00000409}
Spellchecking   : True
Handwriting     : False

LanguageTag     : aal-Latn-CM
Autonym         :
EnglishName     : Afade (aal-Latn-CM)
LocalizedName   :
ScriptName      : Latin
InputMethodTips : {2000:00000409}
Spellchecking   : True
Handwriting     : False

LanguageTag     : btc-Latn-CM
Autonym         :
EnglishName     : Bati (Cameroon) (btc-Latn-CM)
LocalizedName   :
ScriptName      : Latin
InputMethodTips : {2400:00000409}
Spellchecking   : True
Handwriting     : False

LanguageTag     : bcw-Latn-CM
Autonym         :
EnglishName     : Bana (bcw-Latn-CM)
LocalizedName   :
ScriptName      : Latin
InputMethodTips : {2800:00000409}
Spellchecking   : True
Handwriting     : False

LanguageTag     : hbo-Hebr
Autonym         :
EnglishName     : Ancient Hebrew (hbo-Hebr)
LocalizedName   :
ScriptName      : Hebrew
InputMethodTips : {2C00:0002040D}
Spellchecking   : True
Handwriting     : False

LanguageTag     : grc-Grek
Autonym         :
EnglishName     : Ancient Greek (to 1453) (grc-Grek)
LocalizedName   :
ScriptName      : Greek
InputMethodTips : {}
Spellchecking   : True
Handwriting     : False

LanguageTag     : aae-Latn
Autonym         :
EnglishName     : Arbëreshë Albanian (aae-Latn)
LocalizedName   :
ScriptName      : Latin
InputMethodTips : {}
Spellchecking   : True
Handwriting     : False

LanguageTag     : cmo-Khmr
Autonym         :
EnglishName     : Central Mnong (cmo-Khmr)
LocalizedName   :
ScriptName      : Khmer
InputMethodTips : {}
Spellchecking   : True
Handwriting     : False
```

**Comment by MakaraSok** [comment]
Here is the screenshot of after restarting on 14.0.259-beta:

image

**Comment by mcdurdin** [comment]
Try cleaning up the list with `Set-WinUserLanguageList "en-us" -force`, then add a keyboard in Windows Language Settings, then restart, run `Get-WinUserLanguageList` to make sure the list is nice and clean, then retest.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.261-beta](https://keyman.com/downloads/releases/beta/14.0.261)

**Comment by MakaraSok** [comment]
> Try cleaning up the list with `Set-WinUserLanguageList "en-us" -force`, then add a keyboard in Windows Language Settings, then restart, run `Get-WinUserLanguageList` to make sure the list is nice and clean, then retest.

Done that. The locales stay the same before and after the restart. Compare the screenshots below:

- before restarting:

image

- after restarting:

image

**Comment by MakaraSok** [comment]
Yes. 👍

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.20-alpha](https://keyman.com/downloads/releases/alpha/15.0.20)
