### PR TITLE
fix(android): Revert KMManager.onDestroy

### LINKED ISSUE #2539: [Android] Intermittent crash rotating between portrait and landscape
Found during 13.0 pre-beta testing in #2529 

The system keyboard intermittently crashes when rotating between portrait and landscape

Advancing to next system keyboard with "Close Keyman" sometimes triggers crash too.

### Configuration ###
13.0 master
Android 8.1 device
SIL EuroLatin keyboard (after nrc.en.mtnt dictionary uninstalled)
Application: Google Keep

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #2539

During #2326, `KMManager.onDestroy()` was updated to set `InAppKeyboard` and `SystemKeyboard` to null. While good in practice, this created  an issue when closing Keyman as a System Keyboard. Lingering Javascript calls in the WebView would crash with the null keyboards.

This reverts `onDestroy()` to how it has been since before 2.8 stable

### Testing
- [ ] Start Keyman app
- [ ] With Keyman as System Keyboard, verify the following:
  * Rotate between profile and landscape orientation and verify Keyman doesn't crash
  * Use the globe button to bring up keyboard picker
  * Click "Close Keyman" to switch to next system keyboard and verify Keyman doesn't crash
  * Bring up Keyman app and verify Keyboard doesn't crash

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java [hunk 1]
```diff
@@ -405,11 +405,9 @@ public static void onPause() {
   public static void onDestroy() {
     if (InAppKeyboard != null) {
       InAppKeyboard.onDestroy();
-      InAppKeyboard = null;
     }
     if (SystemKeyboard != null) {
       SystemKeyboard.onDestroy();
-      SystemKeyboard = null;
     }
```
Comment (darcywong00) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: > Can you explain the code path that would trigger this issue? It bothers me that we continue using those objects after calling `onDestroy`.

My initial test scenarios were with the Keyman app running in the background, Keyman as system keyboard, and then closing the Keyman system keyboard. If it  hadn't crashed, the Keyman app would have a blank keyboard.

Some of the crashes after `onDestroy` occured with the following calls

-----

`KMManager.pageLoaded()` ~ line 1490
```
if (!InAppKeyboard.keyboardSet) {
```
-----

`KMHardwareKeyboardInterpreter.onKeyDown()` ~ line 26
```
boolean isChiral = KMManager.getKMKeyboard(this.keyboardType).getChirality();
```

Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: I'm not seeing how the `onKeyDown` event could crash -- unless it's actually in `KMManager.getKMKeyboard`.

So, this looks like a bit of a design issue -- the awkward split between `InAppKeyboard` and `SystemKeyboard`, and then lifecycle is uncertain and not validated in `KMManager`. A better long-term fix would be to ensure that we had valid state at any entry point in `KMManager` (e.g. `if(InAppKeyboard != null) ...`.

But that may be too much work for today; if so, feel free to turn this into an issue for the future.

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: k, that will be deferred in #2543
