### PR TITLE
fix(common): Fix setting context when >= 64 characters

### LINKED ISSUE #2002: [Linux] keyman stops working when textline reaches some length limit
**Describe the bug**

LibreOffice Writer and gedit (including its fork mousepad) stop recognizing character sequences, such as `-a > ā`, when the length of the text line is more than 60 symbols:

```
āāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāā-a-a-a-a-a-a-a
ēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēēē
```

Typing "-e" in the second line, you can add one more symbol "ē", but following typing will not transform into the compound symbol.

**To Reproduce**

1. Start `gedit`
2. Create an empty document (File|New)
3. Star typing "-a"
4. When the line reaches length of 60 symbols "ā", you will see the bug.

---

**Keyman for Linux:**
 - OS: Manjaro (Arch Linux based)
 - Keyman version: 11.0.122
 - Target Application: LibreOffice, gedit
 
---
 
**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.8.1

---

**Notes**

Notepadqq is not affected, so it may be a GTK-related bug.

### LINKED ISSUE #2575: [Linux] Rules misbehave if line length is more than 100 characters
The issue is noticed with Malayalam keyboard we developed. I have added a rule in keyman keybaord layout file wherein after space some characters should not appear. This rule is working prefectly OK if the characters of the sentence is less than 100, but if this is greater than 100 the rule is not working.

In Windows and MAC no such issue is there.
Attached all the files

[G.zip](https://github.com/keymanapp/keyman/files/4148194/G.zip)

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #2002, Fixes #2575

Several Keyman for Linux users reported that keyboard rules stop working after the context length hits a limit (~ > 64 characters)

This PR fixes Keyman Core when shifting the internal buffer in `KMX_Context::Set` (also accounting for deadkeys and SMP characters).

Also added 3 kmx unit texts for verifying boundary conditions.

### CODE REVIEW

File: common/engine/keyboardprocessor/src/kmx/kmx_options.cpp [hunk 1]
```diff
@@ -33,7 +33,7 @@ void KMX_Options::AddOptionsStoresFromXString(PKMX_WCHAR s) {
       case CODE_SAVEOPT:
       case CODE_RESETOPT:
         idx = *(s + 2) - 1;
-        if (idx >= 0 && idx < _kp->Keyboard->cxStoreArray && _kp->Keyboard->dpStoreArray[idx].dpName != NULL) {
+        if (idx < _kp->Keyboard->cxStoreArray && _kp->Keyboard->dpStoreArray[idx].dpName != NULL) {
```
Comment (darcywong00) [inline common/engine/keyboardprocessor/src/kmx/kmx_options.cpp]: This fixes a meson warning since `idx` is a unsigned int making `idx >= 0` always TRUE.

File: common/engine/keyboardprocessor/src/kmx/kmx_context.cpp [hunk 2]
```diff
@@ -78,11 +78,28 @@ void KMX_Context::Set(const KMX_WCHAR *buf)
...
+  }
+
+  // If the first character in the buffer is a surrogate pair,
+  // or a deadkey, our buffer may be too long, so move to the
+  // next character in the buffer
+  if ((int)(q-p) > MAXCONTEXT - 1) {
+    p = incxstr((KMX_WCHAR*)p);
+  }
+
+  for(q = CurContext; *p; p++, q++)
```
Comment (darcywong00) [inline common/engine/keyboardprocessor/src/kmx/kmx_context.cpp]: The for loop is much simpler now because all the special characters were already handled above

File: common/engine/keyboardprocessor/tests/unit/kmx/041 - long context and deadkeys.kmn [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+store(&version) '6.0'
+
+begin Unicode > use(Main)
+
+group(Main) using keys
+
+c Test 1 
+dk(1) 'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh' + '1' > context '1'
+
+c Test 2
```
Comment (mcdurdin) [inline common/engine/keyboardprocessor/tests/unit/kmx/041 - long context and deadkeys.kmn]:
```suggestion
c Test 2: test that we haven't split a deadkey code: `UC_SENTINEL CODE_DEADKEY <deadkey_number>`
c   because: `CODE_DEADKEY` = `U+0008`; `deadkey_number` = `U+0001`
```

File: common/engine/keyboardprocessor/tests/unit/kmx/041 - long context and deadkeys.kmn [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+U+0008 U+0001 'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh1' + '2' > 'FAIL TEST 2'
+U+0001 'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh1' + '2' > 'FAIL TEST 2'
+'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh1' + '2' > context '2'
+
+c Test 3
```
Comment (mcdurdin) [inline common/engine/keyboardprocessor/tests/unit/kmx/041 - long context and deadkeys.kmn]:
```suggestion
c Test 3: test that we haven't split a deadkey code: `UC_SENTINEL CODE_DEADKEY <deadkey_number>`
c   because: `CODE_DEADKEY` = `U+0008`; `deadkey_number` = `U+0001`
```

File: common/engine/keyboardprocessor/tests/unit/kmx/042 - long context and split deadkeys.kmn [hunk 5]
```diff
@@ -0,0 +1,12 @@
...
+c keys: [K_SPACE]
+c context: \u00ffff\u000008\u00000001abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh
+c expected: \u00ffff\u000008\u00000001abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh\u0020
+
+store(&version) '6.0'
+
+begin Unicode > use(Main)
+
+group(Main) using keys
+
```
Comment (mcdurdin) [inline common/engine/keyboardprocessor/tests/unit/kmx/042 - long context and split deadkeys.kmn]:
```suggestion

```suggestion

c Test 1: test that we haven't split a deadkey code: `UC_SENTINEL CODE_DEADKEY <deadkey_number>`
c   here, looking at last char only: `deadkey_number` = `U+0001`
```

File: common/engine/keyboardprocessor/tests/unit/kmx/kmx.cpp [hunk 6]
```diff
@@ -362,7 +362,8 @@ std::u16string parse_source_string(std::string const & s) {
         size_t n;
         std::string s1 = s.substr(p - s.begin(), 8);
         v = std::stoul(s1, &n, 16);
-        assert(v >= 0x20 && v <= 0x10FFFF);
+        // Allow deadkey characters onward
+        assert(v >= CODE_ANY && v <= 0x10FFFF);
```
Comment (mcdurdin) [inline common/engine/keyboardprocessor/tests/unit/kmx/kmx.cpp]:
```suggestion
        assert(v >= 0x0001 && v <= 0x10FFFF);
```

Don't use `CODE_ANY` because that's a little misleading -- it happens to have the same value but is not what we are actually testing!
