### PR TITLE
fix(developer): new file support for project 2.0

### LINKED ISSUE #10276: bug(developer): Crash after clicking "New package" button
I opened the `common/test/keyboards/baseline/baseline.kpj` project in Keyman Developer. I upgraded the project to the new 17.0 project format and then pressed the "New package" button. This crashed the app.

Keyman Developer 17.0.229 and 17.0.230 on Windows 10

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #10276.

Adding new files to a v2.0 project was unsupported. This requires a little bit of a logic change to the two new File New dialogs:

1. The New File Details dialog does not allow changing from the SourcePath of the project.
2. The New File dialog does allow changing to any path. If you select a path outside the project path, it will open in a new window.

# User Testing

* **TEST_NEW_FILE_10:** Open an existing v1.0 project file, click File|New, and create a new file (any type). Verify that it creates correctly.

* **TEST_NEW_FILE_DETAILS_10:** Open an existing v1.0 project file, click `New Keyboard...`` in the Project tab, Keyboards view, and create a new keyboard file. Verify that it creates correctly.

* **TEST_NEW_FILE_20:** Create a v2.0 project file, click File|New, and create a new file (any type). Verify that it creates correctly and that it is placed into the project SourcePath folder.

* **TEST_NEW_FILE_20_ELSEWHERE:** Create a v2.0 project file, click File|New, and create a new file (any type). Change the Path field to another folder (e.g. a temporary folder). Verify that the file is created correctly and is opened in a new instance of Keyman Developer.

* **TEST_NEW_FILE_DETAILS_20:** Create a v2.0 project file, click `New Keyboard...`` in the Project tab, Keyboards view, and create a new keyboard file. Verify that it creates correctly and that it is placed into the project SourcePath folder.

### CODE REVIEW

File: developer/src/tike/dialogs/UfrmNew.pas [hunk 1]
```diff
@@ -321,6 +325,14 @@ procedure TfrmNew.mnuShowIconsClick(Sender: TObject);
   lvItems.ViewStyle := vsIcon;
 end;
 
+procedure TfrmNew.SetCanAddToProject(const Value: Boolean);
+begin
+  FCanAddToProject := Value;
+  if not Value then
+    chkAddToProject.Checked := False;
```
Comment (darcywong00) [inline developer/src/tike/dialogs/UfrmNew.pas:332]: Does `chkAddToProject.Checked` default to True?

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_NEW_FILE_10 (PASSED):** Tested with the attached Keyman Developer 17.0.239-alpha-test-10323 on Windows 11 OS and here is my observation: 1. Opened an existing v1.0 project file. 2. Created a new keyboard file successfully using File / New option.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_NEW_FILE_DETAILS_10 (PASSED):** Tested with the attached Keyman Developer 17.0.239-alpha-test-10323 on Windows 11 OS and here is my observation: 1. Opened an existing v1.0 project file. 2. Clicked 'New Keyboard' button from the Project- Keyboards view. 3. Successfully created a new keyboard file.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_NEW_FILE_20 (PASSED):** Tested with the attached Keyman Developer 17.0.239-alpha-test-10323 on Windows 11 OS and here is my observation: 1. Created a new v2.0 project file. 2. Created a new keyboard file. 3. Verified that it is created correctly and that it is placed into the project SourcePath folder.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_NEW_FILE_20_ELSEWHERE (PASSED):** Tested with the attached Keyman Developer 17.0.239-alpha-test-10323 on Windows 11 OS and here is my observation: 1. Created a new v2.0 project file. 2. Created a new keyboard file. 3. Changed the path to a Temporary folder. 4. Verified that the file was created correctly and was opened in a new instance of Keyman Developer.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_NEW_FILE_DETAILS_20 (PASSED):** Tested with the attached Keyman Developer 17.0.239-alpha-test-10323 on Windows 11 OS and here is my observation: 1. Created a new v2.0 project file. 2. Clicked "New Keyboard" button from the Project - Keyboards view. 3. Created a new keyboard file. 4. Verified that it was successfully created and placed into the Project SourcePath folder.

File: developer/src/tike/dialogs/UfrmNew.pas (hunk 1 above)
Comment (mcdurdin) [reply developer/src/tike/dialogs/UfrmNew.pas:332]: Yes:

https://github.com/keymanapp/keyman/blob/070ead74cf88e96b932184a07d57a692a9a86077/developer/src/tike/dialogs/UfrmNew.dfm#L100

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.242-alpha](https://keyman.com/downloads/releases/alpha/17.0.242)
