### PR TITLE
fix(windows): Show full version with tag in Setup

### LINKED ISSUE #4041: bug(windows): setup should show full version string of version to be installed
**Describe the bug**

Currently Setup shows the old style 4-component version number. It should show the current a.b.c-tier-extra pattern instead.

**Screenshots**

image

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 2004 x64 
 - Keyman version: 14.0.194-alpha

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4041.

Show the version with tier and build flags in Setup so that it is clear which version of Keyman will be installed, as the Keyman version can be distinct from the setup.exe version.

Constructs the version tag from `version`+`stability` data in the `UpdateCheckResponse` and uses a new MSI property called `VersionWithTag` for Windows Installers. Older MSIs will still show `a.b.c.d` versions instead of the tagged version if they are checked locally (as opposed to online), because the new `VersionWithTag` property will not be present.

image

image

### CODE REVIEW

File: windows/src/desktop/setup/UfrmInstallOptions.pas [hunk 1]
```diff
@@ -260,23 +260,10 @@ procedure TfrmInstallOptions.SetupDynamicOptions;
...
-      case FInstallInfo.BestMsi.LocationType of
-        iilLocal:  Text := FInstallInfo.Text(ssOptionsUpgradeKeyman, [FInstallInfo.BestMsi.Version]);
-        iilOnline: Text := FInstallInfo.Text(ssOptionsDownloadUpgradeKeyman, [FInstallInfo.BestMsi.Version, FormatFileSize(FInstallInfo.BestMsi.Size)]);
-      end;
-}
   end
   else if FInstallInfo.IsInstalled then
   begin
-    Text := FInstallInfo.Text(ssOptionsKeymanAlreadyInstalled, [FInstallInfo.InstalledVersion.Version]);
+    Text := FInstallInfo.Text(ssOptionsKeymanAlreadyInstalled, [FInstallInfo.InstalledVersion.Version]);//TODO VersionWithTag?
```
Comment (jahorton) [inline windows/src/desktop/setup/UfrmInstallOptions.pas:266]: This `//TODO` is intentionally left unresolved?

**Review by jahorton — APPROVED** [review]
Looks fine.

I did note one new `//TODO` that might be worth a spot-check before you merge, but it's probably nothing egregious.

File: windows/src/desktop/setup/UfrmInstallOptions.pas (hunk 1 above)
Comment (mcdurdin) [reply windows/src/desktop/setup/UfrmInstallOptions.pas:266]: Yes, because we don't have access to `VersionWithTag` without a lot more plumbing here 😭. So this is left as a future (low priority) project.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.215-beta](https://keyman.com/downloads/releases/beta/14.0.215)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.9-alpha](https://keyman.com/downloads/releases/alpha/15.0.9)
