### PR TITLE
[Android] Fix File Provider collision

### LINKED ISSUE #2039: [Android] Regression: unable to run multiple apps with Keyman Engine due to conflict with com.tavultesoft.kmea.fileProvider provider
**Describe the bug**
PR #2020 moved the `com.tavultesoft.kmea.fileProvider` provider from Keyman to Keyman Engine. However, this means that only one app with the engine can be installed on a device.

The proposed fix is to move the manifest data back again into Keyman, and pass an additional `fileProvider` parameter to Keyman Engine from the app.

If the parameter is not provided, then any functionality in the engine which uses the provider (e.g. showing the keyboard Info page) should be disabled and hidden.

At install time, the following debug-level error was seen:

```
Installation failed with message Failed to commit install session 373329842 with command cmd package install-commit 373329842. Error: INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/com.firstvoices.keyboards-jFYlEho7E6-kKltZyE94oA==: Can't install because provider name com.tavultesoft.kmea.fileProvider (in package com.firstvoices.keyboards) is already used by com.tavultesoft.kmapro.debug.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.
```

And the FV Keyboards app would not install until Keyman was uninstalled.

---
  
**Android:**
 - Device: Nokia 3
 - OS: Android 9
 - Keyman version 12.0.x beta

### PR DESCRIPTION
**Pull request by darcywong00**
Fix #2039 

This PR fixes the namespace collision of File Provider by placing the onus of applications to declare it in their Android manifest file.

* Add utility `FileProviderUtils` to check if File Provider exists
* If File Provider doesn't exist, the help links on the info pages are disabled

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelInfoActivity.java [hunk 1]
```diff
@@ -45,13 +46,13 @@
...
   private final String subtitleKey = "subtitle";
   private final String iconKey = "icon";
-  private final String isEnabledKey = "isEnabled";
 
   @Override
   public void onCreate(Bundle savedInstanceState) {
     super.onCreate(savedInstanceState);
     supportRequestWindowFeature(Window.FEATURE_NO_TITLE);
     final Context context = this;
+    final String authority = getApplication().getPackageName() + ".fileProvider";
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/ModelInfoActivity.java]: Should use `FileProviderUtils.getAuthority(context)`?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardSettingsActivity.java [hunk 2]
```diff
@@ -42,13 +47,14 @@
...
   private final String subtitleKey = "subtitle";
   private final String iconKey = "icon";
-  private final String isEnabledKey = "isEnabled";
 
   @Override
   public void onCreate(Bundle savedInstanceState) {
     super.onCreate(savedInstanceState);
     supportRequestWindowFeature(Window.FEATURE_NO_TITLE);
     final Context context = this;
+    final String authority = getApplication().getPackageName() + ".fileProvider";
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardSettingsActivity.java]: Should use `FileProviderUtils.getAuthority(context)`

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardInfoActivity.java [hunk 3]
```diff
@@ -43,6 +46,7 @@ public void onCreate(Bundle savedInstanceState) {
     super.onCreate(savedInstanceState);
     supportRequestWindowFeature(Window.FEATURE_NO_TITLE);
     final Context context = this;
+    final String authority = getApplication().getPackageName() + ".fileProvider";
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KeyboardInfoActivity.java]: Should use `FileProviderUtils.getAuthority(context)`
