### PR TITLE
fix(android/engine): Show keyboard after rotating

### LINKED ISSUE #5277: bug(android): Keyman for Android disappears on Twitter post after rotating and can't get it back on
**Describe the bug**

Keyman works OK in vertical mode on Twitter, but when switch to the horizontal mode it disappears. Tapping in the text area again does not bring it back on either.

**To Reproduce**

1. Go to 'Twitter' and tap to start writing a tweet using the default Keyman keyboard (EuroLatin)
2. Tilt the keyboard to horizontal to continue typing
3. The keyboard disappears and now tap in the text area on the tweet 

**Expected behavior**

The keyboard should appear and work as normal in the horizontal mode.

---

**Keyman for Android:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Keyman version 
https://github.com/keymanapp/keyman/pull/5247

### LINKED ISSUE #5965: bug(android): Shift state becomes inactive after rotation while it's on
**Describe the bug**

While Shift state is active, try and rotate the phone and then try and press on the shift key to see that it doesn't switch to the shift layer at all. The key become inactive.

https://user-images.githubusercontent.com/28331388/143209847-b550dbfc-a490-4af4-a99e-fd0dd1053268.mov

**Expected behavior**

The shift key should not become inactive because of leaving it on prior to the rotation.

---

**Keyman for Android:**
 - Device: Pixel 2 emulator
 - OS: Android 10
 - Keyman version 15.0.154-alpha-est-5958
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.9.5
 - Language name: English

**Additional context**

cf. https://github.com/keymanapp/keyman/pull/5958

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #5277 and possibly fixes #5965

Update SystemKeyboard to show the keyboard after a keyboard change.

## User Testing
Setup
1. Install the the PR build of Keyman for Android
2. Dismiss the "Getting Started" menu and enable Keyman as the default system keyboard

* **TEST_ROTATION** - Verifies the Keyman keyboard is visible after rotating device and the layer can change
1. Launch a separate app (e.g. Twitter or Chrome)
2. With the Keyman keyboard, start typing. Note, any stuck popup keys are addressed separately by #6494
3. Select the "Shift" layer and continue typing
4. Rotate the device
5. Verify after rotation, the Keyman keyboard refreshes and is visible. Note, the layer reverts to Default layer.
6. Continue typing
7. Verify the keyboard continues to output text in the current field and it's lower-case (default layer of SIL EuroLatin).
8. Select the "Shift" layer
9. Verify the keyboard displays the Shift layer
10. Type a character
11. Verify the keyboard outputs a capital letter and stays on the Shift layer (with SIL Euro Latin keyboard)

### CODE REVIEW

File: android/KMEA/app/src/main/assets/android-host.js [hunk 1]
```diff
@@ -308,6 +308,12 @@ function hideKeyboard() {
   window.location.hash = 'hideKeyboard' + fragmentToggle;
 }
 
+function showKeyboard() {
+  var kmw=window['keyman'];
+  // Refresh KMW OSK
+  kmw.correctOSKTextSize();
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/assets/android-host.js:314]: There's no value in the indirection of the variable -- we should eliminate elsewhere in the future but at least let's not make it worse 😁 

```suggestion
  // Refresh KMW OSK
  keyman.correctOSKTextSize();
```

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.230-beta](https://keyman.com/downloads/releases/beta/15.0.230)
