### PR TITLE
fix(android): Fix exception in ResourcesUpdateTool

### LINKED ISSUE #2743: [Android] ResourceUpdateTool causes crash when app is closed
This is affecting a lot of users on [Crashlytics](https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/5abd6c9831c913e93eb75d28da472079)
with 13.0.6200 stable

When the Keyman app is closed, `currentContext` doesn't exist, so this throws a null-pointer exception

ResourceUpdateTool line 334

I wonder if it's better to just dismiss all the update notifications if the app is closed.

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #2743 and crashlytic issue
https://console.firebase.google.com/u/1/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/5abd6c9831c913e93eb75d28da472079

which affected many users.

The primary fix was checking the context isn't null.

While updating ResourcesUpdateTool(), also added a cleanup method to clear the notification bar when exiting Keyman.

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java [hunk 1]
```diff
@@ -49,7 +49,7 @@
    * Force resource update.
    * Only for testing, should be false for merging
    */
-  public static final boolean FORCE_RESOURCE_UPDATE = false;
+  public static final boolean FORCE_RESOURCE_UPDATE = true;
```
Comment (jahorton) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java:52]: Blocking on this, just to be safe.

Comment (jahorton) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java:52]: Otherwise, LGTM.

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/logic/ResourcesUpdateTool.java:52]: ooh, good catch
