### PR TITLE
[iOS] Direct use of specific language lists for downloads

### LINKED ISSUE #1944: [ios] "Add Keyboard" from "Installed Language" view shows the whole list briefly, then the sublist.
"Add Keyboard" from "Installed Language" view leads to showing the whole list initially, then the sublist. Clicking Back then shows the whole list again. The whole list should never be shown.

**To Reproduce**
1. Go to Settings->Installed Languages-><a Language>
2. Click on '+'
3. See error

**Expected behavior**
The list of keyboards of the current language should be shown, only. Clicking back from the list should go  straight to the current language screen.

---
 - Device: iPhone 7
 - OS: iOS version = 12.3.1
 - Keyman version 12.0 beta (very first)
 - Target application: Keyman

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #1944.

Note that a significant amount of the new code is effectively duplicated from `LanguageViewController`.  At least it's largely UI code duplication.

An abstraction might be possible, but it'd be best served by including an enhanced abstraction on the API repositories that would require more time to flesh out and would likely result in significant extra work.  This is also extra work that could help continue the technical debt retirement of #1979... so I think a more robust version would be better left until our next big tech debt push.

- [ ] Needs history.md changes.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/160547:id/kvk/index.html)

File: ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageDetailViewController.swift [hunk 1]
```diff
@@ -31,8 +42,26 @@ class LanguageDetailViewController: UITableViewController, UIAlertViewDelegate {
...
+    
     loadUserKeyboards()
   }
+  
+  func postLanguageLoad(languageDict: [String: Language]) {
+    pendingFetch = false
+    
+    if let language = languageDict[self.language.id] {
+      self.language = language
+      // Do something to update the view.
```
Comment (mcdurdin) [inline ios/engine/KMEI/KeymanEngine/Classes/LanguagePicker/LanguageDetailViewController.swift]:
```suggestion
      // TODO: Do something to update the view.
```
