### PR TITLE
fix(developer): Map symbols for *LTREnter* and *LTRBkSp*

### LINKED ISSUE #4015: bug(developer): `*LTREnter*` and `*LTRBkSp*` do not display correctly in KMDev builder.js
**Describe the bug**

`*LTREnter*` and `*LTRBkSp*` do not display correctly in KMDev builder.js. Ref #3878.

**Screenshots**

image

---

**Keyman Developer:**
 - OS: Windows 10 1909 x64 
 - Keyman Developer version: 14.0.192-alpha

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4015.

Maps `*LTREnter*` and `*LTRBkSp*` to the correct symbols on the touch layout builder.

image

### CODE REVIEW

File: windows/src/developer/TIKE/xml/layoutbuilder/builder.js [hunk 1]
```diff
@@ -606,9 +606,11 @@ $(function () {
...
     '*ShiftLock*':      0x73,
     '*ShiftedLock*':    0x74,
-    '*ZWNJ*':           0x75, // If this one is specified, auto-detection will kick in.
-    '*ZWNJiOS*':        0x75, // The iOS version will be used by default, but the
-    '*ZWNJAndroid*':    0x76, // Android platform has its own default glyph.
+    '*ZWNJ*':           0x75, // * If this one is specified, auto-detection will kick in.
+    '*ZWNJiOS*':        0x75, //   The iOS version will be used by default, but the
+    '*ZWNJAndroid*':    0x76, //   Android platform has its own default glyph.
+    '*LTREnter*':       5,    // * Forces LTR shaping for the Enter/BkSp keys regardless
+    '*LTRBkSp*':        4,    //   of layout's directionality.
```
Comment (jahorton) [inline windows/src/developer/TIKE/xml/layoutbuilder/builder.js:613]: I'd personally add these in the range of lines 573 to 575 (by their non-directional counterparts), but that's mostly personal preference.

**Review by jahorton — APPROVED** [review]

File: windows/src/developer/TIKE/xml/layoutbuilder/builder.js (hunk 1 above)
Comment (mcdurdin) [reply windows/src/developer/TIKE/xml/layoutbuilder/builder.js:613]: I opted to group with 14.0 changes :)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.215-beta](https://keyman.com/downloads/releases/beta/14.0.215)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.9-alpha](https://keyman.com/downloads/releases/alpha/15.0.9)
