### PR TITLE
Fix custom keyboard download

### LINKED ISSUE #411: Custom keyboard download broken
Opening `keyman://localhost/open?direct=true&url=https://marc.durdin.net/wp-content/uploads/2015/11/khmer10-1.2.json` or `keyman://localhost/open?keyboard=hebrew&language=heb` should open a dialog in Keyman prompting download of the keyboard but nothing happens.

(Couldn't get links to `keyman://` working on GitHub)

### PR DESCRIPTION
**Pull request by gabrielwong**
Fixes #411.

Tested on `keyman://localhost/open?direct=true&url=https://marc.durdin.net/wp-content/uploads/2015/11/khmer10-1.2.json` and `keyman://localhost/open?keyboard=hebrew&language=heb`

### CODE REVIEW

File: ios/engine/KMEI/KeymanEngine/Classes/Extension/JSONDecoder.DateDecodingStrategy+ISO8601Fallback.swift [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+import Foundation
+
+extension JSONDecoder.DateDecodingStrategy {
+  static var ios8601WithFallback: JSONDecoder.DateDecodingStrategy {
+    if #available(iOS 10.0, *) {
+      return .iso8601
+    }
+    let formatter = DateFormatter()
+    formatter.locale = Locale(identifier: "en_US_POSIX")
+    formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZZZ"
```
Comment (darcywong00) [inline ios/engine/KMEI/KeymanEngine/Classes/Extension/JSONDecoder.DateDecodingStrategy+ISO8601Fallback.swift]: Do you need to define timeZone? UTC?

File: ios/keyman/Keyman/Keyman/MainViewController.swift [hunk 2]
```diff
@@ -879,51 +878,44 @@ class MainViewController: UIViewController, TextViewDelegate, UIActionSheetDeleg
...
-    } else {
+
+      Manager.shared.dismissKeyboardPicker(self)
+      if !infoView.view.isHidden {
+        perform(#selector(self.infoButtonClick), with: nil)
+      }
+
+      customKeyboardToDownload = [
+        "url": url,
+        "direct": params["direct"] == "true"
```
Comment (mcdurdin) [inline ios/keyman/Keyman/Keyman/MainViewController.swift]: Let's ignore the 'direct' parameter and always go with direct. Deprecates that additional layer of complexity.

File: ios/engine/KMEI/KeymanEngine/Classes/Extension/JSONDecoder.DateDecodingStrategy+ISO8601Fallback.swift (hunk 1 above)
Comment (gabrielwong) [reply ios/engine/KMEI/KeymanEngine/Classes/Extension/JSONDecoder.DateDecodingStrategy+ISO8601Fallback.swift]: I believe the `ZZZZZ` specifies time zone.

For reference, I took the format from [here](https://stackoverflow.com/questions/16254575/how-do-i-get-an-iso-8601-date-on-ios). Note the caveat that this format doesn't deal with milliseconds, but the API doesn't provide them either from what I observed.
