### PR TITLE
fix(mac): add support for M1 processor

### LINKED ISSUE #5700: bug(mac): textinputsource does not support arm64 architecture
**Describe the bug**

All the apps bundled in the Keyman installer support arm64, except textinputsource. Attempting to install on an M1 mac without Rosetta 2 installed gives the following error:

image

Originally reported at https://community.software.sil.org/t/does-keyman-support-m1-mac/5213

---

**Keyman for Windows/macOS/Linux:**
 - OS: macOS 11 (M1) 
 - Keyman version: 14.0.280

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #5700.

Adds support for arm64 (M1) to textinputsource in the Keyman app. All other executables are already fat with support for both x86_64 and arm64.

Note: https://help.keyman.com/knowledge-base/107 needs to be updated once this and a cherry-picked to 14 version are released.

# User Testing

* TEST_INSTALL_M1: Make sure Keyman installs on an M1 mac (I will run this test as I have the M1 mac on my desk).
* TEST_INSTALL_INTEL: Make sure Keyman installs and runs on Intel-based mac.

### CODE REVIEW

**Comment by mcdurdin** [comment]
* TEST_INSTALL_M1: PASSED the install now runs without requiring Rosetta and Keyman works correctly.

**Comment by darcywong00** [comment]
Is there any change for a developer's system requirements?

https://github.com/keymanapp/keyman/blob/master/mac/README.md#setting-up-your-code-signing-and-notarization-environment
> With macOS 10.14 and later...

**Comment by MakaraSok** [comment]
* **TEST_INSTALL_INTEL: FAILED** An error pops up: `No such text input source: Keyman`.

image

After clinking on `OK`, the error message goes away, but Keyman is not found in the input source on the taskbar near the clock and `System Preferences > Keyboard > Input Sources`.

Tested on macOS Big Sur, Version 11.6 (20G165).

File: mac/setup/build.sh [hunk 1]
```diff
@@ -29,6 +29,13 @@ fi
 osacompile -o "$SOURCEAPP" -x source/install.applescript
 cp source/applet.icns "$SOURCEAPP/Contents/Resources/applet.icns"
 
+# Add arm64 to plist so that the script is not marked as requiring Rosetta
+# ... LSArchitecturePriority
+# https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary#Specify-the-Launch-Behavior-of-Your-App
+/usr/libexec/PlistBuddy -c "Add :LSArchitecturePriority array" "$SOURCEAPP/Contents/Info.plist"
+/usr/libexec/PlistBuddy -c "Add :LSArchitecturePriority:0 string 'arm64'" "$SOURCEAPP/Contents/Info.plist"
+/usr/libexec/PlistBuddy -c "Add :LSArchitecturePriority:1 string 'x86_64'" "$SOURCEAPP/Contents/Info.plist"
+
```
Comment (jahorton) [inline mac/setup/build.sh:38]: Is it not possible to add these entries directly to `mac/Keyman4Mac/Keyman4Mac/Info.plist` (or whichever .plist file it is)?

Comment (mcdurdin) [reply mac/setup/build.sh:38]: No, this is the installer plist, which is created by osacompile a few lines earlier.

**Comment by mcdurdin** [comment]
> * An error pops up: `No such text input source: Keyman`.

I don't think this is related to this specific fix as it has been reported elsewhere (e.g. @sgschantz noted it) -- can you open a new issue on this?

**Comment by mcdurdin** [comment]
> Is there any change for a developer's system requirements?
> 
> https://github.com/keymanapp/keyman/blob/master/mac/README.md#setting-up-your-code-signing-and-notarization-environment
> 
> > With macOS 10.14 and later...

Good pick. It only impacts doing a release build, for the setup script, but we require osacompile from macOS 11 Big Sur because it supports building arm64+x86_64 fat executables, whereas 10.x only builds x86_64 executables. I will add some wording.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
> > * An error pops up: `No such text input source: Keyman`.
> 
> I don't think this is related to this specific fix as it has been reported elsewhere (e.g. @sgschantz noted it) -- can you open a new issue on this?

See #5578. Please ignore this problem as it is not related to this particular fix, when testing.

@keymanapp-test-bot retest

**Comment by MakaraSok** [comment]
TEST_INSTALL_INTEL: PASSED The app installs and runs without any issue experienced.

**Comment by darcywong00** [comment]
Will this also address #5573?

**Comment by mcdurdin** [comment]
> Will this also address #5573?

It seems more likely that #5573 is an issue with macOS 12. I am investigating that separately.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.118-alpha](https://keyman.com/downloads/releases/alpha/15.0.118)
