### PR TITLE
fix(mac): externalize strings for package info window localization

### LINKED ISSUE #6081: bug(mac) Localize webview for keyboard info page
@MakaraSok When I did the internationalization for the Mac, I missed all the strings in this view because it is a webview, and I didn't notice the labels coded in HTML. So these must still appear in English for the Khmer localization, too. 

I'm not sure how I missed that -- I might have assumed they had a different source like the help pages. I'll need to externalize the keyboard info strings so they can be localized.

_Originally posted by @sgschantz in https://github.com/keymanapp/keyman/issues/6040#issuecomment-1004581500_

### PR DESCRIPTION
**Pull request by sgschantz**
fixes #6081
The Package Information window in Keyman for Mac is composed with HTML and could not be localized because label strings were still hard-coded in HTML. This change externalizes the labels so that this window can be included with localization.

I also changed some of the terminology in the related UI for consistency and simplicity:
"Keyboard Layouts" to "Keyboards", in the Configuration tab and within the Package Information window
"Keyboard/Package Info" window title to "Package Information"

Previous naming:
image

New naming:
image
image

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

Are you wanting to skip user testing on this?

**Comment by sgschantz** [comment]
We should test with another language, so I need to get the Khmer translations for the new strings from Makara and add them to the project and then do the user test. I'll give @MakaraSok the English strings and ask him for those.

**Comment by MakaraSok** [comment]
> I'll give @MakaraSok the English strings and ask him for those.

The translation has been done and sent over on Slack. :)

**Comment by sgschantz** [comment]
# User Testing
* TEST_KHMER_LANGUAGE: Go to the Mac System Preferences and change the preferred language to Khmer. It may be necessary to restart the machine for the language change to take effect. Run Keyman, go to the Configuration window and select the Info icon for a keyboard package. Verify that the Package Information window title and labels are in Khmer as shown:

image

**Comment by MakaraSok** [comment]
- **TEST_KHMER_LANGUAGE: PASSED** the language on package info page does change to KM.

image

File: mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/KMInfoWindowController.m [hunk 1]
```diff
@@ -82,7 +81,11 @@ - (BOOL)tabView:(NSTabView *)tabView shouldSelectTabViewItem:(NSTabViewItem *)ta
     return YES;
 }
 
+// TODO: refactor: any reason for this to be HTML? hard to read stringWithFormat applied to template with 16 arguments
```
Comment (mcdurdin) [inline mac/Keyman4MacIM/Keyman4MacIM/KMInfoWindow/KMInfoWindowController.m:84]: I think this was probably mimicking the Windows UX. The readme.htm file, if present, is currently presented in an iframe so would need to be included, and the QR code and image are also presented in HTML, so that would take additional rewriting.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.179-alpha](https://keyman.com/downloads/releases/alpha/15.0.179)
