### PR TITLE
fix(developer): kmc warnings tidyup 🗜

### LINKED ISSUE #9296: chore(developer): KM0208A should be `info` severity 🗜
Example:
`postmodern_english_uk_dualstroke.kmn:158 - warn KM0208A: The compiler has assigned a minimum engine version of 9.0 based on features used in this keyboard`

### LINKED ISSUE #9297: chore(developer): KM0500D should have filename prefix 🗜
example:
`info KM0500D: More than 100 warnings or errors received; suppressing further messages.`

### LINKED ISSUE #9298: chore(developer): KM05009 should have filename prefix and use relative paths 🗜
example:
`hint KM05009: File C:\Projects\keyman\keyboards\release\rac\rac_brahui\source\Readme.htm differs in case from reference C:\Projects\keyman\keyboards\release\rac\rac_brahui\source\readme.htm; this will fail on platforms with case-sensitive filesystems.`

### LINKED ISSUE #9299: chore(developer): Broken warning for missing required keys (missing quote, missing data) 🗜
example:
`indonesia.kmn - warn KM02093: Layer "withnumbers" on platform "tablet" is missing the required key(s) '.`

### LINKED ISSUE #9300: chore(developer): KM0400F seems to be more antsy than in 16.0 🗜
example:
`fv_gwichin.kps - warn KM0400F: The file Aboriginal Sans BOLD 9434.ttf does not follow the recommended filename conventions. The extension should be all lower case, and the filename should include only alphanumeric characters, -, _, + and .`

and

`nisenan.kps - warn KM0400F: The file nisenan.keyman-touch-layout does not follow the recommended filename conventions. The extension should be all lower case, and the filename should include only alphanumeric characters, -, _, + and .` (but see also warning about including source files)

This looks like it relates to checkFilenameConventions option in .kpj having wrong default value.

### PR DESCRIPTION
**Pull request by mcdurdin**
* Fixes #9300: respect checkFilenameConventions in kmc
* Fixes #9299: clean up warning KM02093
* Fixes #9298: use relative paths for KM05009
* Fixes #9297: consistently show filename for messages in kmc
* Fixes #9296: reduce KM0208A to info severity

Throws in: warning colour changed to orange to differentiate from line number colour.

Note for #9296: 208A in kmcmplib is the awkwardly-named CWARN_Info. We now have an 'info' severity in kmc, so this tidies that up (we can keep the same flag in kmcmplib for now).

@keymanapp-test-bot skip

### CODE REVIEW

File: developer/src/common/include/kmn_compiler_errors.h [hunk 1]
```diff
@@ -184,7 +184,7 @@
 #define CWARN_ANSIInUnicodeGroup                           0x00002087
 #define CWARN_UnicodeSurrogateUsed                         0x00002088
 #define CWARN_ReservedCharacter                            0x00002089
-#define CWARN_Info                                         0x0000208A
+#define CWARN_Info                                         0x0000008A
```
Comment (ermshiperete) [inline developer/src/common/include/kmn_compiler_errors.h:187]: A comment similar to the one in `developer/src/kmc-kmn/src/compiler/messages.ts` might be helpful to explain why the value is not in the 0x2000 range.

Also it might be helpful to additionally define `CINFO_Info`:

```suggestion
#define CWARN_Info                                         0x0000008A
#define CINFO_Info                                         CWARN_Info
```

File: developer/src/kmc-package/test/test-messages.ts [hunk 2]
```diff
@@ -122,8 +122,10 @@ describe('CompilerMessages', function () {
   // WARN_FileInPackageDoesNotFollowFilenameConventions
 
   it('should generate WARN_FileInPackageDoesNotFollowFilenameConventions if content filename has wrong conventions', async function() {
-    testForMessage(this, ['invalid', 'warn_file_in_package_does_not_follow_filename_conventions.kps'], CompilerMessages.WARN_FileInPackageDoesNotFollowFilenameConventions);
-    testForMessage(this, ['invalid', 'warn_file_in_package_does_not_follow_filename_conventions_2.kps'], CompilerMessages.WARN_FileInPackageDoesNotFollowFilenameConventions);
+    testForMessage(this, ['invalid', 'warn_file_in_package_does_not_follow_filename_conventions.kps'],
+      CompilerMessages.WARN_FileInPackageDoesNotFollowFilenameConventions, {checkFilenameConventions: true});
+    testForMessage(this, ['invalid', 'warn_file_in_package_does_not_follow_filename_conventions_2.kps'],
+      CompilerMessages.WARN_FileInPackageDoesNotFollowFilenameConventions, {checkFilenameConventions: true});
   });
```
Comment (ermshiperete) [inline developer/src/kmc-package/test/test-messages.ts:129]: We might also want to test that we don't get a warning if `checkFilenameConversion == false` or not set.

**Review by ermshiperete — APPROVED** [review]

File: developer/src/kmc-package/test/test-messages.ts (hunk 2 above)
Comment (mcdurdin) [reply developer/src/kmc-package/test/test-messages.ts:129]: See #9317.
