### PR TITLE
fix(android): Handle banner overrides independently when device is locked and unlocked

### LINKED ISSUE #13531: bug(android): Broken image banner when locking and unlocking screen
Split out of #13512 

### Describe the bug

*  A broken image appeared on the lock screen's keyboard.
* Also  it seems clear that `KMManager.mayPredictOverride` is set to disable predictions... so it must not be getting unset when the lock screen's conditions are satisfied.

### Reproduce the bug

Steps to reproduce:
Setup - on an Android device, go to system Settings and set a simple password for the lock screen

1. Installed the Keyman-18.0.214-beta.apk.
2. Launch Keyman for Android
3. From "Get Started" menu, enable Keyman as the default system keyboard
4. Enter a text content.
5. Install a khmer_angkor keyboard by clicking three dots --> Settings --> Install Keyboard or Dictionary.
6. Return to keyman's note app.
7. Change the keyboard from Khmer to euro_latin by the globe key.
8. Lock the screen by pressing the power key.
9. Open the unlock screen by pressing the power key.
10. Observed 1: Here, the keyman banner does not appear on the lock screen. instead, a broken image appeared.
11. Enter the password to unlock the mobile.
12. Observed 2: Here, the keyman note app appeared and the keyman banner appeared.
13. Press the globe key.
Actual Result: An error appeared in the toast message.

Note: Unable to take video on lock screen

### Expected behavior

_No response_

### Related issues

_No response_

### Keyman apps

- [x] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

Keyman-18.0.214-beta

### Operating system

_No response_

### Device

Android 14

### Target application

_No response_

### Browser

_No response_

### Keyboard name

khmer_angkor

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #13531 (both bugs)
* A broken image appeared on the lock screen's keyboard.
* Also it seems clear that `KMManager.mayPredictOverride` is set to disable predictions... so it must not be getting unset when the lock screen's conditions are satisfied.

### Broken image bug
The first bug about the broken image link is fixed with 1 line to SystemKeyboard.java.
```java
BannerController.setHTMLBanner(this, KeyboardType.KEYBOARD_TYPE_SYSTEM);
```

### Override bug
Currently, when the SYSTEM Keyman keyboard is on a password field, the `mayPredictOverride` override is set to true and concurrently disables suggestions for both INAPP Keyman keyboard and SYSTEM Keyman keyboard.

(edited after applying review comments)
This PR refactors undocumented API's so `mayPredictOverride` API calls are independently handled in INAPP and SYSTEM keyboards.
API renames:
| From (Keyman 12.0-17.0) | To (Keyman 18.0+) |
|---------|------|
| `inAppMayPredictOverride` | `inAppPredictionsSuspendedForSensitiveInput` |
| `systemMayPredictOverride`  |`systemPredictionsSuspendedForSensitiveInput` |
| | |
| `getMayPredictOverride()` | `getPredictionsSuspended()` |
| `setMayPredictOverride()` | `setPredictionsSuspended()` |

TODO - update KMManager API docs

## User Testing
**Setup** - Install the PR build of Keyman for Android. In the "Get Started" menu, set Keyman as the default system keyboard. Also install a Keyman Basic Lao keyboard [basic_kbdlao](https://keyman.com/keyboards/basic_kbdlao) that doesn't use a suggestion banner. On the Android device/emulator also do system settings and set a simple "1234" password for the lock screen. If using an actual device, have a secondary unlock method (fingerprint)

* **TEST_BANNER_TOGGLE** - Verifies HTML and suggestion banners toggle correctly
1. Start Keyman for Android
2. In the Keyman app, use the globe key to select sil_euro_latin keyboard.
3. Verify suggestions appear on the banner
4. Use the globe key to switch to the Basic Lao keyboard
5. Verify the image banner appears
6. Launch Chrome and browse to this test page. (It has basic text fields and a password text field)
 https://darcywong00.github.io/examples/form.html
7. With Keyman as the system keyboard, select the "Visible Text Field".
8. Use the globe key to select the sil_euro_latin keyboard
9. Verify suggestions appear on the banner
10. Use the globe key to switch to Basic Lao keyboard
11. Verify the image banner appears
12. Use the globe key to select sil_euro_latin keyboard
13. Verify suggestions appear on the banner
14. Select the "Password Field"
15. Verify the suggestions are disabled and the image banner appears
16. Return the Keyman app
17. With the sil_euro_latin keyboard verify suggestions appear in the app
18. Make sure the Keyman app is the active app
19. Lock the device
20. Unlock the device - use Keyman to enter the password. Verify suggestions are disabled
21. When the device is unlocked and the Keyman app is resumed, observe the sil_euro_latin keyboard and verify suggestions appear.

### CODE REVIEW

**Comment by dinakaranr** [comment]
# Test Results

I tested this issue in the "Keyman-18.0.219-beta-test-13546" build(20/03/2025) on Android 14 physical device and Android 9 emulator. Here I am sharing my observation.

* **TEST_BANNER_TOGGLE (Passed):**
Prerequisite step: Install the Basic Lao keyboard.

1. Start Keyman for Android
2. In the Keyman app, use the globe key to select the sil_euro_latin keyboard.
3. Verified that the suggestions appeared on the banner
4. Use the globe key to switch to the Basic Lao keyboard
5. Verified that the image banner appeared
6. Set the Keyman as the system keyboard.
7. Launch Chrome and browse to this test page. (It has basic text fields and a password text field)
8. (https://darcywong00.github.io/examples/form.html)
9. Verified that the page loaded correctly
10. Click in the "Visible Text Field" box.
11. Use the globe key to select the sil_euro_latin keyboard
12. Verified suggestions appeared on the banner
13. Use the globe key to switch to the Basic Lao keyboard
14. Verified that the image banner appeared
15. Use the globe key to select sil_euro_latin keyboard
16. Verified suggestions appeared on the banner
17. Click in the "Password Field" box.
18. Verified the suggestions are disabled and the image banner appears
19. Return the Keyman app
20. With the sil_euro_latin keyboard. verified suggestions appeared in the app
21. Make sure the Keyman app is the active app
22. Lock the device
23. Unlock the device - use Keyman to enter the password. Verified suggestions are disabled on the lock screen.
24. When the device is unlocked and the Keyman app is resumed.
25. Verified that the sil_euro_latin keyboard appeared and then verified suggestions appeared.
Hence, the Banner toggle works well when the device is locked and unlocked.

**Comment by mcdurdin** [comment]
Leaving this for @sgschantz to review for now

**Review by sgschantz — COMMENTED** [review]
This looks good, though I was initially confused on the meaning of `mayPredictOverride` in the two booleans for system and inApp keyboards. Elsewhere you remove the 'may' in `determinePredictOverride` and is a little easier to parse. 

I think the problem is that you are overriding `mayPredict`, but concatenating three verbs like this leaves room for interpretation as to which verb aligns to the boolean. With the other flag, the boolean indicates whether you 'may' or not, whereas here, the boolean indicates whether it is an override or not.

Also, instead of 'override' can you call this something like 'block' or 'force disable'. Override already has another meaning in OOP, and it is also kind of indifferent. It may be changing the behavior one way or another. Here, you are only blocking predictions from happening when predictions are already enabled, correct? Override will never mean that you will enable predictions that are already disabled by the user.

I imagine the meaning of these things is apparent to anyone familiar with the code, but I think it would be more readable with some name changes.

**Comment by darcywong00** [comment]
> though I was initially confused on the meaning of `mayPredictOverride`

The variable name was used in Keyman 12.0 in PR #2255.  The name originates from the configuration of the KeymanWeb `ModelManager` class that has the property `mayPredict` designed for toggling suggestions when the lexical-model is loaded

https://github.com/keymanapp/keyman/pull/2255#discussion_r339451802

The "Override" is because typing in a password fields trumps whatever the user has set in the LanguageSettings menu (where predictions and corrections are enabled/disabled).

Oops, I now see these calls never got added to the online help. More TODO's
https://help.keyman.com/developer/engine/android/17.0/KMManager/
* getMayPredictOverride()
* setMayPredictOverride()

**Comment by sgschantz** [comment]
Are you saying that nothing can be renamed because it is part of a published API? That would be unfortunate.

I doubt that most people would easily make sense out of 'setMayPredictOverride' when they look at it. It is basically four consecutive verbs. We really need function and property names to have a clear meaning on their own without examining the implementation to discover what state they change or how they impact the logic.

**Comment by sgschantz** [comment]
I guess the key things to rename are the two static variables:
`inAppMayPredictOverride`
`systemMayPredictOverride`

Predictions are enabled because of the user setting, but disabled temporarily because we are editing a password. I was thinking that predictions are disabled or blocked, but it is probably better to describe them as suspended. 'Suspended' makes it clear that predictions are unavailable and also implies that it is temporary, and when the suspension ends, the user's settings will again take effect.

So that would give us something like:
`systemPredictionsSuspended`
`inAppPredictionsSuspended`

It could be a little more verbose if it isn't clear what system and inApp refer to:
`systemKeyboardPredictionsSuspended`
`inAppKeyboardPredictionsSuspended`
but that is probably unnecessary.

We could also include why they are suspended since this will probably only ever be set for password editing:
`inAppPredictionsSuspendedForSensitiveInput`
`systemPredictionsSuspendedForSensitiveInput`

That is even more self-explanatory by describing the purpose of the suspension, but it may be misinterpreted to mean that a value of false would allow you to perform predictions when you are making sensitive input, which we would not allow.

Instead, you could just document in the code that this flag is set temporarily when editing a password field.

I guess you would just add a setter and a getter for this
`setSystemPredictionsSuspended`
`getSystemPredictionsSuspended`
`setInAppPredictionsSuspended`
`setInAppPredictionsSuspended`

Then the function `determinePredictOverride` could be renamed to `determinePredictionsSuspended`. That might be a little unclear though because it returns a boolean. That makes it seem like the function is answering the question as to whether we should determine something. It might be a little clearer to go with:
`shouldSuspendPredictions(inputType)`

Do you have any other ideas or do you think those would work ok?

**Comment by mcdurdin** [comment]
> Are you saying that nothing can be renamed because it is part of a published API? That would be unfortunate.

Given it isn't published yet, I think we can go ahead and change it.

But, yes, in general a published API shouldn't be changed lightly. When we come to our API refresh release, then I think it's all fair game.

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java [hunk 1]
```diff
@@ -244,6 +244,12 @@ public void onActivityResult(int requestCode, int resultCode, Intent returnInten
   @Override
   protected void onResume() {
     super.onResume();
+
+    if (textView != null) {
+      // Reset mayPredictOverride
```
Comment (sgschantz) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java:249]: comment references earlier name

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java [hunk 2]
```diff
@@ -257,10 +257,13 @@ public int toInt() {
   // haptic feedback disabled for hardware keystrokes
   private static boolean mayHaveHapticFeedback = false;
 
-  // Special override for when keyboard is entering a password text field.
-  // When mayPredictOverride is true, the option {'mayPredict' = false} is set in the lm-layer
+  // Special overrides to temporarily disable predictions when editing a password field.
```
Comment (sgschantz) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:260]: maybe call these variables or flag instead of overrides (just because overrides sounds like Java method override)

**Review by sgschantz — APPROVED** [review]
looks good! just a couple references in comments to update for the new variable names

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.222-beta](https://keyman.com/downloads/releases/beta/18.0.222)
