### PR TITLE
fix(web): publish restorePosition() function

### LINKED ISSUE #4948: bug(web): `setRect()` sets `dlftX` and `dfltY` but no way to reset these via API
Once `setRect({left:x, top:y})` has been called, `restorePosition()` no longer resets the position to pin to the active text field. Internally, this is because once `keyman.osk.dfltX` and `keyman.osk.dfltY` are set, there is no API to reset them. `restorePosition()` should probably be clearing those values (or there should be another API to do that).

Furthermore, `dfltX` and `dfltY` are not persisted to KMW's cookies.  This is likely due to the assumption that they'd be automatically re-established during a page's initiation on future visits / refreshes.

_Originally posted in https://github.com/keymanapp/help.keyman.com/issues/379_

---

**KeymanWeb:**
 - OS: any 
 - Browser: any 
 - KeymanWeb Version: 14.0.271

### PR DESCRIPTION
**Pull request by mcdurdin**
This makes the `osk.restorePosition()` function public and makes it work even if the OSK is not presently visible. Also DRY out the repeated implementation.

Also fixes #4948.

Inspired by https://community.software.sil.org/t/keyboard-location/4655/10 and will cherry-pick to stable-14.0 upon approval. Will also update help.keyman.com shortly and reference this PR there.

Note, I have not tried to DRY out the rest of the `_TitleBarInterior()`/`controlBar()` chaos but certainly worth doing.

### CODE REVIEW

File: web/source/osk/oskManager.ts [hunk 1]
```diff
@@ -482,17 +470,25 @@ namespace com.keyman.osk {
     }
 
     /**
-     * Move OSK back to default position
+     * Function     restorePosition
+     * Scope        Public
+     * Description  Move OSK back to default position, floating under active input element
      */
     restorePosition: () => void = function(this: OSKManager) {
```
Comment (jahorton) [inline web/source/osk/oskManager.ts:477]:
```suggestion
    ['restorePosition']: () => void = function(this: OSKManager) {
```

Comment (jahorton) [reply web/source/osk/oskManager.ts:477]: Without this change, we'll lose access to the function in minified versions of KMW.

**Review by jahorton — CHANGES_REQUESTED** [review]
This does not properly publish the `restorePosition` function.

**Comment by jahorton** [comment]
On a side note, I'd be totally fine with throwing a solution for #4948 in with these changes.  Small scope, same function, after all.

**Comment by mcdurdin** [comment]
> On a side note, I'd be totally fine with throwing a solution for #4948 in with these changes. Small scope, same function, after all.

Do you mind if I scope that as a separate PR? I'm just a little leery of more potential side-effects w.r.t. the pin div.

**Review by jahorton — COMMENTED** [review]
I will say that [this comment](https://github.com/keymanapp/keyman/issues/4948#issuecomment-824492311), in particular, _does_ belong as part of this PR:

> FWIW, I think we should consider breaking `restorePosition()` into two functions: a wrapper for the event handlers for the pin, and a public function -- so that we don't do the grungy event fiddling within `restorePosition()` but only when we are responding to direct interaction with the pin div:
>
> https://github.com/keymanapp/keyman/blob/c7adfd116d96cf290d0ffbb4d36fa525f6dd53bc/web/source/osk/oskManager.ts#L499-L501

**Comment by mcdurdin** [comment]
> I will say that [this comment](https://github.com/keymanapp/keyman/issues/4948#issuecomment-824492311), in particular, _does_ belong as part of this PR:

Fair enough. Working on it.

File: web/source/osk/oskManager.ts [hunk 2]
```diff
@@ -482,22 +470,40 @@ namespace com.keyman.osk {
...
-        this.loadCookie();
-        this.userPositioned=false;
-        this.saveCookie();
+      }
+
+      this.loadCookie();
+      this.userPositioned=false;
+      if(!keepDefaultPosition) {
+        delete this.dfltX;
+        delete this.dfltY;
```
Comment (mcdurdin) [inline web/source/osk/oskManager.ts:489]: Resets these values only if called by API consumer (with falsy parameter) but not by pin div onclick...

File: web/testing/unminified.html [hunk 3]
```diff
@@ -42,62 +42,68 @@
...
-    <input type='button' id='btn3' onclick='addKeyboard(3);' value='Add' />   
+    <input type='button' id='btn3' onclick='addKeyboard(3);' value='Add' />
 
     <h3><a href="./">Return to testing home page</a></h3>
+
+    <h3>Control keyboard position</h3>
+    <input type='button' onclick='keyman.osk.restorePosition(true);document.getElementById("ta1").focus();' value='restorePosition(true)' />
+    <input type='button' onclick='keyman.osk.restorePosition(false);document.getElementById("ta1").focus();' value='restorePosition(false)' />
+    <input type='button' onclick='keyman.osk.restorePosition();document.getElementById("ta1").focus();' value='restorePosition()' />
+    <input type='button' onclick='keyman.osk.setRect({left:16, top:16});document.getElementById("ta1").focus();' value='setRect(16,16)' />
```
Comment (mcdurdin) [inline web/testing/unminified.html:89]: @jahorton You may want to place this into a separate html file? I just wanted a quick and easy place to test the `restorePosition()` function

Comment (jahorton) [reply web/testing/unminified.html:89]: Yeah, I'd definitely prefer a separate HTML file.  Should be simple enough to (mostly) copy and paste this file with a new name in its own folder; I did that for a lot of the test pages.

**Review by jahorton — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.33-alpha](https://keyman.com/downloads/releases/alpha/15.0.33)
