### PR TITLE
fix(web): Fix types that listInputs and isKMWInput accept

### LINKED ISSUE #8848: bug(web): listInputs vs isKMWInput -  different accepted types of HTMLInputElement
> This set is different to `isKMWInput` test.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/8801#discussion_r1200008064_ 

------

> Guess that should be marked as an issue?   Or should I go ahead and fix it here?  And, if the latter, should I use the larger set?
>
> From `master`:
>
> https://github.com/keymanapp/keyman/blob/fafe498775d4a01445e44fb92e59e7428c5f80f8/web/src/engine/main/dom/domManager.ts#L805
> 
> https://github.com/keymanapp/keyman/blob/fafe498775d4a01445e44fb92e59e7428c5f80f8/web/src/engine/main/dom/domManager.ts#L812-L823
>
> and...
>
> https://github.com/keymanapp/keyman/blob/fafe498775d4a01445e44fb92e59e7428c5f80f8/web/src/engine/main/dom/domManager.ts#L495-L501

_Originally posted by @jahorton in https://github.com/keymanapp/keyman/pull/8801#discussion_r1201410123

### PR DESCRIPTION
**Pull request by ermshiperete**
This changes `isKMWInput` so that it accepts the same `HTMLInputElement` types that `listInputs` accepts. 

Closes #8848.

@keymanapp-test-bot skip

### CODE REVIEW

**Comment by mcdurdin** [comment]
Can we split the changes relating to unit test infrastructure into a separate PR please?

**Comment by jahorton** [comment]
Cause of Web's CI build failure:

```
02:20:09 
  [common/web/es-bundling] ## build completed successfully

02:20:11 
  node_modules/@types/node/globals.d.ts(114,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.

02:20:11 
  [common/web/utils] ## build failed

```

I have vague memories of a minor headache from this in the past, but I don't recall the details at the moment.  Maybe... using JSDOM might have updated `@types/node` (or similar) in a way that leads to this problem?  That's my initial "stab in the dark," at least.

File: web/src/engine/attachment/src/pageContextAttachment.ts [hunk 1]
```diff
@@ -236,7 +236,7 @@ export class PageContextAttachment extends EventEmitter<EventMap> {
     if(x instanceof x.ownerDocument.defaultView.HTMLTextAreaElement) {
       return true;
     } else if(x instanceof x.ownerDocument.defaultView.HTMLInputElement) {
-      if (x.type == 'text' || x.type == 'search') {
+      if (x.type == 'email' || x.type == 'search' || x.type == 'text' || x.type == 'url') {
```
Comment (jahorton) [inline web/src/engine/attachment/src/pageContextAttachment.ts:239]: Part of me wonders if we should migrate this condition to a method on `Input`... perhaps `Input.isSupportedType(type: string): boolean`?  We are kind of WET re: the types.

Could then call that directly for the _entire_ condition here and replace the switch in the other spot.

**Review by jahorton — APPROVED** [review]
LGTM as-is.

Just a thought, though - we might be able to DRY out the check a bit.

File: web/src/engine/attachment/src/pageContextAttachment.ts (hunk 1 above)
Comment (jahorton) [reply web/src/engine/attachment/src/pageContextAttachment.ts:239]: This, in turn, allows `Input` to self-document which types it supports, rather than having them prescribed / defined outside of the class responsible for the element's primary support.

Comment (ermshiperete) [reply web/src/engine/attachment/src/pageContextAttachment.ts]: Good idea. Done.

**Review by jahorton — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.231-alpha](https://keyman.com/downloads/releases/alpha/17.0.231)
