### PR TITLE
fix(windows): incxstr could run over buffer with malformed data

### LINKED ISSUE #4591: bug(windows): incxstr can have a buffer overrun in malformed xstrings
```diff
-		case CODE_EXTENDED:		p += 2; while(*p != UC_SENTINEL_EXTENDEDEND) p++; return p+1;
+		case CODE_EXTENDED:		p += 2; while(*p && *p != UC_SENTINEL_EXTENDEDEND) p++; return p+1;
```

This fixes a buffer overrun on malformed xstrings. I need to make the same change in Keyman Engine and verify Keyman Core also.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/pull/4584#r587765356_

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4591.

I fixed incxstr in 4 places:

1. Common/Core: kmx_xstring.cpp
2. Engine: xstring.cpp
3. Test project importkeyboard importkeyboard.cpp
4. Test project m-to-p m-to-p.cpp

I updated mcompile to remove its own copy of incxstr (identical to that in xstring.cpp) to reduce WETness but opted not to do so for the test apps, which are pretty much throwaway anyway.

I note that there is more work we could do here; we need to check every character as we increment so we don't miss a `U+0000` end of string with malformed data. But I would like to tackle that as a separate job at some point in the future after Core integration.

### CODE REVIEW

File: windows/src/engine/mcompile/mc_crc32.cpp [hunk 1]
```diff
@@ -1,5 +1,5 @@
 
-#include "stdafx.h"
+#include "pch.h"
```
Comment (mcdurdin) [inline windows/src/engine/mcompile/mc_crc32.cpp:2]: Because our global C++ classes are not yet in a shared library, we have to do dumb things like this where precompiled headers are inconsistent between projects. Yuck. Another possible groundwork project for 15.0?

**Comment by jahorton** [comment]
> Fixes #4591.
>
> [...]
>
> I note that there is more work we could do here; we need to check every character as we increment so we don't miss a `U+0000` end of string with malformed data. But I would like to tackle that as a separate job at some point in the future after Core integration.

So... it _doesn't_ fix the issue?  Or did you plan to make another, more specific issue for this?

**Comment by mcdurdin** [comment]
> So... it _doesn't_ fix the issue? Or did you plan to make another, more specific issue for this?

It fixes one issue. There remain others which will be more work to resolve. I'll turn it into an issue.

**Review by jahorton — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.253-beta](https://keyman.com/downloads/releases/beta/14.0.253)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.19-alpha](https://keyman.com/downloads/releases/alpha/15.0.19)
