### PR TITLE
fix(ios): Fixes bad initialization of system keyboard width

### LINKED ISSUE #2260: [ios] Keyman iOS app landscape orientation
**Describe the bug**
If the youtube was in landscape, keyman keyboard was preselected before opening youtube app (say notes app). If keyboard is required to share the video link or post comment, keyman starts in landscape. Only the suggestion bar will be in full width, keyboard will be in the size of the portrait.

**To Reproduce**
1. keyman keyboard should be preselected before opening youtube app (say notes app).
2. Open youtube, start a video, orient the video to landscape
3. tap on share the video.
4. choose message to share the video.
5. Keyman keyboard will appear in landscape, but the width of the keys will be in portrait.

I have attached the screenshot.

**Screenshots**
IMG_BFE59E8B6E32-1

  
**iPhone/iPad/Android (please complete the following information):**
 - iPhone 11 pro mac
 - OS: iOS 13.1.2 and iOS 13.2
 - Keyman version 12.0.53
 - Target application: Notes, mail, ...

**Keyboard**
 - Keyboard name: SIL EUROLATIN
 - Keyboard version: 1.8.1
 - Language name: English

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #2260.

These changes ensure that the Swift side of the keyboard can provide the KMW side with an initial width, bypassing the need for the failing `window.orientation` check (which was used to produce said initial width).

### CODE REVIEW

File: ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift [hunk 1]
```diff
@@ -855,6 +859,7 @@ extension KeymanWebViewController {
     // Ensures the height is properly updated.
```
Comment (darcywong00) [inline ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift]:
```suggestion
     // Ensures the width and height are properly updated.
```
