### PR TITLE
fix(web): Use regex to determine display layer and functional layers

### LINKED ISSUE #6089: bug(android): longpress with Shift+RightAlt not working on touch
**Describe the bug**

A longpress key with reference to a key with Shift+RightAlt in the computer layout does not output anything. 
It works just fine though when testing on Chrome emulator.

This was encountered when testing [Ukwuani keyboard](https://drive.google.com/drive/folders/1M-HUkJhfvLgb9_G4d-WVuo2tMlqRNl-7).

**To Reproduce**

1. On the current stable version of Keyman (14.0.283) install the keyboard above.
2. Go the Shift layer and then press and hold on key <kbd>E</kbd> to output the capital E with a dot below
3. See error - nothing is output.

**Expected behavior**

The longpress with such reference should work as normal, just like how it works in Chrome emulator.

---

**Keyman for Android:**
 - Device: Pixel XL
 - OS: Android 10.0
 - Keyman version: 14.0.283-stable
 - Target application: Keyman

**KeymanWeb:**
 - OS: Windows 10
 - Browser: Chrome
 - KeymanWeb Version: ?
 - URL: N/A (test it locally using the Ukwuani keyboard project above.

---

**Additional context**

This works OK in iOS when testing with Keyman 14.0.284.

### PR DESCRIPTION
**Pull request by darcywong00**
fixes #6089

> A longpress key with reference to a key with Shift+RightAlt in the computer layout does not output anything.
It works just fine though when testing on Chrome emulator.

I initially started porting the changes in #5651 from stable-14.0, but Makara reported seeing the issue in 14.0 too. Thus, portions of this PR will need to be 🍒 picked back to stable-14.0

The complication in kmwembedded.ts comes from parsing `keyName` which contains:
[display layer]-[virtual key name]+[optional function layer] where display layer and function layer can contain multiple `-` delimiters.
For example: 'ctrl-shift' or 'rightalt-shift'

The virtual key name  can also be T_* , K_* , U_*, ~or ISO 9995 format~

In @MakaraSok 's issue, the displayLayer is 'shift' while the functional layer is 'rightalt-shift' from the longpress key.

## User Testing
Setup:
For each platform test, install the following keyboards (some were used in testing #5651):
1. ukwuani (zip of [source](https://github.com/keymanapp/keyman/files/7845806/ukwuani.zip))
2. sil_madi
3. sil_cameroon_qwerty

* **TEST_ANDROID**
1. Launch Keyman
2. Test and verify sil_euro_latin keyboard:
    a. Use the globe key to switch to sil_euro_latin keyboard
    b. On the "default" layer, longpress a key and select
    c. Verify the output character matches the longpress key
    d. Repeat for "shift" and "symbol" layers
3. Test and verify ukwuani keyboard:
    a. Use the globe key to switch to ukwuani keyboard
    b. On the default layer, Longpress on the <kbd>o</kbd>, <kbd>i</kbd>, <kbd>u</kbd>, <kbd>e</kbd>, or <kbd>n</kbd> keys and select the longpress key
    c. Verify the output character matches the longpress key
    d. Press <kbd>Shift</kbd> to switch to the "Shift" layer
    e. Longpress on the <kbd>O</kbd>, <kbd>I</kbd>, <kbd>U</kbd>, <kbd>E</kbd>, or <kbd>N</kbd> keys and select the longpress key
    f. Verify the output character matches the longpress key
4. Test and verify sil_madi keyboard:
    a. Use the globe key to switch to sil_madi keyboard
    b. On the default layer, longpress on a vowel and select it
    c. Verify the correct character is output
    d. Press <kbd>Shift</kbd> to switch to the "Shift" layer
    e. Longpress on the <kbd>A</kbd> and select one of the caps longpresses.
    f. Verify the correct character is output
5. Test and verify sil_cameroon_qwerty (verifies application of nextlayer)
    a. Use the globe key to switch to sil_cameroon_qwerty
    b. Press <kbd>Shift</kbd> to switch to the "Shift" layer
    c. Longpress on the <kbd>W</kbd> or <kbd>E</kbd> keys and select one of the caps longpresses
    d. Verify the correct character is output
    e. Verify the keyboard switches to the to the default layer
    f. Press <kbd>Shift</kbd> to switch to the "Shift" layer
    g. Press the spacebar
    h. Verify the layer remains on "Shift"
    i. For each of the following:
        * switch to the symbolic layer
        * longpress on the base key and select any of the longpress keys
        * verify the correct character is output
        * verify the keyboard **switches** to the default layer
        **Base Key**
        <kbd><<</kbd> 
        <kbd>>></kbd> 
        <kbd>'</kbd> (single quote)
        <kbd>"</kbd> (double quote)
    j. For each of the following:
        * switch to the symbolic layer
        * longpress on the base key and select any of the longpress keys
        * verify the correct character is output
        * verify the keyboard **remains** on the symbolic layer
        **Base Key**
        <kbd>(</kbd> 
        <kbd>)</kbd> 
        <kbd>?</kbd> (Note, the basekey <kbd>?</kbd> will switch to the default layer
        <kbd>!</kbd> (Note, the basekey <kbd>!</kbd> will switch to the default layer

* **TEST_IOS**
1. Repeat the same steps as ANDROID

### CODE REVIEW

**Comment by MakaraSok** [comment]
- **TEST_ANDROID: PASSED** All things work as indicated.
- **TEST_IOS: PASSED** All things work as indicated.

File: web/source/kmwembedded.ts [hunk 1]
```diff
@@ -361,14 +362,27 @@ namespace com.keyman.text {
...
+      if (matches[3]) {
+        // Optional function layer
+        functionalLayer = matches[3]
+        keyName += '+' + functionalLayer;
+      }
 
-      if (separatorIndex > 0) {
-        keyName = keyName.substring(separatorIndex+1);
+      if(displayLayer == 'undefined') {
+        displayLayer=keymanweb.core.keyboardProcessor.layerId;
```
Comment (rc-swag) [inline web/source/kmwembedded.ts:385]: What is display layer used for once it has been set?

Comment (darcywong00) [reply web/source/kmwembedded.ts]: It had more use in 14.0 code (#5651) where it was used to determine `layer` and then get the modifier state
```
// Determine the "functional" layer
      let layer = displayLayer;
      separatorIndex = keyName.lastIndexOf('+');
      if (separatorIndex > 0) {
        layer = keyName.substring(separatorIndex+1);
      }

      // Note:  this assumes Lelem is properly attached and has an element interface.
      // Currently true in the Android and iOS apps.
      var Lelem=keymanweb.domManager.getLastActiveElement(),keyShiftState=com.keyman.text.KeyboardProcessor.getModifierState(layer);
```

Lastly in 14.0, it was used to:
```
      // Check the virtual key 
        Lcode: Codes.keyCodes[keyName],
        LisVirtualKey: true,
        kName: keyName,
        kLayer: layer,
        kbdLayer: displayLayer,
        ...
```

**Comment by darcywong00** [comment]
Putting this back into draft. I'm gonna take another look in case the regex fails (displayLayer undefined)

**Comment by darcywong00** [comment]
> I'm gonna take another look in case the regex fails (displayLayer undefined)

Since TEST_IOS passed, I guess the displayLayer will always be defined.

**Review by rc-swag — APPROVED** [review]
LGTM

File: web/source/kmwembedded.ts [hunk 2]
```diff
@@ -361,14 +362,25 @@ namespace com.keyman.text {
...
 
-      // Can't just split on '-' because some layers like ctrl-shift contain it.
-      let separatorIndex = keyName.lastIndexOf('-');
+      let displayLayer = keymanweb.core.keyboardProcessor.layerId;
 
-      if (separatorIndex > 0) {
-        keyName = keyName.substring(separatorIndex+1);
+      // Regex for 'display layer'-'virtual key name'+'optional functional layer'
+      // Can't just split on '-' because some layers like ctrl-shift contain it.
+      // Virtual key can be T_, U_, K_, or ISO 9995
```
Comment (mcdurdin) [inline web/source/kmwembedded.ts:372]: ISO9995 identifiers are not valid in the touch layout. The regex should not test for these.

Furthermore, ISO9995 identifiers in .kmn are converted into the base key ids at compile time -- they aren't in the compiled keyboard.

File: web/source/kmwembedded.ts [hunk 3]
```diff
@@ -361,14 +362,25 @@ namespace com.keyman.text {
...
+      let rx = new RegExp("(.*)-([TKU]_[^+]*|[A-E]\\d\\d)\\+?(.*)?");
```
Comment (mcdurdin) [inline web/source/kmwembedded.ts:373]: Six things:

1. This regex should explicitly match the entire identifier -- we need to include `^` and `$`.
2. Why not use the normal Javascript regex enclosing with `/`, which avoids double-escaping?
3. Rather than use `.*` for the layer components, you should use `.+` -- we don't want a zero-length layer identifier!
4. I've removed the ISO9995 component.
5. A key identifier must be `T_`, `K_` or `U_` with one-or-more, not zero-or-more chars.
6. Use `const` where possible (or eliminate variables).

```suggestion
      const rx = /^(.+)-([TKU]_[^+]+)\+?(.+)?$/;
```

Or:

```
      const matches = keyName.match(/^(.+)-([TKU]_[^+]+)\+?(.+)?$/);
```

File: web/source/kmwembedded.ts [hunk 4]
```diff
@@ -361,14 +362,25 @@ namespace com.keyman.text {
       /* Clear any pending (non-popup) key */
       osk.vkbd.keyPending = null;
 
-      // Changes for Build 353 to resolve KMEI popup key issues      
+      // Changes for Build 353 to resolve KMEI popup key issues
       keyName=keyName.replace('popup-',''); //remove popup prefix if present (unlikely)
 
-      // Can't just split on '-' because some layers like ctrl-shift contain it.
-      let separatorIndex = keyName.lastIndexOf('-');
+      let displayLayer = keymanweb.core.keyboardProcessor.layerId;
```
Comment (mcdurdin) [inline web/source/kmwembedded.ts:368]: This value is never used.

File: web/source/kmwembedded.ts [hunk 5]
```diff
@@ -361,14 +362,25 @@ namespace com.keyman.text {
...
+      let matches = keyName.match(rx);
+      if (matches == null) {
+        return false;
+      }
+      displayLayer = matches[1];
+      keyName = matches[2];
+      let functionalLayer = '';
+      if (matches[3]) {
+        functionalLayer = matches[3];
+        keyName += '+' + functionalLayer;
```
Comment (mcdurdin) [inline web/source/kmwembedded.ts:383]: Why not simply `keyName += '+' + matches[3];` and remove the reference to `functionalLayer` altogether?

File: android/KMEA/app/src/main/assets/keyboard.html [hunk 6]
```diff
@@ -248,7 +248,8 @@
         var keyPos = x.toString() + ',' + y.toString();
         for(i=0; i<obj.length; i++)
         {
-          s=s+obj[i].layer+'-'+obj[i].coreID;
+          // elementID contains the layer and coreID
+          s=s+obj[i].elementID;
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/assets/keyboard.html:252]: I don't understand why we are making this change? Is this a separate fix bundled in?

File: web/source/kmwembedded.ts [hunk 7]
```diff
@@ -361,14 +362,25 @@ namespace com.keyman.text {
...
-        keyName = keyName.substring(separatorIndex+1);
+      // Regex for 'display layer'-'virtual key name'+'optional functional layer'
+      // Can't just split on '-' because some layers like ctrl-shift contain it.
+      // Virtual key can be T_, U_, K_, or ISO 9995
+      let rx = new RegExp("(.*)-([TKU]_[^+]*|[A-E]\\d\\d)\\+?(.*)?");
+      let matches = keyName.match(rx);
+      if (matches == null) {
+        return false;
+      }
+      displayLayer = matches[1];
```
Comment (mcdurdin) [inline web/source/kmwembedded.ts:378]: This is never used.

File: web/source/kmwembedded.ts [hunk 8]
```diff
@@ -361,14 +362,25 @@ namespace com.keyman.text {
...
+      keyName = matches[2];
+      let functionalLayer = '';
+      if (matches[3]) {
+        functionalLayer = matches[3];
+        keyName += '+' + functionalLayer;
       }
```
Comment (mcdurdin) [inline web/source/kmwembedded.ts:384]:
```suggestion
      keyName = matches[2] + (matches[3] ? '+' + matches[3] : '');
```

Additional optimisation possible: if we include the `+` in the final regex capture group, we can simplify to:

```
      const matches = keyName.match(/^(.+)-([TKU]_[^+]+)\+?(.+)?$/);
      if (matches == null) {
        return false;
      }
      // matches[1]: displayLayer
      // matches[2]: keyId
      // matches[3]: functionalLayer
      keyName = matches[2] + matches[3];
```

Note I am including the extra detail in comments so that it is compiled out to reduce the size of the compiled code -- critical for web.

**Review by mcdurdin — CHANGES_REQUESTED** [review]

File: android/KMEA/app/src/main/assets/keyboard.html (hunk 6 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/assets/keyboard.html:252]: It's from #5651 that corresponds @jahorton 's DM to me about activeLayout.ts
https://github.com/keymanapp/keyman/blob/6c17ecbd5f3f4ccd47d2330944a513125d06af1a/common/core/web/keyboard-processor/src/keyboards/activeLayout.ts#L112-L118

> This should be s=s+obj[i].elementID .

File: web/source/kmwembedded.ts (hunk 8 above)
Comment (darcywong00) [reply web/source/kmwembedded.ts]: I've incorporated all your comments above in the latest commit.

@keymanapp/test-bot retest

**Review by mcdurdin — APPROVED** [review]

**Comment by darcywong00** [comment]
Trying to trigger retest
@keymanapp-test-bot retest

**Comment by MakaraSok** [comment]
- **TEST_ANDROID: PASSED** Everything is still working as expected.
- **TEST_IOS: PASSED** Everything is still working as expected.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.180-alpha](https://keyman.com/downloads/releases/alpha/15.0.180)
