### PR TITLE
fix(windows): use new windows url for online update check

### LINKED ISSUE #3393: feat(windows): Online Update checks need to support 14.0 functionality
# Online Update Checks in Keyman for Windows
~~- [ ] Online update checks need to support package deprecations~~ (moving to 15.0)
~~- [ ] Online update checks need to support major version upgrades~~ (moving to 15.0)
- [ ] Online update checks need to support /windows/14.0/update path

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #3393.

### CODE REVIEW

File: windows/src/global/delphi/general/Upload_Settings.pas [hunk 1]
```diff
@@ -32,12 +32,11 @@ interface
 const
   // https://api.keyman.com/ - programmatic endpoints
   API_Path_UpdateCheck_Windows = '/windows/14.0/update'; // version will only update when the api changes
-
-  // TODO: use /windows/ instead of /desktop/
-  API_Path_UpdateCheck_Desktop = '/desktop/'+SKeymanVersion+'/update';  // TODO: use updatecheck_windows
```
Comment (jahorton) [inline windows/src/global/delphi/general/Upload_Settings.pas:37]: We're deleting `API_Path_UpdateCheck_Desktop`?  Is that intended?

File: windows/src/desktop/kmshell/main/OnlineUpdateCheck.pas [hunk 2]
```diff
@@ -559,11 +545,12 @@ function TOnlineUpdateCheck.DoRun: TOnlineUpdateCheckResult;
...
     try
       ShowUI := not FSilent;
-      Fields.Add('Version', ansistring(FCurrentVersion));
+      Fields.Add('version', ansistring(CKeymanVersionInfo.Version));
+      Fields.Add('tier', ansistring(CKeymanVersionInfo.Tier));
       for i := 0 to kmcom.Packages.Count - 1 do
       begin
         pkg := kmcom.Packages[i];
-        Fields.Add(ansistring('Package_'+pkg.ID), ansistring(pkg.Version));
+        Fields.Add(ansistring('package_'+pkg.ID), ansistring(pkg.Version));
```
Comment (jahorton) [inline windows/src/desktop/kmshell/main/OnlineUpdateCheck.pas:553]: I imagine not, since it looks to be a deliberate change, but just to be sure:

- This isn't going to cause case-sensitivity issues when updating from prior versions, is it?
- Alternatively, will the change that motivated this cause issues for previous versions?

File: windows/src/global/delphi/general/Upload_Settings.pas (hunk 1 above)
Comment (mcdurdin) [reply windows/src/global/delphi/general/Upload_Settings.pas:37]: Yes, that's correct -- we're moving towards `/windows` as the API endpoint root for Windows, rather than `/desktop`.

File: windows/src/desktop/kmshell/main/OnlineUpdateCheck.pas (hunk 2 above)
Comment (mcdurdin) [reply windows/src/desktop/kmshell/main/OnlineUpdateCheck.pas:553]: This is using the new 14.0 endpoint, so doesn't impact earlier versions.

**Review by jahorton — APPROVED** [review]
