### PR TITLE
fix[android]: Fix UI problem during keyboard switch

### LINKED ISSUE #2137: [Android] Streamlining the keyboard swap operation
In current beta builds of Keyman for Android (12.0.4092), **any** time the keyboard picker is used to change keyboards, there are two separate calls to the embedded page's `setKeymanLanguage` function, in rapid succession.  This results in the Android app doing significant amounts of unnecessary work.

This is also likely the cause of the, uh, less-than-smooth 'animation' that occurs when swapping keyboards.  It's always looked like the keyboards were repeatedly swapping in and out a bit before stabilizing... it turns out that this is near-exactly the case.  We swap the old keyboard for the new keyboard, throw the page away for a full reload, and then we load the new keyboard again.  This results in a lot of visual artifacting that we could somewhat simply remove.

### Recommendations

Either of the following two courses of action should remedy the issue:

1. Completely nix `KeyboardPickerActivity.switchKeyboard` in its current form.  The only important thing it accomplishes is to `saveCurrentKeyboardIndex`, so skip all the wasted JS calls and store the index separately.  Let the page reload do all the work - it's already been doing it, anyway.

2. Nix `KeyboardPickerActivity.onPause` or bypass its contents if we can tell that this was directly user-triggered.  This function does have the benefit of reducing the WebView's memory footprint, though - resetting the page means that we don't keep previously-used resources loaded.

---

## Diagnosing the issue

I first noted the core detail that lead to this diagnosis when using Chrome DevTools to debug the JS side of the 12.0 stability issues.  From there, I swapped to diagnosing the reason for the dual calls on the Java side.

Upon the app's initial load:
- passes through `KMManager.pageLoaded`, `if(!InAppKeyboard.keyboardSet)`

The initial load only calls `setKeyboard` once, which is fairly natural to expect.

Without doing anything else, a keyboard swap (ex: SIL EuroLatin -> Khmer Angkor) yields the following:
- `setKeymanLanguage` call #1:  Khmer Angkor (first call does have data for the 'target' keyboard)
    - Directly called via `KeyboardPickerActivity.switchKeyboard`.
- Call #2:  `KMManager.pageLoaded`
    - … and the `!InAppKeyboard.keyboardSet` branch of the if!?
    - At least it does (re)load Khmer.

Further examination here proves that currently, each keyboard swap has two separate phases - so let's break those phases down.

---

The first uses `KeyboardPickerActivity.switchKeyboard` on the current page.  (This also registers associated models, etc.)  This also does two important-to-note, interesting things:
- it sets `.keyboardSet` to `true` 
- it calls `saveCurrentKeyboardIndex`.

**After** this operation fully completes, the picker eventually self-dismisses, triggering `KeyboardPickerActivity.onPause`.  This then calls `KMKeyboard.loadKeyboard`, which sets `KMKeyboard.keyboardSet` to `false` and _force-resets the keyboard page_.  This near-completely invalidates the first 'set', but there's one important and necessary detail that it accomplished.  (More on that later.)

Once the triggered full-page-refresh finishes, the `InAppKeyboard.pageLoaded` event fires.  This is important because it has the critical `if (!InAppKeyboard.keyboardSet)` check - and since it is now "not set" due to having literally reloaded the base page, KMEA triggers the second `setKeyboard` call that results in the second keyboard load.

Fun fact - to perform the second keyboard load, it looks up the keyboard list index value saved by `saveCurrentKeyboardIndex` - without the first call, the second would not and could not succeed!

### PR DESCRIPTION
**Pull request by safolit**
Fixes #2137

## Previous Behavior ##
Keyboard switch using the keyboard picker in keyman seems to swaps the keyboard more than once.

@jahorton already analyzed that this behavior is caused by two separate calls to the embedded page's `setKeymanLanguage` function. 
The first one is the language switch and the second one a reload of keyboard when keyboardpicker is closed.

## New Behavior ##
Keyboard switch using the keyboard picker swaps only once. 
Fixed the multiple call of `setKeymanLanguage` function.

## Work Done ##
- Remove the call  to the embedded page's `setKeymanLanguage` function in the original `switchKeyboard`-method of keyboardpicker.

The keyboardswitch is now executed in 2 phases: 
- first step only prepares the keyboard switch on android site.
- second step: reload the keyboard and execute `setKeymanLanguage` when closing the keyboard picker

## Testing 
- open Keyboard selection in keyman
- select switch keyboard
- test also switching between keyboard with a dictionary and without.

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java [hunk 1]
```diff
@@ -459,6 +455,49 @@ public void run() {
...
+      languageID = KMManager.KMDefault_LanguageID;
+      retVal = false;
+    }
+    String kbKey = String.format("%s_%s", languageID, keyboardID);
+
+    keyboardVersion = KMManager.getLatestKeyboardFileVersion(getContext(), packageID, keyboardID);
+
+    setKeyboardRoot(packageID);
+
+    //TODO: check fonts?
```
Comment (darcywong00) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java]: Looks like this TODO can be removed.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java [hunk 2]
```diff
@@ -123,7 +115,22 @@
...
-  protected static String currentBanner = "blank";
+
+  /**
+   * Banner state value: "blank" - no banner available.
+   */
+  protected static final String KM_BANNER_STATE_BLANK = "blank";
+  /**
+   * Banner state value: "suggestion" - dictionary suggestions are shown.
+   */
+  protected static final String BANNER_STATE_SUGGESTION = "suggestion";
```
Comment (darcywong00) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: Good. Can you also replace the strings in these lines?
1168
1620
1839
1855

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java [hunk 3]
```diff
@@ -886,6 +893,41 @@ public static boolean setKeyboard(String packageID, String keyboardID, String la
...
+   * @param packageID the package id
+   * @param keyboardID the keyboard id
+   * @param languageID the language id
+   * @param keyboardName keyboard name
+   * @return the success result
+   */
+  public static boolean prepareKeyboardSwitch(String packageID, String keyboardID, String languageID, String keyboardName) {
+
+    //reset banner and layout params
+    currentBanner = KMManager.KM_BANNER_STATE_BLANK;
```
Comment (darcywong00) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java]: The keyboard loading is a lot better now!

Ideally, if we're switching from a keyboard with dictionary (e.g. sil_euro_latin) to another one with dictionary (e.g. fv_sencoten), we wouldn't have this "blank" banner flicker in between. It can wait for another day though.
