### PR TITLE
fix(windows): tweak scrolling in keyboard menu

### LINKED ISSUE #3694: bug(windows): the list does not stop when all keyboards are visible
**Describe the bug**
It is good to be able to scroll up or down the keyboard list to see all installed keyboards, but the scroll does not stop when all keyboards are revealed. It keeps going till only the bottom two are shown.

VirtualBox_Windows 10_09_10_2020_08_50_45

**To Reproduce**
1. Install as many keyboards as they would overflow the keyboard list when clicking on the Keyman icon from the taskbar.
2. Click on the down arrow at the bottom of the list to scroll down to see more keyboards
3. Keep scrolling

**Expected behavior**
Stop scrolling when all keyboards are visible.

---

**Keyman Desktop:**
 - OS: Windows 10 Pro 1909
 - Keyman version: 14.0.154-alpha
 - Target Application: [Self]

**Additional context**
https://github.com/keymanapp/keyman/pull/3627#issuecomment-705228470

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #3694.

The keyboard menu would sometimes scroll too far, which could be confusing for the end user. This fix stops the scroll once the last item is in view; it also tweaks the down arrow key handler to ensure that the current item is correctly scrolled into view.

### CODE REVIEW

File: windows/src/engine/keyman/UfrmKeymanMenu.pas [hunk 1]
```diff
@@ -726,18 +744,6 @@ procedure TfrmKeymanMenu.TntFormKeyDown(Sender: TObject; var Key: Word;
   if not Assigned(Fmnu) or not Assigned(Fmnu.Items) then Exit;  // I2884
 
   case Key of
-    {VK_NEXT:
```
Comment (mcdurdin) [inline windows/src/engine/keyman/UfrmKeymanMenu.pas:729]: Using the arrow keys already scrolls the list, so no need to overload pgup/dn for this.

**Review by darcywong00 — APPROVED** [review]
lgtm
