### PR TITLE
fix(android/engine): Improve KMManager robustness

### LINKED ISSUE #2543: bug(android): Improve robustness of KMManager.onDestroy
From review comment of #2541 about InAppKeyboard and SystemKeyboard calls being nullified and causing crashes

> So, this looks like a bit of a design issue -- the awkward split between InAppKeyboard and SystemKeyboard, and then lifecycle is uncertain and not validated in KMManager. A better long-term fix would be to ensure that we had valid state at any entry point in KMManager (e.g. if(InAppKeyboard != null) ....

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #2543

This PR ensures we have a valid state at any entry point in `KMManager` (e.g. `InAppKeyboard` and `SystemKeyboard` are not null when their methods are called)

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java [hunk 1]
```diff
@@ -394,10 +394,10 @@ public static boolean executeHardwareKeystroke(int code, int shift, int lstates,
...
     int code, int shift, KeyboardType keyboard, int lstates, int eventModifiers) {
-    if (keyboard == KeyboardType.KEYBOARD_TYPE_INAPP) {
+    if (keyboard == KeyboardType.KEYBOARD_TYPE_INAPP && InAppKeyboard != null) {
       InAppKeyboard.executeHardwareKeystroke(code, shift, lstates, eventModifiers);
       return true;
-    } else if (keyboard == KeyboardType.KEYBOARD_TYPE_SYSTEM) {
+    } else if (keyboard == KeyboardType.KEYBOARD_TYPE_SYSTEM && SystemKeyboard != null) {
       SystemKeyboard.executeHardwareKeystroke(code, shift, lstates, eventModifiers);
       return true;
     }
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java:403]: Should we be logging an `else { KMLog.LogError(); }` here? Although if it happens on every keystroke that would kinda spam our logs, so perhaps it should happen just once per session.

**Review by mcdurdin — CHANGES_REQUESTED** [review]

**Review by mcdurdin — APPROVED** [review]
