### PR TITLE
fix(common): Retry curl downloads up to 5 times

### LINKED ISSUE #10670: chore(android): ci needs robustness on package downloads
```
08:27:14   Downloading sil_euro_latin.kmp from downloads.keyman.com
08:27:24   
08:27:24   [android/KMAPro] Downloading /var/lib/TeamCity/work/30ffb35c1b6c4089/keyman/android/KMAPro/kMAPro/src/main/assets/sil_euro_latin.kmp failed with error 3
```

https://build.palaso.org/buildConfiguration/KeymanAndroid_TestPullRequests/442083?buildTab=log&linesState=192&logView=flowAware&focusLine=621

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #10670 

This updates the curl downloads to try up to 5 times (with 5s delay in between).
Reference
https://curl.se/docs/manpage.html#--retry

Also updated to use long option names. And since the curl still uses `--silent`, the retry statuses aren't output.

@keymanapp-test-bot skip

### CODE REVIEW

File: resources/build/build-download-resources.sh [hunk 1]
```diff
@@ -29,10 +30,12 @@ function downloadKeyboardPackage() {
...
   local URL_DOWNLOAD=https://downloads.keyman.com
   local URL_API_KEYBOARD_VERSION=${URL_DOWNLOAD}/api/keyboard/
+  local RETRY=5       # Curl retries this number of times before giving up
+  local RETRY_DELAY=5 # Make curl sleep this amount of time before each retry when a transfer has failed
 
-  echo "Downloading ${ID}.kmp from downloads.keyman.com"
-  local URL_DOWNLOAD_FILE=`curl -s "$URL_API_KEYBOARD_VERSION/${ID}" | "$JQ" -r .kmp`
-  curl -f -s "$URL_DOWNLOAD_FILE" -o "$KEYBOARDS_TARGET" || {
+  echo "Downloading ${ID}.kmp from downloads.keyman.com up to ${RETRY} attempts"
+  local URL_DOWNLOAD_FILE=`curl --silent "$URL_API_KEYBOARD_VERSION/${ID}" | "$JQ" -r .kmp`
```
Comment (mcdurdin) [inline resources/build/build-download-resources.sh:37]: This one doesn't have a retry?

**Review by mcdurdin — APPROVED** [review]

File: resources/build/build-download-resources.sh (hunk 1 above)
Comment (darcywong00) [reply resources/build/build-download-resources.sh:37]: k, I can add it there too
