### PR TITLE
fix(windows): modifer event is always serialized

### LINKED ISSUE #7716: bug(windows): 'ALT' Key 'stuck' after changing keyboards with serialized input enabled
### Describe the bug

When switching between using the `IPA SIL keyboard` and the `Dadyia keyboard` with `paratext` and `MS Excel` the `ALT` key can become "stuck" always on. 

  

### Reproduce the bug

TODO: I have to look up the key sequence for the Dadyia keyboard

- Have MS Excel open with Keyman running. 
- Select the IPA SIL keyboard type in some letters
- Open Paratext and select the `Dadyia Odd Vowels` keyboard
- Type in TODO add key sequence
- Switch to IPA SIL type 
- Switch back to `Dadyia` and observe that trying to type any in any key causes the application menus to open
- Open the keyman OSK and observe the 'ALT' key is purple  = depressed 

### Expected behavior

The "ALT" key should not stay on "depressed"

### Related issues

Previous issue reported #7337

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.270

### Operating system

Windows 10

### Device

_No response_

### Target application

Paratext, MS Office

### Browser

_No response_

### Keyboard name

IPA SIL, Dadyia odd vowels

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rc-swag**
Fixes #7716 

PR #7449 added a `modifier event` to make ensure modifier events
were sent to the serializer even if the keystroke was determined
not to need serializing. However, a logic error was made
trying to use the existing 'Flag' however this was not set in the
!UseCachedHotkeyModifierState case. This change adds a helper function
to simply check if the key is a modifier key and send it to the
event serializer in that case. Separating from the other logic which
is more concerned with handling hotkeys.

PR #7779  was used in this investigation. The extra logging enabled the observation that modifier event was not being sent when not using cached hotkeys.  It also showed that for some users when cycling through the open applications using `ALT` + `Tab`  the initial pressing of  `ALT` is seen when a Keyman Keyboard is active. However, the release of the `ALT` is seen when a Keyman Keyboard is not active.  This was actually what was predicted back in the original #7449 fix but we were not able to confirm. So the extra logging has helped verify this. 
`ALT` down keyman keyboard is active so keyevent is sent through
alt_down

`ALT` key up keyman keyboard is not active so the keyevent is not sent through, just the modify event. 
ALT_UP

# User Testing

This PR changes code around modifier keys. Therefore the tests need to cover interactions around these keys being pressed.

**GROUP_WIN10**  - Run the tests in a Windows 10 OS
**GROUP_WIN11** - Run the tests in Windows 11 OS

**TEST_ALTGR_IN_RULES** 
This is to test the key rules which contain <kbd>AltGr</kbd> or <kbd>Shift</kbd> + <kbd>AltGr</kbd> still work correctly.

* Load a keyboard `khmer_angkor` 
* Open LibreOffice or Notepad 
* Type a <kbd>AltGr</kbd> + <kbd>o</kbd> 
* Observe output of  ឱ​

* Type a <kbd>Shift</kbd> + <kbd>AltGr</kbd> + <kbd>o</kbd> 
* Observe output of ᧨

**TEST_HOTKEYS**
This is to test switching between non-keyman and keyman keyboards using hotkeys. To make sure this PR has not broken Hotkeys that use modifiers 
* Install two different keyman keyboards in addition to the default for the Windows installation.
* Use the Keyman Configuration to assign hotkeys to the default Keyboard as well as the two Keyman Keyboards that use modifiers for the hotkey for example <kbd>Ctrl</kbd> + <kbd>1</kbd>  or <kbd>Alt</kbd> + <kbd>K</kbd>
* Open Notepad 
* Use the hotkeys to switch between keyboards
* Verify that switching between the keyboards is working

**TEST_HOTKEYS_SWITCH_APPS** 
This extends the previous test to test switching between non-keyman and keyman keyboards using hotkeys and also using <kbd>Alt</kbd> + <kbd>Tab</kbd> to switch applications.
* Install two different keyman keyboards in addition to the default for the Windows installation.
* Use the Keyman Configuration to assign hotkeys to the default Keyboard as well as the two Keyman Keyboards
* Open two text input applications for example Libre Office and Notepad.
* Turn on the OSK keyboard
* Open Libre Office and select the default Keyboard with the Hotkeys type some text.
* Use <kbd>Alt</kbd> + <kbd>Tab</kbd> to switch to NotePad
* Use the Hotkeys to switch to a Keyman Keyboard and observe you can use that keyboard.
* Observe that on the <kbd>Alt</kbd> is not pressed down "stuck" on.
* Use the HotKeys to switch to the second Keyman keyboard
* Use <kbd>Alt</kbd> + <kbd>Tab</kbd> to switch to LibreOffice
* Type and observe the keyboard works correctly 
* Observe that the <kbd>Alt</kbd>does not get stuck
* Try a combination of switching between keyboards and applications. Pressing different modifier keys etc.
* We want to make use the ALT Key or any other modifier key does not stay down - become stuck.

**TEST_WIN_EMOJI_INPUT** 

* Start Keyman
* Select a non-keyman keyboard
* Open Notepad 
* Type some text on the physical keyboard. 
* Press the <kbd>&#x229E; Win</kbd> + <kbd>.</kbd> to bring up the emoji and gif window.
* In the search box type some characters.
* Does it allow input into the emoji panels text field? Verify that input still works and is not completely blocked.

### CODE REVIEW

**Comment by mcdurdin** [comment]
Build failure:

```
[16:21:14][Step 1/3] (ClCompile target) -> 
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(232,3): error C2059: syntax error: 'if' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(232,39): error C2143: syntax error: missing ';' before '{' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(232,39): error C2447: '{': missing function header (old-style formal list?) [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(237,3): error C2059: syntax error: 'else' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(237,83): error C2143: syntax error: missing ';' before '{' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(237,83): error C2447: '{': missing function header (old-style formal list?) [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(241,3): error C2059: syntax error: 'if' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(241,59): error C2143: syntax error: missing ';' before '{' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(241,59): error C2447: '{': missing function header (old-style formal list?) [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(251,3): error C2059: syntax error: 'if' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(255,32): error C2143: syntax error: missing ';' before '{' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(255,32): error C2447: '{': missing function header (old-style formal list?) [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(263,3): error C2059: syntax error: 'if' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(263,30): error C2143: syntax error: missing ';' before '{' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(263,30): error C2447: '{': missing function header (old-style formal list?) [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(270,3): error C2059: syntax error: 'if' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(270,34): error C2143: syntax error: missing ';' before '{' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(270,34): error C2447: '{': missing function header (old-style formal list?) [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(289,3): error C2059: syntax error: 'return' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(290,1): error C2059: syntax error: '}' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(290,1): error C2143: syntax error: missing ';' before '}' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(292,62): error C2143: syntax error: missing ';' before '{' [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3]   C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\k32_lowlevelkeyboardhook.cpp(292,62): error C2447: '{': missing function header (old-style formal list?) [C:\BuildAgent\work\7ac43416c45637e9\keyman\windows\src\engine\keyman32\keyman32.vcxproj]
[16:21:14][Step 1/3] 
[16:21:14][Step 1/3]     0 Warning(s)
[16:21:14][Step 1/3]     23 Error(s)
```

File: windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp [hunk 1]
```diff
@@ -201,12 +217,14 @@ LRESULT _kmnLowLevelKeyboardProc(
...
+  }
+
+  // #7337 Post the modifier state ensuring the serialized queue is in sync
+  // Note that the modifier key may be posted again with WM_KEYMAN_KEY_EVENT,
+  // later in this function. This is intentional, as the WM_KEYMAN_MODIFIER_EVENT
+  // message only updates our internal modifier state, and does not do
+  // any additional processing or other serialization of the input queue.
+  if (isModifierKey(hs->vkCode) && flag_ShouldSerializeInput) {
       PostMessage(ISerialKeyEventServer::GetServer()->GetWindow(), WM_KEYMAN_MODIFIER_EVENT, hs->vkCode, LLKHFFlagstoWMKeymanKeyEventFlags(hs));
     }
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/k32_lowlevelkeyboardhook.cpp:229]:
```suggestion
```

**Review by mcdurdin — APPROVED** [review]
Makes sense, good work. I like it when we can see and correct a logic error like this one! 

Changes LGTM once build error is corrected.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_WIN11: - Run the tests in Windows 11 OS

* **TEST_ALTGR_IN_RULES (PASSED):** Tested with the attached PR build (Keyman 16.0.126-beta-test-7935) in Windows 11 OS (VM) and here is my observation: Verified that it is showing the expected output. 

   


* **TEST_HOTKEYS (PASSED):** Verified that the hotkeys are working as expected, while switching between the keyboards in Notepad.

   

* **TEST_HOTKEYS_SWITCH_APPS (PASSED):** Verified that the Hotkeys Switching between non-keyman and keyman keyboards is working as expected. Using Alt+tab to switch application is also working. 

   


* **TEST_WIN_EMOJI_INPUT (PASSED):** Verified that the I am able to type in the text field and it is showing the search results correctly. Seems to be working fine.

**Comment by bharanidharanj** [comment]
### GROUP_WIN10: - Run the tests in a Windows 10 OS

* **TEST_ALTGR_IN_RULES (PASSED):** Tested with the attached PR build (Keyman 16.0.126-beta-test-7935) in Windows 10 OS (VM) and here is my observation: Verified that it is showing the expected output. 




* **TEST_HOTKEYS (PASSED):** Verified that the hotkeys are working as expected, while switching between the keyboards in Notepad.

   


* **TEST_HOTKEYS_SWITCH_APPS (PASSED):** Verified that the Hotkeys Switching between non-keyman and keyman keyboards is working as expected. Using Alt+tab to switch application is also working. 

   


* **TEST_WIN_EMOJI_INPUT (PASSED):** Verified that the I am able to type in the text field and it is showing the search results correctly. Seems to be working fine.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.127-beta](https://keyman.com/downloads/releases/beta/16.0.127)
