### PR TITLE
fix(windows): Windows touch keyboard would cancel on each keystroke

### LINKED ISSUE #2450: [Windows] Conflict with serialization and touch keyboard
**Describe the bug**

If Keyman is running (even with no Keyman keyboard active), the touch keyboard in Windows 10 disappears after each keystroke.

This relates to the [serialization guarantee](https://blog.keyman.com/2018/10/the-keyman-keyboard-input-pipeline/) (warning: technical blog post) that Keyman provides. From a technical perspective, what happens is that Keyman intercepts each keystroke and reissues it to ensure that key events arrive in a specific order when additional key events from Keyman are interleaved into the key event queue. But when Keyman reissues the key event, the touch keyboard thinks it is coming from hardware and closes!

There are two workarounds for now.

### Workaround 1: Exit Keyman when using the touch layout

This works but is obviously awkward if you need to use Keyman!

### Workaround 2: Disable the serialization guarantee

This may mean that some key events arrive out of order when using Keyman, particularly if you type fast. (It is no worse than with earlier versions of Keyman). See the blog post linked above for details. However, I have tested this and it does avoid the conflict with the touch keyboard.

1. Start Registry Editor (regedit.exe)
2. Navigate to `HKEY_CURRENT_USER\Software\Keyman\Keyman Engine`
3. Select **Edit/New/Key** and name the key `Debug`.
4. Select the new `Debug` key, and select **Edit/New/DWORD value** and name the value `Flag_ShouldSerializeInput`. It will be created with the default value `0`.
5. Exit and restart Keyman (you may need to restart Windows).

---

**Keyman Desktop:**
 - OS: Windows 10 1903
 - Keyman version: 11.0+
 - Target Application: Touch Keyboard

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #2450.

When Keyman serialized input, it would cause the touch keyboard to cancel because the touch keyboard thought the received event meant the user was touching the physical keyboard. This resolves that problem, using a watch timer to check the visibility of the touch input panel.

### CODE REVIEW

File: windows/src/engine/keyman/UfrmKeyman7Main.pas [hunk 1]
```diff
@@ -225,6 +228,9 @@   TfrmKeyman7Main = class(TForm)
     FHotkeyWindow: HWND;
     FHotkeys: TIntegerList;
 
+    FInputPane: TFrameworkInputPane;
```
Comment (darcywong00) [inline windows/src/engine/keyman/UfrmKeyman7Main.pas]: Any thoughts on mkaing

Comment (mcdurdin) [reply windows/src/engine/keyman/UfrmKeyman7Main.pas]: We could do, but because the update logic is in `TfrmKeyman7Main`, I think the variable probably belongs there as well :O)
