### PR TITLE
fix(android): Control when system keyboard Keyboard Picker clears activity stack

### LINKED ISSUE #12991: bug(android): Keyman abruptly closes after choosing a keyboard from the keyboard picker menu
Re-opening #9456 for 18.0 since that fix had to be reverted for #12986

### Describe the bug

I noticed that after choosing any keyboard from the keyboard picker menu, keyman app abruptly closes. This happens after selecting keyman as the system wide keyboard. 

### Reproduce the bug

1. Install Keyman 17.0.158-alpha build.
2. Open Keyman In-App.
3. Set Keyman as the system-wide keyboard and default keyboard. 
4. Click 'Install Keyboard or Dictionary' option from the Settings menu. 
5. Click 'Install from keyman.com' option. 
6. Click the Search bar to enter a keyboard name. 

We may notice that the default keyman keyboard flashes on the page. 

7. Click once again on the Search bar. 
8. Long press the 'globe key' from the keyman keyboard. 
9. Click 'Gboard' or English EuroLatin(SIL) keyboard from the Keyboards picker menu. 

Here, I noticed that the keyman app suddenly closes from the screen. Seems to be an issue. 

I have attached the video file for reference. 

..Keyman App abruptly closes

https://github.com/keymanapp/keyman/assets/19683143/6b5d8fe8-9cab-4737-8efb-4ece367d8225

### Expected behavior

After clicking any keyboard it should open the corresponding keyboard on the screen. 

### Related issues

_No response_

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.158-alpha

### Operating system

Android 5.0, 9.0, 12.0

### Device

Redmi Note 8 Pro, API 31 emulator

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #12991 

For as long as Keyman for Android 2.8, the system keyboard KeyboardPickerActivity has been setting the `Intent.FLAG_ACTIVITY_CLEAR_TASK` flag which becomes the root activity and clears previous tasks (Keyman app).

When using Keyman as a system keyboard within the Keyman app, we don't want this to occur.

TODO:
- [x] Update API docs #13373

## Change
Add call to  disable/enable when the system keyboard Keyboard Picker clears previous tasks.

## User Testing
**Setup** - Install PR build of Keyman for Android
From "Get Started", set Keyman as the default system keyboard.

* **TEST_INAPP** - Verifies keyboard picker within the Keyman app
1. Launch Keyman for Android
2. With the inapp keyboard, hold the globe key to launch the Keyboard Picker
3. Dismiss the keyboard picker
4. Verify the Keyman app is not dismissed
5. From Keyman, access Keyman settings --> Install Keyboard or Dictionary --> Install from keyman.com
6. From the keyboard search page, select the search box and select Keyman keyboard if need be
7. With the Keyman OSK displayed, hold the globe key to launch the Keyboard Picker
8. Dismiss the keyboard picker
9. Verify the Keyman app is not dismissed

* **TEST_SYSTEM** - Verifies keyboard picker outside the Keyman app
1. Close Keyman if it's running
2. Launch Chrome browser and select the text area and select Keyman keyboard if need be
3. With the Keyman system keyboard OSK displayed, hold the globe key to launch the Keyboard Picker
4. Dismiss the keyboard picker
5. Verify Keyman is not launched in the background

7.

### CODE REVIEW

**Review by sgschantz — COMMENTED** [review]
I don't see any issues without how this code will execute, but I had trouble understanding the naming, and I had to re-read it carefully to not be confused.

Part of the problem is that I didn't know this: "A task is a collection of activities that users interact with when trying to do something in your app." This is confusing to me because I don't think of activities as smaller than tasks. I think of a task as something that is discrete and an activity as something broader. You can't do much about the Android naming, but it is possible to clarify this relationship with your code and naming.

Beyond that, I think I would still be confused about what is being enabled and disabled. You are not clearing immediately but setting the flag to clear later, predicated on some other event. But that event is not mentioned in the name of the flag. I would rather see it included in the name of the flag (even a long name) than being required to read other code or comments to understand the purpose of the flag.

One other confusing thing is that the actual flag is named `canClearActivityTask` when it seems the flag is forcing the clear to happen. By prefixing it with  'can' I expect that the underlying action is available but optional. The difference in the flag name from the names of the functions that set the flag cause me to doubt that I understand the code that is applying the flag.

**Comment by darcywong00** [comment]
Yeah, I find the naming quite clunky.
Basically we want to toggle [`Intent.INTENT_FLAG_ACTION_CLEAR`](https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_CLEAR_TASK)
> this flag will cause any existing task that would be associated with the activity to be cleared before the activity is started. That is, the activity becomes the new root of an otherwise empty task, and any old activities are finished. 

Maybe something like this?
* clearExistingActivity()
* dontClearExistingActivity()

**Comment by dinakaranr** [comment]
# Test Results
I tested this issue with the attached Keyman"18.0.199-beta-test-13313" build(24/02/2025) on Android 14(Physical device) and Android 12(Emulator). Here I am sharing my observation.

* **TEST_INAPP (Paased):** 
1. Install the keyman-18.0.199.apk file.
2. Launch the Keyman app. 
3. The "Get Started" menu appears, enable Keyman as a system keyboard and set it as the default keyboard.
4. Open the "Keyboard Picker" by pressing the "globe" key.
5. Close the keyboard picker
6. Verified that the Keyman app is not closed.
7. Navigate to the "Search the keyboard" by pressing Keyman settings --> Install Keyboard or Dictionary --> Install from keyman.com.
8. Click in the Search box.  (Search for a keyboard and install a keyboard if needed)
9. Verified that the OSK displayed.
10. Open the "Keyboard Picker" by pressing the "globe" key.
11. Close the keyboard picker
12. Verified that the Keyman app is not closed.

* **TEST_SYSTEM (Passed):** 
1. Install the keyman-18.0.199.apk file.
2. Launch the Keyman app. 
3. The "Get Started" menu appears, enable Keyman as a system keyboard and set it as the default keyboard.
4. Close the Keyman app.
5. Launch Chrome browser.
6. Navigate to the Google search box(text area)
7. Verified that the Keyman keyboard appeared.
8. Open the "Keyboard Picker" by pressing the "globe" key.
9. Close the keyboard picker
10. Verified that the Keyman did not launch in the background.

**Comment by sgschantz** [comment]
That is a lot better, but can it also specify when the existing activity is cleared? How do you best describe what actually triggers the clearing of the activity (provided this flag has been set)?

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java [hunk 1]
```diff
@@ -2299,7 +2313,10 @@ public static void showKeyboardPicker(Context context, KeyboardType kbType) {
 
     if (kbType == KeyboardType.KEYBOARD_TYPE_SYSTEM) {
       i.addFlags(Intent.FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS);
-      i.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK);
+      if (KeyboardPickerActivity.getClearActivityTask()) {
+        // Keyboard Picker Activity becomes root activity and clears Keyman app
+        i.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK);
```
Comment (darcywong00) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2318]: > That is a lot better, but can it also specify when the existing activity is cleared? How do you best describe what actually triggers the clearing of the activity (provided this flag has been set)?

This is the scenario:
When the Keyman system keyboard (as opposed to in-app keyboard) is launching the Keyboard Picker, 
we generally want to dismiss the Keyman app if it's running.

The exception is when using the Keyman system keyboard within the Keyman app (e.g. doing a keyboard search).

Comment (sgschantz) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2318]: Ok, just looked at this again. I think what would help would be to associate your functions directly with showing the keyboard picker. The code reads like it is generic to clearing activity task (closing Keyman), but when you call the related functions, you include a comment that shows that this is only relevant to the keyboard picker.

So instead of `clearExistingActivity`, you could give the context in the name and say `clearExistingActivityOnShowKeyboardPicker`. That is, assuming you only ever plan to read and apply the flag when showing the keyboard picker. (That makes the comments pretty much redundant, but we'd always rather just read the function if we can instead of needing a comment to help us interpret the code.)

If the 'ExistingActivity' is always going to be Keyman -- it is the thing that is getting cleared or closed, then could it actually be `closeKeymanOnShowKeyboardPicker`? Or is that going too far?

Sorry to belabor this, but it seems like we are doing something concrete and discrete, but the terminology is referencing things that are generic and of wider scope. So my lack of familiarity with the Android architecture made it hard to comprehend. I think the code could be in more concrete domain/Keyman terms where the reference and mapping to the Android API only happens when you actually set `Intent.FLAG_ACTIVITY_CLEAR_TASK`.

I still have a problem with the variable `canClearActivityTask` which seems to really mean `forceClearActivityTask` or `forceCloseKeyman` (if closing Keyman is the only possible ActivityTask that we will be clearing).

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2322]: ok, latest round of renames

I called the flag `canCloseParentAppOnShowKeyboardPicker` because there may be other app developers using Keyman Engine for Android (besides Keyman).

And then went with
* dontCloseParentAppOnShowKeyboardPicker()
* closeParentAppOnShowKeyboardPicker()

Comment (sgschantz) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2322]: That makes sense -- I wasn't giving any thought to the API boundary.

**Review by sgschantz — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.206-beta](https://keyman.com/downloads/releases/beta/18.0.206)
