### PR TITLE
fix(windows): add back support for disabling keyboards

### LINKED ISSUE #3560: fix(windows): Add back support for disabling keyboards
As part of the language install rework, disabling Keyman keyboards was made non functional. 

We need to add back support for disabling keyboards by using `InstallLayoutOrTip`, and keeping a list of 'disabled' profiles in cu registry for future enabling. This does involve the whole merry-go-round for transient langids though.

* Fixup Load/Unload of keyboards in Keyman Configuration UI

* While this would be helped by changing the mode of Keyman Configuration to instant-change as documented elsewhere, that should be completed as a separate task.

Relates to #3512.

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #3560. This reworks the functionality for disabling keyboards to work with the new TIP registration pattern. Much of the code is the same as in Keyman 13, but there are some significant differences, so it all needs to be reviewed.

### CODE REVIEW

File: windows/src/global/delphi/general/RegKeyboards.pas [hunk 1]
```diff
@@ -307,6 +312,7 @@ procedure TRegKeyboard.Load(FLoadKeyboard: Boolean);
 var
   ki: TKeyboardInfo;
 begin
+  FCanEnable := True;
```
Comment (mcdurdin) [inline windows/src/global/delphi/general/RegKeyboards.pas:315]: This flag is not currently used but will be helpful in the future.

**Review by darcywong00 — APPROVED** [review]
lgtm
