### PR TITLE
fix(android): Add wrapper for logging errors & exceptions

### LINKED ISSUE #3111: [Android] Send Log.e to Sentry
From https://github.com/keymanapp/keyman/pull/3091#pullrequestreview-408095222
> Does Log.e() fire a Sentry event? ... it should 😉 Possibly even Log.w() should but less sure on that one...

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #3111
This PR adds a wrapper `KMLog()` so `Log.e()` events also get sent to Sentry

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java [hunk 1]
```diff
@@ -135,10 +137,10 @@ public void initKMKeyboard(final Context context) {
 
     setWebChromeClient(new WebChromeClient() {
       public boolean onConsoleMessage(ConsoleMessage cm) {
+        String msg = String.format("KMW JS Log: Line %d, %s:%s", cm.lineNumber(), cm.sourceId(), cm.message());
         if (KMManager.isDebugMode()) {
-          Log.d("KMEA", "Keyman JS Log: Line " + cm.lineNumber() + ", " + cm.sourceId() + ":" + cm.message());
           if (cm.messageLevel() == ConsoleMessage.MessageLevel.ERROR) {
-            Log.e("KMEA", "Keyman JS Log: ERROR");
+            Log.d(TAG, msg);
```
Comment (darcywong00) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java:143]: I lowered this level to `Log.d` because the Log.e gets sent to Sentry in `sendKMWError()` (line 153)

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LexicalModel.java [hunk 2]
```diff
@@ -4,18 +4,20 @@
...
 import com.tavultesoft.kmea.util.FileUtils;
+import com.tavultesoft.kmea.util.KMLog;
 
 import org.json.JSONArray;
 import org.json.JSONException;
 import org.json.JSONObject;
 
 import java.io.Serializable;
 
+import io.sentry.core.Sentry;
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LexicalModel.java:19]: Do we need this?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/Connection.java [hunk 3]
```diff
@@ -30,7 +31,7 @@ public static InputStream getInputStream() {
         return urlConnection.getInputStream();
       }
     } catch (IOException e) {
-      Log.e("Connection", "getInputStream failed: " + e);
+      KMLog.LogException(TAG, "getInputStream failed: ", e);
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/Connection.java:34]: How is this compiling? Where is it getting `KMLog` from?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/DownloadIntentService.java [hunk 4]
```diff
@@ -33,6 +33,7 @@ protected void onHandleIntent(Intent intent) {
       }
     } catch (Exception e) {
       receiver.send(FileUtils.DOWNLOAD_ERROR, Bundle.EMPTY);
+      KMLog.LogException(TAG, "", e);
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/DownloadIntentService.java:36]: Where is this finding `KMLog`?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMLog.java [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+
+  /**
+   * Utility to log exceptions and send to Sentry
+   * @param tag String of the caller
+   * @param msg String of the exception message
+   * @param e Throwable exception
+   */
+  public static void LogException(String tag, String msg, Throwable e) {
+    if (msg != null && !msg.isEmpty()) {
+      Log.e(tag, msg + e);
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMLog.java:36]: Would this be better as, or similar:
```suggestion
      Log.e(tag, msg + "\n" + e.getMessage());
```

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMLog.java [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+    } else if (e != null) {
+      Log.e(tag, e.getMessage(), e);
+    }
+
+    if (Sentry.isEnabled()) {
+      Sentry.captureException(e);
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMLog.java:42]: Is there any way we can pass the message through here too?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/Connection.java (hunk 3 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/Connection.java:34]: `Connection` and `DownloadIntentService` are in the same `com.tavultesoft.kmea.util` package as `KMLog`.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LexicalModel.java (hunk 2 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/data/LexicalModel.java]: Good catch. removed

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMLog.java (hunk 6 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/KMLog.java:45]: I don't see a way with `captureException`, but I was able to add the msg to a breadcrumb
