### PR TITLE
fix(web/engine): findNearestKey erroneously returned key child

### LINKED ISSUE #4065: bug(web): some clicks on touch keyboard cause an error
**Describe the bug**

When touching the keyboard rapidly, I will sometimes see an error `OSK key with ID '', keyID 'undefined' missing needed specification`. This error seems to arise when the `clickKey` function is passed a `span.kmw-key-text` element instead of a `div.kmw-key` element. I don't know how the `span.kmw-key-text` element is passed in but it relates to a function `release` which calls it with the `this.keyPending` property.

**To Reproduce**

1. On Android .194, load any keyboard and type rapidly
2. After some time, see error

**Screenshots**

image

---

**KeymanWeb:**
 - OS: Android 10
 - Browser: Embedded in Keyman for Android, in-app keyboard
 - KeymanWeb Version: 14.0.194-alpha

---

**Keyboard**
 - Keyboard name: Eurolatin (or any keyboard) 
 - Keyboard version: 
 - Language name: 

**Additional context**

Noticed when testing Armenian keyboard (which has other issues) from https://github.com/keymanapp/keyboards/pull/1402

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #4065.

### CODE REVIEW

File: web/source/osk/visualKeyboard.ts [hunk 1]
```diff
@@ -1313,19 +1313,19 @@ namespace com.keyman.osk {
...
       var k, k0=0, dx, dxMax=24, dxMin=100000, x1, x2;
       for(k = 0; k < t.childNodes.length; k++) {
-        let childNode = t.childNodes[k] as HTMLElement; // gets the .kmw-key-square containing a key
-        if(childNode.firstChild) {
-          childNode = childNode.firstChild as HTMLElement; // gets the actual key element.
-        }
+        let keySquare = t.childNodes[k] as HTMLElement; // gets the .kmw-key-square containing a key
+        // Find the actual key element.
+        let childNode = keySquare.firstChild ? keySquare.firstChild as HTMLElement: keySquare;
+
```
Comment (jahorton) [inline web/source/osk/visualKeyboard.ts:1319]: Compare against #3858.

At the time, I failed to realize the change's effect on the line below...

File: web/source/osk/visualKeyboard.ts [hunk 2]
```diff
@@ -1313,19 +1313,19 @@ namespace com.keyman.osk {
...
           continue;
         }
-        x1 = childNode.offsetLeft;
-        x2 = x1 + childNode.offsetWidth;
+        x1 = keySquare.offsetLeft;
+        x2 = x1 + keySquare.offsetWidth;
         if(x >= x1 && x <= x2) {
           // Within the key square
-          return <KeyElement> childNode.firstChild;
+          return <KeyElement> childNode;
```
Comment (jahorton) [inline web/source/osk/visualKeyboard.ts:1328]: #3858's change caused this line to refer to the `<span>` for the key's text, which is the first child of the element we want for the key.

**Review by mcdurdin — APPROVED** [review]
LGTM
