### PR TITLE
fix(web): row height layout calcs now consider layer-group padding

### LINKED ISSUE #6699: bug: [iOS] Bottom row cropped
**Describe the bug**
in iOS, bottom row keys are cropped

this was seen in Keyman version 15 beta version

Same issue can be seen in the screenshot under below issue (Keyman 15.0.238 beta)
https://github.com/keymanapp/keyman/issues/6604

It can also be seen in the other images posted in this pull request (Keyman 15.0.252-beta)
https://github.com/keymanapp/keyman/pull/6658 

no evidence of this issue is seen in screenshots under (Keyman 15.0.103 alpha)
https://github.com/keymanapp/keyman/issues/5646

This issue has started between 15.0.103 and 15.0.238

**To Reproduce**
launch Keyman keyboard in iOS

**Expected behavior**
No cropping

**Screenshots**
IMG_4018
IMG_4019

**Keyman for iPhone/iPad/Android:**
 - Device: iPhone 13 pro max
 - OS: iOS 15.5
 - Keyman version 15.0.255-beta
 - Target application: Notes, Keyman

**Keyboard**
 - Keyboard name:  Euro SIL (repeatable with any keyboard)
 - Keyboard version: latest
 - Language name: English

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #6699.

It looks like I may have missed something small and subtle related to row-height layout calculations in the big OSK refactoring batch last year.  For touch OSKs, our CSS applies light top and bottom padding... but this wasn't being considered in layout calculations.  This resulted in it being applied twice-over at the top, with very-slightly oversized keys to boot - the net effect of which caused the bottom row's keys to appear lightly cropped.

### Testing environments

- GROUP_ANDROID:  test on an Android device.  Emulated should be fine.
- GROUP_IOS:  test on an iOS device.  Emulated should be fine.
    - It may be best to use an un-notched device - something like the iPhone SE.  One aspect of the test may be trickier to confirm otherwise.

### Tests:

- TEST_OSK_PADDING:  load the keyboard and verify that the bottom row's keys are uncropped.
    - There should also be a pixel or two of space underneath them - only a small amount.
        - Note that this space may be used for a drop-shadow effect.
    - If there is an uneven gap between the last key's bottom and the bottom of the keyboard, FAIL this test.
        - Any such gap should evenly match a corresponding gap above the top row.
        - **On notched iOS devices**, note that the "bottom of the keyboard" is where there is a slight transition between two different gray colors:

            image

            This screenshot PASSES; note how the keyboard's background gray is slightly darker than the gray for the iOS's "safe area" beneath it.  It _is_ subtle, but detectable - you may need to bring your eyes close to the screen to discern the difference.  (Also, note how the bottom of the keys is just above the part of the device that would otherwise crop them.)

- TEST_NO_BLACK_BAR:  verify that there is no "black border bar" at the top of the keyboard.  (We don't want #6604 to re-emerge.)

### CODE REVIEW

**Review by ermshiperete — APPROVED** [review]

File: web/source/osk/visualKeyboard.ts [hunk 1]
```diff
@@ -1275,10 +1284,16 @@ namespace com.keyman.osk {
...
       if(this.currentLayer) {
-        this.currentLayer.refreshLayout(this, paddedHeight, this._computedHeight);
+        this.currentLayer.refreshLayout(this, this._computedHeight - this.getVerticalLayerGroupPadding());
       }
     }
 
+    private getVerticalLayerGroupPadding(): number {
+      // For touch-based OSK layouts, kmwosk.css may include top & bottom padding on the layer-group element.
+      const computedGroupStyle = getComputedStyle(this.layerGroup.element);
+      return parseInt(computedGroupStyle.paddingTop) + parseInt(computedGroupStyle.paddingBottom);
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:1294]:
```suggestion
      return parseInt(computedGroupStyle.paddingTop, 10) + parseInt(computedGroupStyle.paddingBottom, 10);
```

`parseInt` without radix prior to 2021 [was bad](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#octal_interpretations_with_no_radix). Even after 2021 it's still [not good](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#description)

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID: test on an Android device.  Emulated should be fine.

* **TEST_OSK_PADDING (PASSED):** Tested Keyman 15.0.260 beta build in Android 10 emulator (API 29) and the bottom keys are not cropped.



* **TEST_NO_BLACK_BAR (PASSED):** Tested Keyman 15.0.260 beta build in Android 10 emulator (API 29) and I noticed that there is no black border at the top of the Keyboard layer.

**Comment by bharanidharanj** [comment]
### GROUP_IOS: test on an iOS device.  Emulated should be fine.

* **TEST_OSK_PADDING (PASSED):** Tested Keyman 15.0.260 beta build in iPhone 13 Pro Simulator and it is working as expected. 

..in Portrait mode



* **TEST_NO_BLACK_BAR (PASSED):** Tested Keyman 15.0.260 beta build in iPhone 13 Pro Simulator and it is working as expected. 

..in iPad Simulator...(Portrait mode)


..Landscape mode
