### PR TITLE
fix(core): reset on frame keys 🙀 

### LINKED ISSUE #10227: feat(windows): Investigate if VKContextReset is needed in for core on kmx processor
In reviewing #10090 it become apparent that the call to reset the context in the windows engine base upon the table VKContextReset was no longer used. This ticket is to investigate if it is still needed if so integrated into the core. Also remove the Array from the Windows engine. 

- [ ] Remove extern const int VKContextReset[256]; from the Windows Engine

- [ ] Store palce const int VKContextReset[256]; in the Core if it is needed

### LINKED ISSUE #10955: bug(core): LDML processor handling "Enter" frame keys etc does not reset/invalidate the context for non-compliant apps
Edit: Update after further investigation.
When a <kbd>Enter</kbd> is pressed with any app non-compliant or compliant, the KMX process will reset(invalidate) the context. What happens on the following keystroke for a compliant app is the context is read again which includes the newline marker and then is set in the core with `km_core_state_context_set_if_needed` api call.

With the LDML processor, the context is not reset.  There is no LF character inserted into the context either, however, that would be incorrect, why because not being context away the `enter` could have moved the cursor to a new text field.

LDML processor after 
<kbd>a</kbd><kbd>Enter</kbd><kbd>c</kbd>
Process_Event_Core: context cache after:  |ac| (len: 2) [ U+0061 U+0063 ]
KMX processor after 
<kbd>a</kbd><kbd>Enter</kbd><kbd>c</kbd>
Process_Event_Core: context cache after:  |c| (len: 1) [ U+0063 ]

KMX Processor Log for non-compliant
<kbd>a</kbd><kbd>Enter</kbd>
```
kmtip: _KeymanProcessKeystroke (d 1c0001   ex=0)
130	TIPProcessKey: Enter VirtualKey=['Enter' 0xd] lParam=1c0001   IsUp=0 Extended=0 Updateable=0 Preserved=0
164	Key pressed: ['Enter' 0xd] Context '|a| (len: 1) [ U+0061 ]'
47 kmtip: KeymanGetContext: Exit: Context does not support manipulation.  Using legacy interaction
287	AITIP::ReadContext: transitory context, so use buffered context [Updateable=0]
108	ProcessEvent: vkey[13] ShiftState[0] isDown[1]
121	Process_Event_Core: context app before:   |a| (len: 1) [ U+0061 ]
122	Process_Event_Core: context app after:    || (len: 0) [ ]
123	Process_Event_Core: context cache before: |a| (len: 1) [ U+0061 ]
124	Process_Event_Core: context cache after:  || (len: 0) [ ]
149	ProcessActionsNonUpdatableParse EMIT_KEYSTROKE
214	TIPProcessKey: Success, res=0
```
<kbd>d</kbd>
```
164	Key pressed: ['B' 0x42] Context '|| (len: 0) [ ]'
47	kmtip: KeymanGetContext: Exit: Context does not support manipulation.  Using legacy interaction
287	AITIP::ReadContext: transitory context, so use buffered context [Updateable=0]
108	ProcessEvent: vkey[66] ShiftState[0] isDown[1]
121	Process_Event_Core: context app before:   || (len: 0) [ ]
122	Process_Event_Core: context app after:    |b| (len: 1) [ U+0062 ]
123	Process_Event_Core: context cache before: || (len: 0) [ ]
124	Process_Event_Core: context cache after:  |b| (len: 1) [ U+0062 ]
214	TIPProcessKey: Success, res=1
```
WordPad Compliant app
<kbd>a</kbd><kbd>Enter</kbd>
```
kmtip: GetLeftOfSelection(63) = U+0061  [1 fetched]
         282	AITIP::ReadContext: full context [Updateable=1] U+0061 
	100	Process_Event_Core: set_if_needed result: 0
	108	ProcessEvent: vkey[13] ShiftState[0] isDown[1]
	121	Process_Event_Core: context app before:   |a| (len: 1) [ U+0061 ]
	122	Process_Event_Core: context app after:    || (len: 0) [ ]
	123	Process_Event_Core: context cache before: |a| (len: 1) [ U+0061 ]
	124	Process_Event_Core: context cache after:  || (len: 0) [ ]
```

### PR DESCRIPTION
**Pull request by srl295**
- Move context reset out of kmx and into the core
- use the context reset table
- reinstate tests in ldml that test for reset
- improve ldml test suite to support multiple steps in the 'embedded' test format

Fixes #10955
Fixes #10227

# User Testing 

Using Windows 10 or Windows 11.
Install the keyman build from this PR.

Use the Text Editor linked in this PR under test artifacts. or if on Windows 10 you can use Notepad.

## SUITE_KMX_PROCESSOR_NON_COMPLIANT:
For these tests make sure the application used on the operating system is a **non-compliant**. A app that is not able to give the context to Keyman.

#### GROUP_LINUX:  Chrome Brower (https://www.editpad.org/)

Install SIL Euro Latin

### TEST_CONTROL_1
1. Press <kbd>`</kbd> 
2. press <kbd>e</kbd>
Expected result:
è

### TEST_FRAME_KEY_RESET_MARKERS
This tests the markers are lost
1. Press <kbd>`</kbd> 
2. Press <kbd>-></kbd>    right arrow
3. Press <kbd>e</kbd>
Expected result: 
`e

### TEST_FRAME_KEY_RESET_NOMARKERS

1. Press <kbd>1</kbd> <kbd>/</kbd> <kbd>/</kbd>
2. Press <kbd>-></kbd>    right arrow
3. Press <kbd>2</kbd>
Expected result: 
1//2

### TEST_SCROLLLOCK_KEY_NO_RESET
Do not reset for scroll lock
1. Press <kbd>`</kbd>
2. Press <kbd>scroll lock</kbd> for Windows and Linux. For MacOS Press <kbd>fn</kbd>
3. Press <kbd>e</kbd>
Expected Result: 
è

## SUITE_KMX_PROCESSOR_COMPLIANT:

For these tests make sure the application used on the operating system is **compliant**. That is Keyman can request the context from the application.

#### GROUP_LINUX: gedit

Install SIL Euro Latin

### TEST_CONTROL_1
1. Press <kbd>`</kbd> 
2. press <kbd>e</kbd>
Expected result:
è

### TEST_FRAME_KEY_RESET_MARKERS
This tests the markers are lost
1. Press <kbd>`</kbd> 
2. Press <kbd>-></kbd>    right arrow
3. Press <kbd>e</kbd>
Expected result: 
`e

### TEST_FRAME_KEY_RESET_NOMARKERS

1. Press <kbd>1</kbd> <kbd>/</kbd> <kbd>/</kbd>
2. Press <kbd>-></kbd>    right arrow
3. Press <kbd>2</kbd>
Expected result: 
½

### TEST_SCROLLLOCK_KEY_NO_RESET
Do not reset for scroll lock
1. Press <kbd>`</kbd>
2. Press <kbd>scroll lock</kbd> for Windows and Linux. For MacOS Press <kbd>fn</kbd>
3. Press <kbd>e</kbd>
Expected Result: 
è

## SUITE_LDML_PROCESSOR_NON_COMPLIANT:
LDML keyboard

### GROUP_LINUX:  Chrome Brower

Install [contextreset.zip](https://github.com/keymanapp/keyman/files/14976065/contextreset.zip) ldml keyboard
### TEST_CONTROL_1
1. Press <kbd>^</kbd> 
2. Press <kbd>e</kbd>
Expected result:
ê

This was previously failing 

### TEST_FRAME_KEY_RESET_MARKERS
1. Press <kbd>^</kbd>
2. Press <kbd>-></kbd>    right arrow
3. Press <kbd>e</kbd>
Expected result: 
e

### TEST_FRAME_KEY_RESET_NO_MARKERS
1. Press <kbd>a</kbd>
2. Press <kbd>-></kbd>    right arrow
3. Press <kbd>Shift</kbd> + <kbd>8</kbd> 
Expected result: 
a*

### TEST_FRAME_SCROLL_LOCK_NO_RESET
1. Press <kbd>^</kbd>
2. Press <kbd>scroll lock</kbd> for Windows and Linux. For MacOS Press <kbd>fn</kbd>
3. Press <kbd>e</kbd>
Expected result: 
ê

### TEST_MODIFIER_TAP_NO_RESET
Do not reset for modifier tap
1. Press <kbd>^</kbd>
2. Press  and Release <kbd>ctrl</kbd>
3. Press <kbd>e</kbd>
Expected result:
ê

## SUITE_LDML_PROCESSOR_COMPLIANT:
LDML keyboard

### GROUP_LINUX: gedit

Install
[contextreset.zip](https://github.com/keymanapp/keyman/files/14976065/contextreset.zip) ldml keyboard
### TEST_CONTROL_1
1. Press <kbd>^</kbd> 
2. Press <kbd>e</kbd>
Expected result:
ê

This was previously failing 

### TEST_FRAME_KEY_RESET_MARKERS
1. Press <kbd>^</kbd>
2. Press <kbd>-></kbd>    right arrow
3. Press <kbd>e</kbd>
Expected result: 
e

### TEST_FRAME_KEY_RESET_NO_MARKERS
1. Press <kbd>a</kbd>
2. Press <kbd>-></kbd>    right arrow
3. Press <kbd>Shift</kbd> + <kbd>8</kbd> 
Expected result: 
Star

### TEST_FRAME_SCROLL_LOCK_NO_RESET
1. Press <kbd>^</kbd>
2. Press <kbd>scroll lock</kbd> for Windows and Linux. For MacOS Press <kbd>fn</kbd>
3. Press <kbd>e</kbd>
Expected result: 
ê

### TEST_MODIFIER_TAP_NO_RESET
Do not reset for modifier tap
1. Press <kbd>^</kbd>
2. Press  and Release <kbd>ctrl</kbd>
3. Press <kbd>e</kbd>
Expected result:
ê

### CODE REVIEW

**Review by mcdurdin — CHANGES_REQUESTED** [review]

**Comment by mcdurdin** [comment]
> For #10955

This should be fixing that issue, right? in which case "fixes ..." rather than "for ..." (and don't forget to link in the Development right hand panel in GH)

> @keymanapp-test-bot skip

I think we can usefully have user tests for this to verify that outcome is as we expect on each platform. Need to spec with non-compliant apps, a test for pressing specific frame key and another test for non-frame keys, with a keyboard rule that depends on preceding context. With sil_euro_latin, type <kbd>'</kbd> ... frame key | non frame key ... <kbd>e</kbd>, and for non-frame key it should combine, with frame key it shouldn't. We could use e.g. <kbd>Insert</kbd> as a non-frame key, and e.g. <kbd>Escape</kbd> as a frame key, if using an app such as Notepad where those keys won't have any other effect.

In fact may need to have tests with compliant apps as well, to verify markers are dropped when frame keys are pressed. Needs thinking through a bit but I think this is critical given this is fundamental to how Keyman works.

File: core/src/km_core_state_api.cpp [hunk 1]
```diff
@@ -363,4 +366,28 @@ km_core_cp * km_core_state_context_debug(
...
+km_core_state_should_clear_context(km_core_state *state,
+                     km_core_virtual_key vk,
+                     uint16_t modifier_state,
+                     uint8_t is_key_down,
+                     uint16_t event_flags) {
+  // if emit_keystroke is present, check if a context reset is needed
+  if (km_core_state_has_type(state, KM_CORE_IT_EMIT_KEYSTROKE)) {
+    if (km::core::vkey_to_contextreset[vk]) {
+      return true;
+    } else if (vk == KM_CORE_VKEY_BKSP && km_core_state_has_type(state, KM_CORE_IT_BACK)) {
```
Comment (rc-swag) [inline core/src/km_core_state_api.cpp:388]: I am not sure this condition is the same as the current behaviour is it?  It does not reset the context if it is emitting a backspace and there is context to delete [to the proccessors knowledge]. It only does it if the context is empty. Which I know theoretical is then a no-op.  I think you could use `code_points_to_delete` or check the context as we haven't applied the actions yet at this point. 
Current behaviour is at https://github.com/keymanapp/keyman/blob/7dcbcf35f1e6ea88d7a1a7e70087c860d6c5efe4/core/src/kmx/kmx_processevent.cpp#L278

Comment (mcdurdin) [reply core/src/km_core_state_api.cpp:388]: Does it work out the same because this action only applies if `KM_CORE_IT_EMIT_KEYSTROKE` is true?

Comment (srl295) [reply core/src/km_core_state_api.cpp:388]: No this part is wip.

**Comment by srl295** [comment]
> > For #10955
> 
> 
> 
> This should be fixing that issue, right? in which case "fixes ..." rather than "for ..." (and don't forget to link in the Development right hand panel in GH)
> 

I usually update that once it actually fixes. 

> 
> 
> > @keymanapp-test-bot skip
> 
> 
> 
> I think we can usefully have user tests for this to verify that outcome is as we expect on each platform. Need to spec with non-compliant apps, a test for pressing specific frame key and another test for non-frame keys, with a keyboard rule that depends on preceding context. With sil_euro_latin, type <kbd>'</kbd> ... frame key | non frame key ... <kbd>e</kbd>, and for non-frame key it should combine, with frame key it shouldn't. We could use e.g. <kbd>Insert</kbd> as a non-frame key, and e.g. <kbd>Escape</kbd> as a frame key, if using an app such as Notepad where those keys won't have any other effect.
> 

Good point. I have never done a user test so far. So I'm just used to skip. 

> 
> 
> In fact may need to have tests with compliant apps as well, to verify markers are dropped when frame keys are pressed. Needs thinking through a bit but I think this is critical given this is fundamental to how Keyman works.

Makes sense

File: core/src/km_core_state_api.cpp (hunk 1 above)
Comment (srl295) [reply core/src/km_core_state_api.cpp]: can't use `code_points_to_delete` because that struct has been changed into an action array already by `state->set_actions()`.

**Comment by srl295** [comment]
getting closer.. i had to:
- tweak the `first_action` debug setting in one of the tests, because it was off
- swap the action array around - i assume it may be significant which order the action queue is in? so I tried to keep it compatible.

In the k_000___null_keyboard.kmn test (I'm getting familiar with kmx and its test code!) there's this case:

```
store(&NAME) '000 - null keyboard'
c Description: Tests null keyboard
c keys: [K_A][RALT K_B][SHIFT K_C]
c expected: aC
c expected context: C
c context:

store(&version) '6.0'

begin Unicode > use(Main)

group(Main) using keys
```

kmx does a reset here after the <kbd>RAlt-b</kbd>. But vkey 66 (`K_B`) in the reset table is false.

Should it reset because of the modifiers?

**Comment by srl295** [comment]
reset on modifiers doesn't work well either per other tests.

**Comment by srl295** [comment]
aha.. it needs to be a key *UP* event also

**Comment by srl295** [comment]
OK, only failing kmx test is the k_020 deadkeys one..

```
action: emit keystroke

expected        : U+0077 U+0078 U+0061 U+0061 U+0020 U+006F U+006B  [wxaa ok]

text store      : U+0077 U+0078 U+0079 U+0061 U+0061 U+0063 U+0064  [wxyaacd]

expected context: U+0077 U+0078 U+0061 U+0061 U+0020 U+006F U+006B  [wxaa ok]
```

**Comment by srl295** [comment]
should pass - the check for chars_to_delete seems to be counterproductive

File: core/src/km_core_state_api.cpp (hunk 1 above)
Comment (srl295) [reply core/src/km_core_state_api.cpp]: take a look now

**Comment by srl295** [comment]
@rc-swag @mcdurdin any comments on the user test required? Assuming the code passes that is going to be the last blocking issue

**Comment by rc-swag** [comment]
> What's the best way to specify that in user tests?

I will write some user tests for this today.

**Comment by rc-swag** [comment]
# User Testing 

Using Windows 10 or Windows 11.
Install the keyman build from this PR.

Use the Basic Text editor. or if on Windows 10 you can use Notepad.

# GROUP_ID:  KMX_PROCESSOR

Install SIL Euro Latin

# TEST_CONTROL_1
1. Press <kbd>`</kbd> 
2. press <kbd>e</kbd>
Expected result:
è

# TEST_FRAME_KEY_RESET
1. Press <kbd>`</kbd> adsf
2. Press <kbd>-></kbd>    right arrow
3. Press <kbd>e</kbd>
Expected result: 
`e

# TEST_SCROLLLOCK_KEY_NO_RESET
Do not reset for scroll lock
1. Press <kbd>`</kbd>
2. Press <kbd>scroll lock</kbd>
3. Press <kbd>e</kbd>
Expected Result: 
è

# GROUP_ID:  LDML_PROCESSOR
LDML keyboard

Install newline ldml
# TEST_CONTROL_1
1. Press <kbd>^</kbd> 
2. Press <kbd>e</kbd>
Expected result:
ê

This was previously failing 

# TEST_FRAME_KEY_RESET
1. Press <kbd>^</kbd>
2. Press <kbd>-></kbd>    right arrow
3. Press <kbd>e</kbd>
Expected result: 
e

# TEST_FRAME_SCROLL_LOCK_NO_RESET
1. Press <kbd>^</kbd>
2. Press <kbd>scroll lock</kbd>
3. Press <kbd>e</kbd>
Expected result: 
ê

File: core/src/km_core_state_api.cpp (hunk 1 above)
Comment (rc-swag) [reply core/src/km_core_state_api.cpp]: > can't use `code_points_to_delete` because that struct has been changed into an action array already by `state->set_actions()`.

Ah yes I see you are actually working on the action que and not action struct. It is getting a little confusing now. 
from LDML processor it is struct -> queue then core again -> struct for the engines.  This PR could possibly just work of the struct as the queue will eventually be deprecated.

File: core/tests/unit/ldml/keyboards/k_102_keytest.xml [hunk 2]
```diff
@@ -1,19 +1,28 @@
...
+@@expected:  zAzAz
+Comment:     2=not mapped, but NO reset.
+
+@@keys:      [K_Q][K_1][K_BKQUOTE][K_Z]
+@@expected:  zAzAzAz
+Comment:     1 is a gap (no effect) so no ctx reset
+
+@@keys:      [K_Q][K_ENTER][K_BKQUOTE][K_Z]
+@@expected:  az
+Comment:     enter=not mappable, causes ctx reset.
```
Comment (rc-swag) [inline core/tests/unit/ldml/keyboards/k_102_keytest.xml:24]: Making this comment not on this PR, but to say if this sequence was entered by the end user  when #10471 is implemented a context-aware app will restore the context after an enter and the transform will give the `A`.
For non-context away apps it will be as this test shows.

**Comment by rc-swag** [comment]
Hmm, I think I need to add a test case for the numlock keys <kbd>*</kbd>; <kbd>/</kbd> ;<kbd>-</kbd> . To test it manually I would need to update the test keyboard to have a transform based on these.

**Review by rc-swag — APPROVED** [review]
Just a suggestion for the comment block. Apart from that 

LGTM

Also I think we will handle this differently once the kmx processor stops using a action queue and just sends a struct like LDML, there will be no need to convert the action struct back to  a queue in the core.

**Comment by srl295** [comment]
Why does the check status show 'user tests are not required'  still?

**Comment by srl295** [comment]
@keymanapp-test-bot retest

**Comment by mcdurdin** [comment]
> kmx does a reset here after the RAlt-b. But vkey 66 (`K_B`) in the reset table is false.
> 
> Should it reset because of the modifiers?

Yes, <kbd>Ctrl</kbd> or <kbd>Alt</kbd> + another (unmatched) key should reset. <kbd>Ctrl</kbd> or <kbd>Alt</kbd> pressed and released without a chord should not cause a reset.

**Comment by mcdurdin** [comment]
This is a critical change late in beta to the kmx processor (less worried about ldml processor at this point).

We need to have user tests run on Windows, Linux, and macOS. We need both compliant and non-compliant apps in all cases. For compliant apps, we want to see that markers are reset when frame key is pressed -- and those tests are showing that. For non-compliant apps, we want to verify that all context is reset when frame key is pressed.

**Comment by rc-swag** [comment]
I started a new ldml keyboad on friday because i want to test some missing
scenarios. I can expand the test cases when I do that.

File: core/src/km_core_state_api.cpp [hunk 3]
```diff
@@ -363,4 +364,32 @@ km_core_cp * km_core_state_context_debug(
...
+bool
+state_should_invalidate_context(km_core_state *state,
+                     km_core_virtual_key vk,
+                     uint16_t modifier_state,
+                     uint8_t is_key_down,
+                     uint16_t _kmn_unused(event_flags)) {
+  // if emit_keystroke is present, check if a context reset is needed
+  if (state_has_action_type(state, KM_CORE_IT_EMIT_KEYSTROKE)) {
+    if (vk == KM_CORE_VKEY_BKSP && state->context().empty()) {
+        return true; // context is empty - so pass back
```
Comment (mcdurdin) [inline core/src/km_core_state_api.cpp:385]: Is this test going to be before or after the context has been manipulated by the rule processor? That is, if we have a single char in context, then user presses backspace, could this result in a context reset when we don't want it? (Yes it may not cause trouble but I want us to be clear on our boundaries and order of execution)

File: core/src/km_core_state_api.cpp [hunk 4]
```diff
@@ -363,4 +364,32 @@ km_core_cp * km_core_state_context_debug(
...
+    } else if (is_key_down &&
+              // either a ctrl or alt modifier
+                ((modifier_state & (K_CTRLFLAG | K_ALTFLAG | LCTRLFLAG | RCTRLFLAG | LALTFLAG | RALTFLAG))
+              // or a frame key
+              || vkey_to_contextreset[vk])) {
```
Comment (mcdurdin) [inline core/src/km_core_state_api.cpp:390]: Should verify that vk is in-range; this may come back to bite us with touch otherwise when we have vk>255

**Review by mcdurdin — APPROVED** [review]
I think these changes LGTM, but I am still very keen to do solid user test on it

**Comment by srl295** [comment]
1. It’s after rule processing.

2. Yes should check vk <= length of array

**Comment by rc-swag** [comment]
I don't follow the handling of the numberpad keys. I had previously noted before this change that the numberpad keys with key caps `/`,`*`,`-`,`+`,   Do not get inserted into the the context.  I was looking at making a manual keyboard that had rules with these characters to see show the rule could be matched as the pressing these keys no longer results in a context reset. However, I realised that it only works when you press the equivalent of these keys Not using the numberpad. Using the numberpad the characters never make it into the context.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_KMX_PROCESSOR_NON_COMPLIANT: 

### GROUP_WIN_10: TextEditor

* **TEST_CONTROL_1 (PASSED):** Tested with the attached PR build (Keyman 17.0.307-beta-test-11172) on Windows 11 OS (VM) in TextEditor (64-bit ) and here is my observation: 1. Pressed '. 2. Pressed the e key and verified that it showed the expected output.
* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed ' key. 2. Pressed right arrow then pressed e key. and verified that it showed the expected output.
* **TEST_FRAME_KEY_RESET_NOMARKERS (PASSED):** 1. Pressed 1 key followed by //. 2. Pressed right arrow then pressed 2 key and verified that it showed the expected output. 
* **TEST_SCROLLLOCK_KEY_NO_RESET (PASSED):** 1. Pressed ' key. 2. Enable Scroll lock. 3. Pressed e key and verified that it showed the expected result.

**Comment by bharanidharanj** [comment]
## SUITE_KMX_PROCESSOR_COMPLIANT: 

### GROUP_WIN_11: Wordpad

* **TEST_CONTROL_1 (PASSED):** 1. Pressed ' key. 2. Pressed e key and verified that it showed the expected output. 

* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed ' key. Pressed the right arrow. Then pressed e key. Verified that it showed the expected output.
* **TEST_FRAME_KEY_RESET_NOMARKERS (PASSED):** 1. Pressed 1// key. 2. Pressed the right arrow. Then, pressed 2 key. Verified that it showed the expected output.
* **TEST_SCROLLLOCK_KEY_NO_RESET (FAILED):** 1. Pressed ' key. 2. Pressed scroll lock ON. 3. Pressed the e key and noticed that it showed the wrong output.

**Comment by bharanidharanj** [comment]
## SUITE_LDML_PROCESSOR_NON_COMPLIANT: 

### GROUP_WIN_11: 

* **TEST_CONTROL_1 (PASSED):** 1. Installed Contextreset keyboard. 2. Opened TexEditor (64-bit) app. 3. Pressed ^. 4. Pressed the e key. Verifed that it showed the expected output. 
* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed ^ key. 2. Pressed right arrow key. 3. Pressed e key. Verified that it showed thex expected output. 
* **TEST_FRAME_KEY_RESET_NO_MARKERS (PASSED):** 1. Pressed a. 2. Pressed right arrow. 3. Pressed Shift+8 keys. Verified the it showed the expected output.
* **TEST_FRAME_SCROLL_LOCK_NO_RESET (FAILED):** 1. Pressed ^ key. 2. Pressed scroll lock ON. 3. Pressed e key. Verified that it showed the wrong output.

**Comment by bharanidharanj** [comment]
## SUITE_LDML_PROCESSOR_COMPLIANT: 

### GROUP_WIN_11: 

* **TEST_CONTROL_1 (PASSED):** 1. Installed Contextreset keyboard. 2. Opened TexEditor (64-bit) app. 3. Pressed ^. 4. Pressed the e key. Verified that it showed the expected output. 
* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed ^ key. 2. Pressed right arrow key. 3. Pressed e key. Verified that it showed the expected output.
* **TEST_FRAME_KEY_RESET_NO_MARKERS (PASSED):** 1. Pressed a. 2. Pressed right arrow. 3. Pressed Shift+8 keys. Verified that it showed the expected output.
* **TEST_FRAME_SCROLL_LOCK_NO_RESET (FAILED):** 1. Pressed ^ key. 2. Pressed scroll lock ON. 3. Pressed e key. Noticed that it showed the wrong output.

**Comment by bharanidharanj** [comment]
## SUITE_KMX_PROCESSOR_NON_COMPLIANT: 

### GROUP_WIN_10: TextEditor

* **TEST_CONTROL_1 (PASSED):** Tested with the attached PR build (Keyman 17.0.307-beta-test-11172) on Windows 10 OS in TextEdit (64-ƀit) and here is my observation: 1. Pressed '. 2. Pressed e key and verified that it showed the expected output. 
* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed ' key. 2. Pressed right arrow then pressed e key. Verified that it showed the expected output.
* **TEST_FRAME_KEY_RESET_NOMARKERS (PASSED):** 1. Pressed 1 key followed by //. 2. Pressed right arrow then pressed 2 key. Verified that it showed the expected output. 
* **TEST_SCROLLLOCK_KEY_NO_RESET (FAILED):** 1. Pressed ' key. 2. Enable Scroll lock. 3. Pressed e key. Verified that it showed the expected result.

**Comment by bharanidharanj** [comment]
## SUITE_KMX_PROCESSOR_COMPLIANT: 

### GROUP_WIN_10: WordPad

* **TEST_CONTROL_1 (PASSED):** Tested with the attached PR build (Keyman 17.0.307-beta-test-11172) on Windows 10 OS in Wordpad and here is my observation: 1. Pressed ' key. 2. Pressed e key and verified that it showed the expected output.
* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed ' key. Pressed the right arrow. Then pressed e key. Verified that it showed the expected output.
* **TEST_FRAME_KEY_RESET_NOMARKERS (PASSED):** 1. Pressed 1// key. 2. Pressed the right arrow. Then, pressed 2 key. Veriried that it showed the expected output. 
* **TEST_SCROLLLOCK_KEY_NO_RESET (FAILED):** 1. Pressed ' key. 2. Pressed scroll lock ON. 3. Pressed the e key and noticed that it showed the wrong output.

**Comment by bharanidharanj** [comment]
# Test Results
## SUITE_LDML_PROCESSOR_NON_COMPLIANT: 

### GROUP_WIN_10: 

* **TEST_CONTROL_1 (PASSED):** 1. Installed Contextreset keyboard. 2. Opened TexEditor (64-bit) app. 3. Pressed ^. 4. Pressed the e key. Verified that it showed the expected output. 
* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed ^ key. 2. Pressed right arrow key. 3. Pressed e key. Verified that it showed the expected output.
* **TEST_FRAME_KEY_RESET_NO_MARKERS (PASSED):** 1. Pressed a. 2. Pressed right arrow. 3. Pressed Shift+8 keys. Verified that it showed the expected output. 
* **TEST_FRAME_SCROLL_LOCK_NO_RESET (FAILED):** 1. Pressed ^ key. 2. Pressed scroll lock ON. 3. Pressed e key. Noticed that it showed the wrong output.

   

## SUITE_LDML_PROCESSOR_COMPLIANT: 

### GROUP_WIN_10: 

* **TEST_CONTROL_1 (PASSED):** 1. Installed Contextreset keyboard. 2. Opened TexEditor (64-bit) app. 3. Pressed ^. 4. Pressed the e key. Verified that it showed the expected output. 
* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed ^ key. 2. Pressed right arrow key. 3. Pressed e key. Verified that it showed the expected output.
* **TEST_FRAME_KEY_RESET_NO_MARKERS (FAILED):** 1. Pressed a. 2. Pressed right arrow. 3. Pressed Shift+8 keys.  Noticed that it showed the wrong output.
* **TEST_FRAME_SCROLL_LOCK_NO_RESET (FAILED):** 1. Pressed ^ key. 2. Pressed scroll lock ON. 3. Pressed e key. Noticed that it showed the wrong output.

**Comment by srl295** [comment]
@bharanidharanj looking at:

https://github.com/keymanapp/keyman/blob/6a2b9015c53a292ddf4115f8b998aed7303b89fe/mac/Keyman4MacIM/Keyman4MacIM/TextApiCompliance.m#L176

I would use the Mac TextEdit as a compliant app, and 
it seems there's a list of apps at the link above.  do you have any of those installed?

File: core/src/km_core_state_api.cpp (hunk 3 above)
Comment (rc-swag) [reply core/src/km_core_state_api.cpp:385]: after

File: core/src/km_core_state_api.cpp (hunk 4 above)
Comment (srl295) [reply core/src/km_core_state_api.cpp]: done

File: core/src/km_core_processevent_api.cpp [hunk 5]
```diff
@@ -52,6 +52,27 @@ km_core_process_event(km_core_state *state,
...
+      foundEmit = true;
+    }
+    state->actions().push_invalidate_context();
+    if (foundEmit) {
+      state->actions().push_back(oldAction);
+    }
+    state->actions().commit();
+  }
+
   state->apply_actions_and_merge_app_context();
```
Comment (rc-swag) [inline core/src/km_core_processevent_api.cpp:76]: I thought since we had already had the run through the processors rules (LDML, KMX) this was the correct place to able to clear the context. However for the LDML normalize case we where not quite done. For the ldml case `apply_actions_and_merge_app_context()` will result in a call `action_item_list_to_actions_object()` and this is now the context been cleared it results in update the `actions.code_points_to_delete` to delete all application context.

Comment (rc-swag) [reply core/src/km_core_processevent_api.cpp:76]: @srl295  we may want to put this PR back in Draft 
@mcdurdin  It is not ready for re-review I was trying to remove my approval but instead requested a re-review.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_KMX_PROCESSOR_COMPLIANT: 

### GROUP_LINUX: 

* **TEST_CONTROL_1 (PASSED):** Tested with the attached PR build (Keyman 17.0.307-beta (package version 17.0.307-1~PR-11172-2732.1+mantic1)) on Ubuntu Mantic Linux OS (VM) and here is my observation: 1. Installed SIL_EuroLatin keyboard. 2. Opened gedit. 3. Pressed ' key. 4. Pressed e and verified that it showed the expected output. 
* **TEST_FRAME_KEY_RESET_MARKERS (FAILED):** 1. Pressed '. 2. Pressed right arrow key. 3. Pressed e and noticed that it showed the wrong output.
* **TEST_FRAME_KEY_RESET_NOMARKERS (PASSED):** 1. Pressed 1//. 2. Pressed right arrow key. 3. Pressed 2 key and verified that it showed the expected output. 
* **TEST_SCROLLLOCK_KEY_NO_RESET (PASSED):** 1. Pressed ' key. 2. Pressed scroll lock key. 3. Pressed e and verified it showed the correct output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_KMX_PROCESSOR_NON_COMPLIANT: 

### GROUP_LINUX: 

* **TEST_CONTROL_1 (FAILED):** Tested with the attached PR build (Keyman 17.0.307-beta (package version 17.0.307-1~PR-11172-2732.1+mantic1) on Ubuntu Mantic Linux OS (VM) and here is my observation: 1. Installed SIL_EuroLatin keyboard. 2. Opened Chrome browser. 3. Clicked the Search bar. Pressed ' key. 4. Pressed e and noticed that it showed the wrong output. 

  


* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed '. 2. Pressed right arrow key. 3. Pressed e and verified that it showed correct output.

   

* **TEST_FRAME_KEY_RESET_NOMARKERS (PASSED):** 1. Pressed 1//. 2. Pressed right arrow key. 3. Pressed 2 key and verified that it showed the expected output. 

   

* **TEST_SCROLLLOCK_KEY_NO_RESET (FAILED):** 1. Pressed ' key. 2. Pressed scroll lock key. 3. Pressed e and noticed that it showed the wrong output.

**Comment by bharanidharanj** [comment]
## SUITE_LDML_PROCESSOR_NON_COMPLIANT: 

### GROUP_LINUX: 

* **TEST_CONTROL_1 (PASSED):** Tested with the attached PR build (Keyman 17.0.307-beta (package version 17.0.307-1~PR-11172-2732.1+mantic1) on Ubuntu Mantic Linux OS (VM) and here is my observation: 1. Installed English (ContextReset) keyboard. 2. Opened gedit. 3. Pressed ' key. 4. Pressed e and verified that it showed the expected output. 

* **TEST_FRAME_KEY_RESET_MARKERS (FAILED):** 1. Pressed '. 2. Pressed right arrow key. 3. Pressed e and noticed that it showed the wrong output. 

* **TEST_FRAME_KEY_RESET_NO_MARKERS (PASSED):** 1. Pressed 1//. 2. Pressed right arrow key. 3. Pressed 2 key and verified that it showed the expected output. 

* **TEST_FRAME_SCROLL_LOCK_NO_RESET (PASSED):** 1. Pressed ' key. 2. Pressed scroll lock key. 3. Pressed e and verified that it showed the correct output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_LDML_PROCESSOR_NON_COMPLIANT: 

### GROUP_MAC: 

* **TEST_CONTROL_1 (PASSED):** Tested with the attached PR build (Keyman 17.0.307-beta-test-11172) on macOS Sonoma and here is my observation: 1. Installed English (ContextReset) keyboard. 2. Opened TexEdit app. 3. Pressed ' key. 4. Pressed e and verified that it showed the expected output. 

   


* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed ^. 2. Pressed right arrow key. 3. Pressed e and verified that it showed correct output. 

   

* **TEST_FRAME_KEY_RESET_NO_MARKERS (FAILED):** 1. Pressed a. 2. Pressed right arrow key. 3. Pressed Shift + 8 and noticed that it showed the wrong output. 

   

* **TEST_FRAME_SCROLL_LOCK_NO_RESET (FAILED):** 1. Pressed ^ key. 2. Pressed scroll lock (by pressing fn+shift+F12 keys) key. 3. Pressed e and noticed that it showed the incorrect output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_LDML_PROCESSOR_NON_COMPLIANT: 

### GROUP_MAC: 

* **TEST_CONTROL_1 (PASSED):** Tested with the attached PR build (Keyman 17.0.307-beta-test-11172) on macOS Sonoma and here is my observation:  1. Installed English (ContextReset) keyboard. 2. Opened Chrome browser. 3. Clicked the Search bar. Pressed ' key. 4. Pressed e and verified that it showed the expected output. 
* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed '. 2. Pressed right arrow key. 3. Pressed e and verified that it showed correct output. 
* **TEST_FRAME_KEY_RESET_NO_MARKERS (PASSED):** 1. Pressed ^. 2. Pressed right arrow key. 3. Pressed e key and verified that it showed the expected output. 
* **TEST_FRAME_SCROLL_LOCK_NO_RESET (FAILED):** 1. Pressed ^ key. 2. Pressed scroll lock (fn+shift+F12)  key. 3. Pressed e and noticed that it showed the wrong output. 
ldmlchrome

**Comment by srl295** [comment]
@bharanidharanj we're going to rework this one a bit.  please hold off on testing

File: core/src/km_core_processevent_api.cpp (hunk 5 above)
Comment (srl295) [reply core/src/km_core_processevent_api.cpp:76]: @rc-swag i'll reply on the body of the PR

**Comment by srl295** [comment]
@rc-swag OK now i'm tracking.

- LDML `supports_normalization()`. So we call `actions_normalize()`. 
- we've cleared the context, so then actions_normalize tries to sync the context with the (cleared) context.

- kmx situation will call the following.  whereas actions_normalize will try to delete any mismatch.

```c
 * Refresh app_context to match the cached_context. Does not do normalization,
 * unlike `actions_normalize`. Used in conjunction with keyboard processors that
 * do not support normalization. Resulting app context is same as the cached
 * context, but without markers.
... */
bool km::core::actions_update_app_context_nfu(
```

but in the kmx case, `cached_context` is also now empty. however, the above function does NOT set code_points_to_delete.   It actually just replaces the app_context with the (now cleared) context.


I guess what I'm wondering is if `actions_normalize()` should have something such as the following at the top:

```c
if (cached_context().empty()) km_core_context_clear(app_context);
```

that is, if there's nothing in the cached context, don't consider any app_context. 

if i'm reading right this would make the ldml behavior match kmx in this situation?

File: core/src/km_core_state_api.cpp (hunk 3 above)
Comment (mcdurdin) [reply core/src/km_core_state_api.cpp:385]: that suggests that bksp for the first character will delete that character and _also_ pass it back to the app for a second deletion?

**Comment by mcdurdin** [comment]
@srl295 That sounds appropriate but I have been out of the loop long enough that I am not 100% confident that I am thinking through all scenarios.

File: core/src/km_core_state_api.cpp (hunk 3 above)
Comment (rc-swag) [reply core/src/km_core_state_api.cpp:385]: Yes, that is correct, we can't rely on the state->context().empty(). I originally thought we could use  `code_points_to_delete` value from the action struct. However, the kmx processor currently only gives the action list.   This information could be found by checking each action item for KM_CORE_IT_BACK then `action_items->backspace.expected_type==KM_CORE_BT_CHAR`. 
I think there a few cleaner choices here.

1. Move  the new code we have in `km_core_state_api` starting at line 55 
```
 if (state_should_invalidate_context(state, vk, modifier_state, is_key_down, event_flags)) {
    state->context().clear();
```
To inside `state::apply_actions_and_merge_app_context()` after line   `action_item_list_to_actions_object(action_items, &this->_action_struct);`.  This way we can just look at the action struct for `code_points_to_delete`.  A bonus here is that this will also mean no change is needed when the kmx_processor is updated to use the action_struct instead of action_list.

2. Go with what we discussed as an option in or zoom meeting. Turn `km_core_bool emit_keystroke;` member of the action struct to a tri-state.  0 = do nothing; 1 = emit_key_stroke; 2 = emit_key_stroke and invalidate context. 
This puts the decision back on the processors though.

**Comment by rc-swag** [comment]
> that is, if there's nothing in the cached context, don't consider any app_context.

Thank you for the detailed explanation.  What you propose would work however, I am thinking that maybe we are handling the result of the invalidated context in two places which may get lost when we look at this code in 1 years time. Do you think we could clear the `app_context` at the same time we clear the `cached context` if invalidate_context is true. 
That way the  `actions_normalize` can stay as it is?

**Comment by srl295** [comment]
> > that is, if there's nothing in the cached context, don't consider any app_context.
> 
> Thank you for the detailed explanation. What you propose would work however, I am thinking that maybe we are handling the result of the invalidated context in two places which may get lost when we look at this code in 1 years time. Do you think we could clear the `app_context` at the same time we clear the `cached context` if invalidate_context is true. That way the `actions_normalize` can stay as it is?

that makes even more sense. i will try that, let me see if i can install this locally and test out the cases myself.

**Comment by srl295** [comment]
So, I installed the build artifact, and was not able to reproduce the issue so far with the latest commit

Now installing a slightly prior version to make sure i can repro what Ross saw.

**Comment by srl295** [comment]
ok SUCCESS i repro'ed the problem in windows downloading an older build of this PR!

**Comment by srl295** [comment]
- with 4f2ef49  I am able to pass all of the tests for conformant / nonconformant X kmx / ldml.

File: core/src/km_core_state_api.cpp (hunk 3 above)
Comment (rc-swag) [reply core/src/km_core_state_api.cpp:385]: @srl295 
Further thoughts looking again at the "kmx_processor" and the "ldml processor". All we have to do is remove the check for `state->context().empty(`).
In the case of a backspace key being pressed the processors only set  `KM_CORE_IT_EMIT_KEYSTROKE` when the context is empty.  Therefore that check has already been made. That is if action is  `KM_CORE_IT_EMIT_KEYSTROKE`  and `vkey== KM_CORE_VKEY_BKSP`. We do not need to check if the context is empty here. 

I think we can keep the change suggest in option 1 for the future when the action list is deprecated.

**Comment by rc-swag** [comment]
@marc I can investigate but you may know, do the number lock keys not get passed to the keyboard processors?

I was going to write some tests to make sure the number lock keys <kbd>*</kbd>;<kbd>/</kbd>;<kbd>+</kbd>;<kbd>-</kbd>; did not reset context however they do. (or they don't get added to the context)

Non-compliant 
Load euro-latin
1. Press <kbd>1</kbd> 
2. Using the number pad press <kbd>/</kbd> <kbd>/</kbd>
3. Press <kbd>2</kbd>
The result is:
1//2
instead of ½

Non-compliant context reset

1. Press <kbd>a</kbd> 
2. Using the number pad press <kbd>*</kbd>
the result is:
a* 
instead of `Star`

**Comment by mcdurdin** [comment]
> @mcdurdin I can investigate but you may know, do the number lock keys not get passed to the keyboard processors?

I don't have a memory on the answer to this, sorry. I think we supported numlock on + numeric keypad in the past, but it's been a long time since I have played with it.

**Comment by rc-swag** [comment]
Ok I am creating a separate issue to deal with the numberpad characters. This PR is solving the blocking issue with LDML, it is adding the vkreset array. Anymore is making it too hard to track the changes.
https://github.com/keymanapp/keyman/issues/11250

**Comment by srl295** [comment]
@keymanapp-test-bot retest SUITE_KMX_PROCESSOR_NON_COMPLIANT GROUP_WIN_11 all , SUITE_KMX_PROCESSOR_COMPLIANT GROUP_WIN_11 all, SUITE_LDML_PROCESSOR_NON_COMPLIANT GROUP_WIN_11 all, SUITE_LDML_PROCESSOR_COMPLIANT GROUP_WIN_11 all

**Comment by rc-swag** [comment]
@keymanapp-test-bot retest SUITE_KMX_PROCESSOR_NON_COMPLIANT GROUP_WIN_10 TEST_SCROLLLOCK_KEY_NO_RESET GROUP_MAC TEST_SCROLLLOCK_KEY_NO_RESET GROUP_LINUX TEST_CONTROL_1 TEST_SCROLLLOCK_KEY_NO_RESET SUITE_KMX_PROCESSOR_COMPLIANT GROUP_WIN_10 TEST_SCROLLLOCK_KEY_NO_RESET GROUP_MAC TEST_SCROLLLOCK_KEY_NO_RESET GROUP_LINUX TEST_FRAME_KEY_RESET_MARKERS SUITE_LDML_PROCESSOR_NON_COMPLIANT GROUP_WIN_10 TEST_FRAME_SCROLL_LOCK_NO_RESET GROUP_MAC TEST_FRAME_SCROLL_LOCK_NO_RESET SUITE_LDML_PROCESSOR_COMPLIANT GROUP_WIN_10 TEST_FRAME_KEY_RESET_NO_MARKERS TEST_FRAME_SCROLL_LOCK_NO_RESET GROUP_MAC TEST_FRAME_KEY_RESET_NO_MARKERS TEST_FRAME_SCROLL_LOCK_NO_RESET GROUP_LINUX TEST_FRAME_KEY_RESET_MARKERS

**Comment by srl295** [comment]
@bharanidharanj the LDML tests now give editors for mac and linux

File: core/src/km_core_processevent_api.cpp [hunk 6]
```diff
@@ -52,6 +52,30 @@ km_core_process_event(km_core_state *state,
...
+    state->context().clear();
+    state->app_context().clear();
+
+    // we are already committed. So we need to un-commit (remove the end of the vector)
+    if (state->actions().back().type == KM_CORE_IT_END) {
+      state->actions().pop_back();
+    }
+    bool foundEmit = false;
+    km::core::action oldAction;
+    // try to put the invalidate item before the emit keystroke
```
Comment (mcdurdin) [inline core/src/km_core_processevent_api.cpp:66]: It'd be good to add some explanation of why we are doing this -- why do we need to add the invalidate context before emit keystroke, etc.

File: core/src/km_core_state_api.cpp [hunk 7]
```diff
@@ -363,4 +364,35 @@ km_core_cp * km_core_state_context_debug(
...
+                     uint16_t modifier_state,
+                     uint8_t is_key_down,
+                     uint16_t _kmn_unused(event_flags)) {
+  if (!is_key_down) {
+    return false;  // don't invalidate on keyup
+  }
+  // if emit_keystroke is present, check if a context reset is needed
+  if (state_has_action_type(state, KM_CORE_IT_EMIT_KEYSTROKE)) {
+    if (
+        // always reset on backspace
```
Comment (mcdurdin) [inline core/src/km_core_state_api.cpp:388]: Some more explanation here would be helpful.

```suggestion
        // when a backspace keystroke is emitted, it is because we are at the start of 
        // context, and we want to give the application the chance to process it, e.g. 
        // by moving to previous field. Note that context manipulation does not result 
        // in an emit_keystroke backspace action, as this is handled through the 
        // `code_points_to_delete` field. So we always invalidate context when a 
        // processor emits a backspace.
```

File: core/src/km_core_state_api.cpp [hunk 8]
```diff
@@ -363,4 +364,35 @@ km_core_cp * km_core_state_context_debug(
...
+        vk == KM_CORE_VKEY_BKSP ||
+        // certain modifiers reset
```
Comment (mcdurdin) [inline core/src/km_core_state_api.cpp:390]:
```suggestion
        // certain modifiers invalidate context
```

File: core/src/km_core_state_api.cpp [hunk 9]
```diff
@@ -363,4 +364,35 @@ km_core_cp * km_core_state_context_debug(
...
+        modifier_should_contextreset(modifier_state) ||
+        // reset on frame keys
```
Comment (mcdurdin) [inline core/src/km_core_state_api.cpp:392]:
```suggestion
        // most frame keys invalidate context
```

File: core/src/km_core_state_api.cpp [hunk 10]
```diff
@@ -363,4 +364,35 @@ km_core_cp * km_core_state_context_debug(
...
+  if (!is_key_down) {
+    return false;  // don't invalidate on keyup
+  }
+  // if emit_keystroke is present, check if a context reset is needed
+  if (state_has_action_type(state, KM_CORE_IT_EMIT_KEYSTROKE)) {
+    if (
+        // always reset on backspace
+        vk == KM_CORE_VKEY_BKSP ||
+        // certain modifiers reset
+        modifier_should_contextreset(modifier_state) ||
```
Comment (mcdurdin) [inline core/src/km_core_state_api.cpp:391]: I think we should call this `modifier_should_invalidate_context`

File: core/src/km_core_state_api.cpp [hunk 11]
```diff
@@ -363,4 +364,35 @@ km_core_cp * km_core_state_context_debug(
...
+        // reset on frame keys
+        vkey_should_contextreset(vk)) {
```
Comment (mcdurdin) [inline core/src/km_core_state_api.cpp:393]:
```suggestion
        vkey_should_invalidate_context(vk)) {
```

File: core/src/vkey_to_contextreset.cpp [hunk 12]
```diff
@@ -0,0 +1,278 @@
+#include "vkey_to_contextreset.hpp"
+
+namespace km {
+namespace core {
+
+bool vkey_to_contextreset[vkey_to_contextreset_count] = {
```
Comment (mcdurdin) [inline core/src/vkey_to_contextreset.cpp:6]:
```suggestion
bool vkey_should_invalidate_context[vkey_should_invalidate_context_count] = {
```

File: core/src/vkey_to_contextreset.cpp
Comment (mcdurdin) [inline core/src/vkey_to_contextreset.cpp:1]: rename this to vkey_should_invalidate_context.cpp

File: core/tests/unit/ldml/ldml.cpp [hunk 13]
```diff
@@ -254,13 +254,13 @@ verify_context(std::u16string& text_store, km_core_state* &test_state, std::vect
...
-    assert(false);
-  }
-  delete[] buf;
+    km_core_context_items_dispose(citems);
+    if (text_store != buf) {
+      std::cerr << "text store has diverged from buf" << std::endl;
+      std::cerr << "text store: " << string_to_hex(text_store) << " [" << text_store << "]" << std::endl;
+      assert(false);
+    }
+    delete[] buf;
```
Comment (mcdurdin) [inline core/tests/unit/ldml/ldml.cpp:263]: should the whole function be outdented instead?

File: core/tests/unit/ldml/ldml.cpp [hunk 14]
```diff
@@ -329,6 +329,11 @@ run_test(const km::core::path &source, const km::core::path &compiled, km::tests
             test_state, p.vk, p.modifier_state | test_source.caps_lock_state(), key_down,
             KM_CORE_EVENT_FLAG_DEFAULT));  // TODO-LDML: for now. Should send touch and hardware events.
 
+        if (state_should_invalidate_context(test_state, p.vk, p.modifier_state | test_source.caps_lock_state(), key_down,
+            KM_CORE_EVENT_FLAG_DEFAULT)) {
+              test_context.clear();
+              text_store.clear();
```
Comment (mcdurdin) [inline core/tests/unit/ldml/ldml.cpp:335]:
```suggestion
          test_context.clear();
          text_store.clear();
```

**Review by mcdurdin — APPROVED** [review]
LGTM. Some comments requested. Minor formatting nits.

**Comment by bharanidharanj** [comment]
## SUITE_KMX_PROCESSOR_NON_COMPLIANT: 

### GROUP_WIN_10: TextEditor

* **TEST_SCROLLLOCK_KEY_NO_RESET (FAILED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 10 OS and here is my observation: 1. Opened the Notepad app. 2. Pressed ' key. 3. Pressed scroll lock ON. 3. Pressed e key. Noticed that it produces wrong output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_KMX_PROCESSOR_NON_COMPLIANT: 

### GROUP_WIN_11: TextEditor

* **TEST_CONTROL_1 (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 11 OS (VM)  and here is my observation: 1. Opened the Notepad app. 2. Pressed ' key. 3. Pressed scroll lock ON. 3. Pressed e key. Noticed that it produces the expected output. 
* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed ' key. 2. Pressed right arrow then pressed e key. Verified that it showed the expected output.
* **TEST_FRAME_KEY_RESET_NOMARKERS (FAILED):** 1. Pressed 1 key followed by //. 2. Pressed right arrow then pressed 2 key. Noticed that it produces the wrong output. 
* **TEST_SCROLLLOCK_KEY_NO_RESET (FAILED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 11 OS (VM)  and here is my observation: 1. Opened the Notepad app. 2. Pressed ' key. 3. Pressed scroll lock ON. 3. Pressed e key. Noticed that it produces wrong output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_KMX_PROCESSOR_NON_COMPLIANT: 

### GROUP_LINUX: Chrome Brower

* **TEST_CONTROL_1 (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Ubuntu 22.04 Jammy Jelly Linux (VM) and here is my observation: 1. Opened the Chromium browser app. 2. Switched to sil_eurolatin Keyboard. 3. Pressed ` key. 4. Pressed e key. Noticed that it shows the wrong output. 

   

* **TEST_SCROLLLOCK_KEY_NO_RESET (PASSED):** 1. Opened the Chromium browser app. 2. Pressed ` key. 3. Pressed scroll lock ON. 3. Pressed e key. Verified that it showing the correct output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_KMX_PROCESSOR_NON_COMPLIANT: 

### GROUP_MAC: Chrome Browser

* **TEST_SCROLLLOCK_KEY_NO_RESET (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on macOS Sonoma and here is my observation: 1. Opened the Chrome browser app. 2. Pressed ` key. 3. Pressed scroll lock ON. 3. Pressed e key. Verified that it showing the correct output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_KMX_PROCESSOR_COMPLIANT: 

### GROUP_MAC: TextEdit 

* **TEST_SCROLLLOCK_KEY_NO_RESET (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on macOS Sonoma and here is my observation: 1. Opened the TextEdit app. 2. Pressed ` key. 3. Pressed scroll lock ON. 3. Pressed e key. Verified that it showing the correct output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_KMX_PROCESSOR_COMPLIANT: 

### GROUP_LINUX: gedit

* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Ubuntu 22.04 Jammy Jelly Linux (VM) and here is my observation: 1.Opened the TextEditor.  Pressed 1 key followed by //. 2. Pressed right arrow then pressed 2 key. Verified that it showed the expected output.

**Comment by rc-swag** [comment]
> ## SUITE_KMX_PROCESSOR_NON_COMPLIANT:
> ### GROUP_WIN_11: TextEditor

@bharanidharanj   For the non_compliant app you should be using the TextEditor that is available as a test artifact on this PR.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_KMX_PROCESSOR_COMPLIANT: 

### GROUP_WIN_10: WordPad

* **TEST_SCROLLLOCK_KEY_NO_RESET (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 10 OS and here is my observation: 1.Opened the WordPad.  Pressed 1 key followed by //. 2. Pressed right arrow then pressed 2 key. Verified that it showed the expected output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_LDML_PROCESSOR_NON_COMPLIANT: 

### GROUP_WIN_10: TextEditor

* **TEST_FRAME_SCROLL_LOCK_NO_RESET (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 10 OS and here is my observation: 1. Opened the Notepad.  Pressed ^ key. 2. Pressed Scroll lock key. 3. Pressed e key. Verified that it showed the expected output ê.

* **TEST_MODIFIER_TAP_NO_RESET (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 10 OS and here is my observation: 1. Opened the Notepad.  Pressed ^ key. 2. Pressed and Release ctrl key. 3. Pressed e key. Verified that it showed the expected output ê.

**Comment by bharanidharanj** [comment]
## SUITE_LDML_PROCESSOR_NON_COMPLIANT: 

### GROUP_LINUX: Chrome Brower

* **TEST_MODIFIER_TAP_NO_RESET (OPEN):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Ubuntu 22.04 Jammy Jelly Linux OS (VM) and here is my observation: 1.Opened the Chromium browser app.  Pressed ^ key. 2. Pressed and Release ctrl key. 3. Pressed e key. Verified that it showed the expected output ê.

**Comment by bharanidharanj** [comment]
## SUITE_LDML_PROCESSOR_COMPLIANT: 

### GROUP_LINUX: gedit

* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on uBUNTU 22.04 Jammy Jelly Linux OS (VM) and here is my observation: 1. Opened TextEditor app. Pressed ^ key. 2. Pressed Scroll lock key. 3. Pressed e key. Verified that it showed the expected output ê.

* **TEST_MODIFIER_TAP_NO_RESET (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Ubuntu 22.04 Jammy Jelly Linux OS (VM) and here is my observation: 1.Opened TextEditor app. Pressed ^ key. 2. Pressed and Release ctrl key. 3. Pressed e key. Verified that it showed the expected output ê.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_KMX_PROCESSOR_COMPLIANT: 

### GROUP_WIN_11: Wordpad

* **TEST_CONTROL_1 (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 11 OS (VM) and here is my observation: 1. Opened the WordPad app. 2. Pressed ' key. 3. Pressed scroll lock ON. 3. Pressed e key. Noticed that it produces the expected output.
* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed ' key. 2. Pressed right arrow then pressed e key. Verified that it showed the expected output.
* **TEST_FRAME_KEY_RESET_NOMARKERS (PASSED):** 1. Pressed 1 key followed by //. 2. Pressed right arrow then pressed 2 key. Verified that the it is showing the correct output.
* **TEST_SCROLLLOCK_KEY_NO_RESET (FAILED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 11 OS (VM) and here is my observation: 1. Opened the Notepad app. 2. Pressed ' key. 3. Pressed scroll lock ON. 3. Pressed e key. Noticed that it produces wrong output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_LDML_PROCESSOR_NON_COMPLIANT: 

### GROUP_WIN_11: TextEditor

* **TEST_CONTROL_1 (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 11 OS (VM) and here is my observation: 1. Opened the Notepad app. 2. Switched to ContextReset Keyboard. Pressed ^ key. 3.  Pressed e key. Verified that it is showing the expected output. 
* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed ^ key. 2. Pressed right arrow then pressed e key. Verified that it showed the expected output.
* **TEST_FRAME_KEY_RESET_NO_MARKERS (FAILED):** 1. Pressed a key followed by a right arrow key. 2. Pressed Shift+8 key. Noticed that the it is showing the wrong output.
* **TEST_FRAME_SCROLL_LOCK_NO_RESET (FAILED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 11 OS (VM) and here is my observation: 1. Opened the Notepad app. 2. Pressed ^ key. 3. Pressed scroll lock ON. 3. Pressed e key. Noticed that it is showing the wrong output. 
* **TEST_MODIFIER_TAP_NO_RESET (PASSED):** 1. Pressed ^ key. 2. Pressed then released Ctrl key. 3. Pressed e key. Verified that it is showing the expected result.

**Comment by srl295** [comment]
@keymanapp-test-bot retest SUITE_KMX_PROCESSOR_NON_COMPLIANT GROUP_WIN_10 TEST_SCROLLLOCK_KEY_NO_RESET GROUP_WIN_10 TEST_SCROLLLOCK_KEY_NO_RESET SUITE_LDML_PROCESSOR_NON_COMPLIANT GROUP_WIN_10 TEST_FRAME_SCROLL_LOCK_NO_RESET SUITE_LDML_PROCESSOR_COMPLIANT GROUP_WIN_10 TEST_FRAME_KEY_RESET_NO_MARKERS TEST_FRAME_SCROLL_LOCK_NO_RESET

**Comment by bharanidharanj** [comment]
## SUITE_LDML_PROCESSOR_COMPLIANT: 

### GROUP_WIN_11: WordPad

* **TEST_CONTROL_1 (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 11 OS (VM) and here is my observation: 1. Opened the WordPad app. 2. Switched to ContextReset Keyboard. Pressed ^ key. 3. Pressed e key. Verified that it is showing the expected output.

* **TEST_FRAME_KEY_RESET_MARKERS (PASSED):** 1. Pressed ^ key. 2. Pressed right arrow then pressed e key. Verified that it showed the expected output.
* **TEST_FRAME_KEY_RESET_NO_MARKERS (PASSED):** 1. Pressed a key followed by a right arrow key. 2. Pressed Shift+8 key. Noticed that it is showing the wrong output.
* **TEST_FRAME_SCROLL_LOCK_NO_RESET (FAILED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 11 OS (VM) and here is my observation: 1. Opened the WordPad app. 2. Pressed ^ key. 3. Pressed scroll lock ON. 3. Pressed e key. Noticed that it is showing the wrong output.
* **TEST_MODIFIER_TAP_NO_RESET (PASSED):** 1. Pressed ^ key. 2. Pressed then released Ctrl key. 3. Pressed e key. Verified that it is showing the expected result.

**Comment by bharanidharanj** [comment]
## SUITE_LDML_PROCESSOR_COMPLIANT: 

### GROUP_WIN_10: WordPad

* **TEST_FRAME_KEY_RESET_NO_MARKERS (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 11 OS (VM) and here is my observation: 1. Opened the WordPad app. 2. Switched to ContextReset Keyboard. 3. Pressed a key followed by a right arrow key. 4. Pressed Shift+8 key. Verified that it is showing the correct output.
* **TEST_FRAME_SCROLL_LOCK_NO_RESET (FAILED):** 1. Opened the WordPad app. 2. Pressed ^ key. 3. Pressed scroll lock ON. 3. Pressed e key. Noticed that it is showing the wrong output.
* **TEST_MODIFIER_TAP_NO_RESET (PASSED):** 1. Pressed ^ key. 2. Pressed then released Ctrl key. 3. Pressed e key. Verified that it is showing the expected result.

**Comment by srl295** [comment]
@keymanapp-test-bot retest SUITE_LDML_PROCESSOR_NON_COMPLIANT GROUP_WIN_11 TEST_FRAME_KEY_RESET_NOMARKERS

**Comment by srl295** [comment]
> @keymanapp-test-bot retest SUITE_LDML_PROCESSOR_NON_COMPLIANT GROUP_WIN_11 TEST_FRAME_KEY_RESET_NOMARKERS

@bharanidharanj I forgot this one which was still on the wrong editor.  Otherwise I think the only issue is the scroll lock key.

PR broken due to only partly accepting review comments - sorry, fixed.

**Comment by rc-swag** [comment]
@keymanapp-test-bot retest SUITE_KMX_PROCESSOR_NON_COMPLIANT GROUP_WIN_11 TEST_FRAME_KEY_RESET_NOMARKERS

**Comment by rc-swag** [comment]
@keymanapp-test-bot retest SUITE_KMX_PROCESSOR_NON_COMPLIANT GROUP_LINUX TEST_CONTROL_1 SUITE_LDML_PROCESSOR_NON_COMPLIANT GROUP_WIN_11 TEST_FRAME_KEY_RESET_NO_MARKERS

**Comment by rc-swag** [comment]
@keymanapp-test-bot skip SUITE_KMX_PROCESSOR_NON_COMPLIANT GROUP_WIN_11 TEST_SCROLLLOCK_KEY_NO_RESET SUITE_KMX_PROCESSOR_COMPLIANT  GROUP_WIN_11 TEST_SCROLLLOCK_KEY_NO_RESET SUITE_LDML_PROCESSOR_NON_COMPLIANT GROUP_WIN_11 TEST_SCROLLLOCK_KEY_NO_RESET
SUITE_LDML_PROCESSOR_COMPLIANT GROUP_WIN_11 TEST_SCROLLLOCK_KEY_NO_RESET

**Comment by rc-swag** [comment]
## SUITE_KMX_PROCESSOR_NON_COMPLIANT: 

### GROUP_WIN_11: TextEditor

* **TEST_SCROLLLOCK_KEY_NO_RESET (SKIPPED):** notes

**Comment by rc-swag** [comment]
@keymanapp-test-bot retest SUITE_LDML_PROCESSOR_COMPLIANT GROUP_WIN_10 TEST_FRAME_SCROLL_LOCK_NO_RESET SUITE_LDML_PROCESSOR_COMPLIANT GROUP_WIN_11 TEST_FRAME_SCROLL_LOCK_NO_RESET

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_KMX_PROCESSOR_NON_COMPLIANT: 

### GROUP_LINUX: Chrome Brower (https://www.editpad.org/)

* **TEST_CONTROL_1 (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Ubuntu 22.04 Jammy Jelly Linux (VM) and here is my observation: 1. Opened "https://editpad.org" site in the chromium browser. 2. Switched to sil_eurolatin Keyboard. 3. Pressed ` key. 4. Pressed e key. Verified that it is showing the expected output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_KMX_PROCESSOR_NON_COMPLIANT: 

### GROUP_WIN_11: TextEditor

* **TEST_FRAME_KEY_RESET_NOMARKERS (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 11 OS (VM) and here is my observation: 1. Opened "EC Test App" text editor. Pressed 1 key followed by //. 2. Pressed right arrow then pressed 2 key. Verified that it showed the expected output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_LDML_PROCESSOR_NON_COMPLIANT: 

### GROUP_WIN_11: TextEditor

* **TEST_FRAME_KEY_RESET_NO_MARKERS (PASSED):** Retested with the updated PR build (Keyman 17.0.311-beta-test-11172) on Windows 11 OS (VM) and here is my observation: 1. Opened "EC Test App" text editor. 1. Pressed a. 2. Pressed right arrow. 3. Pressed Shift+8 keys. Verified that it showed the expected output.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.315-beta](https://keyman.com/downloads/releases/beta/17.0.315)

**Comment by mcdurdin** [comment]
Looks like we forgot to test this in the Keyman Developer debugger -- #11486!
