### PR TITLE
fix(web): prevent layer switch key from erasing selection

### LINKED ISSUE #7866: bug(web): pressing layer switch key with selected text would delete the selection
### Describe the bug

From https://community.software.sil.org/t/ios-and-android-undesirable-behaviour-with-selected-text/6986:

> I must say my phone doesn’t respond well to trying to select words, but when it does recognise that’s what I’m trying to do Keyman doesn’t remove the space like on iOS [refer to #7865], but switches to the capitalised layer automatically which is not what I usually want, and then when I tap shift to change layer it deletes the selected text as if I pressed the delete key. Since I was likely to remove it anyway this is more disconcertingly unexpected behaviour than a catastrophe, but I would prefer it if pressing the layer change buttons didn’t remove selected text and also the non-shift layer is more likely to be the one I want. A clever algorithm would maybe try to guess what I want by looking at context before the selection if possible, but I don’t really expect that. The behaviour is quite different on iOS and Android, anyway.
> 
> I would like to find out whether this is very common, whether I can fix my keyboards to cope with it and whether this is something developers are aware of and whether any attention can be given to it.

### Reproduce the bug

_No response_

### Expected behavior

_No response_

### Related issues

#7865

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

_No response_

### Operating system

_No response_

### Device

_No response_

### Target application

_No response_

### Browser

_No response_

### Keyboard name

NaijaType and sil_euro_latin

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #7866.

When the transform generated by a key event results in no changes to the text, this will no longer trigger a change event in the apps. This means that layer switch keys will no longer erase the selection.

Fix proposed by @jahorton.

# User Testing

GROUP_IOS: Run these tests in Keyman for iPhone and iPad
GROUP_ANDROID: Run these tests in Keyman for Android

TEST_BASIC_INPUT: Verify that basic input continues to function correctly.
TEST_BACKSPACE: Type some text, then verify that backspace continues to work as normal.
TEST_CONTEXT_SYNC: Using Khmer Angkor keyboard, type <kbd>ខ</kbd> <kbd>េ</kbd>. Select the numeric/symbol layer, and return to the default layer. Press <kbd>្ម</kbd> (longpress on <kbd>ម</kbd>). Press <kbd>Backspace</kbd> and verify that the output on screen is ខ្ម (and not ខេ).
TEST_SELECTION_DELETION: Type two words, select the second word, and press backspace on the touch keyboard to delete it. Verify that the word is deleted as expected.
TEST_SELECTION_REPLACEMENT: Type two words, select the second word, and press a letter on the touch keybaord to replace it. Verify that the word is deleted as expected, and the new letter is left in its place.
TEST_SELECTION_LAYER_SWITCH: Type two words, select the second word, and press any layer switch key on the touch keyboard. The active layer should change, but the text should not be modified.

### CODE REVIEW

**Review by ermshiperete — APPROVED** [review]
LGTM

File: web/src/app/webview/src/contextManager.ts [hunk 1]
```diff
@@ -41,7 +41,9 @@ export class ContextHost extends Mock {
 
       // Signal the necessary text changes to the embedding app, if it exists.
       if(this.oninserttext) {
-        this.oninserttext(transform.deleteLeft, transform.insert, transform.deleteRight);
+        if(transform.deleteLeft > 0 || transform.insert != '' || transform.deleteRight > 0 || transform.erasedSelection) {
```
Comment (jahorton) [inline web/src/app/webview/src/contextManager.ts:44]:
```typescript
import {isEmptyTransform} from '@keymanapp/keyboard-processor';
```

```suggestion
        if(!isEmptyTransform(transform) || transform.erasedSelection) {
```

I think it's probably best to keep the new condition outside of `isEmptyTransform`, but we can still use the function here.

**Comment by jahorton** [comment]
> Note: need @jahorton's input on how best to structure these user tests to ensure that we cover the necessary potential context desync scenarios.

What you have here seems fine to me.

File: web/src/app/webview/src/contextManager.ts (hunk 1 above)
Comment (jahorton) [reply web/src/app/webview/src/contextManager.ts:44]: https://github.com/keymanapp/keyman/blob/acc38fea588986c70036571acdf2f334f83bf7b2/common/web/keyboard-processor/src/text/outputTarget.ts#L14-L19

Comment (mcdurdin) [reply web/src/app/webview/src/contextManager.ts:44]: Thanks, didn't know about that function. I'm puzzled that passing a `null` transform is not considered empty? (seems like it would be empty on the surface)

Comment (jahorton) [reply web/src/app/webview/src/contextManager.ts:44]: That's probably a reasonable change to make, based upon its current uses.  I think it's only there at present to serve as a null-guard, but returning `true` makes more sense for that.

Comment (mcdurdin) [reply web/src/app/webview/src/contextManager.ts:44]: Cool taking that up in #11084.

**Review by jahorton — APPROVED** [review]

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS: Run these tests in Keyman for iPhone and iPad

* **TEST_BASIC_INPUT (PASSED):** Tested with the attached PR build (17.0.292-beta-test-11032) on iPhone 13 Mobile device and here is my observation: 1. Installed sil_ipa keyboard. 2. Verified that switching between keyboards using the globe key is working fine. 3. Longpress menu options are working as expected. 4. Shift layer and Symbol layer are working as expected. 5. Tested the same in iPad (10th generation) Simulator and it works fine.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS: Run these tests in Keyman for iPhone and iPad

* **TEST_BACKSPACE (PASSED):** 1. Entered some texts on the Notes app then pressing the backspace key deletes the characters one by one. Verified that the backspace key functionality is working as expected. 2. Tested the same in iPad (10th generation) Simulator and it is working fine.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS: Run these tests in Keyman for iPhone and iPad

* **TEST_CONTEXT_SYNC (PASSED):** Tested with the attached PR build (17.0.292-beta-test-11032) on iPhone 13 Mobile device and here is my observation: 1. Opened https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/451458:id/src/test/manual/web/unminified.html test page in the Chrome browser. 2. Run the web_context_tests keyboard on the test page. 3. Verified that the context changes were correctly synchronized between the the app and keymanweb. 4. Tested this in iPad (10th generation) simulator, and it works fine. Did I miss any other test related to context_sync? Please let me know. Thank you.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS: Run these tests in Keyman for iPhone and iPad

* **TEST_SELECTION_DELETION (PASSED):** Tested with the attached PR build (17.0.292-beta-test-11032) on iPhone 13 Mobile device and here is my observation: 1. Typed two words on the Notes app. 2. Selected the second word. 3. Pressed the backspace key on the OSK and verified that it deletes the selected word. 4. Tested the same on iPad (10 generation) Simulator and it is working fine.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS: Run these tests in Keyman for iPhone and iPad

* **TEST_SELECTION_REPLACEMENT (PASSED):** Tested with the attached PR build (17.0.292-beta-test-11032) on iPhone 13 Mobile device and here is my observation: 1. Typed two words on the Notes app. 2. Selected the second word. 3. Typed a letter on the touch keyboard to replace it. Verified the selected word is deleted and new letter is left in its place. 4. Tested the same on iPad (10 generation) Simulator and it is working fine.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS: Run these tests in Keyman for iPhone and iPad

* **TEST_SELECTION_LAYER_SWITCH (PASSED):** Tested with the attached PR build (17.0.292-beta-test-11032) on iPhone 13 Mobile device and here is my observation: 1. Typed two words on the Notes app. 2. Selected the second word. 3. Pressed the '123' number key and layer changed to another layer. Pressed the Symbol key and the the layer changed to the Symbol layer. Verified that the selected word didn't change. 4. Tested the same on the iPad (10 generation) Simulator and it is working fine.

**Comment by mcdurdin** [comment]
> * **TEST_CONTEXT_SYNC (PASSED):** Tested with the attached PR build (17.0.292-beta-test-11032) on iPhone 13 Mobile device and here is my observation: 1. Opened https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/451458:id/src/test/manual/web/unminified.html test page in the Chrome browser. 2. Run the web_context_tests keyboard on the test page. 3. Verified that the context changes were correctly synchronized between the the app and keymanweb. 4. Tested this in iPad (10th generation) simulator, and it works fine. Did I miss any other test related to context_sync? Please let me know. Thank you.

My apologies, that test was very badly specified by me. I was going to rewrite it and then I missed it. I have rewritten the test, which should be run with the app -- not with KeymanWeb!

@keymanapp-test-bot retest group_ios TEST_CONTEXT_SYNC

**Comment by bharanidharanj** [comment]
> > * **TEST_CONTEXT_SYNC (PASSED):** Tested with the attached PR build (17.0.292-beta-test-11032) on iPhone 13 Mobile device and here is my observation: 1. Opened https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/451458:id/src/test/manual/web/unminified.html test page in the Chrome browser. 2. Run the web_context_tests keyboard on the test page. 3. Verified that the context changes were correctly synchronized between the the app and keymanweb. 4. Tested this in iPad (10th generation) simulator, and it works fine. Did I miss any other test related to context_sync? Please let me know. Thank you.
> 
> My apologies, that test was very badly specified by me. I was going to rewrite it and then I missed it. I have rewritten the test, which should be run with the app -- not with KeymanWeb!
> 
> @keymanapp-test-bot retest group_ios TEST_CONTEXT_SYNC

@mcdurdin Thanks for the clarification!

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS: Run these tests in Keyman for iPhone and iPad

* **TEST_CONTEXT_SYNC (PASSED):** Retested with the updated instructions and here is my observation: 1. Installed Khmer Angkor keyboard. Switched to a Khmer Angkor keyboard. Typed ខ េ.  2. Clicked the number / symbol layer then returned to the default layer. 3. Selected ្ from the long-press menu. 4. Pressed the Backspace key and verified that the output showed  ខ្  on the Screen.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_ANDROID: Run these tests in Keyman for Android

* **TEST_BASIC_INPUT (PASSED):** Tested with the attached PR build (17.0.292-beta-test-11032) on an Android 13 Mobile device and here is my observation: 1. Installed sil_ipa keyboard. 2. Verified that switching between keyboards using the globe key is working fine. 3. Longpress menu options are working as expected. 4. Shift layer and Symbol layer are working as expected. 5. Tested the same in iPad (10th generation) Simulator and it works fine.

* **TEST_BACKSPACE (PASSED):** 1. Entered some texts on the text input screen then pressing the backspace key, deletes the characters one by one. Verified that the backspace key functionality is working as expected. 

* **TEST_CONTEXT_SYNC (PASSED):** 1. Installed Khmer Angkor keyboard. Switched to a Khmer Angkor keyboard. Typed ខ េ. 2. Clicked the number / symbol layer then returned to the default layer. 3. Selected ្ from the long-press menu. 4. Pressed the Backspace key and verified that the output showed ខ្ on the Screen.

   

* **TEST_SELECTION_DELETION (PASSED):** Tested with the attached PR build (17.0.292-beta-test-11032) on an Android Mobile device and here is my observation: 1. Typed two words on the text input screen. 2. Selected the second word. 3. Pressed the backspace key on the OSK and verified that it deletes the selected word. 

* **TEST_SELECTION_REPLACEMENT (PASSED):** Tested with the attached PR build (17.0.292-beta-test-11032) on an Android 13 mobile device and here is my observation: 1. Typed two words on the text input screen. 2. Selected the second word. 3. Typed a letter on the touch keyboard to replace it. Verified the selected word is deleted and new letter is left in its place.

* **TEST_SELECTION_LAYER_SWITCH (PASSED):** Tested with the attached PR build (17.0.292-beta-test-11032) on an Android 13 Mobile device and here is my observation: 1. Typed two words on the text input screen. 2. Selected the second word. 3. Pressed the '123' number key and layer changed to another layer. Pressed the Symbol key and the the layer changed to the Symbol layer. Verified that the selected word didn't change.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.298-beta](https://keyman.com/downloads/releases/beta/17.0.298)
