### PR TITLE
[Windows] Upgrades from 11.0 and 12.0 were losing installed keyboards and settings.

### LINKED ISSUE #2074: [Windows] Keyboards missing after Keyman 11 update
Reported from a user via email. I'll add more configuration details as they come in to aid in reproducing the issue:

-----------------------
June 6, 2019 I re-installed Windows OS and downloaded the new version of Keyman at that time. Not sure if it was updated since then.

Today (Sept 11, 2019) I installed  the Keyman v11.0.1361.0 update and my keyboards have changed. Actually, when I noticed this, I restarted my system and the keyboards changed again! Here's what I've observed:

Before updating Keyman these are the keyboards I had installed (from what I recall):
* English
* Khmer (I think I had Khmer Angkor installed)
* Ancient Greek
* [SIL Hebrew](https://software.sil.org/ezra)

After updating to Keyman v11.0.1361.0:

* English
* Khmer NIDA
* Ancient Greek
 
After restarting once:
* English
* Ancient Greek
 
After restarting a second time (I haven't tried a third time ;-):
* English
* Khmer NIDA
* Ancient Greek
 
Also, since updating the software, whenever I open the Keyman Configuration window there are no keyboards listed in the Keyboard layouts tab (see attached screenshot and notice that the small Keyman menu does list some keyboards. I haven't tried reinstalling any keyboards yet. 

One more thing, after updating Keyman I noticed that Automatically save screen shots to OneDrive wasn't working. It still didn't work after restarting my computer once. I reapplied the setting in OneDrive settings and now it is working. Both Keyman and OneDrive are located in the System Tray…could there be some connection?

Keyman layouts issue

FYI, the Greek Keyman keyboard I use is called Greek Polytonic Unicode

### LINKED ISSUE #2207: [Windows] Update to 12.0.51.0 wiped installed keyboards
**Describe the bug**
Updating to 12.0.51.0 wiped my installed keyboards.

**To Reproduce**
I'm not sure I could replicate it. This happened on a fresh install of Keyman 12, on a new computer that I've had since last week. The update notice popped up automatically, I clicked it, and the next thing I know I've got the keyman start-up screen telling me I have no installed keyboards.

I'd be happy to dig for any supporting information to clarify what went wrong.

---

(Delete the irrelevant sections)

**Keyman Desktop, 
 - OS: Windows 10  1903
 - Keyman version: 12.0.51.0

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #2207.
Fixes #2074.

 (#2074 is a little ambiguous but most likely the same issue)

 This replaces #2212 as it addresses the root issue far more cleanly.

 The one downside is that the msi is slightly less self-contained for upgrades from 7,8,9,10, but the reality is that ship sailed many moons ago. The major version upgrades up until 11.0 relied on setup for transferring data between registry keys anyway. So we haven't actually lost anything.

 Going forward, this actually reduces our reliance on setup.exe as the .msi can do a major upgrade for any 11.0+ version without external transforms. This is a good thing :)

 The one technology that I have struggled with more than anything else is Windows Installer. Years and years worth of struggle. I think the hardest part is having to guess the future when building an installer -- and the myriad of possible configurations, only one of which is actually correct. If you do have a problem in an earlier version of the deployment, it's really, really hard to sort it out in an upgrade. WiX tries has to simplify things but the underlying technology is so overly complicated that it's really just wallpaper on top of the mess.

 I kinda wish we'd never gone Windows Installer, but there are definitely certain benefits to using it ... :(

### CODE REVIEW

**Comment by mcdurdin** [comment]
Once this lands, I will re-run tests on the alpha 13.0 release before cherry-picking to 12.0 stable.

File: windows/src/desktop/setup/RunTools.pas [hunk 1]
```diff
@@ -610,8 +611,26 @@ function TRunTools.InstallMSI: Boolean;
...
-      then ReinstallMode := ReinstallMode + ' REINSTALLMODE=vomus REINSTALL=ALL';
+    if (FInstalledVersion.Version <> '') and (FInstalledVersion.ProductCode = FInstallerVersion.ProductCode) then
+    begin
+      ReinstallMode := ReinstallMode + ' REINSTALLMODE=vomus REINSTALL=ALL';
+    end
+    else
+    begin
+      Status('Removing older versions');
+      // Remove older versions of Keyman now. We'll still get the upgrade desired
+      // because we've backed up the relevant keys for reapplication post-install
```
Comment (darcywong00) [inline windows/src/desktop/setup/RunTools.pas]: From your PR description, it sounds like this check only needs to be done for upgrading from: Keyman 7, 8, 9, 10.

Maybe add a comment for future maintenance so this list won't need to be continually updated.

**Comment by mcdurdin** [comment]
Also #1864 is related but not addressed by this update.

I have now tested this update with 13.0.18 build and Keyman upgrades cleanly with keyboards preserved in all install and upgrade scenarios that I can find.
