### PR TITLE
fix(web): Fix layers for embedded longpress keys

### LINKED ISSUE #5610: bug(android): longpress keys on shift layer aren't applying specified layer
**Describe the bug**

All long press keys on the Shift layer of [sil_madi](https://keyman.com/keyboards/sil_madi?bcp47=mhi) keyboard do not work as expected. They do not output the character shown on the keycap on Android physical device.

**Screenshots**

Chrome emulator using the build off of my computer: 

Chrome emulator using the keymanweb version:

---

**Keyman for Android:**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - Keyman version: 14.0.280
 - Target application: Keyman app

**KeymanWeb:**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - KeymanWeb Version: ?
 - URL: https://keymanweb.com/?_ga=2.74887638.575662518.1629422514-576725948.1623116260#mhi,Keyboard_sil_madi

---

**Keyboard**
 - Keyboard name: sil_madi
 - Keyboard version: 1.0
 - Language name: Madi

### PR DESCRIPTION
**Pull request by darcywong00**
Follow-on to #5351 and fixes #5610

Some longpress keys on the shift layer weren't working on Keyman for Android (e.g. sil_madi).
This fixes how the "functional" layer and "display" layers are determined in kmwembedded.ts.

This fills out `kLayer` and `kbdLayer` so it matches what KeymanWeb on desktop uses
longpress a

The keyboards seem to work in 15.0 (`master`) so maybe don't need to 🍒 pick?

## User Testing
<details><summary>Setup</summary>
1.  Install the test build
2.  Install sil_madi and sil_cameroon_qwerty keyboards
</details>

* **TEST_MADI:** Longpress on shift layer
1. Change the keyboard to sil_madi
2. On the default layer, longpress on a vowel and select it
3. Verify the correct character is output
4. Press <kbd>Shift</kbd> to switch to the "Shift" layer
5. Longpress on the <kbd>A</kbd> and select one of the caps longpresses.
6. Verify the correct character is output

* **TEST_NEXT_LAYER:** Test application of nextlayer
<detail>These steps are based on  #5351</detail>
1. Change the keyboard to sil_cameroon_qwerty
2. Press <kbd>Shift</kbd> to switch to the "Shift" layer
3. Longpress on the <kbd>W</kbd> or <kbd>E</kbd> keys and select one of the caps longpresses
4. Verify the correct character is output
5. Verify the keyboard switches to the to the default layer
6. Press <kbd>Shift</kbd> to switch to the "Shift" layer
7. Press the spacebar
8. Verify the layer remains on "Shift"
9. For each of the following:
    * switch to the symbolic layer
    * longpress on the base key and select any of the longpress keys
    * verify the correct character is output
    * verify the keyboard **switches** to the default layer
    **Base Key**
    <kbd><<</kbd> 
    <kbd>>></kbd> 
    <kbd>'</kbd> (single quote)
    <kbd>"</kbd> (double quote)
10. For each of the following:
    * switch to the symbolic layer
    * longpress on the base key and select any of the longpress keys
    * verify the correct character is output
    * verify the keyboard **remains** on the symbolic layer
    **Base Key**
    <kbd>(</kbd> 
    <kbd>)</kbd> 
    <kbd>?</kbd> (Note, the basekey <kbd>?</kbd> will switch to the default layer
    <kbd>!</kbd> (Note, the basekey <kbd>!</kbd> will switch to the default layer

As only subkeys are affected, testing with other keyboards that utilize subkeys isn't a bad idea. Try with sil_bunong since that was also reported in the issue

### CODE REVIEW

File: web/source/kmwembedded.ts [hunk 1]
```diff
@@ -374,18 +374,25 @@ namespace com.keyman.text {
...
         keyName = keyName.substring(separatorIndex+1);
       }
-      if(layer == 'undefined') {
-        layer=core.keyboardProcessor.layerId;
+      if(displayLayer == 'undefined') {
+        displayLayer=core.keyboardProcessor.layerId;
+      }
+
+      // Determine the "functional" layer
+      let layer = 'default';
```
Comment (jahorton) [inline web/source/kmwembedded.ts:392]:
```suggestion
      let layer = displayLayer;
```

**Review by jahorton — CHANGES_REQUESTED** [review]
Mostly fine, but there's one very important detail that I believe is off.

If things break with the suggestion in place, I believe that's indicative of further problems that may need investigation.

**Comment by jahorton** [comment]
Oh!  Also, some other unit testing ideas - use `sil_cameroon_qwerty`.

I strongly recommend revisiting the tests for that keyboard specified under #5387.  (Alas, that _is_ before we started using the new test-spec format.)  Note the mentioned symbolic layer keys.

While I can't point to a specific example right away without analyzing that keyboard more thoroughly, there is likely a rule in there somewhere that could be affected and that would be wise to test.

File: web/source/kmwembedded.ts (hunk 1 above)
Comment (jahorton) [reply web/source/kmwembedded.ts:392]: Relevant code for the non-embedded representation:

https://github.com/keymanapp/keyman/blob/7db9477f85c8dee3585477e2ecf4e68c5028a4fd/web/source/osk/browser/subkeyPopup.ts#L93-L102

`vkbd.layerId` matches `displayLayer` in purpose.

**Comment by MakaraSok** [comment]
- **TEST_MADI: PASSED** _The long press keys on both default and shift layers output the expected character without any issue._
- **TEST_NEXT_LAYER: PASSED** _Long press keys on both default and shift layers of `sil_madi`, `sil_cameroon_qwerty`, `khmer_angkor` and `sil_bunong` do output the expected characters._

**Review by jahorton — APPROVED** [review]

**Comment by darcywong00** [comment]
> The keyboards seem to work in 15.0 (master) so maybe don't need to 🍒 pick

@jahorton - Last question. Is the OSK refactoring in 15.0 why the keyboards work?

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.281](https://keyman.com/downloads/releases/stable/14.0.281)
