### PR TITLE
[iOS 11.0] Patches issue with LTR/RTL codepoints in context.

### LINKED ISSUE #1212: [iOS] nul and context can interact incorrectly at start of document with system keyboard
The following keyboard goes wrong in iOS when using the system keyboard, at and only at the start of a document. It does not go wrong in the Keyman app or on Android.

Both the `context` rule and the `nul` rule are relevant to the issue. Spider senses suggest that the `context` statement is the root cause but investigation needed.

This issue was reported at https://community.software.sil.org/t/ios-keyboard/1311

```
c Keystrokes:
c Q W E
c
c Expected result:
c 123
c 
c FAIL: In iOS system keyboard, QWE at start of document gives 1XXXX
c In iOS app, E at start of document gives XXXX, as expected
c In iOS app, QWE at start of document gives 123, as expected 
c Every other context in iOS appears to be fine
c Every context in web appears to be fine
c In Android app,  everything appears to be fine
c In Android system keyboard, everything appears to be fine

store(&VERSION) '10.0'
store(&TARGETS) 'any'
store(&NAME) 'nul and context bug'
store(&LAYOUTFILE) 'nul_context_ios_bug.keyman-touch-layout'
begin Unicode > use(main) 

c Main Program
group(main) using keys

+ [K_Q] > '1'
'1' + [K_W] > context '2'
+ [K_E] > '3'
nul + [K_E] > 'XXXX'
```

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #1212. (11.0 stable)

A cherry-picked version of #1756.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/150934:id/kvk/index.html)

File: ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift [hunk 1]
```diff
@@ -411,24 +430,35 @@ open class InputViewController: UIInputViewController, KeymanWebDelegate {
...
-  func setText(_ text: String?) {
-    keymanWeb.setText(text)
-  }
-  
+
   func clearText() {
-    setText(nil)
-    setSelectionRange(NSRange(location: 0, length: 0), manually: true)
+    setContextState(text: nil, range: NSRange(location: 0, length: 0))
     log.info("Cleared text.")
```
Comment (darcywong00) [inline ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift]: How come you don't call `keymanWeb.resetContext()` like you do in #1756?
```
func clearText() {
  setContextState(text: nil, range: NSRange(location: 0, length: 0))
  keymanWeb.resetContext()
  log.info("Cleared text.")
}
```

Comment (jahorton) [reply ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift]: That one's a result of merging in #1764, which needed to be based on this PR's original (alpha-targeted) version.  If we want, I could probably duplicate that work here with no ill effect, but it's a fix for a predictive text issue.
