### PR TITLE
fix(android): Remove sendOptionsToKeyboard function from Engine API

### LINKED ISSUE #13165: chore(android): remove sendOptionsToKeyboard() function from 18.0 Keyman Engine API
Per discussion at https://github.com/keymanapp/help.keyman.com/pull/1500#discussion_r1730783852, this API should not be necessary and should not be exposed to Keyman Engine API users -- it should be the responsibility of Keyman Engine to send options onto the keyboard at the right time.

This needs to be addressed prior to 18.0 stable release

### PR DESCRIPTION
**Pull request by darcywong00**
Follows #12170 and #12185 re: new menu to adjust the longpress delay
Fixes #13165 

Removes `sendOptionsToKeyboard()` from 18.0 Keyman Engine APi so Keyman Engine handles the responsibility to send the longpress delay value to KeymanWeb.

android-host.js now caches the longpress value, so the call can now work before the keyboard is loaded.

## User Testing
**Setup** - Install the PR build of Keyman for Android. Set and enable Keyman as the default system keyboard.
When the tests ask to adjust the longpress delay value, in Keyman app, go to Settings --> Adjust longpress delay --> 
adjust the slider to the specified time and exit the menu with the back button on the menu

* **TEST_ADJUST_DELAY_MENU** - Verifies the longpress delay value can be adjusted and applied
1. Launch Keyman and dismiss the "Get Started" menu
2. Longpress on the default keyboard and observe the duration to trigger the longpress keys (default 0.5 seconds).
3. Adjust the longpress delay to the maximum 1.5 seconds and return the Keyman app
4. Longpress on the default keyboard and verify longpress keys take 1.5 seconds to trigger.
5. Open a separate app (Chrome browser) and select a text area
6. With Keyman as the system keyboard, longpress on the keyboard and verify longpress keys take 1.5 seconds to trigger.
7. Return to the Keyman app
8. Adjust the longpress delay to the minimum 0.3 seconds and return to the Keyman app
9. Longpress on the default keyboard and verify longpress keys take 0.3 seconds to trigger.
10. Open a separate app (Chrome browser) and select a text area
11. With Keyman as the system keyboard, longpress on the keyboard and verify longpress keys take 0.3 seconds to trigger.

* **TEST_INITIAL_LONGPRESS** - Verifies the stored longpress value is restored when Keyman restarts
1. Launch Keyman and dismiss the "Get Started" menu
2. Adjust the longpress delay to 1.5 seconds and return to the Keyman app
3. Close Keyman and restart
4. When Keyman app returns, longpress on the default keyboard and verify longpress keys take 1.5 seconds to trigger.
5. Open a separate app (Chrome browser) and select text area
6. With Keyman as the system keyboard, longpress on the keyboard and verify longpress keys take 1.5 seconds to trigger.

### CODE REVIEW

File: android/KMEA/app/src/main/assets/android-host.js [hunk 1]
```diff
@@ -128,7 +133,8 @@ function notifyHost(event, params) {
 // Update the KeymanWeb longpress delay
 // delay is in milliseconds
 function setLongpressDelay(delay) {
-  if (keyman.osk) {
+  longpressDelay = delay;
+  if (keyman && keyman.osk) {
     keyman.osk.gestureParams.longpress.waitLength = delay;
     console_debug('setLongpressDelay('+delay+')');
   } else {
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/assets/android-host.js:140]: This `else` clause is not really needed because we have the pre-init and post-init pathways defined

**Review by mcdurdin — APPROVED** [review]
LGTM

**Comment by mcdurdin** [comment]
Don't forget to update documentation

**Comment by dinakaranr** [comment]
# Test Results
I tested this issue with the attached keyman"18.0.192-beta-test-13219" build(13/02/2025) on Android 14(Samsung A23 Physical device). Here is my observation.

* **TEST_ADJUST_DELAY_MENU (Passed):**
1. Install the keyman-18.0.192.apk file.
2. Launch Keyman and dismiss the "Get Started" menu.
3. Longpress on the default keyboard.
4. Longpress on the "H". submenu keys appear within(default 0.5 seconds).
5. Verified the duration to trigger the long-press keys(default 0.5 seconds).
6. Adjust the long-press delay to a maximum of 1.5 seconds and return the Keyman app.
7. Longpress on the "G". submenu keys appear within(default 1.5 seconds).
8. Longpress on the default keyboard. submenu keys appears within(default 1.5 seconds). 
9. Verified the longpress keys take 1.5 seconds to trigger.
10. Open a separate app (Chrome browser or Keep app) and select a text area
11. Set the Keyman as the system keyboard.
12. Longpress on the keyboard. 
13. Longpress on the "J". submenu keys appear within(default 1.5 seconds).
14. Verified that the longpress keys take 1.5 seconds to trigger. (default 1.5 seconds). 
15. Return to the Keyman app.
16. Adjust the longpress delay to a minimum 0.3 seconds and return to the Keyman app
17. Longpress on the default keyboard 
18. Longpress on the "S". submenu keys appear within(default 0.3 seconds).
19. Verified that the long-press keys take 0.3 seconds to trigger.
20. Open a separate app (Chrome browser or Keep app) and select a text area.
21. Set Keyman as the system keyboard.
22. Longpress on the keyboard.
23. Longpress on the "A". submenu keys to appear within(default 0.3 seconds).
24. Verified that the longpress keys take 0.3 seconds to trigger.
It works well. Thank you.

* **TEST_INITIAL_LONGPRESS (Passed):**
1. Install the keyman-18.0.192.apk file.
2. Launch Keyman and dismiss the "Get Started" menu
3. Adjust the longpress delay to 1.5 seconds.
4. Return to the Keyman app
5. Close Keyman and restart
6. Open Keyman app returns.
7. Longpress on the default keyboard.
8. Longpress on the "S". submenu keys appear within(default 1.5 seconds).
9. Verified that the longpress keys take 1.5 seconds to trigger.
10. Open a separate app (Chrome browser or Keep app) and select the text area
11. Set Keyman as the system keyboard.
12. Longpress on the keyboard 
13. Longpress on the "L". submenu keys appear within(default 1.5 seconds).
14. Verified that the longpress keys take 1.5 seconds to trigger.
It works well. Thank you.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 18.0.193-beta](https://keyman.com/downloads/releases/beta/18.0.193)
