### PR TITLE
fix(android/engine): Don't load woff fonts on Android N

### LINKED ISSUE #4896: bug(android): Font not found - wookianos.woff
Sentry Issue: [KEYMAN-ANDROID-VR](https://sentry.keyman.com/organizations/keyman/issues/4867/?referrer=github_integration)

```
RuntimeException: Font not found /data/user/0/com.tavultesoft.kmapro/app_data/cloud/wookianos.woff
    at android.graphics.Typeface.createFromFile(Typeface.java:330)
    at android.graphics.Typeface.createFromFile(Typeface.java:313)
    at com.tavultesoft.kmea.KMManager.getFontTypeface(KMManager.java:1020)
    at com.tavultesoft.kmea.KMKeyboard.showSubKeys(KMKeyboard.java:943)
    at com.tavultesoft.kmea.KMKeyboard.access$400(KMKeyboard.java:62)
...
(10 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #4896 where loading .woff fonts on Android N (7.0 / 7.1) devices throws runtimeexceptions

Reference from SO
https://stackoverflow.com/questions/42342572/android-runtime-exception-font-asset-not-found-for-woff-font-files-in-android

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java [hunk 1]
```diff
@@ -1015,6 +1015,13 @@ public static Typeface getFontTypeface(Context context, String fontFilename) {
 
     try {
       if ((fontFilename != null) && FileUtils.hasFontExtension(fontFilename)) {
+        // Ignore .woff files if Android 7.0 / 7.1 (Issue #4896)
+        if ((Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) &&
+            (Build.VERSION.SDK_INT <= Build.VERSION_CODES.N_MR1) &&
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java:1020]: https://developer.android.com/guide/topics/resources/font-resource suggests WOFF is not supported in any recent version? Have you tested on 8.0 plus?

Some Android bug reports:
* https://issuetracker.google.com/issues/62842880
* https://issuetracker.google.com/issues/37136340

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java [hunk 2]
```diff
@@ -1015,6 +1015,13 @@ public static Typeface getFontTypeface(Context context, String fontFilename) {
...
+            fontFilename.toLowerCase().endsWith(FileUtils.WOFFFONT)) {
+          return font;
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java:1022]: I'd prefer `return null;` here to be clear as this is a precondition.

In some ways, I'd prefer to eliminate the `font` variable altogether and simply `return Typeface.createFromFile(file)` on line 1027, with the last line of the method being `return null;` for the error case. I think that is clearer.

**Review by mcdurdin — APPROVED** [review]

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java (hunk 1 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMManager.java:1020]: Yes, I also ran emulator with API 29 (Android 10.0) and the woff loaded fine.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.31-alpha](https://keyman.com/downloads/releases/alpha/15.0.31)
