### PR TITLE
fix(android/engine): Update InApp input connection 🛋

### LINKED ISSUE #8639: bug(android): Keyboard is not working after changing the Display Language
### Describe the bug

I noticed that after changing the UI language, the Keyboard is not at all working in the Keyman In-App

### Reproduce the bug

1. Install Keyman 17.0.90-alpha  build Android Mobile / emulator.
2. Open Keyman In-App.
3. Type a word (eg., Testing) in the text input screen. 
4. We may notice that the typed word appears on the screen. 
5. Change the Display Language into Amharic. 
6. Revert to Home Screen. 
7. Type a word (eg., testing) in the text input screen. 

Here, I noticed that the text is not appearing on the screen. Even, changing the UI into English does not help. 

Seems to be an issue. 

   

..

### Expected behavior

Keyboard should work after changing the display language. 

### Related issues

_No response_

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

18.0.90-alpha

### Operating system

Android 5.0, 9.0, 12.0

### Device

API 21, 28 and 31  Android Emulator

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes  #8639 and maybe fixes/addresses #8548 too  (part of #7881 refactoring)

Regression introduced in #8483 

It turns out the Keyman app is recreated when changing the Display Language. So we can't reuse the inappInputConnection handle.

## User Testing
Setup - Install PR build of Keyman for Android

* **TEST_CHANGING_DISPLAY_LANGUAGE** - Verifies inapp keyboard works after changing display language
1. Open Keyman In-App.
2. Type a word (eg., Testing) in the text input screen.
3. We may notice that the typed word appears on the screen.
4. Change the Display Language into Amharic.
6. Revert to Home Screen.
7. Type a word (eg., testing) in the text input screen.
8. Verify typed text appears

* **TEST_SETTING_SYSTEM_KETYBOARD** -  Verifies inapp keyboard works after setting Keyman as system keyboard
1. Install the PR build of Keyman for Android in an Android Mobile / emulator. 
2. Set the sil_eurolatin keyboard as the system wide and default keyboard. 
3. Type some texts in the Keyman In-app. We may able to see the typed text in the text area. 
4. Close the application. 
5. Open Chrome browser. 
6. Click the Search field in the chrome browser. 
7. Verify that the Keyman Keyboard (sil_eurolatin) appears on the screen. 
8. Type some texts using the system keyboard. 
9. Close the browser. 
10. Open Keyman In-App. 
11. Type some text. 
12. Verify typed text appears
 
(edit) Per review comments, adding two tests from #8611 below
* **TEST_UNDO_SUGGESTION** - Verifies backspace after a suggestion works (suggestion reverts to context)
1. Launch Keyman for Android
2. From Keyman settings --> Change the Display Language into Khmer.
3. With the sil_euro_latin keyboard, type "prob"
4. Select "problem" from the suggestion banner
5. Press <kbd>Backspace</kbd> key
6. Verify "prob" is now the left suggestion (the context before accepting the suggestion)
7. Select "prob" from the suggestion banner
8. Verify the text changes from "problem" to "prob"

* **TEST_REPLACE_SELECTION_DEADKEYS** - Verifies keyboard replaces selected text and handles deadkeys
1. Launch Keyman for Android
2. From Keyman Settings --> Install the Basic French (basic_kbdfr) keyboard
3. From Keyman Settings --> Change the Display Language to Hausa.
4. In Keyman with the sil_euro_latin keyboard, type "the quick brown fox"
5. Select the letters "row" within the word "brown". (keyboard switches to shift layer)
6. Type "H"
7. Verify the text changes from "brown" to "bHn"
8. Select the letters "ick" within the word "quick"
9. Press <kbd>backspace</kbd> key
10. Verify the text changes from "quick" to "qu"
11. Select the letter "o" within the word "fox"
12. Press <kbd>enter</kbd> key
13. verify the word changes from "fox" to "f" followed by "x" on the next line
14. Use the Keyman globe key to switch to the basic_kbdfr keyboard
15. Press the green </kbd>^</kbd>
16. Verify nothing is output (it's a deadkey)
17. Press a vowel
18. Verify the vowel with the combined diacritic is output

### CODE REVIEW

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_CHANGING_DISPLAY_LANGUAGE (PASSED):** Tested with the attached PR build (17.0.92-alpha-test-8647) in Android 12 / API 31 emulator and here is my observation: The Keyboard is working properly, after changing the Display language into Amharic (or any other languages). Seems to be working as expected.  

* **TEST_SETTING_SYSTEM_KETYBOARD (PASSED):** In-app keyboard is working properly, after setting Keyman as the System keyboard. Seems to be working fine.

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java [hunk 1]
```diff
@@ -461,16 +460,12 @@ public static void setInputMethodService(InputMethodService service) {
...
    * @param {KeyboardType} keyboard
    * @return InputConnection
    */
   protected static InputConnection getInputConnection(KeyboardType keyboard) {
     if (keyboard == KeyboardType.KEYBOARD_TYPE_INAPP) {
-      if (inappInputConnection == null) {
-        inappInputConnection = KMTextView.activeView.onCreateInputConnection(new EditorInfo());
-      }
-      return inappInputConnection;
+      return KMTextView.activeView.onCreateInputConnection(new EditorInfo());
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:468]: Is this going to potentially cause other problems with losing context in some apps? `onCreateInputConnection()` was not used anywhere in stable-16.0 that I can see, so this is  a new API usage?

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:468]: This was introduced in #8438 

> Convert's KMKeyboardJSHandler.insertText from an abstract method to strictly using SystemKeyboard's copy of `insertText`. ~I anticipated having to add more logic between the two, but the InApp Keyboard seems to still work.~
> (edit) - It turns out I had to add new code to get the InputConnection for InAppKeyboard.

This should only impact the Keyman app.

Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:468]: OK. Do we need to run new user tests to verify that we won't lose e.g. deadkey state?

**Review by mcdurdin — APPROVED** [review]
LGTM assuming this doesn't break context caching :grin:

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java (hunk 1 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:468]: Yeah I can add the tests from #8611... Will try locally first.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_UNDO_SUGGESTION (PASSED):** Tested with the attached PR build (Keyman 17.0.92-alpha-test-8647) in Android 12 / API 31 emulator and here is my observation: 1. Verified that 'Prob' appears on the suggestion bar after pressing the Backspace key. 2. Selecting "Prob" from the suggestion banner shows "Prob" on the text input screen.

   


* **TEST_REPLACE_SELECTION_DEADKEYS (PASSED):**  Tested this per the instructions with the attached PR build (Keyman 17.0.92-alpha-test-8647) in Android 12 / API 31 emulator and here is my observation: 1. Changed the Display language into Hausa. Verified that the text changes from "brown" to "bHn". 2. Verified that the text changes from "quick" to "qu" after pressing the backspace key. 3. Verified that the word changes from "fox" to "f" followed by "x" on the next line. 4. Switched to French Basic keyboard. Verified that pressing the green ^ key outputs nothing on the input text screen. Pressing a vowel 'a' shows the combined diacritic on the screen. Seems to be working as expected.
