### PR TITLE
fix(ios): changed build script prepRelease to fix sample builds 🏠

### LINKED ISSUE #10844: bug(ios): sample keyboard apps do not build according to instructions
### Describe the bug

Following the [sample keyboard app build instructions](https://help.keyman.com/developer/engine/iphone-and-ipad/current-version/guides/in-app/) results in build errors: 'There is no XCFramework found'

### Related issues

possibly related to #9674, though there are differences for Keyman 16 and 17

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16

### Operating system

ios

### PR DESCRIPTION
**Pull request by sgschantz**
Changed the script responsible for creating the ios sample app zip file so that the sample apps will find their frameworks and build successfully.

fixes #10844 

@keymanapp-test-bot skip

### CODE REVIEW

File: ios/tools/prepRelease.sh [hunk 1]
```diff
@@ -56,27 +56,56 @@ LC_ALL=UTF-8 sed -e "s/[$(printf $emoji)]//g" < "$CHANGELOG_PATH" > "$CHANGELOG_
...
 
-KMEI_DST_NAME="keyman-engine-ios-${BUILD_NUMBER}.zip"
-KMEI_DST="${WORK_DIR}/${UPLOAD_DIR}/${KMEI_DST_NAME}"
+CARTHAGE_DIR="Carthage"
+KEYMAN_FRAMEWORKS="Carthage/Build/"
+#KEYMAN_FRAMEWORK_BASE="Carthage"
 
-KMEI_FRAMEWORK_BASE="build/Build/Products/Release/"
-FRAMEWORK="KeymanEngine.xcframework"
+cd $UPLOAD_DIR
```
Comment (mcdurdin) [inline ios/tools/prepRelease.sh:70]:
```suggestion
cd "$UPLOAD_DIR"
```

Here and elsewhere, always quote variables to avoid space tragedies

File: ios/tools/prepRelease.sh [hunk 2]
```diff
@@ -56,27 +56,56 @@ LC_ALL=UTF-8 sed -e "s/[$(printf $emoji)]//g" < "$CHANGELOG_PATH" > "$CHANGELOG_
...
+mkdir -p "${CARTHAGE_DIR}"
+
+cd $WORK_DIR
+echo "Copying frameworks into ${CARTHAGE_DIR} and adding to zip file..."
+cp -rf "${KEYMAN_FRAMEWORKS}" "${UPLOAD_DIR}/${CARTHAGE_DIR}"
+zip -qrX ${KMEI_DST} "${KEYMAN_FRAMEWORKS}"
```
Comment (mcdurdin) [inline ios/tools/prepRelease.sh:76]:
```suggestion
cd "$WORK_DIR"
echo "Copying frameworks into ${CARTHAGE_DIR} and adding to zip file..."
cp -rf "${KEYMAN_FRAMEWORKS}" "${UPLOAD_DIR}/${CARTHAGE_DIR}"
zip -qrX "${KMEI_DST}" "${KEYMAN_FRAMEWORKS}"
```

File: ios/tools/prepRelease.sh [hunk 3]
```diff
@@ -56,27 +56,56 @@ LC_ALL=UTF-8 sed -e "s/[$(printf $emoji)]//g" < "$CHANGELOG_PATH" > "$CHANGELOG_
...
 echo "engine dest: $KMEI_DST"
 
-echo "Zipping ${UNI_FRAMEWORK} => ${UPLOAD_DIR}/${KMEI_DST}..."
-cd "${KMEI_FRAMEWORK_BASE}"
-zip -qrX ${KMEI_DST} ${FRAMEWORK}
+echo "Copying ${UNI_FRAMEWORK} => ${UPLOAD_DIR}/samples..."
 cd $WORK_DIR
+cp -rf "${KMEI_FRAMEWORK_BASE}/${KEYMAN_ENGINE_FRAMEWORK}" "${UPLOAD_DIR}/samples/KMSample1/"
+cp -rf "${KMEI_FRAMEWORK_BASE}/${KEYMAN_ENGINE_FRAMEWORK}" "${UPLOAD_DIR}/samples/KMSample2/"
+#zip -qrX ${KMEI_DST} ${FRAMEWORK}
```
Comment (mcdurdin) [inline ios/tools/prepRelease.sh:104]:
```suggestion
```

File: ios/tools/prepRelease.sh [hunk 4]
```diff
@@ -56,27 +56,56 @@ LC_ALL=UTF-8 sed -e "s/[$(printf $emoji)]//g" < "$CHANGELOG_PATH" > "$CHANGELOG_
...
+cd $UPLOAD_DIR
+mkdir -p "${CARTHAGE_DIR}"
+
+cd $WORK_DIR
+echo "Copying frameworks into ${CARTHAGE_DIR} and adding to zip file..."
+cp -rf "${KEYMAN_FRAMEWORKS}" "${UPLOAD_DIR}/${CARTHAGE_DIR}"
+zip -qrX ${KMEI_DST} "${KEYMAN_FRAMEWORKS}"
+cd $UPLOAD_DIR
+rm -rf "${CARTHAGE_DIR}"
+cd $WORK_DIR
```
Comment (mcdurdin) [inline ios/tools/prepRelease.sh:79]:
```suggestion
cd "$UPLOAD_DIR"
rm -rf "${CARTHAGE_DIR}"
cd "$WORK_DIR"
```

File: ios/tools/prepRelease.sh [hunk 5]
```diff
@@ -56,27 +56,56 @@ LC_ALL=UTF-8 sed -e "s/[$(printf $emoji)]//g" < "$CHANGELOG_PATH" > "$CHANGELOG_
...
+
+#
+# Samples - copy source to temporary folder
+#
 
 KEYMAN_SAMPLES="samples"
+echo "Copying Keyman Engine samples into ${UPLOAD_DIR}/${KMEI_DST_NAME}..."
+cd $WORK_DIR
```
Comment (mcdurdin) [inline ios/tools/prepRelease.sh:87]:
```suggestion
cd "$WORK_DIR"
```

File: ios/tools/prepRelease.sh [hunk 6]
```diff
@@ -56,27 +56,56 @@ LC_ALL=UTF-8 sed -e "s/[$(printf $emoji)]//g" < "$CHANGELOG_PATH" > "$CHANGELOG_
...
+KMEI_FRAMEWORK_BASE="build/Build/Products/Release/"
+KEYMAN_ENGINE_FRAMEWORK="KeymanEngine.xcframework"
 
 echo "engine dest: $KMEI_DST"
 
-echo "Zipping ${UNI_FRAMEWORK} => ${UPLOAD_DIR}/${KMEI_DST}..."
-cd "${KMEI_FRAMEWORK_BASE}"
-zip -qrX ${KMEI_DST} ${FRAMEWORK}
+echo "Copying ${UNI_FRAMEWORK} => ${UPLOAD_DIR}/samples..."
 cd $WORK_DIR
```
Comment (mcdurdin) [inline ios/tools/prepRelease.sh:101]:
```suggestion
cd "$WORK_DIR"
```

**Review by mcdurdin — APPROVED** [review]
LGTM, am assuming it works -- hard for me to try it from here at present. The changes I am requesting are nits only but trying to be consistent about quoting. (We could start using shell script linting like @ermshiperete does for the linux scripts

**Comment by sgschantz** [comment]
@mcdurdin Thanks for the review comments. I still had this PR in draft because it was not quite working. The sample projects could find all their frameworks, but local sample project builds were still failing because they could not find the swiftlint.yml file, the path for which pointed outside of the zip file. I removed the config option from the command to run swiftlint contained in the Xcode script, and it now runs without errors, though I also had to fix a violation that swiftlint found.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.146](https://keyman.com/downloads/releases/stable/16.0.146)
