### PR TITLE
fix(core): fix output append logic in any_group::apply_transform

### LINKED ISSUE #10736: bug(core): bug in ldml transform matcher
- see PR #10735 - matcher replaces one too many chars, resulting on `...map_varsOK` instead of `...map_vars:OK`. 

- splitting out from #10734 as it's a different issue.

### PR DESCRIPTION
**Pull request by srl295**
- logic updating intermediate 'output' was incorrect
- update comments
- also replace size() with length() several places
- refactor transform apply code

Fixes #10736

@keymanapp-test-bot skip

### CODE REVIEW

File: core/src/ldml/ldml_transforms.cpp [hunk 1]
```diff
@@ -669,6 +669,60 @@ any_group::any_group(const transform_group &g) : type(any_group_type::transform)
...
+  std::u32string subOutput;
+  size_t subMatched = transform.apply(input, subOutput);
+
+  if (subMatched == 0) {
+    return matched; // no match, break out
+  }
+
+  // remove the matched part of the input
+  assert(subMatched <= input.length());
+  input.resize(input.length() - subMatched);  // chop of the subMatched part at end
```
Comment (mcdurdin) [inline core/src/ldml/ldml_transforms.cpp:695]:
```suggestion
  input.resize(input.length() - subMatched);  // chop off the subMatched part at end
```

**Review by mcdurdin — APPROVED** [review]
LGTM, nice refactor also

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.272-beta](https://keyman.com/downloads/releases/beta/17.0.272)
