### PR TITLE
fix(developer): various bugs in kmc and related packages 🗜

### LINKED ISSUE #9097: bug(developer): Warning 2020a9 should not be emitted for aksarabali_panlex js build 🗜
Warning should not be emitted for aksarabali_panlex js build: `WARN 2020a9: Key "K_SHIFT" on platform "phone", layer "shift" does not have the key type "Special" or "Special (active)" but has the label "*Shifted*". This feature is only supported in Keyman 14 or later`

Full kmc log:
```
Building keyboard /c/Projects/keyman/keyboards/release/a/aksarabali_panlex/
INFO 5002: Building aksarabali_panlex.kpj
INFO 5002: Building C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\source\aksarabali_panlex.kmn
HINT 1020ae [253]: This rule will never be matched as another rule takes precedence Overridden by rule on line 189
HINT 1020ae [242]: This rule will never be matched as another rule takes precedence Overridden by rule on line 185
HINT 1020ae [252]: This rule will never be matched as another rule takes precedence Overridden by rule on line 243
HINT 1020ae [253]: This rule will never be matched as another rule takes precedence Overridden by rule on line 189
HINT 1020ae [242]: This rule will never be matched as another rule takes precedence Overridden by rule on line 185
HINT 1020ae [252]: This rule will never be matched as another rule takes precedence Overridden by rule on line 243
WARN 2020a9: Key "K_SHIFT" on platform "phone", layer "shift" does not have the key type "Special" or "Special (active)" but has the label "*Shifted*". This feature is only supported in Keyman 14 or later
INFO 5006: aksarabali_panlex.kmn built successfully.
INFO 5002: Building C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\source\aksarabali_panlex.kps
WARN 20400f: The file Vimala.ttf does not follow the recommended filename conventions. The extension should be all lower case, and the filename should include only alphanumeric characters, -, _, + and .
INFO 5006: aksarabali_panlex.kps built successfully.
INFO 5006: aksarabali_panlex.kpj built successfully.
```

Full kmcomp log:
```
Building keyboard release/a/aksarabali_panlex/

aksarabali_panlex.kmn: Compiling 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\source\aksarabali_panlex.kmn' for Windows, macOS, Linux, Desktop devices...
aksarabali_panlex.kmn (253): Hint: 10AE This rule will never be matched as another rule takes precedence Overridden by rule on line 189
aksarabali_panlex.kmn (242): Hint: 10AE This rule will never be matched as another rule takes precedence Overridden by rule on line 185
aksarabali_panlex.kmn (252): Hint: 10AE This rule will never be matched as another rule takes precedence Overridden by rule on line 243
aksarabali_panlex.kmn: Success: 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\source\aksarabali_panlex.kmn' was compiled successfully for Windows, macOS, Linux, Desktop devices to 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\build\aksarabali_panlex.kmx'.
aksarabali_panlex.kmn: Compiling 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\source\aksarabali_panlex.kmn' for Web, iPhone, iPad, Android phone, Android tablet, Mobile devices, Tablet devices...   
aksarabali_panlex.kmn (253): Hint: 10AE This rule will never be matched as another rule takes precedence Overridden by rule on line 189
aksarabali_panlex.kmn (242): Hint: 10AE This rule will never be matched as another rule takes precedence Overridden by rule on line 185
aksarabali_panlex.kmn (252): Hint: 10AE This rule will never be matched as another rule takes precedence Overridden by rule on line 243
aksarabali_panlex.kmn: Success: 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\source\aksarabali_panlex.kmn' was compiled successfully for Web, iPhone, iPad, Android phone, Android tablet, Mobile devices, Tablet devices to 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\build\aksarabali_panlex.js'.
aksarabali_panlex.kps: Compiling package aksarabali_panlex.kps...
aksarabali_panlex.kps: Keyboard with ID 'aksarabali_panlex' has a BCP 47 warning: 'kaw-Bali' is a valid tag but is not canonical: it should be 'kaw'.
aksarabali_panlex.kps: Success: 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\source\aksarabali_panlex.kps' compiled successfully to 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\build\aksarabali_panlex.kmp'.
```

### LINKED ISSUE #9098: bug(developer): Warning 20400f should not be emitted for aksarabali_panlex kmp build 🗜
Warning should not be emitted for aksarabali_panlex kmp build: `WARN 20400f: The file Vimala.ttf does not follow the recommended filename conventions. The extension should be all lower case, and the filename should include only alphanumeric characters, -, _, + and .`

Full kmc log:
```
Building keyboard /c/Projects/keyman/keyboards/release/a/aksarabali_panlex/
INFO 5002: Building aksarabali_panlex.kpj
INFO 5002: Building C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\source\aksarabali_panlex.kmn
HINT 1020ae [253]: This rule will never be matched as another rule takes precedence Overridden by rule on line 189
HINT 1020ae [242]: This rule will never be matched as another rule takes precedence Overridden by rule on line 185
HINT 1020ae [252]: This rule will never be matched as another rule takes precedence Overridden by rule on line 243
HINT 1020ae [253]: This rule will never be matched as another rule takes precedence Overridden by rule on line 189
HINT 1020ae [242]: This rule will never be matched as another rule takes precedence Overridden by rule on line 185
HINT 1020ae [252]: This rule will never be matched as another rule takes precedence Overridden by rule on line 243
WARN 2020a9: Key "K_SHIFT" on platform "phone", layer "shift" does not have the key type "Special" or "Special (active)" but has the label "*Shifted*". This feature is only supported in Keyman 14 or later
INFO 5006: aksarabali_panlex.kmn built successfully.
INFO 5002: Building C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\source\aksarabali_panlex.kps
WARN 20400f: The file Vimala.ttf does not follow the recommended filename conventions. The extension should be all lower case, and the filename should include only alphanumeric characters, -, _, + and .
INFO 5006: aksarabali_panlex.kps built successfully.
INFO 5006: aksarabali_panlex.kpj built successfully.
```

Full kmcomp log:
```
Building keyboard release/a/aksarabali_panlex/

aksarabali_panlex.kmn: Compiling 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\source\aksarabali_panlex.kmn' for Windows, macOS, Linux, Desktop devices...
aksarabali_panlex.kmn (253): Hint: 10AE This rule will never be matched as another rule takes precedence Overridden by rule on line 189
aksarabali_panlex.kmn (242): Hint: 10AE This rule will never be matched as another rule takes precedence Overridden by rule on line 185
aksarabali_panlex.kmn (252): Hint: 10AE This rule will never be matched as another rule takes precedence Overridden by rule on line 243
aksarabali_panlex.kmn: Success: 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\source\aksarabali_panlex.kmn' was compiled successfully for Windows, macOS, Linux, Desktop devices to 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\build\aksarabali_panlex.kmx'.
aksarabali_panlex.kmn: Compiling 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\source\aksarabali_panlex.kmn' for Web, iPhone, iPad, Android phone, Android tablet, Mobile devices, Tablet devices...   
aksarabali_panlex.kmn (253): Hint: 10AE This rule will never be matched as another rule takes precedence Overridden by rule on line 189
aksarabali_panlex.kmn (242): Hint: 10AE This rule will never be matched as another rule takes precedence Overridden by rule on line 185
aksarabali_panlex.kmn (252): Hint: 10AE This rule will never be matched as another rule takes precedence Overridden by rule on line 243
aksarabali_panlex.kmn: Success: 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\source\aksarabali_panlex.kmn' was compiled successfully for Web, iPhone, iPad, Android phone, Android tablet, Mobile devices, Tablet devices to 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\build\aksarabali_panlex.js'.
aksarabali_panlex.kps: Compiling package aksarabali_panlex.kps...
aksarabali_panlex.kps: Keyboard with ID 'aksarabali_panlex' has a BCP 47 warning: 'kaw-Bali' is a valid tag but is not canonical: it should be 'kaw'.
aksarabali_panlex.kps: Success: 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\source\aksarabali_panlex.kps' compiled successfully to 'C:\Projects\keyman\keyboards\release\a\aksarabali_panlex\build\aksarabali_panlex.kmp'.
```

### LINKED ISSUE #9101: bug(developer): Unexpected fatal error 403000 in build of `release/a/anii` 🗜
Build of `release/a/anii` fails with `FATAL 403000: Unexpected exception: TypeError: Cannot read properties of undefined (reading 'toLowerCase')`

kmc log:

```
Building keyboard /c/Projects/keyman/keyboards/release/a/anii/
INFO 5002: Building anii.kpj
INFO 5002: Building C:\Projects\keyman\keyboards\release\a\anii\source\anii.kmn
HINT 105009: File C:\Projects\keyman\keyboards\release\a\anii\source\anii.ico differs in case from reference C:\Projects\keyman\keyboards\release\a\anii\source\Anii.ico; this will fail on platforms with case-sensitive filesystems.
HINT 105009: File C:\Projects\keyman\keyboards\release\a\anii\source\anii.ico differs in case from reference C:\Projects\keyman\keyboards\release\a\anii\source\Anii.ico; this will fail on platforms with case-sensitive filesystems.
WARN 202094: File C:\Projects\keyman\keyboards\release\a\anii\source\anii-help.htm could not be loaded: TypeError: String.prototype.replaceAll called with a non-global RegExp argument
WARN 2020a9: Key "K_SHIFT" on platform "tablet", layer "shift" does not have the key type "Special" or "Special (active)" but has the label "*Shift*". This feature is only supported in Keyman 14 or later        
FATAL 403000: Unexpected exception: TypeError: Cannot read properties of undefined (reading 'toLowerCase')

Call stack:
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at ValidateLayoutFile (file:///C:/Projects/keyman/app/developer/src/kmc-kmn/build/src/kmw-compiler/validate-layout-file.js:186:32)
    at WriteCompiledKeyboard (file:///C:/Projects/keyman/app/developer/src/kmc-kmn/build/src/kmw-compiler/kmw-compiler.js:137:22)
    at KmnCompiler.runWebCompiler (file:///C:/Projects/keyman/app/developer/src/kmc-kmn/build/src/compiler/compiler.js:229:22)
    at KmnCompiler.runCompiler (file:///C:/Projects/keyman/app/developer/src/kmc-kmn/build/src/compiler/compiler.js:207:34)
    at KmnCompiler.run (file:///C:/Projects/keyman/app/developer/src/kmc-kmn/build/src/compiler/compiler.js:85:27)
    at BuildKmnKeyboard.build (file:///C:/Projects/keyman/app/developer/src/kmc/build/src/commands/buildClasses/BuildKmnKeyboard.js:21:25)
    at async ProjectBuilder.buildTarget (file:///C:/Projects/keyman/app/developer/src/kmc/build/src/commands/buildClasses/BuildProject.js:100:22)
    at async ProjectBuilder.buildProjectTargets (file:///C:/Projects/keyman/app/developer/src/kmc/build/src/commands/buildClasses/BuildProject.js:89:26)
    at async ProjectBuilder.run (file:///C:/Projects/keyman/app/developer/src/kmc/build/src/commands/buildClasses/BuildProject.js:42:18)
    at async build (file:///C:/Projects/keyman/app/developer/src/kmc/build/src/commands/build.js:71:22)
INFO 5007: anii.kmn failed to build.
INFO 5007: anii.kpj failed to build.
```

### LINKED ISSUE #9102: bug(developer): Unexpected warning 202094 compiling anii 🗜
`WARN 202094: File C:\Projects\keyman\keyboards\release\a\anii\source\anii-help.htm could not be loaded: TypeError: String.prototype.replaceAll called with a non-global RegExp argument`

kmc log:

```
Building keyboard /c/Projects/keyman/keyboards/release/a/anii/
INFO 5002: Building anii.kpj
INFO 5002: Building C:\Projects\keyman\keyboards\release\a\anii\source\anii.kmn
HINT 105009: File C:\Projects\keyman\keyboards\release\a\anii\source\anii.ico differs in case from reference C:\Projects\keyman\keyboards\release\a\anii\source\Anii.ico; this will fail on platforms with case-sensitive filesystems.
HINT 105009: File C:\Projects\keyman\keyboards\release\a\anii\source\anii.ico differs in case from reference C:\Projects\keyman\keyboards\release\a\anii\source\Anii.ico; this will fail on platforms with case-sensitive filesystems.
WARN 202094: File C:\Projects\keyman\keyboards\release\a\anii\source\anii-help.htm could not be loaded: TypeError: String.prototype.replaceAll called with a non-global RegExp argument
WARN 2020a9: Key "K_SHIFT" on platform "tablet", layer "shift" does not have the key type "Special" or "Special (active)" but has the label "*Shift*". This feature is only supported in Keyman 14 or later        
FATAL 403000: Unexpected exception: TypeError: Cannot read properties of undefined (reading 'toLowerCase')

Call stack:
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at ValidateLayoutFile (file:///C:/Projects/keyman/app/developer/src/kmc-kmn/build/src/kmw-compiler/validate-layout-file.js:186:32)
    at WriteCompiledKeyboard (file:///C:/Projects/keyman/app/developer/src/kmc-kmn/build/src/kmw-compiler/kmw-compiler.js:137:22)
    at KmnCompiler.runWebCompiler (file:///C:/Projects/keyman/app/developer/src/kmc-kmn/build/src/compiler/compiler.js:229:22)
    at KmnCompiler.runCompiler (file:///C:/Projects/keyman/app/developer/src/kmc-kmn/build/src/compiler/compiler.js:207:34)
    at KmnCompiler.run (file:///C:/Projects/keyman/app/developer/src/kmc-kmn/build/src/compiler/compiler.js:85:27)
    at BuildKmnKeyboard.build (file:///C:/Projects/keyman/app/developer/src/kmc/build/src/commands/buildClasses/BuildKmnKeyboard.js:21:25)
    at async ProjectBuilder.buildTarget (file:///C:/Projects/keyman/app/developer/src/kmc/build/src/commands/buildClasses/BuildProject.js:100:22)
    at async ProjectBuilder.buildProjectTargets (file:///C:/Projects/keyman/app/developer/src/kmc/build/src/commands/buildClasses/BuildProject.js:89:26)
    at async ProjectBuilder.run (file:///C:/Projects/keyman/app/developer/src/kmc/build/src/commands/buildClasses/BuildProject.js:42:18)
    at async build (file:///C:/Projects/keyman/app/developer/src/kmc/build/src/commands/build.js:71:22)
INFO 5007: anii.kmn failed to build.
INFO 5007: anii.kpj failed to build.
```

### LINKED ISSUE #9103: bug(developer): `TypeError: Cannot read properties of undefined (reading 'StoreIndex')` compiling armenian_mnemonic 🗜
`TypeError: Cannot read properties of undefined (reading 'StoreIndex')`

```
armenian_mnemonic.keyboard_info: Success: File armenian_mnemonic.keyboard_info validated successfully.
source/armenian_mnemonic.kps validates
Building keyboard /c/Projects/keyman/keyboards/release/a/armenian_mnemonic/
INFO 5002: Building armenian_mnemonic.kpj
INFO 5002: Building C:\Projects\keyman\keyboards\release\a\armenian_mnemonic\source\armenian_mnemonic.kmn
FATAL 402900: Unexpected exception: TypeError: Cannot read properties of undefined (reading 'StoreIndex')

Call stack:
TypeError: Cannot read properties of undefined (reading 'StoreIndex')
    at ExpandSentinel (C:\Projects\keyman\app\developer\src\kmc-kmn\src\kmw-compiler\util.ts:153:41)
    at JavaScript_OutputString (C:\Projects\keyman\app\developer\src\kmc-kmn\src\kmw-compiler\javascript-strings.ts:738:15)
    at JavaScript_Rule (C:\Projects\keyman\app\developer\src\kmc-kmn\src\kmw-compiler\javascript-strings.ts:145:48)
    at JavaScript_Rules (C:\Projects\keyman\app\developer\src\kmc-kmn\src\kmw-compiler\javascript-strings.ts:197:23)
    at WriteCompiledKeyboard (C:\Projects\keyman\app\developer\src\kmc-kmn\src\kmw-compiler\kmw-compiler.ts:312:17)
    at KmnCompiler.runWebCompiler (C:\Projects\keyman\app\developer\src\kmc-kmn\src\compiler\compiler.ts:312:18)
    at KmnCompiler.runCompiler (C:\Projects\keyman\app\developer\src\kmc-kmn\src\compiler\compiler.ts:283:26)
    at KmnCompiler.run (C:\Projects\keyman\app\developer\src\kmc-kmn\src\compiler\compiler.ts:139:23)
    at BuildKmnKeyboard.build (C:\Projects\keyman\app\developer\src\kmc\src\commands\buildClasses\BuildKmnKeyboard.ts:26:21)
    at ProjectBuilder.buildTarget (C:\Projects\keyman\app\developer\src\kmc\src\commands\buildClasses\BuildProject.ts:120:18)
```

### LINKED ISSUE #9104: bug(developer): `TypeError: Cannot read properties of undefined (reading 'toLowerCase')` compiling ausephon 🗜
`TypeError: Cannot read properties of undefined (reading 'toLowerCase')`

```
Building keyboard release/a/ausephon
INFO 5002: Building ausephon.kpj
INFO 5002: Building C:\Projects\keyman\keyboards\release\a\ausephon\source\ausephon.kmn
FATAL 402900: Unexpected exception: TypeError: Cannot read properties of undefined (reading 'toLowerCase')

Call stack:
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at CheckKey (C:\Projects\keyman\app\developer\src\kmc-kmn\src\kmw-compiler\validate-layout-file.ts:78:47)
    at ValidateLayoutFile (C:\Projects\keyman\app\developer\src\kmc-kmn\src\kmw-compiler\validate-layout-file.ts:233:20)
    at WriteCompiledKeyboard (C:\Projects\keyman\app\developer\src\kmc-kmn\src\kmw-compiler\kmw-compiler.ts:154:18)
    at KmnCompiler.runWebCompiler (C:\Projects\keyman\app\developer\src\kmc-kmn\src\compiler\compiler.ts:312:18)
    at KmnCompiler.runCompiler (C:\Projects\keyman\app\developer\src\kmc-kmn\src\compiler\compiler.ts:283:26)
    at KmnCompiler.run (C:\Projects\keyman\app\developer\src\kmc-kmn\src\compiler\compiler.ts:139:23)
    at BuildKmnKeyboard.build (C:\Projects\keyman\app\developer\src\kmc\src\commands\buildClasses\BuildKmnKeyboard.ts:26:21)
    at ProjectBuilder.buildTarget (C:\Projects\keyman\app\developer\src\kmc\src\commands\buildClasses\BuildProject.ts:120:18)
    at ProjectBuilder.buildProjectTargets (C:\Projects\keyman\app\developer\src\kmc\src\commands\buildClasses\BuildProject.ts:106:18)    
    at ProjectBuilder.run (C:\Projects\keyman\app\developer\src\kmc\src\commands\buildClasses\BuildProject.ts:50:11)
```

### LINKED ISSUE #9105: bug(developer): `FATAL 405001: Unexpected exception: TypeError: Cannot set properties of undefined (setting 'description')` building bangla_munir 🗜
```
Building keyboard /c/Projects/keyman/keyboards/release/b/bangla_munir/
INFO 5002: Building bangla_munir.kpj
INFO 5002: Building C:\Projects\keyman\keyboards\release\b\bangla_munir\source\bangla_munir.kmn
INFO 5006: bangla_munir.kmn built successfully.
INFO 5002: Building C:\Projects\keyman\keyboards\release\b\bangla_munir\source\bangla_munir.kps
FATAL 405001: Unexpected exception: TypeError: Cannot set properties of undefined (setting 'description')

Call stack:
TypeError: Cannot set properties of undefined (setting 'description')
    at PackageVersionValidation.validateAndUpdateVersions (C:\Projects\keyman\app\developer\src\kmc-package\src\compiler\package-version-validation.ts:76:37)
    at KmpCompiler.transformKpsToKmpObject (C:\Projects\keyman\app\developer\src\kmc-package\src\compiler\kmp-compiler.ts:145:26)
    at BuildPackage.build (C:\Projects\keyman\app\developer\src\kmc\src\commands\buildClasses\BuildPackage.ts:20:37)
    at ProjectBuilder.buildTarget (C:\Projects\keyman\app\developer\src\kmc\src\commands\buildClasses\BuildProject.ts:120:33)
    at ProjectBuilder.buildProjectTargets (C:\Projects\keyman\app\developer\src\kmc\src\commands\buildClasses\BuildProject.ts:106:29)
    at ProjectBuilder.run (C:\Projects\keyman\app\developer\src\kmc\src\commands\buildClasses\BuildProject.ts:50:22)
    at build (C:\Projects\keyman\app\developer\src\kmc\src\commands\build.ts:82:18)
    at Command.<anonymous> (C:\Projects\keyman\app\developer\src\kmc\src\commands\build.ts:44:13)
    at async Command.parseAsync (C:\Projects\keyman\app\node_modules\commander\lib\command.js:935:5)
```

### LINKED ISSUE #9106: bug(developer): `FATAL 402900: Unexpected exception: TypeError: Cannot read properties of undefined (reading 'startsWith')` building btl_kenya 🗜
```
Building keyboard /c/Projects/keyman/keyboards/release/b/btl_kenya/
INFO 5002: Building btl_kenya.kpj
INFO 5002: Building C:\Projects\keyman\keyboards\release\b\btl_kenya\source\btl_kenya.kmn
FATAL 402900: Unexpected exception: TypeError: Cannot read properties of undefined (reading 'startsWith')

Call stack:
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at CheckKey (C:\Projects\keyman\app\developer\src\kmc-kmn\src\kmw-compiler\validate-layout-file.ts:140:12)
    at ValidateLayoutFile (C:\Projects\keyman\app\developer\src\kmc-kmn\src\kmw-compiler\validate-layout-file.ts:240:24)
    at WriteCompiledKeyboard (C:\Projects\keyman\app\developer\src\kmc-kmn\src\kmw-compiler\kmw-compiler.ts:154:18)
    at KmnCompiler.runWebCompiler (C:\Projects\keyman\app\developer\src\kmc-kmn\src\compiler\compiler.ts:312:18)
    at KmnCompiler.runCompiler (C:\Projects\keyman\app\developer\src\kmc-kmn\src\compiler\compiler.ts:283:26)
    at KmnCompiler.run (C:\Projects\keyman\app\developer\src\kmc-kmn\src\compiler\compiler.ts:139:23)
    at BuildKmnKeyboard.build (C:\Projects\keyman\app\developer\src\kmc\src\commands\buildClasses\BuildKmnKeyboard.ts:26:21)
    at ProjectBuilder.buildTarget (C:\Projects\keyman\app\developer\src\kmc\src\commands\buildClasses\BuildProject.ts:120:18)
    at ProjectBuilder.buildProjectTargets (C:\Projects\keyman\app\developer\src\kmc\src\commands\buildClasses\BuildProject.ts:106:18)
    at ProjectBuilder.run (C:\Projects\keyman\app\developer\src\kmc\src\commands\buildClasses\BuildProject.ts:50:11)
INFO 5007: btl_kenya.kmn failed to build.
INFO 5007: btl_kenya.kpj failed to build.
```

### LINKED ISSUE #9108: bug(developer): errors emitted do not necessarily cancel the build 🗜
For example, el_harari_latin had a bug in its .kps, and the following log was emitted, but the build continued on the next source file.

```
INFO 5002: Building release/el/el_harari_latin/el_harari_latin.kpj
INFO 5002: Building C:\Projects\keyman\keyboards\release\el\el_harari_latin\source\el_harari_latin.kmn
INFO 5006: el_harari_latin.kmn built successfully.
INFO 5002: Building C:\Projects\keyman\keyboards\release\el\el_harari_latin\source\el_harari_latin.kps
ERROR 304008: Keyboard  was listed in <Keyboards> but a corresponding .kmx file was not found in <Files>
INFO 5007: el_harari_latin.kps failed to build.
INFO 5007: release/el/el_harari_latin/el_harari_latin.kpj failed to build.
```

Note: this did not cancel the build, when it should have (similar to #9100)

### LINKED ISSUE #9109: bug(developer): `ERROR 305008: Project file is not valid: Error: data/KeymanDeveloperProject/Files/File/0/Details must be object` 🗜
```
INFO 5002: Building release/rac/rac_uyghur/rac_uyghur.kpj
ERROR 305008: Project file is not valid: Error: data/KeymanDeveloperProject/Files/File/0/Details must be object
INFO 5007: release/rac/rac_uyghur/rac_uyghur.kpj failed to build.
```

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #9097.
Fixes #9098.
Fixes #9101.
Fixes #9102.
Fixes #9103.
Fixes #9104.
Fixes #9105.
Fixes #9106.
Fixes #9108.
Fixes #9109.

This fixes a number of bugs in kmc that were identified by running against the keyboards repository.

Where possible, each bug fix is a separate commit in this PR; you may wish to review each commit separately.

This does not yet get us to 100% identical behaviour on the keyboards repository. There are a number of additional issues to follow up; see #9090, but calling out in particular:

* time and memory complexity issues for the vietnamese_ keyboards currently break kmc-kmw
* a decision needs to be made on `true` vs `True` in hand-edited .kpj files (the 'official' and recently-documented requirement is title case, but the current Delphi loader is lenient)
* some work needs to be done on `compilerWarningsAsErrors` -- it appears that the kmcomp package compiler currently ignores this, whereas kmc-package would respect it. There are numerous packages raising warnings about BCP47 codes, so we need to resolve this.

@keymanapp-test-bot skip

### CODE REVIEW

File: developer/src/kmc-package/src/compiler/package-version-validation.ts [hunk 1]
```diff
@@ -73,7 +73,7 @@ export class PackageVersionValidation {
 
     if(result) {
       if(followKeyboardVersion) {
-        kmp.info.version.description = kmp.keyboards[0].version;
+        kmp.info.version = {description: kmp.keyboards[0].version};
```
Comment (jahorton) [inline developer/src/kmc-package/src/compiler/package-version-validation.ts:76]: Sounds reasonable.  Part of me wonders if there ever would be an existing definition with other members we may wish to save, but realistically speaking... I severely doubt it, in which case this is fine.

File: developer/src/kmc/src/commands/build.ts [hunk 2]
```diff
@@ -79,8 +79,11 @@ async function build(filename: string, options: CompilerOptions): Promise<boolea
       }
     }
 
+    const failureCodes = [CompilerErrorSeverity.Fatal, CompilerErrorSeverity.Error];
+    // TODO: #9100: .concat(options.compilerWarningsAsErrors ? [CompilerErrorSeverity.Warn] : []);
```
Comment (jahorton) [inline developer/src/kmc/src/commands/build.ts:83]: Just highlighting this, as it doesn't seem to be highlighted in the description... and GitHub will help link this TODO by tagging the issue here: #9100.

**Review by jahorton — APPROVED** [review]

**Review by srl295 — APPROVED** [review]

File: developer/src/kmc-package/src/compiler/package-version-validation.ts (hunk 1 above)
Comment (mcdurdin) [reply developer/src/kmc-package/src/compiler/package-version-validation.ts:76]: Yeah, this is actually better than what we had previously -- the `followKeyboardVersion` flag says we should ignore metadata on version found in the package, so this matches the intention of that flag more closely.

In any case, the only other metadata available in `kmp.info.version` is `.url` which is a nonsense anyway for `.version` (yay generic structures for metadata, bad design decision by me way back in the past. The `.url` property is used for some of the other `.info` properties such as `author` -- e.g. `mailto:me@example.com`).
