### PR TITLE
[Mac] Add notarization for 10.14.5 and later versions

### LINKED ISSUE #1877: [Mac] Keyman on Mojave 10.14.5 sometimes emits wrong characters in legacy apps
**Describe the bug**
In macOS 10.14.5, when using legacy apps, such as Word or Adobe products, Keyman sometimes emits base characters instead of the intended output character.

For example, using the GFF Amharic keyboard, pressing `aa` emits `አa` instead `ዓ`. 

It appears that when context modification is required, it is not working with these applications. This did work in macOS 10.14.4.

Reported at:
* https://community.software.sil.org/t/amharic-keyboard-wont-function-fully-on-macos-mojave/2304
* https://community.software.sil.org/t/sil-ipa-ver-1-7-not-functioning-correctly-on-macos-mojave/2340

**To Reproduce**
1. Open Word or another app that requires legacy-mode (backspace-based) input.
2. Select GFF Amharic keyboard (or other keyboard that does context manipulation)
3. Type `aa`.

---

**Keyman for macOS:**
 - OS: macOS 10.14.5
 - Keyman version: 11.0.220
 - Target Application: Word 16.27, Adobe products

### LINKED ISSUE #1893: bug(mac): Amharic keyboard on macOS Mojave 10.14.6 in LibreOffice emits wrong characters
**Background Info**
The updated Keyman as described [here](https://github.com/keymanapp/keyman/issues/1877#issuecomment-514429795) has been install on macOS 10.14.6. The SIL IPA keyboard has also be uninstalled and reinstalled on the OS.

**Describe the bug**
Key sequence and the expected output
hi > ሂ
ho > ሆ
hu > ሁ
he > ሀ
ha > ሃ

But in LibreOffice, the followings are output instead:
hi > ህi
ho > ህo
hu > ህu
he > ህe
ha > ህa

**To Reproduce**
1. Go to 'LibreOffice' or 'TextEdit' or 'Notes' or 'Message' 
2. Select the 'GFF Amharic' keyboard from the Keyman menu
3. Type: hi, ho, hu, he, ha

**Screenshots**
Text typed on 'LibreOffice,' 'TextEdit,' 'Notes' and 'Message' (in this order)
image

---

**Keyman for macOS**
 - OS: macOS Mojave 10.14.6
 - Keyman version: [12.0 (for testing)](https://drive.google.com/file/d/1HsNAJDlsNGMlmSphVEG4OOmhlgi4NNSa/view?usp=sharing)
 - Target Application: 'LibreOffice' or 'TextEdit' or 'Notes' or 'Message' 
   
**Keyboard**
 - Keyboard name: [GFF Amharic](https://keyman.com/keyboards/gff_amharic)
 - Keyboard version: 1.8
 - Language name: Amharic

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #1877.
Fixes #1893.

Initially appeared that this relates to #1892 but this now looks like a separate issue.

This PR adds runtime hardening, timestamped certificate, appropriate entitlements, and updates build scripts to pass the app through Apple's notarization process.

A little bit of tidyup is included (particularly not printing all environment variables in build scripts -- I can't imagine why XCode defaults to printing environment variables in custom build script invocations but there you go). This is a security change given we may at some point have secure parameters in CI.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/157626:id/kvk/index.html)

**Comment by mcdurdin** [comment]
Note, for testing, also review instructions at https://github.com/keymanapp/keyman/issues/1877#issuecomment-514429795

**Comment by mcdurdin** [comment]
Per https://community.software.sil.org/t/amharic-keyboard-wont-function-fully-on-macos-mojave/2304/18 there are still some issues; also see failing tests. WIP.

**Comment by mcdurdin** [comment]
Okay, I don't think this is WIP any more. As well as notarization, there is some restructuring and logic change because Delete Back, when synthesized by Keyman, is not always visible to Keyman, for example in Adobe apps, using the normal `InputController handleEvent` method. So we now process Delete Back for 'legacy' style apps through the low level event tap, which does appear more reliable.

I have also added a number of other apps to the list of 'legacy' apps. In the future, we should make this list user-manageable, and it may be possible to design a heuristic to allow us to dynamically switch into legacy mode if a delete command is not processed by the client app.

File: mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m [hunk 1]
```diff
@@ -81,20 +81,28 @@ - (id)init {
...
-        self.lowLevelEventTap = CGEventTapCreate(kCGAnnotatedSessionEventTap, kCGHeadInsertEventTap, kCGEventTapOptionListenOnly, CGEventMaskBit(kCGEventFlagsChanged) | CGEventMaskBit(kCGEventLeftMouseDown) | CGEventMaskBit(kCGEventLeftMouseUp), (CGEventTapCallBack)eventTapFunction, nil);
-        
+
+        self.lowLevelEventTap = CGEventTapCreate(kCGAnnotatedSessionEventTap,
+                                                 kCGHeadInsertEventTap,
+                                                 kCGEventTapOptionListenOnly,
+                                                 CGEventMaskBit(kCGEventFlagsChanged) |
+                                                 CGEventMaskBit(kCGEventLeftMouseDown) |
+                                                 CGEventMaskBit(kCGEventLeftMouseUp) |
+                                                 CGEventMaskBit(kCGEventKeyDown),
```
Comment (mcdurdin) [inline mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodAppDelegate.m]: Note, this is added

File: mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m [hunk 2]
```diff
@@ -720,34 +757,33 @@ - (BOOL)deleteBackLegacy:(NSUInteger)n at:(NSUInteger) pos with:(NSRange) select
...
             NSLog(@"Legacy mode: calling postDeleteBacks");
             if (_clientCanProvideSelectionInfo == No || _clientCanProvideSelectionInfo == Unreliable)
                 NSLog(@"Cannot trust client to report accurate selection length - assuming no selection.");
         }
-        
-        // Note: If pos is "not found", most likely the client can't accurately report the location. This might be
-        // dangerous, but for now let's go ahead and attempt to delete the characters we think should be there.
+
         if (_pendingBuffer != nil && [[self pendingBuffer] length] > 0) {
-            NSException* exception = [NSException
```
Comment (mcdurdin) [inline mac/Keyman4MacIM/Keyman4MacIM/KMInputMethodEventHandler.m]: Throwing an exception in an input method is messy, causes macOS to eventually (after 3 repeats?) stop loading the IM until a restart. Better that we log to console and pretend all is good ...

File: mac/build.sh [hunk 3]
```diff
@@ -25,18 +25,32 @@ display_usage() {
     echo "  -clean          Removes all previously-existing build products for anything to be built before building."
     echo "  -test           Runs unit tests (not applicable to 'testapp' target)"
     echo "  -no-codesign    Disables code-signing for Keyman4MacIM, allowing it to be performed separately later"
```
Comment (mcdurdin) [inline mac/build.sh]: This comment could be better; that avoids the default codesigning. Using `-deploy local -no-codesign` actually does do signing, but not using the default certificate ID.

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/159612:id/kvk/index.html)

File: mac/README.md [hunk 4]
```diff
@@ -8,22 +8,53 @@ Install cocoapods (sudo gem install cocoapods) if not already installed.
...
+With macOS 10.14 and later, Keyman must be signed then notarized by Apple, even for local
+test builds. This requires additional configuration for your build environment.
+
+1. First, open XCode, Preferences, Accounts, and select Manage Certificates for the identity
+   you wish to use for signing. Click **+** and select **Developer ID Application**. A
+   certificate will then be generated and listed in your Keychain. Get info for the certificate
+   you generated from Keychain and copy its SHA-1 fingerprint. You'll need to remove spaces
+   from between the hex pairs; you'll use this in step 3.
+
+2. Determine the Apple ID details in order to run a build. You'll need to create an
```
Comment (jahorton) [inline mac/README.md]:
```suggestion
2. Determine the Apple ID details in order to run a build. You may wish to create an
```

File: mac/README.md [hunk 5]
```diff
@@ -8,22 +8,53 @@ Install cocoapods (sudo gem install cocoapods) if not already installed.
...
-  
+    * If you have signing credentials from the core development team, you can build a signed version by omitting `-no-codesign`. Somewhat misleadingly, `-no-codesign` only stops
+    automatic signing using the certificate maintained by the core development team!
+
 Note: If Carthage prompts you to allow it access to your github credentials, it's fine to click Deny.
 
 ### Running Keyman
 1. Deploy Keyman locally using `./build.sh -deploy local -deploy-only`.
-    * Alternatively copy **keyman/mac/Keyman4MacIM/build/Debug/Keyman.app** to **~/Library/Input Methods**
+    * This will notarize the app, signing with your local credentials if not already signed, and copy **keyman/mac/Keyman4MacIM/build/Debug/Keyman.app** to **~/Library/Input Methods**
```
Comment (jahorton) [inline mac/README.md]: Note that this requires a "release" build, which step 3 doesn't generate... at least without the `-no-codesign` parameter.  That said, since "debug" builds seem to be useless now, maybe "release" should now be the default?

Comment (mcdurdin) [reply mac/README.md]: Release should be the default for the command line build I guess. Debug builds are useful for local debugging without being installed as an IM, though.
