### PR TITLE
fix(mac): restore OSK keys that became invisible in mac OS 14 Sonoma

### LINKED ISSUE #11379: bug(mac): on-screen keyboard blank for all keyboards
### Describe the bug

This problem appears for all language keyboards under keyman.

### Reproduce the bug

Steps to reproduce:

1. Install the latest version of the Keyman-18.0.28 Alpha 06/05/2024 build.
2. Downloaded and installed the gff_amharic keyboard using the Keyman Configuration dialog.
3. Select the "Amharic" keyboard on the toolbar.
4. Open the "On-Screen Keyboard" window by clicking the Keyman icon.
Here, the on-screen keyboard is showing as blank, and there are no "amhairc" buttons. 

Please refer the screenshot below.

    
   

### Expected behavior

It needs to show the all buttons on the "on-screen keyboard" window.

### Related issues

_No response_

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

Keyman-18.0.28 Alpha

### Operating system

macOS Somona

### Device

_No response_

### Target application

_No response_

### Browser

_No response_

### Keyboard name

_No response_

### Keyboard version

_No response_

### Language name

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sgschantz**
According to [AppKit Release Notes for macOS 14](https://developer.apple.com/documentation/macos-release-notes/appkit-release-notes-for-macos-14#NSView) the property NSView.clipsToBounds which was defaulted to true was changed to default to false. This caused the Keyman OSK keys to not be drawn correctly under Sonoma, giving the appearance of a blank OSK. This change is to override the new default behavior and set the property back to true.

Fixes #11379 

Also, with the move to Xcode 15.3, there are several APIs called from Keyman for Mac that were deprecated before our minimum supported version of macOS (now set to 10.13). These can be replaced without doing version checks because the replacements are available for all of our supported OS versions. It was suspected that these may have caused the OSK issue, but they had no effect.

To support the debugging of the OSK issue, log statements were also added using the Unified Logging API for which we now have support in our minimum target version of macOS.

# User Testing

* **TEST_OSK_KEYS_VISIBLE**: confirm that the OSK looks as expected

1. Select On-screen Keyboard from the Keyman menu 
1. Confirm that the keyboard is not blank but populated with dozens of keys as expected

* **TEST_OSK_VIEW_RESIZABLE**: confirm that the OSK is resizable

1. Select On-screen Keyboard from the Keyman menu 
1. Resize the OSK
1. Confirm that the keys resize appropriately and are still visible

### CODE REVIEW

File: mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m [hunk 1]
```diff
@@ -27,28 +28,30 @@ @interface KeyView ()
...
 @implementation KeyView
 @synthesize tag;
-@synthesize bgColor1, bgColor2;
+@synthesize bgColorRegularKey, bgColorSpecialKey;
 
 - (id)initWithFrame:(NSRect)frame {
+    os_log_t oskKeyLog = os_log_create("org.sil.keyman", "osk-key");
     self = [super initWithFrame:frame];
     if (self) {
+        os_log_with_type(oskKeyLog, OS_LOG_TYPE_DEBUG, "KeyView initWithFrame: %{public}@, bounds: %{public}@, default clipsToBounds %{public}@", NSStringFromRect(frame), NSStringFromRect(self.bounds), self.clipsToBounds?@"YES":@"NO");
```
Comment (jahorton) [inline mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m:45]: I take it the new logs are intentionally being left in?

File: mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m [hunk 2]
```diff
@@ -60,22 +63,26 @@ - (id)initWithFrame:(NSRect)frame {
...
+        bgColorRegularKey = [self getOpaqueColorWithRed:209 green:211 blue:212];
+        bgColorSpecialKey = [self getOpaqueColorWithRed:166 green:169 blue:172];
     }
 
     return self;
 }
 
 - (void)drawRect:(NSRect)rect {
+    os_log_t oskKeyLog = os_log_create("org.sil.keyman", "osk-key");
+    os_log_with_type(oskKeyLog, OS_LOG_TYPE_DEBUG, "KeyView drawRect: %{public}@, bounds: %{public}@, keyCode: 0x%lx, caption: %{public}@, label: %{public}@", NSStringFromRect(rect), NSStringFromRect(self.bounds), self.keyCode, self.caption.stringValue, self.label.stringValue);
```
Comment (jahorton) [inline mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m:75]: More "new logs".  This one looks like we're making a new logging object... with the same ID as the log noted for the previous comment?

File: mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/OSKKey.m [hunk 3]
```diff
@@ -7,12 +7,15 @@
...
 #import "OSKKey.h"
+#import <os/log.h>
 
 @implementation OSKKey
 
 - (id)initWithKeyCode:(NSUInteger)keyCode caption:(NSString *)caption scale:(CGFloat)scale {
     self = [super init];
     if (self) {
+        os_log_t oskKeyLog = os_log_create("org.sil.keyman", "osk-key");
+      os_log_with_type(oskKeyLog, OS_LOG_TYPE_DEBUG, "OSKKey initWithKeyCode: 0x%lx, caption: %{public}@, scale: %f", keyCode, caption, scale);
```
Comment (jahorton) [inline mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/OSKKey.m:18]: Noting the log stuff yet again, just in case.

**Comment by dinakaranr** [comment]
# Test Results
* **TEST_OSK_KEYS_VISIBLE (PASSED):** I tested this issue with the attached "Keyman 17.0.320-beta-test-11388" build on an macOS environment: Here is my observation.
Steps to reproduce:

1. Install the latest version of the Keyman-17.0.320.dmg file on 10/05/2024
2. Downloaded and installed the gff_amharic keyboard using the Keyman Configuration dialog.
3. Select the "Amharic" keyboard on the toolbar.
4. Open the "On-Screen Keyboard" window by clicking the Keyman icon.

Here, the on-screen keyboard appeared correctly, and it is not in a blank state now. It is showing the "amhairc" key buttons.
* **TEST_OSK_VIEW_RESIZABLE (PASSED):**
Followed above step 1 to 4
Resize the “on-screen keyboard”window and observed that the key are showing in visible state.(Keyboard appeared in resize state when reopening the keyboard)
The OSK is working correctly on macOS and when resize the keyboard screen too. It works good. Thanks.

File: mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m (hunk 1 above)
Comment (sgschantz) [reply mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m:45]: Yes, I am planning to include more log statements with the unified logging APIs because attaching the debugger to the input method is not practical. I will do this throughout the app for #10997.

With log statements of type DEBUG, the messages are not persisted and are immediately discarded unless debug messages are enabled (disabled by default) and the log is actually being streamed.

File: mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m (hunk 2 above)
Comment (sgschantz) [reply mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/OnScreenKeyboard/KeyView.m:75]: The os_log_create does not actually create a new log object if it has already been called. Internally, the logging framework creates a singleton for each log object of a certain subsystem/category.

To reduce clutter, I can create a private member variable to hold this reference so that within each method there is only one line of code to write a log statement. It will have no effect on performance, but could make it easier to read the code.

**Comment by jahorton** [comment]
Have we been able to test this on pre-Sonoma devices as well?  Since the issue arose with Sonoma, it'd be wise to verify that we don't break on older macOS as a consequence of the fix.

**Review by mcdurdin — APPROVED** [review]
LGTM. Agree that we should test against older operating systems as well

**Comment by sgschantz** [comment]
Tested with Monterey, and the OSK passes both users tests there also.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.323-beta](https://keyman.com/downloads/releases/beta/17.0.323)
