### PR TITLE
fix(web): post-keystroke processing after use of pred. text selection

### LINKED ISSUE #6885: bug(web): unbound banner event handler leads to failure to read properties of undefined
Sentry Issue: [KEYMAN-WEB-3G](https://sentry.io/organizations/keyman/issues/3393363803/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'touchable')
  at call (source/osk/banner.ts:408:7)
  at apply (source/osk/banner.ts:266:16)
  at doAccept (source/osk/banner.ts:562:38)
  at select (source/osk/banner.ts:482:7)
  at inputEndHandler (source/osk/uiTouchHandlerBase.ts:305:11)
...
(7 additional frame(s) were not displayed)
```

This bug was introduced by #6874.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #6885 for `stable-15.0`.  We'll likely want equivalent changes in #6849 before it merges as well.

## User Testing

TEST_PRED_TEXT:  On a desktop device, using Chrome's developer mode on the "Prediction - robust testing" Web test page...

1. Use the "Toggle device toolbar" button to _emulate_ a mobile device.
2. Refresh the page.
3. Click one of the textboxes.
4. Click any default suggestion.
    - If the selected suggestion is not applied properly, _**FAIL**_ this test.
5. Check the developer-mode "Console" tab (it's usually visible by default).  If there are _any_ errors (with red text!) in the console log, report them and _**FAIL**_ this test.
    - Unless they were already in the console before step 4.
6. Type a few letters and click another suggestion.
    - If the selected suggestion is not applied properly, _**FAIL**_ this test.
7. Repeat step 5.
8. Repeat steps 6 and 7 at least 4 more times.

It would be nice if we had a pre-existing resource set where we could selectively trigger a postKeyboard rule in a meaningful, visual way without resorting to the console... but I don't believe that we do.  And it is a simple enough and highly directed fix, so... this may be fine as-is?

### CODE REVIEW

File: web/source/osk/banner.ts [hunk 1]
```diff
@@ -427,6 +427,7 @@ namespace com.keyman.osk {
       keyman.core.languageProcessor.removeListener('suggestionsready', manager.updateSuggestions);
       keyman.core.languageProcessor.removeListener('tryaccept', manager.tryAccept);
       keyman.core.languageProcessor.removeListener('tryrevert', manager.tryRevert);
+      keyman.core.languageProcessor.removeListener('suggestionapplied', this.suggestionApplied);
```
Comment (jahorton) [inline web/source/osk/banner.ts:430]: I threw this in, since I happened to notice it.

**Review by mcdurdin — APPROVED** [review]
LGTM, code changes makes sense. Though it's kinda weird that suggestionApplied is the only event handler that isn't in manager ... not sure I understand why?

**Comment by jahorton** [comment]
> LGTM, code changes makes sense. Though it's kinda weird that suggestionApplied is the only event handler that isn't in manager ... not sure I understand why?

I can trace this to #6004.  That said, I do understand why - `SuggestionManager` doesn't track `hostDevice`, but `SuggestionBanner` does.

_**That**_ said, this handler doesn't belong in the banner's code at all.  It should be handled within `InputProcessor` as part of suggestion application, not as part of the banner's code.  That'll be a bridge to cross when we go to fully split of Web's OSK as its own module.

**Comment by MakaraSok** [comment]
# Test Results

Tested on Chrome `103.0.5060.53 (Official Build) (x86_64)` on macOS `12.4`.

* **TEST_PRED_TEXT (PASSED):** No issue found. Everything works as indicated.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.265](https://keyman.com/downloads/releases/stable/15.0.265)
