### PR TITLE
fix(developer): report missing help to sentry instead of local xml

### LINKED ISSUE #11262: bug(developer): exit can cause `EAccessViolation` in the help form in some cases
Sentry Issue: [KEYMAN-DEVELOPER-ZZ](https://keyman.sentry.io/issues/3899761275/?referrer=github_integration)

```
EAccessViolation: Exception EAccessViolation in module tike.exe at 008DA216.
Access violation at address 00CDA216 in module 'tike.exe'. Read of address 00000000.

  File "UfrmHelp.pas", line 200, in UfrmHelp.TfrmHelp.FormDestroy
    FHelpMissingFile.SaveToFile(FHelpFileName);
  File "Vcl.Forms.pas", line 3851, in Vcl.Forms.TCustomForm.DoDestroy
  File "Vcl.Forms.pas", line 3784, in Vcl.Forms.TCustomForm.BeforeDestruction
  File "System.pas", line 17458, in System.TObject.Free
  File "UfrmMain.pas", line 691, in UfrmMain.TfrmKeymanDeveloper.FormDestroy
    DoCloseCleanup;
...
(47 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #11262.

Avoid the crash by reporting missing help pages to Sentry instead of attempting to write to a local .xml file. This gives us more data of which help is missing from Keyman Developer, which is more useful to us.

@keymanapp-test-bot skip

### CODE REVIEW

File: developer/src/tike/main/UfrmHelp.pas [hunk 1]
```diff
@@ -55,52 +68,35 @@ implementation
...
+  if TKeymanSentryClient.Instance.Client = nil then Exit;
 
-  n := FHMFRoot.AddChild('MissingTopic');
-  n.Attributes['FormName'] := FormName;
-  n.Attributes['ControlName'] := ControlName;
-  n.Attributes['LastVisited'] := Now;
-  n.Attributes['VisitCount'] := 1;
-end;
+  if FormName = '' then FormName := '<empty>';
+  if ControlName = '' then ControlName := '<empty>';
```
Comment (darcywong00) [inline developer/src/tike/main/UfrmHelp.pas:90]: Are these tags closed automatically? (e.g. `</empty>`)

**Review by darcywong00 — APPROVED** [review]
lgtm

File: developer/src/tike/main/UfrmHelp.pas (hunk 1 above)
Comment (mcdurdin) [reply developer/src/tike/main/UfrmHelp.pas:90]: It's not actually a tag in this case, it's just placeholder text (can't have an empty string for Sentry's tags)
