### PR TITLE
fix(developer/ide): Model editor various bugs

### LINKED ISSUE #2437: [Developer] Lexical Model Editor TODO items
**Describe the bug**
A number of to do items from the Lexical Model Editor source.

```
//TODO: CEF destruction is incorrect in this unit

// TODO: FindError is not implemented

function TfrmModelEditor.GetDefaultExt: string;
begin
  Result := '.model.ts';  // TODO: test if this actually works!
end;

function TfrmModelEditor.GetHelpTopic: string;
begin
  Result := ''; //SHelpTopic_Context_WordlistEditor;  // TODO: use a better topic
end;

procedure TfrmModelEditor.cmdSendURLsToEmailClick(Sender: TObject);
begin
  with TfrmSendURLsToEmail.Create(Application.MainForm) do
  try
    //TODO: KeyboardName := Self.FKeyboardParser.GetSystemStoreValue(ssName);
    Hosts.Assign(lbDebugHosts.Items);
    ShowModal;
  finally
    Free;
  end;
end;
```

--
 
**Keyman Developer**:
 - OS: Windows 10
 - Keyman Developer version: 13.0

### LINKED ISSUE #2632: [Developer] Changes in Wordlist tab do not mark lexical model editor as modified
**Describe the bug**
When editing a wordlist lexical model in Developer, if you have an unmodified file and make changes in any wordlist tab, the resulting Modified flag is not set in the parent .model.ts, so the changes will never be saved.

---

**Keyman Developer:**
 - OS: Windows 10
 - Keyman Developer version: 13.0.70

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #2632.
Fixes #2437.

* The model editor was not being notified of changes in wordlist tabs, which meant that it would never be set into modified state for changes exclusively in a wordlist.
* add context help
* add Ctrl+PgUp/Ctrl+PgDn hotkeys for switching pages
* add Alt+Left/Alt+Right hotkeys for switching views
* remove old TODO items
* saving file from source view now gets latest changes correctly

### CODE REVIEW

File: windows/src/developer/TIKE/child/UfrmKeymanWizard.pas [hunk 1]
```diff
@@ -2466,7 +2466,13 @@ procedure TfrmKeymanWizard.ChangeView(FView: TCodeDesignView);   // I4678
     case FView of
       cdvDesign: if pagesTouchLayout.ActivePage <> pageTouchLayoutDesign then pagesTouchLayout.SelectNextPage(False);
       cdvCode:   if pagesTouchLayout.ActivePage <> pageTouchLayoutCode then pagesTouchLayout.SelectNextPage(True);
-    end;
+    end
+  else if pages.ActivePage = pageOnScreenKeyboard then
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/child/UfrmKeymanWizard.pas]: Also fixed the Alt+Left/Right in On Screen Keyboard view while I was at it.

File: windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.pas [hunk 2]
```diff
@@ -1,4 +1,3 @@
-//TODO: CEF destruction is incorrect in this unit
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.pas]: CEF destruction appears to be correct; this comment is probably very old.

File: windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.pas [hunk 3]
```diff
@@ -282,7 +297,7 @@ procedure TfrmModelEditor.FormDestroy(Sender: TObject);
 
 function TfrmModelEditor.GetDefaultExt: string;
 begin
-  Result := '.model.ts';  // TODO: test if this actually works!
```
Comment (mcdurdin) [inline windows/src/developer/TIKE/child/Keyman.Developer.UI.UfrmModelEditor.pas]: Now tested, works.
