### PR TITLE
fix(web): fixes variable stores

### LINKED ISSUE #2874: [Web] Proper variable-store handling
**Describe the bug**
As noted in #2850, we'll need to revise variable-store handling in the near future.  It hasn't received much love in a long time, and we should definitely add unit-testing for the feature.

From that PR's comments:

>    What would be some good keyboards to use for testing variable stores? We've never had too much testing against those, so I wouldn't be surprised if there have been lingering issues for a while.

The following keyboards may be applicable -- with some minor changes to allow for web, possibly:

"C:\Projects\keyman\app\common\core\desktop\tests\unit\kmx\021 - options.kmn"
"C:\Projects\keyman\app\common\core\desktop\tests\unit\kmx\022 - options with preset.kmn"
"C:\Projects\keyman\app\common\core\desktop\tests\unit\kmx\023 - options with save.kmn"
"C:\Projects\keyman\app\common\core\desktop\tests\unit\kmx\024 - options with save and preset.kmn"
"C:\Projects\keyman\app\common\core\desktop\tests\unit\kmx\025 - options with reset.kmn"

Where "keyman\app" is a developer's local version of "keymanapp/keyman" - this repo's base.

### PR DESCRIPTION
**Pull request by jahorton**
Yeah... these have been broken for quite a while.

Fixes #2874.

Includes unit tests, since this feature never had any to begin with.  Note that it hasn't yet been refactored; this is only a fix.  Those make up the bulk of this PR's changes.

### CODE REVIEW

File: web/source/keyboards/kmwkeyboards.ts [hunk 1]
```diff
@@ -1181,7 +1181,7 @@ namespace com.keyman.keyboards {
      * @param {string} x keyboard name string
      *
```
Comment (darcywong00) [inline web/source/keyboards/kmwkeyboards.ts]: Can you add a comment how `force` gets used? The commit message said it's for a unit test, but I don't see the usage.

Comment (jahorton) [reply web/source/keyboards/kmwkeyboards.ts]: Good catch; it's used now by the new tests, and I added the new comment bit from kmwbase.ts here as well.

File: web/testing/options-with-save/index.html [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+    </script>
+  </head>
+
+  <body>
+    <h2>KeymanWeb:  Test basic variable-store functionality</h2>
+    <p><ul>
+      <li><code>a</code>: Outputs "foo." if store is 'true', "no foo." if store is 'false'.</li>
+      <li><code>0</code>: Sets store to 'false'.</li>
+      <li><code>1</code>: Sets store to 'true'.</li>
+      <li><code>2</code>: "Saves" store; value should persist after a page reload.</li>
```
Comment (darcywong00) [inline web/testing/options-with-save/index.html]: On my setup, the test page behaves as if the store were `false` on page reload. (I'm having to also hit the "Use Web keyboard" button on each load. Otherwise a -> a).

Key sequence
a01a2
page reload
a --> no foo.

Comment (darcywong00) [reply web/testing/options-with-save/index.html]: ah, will rerun with the newest commits...

Comment (jahorton) [reply web/testing/options-with-save/index.html]: I did note having to toggle the keyboard on after I cleared the page's cache from the past day (since before I started work on this issue).  Even with the purged web-cookie, it's still working correctly on my end.

Just in case, maybe try purging the cache/rebuilding?

Comment (darcywong00) [reply web/testing/options-with-save/index.html]: My Chrome must have latched on to something.
Rerunning in FF worked fine

**Comment by jahorton** [comment]
Yep, right about.  Testing those three lines, though... that's where it gets you.
