### PR TITLE
fix(windows, common/core/desktop): context mismatch with if and dk

### LINKED ISSUE #4275: bug(windows): context() and context do not work correctly with if() or deadkey()
**Describe the bug**

The `context()` and `context` statements do not correctly reproduce the context when `if()` or `deadkey()` statements are used. The results are slightly different in each case:

1. With each `if()` statement, subsequent characters are offset by 1 for `context()` indices.
2. Deadkeys are elided for `context` statements 
3. `context()` statements that refer to deadkeys emit garbage (`U+FFFF`)

These issues arise because of poor use of `miniContext` [in Keyman Engine](https://github.com/keymanapp/keyman/blob/f7e23ba0c5a9430049d1281e228ee8f9c53d0843/windows/src/engine/keyman32/kmprocess.cpp#L551-L565), which does not account for `if()` or other zero-width statements, and is emitted character-by-character rather than emitting the actual code element (using `PostString` such as is done with the [`CODE_INDEX` path](https://github.com/keymanapp/keyman/blob/f7e23ba0c5a9430049d1281e228ee8f9c53d0843/windows/src/engine/keyman32/kmprocess.cpp#L586-L594)).

* Keyman Engine for Web: not affected.
* Keyman Engine for macOS: affected, will not fix, wait for Keyman Core on macOS.
* Keyman Core (Linux): also affected.

**Backward compatibility report**

1. It is possible that there are keyboards that are using the `context()` and `if()` statements that have hacked workarounds but a search shows that only el_dinka and el_nuer in the keyboards repository are using this construct, and only in commented out rules (perhaps because of this bug).

2. The fixes for deadkeys should be reasonably straightforward because they would never have been correct in earlier versions. A search in the keyboards repository (regex `(deadkey|dk)\(.+context`) reveals the following keyboards:

  * bj_naskapi_common uses this construct in [3 rules](https://github.com/keymanapp/keyboards/blob/11dcc04b90d6d58f67c563980fb5a60144cf1ae4/release/bj/bj_naskapi_common/source/bj_naskapi_common.kmn#L233-L235)
  * korean_rr.kmn uses this in [4 rules](https://github.com/keymanapp/keyboards/blob/11dcc04b90d6d58f67c563980fb5a60144cf1ae4/release/k/korean_rr/source/korean_rr.kmn#L111-L114). Fixing this issue will improve this keyboard.
  * lao_phonetic.kmn uses this in [1 rule](https://github.com/keymanapp/keyboards/blob/11dcc04b90d6d58f67c563980fb5a60144cf1ae4/release/l/lao_phonetic/source/lao_phonetic.kmn#L146)
  * sil_korda_jamo.kmn uses this in [2 rules](https://github.com/keymanapp/keyboards/blob/11dcc04b90d6d58f67c563980fb5a60144cf1ae4/release/sil/sil_korda_jamo/source/sil_korda_jamo.kmn#L88-L89)
  * sil_korda_latin.kmn uses this in [1 rule](https://github.com/keymanapp/keyboards/blob/11dcc04b90d6d58f67c563980fb5a60144cf1ae4/release/sil/sil_korda_latin/source/sil_korda_latin.kmn#L138)

**To Reproduce**

Keyboard context_mismatchwith_if:

```
c Tests context(n) together with if() and BKSP, as reported by 
c Andrew Cunningham.

c
c Tests:
c
c 1. [x][BKSP] should result in "a" U+0308
c    -> 14.0.223 gives U+0308 "e"
c 2. [y][z] should result in '<' dk(1) 'a' dk(2) 'b' dk(3) '>'
c    -> 14.0.223 gives 'ab>' (note the missing initial '<'!)
c 3. [y][M] should result in '<' dk(1) '>'
c    -> 14.0.223 gives '<' U+FFFF '>'
c    (to test on web, type [y][M][?], which should result in 'correct', as it is
c     difficult to observe deadkeys)
c
c Note: all these tests pass on web.
c


store(&VERSION) '10.0'
store(&NAME) 'context_mismatch_with_if'
store(&COPYRIGHT) '© 2021 Andrew Cunningham / Marc Durdin'
store(&TARGETS) 'any'

begin Unicode > use(constraints)

store(nfc) '0'    c 1 (default) = Normalisation Form C, 0 = Normalisation Form D
store(diaeresisBase) U+0061 U+0041 U+0065 U+0045 U+0069 U+0049 U+006F U+004F                   c a A e E i I o O

group(constraints) using keys

c ########################
c character position tests
c ########################

c Setup

+ 'x' > 'a' U+0308 'e' U+0308

c Test #1 for if() with context(n)

if(nfc = "0") any(diaeresisBase) U+0308 any(diaeresisBase) U+0308 + [K_BKSP] > context(2) context(3)

c ##########################
c deadkeys and context tests
c ##########################

c Setup

+ 'y' > dk(1) 'a' dk(2) 'b' dk(3)

c Test #2 for dk(d) and context

dk(1) 'a' dk(2) 'b' dk(3) + 'z' > '<' context '>'
'<' dk(1) 'a' dk(2) 'b' dk(3) '>' + '?' > 'correct'

c Test #3 for dk(d) and context(n)

dk(1) 'a' dk(2) 'b' dk(3) + 'M' > '<' context(1) '>'
'<' dk(1) '>' + '?' > 'correct'
```

Using keyboard context_mismatch_with_if, type the following sequences:

1. <kbd>x</kbd><kbd>BKSP</kbd> should result in `"a" U+0308` but 14.0.223 gives `U+0308 "e"`
2. <kbd>y</kbd><kbd>z</kbd> should result in `'<' dk(1) 'a' dk(2) 'b' dk(3) '>'` but 14.0.223 gives `"ab>"` (note the missing initial `"<"`!)
3. <kbd>y</kbd><kbd>M</kbd> should result in `"<" dk(1) ">"` but 14.0.223 gives `'<' U+FFFF '>'`

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10, Linux 
 - Keyman version: 14.0.223-beta

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4275.

Includes automatic and manual tests.

### CODE REVIEW

File: common/core/desktop/src/kmx/kmx_processor.cpp [hunk 1]
```diff
@@ -353,20 +356,22 @@ int KMX_Processor::PostString(PKMX_WCHAR str, LPKEYBOARD lpkb, PKMX_WCHAR endstr
...
+      {
+        KMX_BOOL ignoreOutputKeystroke;
         p++;
-        for(q = m_miniContext, i = 0; *q && i < *p-1; i++, q=incxstr(q));
-        if(*q) {
-          m_actions.QueueAction(QIT_CHAR, *q);
-          if(Uni_IsSurrogate1(*q) && Uni_IsSurrogate2(*(q+1))) {
-            m_actions.QueueAction(QIT_CHAR, *(q+1));
-          }
+        for (q = m_miniContext, i = m_miniContextIfLen; *q && i < *p - 1; i++, q = incxstr(q));
```
Comment (mcdurdin) [inline common/core/desktop/src/kmx/kmx_processor.cpp:368]: This change ensures we skip the `if()` statements which are excluded from the `m_miniContext` buffer.

File: common/core/desktop/src/kmx/kmx_processor.cpp [hunk 2]
```diff
@@ -353,20 +356,22 @@ int KMX_Processor::PostString(PKMX_WCHAR str, LPKEYBOARD lpkb, PKMX_WCHAR endstr
...
+        if (*q) {
+          temp = incxstr(q);
+          PostString(q, lpkb, temp, &ignoreOutputKeystroke);
```
Comment (mcdurdin) [inline common/core/desktop/src/kmx/kmx_processor.cpp:371]: This change ensures we cope with deadkeys which can also be found in the `m_miniContext` buffer. It outputs only the first element found at `q`.

File: windows/src/engine/keyman32/kmprocess.cpp [hunk 3]
```diff
@@ -426,6 +426,8 @@ BOOL ProcessGroup(LPGROUP gp)
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/kmprocess.cpp:426]: Changes in this file are equivalent to those in kmx_processor.cpp.

File: common/core/desktop/src/kmx/kmx_processor.cpp [hunk 4]
```diff
@@ -242,6 +243,8 @@ KMX_BOOL KMX_Processor::ProcessGroup(LPGROUP gp, KMX_BOOL *pOutputKeystroke)
 
   assert(kkp != NULL);
 
+  m_miniContextIfLen = xstrlen(kkp->dpContext) - xstrlen_ignoreifopt(kkp->dpContext);
```
Comment (mcdurdin) [inline common/core/desktop/src/kmx/kmx_processor.cpp:246]: Find the number of `if()` statements in the string; assumption is `if()` statements will be at the start of the context (this should really be validated in the compiler).

File: common/core/desktop/src/kmx/kmx_processor.cpp [hunk 5]
```diff
@@ -353,20 +356,22 @@ int KMX_Processor::PostString(PKMX_WCHAR str, LPKEYBOARD lpkb, PKMX_WCHAR endstr
...
-          m_actions.QueueAction(QIT_CHAR, *q);
-        }
+      {
+        KMX_BOOL ignoreOutputKeystroke;
+        PostString(m_miniContext, lpkb, (PKMX_WCHAR) u16chr(m_miniContext, 0), &ignoreOutputKeystroke);
         break;
+      }
       case CODE_CONTEXTEX:
+      {
+        KMX_BOOL ignoreOutputKeystroke;
```
Comment (darcywong00) [inline common/core/desktop/src/kmx/kmx_processor.cpp:366]: chore: can this get declared above l. 371?

File: windows/src/engine/keyman32/kmprocess.cpp [hunk 6]
```diff
@@ -549,18 +551,14 @@ int PostString(PWSTR str, LPMSG mp, LPKEYBOARD lpkb, PWSTR endstr)
 			  _td->app->QueueAction(QIT_BELL, 0);
 			  break;
 		  case CODE_CONTEXT:				// copy the context to the output
-			  for(q = _td->miniContext; *q; q++) {
-			    _td->app->QueueAction(QIT_CHAR, *q);
-        }
-			  break;
+        PostString(_td->miniContext, mp, lpkb, wcschr(_td->miniContext, 0));
```
Comment (darcywong00) [inline windows/src/engine/keyman32/kmprocess.cpp:554]: Does the Windows version of `PostString()` not have a corresponding parameter `ignoreOutputKeystroke`?

https://github.com/keymanapp/keyman/blob/91b0795f1d2321c40ec197efac67742889fe3809/common/core/desktop/src/kmx/kmx_processor.cpp#L361

File: common/core/desktop/src/kmx/kmx_processor.cpp (hunk 5 above)
Comment (mcdurdin) [reply common/core/desktop/src/kmx/kmx_processor.cpp:366]: I was intentionally declaring this variable locally because I didn't want confusion over its lifetime in this overly large function.

File: windows/src/engine/keyman32/kmprocess.cpp (hunk 6 above)
Comment (mcdurdin) [reply windows/src/engine/keyman32/kmprocess.cpp:554]: The Windows version has a global which is equivalent. The core version is the new one which will hopefully replace the Windows one before too long!

File: common/core/desktop/src/kmx/kmx_processor.cpp (hunk 5 above)
Comment (darcywong00) [reply common/core/desktop/src/kmx/kmx_processor.cpp:366]: Right. I was asking about having the local scope closer as in
```
if (*q) {
  temp = incxstr(q);
  KMX_BOOL ignoreOutputKeystroke;
  PostString(q, lpkb, temp, &ignoreOutputKeystroke);
}

Comment (mcdurdin) [reply common/core/desktop/src/kmx/kmx_processor.cpp:366]: Ah sorry, yes, can do something like that.

**Review by darcywong00 — APPROVED** [review]
lgtm.
I reran on Linux and tests passed for me.

nit about the ignoreOutputKeystroke declaration.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.226-beta](https://keyman.com/downloads/releases/beta/14.0.226)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.9-alpha](https://keyman.com/downloads/releases/alpha/15.0.9)
