### PR TITLE
fix(web): touch-layout fontsize property use ⛲

### LINKED ISSUE #10444: bug(web): layout font size not being properly applied
When replying to https://community.software.sil.org/t/change-font-size-of-mobile-key-caps/8305/, we found that the 'proper' way to set fontsize for a layout isn't being handled properly by Keyman Engine for Web; at a minimum, it's getting overwritten whenever the OSK's layout is refreshed.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #10444 for standard use cases.  To reach "all use cases" will take a bit more work.

## User Testing

TEST_BALOCHI_PHONETIC:  Using the Keyman app on an iPhone - preferably on an iPhone SE (emulated or real) - verify that key caps are sufficiently large.

1. Install the  `balochi_phonetic` keyboard.
2. Load the `balochi_phonetic` keyboard.
3. Verify that multiple keys have key caps spanning nearly the entire width of their respective keys.
    - Good keys to inspect:
        - 'g': `گ`
        - 'k': `ک`
        - 'e': `ے`
        - 't': `ت`

Example of the keyboard properly rendered:

image

How it looks on the current `master`, for comparison:

image

It may be wise to run the test a second time, with the latest `alpha` build, for comparison.

(This keyboard's touch-layout requests a font-size boost of +40%.)

### CODE REVIEW

File: web/src/engine/osk/src/visualKeyboard.ts [hunk 1]
```diff
@@ -1232,17 +1232,15 @@ export default class VisualKeyboard extends EventEmitter<EventMap> implements Ke
       paddedHeight = this.computedAdjustedOskHeight(this.height);
     }
 
-    let b = this.layerGroup.element as HTMLElement;
     let gs = this.kbdDiv.style;
-    let bs = b.style;
```
Comment (jahorton) [inline web/src/engine/osk/src/visualKeyboard.ts:1237]: The choice of variable names here wasn't particularly helpful.

We want to leave the layer-group font-size alone here - that's where the touch-layout fontsize property is applied, and why it was being overwritten.

**Review by mcdurdin — APPROVED** [review]
LGTM in principle, I think that makes sense.

**Review by ermshiperete — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.253-alpha](https://keyman.com/downloads/releases/alpha/17.0.253)
