### PR TITLE
[Developer] Workaround limitation in Chrome V8 with if/else ladders with KeymanWeb keyboards

### LINKED ISSUE #183: Chrome gives error "Uncaught RangeError: Maximum call stack size exceeded" loading Hieroglyphic keyboard
<a href="https://github.com/mcdurdin"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Jun 16, 2017 at 06:56 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/82_

----

https://keymanweb.com/#egy,Keyboard_hieroglyphic

However, this error does not appear in Firefox. Chrome fails to load the keyboard (in fact, it doesn't even show in the Sources tab in Developer Tools, which smells like a Chrome parser bug).

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #183 

WIP now because we need to add some more robust unit tests. Specifically want to test before & after on a whole bunch of keyboards to ensure that the changes to the compiled keyboard logic are 100% safe.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/139886:id/kvk/index.html)

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 1]
```diff
@@ -637,6 +642,142 @@ function TCompileKeymanWeb.JavaScript_ContextMatch(fkp: PFILE_KEY; context: PWid
     else Result := JavaScript_CompositeContextValue(fkp, context);
 end;
 
+function TCompileKeymanWeb.JavaScript_Rule(FTabStops, FElse: string; fgp: PFILE_GROUP; fkp: PFILE_KEY): string;
```
Comment (jahorton) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: I'm having trouble finding what is calling this method; how does it integrate into existing code?

Comment (mcdurdin) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: Lines 739 and 759 call this function

**Comment by mcdurdin** [comment]
Depends on #1652

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/148035:id/kvk/index.html)

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/148761:id/kvk/index.html)

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/148788:id/kvk/index.html)

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/148897:id/kvk/index.html)

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/148922:id/kvk/index.html)

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/148927:id/kvk/index.html)

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas [hunk 2]
```diff
@@ -1869,55 +2011,63 @@ function TCompileKeymanWeb.WriteCompiledKeyboard: string; {UTF8}
 
     fkp := fgp.dpKeyArray;
     HasRules := False;
-		for j := 0 to Integer(fgp.cxKeyArray) - 1 do    // I1964
+
+    if IsKeyboardVersion10OrLater or True then
```
Comment (darcywong00) [inline windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: Why ` or True`?

Comment (mcdurdin) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: Good catch. I should clean this one up.

File: web/testing/regression-tests/src/known-failures.js [hunk 3]
```diff
@@ -12,13 +12,20 @@
...
-  'fv_northern_tutchone': { reason: 'Chrome ladder bug #183?' },
-  'fv_southern_tutchone': { reason: 'Chrome ladder bug #183?' }, 
-  'fv_tagizi_dene': { reason: 'Chrome ladder bug #183?' }, 
+  'clavbur9': { reason: 'KCCM generated but not supported #1711' },
+  'fv_gwichin': { /*, knownGoodCompilerVersion: '12.0.333.0', knownGoodEngineVersion: '12.0.444'*/ reason: 'Chrome ladder bug #183' },
+  'fv_han': { reason: 'Chrome ladder bug #183' }, 
+  'fv_northern_tutchone': { reason: 'Chrome ladder bug #183' },
+  'fv_southern_tutchone': { reason: 'Chrome ladder bug #183' }, 
+  'fv_tagizi_dene': { reason: 'Chrome ladder bug #183' }, 
   'hieroglyphic': { reason: 'Chrome ladder bug #183' },
```
Comment (jahorton) [inline web/testing/regression-tests/src/known-failures.js]: I see these are still listed as `knownFailures`.  Is this because the old versions would break, and so generate differences with the current versions?

- [ ] What's the plan/timeline on unlisting these?

Comment (mcdurdin) [reply web/testing/regression-tests/src/known-failures.js]: The plan is to remove these from the `knownFailures` array when I cherry-pick the compiler fix to stable. Then they will build correctly with the latest known stable that the regression test pulls in.

File: windows/src/developer/TIKE/compile/CompileKeymanWeb.pas (hunk 2 above)
Comment (mcdurdin) [reply windows/src/developer/TIKE/compile/CompileKeymanWeb.pas]: And fixed. Now only applies the fix is the ladderlength registry value != 0 (default if the registry value is not set is 100).

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/148995:id/kvk/index.html)
