### PR TITLE
[KeymanWeb] The Deadkey Rework

### LINKED ISSUE #281: Deadkeys that are supposed to prevent matches are not working in KeymanWeb
<a href="https://github.com/mcdurdin"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Wednesday Oct 9, 2013 at 22:31 GMT_
_Originally opened as KD-157_

----

When a deadkey is in the middle of a context string, a context should not match if it does not reference that deadkey. For example, if the backing store is:
```
  a<dk(0)>b
```
Then:
```
  'ab' + 'c' > 'match'
```
Should not fire. This is the Keyman Engine behaviour. The reason the rule is firing is that we don't ever test deadkeys within the context match rules.

## Keyboard which replicates this bug in KeymanWeb 
```
store(&VERSION) '8.0'
store(&NAME) 'Test missing deadkey'
begin Unicode > use(main)

group(main) using keys

'ab' + 'c' > 'match'
+ 'b' > dk(1) 'b'

+ 'd' > 'd' dk(2)
'd' + 'e' > 'fail'
```

## Test cases

**Type:** "abc".
**Expected (Keyman Engine):** "a<dk>bc"
**Actual (KeymanWeb):** "match"

**Type** "de".
**Expected (Keyman Engine):** "d<dk>e"
**Actual (KeymanWeb):** "fail"

I do not have an immediate answer for a fix. It will probably require a compiler change, because updating KCM to test for deadkeys within the text will work, but testing for a deadkey at the end of the text is not going to work. This is due to the way the compiler assembles the tests, e.g.
```
  'd' dk(2) + 'E' > 'pass'
```
Compiles to:
```
  if(k.KKM(e,16400,69)&&k.KCM(1,t,"d",1)&&k.KDM(0,t,1))
```
But:
```
  'd' + 'e' > 'fail'     
```
Compiles to:
```
  if(k.KKM(e,16384,69)&&k.KCM(1,t,"d",1))
```

So we need to have some way of validating the deadkey state even for rules that don't specifically test for a deadkey.

----
MD and JD add:

One keyboard that exhibits this issue is ISIS Devangari, typing 'kxi' or 'kxh'.
We expect कइ and कह respectively. But we get the default form of कि and ख instead.

This behaviour was confirmed on 2 May 2014.
If it is a Keyman compiler bug, then the issue should be moved to KM Dev. But if it needs changes to the KMEW code, then it should stay here.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #281.

Aims to bring KeymanWeb's deadkey functionality to parity with that of Keyman Desktop, fixing existing bugs and extending the engine to allow deadkeys in stores and store-based operations.

Note that this PR should not be merged until all PRs and work listed below are complete:
- [ ] Extension: _deadkey stores_  (#617)
- [ ] Developer compiler update (Does not yet exist, to be based on the prior PR's work.)
    - [ ] `test_deadkeys` keyboard - ensure the in-repo .js is compiled from the updated Developer.
    - [ ] Integrate the new `fullContextMatch` function into KMW 10+ compiled keyboards.
        - [ ] Include a hint/warning if any rule attempts to use neighboring deadkeys and version 9-.
    - [ ] Integrate the new store format for deadkey stores.
        - [ ] Remove warning about deadkeys being incompatible with `any` and `index` for version 10+.

Checklist:
- [x] Design a robust set of deadkey-related tests (with specialized testing keyboards) to ensure implementation correctness across multiple keystrokes.
- [x] Implement a new `fullContextMatch` keyboard API function that is more directly analogous to Keyman Desktop's matching scheme.
    - [x] Implement an 'extended context cache' helper.
        - [x] Specialized unit test - everything else in `fullContextMatch` will require correctness of this helper.
    - [x] Implement the deadkey matching component of `fullContextMatch`.
        - [x] (Simple case) unit test
    - [x] Implement plain context matching.
    - [x] Implement complex context matching with `any()`, `index()`, and `context()`.
- [x] Handwrite a reference keyboard using the new API as a reference for Developer work.
    - [x] Use said handwritten reference as a stop-gap implementation to develop the full-blown deadkey support unit test.

### CODE REVIEW

**Comment by jahorton** [comment]
See `web/unit_tests/resources/keyboards/temp_test_deadkeys_hand.js` for an example (hand-converted) KMW 10 keyboard using this API.  I aimed to make it as close to Developer-style output as possible.

File: web/source/kmwcallback.ts [hunk 1]
```diff
@@ -234,6 +324,143 @@ class KeyboardInterface {
...
+        var str = rule[i] as string;
+        if(str != context[i]) {
+          mismatch = true;
+          break;
+        }
+      } else if(rule[i]['d'] !== undefined) {
+        var deadSpec = rule[i] as RuleDeadkey;
+        // We still need to set a flag here; 
+        if(deadSpec['d'] != context[i]) {
+          mismatch = true;
```
Comment (mcdurdin) [inline web/source/kmwcallback.ts]: Should we be `break`ing after any mismatch? Or could we refactor the loop into another function and short-circuit `return false on mismatch`? It'd simplify the code a little bit.

File: web/source/kmwcallback.ts [hunk 2]
```diff
@@ -7,13 +7,65 @@
...
+class ContextEx {
+  /**
+   * Existence of this property indicates that the object reflects a "context" Keyman language statement.
+   * 
+   * Value:  The offset into the current rule's context to be matched.
+   */
+  ['c']: number; // For 'c'ontext statement.
+}
+
+type ContextEntry = RuleChar | RuleDeadkey | ContextAny | RuleIndex | ContextEx;
```
Comment (mcdurdin) [inline web/source/kmwcallback.ts]: I think I'd like to see this constructed as a discriminated union -- it makes type guards simpler later on and allows us to build in compile-time checks for completeness where we work with it; see https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions

File: web/source/kmwcallback.ts [hunk 3]
```diff
@@ -567,23 +804,43 @@ class KeyboardInterface {
...
+   * @param       {string}      Ps      string
+   * @param       {number}      Pn      index
+   * Description  Returns the character from a store string according to the offset in the index array
+   */
+  _Index(Ps: string, Pn: number): string {
+    if(this._AnyIndices[Pn] < Ps._kmwLength()) {   //I3319
+      return Ps._kmwCharAt(this._AnyIndices[Pn]);
+    } else {
+      /* Should this really be possible for a compiled keyboard?  
+       * Should we throw an error / output a console.error("")?
```
Comment (mcdurdin) [inline web/source/kmwcallback.ts]: Yes, we should `console.warn` this for those working with hand-coded keyboards.

File: web/source/kmwcallback.ts [hunk 4]
```diff
@@ -567,23 +804,43 @@ class KeyboardInterface {
...
-   */    
+   */
   indexOutput(Pdn: number, Ps: string, Pn: number, Pelem: HTMLElement): void {
     this.resetContextCache();
-    if(this._AnyIndices[Pn-1] < Ps._kmwLength()) {                        //I3319
-      this.output(Pdn,Pelem,Ps._kmwCharAt(this._AnyIndices[Pn-1]));  //I3319
+    var indexChar = this._Index(Ps, Pn-1);
+    if(indexChar) {
+      this.output(Pdn,Pelem,indexChar);  //I3319
     }
```
Comment (mcdurdin) [inline web/source/kmwcallback.ts]: Should we `console.warn` on the `else` case here?

File: web/source/kmwcallback.ts [hunk 5]
```diff
@@ -776,9 +1034,9 @@ class KeyboardInterface {
    * Description  Clear all matched deadkey flags
    */       
   _DeadkeyResetMatched(): void {                   
-    var Li, _Dk = this._DeadKeys;
-    for(Li = 0; Li < _Dk.length; Li++) {
-      (<Deadkey>_Dk[Li]).reset();
+    var _Dk = this._DeadKeys;
+    for(var Li = 0; Li < _Dk.length; Li++) {
```
Comment (mcdurdin) [inline web/source/kmwcallback.ts]: We should start using ES6 style iteration, e.g.
````typescript
for(let dk of this._DeadKeys) {
  dk.reset();
}
````

File: web/source/kmwcallback.ts [hunk 6]
```diff
@@ -804,8 +1062,8 @@ class KeyboardInterface {
    * Description  Adjust saved positions of deadkeys in context
    */       
   _DeadkeyAdjustPos(Lstart: number, Ldelta: number): void {
-    var Li, _Dk = this._DeadKeys;
-    for(Li = 0; Li < _Dk.length; Li++) {
+    var _Dk = this._DeadKeys;
+    for(var Li = 0; Li < _Dk.length; Li++) {
```
Comment (mcdurdin) [inline web/source/kmwcallback.ts]:
````typescript
for(let dk of this._DeadKeys) {
  ...
````

File: web/source/kmwcallback.ts (hunk 5 above)
Comment (jahorton) [reply web/source/kmwcallback.ts]: I'll have to ensure that it's compatible with IE 9.  Heck, I think IE 11 doesn't even like `for(var i in this._DeadKeys)`, which is why I've been avoiding that style.

Granted, it may be possible if I fiddle with the TypeScript compile target, as it can do polyfills when set to use older versions of JavaScript.

File: web/source/kmwcallback.ts (hunk 2 above)
Comment (jahorton) [reply web/source/kmwcallback.ts]: Note that using a discriminated union would require Developer to compile in an extra parameter for each object that appears in a `KFCM` rule, as we'd need to add in a _discriminant_ property.  This will, of course, increase the size of v10+ keyboards.  Are we okay with this?

File: web/source/kmwcallback.ts (hunk 5 above)
Comment (mcdurdin) [reply web/source/kmwcallback.ts]: Yes, yet another one of the big advantages of using TypeScript is that it will rewrite these things for ES3 etc so we can use modern features in the language without having to wait for browser usage to catch up.

File: web/source/kmwcallback.ts (hunk 2 above)
Comment (mcdurdin) [reply web/source/kmwcallback.ts]: Good point. That may be a good enough reason to not do it.

File: web/source/kmwcallback.ts [hunk 7]
```diff
@@ -22,24 +22,32 @@ type KeyboardStore = PlainKeyboardStore; // | ComplexKeyboardStore;
...
   ['a']: KeyboardStore; // For 'a'ny statement.
 }
 
 class RuleIndex {
+  /** Discriminant field - 'i' for `index()`.
+   */
+  ['t']: 'i';
+  
   /**
    * Existence of this property indicates the object reflects an "index" statement.
```
Comment (mcdurdin) [inline web/source/kmwcallback.ts]: Should remove this comment now

File: web/source/kmwcallback.ts [hunk 8]
```diff
@@ -22,24 +22,32 @@ type KeyboardStore = PlainKeyboardStore; // | ComplexKeyboardStore;
 type RuleChar = string;
 
 class RuleDeadkey {
```
Comment (mcdurdin) [inline web/source/kmwcallback.ts]: should these be classes or interfaces; from a structural point of view should they all inherit from a base interface `RuleComponent`?

File: web/source/kmwcallback.ts [hunk 9]
```diff
@@ -414,40 +427,56 @@ class KeyboardInterface {
...
-        }
-      } else if(rule[i]['i'] !== undefined) {
-        var indexSpec = rule[i] as RuleIndex;
-        var ch = this._Index(indexSpec.i.s, indexSpec.i.o);
+      } else {
+        // TypeScript needs a cast to this intermediate type to do its discriminated union magic.
+        var r = rule[i] as ContextNonCharEntry;
+        switch(r.t) {
+          case 'd':
+            var deadSpec = r as RuleDeadkey;
```
Comment (mcdurdin) [inline web/source/kmwcallback.ts]: Do we need this because the discriminated union magic should be constraining the type of `r` to `RuleDeadkey` now, shouldn't it?

File: web/source/kmwcallback.ts (hunk 8 above)
Comment (jahorton) [reply web/source/kmwcallback.ts]: I mean, we can write that in TypeScript, but since these correspond to incoming objects without the prototype information, I felt it better to have them merely be what they actually are - raw type specifications.
