### PR TITLE
fix(windows): external links should open externally

### LINKED ISSUE #3461: [Windows] Links in Download Keyboard dialog do not open in external browser
Clicking an external link (e.g. Source) in the Download Keyboard dialog does not open in an external browser, like it should. Instead, it opens a new window in the KMShell process, which then crashes Keyman when it is closed.

For clarity, an external link is any that is not under `https://keyman.com/keyboards` (or the staging/dev variants)

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #3461.

### CODE REVIEW

File: windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas [hunk 1]
```diff
@@ -117,7 +118,17 @@ procedure TfrmInstallKeyboardFromWeb.TntFormCreate(Sender: TObject);
...
+  // a bit of a shame, because we try to keep our internal knowledge to /go/ urls on
+  // keyman.com. However, there is not really any great way around this that I've found,
+  // which allows us to handle internal navigation on the keyboard search and still lets
+  // us open other URLs that may be in the search results in an external browser.
+  Handled :=
+    TRegEx.IsMatch(Url, URLPath_RegEx_MatchKeyboardsInstall) or       // capture https://keyman.com/keyboards/install/*
+    (not TRegEx.IsMatch(Url, UrlPath_RegEx_MatchKeyboardsRoot) and    // don't capture https://keyman.com/keyboards*
+    not Url.StartsWith('keyman:') and                                 // don't capture keyman:*
+    not IsLocalUrl(Url) and                                           // don't capture the external frame or its resources
+    not TRegEx.IsMatch(Url, UrlPath_RegEx_MatchKeyboardsGo));         // don't capture the launch url https://keyman.com/go/windows/download-keyboards
```
Comment (mcdurdin) [inline windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas:131]: @jahorton @darcywong00 @ermshiperete this pattern here is similar to what you'll need in your platform implementations for determining if a URL in the embedded download dialog is internal or external.

File: windows/src/global/delphi/general/Upload_Settings.pas [hunk 2]
```diff
@@ -54,7 +54,12 @@ interface
   URLPath_Community = '/go/'+SKeymanVersion+'/community';
 
   // Keyboard download and installation
-  URLPath_RegEx_MatchKeyboardsInstall = '^http(?:s)?://[^/]+/keyboards/install/([^?/]+)(?:\?(.+))?$';
+  URLPath_RegEx_MatchKeyboardsInstall = '^http(?:s)?://keyman(?:-staging)?\.com(?:\.local)?/keyboards/install/([^?/]+)(?:\?(.+))?$';
+                                  // e.g. https://keyman.com/keyboards/install/foo
+  UrlPath_RegEx_MatchKeyboardsRoot = '^http(?:s)?://keyman(?:-staging)?\.com(?:\.local)?/keyboards([/?].*)?$';
+                               // e.g. http://keyman.com.local/keyboards/foo
+  UrlPath_RegEx_MatchKeyboardsGo = '^http(?:s)?://keyman(?:-staging)?\.com(?:\.local)?/go/windows/[^/]+/download-keyboards';
```
Comment (darcywong00) [inline windows/src/global/delphi/general/Upload_Settings.pas:61]: Does the regex need to go all the way to the end (like _MatchKeyboardsRoot)?
`([/?].*)?$`

File: windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas (hunk 1 above)
Comment (jahorton) [reply windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas:131]: ... uh-huh.  For what purpose(s)?  To block any external links?

Comment (jahorton) [reply windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas:131]: Is the plan to open any external links (from keyboard search) outside the app?  So we vet any links opened during keyboard search and kick the user out to a browser if the link isn't also part of the keyboard search?

Comment (mcdurdin) [reply windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas:131]: > So we vet any links opened during keyboard search and kick the user out to a browser if the link isn't also part of the keyboard search?

Correct.

Comment (mcdurdin) [reply windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas:131]: Although ... that pattern makes heaps of sense on desktop. I'm not so sure it works as well on mobile devices. Something to think about.

Comment (jahorton) [reply windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas:131]: It's... not a bad paradigm for iOS, at least recent versions.  Whenever the user wishes to return to the app, there's a "Back to Keyman" button at the top right.

File: windows/src/global/delphi/general/Upload_Settings.pas (hunk 2 above)
Comment (mcdurdin) [reply windows/src/global/delphi/general/Upload_Settings.pas:61]: It's not terribly important; it probably should...

**Comment by mcdurdin** [comment]
Sorry, didn't mean to merge #3604 into this...

File: windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas [hunk 3]
```diff
@@ -117,7 +118,17 @@ procedure TfrmInstallKeyboardFromWeb.TntFormCreate(Sender: TObject);
...
 begin
-  Handled := TRegEx.IsMatch(Url, UrlPath_RegEx_MatchKeyboardsInstall);
+  // This introduces some deeper knowledge of URL paths in Keyman Configuration, which is
+  // a bit of a shame, because we try to keep our internal knowledge to /go/ urls on
+  // keyman.com. However, there is not really any great way around this that I've found,
+  // which allows us to handle internal navigation on the keyboard search and still lets
+  // us open other URLs that may be in the search results in an external browser.
+  Handled :=
+    TRegEx.IsMatch(Url, URLPath_RegEx_MatchKeyboardsInstall) or       // capture https://keyman.com/keyboards/install/*
+    (not TRegEx.IsMatch(Url, UrlPath_RegEx_MatchKeyboardsRoot) and    // don't capture https://keyman.com/keyboards*
```
Comment (darcywong00) [inline windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas:128]: I'm a little confused why we don't capture https://keyman.com/keyboards*

e.g. https://keyman.com/keyboards/khmer_angkor

Shouldn't we treat as an internal link and handle it?

Comment (darcywong00) [reply windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas:128]: "handle" as in render it in the embedded keyboard search instead of kicking to external browser

Comment (mcdurdin) [reply windows/src/desktop/kmshell/install/UfrmInstallKeyboardFromWeb.pas:128]: Handle means that we are capturing the URL and not letting it go through to the embedded browser; it is then processed in the `cefBeforeBrowse` function (`cefBeforeBrowseSync` happens in the CEF thread but we have to do the actual processing in the main thread).

**Review by darcywong00 — APPROVED** [review]
lgtm
