### PR TITLE
fix(windows): SMP-aware deletion in TSF-aware apps

### LINKED ISSUE #4196: bug(windows):  Microsoft word inserts invalid characters with sequences with SMP context
**Describe the bug**
Microsoft Word 365 inserts an invalid character with sequences that have SMP characters as the immediate previous context.

For instance, sequences such as the below result in such behavior.

'𑌇' + "i" > '𑌈'
'𑍍' + "i" > '𑌿' 
'𑍍' + "o" > '𑍋' 

They work perfectly in other apps but for some reason, they do not work with MS Word.

However, sequences without any context seem to work fine.

+ "p" > '𑌪' '𑍍'
+ "i" > '𑌇'

**To Reproduce**
Install the Keyman keyboard from the zip file and compose text in MS Word 365. The zip file includes both the source and the compiled keyboard.

[grantha_unicode_phonetic.zip](https://github.com/keymanapp/keyman/files/5726860/grantha_unicode_phonetic.zip)

If it helps, you can download the relevant font from here:

https://github.com/googlefonts/noto-fonts/tree/master/unhinted/otf/NotoSansGrantha

**Expected behavior**
Invalid characters should not appear

**Screenshots**

image

The sequences to type are:

p pa pi po i ii

---

**Keyman for Windows:**
 - OS:  Windows 10
 - Keyman version: Version 14.0.214-beta
 - Target Application: Microsoft Word 365

**Keyman Developer:**
 - OS: Windows 10
 - Keyman Developer version: Version 14.0.214.0

---

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4196.

When deleting characters in a TSF-aware app, we must delete both halves of a surrogate pair. This behaviour differs from legacy apps, where a single backspace is usually sufficient to delete both characters.

Truly ancient apps that do not know about Unicode surrogate pairs are not going to delete both halves with a single backspace event. Fortunately, these are few and far between; we would handle them on a case-by-case basis if support questions for them arise.

When we come to integrating Keyman Core into Keyman for Windows, there will need to be some careful checking of surrogate pair support, as it is likely that the handling will need to change.

### CODE REVIEW

File: windows/src/engine/keyman32/kmprocess.cpp [hunk 1]
```diff
@@ -451,24 +451,30 @@ BOOL ProcessGroup(LPGROUP gp)
...
-	{
-		for(p = _td->miniContext; *p; p = incxstr(p))
-		{
-			if(*p == UC_SENTINEL)
-				switch(*(p+1))
-				{
-			    case CODE_DEADKEY: _td->app->QueueAction(QIT_BACK, BK_DEADKEY); break;
-					case CODE_NUL: break;	// 11 Aug 2003 - I25(v6) - mcdurdin - CODE_NUL context support
+	if(*p != UC_SENTINEL || *(p+1) != CODE_CONTEXT) {
+		for(PWSTR mcp = decxstr(wcschr(_td->miniContext, 0), _td->miniContext); mcp != NULL; mcp = decxstr(mcp, _td->miniContext)) {
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/kmprocess.cpp:455]: We need to add these in reverse order so we get the correlation with deadkey and surrogate pair elements.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.233-beta](https://keyman.com/downloads/releases/beta/14.0.233)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)
