### PR TITLE
[Web] Publishes the alignInputs() function as API for touch-alias correction.

### LINKED ISSUE #64: Touch Element Resize Event Doesn't Work
When using a device with a touch screen, the blocking elements added by KeymanWeb are created at the same size as their base input. To deal with the issue of inputs that change size, those inputs get a "resize" event added to them that then calls resizeInput on the blocker element on top of them.

The problem is that resize events seem to [only be supported by the window](http://stackoverflow.com/a/18662439/5857510) , meaning they cannot be fired (even manually) in the input element.

I tried to get around this by calling the resizeInput function on the blocking element, but that didn't work as anticipated. While the blocking element expanded to fully cover the expanded size of the input, the fake input inside of it did not. It instead remained the same size and moved position to the top left corner of the input.

I've attached three screenshots showing the problem. The first shows the input being covered as expected, the second what happens when the input is made larger (which was also programmed to fire the resize event), and the third what happens after calling the resizeInput function on the blocking element (specifically the one with the "keymanweb-input" class).

1. before element is bigger

2. after element is bigger

3. after resizeinput

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #64.

While the underlying issue has likely already been resolved, this PR publishes a method for web-developer use to ensure that it stays permanently solved.  Should we accidentally break things with our automatic rotation handling, this can be called by developers with their own detection methods to correct the resulting mistakes as a workaround.

At the same time, this PR reworks the method's spec to be cleaner and more intuitive for web developer use, splitting off the 'hide' functionality of the method's old version into its own, distinct method and extending the new method to allow specific elements to be requested, rather than all of them.

### CODE REVIEW

File: web/source/kmwnative.ts [hunk 1]
```diff
@@ -146,29 +146,62 @@ if(!window['keyman']['initialized']) {
...
+          }
+        })      
+      }
+    }
+
     /**
      * Align all input fields with underlying elements after a rotation, resize, or change of element font
      * and/or set visibility     
      * 
      *  @param  {boolean}   align    align and make visible, else hide
```
Comment (darcywong00) [inline web/source/kmwnative.ts]: This is now hideInputs with no parameter
