### PR TITLE
fix(linux): Fix reordering of output

### LINKED ISSUE #1489: bug(linux): Backspacing and reordering is not working well in Firefox, Terminal
Keyman does not appear to be working correctly in Firefox, Terminal:  reordering, e.g. with Khmer Angkor, xEjmr is not​ producing ខ្មែរ (normally typed xjmEr).

### LINKED ISSUE #4028: bug(linux): Ubuntu 20.10: backspace behaviour in search bar
When typing with a Keyman keyboard in the Gnome Shell search bar, it takes more backspaces to remove the characters then what you've typed. E.g. with EuroLatin keyboard, typing ":aa" requires 5 backspace to delete the text.

### LINKED ISSUE #4029: bug(linux): Ubuntu 20.10: wrong characters displayed in search bar
When typing with a Keyman keyboard in the Gnome Shell search bar, characters don't get properly replaced while typing.
E.g. with the EuroLatin Keyman keyboard, typing ":aa" should result in "äa", but actual result is ":äa".

### LINKED ISSUE #4030: bug(linux): Ubuntu 18.04: Keyman keyboards don't work in search bar
When typing with a Keyman keyboard in the Gnome Shell search bar, typing the characters defined in the Keyman keyboard doesn't work - the characters from the English default keyboard get inserted.

### LINKED ISSUE #4505: bug(linux): Backspacing and reordering not working correct in Anki
Keyman does not appear to be working correctly in Anki: reordering, e.g. with Khmer Angkor, xEjmr is not​ producing ខ្មែរ (normally typed xjmEr). This is similar to #1489 for Firefox.

For the khmer_angkor keyboard, I'll give baseline results with Anki. It's important to understand that when I type `xEjm`, the khmer_angkor keyboard reorders the output at the time the `m` key is pressed, to give the equivalent of `xjmE`. The `r` is extraneous (but forms part of the complete word)...  

* Ubuntu 18.04
* Anki 2.1.40

| Correct order key | Correct order result | vs | Alternate keying order | Alternate order result |
| --- | --- | --- | --- | --- |
| `x` | `U+1781` | | `x` | `U+1781` |
| `xj` | `U+1781 U+17D2` | | `xE` | `U+1781 U+17C2` |
| `xjm` | `U+1781 U+17D2 U+1798` | | `xEj` | `U+1781 U+17C2 U+17D2` |
| `xjmE` | `U+1781 U+17D2 U+1798 U+17C2` | | `xEjm` | `U+1781 U+17c2 U+17d2 U+17d2 U+1798 U+17c2 *` |
| `xjmEr` | `U+1781 U+17D2 U+1798 U+17C2 U+179A` | | `xEjmr` | `U+1781 U+17c2 U+17d2 U+17d2 U+1798 U+17c2 U+179a *` |

\* These are incorrect results

## Backspacing

Starting with ខ្មែរ (correct order key sequence) and pressing backspace:
after 1 backspace: ខ្មែ
after 2-5 backspaces: ខ្មែ
after 6 backspaces: ខ្ម
after 7 backspaces: ខ្
after 8-9 backspaces: ខ្
after 10 backspaces: ខ
after 11 backspaces:

Expected: all codepoints are gone after 5 backspace; each backspace deletes one codepoint in the reverse order of the correct order key sequence.

### LINKED ISSUE #5510: bug(linux): Chrome(ium) / Electron apps don't "delete surrounding text"
**Describe the bug**
In Ubuntu / Wasta-Linux (all versions), when using Keyman keyboards or older ibus-kmfl keyboards in Chrome(ium) - basically ALL browsers except Firefox at this point, and also Electron apps (such as vscode or skype, or the upcoming PTLite), then multiple key sequences that need "delete surrounding text" do not delete the initial character when producing the resulting character.

For example, we use `;` as a "visible trigger" for users, so `; n` is typed to produce `ŋ`. When typing the sequence, the `;` should display, then when `n` is pressed the `;` should be deleted and `ŋ` is inserted. However, `;ŋ` is displayed.

For another example, if you use the "SIL Ethiopic" keyboard, typing `m u` should first display `ም` when `m` is pressed, then delete it and replace with `ሙ` when `u` is pressed. Instead, the `ም` isn't deleted and `ምሙ` displays.

I believe this may be discussed in other issues, but I wasn't certain which one to add to, so this may be listed as a duplicate.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Ubuntu / Wasta-Linux 20.04
 - Keyman version: 14.0.276-1+focal1
 - Target Application: Chromium, Visual Studio Code, Skype, Signal, Telegram, etc.

---

Additional Note: In Firefox, when using "Google Docs" the same problem exists. I have NOT seen it in any other site, so I think it is specific to Google. It may be best for me to report that as a separate issue.

### LINKED ISSUE #6639: bug(Linux): Khmer, IPA (SIL) Keyboards are not working as expected in LibreOffice Writer, TextEditor in Bionic Linux OS
**Describe the bug**
Typing on LibreOffice Writer or Text Editor produces wrong outputs but working correctly while typing it on browser like Mozilla Firefox. 

**To Reproduce**
1. Install Keyman 15.0.248-beta build in Bionic Linux OS.
2. Download and install Khmer, IPA (SIL) Keyboards using Configuration dialog. 
3. Open LibreOffice Writer Document. 
4. Change the Keyman Keyboard into Khmer. 
5. Type xEjmr.
6. I noticed that it shows wrong output ខែ្្មែរ
7. Change the Keyman Keyboard into IPA (SIL).
8. Type n>, it shows wrong output nŋ

**Expected behavior**
1. Using Khmer Keyboard, typing xEjmr should show up ខ្មែរ
2. Using IPA (SIL) Keyboard, typing n> should show up ŋ

**Screenshots**

..in LibreOffice Writer:
 

..in Text Editor:
 

..in Mozilla Firefox Browser:
 

---

**Keyman for Bionic Linux:**
 - OS: Ubuntu 18.04 Bionic Linux OS
 - Keyman version: Keyman 15.0.248-beta 
 - Target Application: LibreOffice Writer, Text Editor

---

**Keyboard 1**
 - Keyboard name:  khmer_angkor
 - Keyboard version: 1.2
 - Language name:  Khmer

---

**Keyboard 2**
- Keyboard name:  Undetermined (IPA (SIL))
 - Keyboard version: 1.8.6
 - Language name:  IPA (SIL)

**Additional context**
Using the same Keyman Keyboards in Mozilla Firefox browser, then it is showing the expected texts.

### PR DESCRIPTION
**Pull request by ermshiperete**
[Quick link to the test results](https://github.com/keymanapp/keyman/pull/7079#issuecomment-1218025741)

This change implements a commit queue which allows to control the order of the output. This ensures that any backspace we generate will be processed before the character we're adding.

**Requires changes in ibus** ([surrounding text fix](https://github.com/ibus/ibus/pull/2436) (see #7072) and [prefilter change](https://github.com/ibus/ibus/pull/2440)).

* Fixes #1489.
* Fixes #4028.
* Fixes #4029.
* Fixes #4030.
* Fixes #4505.
* Fixes #5510.
* Fixes #6639.

# User Testing

## Preparations

- The tests should be run on these Linux platforms:
  - **GROUP_BIONIC**: Ubuntu 18.04 Bionic with Gnome Shell and X11
  - **GROUP_FOCAL**: Ubuntu 20.04 Focal with Gnome Shell and X11
  - **GROUP_JAMMY_X11**: Ubuntu 22.04 Jammy with Gnome Shell and X11
  - **GROUP_WASTA**: Wasta 20.04 with Cinnamon

- Add the Keyman Test ppa: 
  ```bash
  sudo add-apt-repository ppa:keymanapp/keyman-test
  ```

- Install all updates
  ```bash
  sudo apt update
  sudo apt upgrade
  ```

- Verify that you have the updated ibus version required to test this PR
  - Run the following command
    ```bash
    dpkg -l ibus
    ```
  - This shows a table similar to this:
    ```
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name           Version            Architecture Description
    +++-==============-==================-============-===========================>
    ii  ibus           1.5.26-4sil1~jammy amd64        Intelligent Input Bus - core
    ```
    The exact version depends on the platform. The important part is the **sil** in the version number - that needs to be
    there, otherwise you don't have updated ibus version.

- On Ubuntu 22.04 Jammy, install the Firefox .deb package (not snap) - this is not needed for older distributions
  - Run the following commands:
    ```bash
    sudo apt remove firefox
    snap remove firefox
    sudo add-apt-repository ppa:mozillateam/ppa
    echo '
    Package: *
    Pin: release o=LP-PPA-mozillateam
    Pin-Priority: 1001
    ' | sudo tee /etc/apt/preferences.d/mozilla-firefox
    echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox
    sudo apt install firefox
    ```
  - when testing in Firefox, test in the address bar.

- On Ubuntu 22.04 Jammy, Ubuntu 20.04 Focal and Wasta install the Chromium .deb package (not snap) - this is not needed for Bionic
  - Run the following commands:
    ```bash
    sudo add-apt-repository ppa:saiarcot895/chromium-beta
    sudo apt install chromium-browser
    ```
  - when testing in Chromium, open https://keyman.com/keyboards and **type in the "Keyboard search" field**

- Install Anki
  - Download [Qt5 version of Anki](https://apps.ankiweb.net/#linux) (For Bionic use the "Download Anki for 2016+ Linux" version)
  - Run the following commands
    ```bash
    sudo apt update
    sudo apt install zstd
    tar xaf Downloads/anki-2.*-linux-qt5.tar.zst
    cd anki-2.*-linux
    sudo ./install.sh
    sudo apt install libxcb-xinerama0
    ```
    (for Bionic, the first line has to be: `tar xfx anki-2.*-linux.tar.bz2`)
  - When testing in Anki, select e.g. "Tools"/"Study Deck"

- [Install build artifacts of this PR](https://github.com/keymanapp/keyman/wiki/How-to-test-artifacts-from-pull-requests-for-Keyman-for-Linux)

- Reboot

- Install the following keyboards in Keyman:
  * [IPA (SIL)](https://keyman.com/keyboards/sil_ipa)
  * [Korean KORDA Jamo (SIL)](https://keyman.com/keyboards/sil_korda_jamo)
  * [Khmer Angkor](https://keyman.com/keyboards/khmer_angkor)
  * [Vedic Sanskrit Devanagari Phonetic (ITRANS)](https://keyman.com/keyboards/itrans_devanagari_sanskrit_vedic)

## SUITE_WRITER: LibreOffice Writer

- **GROUP_BIONIC**: Ubuntu 18.04 Bionic with Gnome Shell and X11
- **GROUP_FOCAL**: Ubuntu 20.04 Focal with Gnome Shell and X11
- **GROUP_JAMMY_X11**: Ubuntu 22.04 Jammy with Gnome Shell and X11
- **GROUP_WASTA**: Wasta 20.04 with Cinnamon

Open LibreOffice Writer.

### Tests

- **TEST_WRITER_IPA:** Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_WRITER_KO:** Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_WRITER_HI:** Switch to "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard. Type `shrI`. Verify that the result is "श्री". (If the result looks wrong, select all text and change the font to "Siddhanta")
- **TEST_WRITER_KM:** Switch to "Khmer Angkor" keyboard. Type `xEjmr`. Verify that the output is "ខ្មែរ".
- **TEST_WRITER_KM_BS:** With the output "ខ្មែរ" still being displayed, press Backspace key 5 times. Verify that after each keystroke a part of the string is removed and after the 5th backspace the entire word is deleted.

## SUITE_GEDIT: gedit

- **GROUP_BIONIC**: Ubuntu 18.04 Bionic with Gnome Shell and X11
- **GROUP_FOCAL**: Ubuntu 20.04 Focal with Gnome Shell and X11
- **GROUP_JAMMY_X11**: Ubuntu 22.04 Jammy with Gnome Shell and X11
- **GROUP_WASTA**: Wasta 20.04 with Cinnamon

Open gedit.

### Tests

- **TEST_GEDIT_IPA:** Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_GEDIT_KO:** Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_GEDIT_HI:** Switch to "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard. Type `shrI`. Verify that the result is "श्री".
- **TEST_GEDIT_KM:** Switch to "Khmer Angkor" keyboard. Type `xEjmr`. Verify that the output is "ខ្មែរ".
- **TEST_GEDIT_KM_BS:** With the output "ខ្មែរ" still being displayed, press Backspace key 5 times. Verify that after each keystroke a part of the string is removed and after the 5th backspace the entire word is deleted.

## SUITE_FIREFOX: Firefox

- **GROUP_BIONIC**: Ubuntu 18.04 Bionic with Gnome Shell and X11
- **GROUP_FOCAL**: Ubuntu 20.04 Focal with Gnome Shell and X11
- **GROUP_JAMMY_X11**: Ubuntu 22.04 Jammy with Gnome Shell and X11
- **GROUP_WASTA**: Wasta 20.04 with Cinnamon

Open https://keyman.com/keyboards in Firefox.

**NOTE:** If the output looks wrong, copy the text from the browser and paste it into gedit and verify that it there.

### Tests

- **TEST_FIREFOX_IPA:** Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_FIREFOX_KO:** Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_FIREFOX_HI:** Switch to "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard. Type `shrI`. Verify that the result is "श्री".
- **TEST_FIREFOX_KM:** Switch to "Khmer Angkor" keyboard. Type `xEjmr`. Verify that the output is "ខ្មែរ".
- **TEST_FIREFOX_KM_BS:** With the output "ខ្មែរ" still being displayed, press Backspace key 5 times. Verify that after each keystroke a part of the string is removed and after the 5th backspace the entire word is deleted.

## SUITE_CHROMIUM: Chromium

- **GROUP_BIONIC**: Ubuntu 18.04 Bionic with Gnome Shell and X11
- **GROUP_FOCAL**: Ubuntu 20.04 Focal with Gnome Shell and X11
- **GROUP_JAMMY_X11**: Ubuntu 22.04 Jammy with Gnome Shell and X11
- **GROUP_WASTA**: Wasta 20.04 with Cinnamon

Open Chromium browser.

**NOTE:** If the output looks wrong, copy the text from the browser and paste it into gedit and verify that it there.

### Tests

- **TEST_CHROMIUM_IPA:** Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_CHROMIUM_KO:** Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_CHROMIUM_HI:** Switch to "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard. Type `shrI`. Verify that the result is "श्री".
- **TEST_CHROMIUM_KM:** Switch to "Khmer Angkor" keyboard. Type `xEjmr`. Verify that the output is "ខ្មែរ".
- **TEST_CHROMIUM_KM_BS:** With the output "ខ្មែរ" still being displayed, press Backspace key 5 times. Verify that after each keystroke a part of the string is removed and after the 5th backspace the entire word is deleted.

## SUITE_TERMINAL: gnome-terminal

- **GROUP_BIONIC**: Ubuntu 18.04 Bionic with Gnome Shell and X11
- **GROUP_FOCAL**: Ubuntu 20.04 Focal with Gnome Shell and X11
- **GROUP_JAMMY_X11**: Ubuntu 22.04 Jammy with Gnome Shell and X11
- **GROUP_WASTA**: Wasta 20.04 with Cinnamon

Open Terminal.

### Tests

- **TEST_TERMINAL_IPA:** Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_TERMINAL_KO:** Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_TERMINAL_HI:** Switch to "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard. Type `shrI`. Verify that the result is "श्री".
- **TEST_TERMINAL_KM:** Switch to "Khmer Angkor" keyboard. Type `xjmEr` (Note the different character order!). **Copy the output characters from terminal and paste them in gedit.** Verify that the pasted text is "ខ្មែរ". (Terminal has a rendering problem with some Khmer characters, so the output in terminal looks wrong, even though Keyman added the correct characters.)
- **TEST_TERMINAL_KM_BS:** With the output of the previous test still being displayed, press Backspace key 5 times. Verify that after each keystroke a part of the string is removed and after the 5th backspace the entire word is deleted.

## SUITE_ANKI: Anki

- **GROUP_BIONIC**: Ubuntu 18.04 Bionic with Gnome Shell and X11
- **GROUP_FOCAL**: Ubuntu 20.04 Focal with Gnome Shell and X11
- **GROUP_JAMMY_X11**: Ubuntu 22.04 Jammy with Gnome Shell and X11
- **GROUP_WASTA**: Wasta 20.04 with Cinnamon

Open Anki.

### Tests

- **TEST_ANKI_IPA:** Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_ANKI_KO:** Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_ANKI_HI:** Switch to "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard. Type `shrI`. Verify that the result is "श्री" (If the result looks wrong, copy/paste it in text editor and verify there).
- **TEST_ANKI_KM:** Switch to "Khmer Angkor" keyboard. Type `xEjmr`. Verify that the output is "ខ្មែរ".
- **TEST_ANKI_KM_BS:** With the output "ខ្មែរ" still being displayed, press Backspace key 5 times. Verify that after each keystroke a part of the string is removed and after the 5th backspace the entire word is deleted.

## SUITE_SEARCHBAR: Searchbar in gnome-shell

- **GROUP_BIONIC**: Ubuntu 18.04 Bionic with Gnome Shell and X11
- **GROUP_FOCAL**: Ubuntu 20.04 Focal with Gnome Shell and X11
- **GROUP_JAMMY_X11**: Ubuntu 22.04 Jammy with Gnome Shell and X11
- **GROUP_WASTA**: Wasta 20.04 with Cinnamon

Press Windows key to open searchbar.

### Tests

- **TEST_SEARCHBAR_IPA:** Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_SEARCHBAR_KO:** Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_SEARCHBAR_HI:** Switch to "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard. Type `shrI`. Verify that the result is "श्री".
- **TEST_SEARCHBAR_KM:** Switch to "Khmer Angkor" keyboard. Type `xEjmr`. Verify that the output is "ខ្មែរ".
- **TEST_SEARCHBAR_KM_BS:** With the output "ខ្មែរ" still being displayed, press Backspace key 5 times. Verify that after each keystroke a part of the string is removed and after the 5th backspace the entire word is deleted.

### CODE REVIEW

**Comment by mcdurdin** [comment]
Rough diagram of IPC

```mermaid

sequenceDiagram
    Note right of Client: _key_snooper_cb receives new key event
    Client-)IBusDaemon: ProcessKeyEvent
    IBusDaemon-)EngineDBus: ProcessKeyEvent
    EngineDBus-)EngineProcessor: process-key-event
    activate EngineProcessor
    EngineProcessor-)IBusDaemon: ForwardKeyEvent +PREFILTER
    deactivate EngineProcessor
    IBusDaemon-)Client: ForwardKeyEvent +PREFILTER

    Note right of Client: _key_snooper_cb receives forwarded key event.
    Note right of Client: +PREFILTER means we reprocess the key event
    Client-)IBusDaemon: ProcessKeyEvent +PREFILTER
    IBusDaemon-)EngineDBus: ProcessKeyEvent +PREFILTER
    EngineDBus-)EngineProcessor: process-key-event +PREFILTER
    activate EngineProcessor
    EngineProcessor-)IBusDaemon: bksp + text emitted
    deactivate EngineProcessor
    IBusDaemon-)Client: bksp + text emitted
```

File: linux/ibus-keyman/src/engine.c [hunk 1]
```diff
@@ -692,16 +738,51 @@ process_capslock_action(
...
+      g_error("Overflow of keyman commit_queue!");
+      // TODO: log to Sentry
+      keyman->commit_item--;
+    }
+
+    // Forward a fake key event to get the correct order of events so that any backspace key we
+    // generated will be processed before the character we're adding. We need to send a
+    // valid keyval/keycode combination so that it doesn't get swallowed by GTK but which
+    // isn't very likely used in real keyboards. F24 seems to work for that.
+    ibus_engine_forward_key_event((IBusEngine*)keyman, KEYMAN_NOCHAR_KEYSYM, KEYMAN_F24_KEYCODE_OUTPUT_SENTINEL, IBUS_PREFILTER_MASK);
```
Comment (ermshiperete) [inline linux/ibus-keyman/src/engine.c:775]: @mcdurdin Do we need to forward the fake key event if the app supports surrounding text?

Comment (ermshiperete) [reply linux/ibus-keyman/src/engine.c:757]: With the [prefilter version of ibus](https://github.com/keymanapp/ibus/pull/1) we get warnings with gedit:

```
(gedit:2437): Gdk-WARNING **: 17:52:19.388: Event with type 8 not holding a GdkDevice. It is most likely synthesized outside Gdk/GTK+

(gedit:2437): Gdk-WARNING **: 17:52:19.388: Event with type 9 not holding a GdkDevice. It is most likely synthesized outside Gdk/GTK+
```

Strangely enough we don't get these warnings with Chromium.

Comment (mcdurdin) [reply linux/ibus-keyman/src/engine.c:757]: Can we extend the comment above to reference the issue with Chromium doing its 'rate limiting' of hotkey-type keystrokes?

File: linux/ibus-keyman/src/engine.c [hunk 2]
```diff
@@ -769,13 +832,24 @@ ibus_keyman_engine_process_key_event(
...
   g_message("-----------------------------------------------------------------------------------------------------------------");
   g_message(
-      "DAR: ibus_keyman_engine_process_key_event - keyval=0x%02x keycode=0x%02x, state=0x%02x, isKeyDown=%d", keyval, keycode,
-      state, isKeyDown);
+      "DAR: ibus_keyman_engine_process_key_event - keyval=0x%02x keycode=0x%02x, state=0x%02x, isKeyDown=%d, supports_prefilter=%d", keyval, keycode,
+      state, isKeyDown, engine->client_capabilities & IBUS_CAP_PREFILTER);
+
+  // This keycode is a fake keycode that we send when it's time to commit the text, ensuring the
+  // correct output order of backspace and text.
+  if ((engine->client_capabilities & IBUS_CAP_PREFILTER) && keycode == KEYMAN_F24_KEYCODE_OUTPUT_SENTINEL &&
```
Comment (ermshiperete) [inline linux/ibus-keyman/src/engine.c:848]: Good thing we check `keycode` and not `keyval` since Chromium sends us a different value than what we used in the forward key event (from Chromium: 0x1008ff43, we sent: 0x100fdd0). Other apps send us the same value back.

File: linux/ibus-keyman/src/engine.c [hunk 3]
```diff
@@ -639,18 +661,25 @@ process_persist_action(
...
-    ibus_keyman_engine_commit_string(keyman, keyman->char_buffer);
-    g_free(keyman->char_buffer);
-    keyman->char_buffer = NULL;
+static gboolean
+process_emit_keystroke_action(IBusKeymanEngine *keyman) {
+  IBusEngine *engine = (IBusEngine *)keyman;
+  if ((engine->client_capabilities & IBUS_CAP_PREFILTER) &&
+      !(engine->client_capabilities & IBUS_CAP_SURROUNDING_TEXT)) {
+    keyman->commit_item->emitting_keystroke = TRUE;
+  } else {
```
Comment (mcdurdin) [inline linux/ibus-keyman/src/engine.c:670]: We could invert this condition and combine it with ll671 and move the ` keyman->commit_item->emitting_keystroke = TRUE;` out of the if statement to avoid repeating it and on ll676?

File: linux/ibus-keyman/src/engine.c [hunk 4]
```diff
@@ -678,16 +707,59 @@ process_capslock_action(
...
-static gboolean process_end_action(IBusKeymanEngine *keyman) {
-  keyman->firstsurrogate = 0;
-  if (keyman->char_buffer != NULL) {
-    ibus_keyman_engine_commit_string(keyman, keyman->char_buffer);
-    g_free(keyman->char_buffer);
-    keyman->char_buffer = NULL;
+static void
+commit_text(IBusKeymanEngine *keyman) {
+  g_assert(keyman != NULL);
+  if (keyman->commit_item > keyman->commit_queue) {
```
Comment (mcdurdin) [inline linux/ibus-keyman/src/engine.c:713]: Is this effectively an input condition? We could invert the test and return early and avoid nesting. (Do we want an assertion or log? I don't think so?)

File: linux/ibus-keyman/src/engine.c [hunk 5]
```diff
@@ -678,16 +707,59 @@ process_capslock_action(
...
-    keyman->emitting_keystroke = FALSE;
-    return FALSE;
+}
+
+static gboolean
+process_end_action(IBusKeymanEngine *keyman) {
+  g_assert(keyman != NULL);
+  IBusEngine *engine = (IBusEngine *)keyman;
+  if ((engine->client_capabilities & IBUS_CAP_PREFILTER) &&
+      !(engine->client_capabilities & IBUS_CAP_SURROUNDING_TEXT)) {
```
Comment (mcdurdin) [inline linux/ibus-keyman/src/engine.c:734]: Given we use this test in more than one place, can we define a function for it? I see usages on lines 667, 733, 843, and 923 (inverted).

File: linux/ibus-keyman/src/engine.c [hunk 6]
```diff
@@ -678,16 +707,59 @@ process_capslock_action(
...
+    guint state = keyman->commit_item->state;
+    keyman->commit_item++;
+    if (keyman->commit_item > &keyman->commit_queue[MAX_QUEUE_SIZE-1]) {
+      g_error("Overflow of keyman commit_queue!");
+      // TODO: log to Sentry
```
Comment (mcdurdin) [inline linux/ibus-keyman/src/engine.c:739]: Don't forget this!

File: linux/ibus-keyman/src/engine.c [hunk 7]
```diff
@@ -678,16 +707,59 @@ process_capslock_action(
...
+  } else {
+    if (keyman->commit_item->char_buffer != NULL) {
+      ibus_keyman_engine_commit_string(keyman, keyman->commit_item->char_buffer);
+      g_free(keyman->commit_item->char_buffer);
+      keyman->commit_item->char_buffer = NULL;
+    }
+    if (keyman->commit_item->emitting_keystroke) {
+      keyman->commit_item->emitting_keystroke = FALSE;
+      return FALSE;
+    }
```
Comment (mcdurdin) [inline linux/ibus-keyman/src/engine.c:762]: We should document why we are returning `FALSE` here

File: linux/ibus-keyman/src/engine.c [hunk 8]
```diff
@@ -831,12 +915,14 @@ ibus_keyman_engine_process_key_event(
 
   // km_kbp_state_action_items to get action items
   size_t num_action_items;
-  g_free(keyman->char_buffer);
-  keyman->char_buffer                    = NULL;
+  g_free(keyman->commit_item->char_buffer);
+  keyman->commit_item->char_buffer                    = NULL;
```
Comment (mcdurdin) [inline linux/ibus-keyman/src/engine.c:919]:
```suggestion
  keyman->commit_item->char_buffer = NULL;
```

File: linux/ibus-keyman/src/engine.c [hunk 9]
```diff
@@ -831,12 +915,14 @@ ibus_keyman_engine_process_key_event(
...
   const km_kbp_action_item *action_items = km_kbp_state_action_items(keyman->state, &num_action_items);
 
-  if (!process_actions(engine, action_items, num_action_items))
+  if (!process_actions(engine, action_items, num_action_items) &&
+      (!(engine->client_capabilities & IBUS_CAP_PREFILTER) || (engine->client_capabilities & IBUS_CAP_SURROUNDING_TEXT))) {
     return FALSE;
```
Comment (mcdurdin) [inline linux/ibus-keyman/src/engine.c:924]: We should document why we return FALSE only when the !PREFILTER/SURROUNDING_TEXT capability condition is met.

**Review by mcdurdin — CHANGES_REQUESTED** [review]
This all looks good. I have a bunch of minor quality requests.

File: linux/ibus-keyman/src/engine.c (hunk 4 above)
Comment (ermshiperete) [reply linux/ibus-keyman/src/engine.c:713]: done

File: linux/ibus-keyman/src/engine.c (hunk 9 above)
Comment (ermshiperete) [reply linux/ibus-keyman/src/engine.c:951]: done

**Comment by bharanidharanj** [comment]
### GROUP_JAMMY_X11: Ubuntu 22.04 Jammy with Gnome Shell and X11

* **TEST_WRITER_IPA (PASSED):** Tested with the attached PR build (Keyman 16.0.59-alpha) as per the instructions in Jammy_X11 and I was able to see the expected output. 
* **TEST_WRITER_KO (PASSED):** Tested with the attached PR build (Keyman 16.0.59-alpha) as per the instructions and I was able to see the expected output. 
* **TEST_WRITER_HI (PASSED):** Tested with the attached PR build (Keyman 16.0.59-alpha) as per the instructions and I was able to see the expected output. 
* **TEST_WRITER_KM (PASSED):** Tested with the attached PR build (Keyman 16.0.59-alpha) as per the instructions and I was able to see the expected output. 
* **TEST_WRITER_KM_BS (PASSED):** Tested with the attached PR build (Keyman 16.0.59-alpha) as per the instructions and I was able to see the expected output. ie., Pressing the Backspace key would entirely deleted all the characters.

**Comment by bharanidharanj** [comment]
## SUITE_GEDIT: gedit

### GROUP_JAMMY_X11: Ubuntu 22.04 Jammy with Gnome Shell and X11

* **TEST_GEDIT_IPA (PASSED):** Tested with the attached PR build (Keyman 16.0.59-alpha) as per the instructions in Jammy_X11 and I was able to see the expected output.
* **TEST_GEDIT_KO (PASSED):** Tested with the attached PR build (Keyman 16.0.59-alpha) as per the instructions and I was able to see the expected output.
* **TEST_GEDIT_HI (PASSED):** Tested with the attached PR build (Keyman 16.0.59-alpha) as per the instructions and I was able to see the expected output.
* **TEST_GEDIT_KM (PASSED):** Tested with the attached PR build (Keyman 16.0.59-alpha) as per the instructions and I was able to see the expected output.
* **TEST_GEDIT_KM_BS (PASSED):** Tested with the attached PR build (Keyman 16.0.59-alpha) as per the instructions and I was able to see the expected output.

File: linux/ibus-keyman/src/engine.c [hunk 10]
```diff
@@ -758,10 +767,19 @@ process_end_action(IBusKeymanEngine *keyman) {
     }
     if (keyman->commit_item->emitting_keystroke) {
       keyman->commit_item->emitting_keystroke = FALSE;
+      // We have an old ibus version without prefilter support, or a client that does support
+      // surrounding text. In either case we return FALSE because we emitted a keystroke
+      // so that the processing of the event will continue.
```
Comment (mcdurdin) [inline linux/ibus-keyman/src/engine.c:772]: :+1:

File: linux/ibus-keyman/src/engine.c [hunk 11]
```diff
@@ -227,9 +227,22 @@ static gchar *get_current_context_text(km_kbp_context *context)
...
-    IBusKeymanEngine *keyman = (IBusKeymanEngine *) engine;
+  g_assert(engine != NULL);
+  return (engine->client_capabilities & IBUS_CAP_PREFILTER) != 0;
+}
+
+static gboolean
+client_supports_surrounding_text(IBusEngine *engine) {
+  g_assert(engine != NULL);
+  return (engine->client_capabilities & IBUS_CAP_SURROUNDING_TEXT) != 0;
+}
```
Comment (mcdurdin) [inline linux/ibus-keyman/src/engine.c:241]: 😍 I guess we could have done these as macros or inline them but this is nice

File: linux/ibus-keyman/src/engine.c [hunk 12]
```diff
@@ -758,10 +767,19 @@ process_end_action(IBusKeymanEngine *keyman) {
...
+      // We have an old ibus version without prefilter support, or a client that does support
+      // surrounding text. In either case we return FALSE because we emitted a keystroke
+      // so that the processing of the event will continue.
       return FALSE;
     }
   }
 
+  // If we have a new ibus version that supports prefilter and a client that doesn't support
+  // surrounding text (e.g. Chromium) we forwarded the key event with IBUS_PREFILTER_MASK set
+  // and now return TRUE here to stop further processing.
```
Comment (mcdurdin) [inline linux/ibus-keyman/src/engine.c:779]:
```suggestion
  // If we have a new ibus version that supports prefilter and a client that doesn't support
  // surrounding text (e.g. Chromium as of v104) we forwarded the key event with
  // IBUS_PREFILTER_MASK set and now return TRUE here to stop further processing.
```

**Review by mcdurdin — APPROVED** [review]
LVGTM

**Comment by bharanidharanj** [comment]
## SUITE_WRITER: LibreOffice Writer

### GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11

* **TEST_WRITER_IPA (PASSED):** Tested this as per the instructions in LibreOffice Writer 7.3 and it is working as expected. 
* **TEST_WRITER_KO (PASSED):** Tested this as per the instructions in LibreOffice Writer 7.3 and it is working as expected.
* **TEST_WRITER_HI (FAILED):** Tested this as per the instructions in LibreOffice Writer 7.3 and it is showing different output. 
* **TEST_WRITER_KM (PASSED):** Tested this as per the instructions in LibreOffice Writer 7.3 and it is working as expected.
* **TEST_WRITER_KM_BS (PASSED):** Tested this as per the instructions in LibreOffice Writer 7.3 and it is working as expected.

..in LibreOffice 7.3
   



### GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11

* **TEST_GEDIT_IPA (PASSED):** Tested this as per the instructions in LibreOffice Writer 7.3 and it is working as expected.
* **TEST_GEDIT_KO (PASSED):** Tested this as per the instructions in LibreOffice Writer 7.3 and it is working as expected.
* **TEST_GEDIT_HI (PASSED):** Tested this as per the instructions in LibreOffice Writer 7.3 and it is working as expected.
* **TEST_GEDIT_KM (PASSED):** Tested this as per the instructions in LibreOffice Writer 7.3 and it is working as expected.
* **TEST_GEDIT_KM_BS (PASSED):** Tested this as per the instructions in LibreOffice Writer 7.3 and it is working as expected.

..in TextEditor

   

..ibus version

**Comment by bharanidharanj** [comment]
## SUITE_WRITER: LibreOffice Writer

### GROUP_FOCAL: Ubuntu 20.04 Focal with Gnome Shell and X11

* **TEST_WRITER_IPA (PASSED):** Tested this as per the instructions in LibreOffice Writer 6.4.7.2 and it is working as expected.
* **TEST_WRITER_KO (PASSED):** Tested this as per the instructions in LibreOffice Writer 6.4.7.2 and it is working as expected.
* **TEST_WRITER_HI (PASSED):** Tested this as per the instructions in LibreOffice Writer 6.4.7.2 and it is working as expected.
* **TEST_WRITER_KM (PASSED):** Tested this as per the instructions in LibreOffice Writer 6.4.7.2 and it is working as expected.
* **TEST_WRITER_KM_BS (PASSED):** Tested this as per the instructions in LibreOffice Writer 6.4.7.2 and it is working as expected.

..LibreOffice Writer 6.4 
 
  


## SUITE_GEDIT: gedit

### GROUP_FOCAL: Ubuntu 20.04 Focal with Gnome Shell and X11

* **TEST_GEDIT_IPA (PASSED):** Tested this as per the instructions in Text Editor and it is working as expected.
* **TEST_GEDIT_KO (PASSED):** Tested this as per the instructions in Text Editor and it is working as expected.
* **TEST_GEDIT_HI (PASSED):** Tested this as per the instructions in Text Editor and it is working as expected.
* **TEST_GEDIT_KM (PASSED):** Tested this as per the instructions in Text Editor and it is working as expected.
* **TEST_GEDIT_KM_BS (PASSED):** Tested this as per the instructions in Text Editor and it is working as expected.

..in Text Editor

   


..ibus version

**Comment by bharanidharanj** [comment]
## SUITE_WRITER: LibreOffice Writer

### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_WRITER_IPA (PASSED):** Tested this as per the instructions in LibreOffice Writer 7.3.6.2 and it is working as expected.
* **TEST_WRITER_KO (PASSED):** Tested this as per the instructions in LibreOffice Writer 7.3.6.2 and it is working as expected.
* **TEST_WRITER_HI (FAILED):** Tested this as per the instructions in LibreOffice Writer 7.3.6.2 and it is working as expected.
* **TEST_WRITER_KM (PASSED):** Tested this as per the instructions in LibreOffice Writer 7.3.6.2 and it is working as expected.
* **TEST_WRITER_KM_BS (PASSED):** Tested this as per the instructions in LibreOffice Writer 7.3.6.2 and it is working as expected.

..LibreOffice 7.3

   


## SUITE_GEDIT: gedit

### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_GEDIT_IPA (PASSED):** Tested this as per the instructions in Text Editor and it is working as expected.
* **TEST_GEDIT_KO (PASSED):** Tested this as per the instructions in Text Editor and it is working as expected.
* **TEST_GEDIT_HI (FAILED):** Tested this as per the instructions in Text Editor and it is working as expected.
* **TEST_GEDIT_KM (PASSED):** Tested this as per the instructions in Text Editor and it is working as expected.
* **TEST_GEDIT_KM_BS (PASSED):** Tested this as per the instructions in Text Editor and it is working as expected.

..TextEditor

   


..ibus version

**Comment by bharanidharanj** [comment]
## SUITE_FIREFOX: Firefox

### GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11

* **TEST_FIREFOX_IPA (PASSED):** Tested this in the Keyboard Search filed and it is working as expected. 
* **TEST_FIREFOX_KO (PASSED):** Tested this in the Keyboard Search filed and it is working as expected. 
* **TEST_FIREFOX_HI (PASSED):** Tested this in the Keyboard Search filed and it is working as expected. 
* **TEST_FIREFOX_KM (PASSED):** Tested this in the Keyboard Search filed and it is working as expected. 
* **TEST_FIREFOX_KM_BS (PASSED):** Tested this in the Keyboard Search filed and it is working as expected.

**Comment by bharanidharanj** [comment]
## SUITE_TERMINAL: gnome-terminal

### GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11

* **TEST_TERMINAL_IPA (PASSED):** Tested this in terminal window and it showing the correct output. 

* **TEST_TERMINAL_KO (FAILED):** Tested this in terminal window and it showing the wrong output. 



* **TEST_TERMINAL_HI (FAILED):**  Tested this in terminal window and it showing the wrong output. 




* **TEST_TERMINAL_KM (FAILED):** Tested this in terminal window and it showing the wrong output. 




* **TEST_TERMINAL_KM_BS (FAILED):** Tested this in terminal window and I noticed that the entire word is deleted after pressing the Backspace key for the 3 time.

**Comment by ermshiperete** [comment]
@bharanidharanj For the failed TEST_WRITER_HI tests, please change the font to "Siddhanta" and retest.

@keymanapp-test-bot retest SUITE_WRITER GROUP_BIONIC TEST_WRITER_HI GROUP_WASTA TEST_WRITER_HI

The failing test in Chromium on Bionic seems to be a font issue - when I connect to the test server on my Windows machine and test with Chromium and Firefox with both System Keyboard (and selected ITRANS), and the ITRANS web keyboard, with the web keyboard I get the wrong results in both browsers. However, in Firefox when I then switch to the System Keyboard the output suddenly displays correctly.

@keymanapp-test-bot skip SUITE_CHROMIUM GROUP_BIONIC TEST_CHROMIUM_HI

Similarly, in gnome-terminal on Bionic the display is wrong, but Keyman sends the correct output.

@keymanapp-test-bot skip SUITE_TERMINAL GROUP_BIONIC TEST_TERMINAL_KO TEST_TERMINAL_HI TEST_TERMINAL_KM TEST_TERMINAL_KM_BS

Same thing in gedit where the font is wrong (changing to "Siddhanta" font will display things correctly).

@keymanapp-test-bot skip  SUITE_GEDIT GROUP_WASTA TEST_GEDIT_HI

**Comment by ermshiperete** [comment]
@keymanapp-test-bot skip SUITE_CHROMIUM GROUP_BIONIC TEST_CHROMIUM_HI SUITE_TERMINAL GROUP_BIONIC TEST_TERMINAL_KO TEST_TERMINAL_HI TEST_TERMINAL_KM TEST_TERMINAL_KM_BS SUITE_GEDIT GROUP_WASTA TEST_GEDIT_HI

**Comment by mcdurdin** [comment]
@ermshiperete I have updated your test bot skip instructions to match what the bot understands! :grin: Only 'retest' is supported asking the bot directly at present.

**Comment by ermshiperete** [comment]
> @ermshiperete I have updated your test bot skip instructions to match what the bot understands! grin Only 'retest' is supported asking the bot directly at present.

Ahh, right. Forgot about that! Thanks!

**Comment by bharanidharanj** [comment]
## SUITE_WRITER: LibreOffice Writer

### GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11

* **TEST_WRITER_HI (PASSED):** Installed 'Siddhanta' font and now I am able to see the expected output.

**Comment by bharanidharanj** [comment]
## SUITE_WRITER: LibreOffice Writer

### GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11

* **TEST_WRITER_KM (FAILED):** After installing the Siddhanta font the Hindi Vedanta keyboard is working fine. But, I am getting wrong output while using Khmer Angkor Keyboard.

**Comment by bharanidharanj** [comment]
## SUITE_WRITER: LibreOffice Writer

### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_WRITER_HI (PASSED):** After installing Siddhanta font, I am not able reproduce the font issue.

**Comment by bharanidharanj** [comment]
## SUITE_GEDIT: gedit

### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_GEDIT_HI (PASSED):** Edit the font in Preferences / Font & Colors tab in Text Editor and now I am able to see the expected output.

**Comment by bharanidharanj** [comment]
### GROUP_JAMMY_X11: Ubuntu 22.04 Jammy with Gnome Shell and X11

* **TEST_SEARCHBAR_IPA (PASSED):** Tested this in Search bar and it produces the expected output. 
   
   


* **TEST_SEARCHBAR_KO (PASSED):** Tested this in Search bar and it produces the expected output. 
   
   


* **TEST_SEARCHBAR_HI (PASSED):** Tested this in Search bar and it produces the expected output. 

   


* **TEST_SEARCHBAR_KM (PASSED):** Tested this in Search bar and it produces the expected output. 

   


* **TEST_SEARCHBAR_KM_BS (PASSED):** After pressing the backspace key 5 times entire word has been removed from the space bar.

**Comment by bharanidharanj** [comment]
## SUITE_FIREFOX: Firefox

### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_FIREFOX_IPA (PASSED):** Tested IP (SIL) keyboard in Keyboard Search field and it shows the expected output. 

   


* **TEST_FIREFOX_KO (FAILED):** Tested 'Korean KORDA Jamo (SIL)' keyboard and it is showing wrong output. 

   


* **TEST_FIREFOX_HI (FAILED):** Tested 'Vedic Sanskrit Devanagari Phonetic (ITRANS)' keyboard and it is showing wrong output.


   

 
* **TEST_FIREFOX_KM (PASSED):** Tested 'Khmer Angkor' keyboard and it shows the expected output. 

   



* **TEST_FIREFOX_KM_BS (FAILED):** After Pressing Backspace key 5 times, the fonts are not completely removed from the Search filed.

**Comment by bharanidharanj** [comment]
## SUITE_CHROMIUM: Chromium

### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_CHROMIUM_IPA (FAILED):** Tested this as per the instructions and it is showing wrong output.
   


* **TEST_CHROMIUM_KO (FAILED):** Tested this as per the instructions and it is showing wrong output.
   


* **TEST_CHROMIUM_HI (FAILED):** Tested this as per the instructions and it is showing wrong output.

   


* **TEST_CHROMIUM_KM (FAILED):** Tested this as per the instructions and it is showing wrong output.

   


* **TEST_CHROMIUM_KM_BS (FAILED):** Tested this as per the instructions and it is showing wrong output.

**Comment by bharanidharanj** [comment]
## SUITE_TERMINAL: gnome-terminal

### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_TERMINAL_IPA (PASSED):** Tested this as per the instructions and it is showing the wrong output. 
   


* **TEST_TERMINAL_KO (FAILED):** Tested this as per the instructions and it is showing the wrong output.
   

* **TEST_TERMINAL_HI (FAILED):** Tested this as per the instructions and it is showing the wrong output.

   


* **TEST_TERMINAL_KM (FAILED):** Tested this as per the instructions and it is showing the wrong output.

   


* **TEST_TERMINAL_KM_BS (FAILED):** Tested this as per the instructions and it is showing the wrong output.

**Comment by bharanidharanj** [comment]
## SUITE_ANKI: Anki

### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_ANKI_IPA (PASSED):** Tested this in Anki 2.1.54 and it is working as expected. 

   

* **TEST_ANKI_KO (PASSED):** Tested this in Anki 2.1.54 and it is working as expected.

   

* **TEST_ANKI_HI (FAILED):** Tested this in Anki 2.1.54 and it is working as expected.

   

* **TEST_ANKI_KM (PASSED):** Tested this in Anki 2.1.54 and it is working as expected.

   

* **TEST_ANKI_KM_BS (PASSED):** Tested this in Anki 2.1.54 and after pressing Backspace key 5 times the entire word has been removed from the Filter box.

**Comment by bharanidharanj** [comment]
## SUITE_SEARCHBAR: Searchbar in gnome-shell

### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_SEARCHBAR_IPA (FAILED):** Tested this in Wasta gnome-shell Search bar and it showing wrong output. 

   


* **TEST_SEARCHBAR_KO (FAILED):** Tested this in Wasta gnome-shell Search bar and it showing wrong output.

   

* **TEST_SEARCHBAR_HI (FAILED):** Tested this in Wasta gnome-shell Search bar and it showing wrong output.

   


* **TEST_SEARCHBAR_KM (FAILED):** Tested this in Wasta gnome-shell Search bar and it showing wrong output.

   

* **TEST_SEARCHBAR_KM_BS (FAILED):** Tested this in Wasta gnome-shell Search bar and after pressing Backsapce key for 5 times does not remove the letter from the Wasta Search bar.

**Comment by bharanidharanj** [comment]
## SUITE_ANKI: Anki

### GROUP_JAMMY_X11: Ubuntu 22.04 Jammy with Gnome Shell and X11

* **TEST_ANKI_IPA (PASSED):** Tested this in Anki and it is working as expected. 

   

* **TEST_ANKI_KO (PASSED):** Tested this in Anki and it is working as expected.

   

* **TEST_ANKI_HI (PASSED):** Tested this in Anki and it is working as expected.

   

* **TEST_ANKI_KM (PASSED):** Tested this in Anki and it is working as expected.

   

* **TEST_ANKI_KM_BS (PASSED):** Tested this in Anki and pressing Backspace key 5 times remove the entire word from the Filter box.

**Comment by bharanidharanj** [comment]
## SUITE_TERMINAL: gnome-terminal

### GROUP_JAMMY_X11: Ubuntu 22.04 Jammy with Gnome Shell and X11

* **TEST_TERMINAL_IPA (FAILED):** Tested this as per the instructions and it is showing wrong output. 

   

* **TEST_TERMINAL_KO (FAILED):** Tested this as per the instructions and it is showing wrong output.

   


* **TEST_TERMINAL_HI (FAILED):** Tested this as per the instructions and it is showing wrong output.

  


* **TEST_TERMINAL_KM (FAILED):** Tested this as per the instructions and it is showing wrong output.

   


* **TEST_TERMINAL_KM_BS (FAILED):** Tested this as per the instructions and pressing backspace key 5 times does not remove the entire word from the terminal.

**Comment by bharanidharanj** [comment]
## SUITE_CHROMIUM: Chromium

### GROUP_JAMMY_X11: Ubuntu 22.04 Jammy with Gnome Shell and X11

* **TEST_CHROMIUM_IPA (FAILED):** Tested this in Chromium browser and it is showing wrong output. 

   


* **TEST_CHROMIUM_KO (FAILED):** Tested this in Chromium browser and it is showing wrong output.

   


* **TEST_CHROMIUM_HI (FAILED):** Tested this in Chromium browser and it is showing wrong output.

    


* **TEST_CHROMIUM_KM (FAILED):** Tested this in Chromium browser and it is showing wrong output.

   


* **TEST_CHROMIUM_KM_BS (FAILED):** Tested this in Chromium browser and pressing Backspace key 5 times does not remove the word from the Search field.

**Comment by bharanidharanj** [comment]
## SUITE_FIREFOX: Firefox

### GROUP_JAMMY_X11: Ubuntu 22.04 Jammy with Gnome Shell and X11

* **TEST_FIREFOX_IPA (PASSED):** Tested in Keyboard Search field and it is showing the correct output. 

   


* **TEST_FIREFOX_KO (PASSED):** Tested in Keyboard Search field and it is showing the correct output. 

   


* **TEST_FIREFOX_HI (FAILED):** Tested in Keyboard Search field and it is showing wrong output. 

   


* **TEST_FIREFOX_KM (FAILED):** Tested in Keyboard Search field and it is showing wrong output. 

   


* **TEST_FIREFOX_KM_BS (FAILED):** Tested this in Chromium browser and pressing Backspace key 5 times does not remove the word from the Search field.

**Comment by bharanidharanj** [comment]
## SUITE_ANKI: Anki

### GROUP_FOCAL: Ubuntu 20.04 Focal with Gnome Shell and X11

* **TEST_ANKI_IPA (PASSED):** Tested this with Anki 2.1.54 and it is showing the correct output. 
* **TEST_ANKI_KO (PASSED):** Tested this with Anki 2.1.54 and it is showing the correct output.
* **TEST_ANKI_HI (PASSED):** Tested this with Anki 2.1.54 and it is showing the correct output.
* **TEST_ANKI_KM (PASSED):** Tested this with Anki 2.1.54 and it is showing the correct output.
* **TEST_ANKI_KM_BS (PASSED):** Tested this with Anki 2.1.54 and it is showing the correct output.

**Comment by bharanidharanj** [comment]
## SUITE_TERMINAL: gnome-terminal

### GROUP_FOCAL: Ubuntu 20.04 Focal with Gnome Shell and X11

* **TEST_TERMINAL_IPA (PASSED):** Tested this as per the instructions and it is showing the correct output.
* **TEST_TERMINAL_KO (FAILED):** Tested this as per the instructions and it is showing the wrong output.
* **TEST_TERMINAL_HI (FAILED):** Tested this as per the instructions and it is showing the wrong output.
* **TEST_TERMINAL_KM (FAILED):** Tested this as per the instructions and it is showing the wrong output.
* **TEST_TERMINAL_KM_BS (FAILED):** Tested this as per the instructions and it is showing the wrong output.

**Comment by bharanidharanj** [comment]
## SUITE_CHROMIUM: Chromium

### GROUP_FOCAL: Ubuntu 20.04 Focal with Gnome Shell and X11

* **TEST_CHROMIUM_IPA (FAILED):** Tested this as per the instructions and it is showing wrong output. (same like in wasta linux)
* **TEST_CHROMIUM_KO (FAILED):** Tested this as per the instructions and it is showing wrong output.
* **TEST_CHROMIUM_HI (FAILED:** Tested this as per the instructions and it is showing wrong output.
* **TEST_CHROMIUM_KM (FAILED):** Tested this as per the instructions and it is showing wrong output.
* **TEST_CHROMIUM_KM_BS (FAILED):** Tested this as per the instructions and it is showing wrong output.

**Comment by bharanidharanj** [comment]
## SUITE_FIREFOX: Firefox

### GROUP_FOCAL: Ubuntu 20.04 Focal with Gnome Shell and X11

* **TEST_FIREFOX_IPA (PASSED):** Tested IP (SIL) keyboard in Keyboard Search field and it shows the expected output.
   
   


* **TEST_FIREFOX_KO (PASSED):** Tested 'Korean KORDA Jamo (SIL)' keyboard and it is showing the correct output.

   


* **TEST_FIREFOX_HI (FAILED):** Tested 'Vedic Sanskrit Devanagari Phonetic (ITRANS)' keyboard and it is showing wrong output.

   


* **TEST_FIREFOX_KM (FAILED):** Tested 'Khmer Angkor' keyboard and it is showing the wrong output.

   


* **TEST_FIREFOX_KM_BS (FAILED):** After Pressing Backspace key 5 times, the fonts are not completely removed from the Search field.

**Comment by bharanidharanj** [comment]
## SUITE_SEARCHBAR: Searchbar in gnome-shell

### GROUP_FOCAL: Ubuntu 20.04 Focal with Gnome Shell and X11

* **TEST_SEARCHBAR_IPA (FAILED):** Tested this as per the instructions and it is showing wrong output.

   

* **TEST_SEARCHBAR_KO (FAILED):** Tested this as per the instructions and it is showing wrong output.

   

* **TEST_SEARCHBAR_HI (FAILED):** Tested this as per the instructions and it is showing wrong output.

   

* **TEST_SEARCHBAR_KM (FAILED):** Tested this as per the instructions and it is showing wrong output.
   

* **TEST_SEARCHBAR_KM_BS (FAILED):** After Pressing Backspace key 5 times, the fonts are not completely removed from the Search field.

**Comment by bharanidharanj** [comment]
## SUITE_SEARCHBAR: Searchbar in gnome-shell

### GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11

* **TEST_SEARCHBAR_IPA (FAILED):** Tested this as per the instructions and it is showing wrong output.
   
   


* **TEST_SEARCHBAR_KO (FAILED):** Tested this as per the instructions and it is showing wrong output.

   


* **TEST_SEARCHBAR_HI (FAILED):** Tested this as per the instructions and it is showing wrong output.

   


* **TEST_SEARCHBAR_KM (FAILED):** Tested this as per the instructions and it is showing wrong output.

   


* **TEST_SEARCHBAR_KM_BS (FAILED):** fter Pressing Backspace key 5 times, the fonts are not completely removed from the Search field.

**Comment by bharanidharanj** [comment]
## SUITE_ANKI: Anki

### GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11

* **TEST_ANKI_IPA (PASSED):** Tested this in Anki 2.1.49 (as per Eberhard's suggestion) and it is showing the correct output. 

   


* **TEST_ANKI_KO (PASSED):** Tested this as per the instructions and it is working as expected. 

   

* **TEST_ANKI_HI (PASSED):** Tested this as per the instructions and it is working as expected. 

   

* **TEST_ANKI_KM (PASSED):** Tested this as per the instructions and it is working as expected. 
   


* **TEST_ANKI_KM_BS (PASSED):** After pressing the Backspace key 5 times all the characters have been removed from the Filter box.

**Comment by bharanidharanj** [comment]
## SUITE_CHROMIUM: Chromium

### GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11

* **TEST_CHROMIUM_HI (FAILED):** Tested this in Chromium browser in Keyboard Search field and it is showing the wrong output.

**Comment by bharanidharanj** [comment]
## SUITE_TERMINAL: gnome-terminal

### GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11

* **TEST_TERMINAL_IPA (PASSED):** Tested this in terminal window and it showing the correct output. 

   


* **TEST_TERMINAL_KO (FAILED):** Tested this in terminal window and it showing the wrong output. 



* **TEST_TERMINAL_HI (FAILED):**  Tested this in terminal window and it showing the wrong output. 




* **TEST_TERMINAL_KM (FAILED):** Tested this in terminal window and it showing the wrong output. 




* **TEST_TERMINAL_KM_BS (FAILED):** Tested this in terminal window and I noticed that the entire word is deleted after pressing the Backspace key for the 3 time.

**Comment by ermshiperete** [comment]
I can't repro the test failure in Writer on Bionic. @bharanidharanj would you please try again?
As for Chromium on Focal and Wasta, I updated the instructions: you'll have to install Chromium in the same way as on Ubuntu 22.04, sorry, I overlooked that before.

The failing test in Chromium on Bionic seems to be a font issue. Ignoring that test:

SUITE_CHROMIUM
GROUP_BIONIC
TEST_CHROMIUM_HI skipped

Looks like the searchbar in Bionic, Focal, and Wasta doesn't have the fix that is available in Jammy. Ignoring those tests:

SUITE_SEARCHBAR
GROUP_BIONIC
TEST_SEARCHBAR_IPA skipped
TEST_SEARCHBAR_KO skipped
TEST_SEARCHBAR_HI skipped
TEST_SEARCHBAR_KM skipped
TEST_SEARCHBAR_KM_BS skipped

GROUP_FOCAL
TEST_SEARCHBAR_IPA skipped
TEST_SEARCHBAR_KO skipped
TEST_SEARCHBAR_HI skipped
TEST_SEARCHBAR_KM skipped
TEST_SEARCHBAR_KM_BS skipped

GROUP_WASTA
TEST_SEARCHBAR_IPA skipped
TEST_SEARCHBAR_KO skipped
TEST_SEARCHBAR_HI skipped
TEST_SEARCHBAR_KM skipped
TEST_SEARCHBAR_KM_BS skipped

In gnome-terminal on Bionic, Focal and Wasta the display is wrong, but Keyman sends the correct output. Ignoring those tests:

SUITE_TERMINAL
GROUP_BIONIC
TEST_TERMINAL_KO skipped
TEST_TERMINAL_HI skipped
TEST_TERMINAL_KM skipped
TEST_TERMINAL_KM_BS skipped

GROUP_FOCAL
TEST_TERMINAL_KO skipped
TEST_TERMINAL_HI skipped
TEST_TERMINAL_KM skipped
TEST_TERMINAL_KM_BS skipped

GROUP_WASTA
TEST_TERMINAL_KO skipped
TEST_TERMINAL_HI skipped
TEST_TERMINAL_KM skipped
TEST_TERMINAL_KM_BS skipped

@keymanapp-test-bot retest SUITE_WRITER GROUP_BIONIC TEST_WRITER_KM  SUITE_CHROMIUM GROUP_FOCAL TEST_CHROMIUM_IPA TEST_CHROMIUM_KO TEST_CHROMIUM_HI TEST_CHROMIUM_KM TEST_CHROMIUM_KM_BS GROUP_WASTA TEST_CHROMIUM_IPA TEST_CHROMIUM_KO TEST_CHROMIUM_HI TEST_CHROMIUM_KM TEST_CHROMIUM_KM_BS

**Comment by ermshiperete** [comment]
SUITE_CHROMIUM
GROUP_BIONIC
TEST_CHROMIUM_HI skipped

SUITE_SEARCHBAR
GROUP_BIONIC
TEST_SEARCHBAR_IPA skipped
TEST_SEARCHBAR_KO skipped
TEST_SEARCHBAR_HI skipped
TEST_SEARCHBAR_KM skipped
TEST_SEARCHBAR_KM_BS skipped

GROUP_FOCAL
TEST_SEARCHBAR_IPA skipped
TEST_SEARCHBAR_KO skipped
TEST_SEARCHBAR_HI skipped
TEST_SEARCHBAR_KM skipped
TEST_SEARCHBAR_KM_BS skipped

GROUP_WASTA
TEST_SEARCHBAR_IPA skipped
TEST_SEARCHBAR_KO skipped
TEST_SEARCHBAR_HI skipped
TEST_SEARCHBAR_KM skipped
TEST_SEARCHBAR_KM_BS skipped

SUITE_TERMINAL
GROUP_BIONIC
TEST_TERMINAL_KO skipped
TEST_TERMINAL_HI skipped
TEST_TERMINAL_KM skipped
TEST_TERMINAL_KM_BS skipped

GROUP_FOCAL
TEST_TERMINAL_KO skipped
TEST_TERMINAL_HI skipped
TEST_TERMINAL_KM skipped
TEST_TERMINAL_KM_BS skipped

GROUP_WASTA
TEST_TERMINAL_KO skipped
TEST_TERMINAL_HI skipped
TEST_TERMINAL_KM skipped
TEST_TERMINAL_KM_BS skipped

**Comment by bharanidharanj** [comment]
## SUITE_CHROMIUM: Chromium

### GROUP_FOCAL: Ubuntu 20.04 Focal with Gnome Shell and X11

* **TEST_CHROMIUM_IPA (PASSED):** Retested this as per Eberhard's instructions (ie., following the steps as it mentioned in the Ubuntu 22.04 Jammy Linux)and it showing the correct output. 

   


* **TEST_CHROMIUM_KO (FAILED):** Retested this as per the instructions and the second letter shows wrong (?) output.

   


* **TEST_CHROMIUM_HI (FAILED):** Retested this as per the instructions and it is showing the wrong output. 

   


* **TEST_CHROMIUM_KM (PASSED):** Retested this as per the instructions and it is showing the correct output. 

   


* **TEST_CHROMIUM_KM_BS (PASSED):** Retested this as per the instructions and  after pressing the Backspace key 5 times all the characters have been removed.

**Comment by bharanidharanj** [comment]
## SUITE_CHROMIUM: Chromium

### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_CHROMIUM_IPA (FAILED):** Retested this as per the instructions and it is showing the wrong output. 

   


* **TEST_CHROMIUM_KO (FAILED):** Retested this as per the instructions and it is showing the wrong output. 

   


* **TEST_CHROMIUM_HI (FAILED):** Retested this as per the instructions and it is showing the wrong output. 

   


* **TEST_CHROMIUM_KM (FAILED):** Retested this as per the instructions and it is showing the wrong output. 

    


* **TEST_CHROMIUM_KM_BS (FAILED):** Retested this as per the instructions and it is showing the wrong output.

**Comment by bharanidharanj** [comment]
## SUITE_CHROMIUM: Chromium

### GROUP_JAMMY_X11: Ubuntu 22.04 Jammy with Gnome Shell and X11

* **TEST_CHROMIUM_IPA (FAILED):** Retested this as per the instructions and it is showing the wrong output.

    


* **TEST_CHROMIUM_KO (FAILED):** Retested this as per the instructions and it is showing the wrong output.

    

* **TEST_CHROMIUM_HI (FAILED):** Retested this as per the instructions and it is showing the wrong output.

   


* **TEST_CHROMIUM_KM (FAILED):** Retested this as per the instructions and it is showing the wrong output.

   

* **TEST_CHROMIUM_KM_BS (FAILED):** Retested this as per the instructions and it is showing the wrong output.

**Comment by bharanidharanj** [comment]
## SUITE_WRITER: LibreOffice Writer

### GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11

* **TEST_WRITER_KM (FAILED):** Retested this in updated LibreOffice 7.4 in Bionic 18.04 Linux OS and still I am able to reproduce it.

**Comment by ermshiperete** [comment]
@bharanidharanj Would you please retest in Firefox with ibus version *sil2.1* and the Keyman packages from this PR? Thanks!

@keymanapp-test-bot retest SUITE_FIREFOX

**Comment by bharanidharanj** [comment]
> @bharanidharanj Would you please retest in Firefox with ibus version *sil2.1* (running `sudo apt update && sudo apt upgrade` should update to that version) and the Keyman packages from this PR? Thanks!
> 
> @keymanapp-test-bot retest SUITE_FIREFOX GROUP_FOCAL TEST_FIREFOX_IPA TEST_FIREFOX_KO TEST_FIREFOX_HI TEST_FIREFOX_KM TEST_FIREFOX_KM_BS GROUP_JAMMY_X11 TEST_FIREFOX_IPA TEST_FIREFOX_KO TEST_FIREFOX_HI TEST_FIREFOX_KM TEST_FIREFOX_KM_BS GROUP_WASTA TEST_FIREFOX_IPA TEST_FIREFOX_KO TEST_FIREFOX_HI TEST_FIREFOX_KM TEST_FIREFOX_KM_BS

@ermshiperete Sure. I will do it. Thanks.

**Comment by bharanidharanj** [comment]
## SUITE_FIREFOX: Firefox

### GROUP_FOCAL: Ubuntu 20.04 Focal with Gnome Shell and X11

* **TEST_FIREFOX_IPA (PASSED):** Retested this as per eberhard's new instructions and here is my observations. Tested IP (SIL) keyboard in Keyboard Search field and it shows the expected output.

   


* **TEST_FIREFOX_KO (PASSED):** Tested 'Korean KORDA Jamo (SIL)' keyboard and it is showing the correct output.

   



* **TEST_FIREFOX_HI (PASSED):** Tested 'Vedic Sanskrit Devanagari Phonetic (ITRANS)' keyboard and it is showing the correct output. 


   



* **TEST_FIREFOX_KM (PASSED):** Tested 'Khmer Angkor' keyboard and it is showing the correct output.

   


* **TEST_FIREFOX_KM_BS (PASSED):** After Pressing Backspace key 5 times, the entire word is deleted.

**Comment by ermshiperete** [comment]
Looks like the failing test in Bionic is caused by a wrong font. @bharanidharanj After typing `x` make sure that _Khmer Mondulkiri_ font is shown; otherwise select the text, set _Khmer Mondulkiri_ font and then continue typing. That way I got things to work.

@keymanapp-test-bot retest SUITE_WRITER GROUP_BIONIC TEST_WRITER_KM

**Comment by ermshiperete** [comment]
@keymanapp-test-bot retest SUITE_WRITER GROUP_BIONIC TEST_WRITER_KM

**Comment by ermshiperete** [comment]
Looks like the failing test in Chromium in Bionic is also caused by Chromium choosing the wrong font. @bharanidharanj Please copy the text displayed in Chromium and paste it into gedit and verify it there.

@keymanapp-test-bot retest SUITE_CHROMIUM GROUP_BIONIC TEST_CHROMIUM_HI

**Comment by bharanidharanj** [comment]
## SUITE_CHROMIUM: Chromium

### GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11

* **TEST_CHROMIUM_HI (PASSED):** Retested this as per Eberhard's suggestion and here is my observation. After pasting the Hindi font into gedit, the font changes and showing the correct output.

**Comment by bharanidharanj** [comment]
## SUITE_WRITER: LibreOffice Writer

### GROUP_BIONIC: Ubuntu 18.04 Bionic with Gnome Shell and X11

* **TEST_WRITER_KM (PASSED):** Retested this as per Eberhard's instructions and after changing the font, I was able to see the expected output.

**Comment by bharanidharanj** [comment]
### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_FIREFOX_IPA (PASSED):** Retested this with Keyman 16.0.74-alpha build as per Ebherhard's suggestion and it is working as expected. 


    


* **TEST_FIREFOX_KO (PASSED):** Retested this and I noticed that after pasting it on the gedit, it is showing the correct output. 


   


* **TEST_FIREFOX_HI (PASSED):** Retested this and I noticed that after pasting it on the gedit, it is showing the correct output. 

   


* **TEST_FIREFOX_KM (PASSED):** Retested this in the Keyman Search bar and it is working as expected. 

   


* **TEST_FIREFOX_KM_BS (PASSED):** After Pressing Backspace key 5 times, the entire word is deleted.

**Comment by ermshiperete** [comment]
@keymanapp-test-bot retest SUITE_CHROMIUM GROUP_FOCAL TEST_CHROMIUM_KO TEST_CHROMIUM_HI

**Comment by ermshiperete** [comment]
The following failing tests in Jammy are caused by gnome-terminal not supporting surrounding text and deleting clusters instead of single code points (see #7130), so we skip these tests.

SUITE_TERMINAL
GROUP_JAMMY_X11 
- TEST_TERMINAL_KO(skipped)
- TEST_TERMINAL_HI(skipped)
- TEST_TERMINAL_KM(skipped)
- TEST_TERMINAL_KM_BS (skipped)

@bharanidharanj Please retest TEST_TERMINAL_IPA with a slight variation: after you opened gnome-terminal, press the Enter key first, then start with the test.

@keymanapp-test-bot retest SUITE_TERMINAL GROUP_JAMMY_X11 TEST_TERMINAL_IPA

**Comment by ermshiperete** [comment]
The following failing tests in Jammy are caused by gnome-terminal not supporting surrounding text and deleting clusters instead of single code points (see #7130), so we skip these tests.

SUITE_TERMINAL
GROUP_JAMMY_X11 
- TEST_TERMINAL_KO skipped
- TEST_TERMINAL_HI skipped
- TEST_TERMINAL_KM skipped
- TEST_TERMINAL_KM_BS skipped

**Comment by bharanidharanj** [comment]
## SUITE_TERMINAL: gnome-terminal

### GROUP_JAMMY_X11: Ubuntu 22.04 Jammy with Gnome Shell and X11

* **TEST_TERMINAL_IPA (PASSED):** Tested this as per Eberhard's instructions in Jammy (X11) Linux and it is showing the correct output.

**Comment by bharanidharanj** [comment]
## SUITE_FIREFOX: Firefox

### GROUP_JAMMY_X11: Ubuntu 22.04 Jammy with Gnome Shell and X11

* **TEST_FIREFOX_IPA (PASSED):** Retested this as per the instructions in Ubuntu 22.04 Jammy X11 and it is showing the correct output. 
   


* **TEST_FIREFOX_KO (PASSED):**Retested this as per the instructions in Ubuntu 22.04 Jammy X11 and it is showing the correct output. 

   

* **TEST_FIREFOX_HI (PASSED):** Retested this as per the instructions in Ubuntu 22.04 Jammy X11 and it is showing the correct output. 

   



* **TEST_FIREFOX_KM (PASSED):** Retested this as per the instructions in Ubuntu 22.04 Jammy X11 and it is showing the correct output. 

    


* **TEST_FIREFOX_KM_BS (PASSED):** Retested this as per the instructions in Ubuntu 22.04 Jammy X11,  after Pressing Backspace key 5 times, the entire word is deleted.

**Comment by bharanidharanj** [comment]
## SUITE_CHROMIUM: Chromium

### GROUP_JAMMY_X11: Ubuntu 22.04 Jammy with Gnome Shell and X11

* **TEST_CHROMIUM_IPA (PASSED):** Retested this as per the instructions in (Keyman 16.0.76-alpha) Ubuntu 22.04 Jammy X11 and it is showing the correct output.

    


* **TEST_CHROMIUM_KO (PASSED):** Retested this as per the instructions in Ubuntu 22.04 Jammy X11 and it is showing the correct output.

   


* **TEST_CHROMIUM_HI (PASSED):** Retested this as per the instructions in Ubuntu 22.04 Jammy X11 and it is showing the correct output.

   


* **TEST_CHROMIUM_KM (PASSED):** Retested this as per the instructions in Ubuntu 22.04 Jammy X11 and it is showing the correct output.


   


* **TEST_CHROMIUM_KM_BS (PASSED):** Retested this as per the instructions in Ubuntu 22.04 Jammy X11, after Pressing Backspace key 5 times, the entire word is deleted.

**Comment by bharanidharanj** [comment]
## SUITE_CHROMIUM: Chromium

### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_CHROMIUM_IPA (PASSED):**  Retested this as per the instructions in (Keyman 16.0.76-alpha) Wasta 20.04 Linux and it is showing the correct output.

   


* **TEST_CHROMIUM_KO (PASSED):** Retested this in Wasta Linux and it seems that after pasting the fonts in the text editor it shows the correct the output. 

   


* **TEST_CHROMIUM_HI (PASSED):** Retested this in Wasta Linux and it seems that after pasting the fonts in the text editor it shows the correct the output. 

   


* **TEST_CHROMIUM_KM (PASSED):** Retested this in Wasta Linux and it is showing the correct output.

   


* **TEST_CHROMIUM_KM_BS (PASSED):** After Pressing Backspace key 5 times, the entire word is deleted.

**Comment by bharanidharanj** [comment]
## SUITE_ANKI: Anki

### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_ANKI_HI (PASSED):** Retested this with Keyman 16.0.76-alpha build in Anki application and after pasting the fonts into the text edit, it shows the correct output.

**Comment by bharanidharanj** [comment]
## SUITE_CHROMIUM: Chromium

### GROUP_FOCAL: Ubuntu 20.04 Focal with Gnome Shell and X11

* **TEST_CHROMIUM_KO (PASSED):** Retested this with Keyman 16.0.76-alpha in Ubuntu Focal Linux and it is showing the correct output. 

   

* **TEST_CHROMIUM_HI (PASSED):** Retested this with Keyman 16.0.76-alpha in Ubuntu Focal Linux and it is showing the correct output.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 16.0.78-alpha](https://keyman.com/downloads/releases/alpha/16.0.78)
