### PR TITLE
fix(windows): remove Show Keyboard Usage hotkey

### LINKED ISSUE #4336: bug(windows): Hotkey for "Show Keyboard Usage Pane" Does Nothing
**Describe the bug**

The hotkey set for "Show Keyboard Usage Pane" does nothing.

**To Reproduce**

1. Go to 'Configuration'
2. Click on 'Hotkeys' tab
3. Set a hotkey combo for "Show Keyboard Usage Page" -- say "Ctrl+Shift+K"
4. Close the Configuration and then try the hotkey
5. See error

**Expected behavior**

If "Show Keyboard Usage Pane" is no longer a thing, it should be removed from the list on the Hotkeys tab. Otherwise, the appropriate Keyboard Usage should be redirected to. 

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.229-beta
 - Target Application: self

---

**Additional context**

https://github.com/keymanapp/keyman/pull/4164

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4336.

Removes the "Show Keyboard Usage Page" hotkey entry as it has no effect, and cleans up Keyboard Usage and OSK Hint strings from all the current locales.

### CODE REVIEW

File: windows/src/engine/keyman/viskbd/UfrmVisualKeyboard.pas [hunk 1]
```diff
@@ -661,6 +661,7 @@ function TfrmVisualKeyboard.FormHelp(Command: Word; Data: NativeInt; var CallHel
     case ActivePage of
       apKeyboard: TKeymanDesktopShell.OpenHelp('context_onscreenkeyboard');
       apCharacterMap: TKeymanDesktopShell.OpenHelp('context_charactermap');
+      apFontHelper: TKeymanDesktopShell.OpenHelp('context_fonthelper');
```
Comment (mcdurdin) [inline windows/src/engine/keyman/viskbd/UfrmVisualKeyboard.pas:664]: This context help entry was missing. A bonus fix.

File: windows/src/desktop/kmshell/xml/keyman_hotkeys.xsl [hunk 2]
```diff
@@ -105,7 +105,7 @@
           <xsl:when test="Target='1'"><xsl:value-of select="$locale/string[@name='S_Hotkey_OpenKeyboardMenu']"/></xsl:when>
           <xsl:when test="Target='2'"><xsl:value-of select="$locale/string[@name='S_Hotkey_ShowOnScreenKeyboard']"/></xsl:when>
           <xsl:when test="Target='3'"><xsl:value-of select="$locale/string[@name='S_Hotkey_OpenConfiguration']"/></xsl:when>
-          <xsl:when test="Target='4'"><xsl:value-of select="$locale/string[@name='S_Hotkey_ShowKeyboardUsage']"/></xsl:when>
+
```
Comment (darcywong00) [inline windows/src/desktop/kmshell/xml/keyman_hotkeys.xsl:108]: So the Targets 5-7 don't need to re-index?

Comment (mcdurdin) [reply windows/src/desktop/kmshell/xml/keyman_hotkeys.xsl:108]: No, because those Target identifiers are published in the Keyman COM API, so they can't change.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.234-beta](https://keyman.com/downloads/releases/beta/14.0.234)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)
