### PR TITLE
fix(android): key tip sticky with multitap

### LINKED ISSUE #6489: bug(web,android): holding backspace then pressing another key will leave the key preview visible for the second key
**Describe the bug**

If you hold down backspace on the touch keyboard, then press another key on the keyboard, the key preview for that second key will be left visible when you release.

Noted from https://community.software.sil.org/t/keyman-15-beta-feedback/5755/29

**To Reproduce**

1. Hold backspace on the touch keyboard
2. Press any other letter
3. Release both keys -- the longpress popup will be left visible

In testing, this only happens in Keyman for Android and not for KeymanWeb itself.

**Screenshots**

image

---

**Keyman for iPhone/iPad/Android:**
 - Device: Samsung A90 
 - OS: Android 
 - Keyman version: 15.0.228-beta 
 - Target application: any (in app or system)

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #6489.

The issue arose in multitap scenarios, where the tip display state became desynchronised with the actual display state as maintained in the Android code.

The fix I applied was to reduce some of the state checks into the js wrapper android-host.js. This is not ideal. The state machine for key tip display is scattered across four functions in three files:

* visualKeyboard.ts: VisualKeyboard.highlightKey
* visualKeyboard.ts: VisualKeyboard.showKeyTip
* embedded/keytip.ts: KeyTip.show
* android-host.js: oskShowKeyPreview / oskClearKeyPreview

I have moved the actual re-creation check for the tip to the lowest level functions -- those in android-host.js. But a more detailed look at the state machine and a refactoring would certainly be worthwhile.

# User Testing

**GROUP_ANDROID:** Test on the in-app keyboard on an Android phone device. Multi-tap is not straightforward in the emulator, so please test on a physical device.
**GROUP_IOS:** Test on the in-app keyboard on an iPhone device. Multi-tap is not straightforward in the simulator, so please test on a physical device.

* **TEST_BASIC_KEY_PREVIEW:** Test that the key preview appears and disappears appropriately on keys that have long-press and keys that do not have longpress.

* **TEST_BKSP_KEY_PREVIEW:** Test that in a multi-tap scenario involving backspace, that the key preview is gone after all keys are released.

  This tests the first reported issue in #6489.

  1. Hold backspace on the touch keyboard
  2. Press any other letter
  3. Release both keys -- the longpress popup should no longer be left visible

* **TEST_MULTI_KEY_PREVIEW:** Test that in a multi-tap scenario involving two non-longpress keys, that the key preview is gone after all keys are released.

  This tests the second reported issue in #6489.

  On the numeric/symbol layer on sil_euro_latin:

  1. Hold <kbd>@</kbd>
  2. Press and release <kbd>=</kbd>
  3. Press and hold <kbd>=</kbd>
  4. Release <kbd>@</kbd>
  5. Release <kbd>=</kbd>

  After step 5, no key preview should be visible.

### CODE REVIEW

File: web/source/osk/visualKeyboard.ts [hunk 1]
```diff
@@ -1660,8 +1660,10 @@ namespace com.keyman.osk {
     showKeyTip(key: KeyElement, on: boolean) {
       var tip = this.keytip;
 
+      //console.log('VisualKeyboard.showKeyTip', key ? key.id : 'null', on);
+
       // Do not change the key preview unless key or state has changed
```
Comment (darcywong00) [inline web/source/osk/visualKeyboard.ts:1665]: The comment can be updated

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID: Test on the in-app keyboard on an Android phone device. Multi-tap is not straightforward in the emulator, so please test on a physical device.

* **TEST_BASIC_KEY_PREVIEW (PASSED):** Tested this in my Android Mobile device (Version 11.0) with the attached PR build (Keyman 15.0.229-beta) and it is working as expected. 
* **TEST_BKSP_KEY_PREVIEW (PASSED):** Tested this in my Android Mobile device (Version 11.0)  and it is working as expected. 
* **TEST_MULTI_KEY_PREVIEW (PASSED):** Tested this in my Android Mobile device (Version 11.0)  and it is working as expected.

**Comment by MakaraSok** [comment]
> **GROUP_IOS:** Test on the in-app keyboard on an iPhone device. Multi-tap is not straightforward in the simulator, so please test on a physical device.

For the time being the .ipa file is not installable on physical devices. Should I wait for this to be merged and test on TestFlight? or @sgschantz can help with this test before merging. What do you think, @mcdurdin?

**Comment by mcdurdin** [comment]
it should be available on testflight already as an internal build with this PR number in the version number.

**Comment by MakaraSok** [comment]
# Test Results

### GROUP_IOS: Test on the in-app keyboard on an iPhone device. Multi-tap is not straightforward in the simulator, so please test on a physical device.

* **TEST_BASIC_KEY_PREVIEW (BLOCKED):** the build got installed on iPod touch 7th gen running iOS 15.3.1, but it crashes when open.
* **TEST_BKSP_KEY_PREVIEW (BLOCKED):** the build got installed on iPod touch 7th gen running iOS 15.3.1, but it crashes when open.
* **TEST_MULTI_KEY_PREVIEW (BLOCKED):** the build got installed on iPod touch 7th gen running iOS 15.3.1, but it crashes when open.

Here is the screenshot of the crash:
image

Here is the installed build: 
image

**Comment by mcdurdin** [comment]
Okay, I've fixed the iOS TestFlight build, so you should be able to re-test.

@keymanapp-test-bot retest GROUP_IOS all

**Comment by MakaraSok** [comment]
# Test Results

### GROUP_IOS: Test on the in-app keyboard on an iPhone device. Multi-tap is not straightforward in the simulator, so please test on a physical device.

_All tests were done in-app using `15.0.235-beta-test-6535`build via TestFlight (`15.0.235 (0.6535.6145)`) on iPod touch 7th gen running `iOS 15.3.1`._

* **TEST_BASIC_KEY_PREVIEW (PASSED):** No issue found while assessing the key preview on keys with subkeys.
* **TEST_BKSP_KEY_PREVIEW (PASSED):** The subkeys disappear after releasing both keys, as expected.

There is a catch though if the backspace is pressed for a while to clear the text (including white spaces), the subkeys are no longer available (nothing shown on the keys with subkeys) and the preview key stay longer than usual or won't even disappear at times.

https://user-images.githubusercontent.com/28331388/163746256-d8bb913e-0d71-4247-805a-bc3fc40d5aa8.mov


* **TEST_MULTI_KEY_PREVIEW (PASSED):** No preview key is left after releasing the second key.

File: web/source/osk/embedded/keytip.ts [hunk 2]
```diff
@@ -20,6 +20,8 @@ namespace com.keyman.osk.embedded {
     show(key: KeyElement, on: boolean, vkbd: VisualKeyboard) {
       let util = com.keyman.singleton.util;
 
+      //console.log('KeyTip.show', key ? key.id : null, on);
```
Comment (jahorton) [inline web/source/osk/embedded/keytip.ts:23]: Is it your intent to insert this comment here?

File: web/source/osk/visualKeyboard.ts [hunk 3]
```diff
@@ -1134,6 +1134,7 @@ namespace com.keyman.osk {
      *  @param    {boolean}   on    add or remove highlighting
      **/
     highlightKey(key: KeyElement, on: boolean) {
+      //console.log('VisualKeyboard.highlightKey', key ? key.id : 'null', on);
```
Comment (jahorton) [inline web/source/osk/visualKeyboard.ts:1137]: Same question as before re: comment insertion.

File: web/source/osk/visualKeyboard.ts [hunk 4]
```diff
@@ -1660,8 +1660,7 @@ namespace com.keyman.osk {
     showKeyTip(key: KeyElement, on: boolean) {
       var tip = this.keytip;
 
-      // Do not change the key preview unless key or state has changed
-      if (tip == null || (key == tip.key && on == tip.state)) {
+      if (tip == null) {
```
Comment (jahorton) [inline web/source/osk/visualKeyboard.ts:1663]: Was this change still needed after the change earlier in this file?  I find that interesting if so.

**Review by jahorton — APPROVED** [review]
I'm pretty sure the underlying cause is due to difficulties with Web's handling of tracking multi-touch input; by and large, the original code was clearly written from a single-touch paradigm.  We've got _some_ logic in place to smooth multi-touch scenarios, but some rough edges (like this) still remain.

File: web/source/osk/embedded/keytip.ts (hunk 2 above)
Comment (mcdurdin) [reply web/source/osk/embedded/keytip.ts:23]: Yeah, will remove the logging comments before merge.

File: web/source/osk/visualKeyboard.ts (hunk 4 above)
Comment (mcdurdin) [reply web/source/osk/visualKeyboard.ts:1663]: From what I can recall, this was necessary because `showKeyTip` is called from a few places, and this was just removing the state check from an intermediate part of the state machine which was part of the desync issue. See my initial comment:

> But a more detailed look at the state machine and a refactoring would certainly be worthwhile.

😆

File: web/source/osk/embedded/keytip.ts [hunk 5]
```diff
@@ -20,6 +20,8 @@ namespace com.keyman.osk.embedded {
...
+
```
Comment (mcdurdin) [inline web/source/osk/embedded/keytip.ts:24]:
```suggestion
```

File: web/source/osk/visualKeyboard.ts (hunk 3 above)
Comment (mcdurdin) [reply web/source/osk/visualKeyboard.ts:1137]:
```suggestion
```

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.236-beta](https://keyman.com/downloads/releases/beta/15.0.236)
