### PR TITLE
fix(android): Reorder display language list

### LINKED ISSUE #15849: bug(android): "German" should be "Deutsch" and not in alphabetical order anyway in Display Language menu
"German" should be "Deutsch (German)" or "Deutsch", and should be in (English-like) alphabetical order (i.e. under D, not between I and K -- how on earth is that even happening??).
Similar happens with "(Simplified Chinese)" which currently is listed as the last item and which should be sorted under C (for Chinese)

Image

version: 19.0.222-alpha

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #15849

This updates the Keyman for Android "Display Language" list accordingly:
> * German" should be "Deutsch (German)" or "Deutsch", and should be in (English-like) alphabetical order (i.e. under D, not between I and K -- how on earth is that even happening??).
> * Similar happens with "(Simplified Chinese)" which currently is listed as the last item and which should be sorted under C (for Chinese)

## Screenshots of the updates Display Language list

(updated after review comments)
part 1
display 1

part 2
display 2

part 3
display 3

Test-bot: skip

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/keyman/engine/DisplayLanguages.java [hunk 1]
```diff
@@ -68,11 +67,12 @@ public static final DisplayLanguageType[] getDisplayLanguages(Context context) {
       new DisplayLanguageType("ff-ZA", "Pulaar-Fulfulde"), // or Fulah
       new DisplayLanguageType("ru-RU", "Русский (Russian)"),
       new DisplayLanguageType("shu-latn", "Shuwa (Latin)"),
+      new DisplayLanguageType("es-ES", "Español (Spanish)"),
+      new DisplayLanguageType("es-419", "Español (Spanish - Latin America)"),
       new DisplayLanguageType("sv-SE", "svenska (Swedish)"),
```
Comment (SabineSIL) [inline android/KMEA/app/src/main/java/com/keyman/engine/DisplayLanguages.java]:
```suggestion
      new DisplayLanguageType("sv-SE", "Svenska (Swedish)"),
```

**Review by SabineSIL — APPROVED** [review]
Do we want to write 'Svenska' in Capital letters? 
Other than that LGTM

File: android/KMEA/app/src/main/java/com/keyman/engine/DisplayLanguages.java [hunk 2]
```diff
@@ -68,11 +67,12 @@ public static final DisplayLanguageType[] getDisplayLanguages(Context context) {
       new DisplayLanguageType("ff-ZA", "Pulaar-Fulfulde"), // or Fulah
       new DisplayLanguageType("ru-RU", "Русский (Russian)"),
       new DisplayLanguageType("shu-latn", "Shuwa (Latin)"),
+      new DisplayLanguageType("es-ES", "Español (Spanish)"),
+      new DisplayLanguageType("es-419", "Español (Spanish - Latin America)"),
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/keyman/engine/DisplayLanguages.java]: These should be sorted under `e` for `Español` - because they are in Latin script. Just like `Deutsch` is under `d`.

File: android/KMEA/app/src/main/java/com/keyman/engine/DisplayLanguages.java (hunk 1 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/keyman/engine/DisplayLanguages.java]: Sure - capitalized.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 19.0.223-alpha](https://keyman.com/downloads/releases/alpha/19.0.223)
