### PR TITLE
fix(windows): Fix multiple issues with UI locales

### LINKED ISSUE #3750: bug(windows): The display language list has incorrect labels and doesn't work
**Describe the bug**
No other languages are shown in the Display language list.

image

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'English' next to the globe icon `Display in:`.
3. See error

**Expected behavior**
The list should not show "Englishes". Various languages should be there to choose from instead.

---
**Keyman Desktop:**
 - OS: Windows 10 Pro 2004
 - Keyman version: 14.0.168-alpha
 - Target Application: [self]

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #3750.

You may wish to review this commit-by-commit. The changes are related but scattered among multiple components. See commit messages for details on changes.

### CODE REVIEW

File: windows/src/global/delphi/cust/CustomisationMessages.pas [hunk 1]
```diff
@@ -107,61 +107,6 @@ function TCustomisationMessageManager.GetAvailableLanguages: string;
     end;
   end;
 
-  procedure ReadPackageLanguages(IsLM: Boolean);
```
Comment (jahorton) [inline windows/src/global/delphi/cust/CustomisationMessages.pas:110]: Noting the message from this commit:

> Locales will be distributed as part of the app, for now. We may re-introduce package-based locales in the future, across all platforms.

Would this affect users in any noticeable way or cause possible loss of functionality for people?

Comment (mcdurdin) [reply windows/src/global/delphi/cust/CustomisationMessages.pas:110]: There may be some very old packages that include locale.xml files, but it's never been very well supported and I have never seen any in the wild. As it stands, they won't work anyway since we went from locale.xml format to strings.xml format for 14.0...

**Review by jahorton — APPROVED** [review]
