### PR TITLE
[Web] Fix for subkey '(layer-default)' behavior.

### LINKED ISSUE #161: Longpress menus are assigned the wrong layer when no layer is specified for a subkey
A longpress menu on a non-default layer is assigned the wrong layer in the id for each key, if that key has no layer override set. For example, instead of having `'popup-shift-T_blah'` as the id for the key, it is given instead `'popup-default-T_blah'`.

This issue is in kmwosk.js, `showSubKeys()`:

````
if(typeof(sk['layer']) == 'string' && sk['layer'] != '')
  btn.id='popup-'+sk['layer']+'-'+sk['id'];
else
  btn.id='popup-default-'+sk['id'];
````

Instead of `default`, we should be injecting the currently selected layer, which we can find in `osk.layerId`. It should not be taken from the parent key's id, because that may be an override.

### PR DESCRIPTION
**Pull request by jahorton**
Reformats `osk.showSubKeys` and fixes #161.

----

A couple of notes:  this might should have some Developer-based work as well, given this default-generated layout within KM Developer:

image

Note that on the `shift` layer for the 'Latin' touch-optimized OSK, the '.' subkeys are given the `(layer-default)` shifting property instead of `default` shifting; the submenus on the `default` and `shift` layers are identical, so their prescribed Shift property should probably also be *functionally* identical - operating as if on the `default` layer.

### CODE REVIEW

File: web/source/kmwosk.js [hunk 1]
```diff
@@ -534,37 +543,45 @@ if(!window['keyman']['initialized']) {
...
         osk.setButtonClass(sk,btn);
 
         // Create (temporarily) unique ID by prefixing 'popup-' to actual key ID
-        if(typeof(sk['layer']) == 'string' && sk['layer'] != '')
+        if(typeof(sk['layer']) == 'string' && sk['layer'] != '') {
           btn.id='popup-'+sk['layer']+'-'+sk['id'];
-        else
-          btn.id='popup-default-'+sk['id'];
+        } else {
+          btn.id='popup-' + osk.layerId + '-'+sk['id'];
```
Comment (jahorton) [inline web/source/kmwosk.js]: The key line of the change, as originally prescribed on #161.

**Comment by darcywong00** [comment]
Some good keyboards to use for testing longpress:
> Kayan, Hanga, Amharic

**Comment by darcywong00** [comment]
oops, is it too late to ask for an update on history.md?
