### PR TITLE
fix(core): surrogate handling, markers in app context, and memory leak

### LINKED ISSUE #10615: bug(core): `is_context_unchanged` does not handle surrogate pairs
The context string comparison in `is_context_unchanged` compares `km_core_context_item[]` (UTF-32) with `km_core_cp*` (UTF-16), which means that surrogate pairs are not correctly handled.

Relates to #10605.

### LINKED ISSUE #10616: bug(core): some tests (esp. for `km_core_state_context_set_if_needed()`) make invalid assumptions about app context
Two things happening here:

* Setting app_context with markers (debug_api.cpp, state_context_api.cpp), e.g.:
https://github.com/keymanapp/keyman/blob/83f80c061a5e71909ccf4c78cec45747a9738b2c/core/tests/unit/kmnkbd/debug_api.cpp#L429
https://github.com/keymanapp/keyman/blob/2ebca107e00408b47e80212cd86076be882d9f91/core/tests/unit/kmnkbd/state_context_api.cpp#L184

* Comparing app_context to a context with markers (state_context_api.cpp), e.g.:
https://github.com/keymanapp/keyman/blob/2ebca107e00408b47e80212cd86076be882d9f91/core/tests/unit/kmnkbd/state_context_api.cpp#L189

Proposed mitigations:
1. Fix the tests
2. Add debug assertions for app_context to ensure it never gets polluted with markers

### LINKED ISSUE #10617: bug(core): `replace_context()` leaks `new_context_items`
The success path in the following snippet does not free `new_context_items`:

https://github.com/keymanapp/keyman/blob/2ebca107e00408b47e80212cd86076be882d9f91/core/src/km_core_state_context_set_if_needed.cpp#L128-L135

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #10615 (surrogate handling, km_core_state_context_set_if_needed).
Fixes #10616, #10388 (markers in app context, in unit tests)
Fixes #10617 (memory leak in replace_context).

The surrogate handling and markers in app context bugs were quite tangled, so opted to fix those both together in one commit. The memory leak was spotted while verifying the changes for surrogate handling.

Surrogates were not handled in is_context_unchanged, and opted to refactor to work directly with km_core_context_item arrays rather than continue with the string-based comparison, for simplicity.

While writing the corresponding unit tests, realised that the app_context checks were incorrect in a number of existing tests, and so fixed up the existing tests at the same time as writing up the new tests. The only changes to core for this were to add assertions for the app_context to ensure that markers are not inadvertently added.

# User Testing

# Windows Tests

## SUITE_WINDOWS 

* **TEST_HIEROGLYPHIC_WINDOWS**
  1. Install Hieroglyphic Keyboard from keyman.com into Keyman for Windows.
  2. Open Wordpad.
  3. Select the Hieroglyphic keyboard
  4. In wordpad, type: <kbd>w</kbd><kbd>d</kbd><kbd>i</kbd><kbd>spacebar</kbd><kbd>spacebar</kbd>
  5. Expected Output : w𓂞
  6. Type:<kbd>backspace</kbd>
  7. Expected Output: w
  

**Non Compliant/non-context-aware apps**

* **TEST_BACKSPACE_DELETES_NON_COMPLIANT**
This is to test that if we have a (non-surrogate) we do not delete two characters. Then test that a surrogate pair deletes both
characters.

1. Download the the basic Text Editor include under the Test Artifacts found in the PR.
2. Install [Hieroglyphic ](url)Keyboard from keyman.com
3. Open the Text Editor .
4. Select the Hieroglyphic keyboard from the status bar
5. Type: <kbd>d</kbd><kbd>i</kbd><kbd>spacebar</kbd><kbd>d</kbd>
6. Expected Output : 𓏙d    and the character bar shows two characters "0133d9"  "0064"
7. Type:<kbd>backspace</kbd>
8. Expected Output: 𓏙
9. Type:<kbd>backspace</kbd>
10. Expected Output: 

## Testing Persiting Options

* **TEST_PERSITING_OPTIONS**

1. Install k_022___options_with_preset.kmx
2. Open Notepad 
3. Type <kbd>a</kbd> 
4. Expected reasult "no. foo"
5. Type <kbd>1</kbd> 
6. Type <kbd>a</kbd> 
7. Expected reasult "foo"
8. Type <kbd>Win</kbd> +<kbd>r</kbd> 
9. In the run Window type regedit
10. Find the registry key for the k_022___options_with_preset.kmx keyboard under active keyboards\options  veriy that "foo" key is there and the value is `1`.  Full path for the registry key is `Computer\HKEY_CURRENT_USER\SOFTWARE\Keyman\Keyman Engine\Active Keyboards\k_022___options_with_preset\options`
11. 5. Type <kbd>0</kbd> 
12. Verify the key in registry is now `0`

## Testing Alerts
* **TEST_ALERTS**

1. Install the `Gujarati Phonetic` keyboard
6. ensure the sound is not muted on the desktop
7. Use any text editor
8. Type type: <kbd>d</kbd><kbd>Space</kbd>
13. Expected result:દ 
14. Type type: <kbd>Shift</kbd> + <kbd>f</kbd>
15. Expected result:     (no output but a bell sound is played)

## Testing Caps Lock

**Note:** When testing in a virtual machine, use an on-screen keyboard (in VirtualBox: Input/Keyboard/Soft Keyboard) and observe the caps lock indicator of the on-screen keyboard. Using the hardware keyboard might show side effects with caps lock.

- Install a keyboard that has `CapsAlwaysOff` store set, e.g. `caps_always_off.kmp`.
- Currently active keyboard is a non-Keyman keyboard

* **TEST_CAPSOFF-EXT_EVENT**: switching turns off caps lock
  - turn on caps lock
  - switch to capsalwaysoff keyboard
  Expected result:
  - caps lock indicator turned off

# Linux Tests

We'll run these tests on Linux -- the same results should follow for other platforms. Note, tests copied from #10480 as they appear to be a good set of stability tests for this area of the code.

### Preparations

- The tests can be be run on any Linux platforms (running with X11). Note that Firefox and Chromium have to be installed from .deb, the snap version won't work because it's missing the ibus patch.

- Install Anki
  - Download [Qt5 version of Anki](https://apps.ankiweb.net/#linux)
  - Run the following commands
    ```bash
    sudo apt update
    sudo apt install zstd
    tar xaf Downloads/anki-2.*-linux-qt5.tar.zst
    cd anki-2.*-linux-qt5
    sudo ./install.sh
    sudo apt install libxcb-xinerama0
    ```
  - When testing in Anki, select e.g. "Tools"/"Study Deck"

- Install patched ibus by running these commands:
  ```
  sudo add-apt-repository ppa:keymanapp/keyman-alpha
  sudo apt upgrade
  ```
  - afterwards running `dpkg -l ibus` should show a version number with `sil` in the version string, e.g. `1.5.28-3sil2~jammy`
 
- [Install build artifacts of this PR](https://github.com/keymanapp/keyman/wiki/How-to-test-artifacts-from-pull-requests-for-Keyman-for-Linux)

- Reboot

- Install the following keyboards in Keyman:
  * [IPA (SIL)](https://keyman.com/keyboards/sil_ipa)
  * [Korean KORDA Jamo (SIL)](https://keyman.com/keyboards/sil_korda_jamo)
  * [Khmer Angkor](https://keyman.com/keyboards/khmer_angkor)
  * [Vedic Sanskrit Devanagari Phonetic (ITRANS)](https://keyman.com/keyboards/itrans_devanagari_sanskrit_vedic)

## SUITE_WRITER: LibreOffice Writer

Open LibreOffice Writer.

### Tests

- **TEST_WRITER_IPA:** Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_WRITER_KO:** Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_WRITER_HI:** Switch to "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard. Type `shrI`. Verify that the result is "श्री". (If the result looks wrong, select all text and change the font to "Siddhanta")
- **TEST_WRITER_KM:** Switch to "Khmer Angkor" keyboard. Select "Khmer Mondulkiri" font. Type `xEjmr`. Verify that the output is "ខ្មែរ".
- **TEST_WRITER_KM_BS:** With the output "ខ្មែរ" still being displayed, press Backspace key 5 times. Verify that after each keystroke a part of the string is removed and after the 5th backspace the entire word is deleted.

## SUITE_GEDIT: gedit

Open gedit.

### Tests

- **TEST_GEDIT_IPA:** Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_GEDIT_KO:** Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_GEDIT_HI:** Switch to "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard. Type `shrI`. Verify that the result is "श्री".
- **TEST_GEDIT_KM:** Switch to "Khmer Angkor" keyboard. Type `xEjmr`. Verify that the output is "ខ្មែរ".
- **TEST_GEDIT_KM_BS:** With the output "ខ្មែរ" still being displayed, press Backspace key 5 times. Verify that after each keystroke a part of the string is removed and after the 5th backspace the entire word is deleted.

## SUITE_FIREFOX: Firefox

Open https://keyman.com/keyboards in Firefox.

**NOTE:** If the output looks wrong, copy the text from the browser and paste it into gedit and verify that it there.

### Tests

- **TEST_FIREFOX_IPA:** Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_FIREFOX_KO:** Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_FIREFOX_HI:** Switch to "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard. Type `shrI`. Verify that the result is "श्री".
- **TEST_FIREFOX_KM:** Switch to "Khmer Angkor" keyboard. Type `xEjmr`. Verify that the output is "ខ្មែរ".

**NOTE:** Backspace with Firefox won't work correctly because of #9971).

## SUITE_CHROMIUM: Chrome/Chromium

Open https://keyman.com/keyboards in Chrome/Chromium browser.

**NOTE:** If the output looks wrong, copy the text from the browser and paste it into gedit and verify that it there.

### Tests

- **TEST_CHROMIUM_IPA:** Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_CHROMIUM_KO:** Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_CHROMIUM_HI:** Switch to "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard. Type `shrI`. Verify that the result is "श्री".
- **TEST_CHROMIUM_KM:** Switch to "Khmer Angkor" keyboard. Type `xEjmr`. Verify that the output is "ខ្មែរ".
- **TEST_CHROMIUM_KM_BS:** With the output "ខ្មែរ" still being displayed, press Backspace key 5 times. Verify that after each keystroke a part of the string is removed and after the 5th backspace the entire word is deleted.

## SUITE_TERMINAL: gnome-terminal

Open Terminal.

### Tests

**NOTE:** the tests for gnome-terminal won't work because of #10481 and #10536

## SUITE_ANKI: Anki

Open Anki.

### Tests

- **TEST_ANKI_IPA:** Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_ANKI_KO:** Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_ANKI_HI:** Switch to "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard. Type `shrI`. Verify that the result is "श्री" (If the result looks wrong, copy/paste it in text editor and verify there).
- **TEST_ANKI_KM:** Switch to "Khmer Angkor" keyboard. Type `xEjmr`. Verify that the output is "ខ្មែរ".
- **TEST_ANKI_KM_BS:** With the output "ខ្មែរ" still being displayed, press Backspace key 5 times. Verify that after each keystroke a part of the string is removed and after the 5th backspace the entire word is deleted.

## SUITE_SEARCHBAR: Searchbar in gnome-shell

Press Windows key to open searchbar.

### Tests

- **TEST_SEARCHBAR_IPA:** Switch to "IPA (SIL)" keyboard. Type `n>`. Verify that the result is "ŋ".
- **TEST_SEARCHBAR_KO:** Switch to "Korean KORDA Jamo (SIL)" keyboard. Type `han<space>geul<space>`. Verify that the result is "한글".
- **TEST_SEARCHBAR_HI:** Switch to "Vedic Sanskrit Devanagari Phonetic (ITRANS)" keyboard. Type `shrI`. Verify that the result is "श्री".
- **TEST_SEARCHBAR_KM:** Switch to "Khmer Angkor" keyboard. Type `xEjmr`. Verify that the output is "ខ្មែរ".
- **TEST_SEARCHBAR_KM_BS:** With the output "ខ្មែរ" still being displayed, press Backspace key 5 times. Verify that after each keystroke a part of the string is removed and after the 5th backspace the entire word is deleted.

### CODE REVIEW

File: core/src/km_core_state_context_set_if_needed.cpp [hunk 1]
```diff
@@ -132,6 +132,7 @@ replace_context(
       km_core_context_items_dispose(new_context_items);
       return false;
     }
+    km_core_context_items_dispose(new_context_items);
```
Comment (mcdurdin) [inline core/src/km_core_state_context_set_if_needed.cpp:135]: memory leak fix

File: core/src/km_core_state_context_set_if_needed.cpp [hunk 2]
```diff
@@ -175,73 +176,84 @@ context_previous_char(
...
-  uint8_t n = 1;
-  for (; new_context_p > new_context_string; new_context_p--) {
+
+  for (n = 1; new_context_p > new_context_items; new_context_p--) {
     n++;
   }
   change_type.type = CONTEXT_SHORTER;
   change_type.end_difference = n;
+
+is_context_unchanged_cleanup:
```
Comment (mcdurdin) [inline core/src/km_core_state_context_set_if_needed.cpp:255]: I may rewrite this as a wrapper function to avoid goto and separate out the concerns a bit further.

File: core/src/km_core_state_context_set_if_needed.cpp [hunk 3]
```diff
@@ -31,16 +31,16 @@ enum context_changed_type {
 
 typedef struct {
   enum context_changed_type type;
-  // the number of characters/context items (from beginning of context)
-  // that are missing from the new/internal context.
+  // the number of context items (from beginning of context)
+  // that are missing from the new/internal context (i.e. USV not UTF-16)
   uint32_t end_difference;
-} context_change_type;
+} context_change;
```
Comment (mcdurdin) [inline core/src/km_core_state_context_set_if_needed.cpp:37]: renamed because I was frequently confused by `context_changed_type` vs `context_change_type` :grin:

File: core/src/km_core_state_context_set_if_needed.cpp [hunk 4]
```diff
@@ -175,73 +176,84 @@ context_previous_char(
...
     change_type.type = CONTEXT_UNCHANGED;
-    km_core_context_items_dispose(context_items);
-    return change_type;
+    goto is_context_unchanged_cleanup;
   }
 
   if (context_p >= context_items) {
-    uint8_t n = 1;
-    for (; context_p > context_items; context_p--) {
+    for (n = 1; context_p > context_items; context_p--) {
```
Comment (rc-swag) [inline core/src/km_core_state_context_set_if_needed.cpp:241]: I note that here we are just happy with the decrement, where as earlier it used `context_previous_char` which skips markers. For  `new_context_items` it doesn't matter as it is created using `context_items_from_utf16` ensuring markers are already stripped.

**Review by rc-swag — APPROVED** [review]
LGTM
just some questions that don't change the outcome of the code

File: core/src/km_core_state_context_set_if_needed.cpp (hunk 4 above)
Comment (rc-swag) [reply core/src/km_core_state_context_set_if_needed.cpp:241]: Looking at this again, this is actually what needs to be done. It needs to count both the markers and the characters in the count difference as it will then use this count to shrink the cached_context.  It was correct not use `context_previous_char`

File: core/src/km_core_context_api.cpp [hunk 5]
```diff
@@ -201,7 +201,13 @@ km_core_status context_append(km_core_context *ctxt,
   {
     for (;ci->type != KM_CORE_CT_END; ++ci)
     {
-      ctxt->emplace_back(*ci);
+      assert(ci->type == KM_CORE_CT_CHAR || ci->type == KM_CORE_CT_MARKER);
```
[the remark this answers is not in the document]
Comment (mcdurdin) [reply core/src/km_core_context_api.cpp:204]: ensuring that inputs are valid

File: core/src/km_core_state_context_set_if_needed.cpp (hunk 4 above)
Comment (mcdurdin) [reply core/src/km_core_state_context_set_if_needed.cpp:263]: Hopefully reflected in the function description now

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_WRITER: LibreOffice Writer

* **TEST_WRITER_IPA (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed IPA (SIL) keyboard. Verified that it is showing the correct output. 
* **TEST_WRITER_KO (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Koren KORDA keyboard. Verified that it is showing the correct output. 
* **TEST_WRITER_HI (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Vedic Sanskrit keyboard. Verified that it is showing the correct output. 
* **TEST_WRITER_KM (FAILED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Khmer Angkor keyboard. Verified that it is showing the wrong output. 

   


* **TEST_WRITER_KM_BS (FAILED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Khmer Angkor keyboard. Verified that it is showing the wrong output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_GEDIT: gedit

* **TEST_GEDIT_IPA (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed IPA (SIL) keyboard. Verified that it is showing the correct output. 
* **TEST_GEDIT_KO (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Korean KORDA keyboard. Verified that it is showing the correct output. 
* **TEST_GEDIT_HI (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Vedit Sanskrit keyboard. Verified that it is showing the correct output. 
* **TEST_GEDIT_KM (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Khmer Angkor keyboard. Verified that it is showing the correct output. 
* **TEST_GEDIT_KM_BS (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Khmer Angkor keyboard. Verified that after pressing the backspace key 5 times, the entire word is gone from the text editor.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_FIREFOX: Firefox

* **TEST_FIREFOX_IPA (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed IPA (SIL) keyboard. 2. Opened Firefox browser. 3. Opened the Keyboard Search bar from the Keyman Site. 4. Switch to the IPA (SIL) keyboard. Verified that it is showing the correct output. 
* **TEST_FIREFOX_KO (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Korean KORDA keyboard. 2. Opened Firefox browser. 3. Opened the Keyboard Search bar from the Keyman Site. 4. Switch to the Korean KORDA keyboard. Verified that it is showing the correct output. 
* **TEST_FIREFOX_HI (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Vedic Sanskrit keyboard. 2. Opened Firefox browser. 3. Opened the Keyboard Search bar from the Keyman Site. 4. Switch to the Vedic Sanskrit keyboard. Verified that it is showing the correct output. 
* **TEST_FIREFOX_KM (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Khmer Angkor keyboard. 2. Opened Firefox browser. 3. Opened the Keyboard Search bar from the Keyman Site. 4. Switch to the Khmer Angkor keyboard. Verified that it is showing the correct output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_CHROMIUM: Chrome/Chromium

* **TEST_CHROMIUM_IPA (FAILED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed IPA (SIL) keyboard. 2. Opened Chromium browser. 2. Opened the Keyboard Search bar from Keyman Site. 3. Switched to the corresponding keyboard. 4. Verified that it is showing the wrong output. 5. Copied and pasted it into gedit and verified it is showing the wrong output. 

ChromIPAbrowser

* **TEST_CHROMIUM_KO (FAILED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Korean KORDA keyboard. 2. Opened Chromium browser. 2. Opened the Keyboard Search bar from the Keyman Site. 3. Switched to the corresponding keyboard. 4. Verified that it is showing the wrong output. 5. Copied and pasted it into gedit and verified it is showing the wrong output. 

   

* **TEST_CHROMIUM_HI (FAILED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Vedic Sanskrit keyboard. 2. Opened Chromium browser. 2. Opened the Keyboard Search bar from the Keyman Site. 3. Switched to the corresponding keyboard. 4. Verified that it is showing the wrong output. 5. Copied and pasted it into gedit and verified it is showing the wrong output. 

   


* **TEST_CHROMIUM_KM (FAILED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Khmer Angkor keyboard. 2. Opened Chromium browser. 2. Opened the Keyboard Search bar from the Keyman Site. 3. Switched to the corresponding keyboard. 4. Verified that it is showing the wrong output. 5. Copied and pasted it into gedit and verified it is showing the wrong output. 

   

* **TEST_CHROMIUM_KM_BS (FAILED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed IPA (SIL) keyboard. 2. Opened Chromium browser. 2. Opened the Keyboard Search bar from the Keyman Site. 3. Switched to the corresponding keyboard. 4. Verified that it is showing the wrong output. 5. Copied and pasted it into gedit and verified it is showing the wrong output.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_ANKI: Anki

* **TEST_ANKI_IPA (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed IPA (SIL) keyboard. 2. Opened Anki app. 3. Opened Study Deck, Filter Search bar. 4. Switched to the corresponding keyboard. 5. Typed and verified that it is showing the correct output. 
* **TEST_ANKI_KO (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Korean KORDA keyboard. 2. Opened Anki app. 3. Opened Study Deck, Filter Search bar. 4. Switched to the corresponding keyboard. 5. Typed and verified that it is showing the correct output. 
* **TEST_ANKI_HI (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Vedic Sanskrit keyboard. 2. Opened Anki app. 3. Opened Study Deck, Filter Search bar. 4. Switched to the corresponding keyboard. 5. Typed and verified that it is showing the correct output.  
* **TEST_ANKI_KM (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Khmer Angkor keyboard. 2. Opened Anki app. 3. Opened Study Deck, Filter Search bar. 4. Switched to the corresponding keyboard. 5. Typed and verified that it is showing the correct output. 
* **TEST_ANKI_KM_BS (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Khmer Angkor keyboard. 2. Opened Anki app. 3. Opened Study Deck, Filter Search bar. 4. Switched to the corresponding keyboard. 5. Typed and verified that it is showing the correct output. 6. Pressing the Backspace key 5 times removed the entire text. Seems to be working fine.

**Comment by mcdurdin** [comment]
@bharanidharanj could you retest the failing tests on an earliee version of Ubuntu because we know that 23.10 has some compatibility issues.

Thanks!

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_SEARCHBAR: Searchbar in gnome-shell

* **TEST_SEARCHBAR_IPA (FAILED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) (X11) and here is my observation: 1. Installed IPA (SIL) keyboard. 2. Clicked on the gnome Search bar. 3. Switched to the corresponding keyboard. 4. I observed that when I type 'n>' in the search bar, the text promptly disappears.

   

* **TEST_SEARCHBAR_KO (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Korean KORDA keyboard. 2. Clicked on the gnome Search bar. 3. Switched to the corresponding keyboard. 4. Verified that it is showing the correct output. 

* **TEST_SEARCHBAR_HI (FAILED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed Vedic Sanskrit keyboard. 2. Clicked on the gnome Search bar. 3. Switched to the corresponding keyboard. 4. I observed that when I type 'shrI' in the search bar, the text promptly disappears.

   

* **TEST_SEARCHBAR_KM (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed IPA (SIL) keyboard. 2. Clicked on the gnome Search bar. 3. Switched to the corresponding keyboard. 4. Verified that it is showing the correct output. 


* **TEST_SEARCHBAR_KM_BS (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+mantic1) on Ubuntu 23.10 Linux OS (VM) and here is my observation: 1. Installed IPA (SIL) keyboard. 22. Clicked on the gnome Search bar. 3. Switched to the corresponding keyboard. 4. Verified that it is showing the correct output. 5. Pressing the Backspace key 5 times removed the entire text.

**Comment by mcdurdin** [comment]
@keymanapp-test-bot retest SUITE_WRITER  TEST_WRITER_KM TEST_WRITER_KM_BS SUITE_CHROMIUM  TEST_CHROMIUM_IPA TEST_CHROMIUM_KO TEST_CHROMIUM_HI TEST_CHROMIUM_KM TEST_CHROMIUM_KM_BS SUITE_SEARCHBAR  TEST_SEARCHBAR_IPA TEST_SEARCHBAR_HI

**Comment by bharanidharanj** [comment]
## SUITE_WRITER: LibreOffice Writer

* **TEST_WRITER_KM (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+jammy1) on Ubuntu 22.04 Linux OS (VM) and here is my observation: 1. Installed Khmer Angkor keyboard. Typed the relevant text and verified that it was showing the correct output.
* **TEST_WRITER_KM_BS (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+jammy1) on Ubuntu 22.04 Linux OS (VM) and here is my observation: 1. Installed Khmer Angkor keyboard. Typed the relevant text and verified that it was showing the correct output.

## SUITE_CHROMIUM: Chrome/Chromium

* **TEST_CHROMIUM_IPA (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+jammy1) on Ubuntu 22.04 Linux OS (X11) and here is my observation: 1. Installed IPA (SIL) keyboard. 2. Opened Firefox browser. 3. Opened the Keyboard Search bar from the Keyman Site. 4. Switch to the IPA (SIL) keyboard. Typed the relevant text and verified that it was showing the correct output.
* **TEST_CHROMIUM_KO (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+jammy1) on Ubuntu 22.04 Linux OS (X11) and here is my observation: 1. Installed Korean KORDA keyboard. 2. Opened Firefox browser. 3. Opened the Keyboard Search bar from the Keyman Site. 4. Switch to the Korean KORDA keyboard. Typed the relevant text and verified that it was showing the correct output.
* **TEST_CHROMIUM_HI (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+jammy1) on Ubuntu 22.04 Linux OS (X11) and here is my observation: 1. Installed Vedic Sanskrit keyboard. 2. Opened Firefox browser. 3. Opened the Keyboard Search bar from the Keyman Site. 4. Switch to the Vedic Sanskrit keyboard. Typed the relevant text and verified that it was showing the correct output.
* **TEST_CHROMIUM_KM (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+jammy1) on Ubuntu 22.04 Linux OS (X11) and here is my observation: 1. Installed Khmer Angkor keyboard. 2. Opened Firefox browser. 3. Opened the Keyboard Search bar from the Keyman Site. 4. Switch to the Khmer Angkor keyboard. Typed the relevant text and verified that it was showing the correct output.
* **TEST_CHROMIUM_KM_BS (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+jammy1) on Ubuntu 22.04 Linux OS (X11) and here is my observation: 1. Installed Khmer Angkor keyboard. 2. Opened Firefox browser. 3. Opened the Keyboard Search bar from the Keyman Site. 4. Switch to the Khmer Angkor keyboard. Typed the relevant text and verified that it was showing the correct output. 5. Pressing Backspace key 5 times removed the entire text in the Search bar. Seems to be working fine.

**Comment by bharanidharanj** [comment]
## SUITE_SEARCHBAR: Searchbar in gnome-shell

* **TEST_SEARCHBAR_IPA (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+jammy1) on Ubuntu 22.04 Linux OS (VM) and here is my observation: 1. Installed IPA (SIL) keyboard. 2. Clicked on the gnome Search bar. 3. Switched to the corresponding keyboard. 4. Verified that it is showing the correct output.
* **TEST_SEARCHBAR_HI (PASSED):** Tested with the attached PR build (17.0.261-alpha-local (package version 17.0.261-1~PR-10618-2262.1+jammy1) on Ubuntu22.04 Linux OS (VM) and here is my observation: 1. Installed Vedic Sanskrit keyboard. 2. Clicked on the gnome Search bar. 3. Switched to the corresponding keyboard. 4. Verified that it is showing the correct output.

**Comment by rc-swag** [comment]
@bharanidharanj  also note I have added some more Windows tests. These will need to be completed on this PR thanks.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_WINDOWS: 

* **TEST_BACKSPACE_DELETES_NON_COMPLIANT (PASSED):** Tested with the attached PR build (17.0.261-alpha-test-10618) on Windows 11 OS (VM) and here is my observation : 1. Installed Hieroglyphic Keyboard from Keyman.com Site. 2. Opened Text Editor (64 bit). 3. Switched to Hieroglyphic keyboard. 4. Noticed that it is showing  𓏙d on the screen. Not able to view the two mentioned characters since this editor does not show the character bar. 5. Typed Backspace key. Verified the output  𓏙 on the screen. 6. Typed Backspace key. Verified that it does not show up anything on the screen. Seems to be working fine.

**Comment by bharanidharanj** [comment]
* **TEST_ALERTS (PASSED):** Tested with the attached PR build (17.0.261-alpha-test-10618) on Windows 11 OS (VM) and here is my observation: 1. Installed the Gujarati Phonetic keyboard. 2. Opened Notepad app. 3. Switched to Gujarati Phonetic keyboard. 4. Typed d spacebar showing the expected result દ on the screen. 5. Able to hear the bell sound after pressing the Shift+f keys and no output appears on the screen. Seems to be working fine.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_WINDOWS: 

* **TEST_CAPSOFF-EXT_EVENT (PASSED):** Tested with the attached PR build (17.0.261-alpha-test-10618) on Windows 11 OS (VM) and here is my observation: 1. Installed CapsAlwaysOff keyboard. 2. Verified that the active keyboard is a non-keyman (English(IN)) keyboard. 3. Turned ON the caps lock indicator from the physical keyboard. 4. Switched to CapsAlwaysOff keybaord. 5. Verified that the physical keyboard's caps lock indicator turned off. It is working fine.

**Comment by bharanidharanj** [comment]
# Test Results

## SUITE_WINDOWS: 

* **TEST_PERSITING_OPTIONS (PASSED):** Tested with the attached PR build (17.0.261-alpha-test-10618) on Windows 10 OS and here is my observation: 1. Installed 022-Options with preset keyboard. 2. Opened Notepad app. 3. Switched to 022-options with preset keyboard. Verified that it showed the expected result. 4. Opened Registry editor. 5. Verified that "foo" key was there with value 1. 6. Set the value to '0'. Verified that the Value changed to '0'. 

..Result 1

   


..Result 2

File: core/src/context.hpp [hunk 6]
```diff
@@ -23,6 +24,7 @@ namespace core
 class context: public std::list<km_core_context_item>
 {
 public:
+  bool has_markers = true;
```
Comment (srl295) [inline core/src/context.hpp:27]: is it really `allow_markers` ?

Would be good to document. `has_markers` sounds like it's only observational.

File: core/src/state.cpp [hunk 7]
```diff
@@ -40,6 +40,7 @@ void actions::push_capslock(bool turnOn) {
 state::state(km::core::abstract_processor & ap, km_core_option_item const *env)
   : _processor(ap)
 {
+  _app_ctxt.has_markers = false;
```
Comment (srl295) [inline core/src/state.cpp:43]: explain why here?

File: core/tests/unit/kmnkbd/state_context_api.cpp [hunk 8]
```diff
@@ -90,6 +90,23 @@ is_identical_context(km_core_cp const *cached_context) {
     km_core_context_items_dispose(citems_new);                                                     \
   }
 
+// citems contains markers, but we will skip over them
```
Comment (srl295) [inline core/tests/unit/kmnkbd/state_context_api.cpp:93]: huh, ldml.cpp unit test has an identical check..!

**Review by srl295 — APPROVED** [review]
LGTM but documentation would be good

File: core/src/context.hpp (hunk 6 above)
Comment (mcdurdin) [reply core/src/context.hpp:27]: `has` makes sense here because it's about the purpose of the `context` object -- will we be working with markers or not? "My dog has spots" vs "My dog is allowed to have spots" (thanks @rc-swag for the example)

File: core/src/state.cpp (hunk 7 above)
Comment (mcdurdin) [reply core/src/state.cpp:43]:
```suggestion
  // The app context will never have markers, because it is an exact
  // copy of the context passed in from the application, in whatever
  // normalization form that the app is using.
  _app_ctxt.has_markers = false;
```

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.262-alpha](https://keyman.com/downloads/releases/alpha/17.0.262)
