### PR TITLE
Rework the [Install into app] infrastructure and fix bugs

### LINKED ISSUE #668: Keyboard Test Host fails to install keyboard
Using Keyman Developer 10.0.1040.0, I can connect to the **Keyboard Test Host** from the Android emulator. However, "Install Keyboard into Keyman app" fails to install the keyboard (Khmer Angkor).

The confirmation dialog appears, but investigate if there's a connection issue preventing the keyboard from installing

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #668

### CODE REVIEW

File: windows/src/developer/TIKE/web/UmodWebHttpServer.pas [hunk 1]
```diff
@@ -437,92 +441,49 @@ procedure TmodWebHttpServer.httpCommandGet(AContext: TIdContext;
...
-          begin
-            jsonLanguage := TJSONObject.Create;
-            jsonLanguage.AddPair('id', 'eng');
-            jsonLanguage.AddPair('name', 'English');
-            jsonLanguages.Add(jsonLanguage);
-            jsonKeyboard.RemovePair('languages');
-            jsonKeyboard.AddPair('languages', jsonLanguages);
-          end;
+        jsonLanguage := TJSONObject.Create;
+        jsonLanguage.AddPair('id', 'eng');
```
[the remark this answers is not in the document]
Comment (mcdurdin) [reply windows/src/developer/TIKE/web/UmodWebHttpServer.pas]: Yes

File: windows/src/developer/TIKE/web/UmodWebHttpServer.pas [hunk 2]
```diff
@@ -437,92 +441,49 @@ procedure TmodWebHttpServer.httpCommandGet(AContext: TIdContext;
...
+        jsonFont := TJSONObject.Create;
+        jsonFont.AddPair('family', value.FontName[kfontChar]);   // I4409
+        jsonFont.AddPair('filename', value.ID+'-'+value.Version+'-'+TestFontName[kfontChar]+'.ttf');   // I4409
+        jsonKeyboard.AddPair('font', jsonFont);
 
-          jsonOptions.RemovePair('fontBaseUri').Free;
-          jsonOptions.AddPair('fontBaseUri', FFontBaseUri);
+        jsonOskFont := TJSONObject.Create;
+        jsonOskFont.AddPair('family', value.FontName[kfontOSK]);   // I4409
+        jsonOskFont.AddPair('filename', value.ID+'-'+value.Version+'-'+TestFontName[kfontOSK]+'.ttf');   // I4409
```
Comment (darcywong00) [inline windows/src/developer/TIKE/web/UmodWebHttpServer.pas]: Is `filename` correct? When I've tested legacy distribution, I've been using this JSON
```
    "font": {
      "family":"Khmer Mondulkiri",
      "source":"Mondulkiri-R.ttf"
    },
    "oskFont": {
      "family":"Khmer Mondulkiri",
      "source":"Mondulkiri-R.ttf"
    },
```

Comment (mcdurdin) [reply windows/src/developer/TIKE/web/UmodWebHttpServer.pas]: Indeed you are right. `filename` was an old, wrong way of doing it.
