### PR TITLE
fix(developer): touch layout osk import handling of multiple modifiers

### LINKED ISSUE #2740: bug(developer): Importing OSK can import wrong layer onto touch layout
**Describe the bug**
Importing the OSK in the keyboard me_en wrongly imports Ralt+shift layer into the default layer.

**To Reproduce**
1. Open me_en.kmn.
2. Click on Touch Layout
3. Click Import from On Screen
4. Observe the ralt+shift layer importing into the default layer of the touch layout

---
 
**Keyman Developer:**
 - OS: Windows 10
 - Keyman Developer version: 13.0.101.0

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #2740.

The definitions for several of the combined modifiers was incorrect, which led to a mismatch when attempting to import those layers from a visual keyboard into the touch layout editor.

### CODE REVIEW

File: windows/src/developer/TIKE/oskbuilder/TouchLayoutDefinitions.pas [hunk 1]
```diff
@@ -123,12 +123,12 @@   TJSONDef = record
...
-    'shift-lctrl',
-    'shift-rctrl',
-    'shift-lalt',
-    'shift-ralt',
-    'shift-lctrl-lalt',
-    'shift-rctrl-ralt'
+    'leftctrl-shift',
+    'rightctrl-shift',
+    'leftalt-shift',
+    'rightalt-shift',
```
Comment (darcywong00) [inline windows/src/developer/TIKE/oskbuilder/TouchLayoutDefinitions.pas:129]: Will this impact existing keyboards?

These layers are currently in use:

## shift-ralt
* basic_kbdarmph
* basic_kbdarmty
* basic_kbdcher
* basic_kbdinen

## shift-rightalt
* basic_kbdindev

Comment (mcdurdin) [reply windows/src/developer/TIKE/oskbuilder/TouchLayoutDefinitions.pas:129]: No, it's only used in the import from osk to touch layout. If we use those definitions elsewhere in the future, it's important that they match up, but even then existing keyboards will not be impacted.

Comment (jahorton) [inline windows/src/developer/TIKE/oskbuilder/TouchLayoutDefinitions.pas:129]: A KMW reference for default layer names:

https://github.com/keymanapp/keyman/blob/81d7722bf4840d43589de4bc8a3f632c34ed2574/common/core/web/keyboard-processor/src/keyboards/defaultLayouts.ts#L86-L106

Comment (jahorton) [reply windows/src/developer/TIKE/oskbuilder/TouchLayoutDefinitions.pas:129]: So, :+1:

**Review by jahorton — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.251-beta](https://keyman.com/downloads/releases/beta/14.0.251)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.19-alpha](https://keyman.com/downloads/releases/alpha/15.0.19)
