### PR TITLE
fix(web): osk size & position after focus changes

### LINKED ISSUE #3697: bug(web): desktop osk resets to original size after any key press or control focus change
**Describe the bug**
Any resizing of the desktop OSK is lost the first time a key is pressed or control focus changes -- it resets to the original size.

**To Reproduce**
1. Open web/testing/unminified.html in a desktop browser
2. Select Lao Basic, for instance.
3. Drag the bottom right corner of the OSK to resize
4. Click a key or change focus
5. The OSK resets to original size

**Expected behavior**
The OSK should not resize

---

**KeymanWeb:**
 - OS: Windows 10
 - Browser: Chrome
 - KeymanWeb Version: 14.0.157
 - URL: web/testing/unminified.html

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #3697.

One of the handlers failed to update two important fields:  `OSKManager.width` and `OSKManager.height`.  _These_ are the fields that are used to set OSK cookie properties... which are then used to reload the properties whenever focus shifts between (DOM) controls.

### CODE REVIEW

File: web/source/osk/oskManager.ts [hunk 1]
```diff
@@ -797,6 +793,8 @@ namespace com.keyman.osk {
         var r=this.getRect();
         this.width=r.width;
         this.height=r.height;
+        this.x = r.left;
+        this.y = r.top;
```
Comment (jahorton) [inline web/source/osk/oskManager.ts:797]: This is part of the OSK-repositioning mouse-move handler.  Width and height shouldn't really be changed here; the important parts are the left & top positions.

With these changes, it becomes possible to bypass cookie loads & saves after the initial load.  (See the first commit, which did _exactly_ this until I figured out how to fix the cookies, too.)

File: web/source/osk/oskManager.ts [hunk 2]
```diff
@@ -934,6 +928,19 @@ namespace com.keyman.osk {
...
+        this.height = height;
+      }
+
+      if(this.vkbd) {
+        this.vkbd.kbdDiv.style.width=this.width+'px';
+        this.vkbd.kbdDiv.style.height=this.height+'px';
+        this.vkbd.kbdDiv.style.fontSize=(this.height/8)+'px';
+      }
+    }
+
```
Comment (jahorton) [inline web/source/osk/oskManager.ts:943]: Compare with lines 861-864 below:

https://github.com/keymanapp/keyman/blob/f20098244aebc2a8b157c2e2e147d7bfd9e69262/web/source/osk/oskManager.ts#L861-L864

The bug arose because `this.width` and `this.height` were previously neglected by a handler or two.

(From the method quoted below)

https://github.com/keymanapp/keyman/blob/f20098244aebc2a8b157c2e2e147d7bfd9e69262/web/source/osk/oskManager.ts#L847-L867

File: web/source/osk/oskManager.ts [hunk 3]
```diff
@@ -1280,7 +1289,9 @@ namespace com.keyman.osk {
       if(device.formFactor == 'desktop') {
         Ls.position='absolute'; Ls.display='block'; //Ls.visibility='visible';
         Ls.left='0px';
-        this.loadCookie();
+
+        this.setSize();
+
```
Comment (jahorton) [inline web/source/osk/oskManager.ts]: First commit only:  the 'kill-switch' to disable constant use of the OSK cookie.  The cookie would still be used to initialize the OSK, but any other control focuses would then rely on state fields.

As web cookies are synchronous, there shouldn't be any significant harm from continuing to rely on the cookies.

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.220-beta](https://keyman.com/downloads/releases/beta/14.0.220)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.9-alpha](https://keyman.com/downloads/releases/alpha/15.0.9)
