### PR TITLE
[Android] Improve font handling

### LINKED ISSUE #1478: [Android] Crash retrieving missing font
KMManager.java line 620
com.tavultesoft.kmea.KMManager.getFontTypeface

https://console.firebase.google.com/u/0/project/kmapro-ee779/crashlytics/app/android:com.tavultesoft.kmapro/issues/5c2dd37df8b88c29630b871c?time=last-seven-days&pli=1

```
Fatal Exception: java.lang.RuntimeException
Font not found /data/user/0/com.tavultesoft.kmapro/app_data/cloud/wookianos.woff

Fatal Exception: java.lang.RuntimeException: Font not found /data/user/0/com.tavultesoft.kmapro/app_data/cloud/wookianos.woff
       at android.graphics.Typeface.createFromFile(Typeface.java:330)
       at android.graphics.Typeface.createFromFile(Typeface.java:313)
       at com.tavultesoft.kmea.KMManager.getFontTypeface(KMManager.java:620)
       at com.tavultesoft.kmea.KMKeyboard.showSubKeys(KMKeyboard.java:706)
       at com.tavultesoft.kmea.KMKeyboard.access$200(KMKeyboard.java:54)
       at com.tavultesoft.kmea.KMKeyboard$2.onLongPress(KMKeyboard.java:156)
       at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:809)
       at android.view.GestureDetector.-wrap0(GestureDetector.java)
       at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:305)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6780)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

This is occurring in the beta version of Keyman for Android 11.0.2050.0

### PR DESCRIPTION
**Pull request by darcywong00**
This PR addresses two issues in how Keyman for Android handles fonts:
gff_amharic keyboard lists associated fonts in this order:
```
          "wookianos.woff",
          "wookianos.ttf",
          "wookianos.mobileconfig",
          "ETHIOPI0.eot"
```
and the current Android app just grabs the first one (.woff) when making the Typeface in the WebView.

1. Fixes #1478 where certain Android SDK levels crash when attempting to create a Typeface from a .woff font
This could be replicated in an emulator of SDK level 15 and attempting to download the Amharic keyboard.

2. When downloading keyboard that lists multiple fonts, choose the .ttf if available

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/138379:id/kvk/index.html)

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java [hunk 1]
```diff
@@ -384,6 +393,67 @@ public static boolean isCustom(String u) {
...
+          }
+
+          if (updateJsonFont) {
+            JSONArray copy = fontSource;
+            jsonFont.remove(KMManager.KMKey_FontSource);
+            jsonFont.put(KMManager.KMKey_FontSource, copy);
+          }
+        }
+      }
+    } catch (JSONException e) {
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: In what scenarios can you see an exception? Shouldn't we at least log it?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java [hunk 2]
```diff
@@ -384,6 +393,67 @@ public static boolean isCustom(String u) {
...
+    try {
+      for (int i = 0; i < fontSource.length(); i++) {
+        String s = fontSource.getString(i);
+        if (s.toLowerCase().endsWith(FileUtils.TRUETYPEFONT)) {
+          return true;
+        }
+      }
+      return false;
+    } catch (JSONException e) {
+      return false;
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: Ditto; In what scenarios can you see an exception? Shouldn't we at least log it?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java [hunk 3]
```diff
@@ -384,6 +393,67 @@ public static boolean isCustom(String u) {
...
+    try {
+      JSONArray fontSource = jsonFont.optJSONArray(KMManager.KMKey_FontSource);
+      if (fontSource != null) {
+        boolean containsTTF = hasTTFFont(fontSource);
+        if (containsTTF) {
+          for (int i = fontSource.length() - 1; i >= 0; i--) {
+            String s = fontSource.getString(i);
+            if (!FileUtils.isTTFFont(s)) {
+              updateJsonFont = true;
+              if (Build.VERSION.SDK_INT > 19) {
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: Why the two different code paths? Does the `remove` function not work in earlier versions?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java [hunk 4]
```diff
@@ -384,6 +393,67 @@ public static boolean isCustom(String u) {
...
+                fontSource.remove(i);
+              } else {
+                fontSource = removeJsonObjectAtIndex(fontSource, i);
+              }
+            }
+          }
+
+          if (updateJsonFont) {
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: Have you tested a scenario where `findTTF` removes all entries from the array (e.g. only includes a .woff and .mobileconfig or something like that)?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java [hunk 5]
```diff
@@ -392,10 +462,21 @@ public static boolean isCustom(String u) {
...
       int fcCount = fontSource.length();
+      boolean containsTTF = hasTTFFont(fontSource);
       for (int i = 0; i < fcCount; i++) {
         String fontSourceString;
         try {
           fontSourceString = fontSource.getString(i);
+          // Prioritize .ttf if it exists
+          if (!FileUtils.isTTFFont(fontSourceString) && containsTTF) {
+            if (Build.VERSION.SDK_INT > 19) {
+              fontSource.remove(i);
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: Won't this cause an index overrun with the `for` loop?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java (hunk 3 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: [remove()](https://developer.android.com/reference/org/json/JSONArray#remove(int)) was added for API 19+ so I was getting exceptions on older devices

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java (hunk 1 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: The IDE forces me to enclose the JSON calls in try/catch. I can add logging

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java (hunk 5 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: This block in fontUrls was where I originally started the fix.
But now that it's handled earlier in ll 300-306 I should be able to revert this.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java (hunk 4 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: This is inside the `if (containsTTF) {` block so in that scenario, nothing gets removed.
