### PR TITLE
fix(windows): hint dialog was blank when elevated

### LINKED ISSUE #3110: [Windows] Exit Keyman hint dialog does not render if Debugging is switched on
**Describe the bug**
If Debugging is switched on, then Keyman is run elevated. When the user goes to exit, Keyman launches kmshell to render an exit dialog, but kmshell is launched elevated, so the exit dialog does not render, as Chromium does not run elevated...

This arises from the Chromium refactor in 14.0.

**To Reproduce**
1. Enable debugging in Keyman Configuration and restart Keyman; ensure hints and warnings are reset and on.
2. Attempt to exit Keyman
3. See error

Possible ways to resolve:

1. Don't show hint / help dialogs when Keyman is running elevated? This may be most complex for the Exit dialog which must communicate its result back to the host process.
2. Launch Keyman non-elevated (as is done with Keyman Configuration it seems)

---

**Keyman Desktop:**
 - OS: Windows 10
 - Keyman version: 14.0.71

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #3110. The hint dialog must be launched unelevated. Refactors the UCreateProcessAsShellUser unit into the TUtilExecute class.

### CODE REVIEW

File: windows/src/global/delphi/general/utilexecute.pas [hunk 1]
```diff
@@ -241,4 +256,131 @@ class function TUtilExecute.WaitForProcess(const cmdline, curdir: string; var EC
...
 end;
 
+// Refactored from UCreateProcessAsShellUser
+
+function GetShellWindow: HWND; stdcall; external user32;
+
+type
+  TCreateProcessWithTokenW = function(hToken: THANDLE; dwLogonFlags: DWORD; lpApplicationName: LPCWSTR; lpCommandLine: LPWSTR;
+  dwCreationFlags: DWORD; lpEnvironment: Pointer; lpCurrentDirectory: LPCWSTR; lpStartupInfo: PSTARTUPINFOW;
+  lpProcessInformation: PPROCESSINFORMATION): BOOL; stdcall;
```
Comment (darcywong00) [inline windows/src/global/delphi/general/utilexecute.pas:266]: Do these two lines need some indentation?

**Review by darcywong00 — APPROVED** [review]
lgtm
