### PR TITLE
fix(common/core/web): disambiguation of keys sharing same base key ID

### LINKED ISSUE #4617: bug(web): key-id aliasing results in issues for predictive text, recorder module
**Describe the bug**

The suggestion on the banner does not match the character directly to the left of the cursor. Three words begins with a different character.

Screenshot_1614931057

**To Reproduce**

1. Install this keyboard and the its lm ([brao_keyboard_and_lm.zip](https://github.com/keymanapp/keyman/files/6088954/brao_keyboard_and_lm.zip))
2. In the Keyman text editor area, press the key on the top left -- output ក
3. See error

**Expected behavior**

When ក is pressed, words beginning with ក should be shown on the suggestion, not those beginning with គ.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.252-beta
 - Target Application: Chrome Version 89.0.4389.72 (Official Build) (64-bit) and Keyman app for Android

**Keyman for Android:**
 - Device: Pixel 2 API 29 - emulator
 - OS: Android 10
 - Keyman version 14.0.252-beta
 - Target application: Keyman 

---

**Keyboard**
 - Keyboard name: Brao (SIL)
 - Keyboard version: 1.0
 - Language name: Lave (Brao)

**Additional context**

When click away and click back to the right of the character (say, ក), then the expected words are shown in the banner.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #4617.

Implements the spec suggested within https://github.com/keymanapp/keyman/issues/4617#issuecomment-799907262, additionally noting a few different _kinds_ of ID needed at various levels of keyboard processing:

- `baseKeyIdentifier`:  this is the key ID as known to the Keyman keyboard language.  No modifiers, no layer information, etc.  _**Just**_ the base key.
- `coreID`: `baseKeyIdentifier` + the _modifier_ layer, if different from the key's _display_ layer.
    - "Modifier layer":  the layer representing a modifier set that would be accessible to the Keyman keyboard language, as set by keyboard developers within the touch-layout designer on a per-key basis as an override.
    - Check against https://github.com/keymanapp/keyman/issues/4617#issuecomment-799907262 for further clarification, explanation, and examples as needed.
- `elementID`: the key's _display_ layer + `coreID`.  This is the identifier used as a web element ID and will be unique among all keys of the loaded keyboard (unless there is an intended, _literal_ duplicate key definition).
    - Caveat:  if two separate keyboards are simultaneously loaded somehow, two keys with the same `elementID` may coexist - one from each keyboard.

Note that this does introduce a breaking change for any developer who may have had code relying on key IDs.  That said, this spec does its best to minimize breaks, preserving the original ID structure for the most common cases.

To wit:  I made no changes whatsoever to the unit tests, many of which use pre-recorded sequences that rely, _directly_, on key IDs.  None of them broke.

## User Testing
@MakaraSok 

Please test with the same resources you were using to report the original issue.  The symptoms should be resolved.

From a quick load/test within iOS:

Simulator Screen Shot - iPhone SE (2nd generation) - 2021-03-17 at 11 09 37

Additionally, please test a keyboard or two with subkeys - even `sil_euro_latin` should suffice here.  There were a few tweaks needed to maintain popup key behavior as a result, so we need to be sure that nothing was broken there.

Some tests with `khmer_angkor` would also be good - it has some subkeys with modifiers that don't match the display layer.  For example, ឆ (base key) has ឈ (subkey, '+shift') and ក (base key) គ (subkey, '+shift').  Everything should "feel normal" with no unexpected changes.

Finally, some tests with `sil_cameroon_qwerty` may be nice.  I've already tested them within Web, but Android-based tests may be wise as well.  The top row of its SHIFT layer has some diacritic keys with modifier sets that don't match the SHIFT layer, thus have new IDs internally.  (There may be more keys, but those were the easiest to find.)   Everything should "feel normal" with no unexpected changes.

I've run most of these tests myself on Web, with some also on emulated Android... but it'd be good to have a second pair of eyes on this.

### CODE REVIEW

File: web/source/osk/preProcessor.ts [hunk 1]
```diff
@@ -48,7 +48,13 @@ namespace com.keyman.osk {
...
         outputTarget.deadkeys().deleteMatched();      // Delete any matched deadkeys before continuing
 
-        let keySpec = (e['key'] ? e['key'].spec : null) as keyboards.ActiveKey;
+        // Future note:  we need to refactor osk.OSKKeySpec to instead be a 'tag field' for
+        // keyboards.ActiveKey.  (Prob with generics, allowing the Web-only parts to
+        // be fully specified within the tag.)  
+        //
+        // Would avoid the type shenanigans needed here because of our current type-abuse setup 
+        // for key spec tracking.
+        let keySpec = (e['key'] ? e['key'].spec : null) as unknown as keyboards.ActiveKey;
```
Comment (jahorton) [inline web/source/osk/preProcessor.ts:57]: Naturally, as is practically tradition for me, I've identified a piece of technical debt that could use some future resolution.  Definitely not touching this right now.

It'd be a good fit with any major OSK refactors that may occur in the future.

File: web/source/osk/visualKeyboard.ts [hunk 2]
```diff
@@ -46,6 +46,12 @@ namespace com.keyman.osk {
   //#region OSK key objects and construction
   export class OSKKeySpec implements keyboards.LayoutKey {
     id: string;
+
+    // Only set (within @keymanapp/keyboard-processor) for keys actually specified in a loaded layout
+    baseKeyIdentifier?: string;
+    coreID?: string;
+    elementID?: string;
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:53]: Can you document what these look like with examples here? That will really help for future maintenance.

Also I am not that comfortable with using `Identifier` vs `ID` here. It feels inconsistent.

**Review by mcdurdin — CHANGES_REQUESTED** [review]
I understand the changes I think. I'm not entirely clear on exactly when/where the 3 different identifier types should be used!

Asking for a little more doc on the three new identifiers in `OSKKeySpec`.

**Review by mcdurdin — APPROVED** [review]

**Comment by MakaraSok** [comment]
Tested with this build (image). 

Observation: the prediction works as expected only when there is only one character preceded by a regular space to the left of the caret.
- space + consonant + caret:

Screenshot_1616043513

- space + consonant + subscript + caret:

Screenshot_1616043624

The EuroLatin (SIL) keyboard with the prediction does work as expected when though there are multiple consonants/vowels to the left of the caret:
Screenshot_1616043813

**Comment by jahorton** [comment]
> Tested with this build (image).
>
>     * space + consonant + subscript + caret: 
> 
> Screenshot_1616043624

This is due to this part of your model spec and the fact that you're using Khmer script:

```
        wordBreaker: wordBreakers['default'],
```

The Unicode defaults for Khmer script don't wordbreak as you'd expect, even when manually inserting spaces.  It'll need a custom wordbreaker spec to avoid this, which is separate from this issue.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.265-beta](https://keyman.com/downloads/releases/beta/14.0.265)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.20-alpha](https://keyman.com/downloads/releases/alpha/15.0.20)
