### PR TITLE
fix(android/engine): Update in-app TextView context on pageLoaded

### LINKED ISSUE #3809: bug(android/app): Backspace doesn't work after restoring app text
When the Keyman app loads and restores the previous text, the backspace key on the in-app keyboard fails to delete.

I don't believe this is from predictive text, because I get the same behavior from khmer_angkor.

## Affected builds:
14.0.32 alpha was the last apk where the backspace key worked (see steps below).
14.0.33 alpha fails to load the default keyboard
14.0.34+ onward the backspace key fails.

## Steps to reproduce:
1. Load the Keyman app and enter some text. 
2. Switch to another app (like Chrome) to force the app to save the text.
3. Exit the Keyman app and then reopen it. The previous text should be restored
4. Attempt to backspace a character, and nothing happens

Any correlation to the refactor in #2854?

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #3809

This fixes the race condition where the in-app TextView would load before the in-app keyboard is loaded. The TextView would fail to get existing context.

* Consolidates some WET code to `updateTextContext()`

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMTextView.java [hunk 1]
```diff
@@ -179,11 +187,7 @@ public void onWindowFocusChanged(boolean hasWindowFocus) {
 
       if (activeView != null && activeView.equals(this)) {
         if (KMManager.InAppKeyboardLoaded) {
-          KMTextView textView = (KMTextView) activeView;
-          int selStart = textView.getSelectionStart();
-          int selEnd = textView.getSelectionEnd();
-          KMManager.updateText(KeyboardType.KEYBOARD_TYPE_INAPP, textView.getText().toString());
-          KMManager.updateSelectionRange(KeyboardType.KEYBOARD_TYPE_INAPP, selStart, selEnd);
+          updateTextContext();
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMTextView.java:190]: This is a slight change in functionality here -- do you need to do any tests to validate the change?

**Review by mcdurdin — APPROVED** [review]
LGTM apart from the one question.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMTextView.java (hunk 1 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMTextView.java:190]: Here's what I did to check the context is (now) reset

1. Install basic_kbdfr (it uses deadkeys)
2. With French Basic keyboard selected:
3. Type the deadkey <kbd>^</kbd>
4. Type <kbd>a</kbd> and verify output `â `
5. Now type another deadkey <kbd>^</kbd>
6. Hit the Android square task button, then focus back on Keyman
7. Type <kbd>a</kbd> and verify only 'a' is output (deadkey cleared)

Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMTextView.java:190]: Is that behaviour different to the previous version?

Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMTextView.java:190]: Previous version didn't reset context. Step 7 typing <kbd>a</kbd> would output `â`

Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMTextView.java:190]: Excellent, that's what I was hoping!

**Comment by mcdurdin** [comment]
One last question: what is the difference between `onWindowFocusChanged` and `onFocusChanged`? Are they ever both called?

**Comment by darcywong00** [comment]
> One last question: what is the difference between `onWindowFocusChanged` and `onFocusChanged`? Are they ever both called?

I had to looks this up:
onFocusChanged
https://developer.android.com/reference/android/view/View#onFocusChanged(boolean,%20int,%20android.graphics.Rect)
> Called when the view gains or loses focus

onWindowFocusChanged
https://developer.android.com/reference/android/view/View#onWindowFocusChanged(boolean)
> Called when the window containing the view gains or loses focus.

And the difference:
>  If a window is displayed on top of yours that takes input focus, then your own window will lose focus but the view focus will remain unchanged.
