### PR TITLE
[iOS] Keyboard refactor + rotation fix

### LINKED ISSUE #444: [iOS] Landscape keyboard sized incorrectly on iPhone X
KeymanEngine sets the width of keyboard views to the screen width. But on iPhone X, the keyboard is not given full width in landscape.

Landscape system keyboard:
screen shot 2017-11-24 at 12 28 41 pm

Landscape in-app keyboard:
screen shot 2017-11-24 at 12 30 12 pm

Portrait system keyboard (correct but just for reference):
screen shot 2017-11-24 at 12 29 38 pm

### LINKED ISSUE #1045: [iOS] bottom row not getting painted correctly
I'm seeing an annoying display problem on my iPad mini 4, any time I return to the main Keyman screen after going to the Keyboards screen. At first I thought it was just a Simulator problem, but I'm also seeing it on my physical device. In portrait mode, only the top 10% of the bottom row gets painted. Below that, it's just a gray bar. In landscape mode, about the top third gets painted. Switching from portrait to landscape or vice verse corrects the problem, but if I ever go back into the Keyboards screen, the problem returns.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #444.
Fixes #1045.

This PR will serve the following purposes:

1. Refactors all keyboard management code into a more centralized and OO-based pattern
2. Merges the code paths for the in-app and system keyboard, simplifying management of keyboard events and layout
3. Implements constraint-based sizing and layout for the keyboard, allowing iOS to automatically handle keyboard rotation events as appropriate for a user's device with little issue. 

As #683 already performs a number of tasks related to point 1 above, this PR will be based upon that PR's work until it is merged.

---

Due to the scale of the work involved, it may be wise to review by commit in some cases.  (That said, the line changed count is surprisingly low for this refactor...)

Particularly interesting commits:

https://github.com/keymanapp/keyman/commit/034680d9f413dfbfa5457a2d9be062406e26eec
* gets in-app keyboard rotation based upon constraints working about as well as `master`'s current state.  It kinda breaks it for the system keyboard, though, but will serve well for further work in constraint-based rotation.
  - Warning logs during debug sessions indicate the need for a merged, centralized keyboard container that can help mediate constraints between our keyboard and the system's expectations of a keyboard view.

https://github.com/keymanapp/keyman/commit/9d7da159f1a199cd6d5284390cd4acd8449be525
* removes `Manager` from the `KeymanWebDelegate` indirection control flow.  `KeymanWebViewController` now directly makes calls to the 'first responder.'
  - This has the effect of partially centralizing and disentangling the in-app vs system control path code, preparing it for further refactoring.
  - More must be done to fully de-spaghettify `KeymanWebDelegate` and its usages, though.

https://github.com/keymanapp/keyman/pull/1347/commits/3f2c59c09687630914bfd8549b9f4dd2a5a1c740 - a massive refactor that transforms the old system keyboard's base into a unified in-app/system keyboard object.
* Updates base iOS target version to 9.0.
  - according to https://everyi.com/by-capability/maximum-supported-ios-version-for-ipod-iphone-ipad.html, this shouldn't affect _any_ properly updated iOS device; if it was supported before, it'll still be supported by Keyman.
  - this decision simplifies constraint-based coding dramatically; the whole 'anchor' constraint scheme used by this commit was introduced in this version of iOS.
  - adds a couple of new warnings about a method deprecated after iOS 8 but by iOS 9.
* sets `InputViewController` as the owner and maintainer of the `KeymanWebViewController`.
  - That bit about a "merged, centralized keyboard container" before?  `InputViewController` can fulfill that role!
* is now also the _only_ `KeymanWebDelegate`, directly processing all text commands rather than relying on extra supporting code for TextViews and TextFields.
  - If desired, we may be able to fully strip out the entire 'delegate' abstraction now.
  - Since `InputViewController` is more generally usable, it can now be used via the `inputViewController` property for `TextView` and `TextField`.  
    - More research is required to see if it'll even work directly with the base UIKit versions.
* fully implements constraint-based sizing and layout for the in-app keyboard without issue
  - basically, gets the work from https://github.com/keymanapp/keyman/commit/034680d9f413dfbfa5457a2d9be062406e26eecf working on the refactored core keyboard object, and even better than before.
  - this does break the system keyboard, and even more so than before.  So, still WIP.

https://github.com/keymanapp/keyman/pull/1347/commits/b9eeab6a4e74315c74cbc59efb301c6cec6411a9
* Gets the system (app-extension) keyboard to display the actual keyboard again... for the first load only.
  - It's a very consistent pattern - apparently, the WebView needs to be reinitialized/reset each time the extension is reloaded, as it forgets the old page.
* Continued debugging of system keyboard constraint effects... something's really weird with how (system) keyboard extension constraints are handled when compared to in-app.
  - The work done here to ensure a consistent keyboard instance should help with... interpreting... the constraint violation logs that iOS provides.

https://github.com/keymanapp/keyman/pull/1347/commits/e4c6ec6463c84f8a3b2837ad0e5d2e2371ba4d11
* System keyboard is now operational!
  - Turns out that `InputViewController` wasn't actually making its 'base' view correctly, as it's supposed to set `inputView` rather than `view` and use a `UIInputView`.
  - With this change in place, smart placement of an additional constraint allows the resulting base-level system keyboard view did the rest.

### CODE REVIEW

File: ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift [hunk 1]
```diff
@@ -90,15 +120,19 @@ class KeymanWebViewController: UIViewController {
...
+  override func viewDidAppear(_ animated: Bool) {
+    fixLayout()
+  }
 }
 
 // MARK: - JavaScript functions
 extension KeymanWebViewController {
   func languageMenuPosition(_ completion: @escaping (CGRect) -> Void) {
-    webView.evaluateJavaScript("langMenuPos();") { result, _ in
+    webView!.evaluateJavaScript("langMenuPos();") { result, _ in
```
Comment (mcdurdin) [inline ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift]: Sometimes you use `webView!` and others you use `webView?`.  Is this intentional and if so it might be good to clarify why.

Comment (jahorton) [reply ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift]: That's a Swift thing - `webView!` asserts that it's not `nil`, while `webView?` has a built-in `nil` check before continuing with the rest of the line.

Comment (mcdurdin) [reply ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift]: Yep -- it's just not clear to me the reason why sometimes you assert and sometimes you go ahead with a nil check for each of those JS calls.

Comment (jahorton) [reply ios/engine/KMEI/KeymanEngine/Classes/KeymanWebViewController.swift]: OK.  There are two cases I see in that file, and they do have a particular reason - they're the `setOSKWidth`/`setOSKHeight` methods, right?  Those two lines actually _can_ be reached before `webView` is initialized, so they need the `nil` check.  It's also fine if the call doesn't go through, as a state variable is also set with the size information and can be passed along to the `webView` as part of its initialization, so it's not like the values are being lost.

Without other changes, setting those two checks to use `!` instead of `?` will actually crash the app.

**Comment by jahorton** [comment]
Yeah, the system keyboard isn't as consistent about reporting its rotation messages, so I did what I could to smooth it out.
