### PR TITLE
[iOS] Filters out prefixed LTR/RTL marks from context.

### LINKED ISSUE #1212: [iOS] nul and context can interact incorrectly at start of document with system keyboard
The following keyboard goes wrong in iOS when using the system keyboard, at and only at the start of a document. It does not go wrong in the Keyman app or on Android.

Both the `context` rule and the `nul` rule are relevant to the issue. Spider senses suggest that the `context` statement is the root cause but investigation needed.

This issue was reported at https://community.software.sil.org/t/ios-keyboard/1311

```
c Keystrokes:
c Q W E
c
c Expected result:
c 123
c 
c FAIL: In iOS system keyboard, QWE at start of document gives 1XXXX
c In iOS app, E at start of document gives XXXX, as expected
c In iOS app, QWE at start of document gives 123, as expected 
c Every other context in iOS appears to be fine
c Every context in web appears to be fine
c In Android app,  everything appears to be fine
c In Android system keyboard, everything appears to be fine

store(&VERSION) '10.0'
store(&TARGETS) 'any'
store(&NAME) 'nul and context bug'
store(&LAYOUTFILE) 'nul_context_ios_bug.keyman-touch-layout'
begin Unicode > use(main) 

c Main Program
group(main) using keys

+ [K_Q] > '1'
'1' + [K_W] > context '2'
+ [K_E] > '3'
nul + [K_E] > 'XXXX'
```

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #1212.

As it turns out, our own code has been adding Unicode LTR and RTL markers to our extended `TextField` and `TextView` class definitions as part of their `text` properties.  This marker was then copied into KMW and used as part of the context, which breaks `nul` and any `nul`-adjacent `context` statements in keyboard code.

To remedy this, we recognize that all text and caret communcation between apps (including Keyman) and the keyboard passes through `InputViewController`, which can filter out such prefixed codepoints so that they affect neither the context nor the caret position - the latter of which shows up more as an issue when testing with predictive text implementations.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/150920:id/kvk/index.html)

File: ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift [hunk 1]
```diff
@@ -237,6 +248,10 @@ open class InputViewController: UIInputViewController, KeymanWebDelegate {
         }
       }
     }
+    
+    self.swallowBackspaceTextChange = true
+    // afterDelay 0.01 is not sufficient!  0.02 seems to be enough for an actual delay to register.
+    perform(#selector(self.clearSwallowFlag), with: nil, afterDelay: 0.02)
```
Comment (jahorton) [inline ios/engine/KMEI/KeymanEngine/Classes/InputViewController.swift]: Yeah, this is ugly.  I don't see another way around the issue at present, though - we need the wait to ensure that `textDidChange` doesn't incorrectly wipe the embedded KMW's context due to desync.  There are no calls that occur later to allow us to consistently refresh the context after the fact.

We can't just ignore `textDidChange` because it's needed to detect legitimate changes of the context.  (Selections, caret movement, copy/paste, etc.)
