### PR TITLE
[Web] Keystroke control path rework

### LINKED ISSUE #237: Language-keyboard support on mobile devices using external keyboards not consistent
On mobile devices with the current alpha, many keyboards (like the default US, Lao Basic, Hebrew, and French keyboards) work perfectly with external keyboards on mobile devices.  However, some keyboards, such as the EuroLatin2 keyboard, do not accept keystrokes from external keyboards, despite receiving the KeyDown events.

The OSK still functions perfectly regardless; the issue is with the input coming from physical, external keyboards being used in browsers on mobile devices for 'native' KeymanWeb.

### LINKED ISSUE #311: Regression: modifier keys on physical keyboard switch layers on touch keyboard
In KeymanWeb 2.0.473, when using a physical keyboard in combination with the emulated Keyman touch keyboard (e.g. in the Chrome mobile emulator), the physical keyboard had no effect: keystrokes would generate no output. This was by design.

In alpha 10.0.15, keystrokes on the physical keyboard do have effects. This is not necessarily a bad thing in theory, but the keystrokes are not flowing through the correct 'desktop' pathways, meaning that keyboards have incorrect behaviours.

So, somewhere we have a regression in how physical keystrokes are processed in mobile emulation mode.

Ideal resolution:

1. Physical keystrokes are processed according to desktop semantics (including applying correct platform values) but touch keystrokes continue to use the touch pathway.
2. Modifier and State keys have no impact on the touch keyboard. *It is possible to make standard modifiers reflect on the touch keyboard, but the layout will not necessarily match the physical keyboard anyway so it's more confusing than not; plus there is no physical 'numeric' modifier key so it is a faulty paradigm anyway!)

----

Conversation here recorded for posterity:

marc [28 minutes ago] 
@jahorton I'm seeing some weird behaviour when simulating the touch keyboard now -- pressing modifier keys on the physical keyboard changes the layer for the touch keyboard, which it didn't used to.

I don't think it is directly related to the chirality PR, but the issue is present in alpha 10.0.15 and not in release 2.0.473.

In Chrome with mobile emulation on:
* keymanweb.com?tier=alpha shows the problem
* keymanweb.com shows the correct behaviour.

jahorton [21 minutes ago] 
Um... keymanweb.com doesn't exactly have the correct behavior for me.  It doesn't take _any_ physical key input.  I feel like this is something I corrected for in a relatively recent PR, so I may want to revisit that to ensure I didn't go too far with its changes.

jahorton [19 minutes ago] 
It can't be related to chirality if it's in the live alpha.  I wonder how it works with the new PR I put up, https://github.com/keymanapp/keyman/pull/310.

At the least, that PR is addressing a highly-related issue.
GitHub
[Web] Next layer processing fix by jahorton · Pull Request #310 · keymanapp/keyman
Addresses #116. Turns out that after #117's work toward #115, little extra work actually needed to be done to correct #116, though this took some time and investigation to determine.
 

jahorton [18 minutes ago] 
I almost broke the desktop OSK with my initial change, which I then had to unbreak with the last commit of that PR.  That 'extraneous statement' may be at fault for the present issue, but will be filtered to 'desktop'-only.

marc [11 minutes ago] 
The previous behaviour on desktop was that in emulation mode it would not accept any physical keystroke. There's some work we can do there but there's more to it than just accepting the keystrokes (c.f. Android hardware keyboard support).

jahorton [4 minutes ago] 
Android hardware keyboard support does some significant manipulation of the OSK that basically cuts the wires, if I remember correctly.  @darcywong00, you haven't seen the OSK visually respond to any physical keystrokes while working on chirality, right?

darcy [3 minutes ago] 
iirc, the OSK stays at the current layer, and the app inserts the correct character for your key combo

marc [2 minutes ago] 
Correct. That same string-cutting needs to be done -- i.e. platform should return as desktop not mobile/tablet and therefore desktop rules should fire (and osk manipulation should not take place). I don't think we try and solve that this afternoon because I'd like a bigger discussion before we do it

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #237 and fixes #311.

This PR aims to enhance the consistency of keystroke evaluation within KeymanWeb by permitting differentiation of hardware keystroke input from OSK-based input within the system.  The former will always follow the 'hardware desktop' rule set, while the latter's functionality is unchanged.  This also streamlines the connection between KMW and KMEA, eliminating the need for device aliasing when processing hardware keystrokes on Android devices.

As a result of this enhancement, we can now safely enable hardware-based input on touch-based devices and ensure that input is handled correctly for both input methods.  Additional work and refactoring was necessary to support keyboards that rely upon system-default behaviors, like EuroLatin2, which (in native mode) relies upon the browser to output base Latin characters instead of using rules to evaluate them.

Some initial work is included toward supporting caret manipulation and further command-type keystrokes to for better touch-alias emulation, but it is incomplete due to its inability to properly account for character clusters.  As such, it is disabled at this time.

### CODE REVIEW

File: web/source/keymanweb.js [hunk 1]
```diff
@@ -3183,14 +3193,27 @@ if(!window['keyman']['initialized']) {
...
+        var ch = osk.defaultKeyOutput('',Levent.Lcode,Levent.Lmodifiers,false,Levent.Ltarg);
+        if(ch) {
+          kbdInterface.output(0, Levent.Ltarg, ch);
+          return false;
+        }
+      }
       return true;
     }                
 
     keymanweb.callKeyboardStartGroup = function(Ltarg, Levent) {
```
Comment (mcdurdin) [inline web/source/keymanweb.js]: Can we document who calls this? Is there any reason why this is only called for hardware keyboard input processing? The name doesn't signify that...

File: web/source/keymanweb.js [hunk 2]
```diff
@@ -3312,51 +3342,52 @@ if(!window['keyman']['initialized']) {
...
-      {          
+      for(i=0; i<t.length; i++) {          
         if(t[i] == activeBase) break;
       }   
 
       // Find the next (or previous) element in the list
-      if(bBack) i=i-1; else i=i+1; 
-      if(i >= t.length) i=i-t.length;
-      if(i < 0) i=i+t.length;
+      if(bBack) {
```
Comment (mcdurdin) [inline web/source/keymanweb.js]: Can we ternarise this?
```
i=bBack ? i-1 : i+1;
```

File: web/source/keymanweb.js [hunk 3]
```diff
@@ -3312,51 +3342,52 @@ if(!window['keyman']['initialized']) {
...
-        
-        // Or reposition the caret on the input DIV if mapped
-        else  
-        {
+        } else { // Or reposition the caret on the input DIV if mapped
           keymanweb._ActiveElement=keymanweb._LastActiveElement=target;    
           keymanweb.setTextCaret(target,10000);                            
-          keymanweb.scrollInput(target);                                   
+          keymanweb.scrollInput(target);   // mousedown check
+          target.focus();
```
Comment (mcdurdin) [inline web/source/keymanweb.js]: This line here is new behaviour. I don't quite understand why it is needed?

File: web/source/kmwembedded.js [hunk 4]
```diff
@@ -450,7 +450,7 @@
       if(!keymanweb._ActiveKeyboard ||  Lkc.Lcode == 0) return false;
       
       // If key is mapped, return true
-      if(keymanweb._ActiveKeyboard['gs'](Lelem, Lkc)) return true;
+      if(keymanweb.processKeystroke(util.physicalDevice, Lelem, Lkc)) return true;
```
Comment (mcdurdin) [inline web/source/kmwembedded.js]: Should this be `util.physicalDevice` or `util.device`? These are popup key events so they are touch-based, right?

File: web/source/kmwosk.js [hunk 5]
```diff
@@ -787,6 +789,78 @@ if(!window['keyman']['initialized']) {
...
+                Lelem.base.disabled=false;
+                Lelem.base.form.submit();
+              } else {
+                keymanweb.moveToNext(false);
+              }
+            }
+            break;
+          case osk.keyCodes['K_SPACE']:
+            return ' ';
+            break;
```
Comment (mcdurdin) [inline web/source/kmwosk.js]: this line is not needed

File: web/source/keymanweb.js (hunk 3 above)
Comment (jahorton) [reply web/source/keymanweb.js]: Previously, switching between touch-based elements always happened with the OSK, which didn't need to intercept keystrokes.  It turns out that to properly support keystrokes, we needed `focus` to be called here to ensure things don't break upon use of the ENTER key within single-line controls, or if using the OSK to swap and then typing.

File: web/source/kmwembedded.js (hunk 4 above)
Comment (jahorton) [reply web/source/kmwembedded.js]: Good catch.  I was too caught up with all the 'physical' changes that I blanked out on that detail.

File: web/source/keymanweb.js [hunk 6]
```diff
@@ -3360,17 +3360,9 @@ if(!window['keyman']['initialized']) {
...
-      }
-      if(i >= t.length) {
-        i=i-t.length;
-      }
-      if(i < 0) {
-        i=i+t.length;
-      }
+      i = bBack ? i-1 : i+1;
+      // Treat the list as circular, wrapping the index if necessary.
+      i = i >= t.length ? i-t.length : (i < 0 ? i+t.length : i) ;
```
Comment (mcdurdin) [inline web/source/keymanweb.js]: Ha ha ... that's taking it further than I intended ... Okay, I guess although the double-ternary is a little more challenging to read!

Comment (jahorton) [reply web/source/keymanweb.js]: I figured it might, but it is annoying to see tons of tiny if-statements about too.  I figured I'd place that comment on the double-ternary just in case.

File: web/source/keymanweb.js (hunk 1 above)
Comment (jahorton) [reply web/source/keymanweb.js]: Ran a check with it; I think `callKeyboardStartGroup` was the original `processKeystroke` but was never utilized for OSK input for some reason.  Things seem pretty stable when merging the two methods.

I may run with `processKeystroke` as the name since it's less wordy and leave an internal comment about calling the start group.

File: web/source/keymanweb.js [hunk 7]
```diff
@@ -3206,16 +3191,35 @@ if(!window['keyman']['initialized']) {
...
 
-      // As this function should only be called for hardware keyboard input processing,
-      // this processes the keystroke through hardware-based rules.
-      return keymanweb.processKeystroke(util.physicalDevice, Ltarg, Levent);
+      util.activeDevice = device;
+
+      return keymanweb._ActiveKeyboard['gs'](element, keystroke);
     }
 
+    // keymanweb.callKeyboardStartGroup = function(Ltarg, Levent) {
```
Comment (mcdurdin) [inline web/source/keymanweb.js]: any reason why you've left this code there commented out?

File: web/source/keymanweb.js [hunk 8]
```diff
@@ -3206,16 +3191,35 @@ if(!window['keyman']['initialized']) {
...
+     */
+    keymanweb.processKeystroke = function(device, element, keystroke) {
       keymanweb._CachedSelectionStart = null; // I3319     
       keymanweb._DeadkeyResetMatched();       // I3318    
       keymanweb.cachedContext.reset();
 
-      // As this function should only be called for hardware keyboard input processing,
-      // this processes the keystroke through hardware-based rules.
-      return keymanweb.processKeystroke(util.physicalDevice, Ltarg, Levent);
+      util.activeDevice = device;
```
Comment (mcdurdin) [inline web/source/keymanweb.js]: `activeDevice` doesn't need to be reset after this function, correct?

File: web/source/keymanweb.js [hunk 9]
```diff
@@ -3206,16 +3191,35 @@ if(!window['keyman']['initialized']) {
...
+    /**
+     * Function     processKeystroke
+     * Scope        Private
+     * @param       {Object}        device      The device object properties to be utilized for this keystroke.
+     * @param       {Object}        element     The page element receiving input
+     * @param       {Object}        keystroke   The input keystroke (with its properties) to be mapped by the keyboard.
+     * Description  Encapsulates calls to keyboard input processing.
+     * @returns     {number}        0 if no match is made, otherwise 1.
+     */
+    keymanweb.processKeystroke = function(device, element, keystroke) {
```
Comment (mcdurdin) [inline web/source/keymanweb.js]: Given we are resetting cached selection, deadkey matches and cached context here, does that cause any issues with the new callers to the function? I'm not familiar enough with the old codepaths to be sure that the behaviour will be the same.

File: web/source/keymanweb.js (hunk 7 above)
Comment (jahorton) [reply web/source/keymanweb.js]: Because someone forgot to hit CTRL+S.  It's taken care of now.

File: web/source/keymanweb.js (hunk 8 above)
Comment (jahorton) [reply web/source/keymanweb.js]: Correct.  It'll always be set by the function call itself.

File: web/source/keymanweb.js (hunk 9 above)
Comment (jahorton) [reply web/source/keymanweb.js]: I tested with the French keyboard for deadkey matches.  As for cached context, that appears to be largely for dealing with `any`, `index`, and/or `context` statements.  It's simply cleaning house before rounds of processing.
