### PR TITLE
fix(web): fixes fat-finger distrib when subkey selected

### LINKED ISSUE #6573: bug(web): subkey fat-fingering regression
**Describe the bug**
A regression occurred during work on the OSK refactor leading to the "inlined" use case:  subkeys, when used, are not being passed along to the predictive text engine.  Only the base key and its neighboring keys are.

This is one of two KeymanWeb / predictive-text bugs arising from https://github.com/keymanapp/lexical-models/issues/143.

**To Reproduce**
1. Either use one of the Keyman mobile apps or the "robust" predictive text Web test page.
2. Set your active keyboard to `sil_euro_latin` - ensure the predictive text banner appears.
3. Type `we'` (as in `we're`)
4. See error - nothing even close to `we're` will appear as a suggestion.

Note:  this example is entangled with a second error (documented as #6572), so it's best verified by actually going into debug mode to watch related variables and data flow.

Unfortunately, this is, by far, the easiest example to conjure; any other examples (without `'`) using English-keyboard subkeys are generally not useful due to robustness provided by our default diacritic insensitivity (`searchTermToKey`) behaviors.

**Expected behavior**
When both this issue and #6572 are resolved, `we're` should generally appear as a suggestion when `we'` is typed.  It's a very natural continuation.

---

**KeymanWeb:**
 - OS: any
 - Browser: any (in touch mode)
 - KeymanWeb Version: 15.0 alpha - likely since around `15.0.83` or so.
 - URL: `web/testing/prediction-mtnt`

https://github.com/keymanapp/lexical-models/issues/143 did not indicate which version of KMW was used when the issue was noted; this issue was found during attempts to repro that bug.  Granted, the _other_ bug (#6572) likely affects older versions, too.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #6573.
This is but one part at play for https://github.com/keymanapp/lexical-models/issues/143.
(Re)based on #6574, as it is another part at play and its fix allows this PR to be directly user-testable.

Turns out I broke use of subkeys in the fat-finger distribution during the big OSK refactor work; this'll restore their presence.  Kinda helps when the LMLayer actually _knows_ there's a quotation mark there.

image

## User Testing

Use Chrome remote-device emulation with the standard `web/testing/prediction-mtnt` ("Predictive Text:  Robust Testing") test page.  (Alternatively, this should also be testable through the mobile apps if desired.)

- TEST_WE_ARE:  Using **`sil_euro_latin`** on the page (where `'` is a subkey of `.`), type the following.  

Access `sil_euro_latin` via the globe key; when using a web browser to test, you'll find it under "English...".

Make sure to be precise with your keystrokes.  If, at any point, no suggestions appear, **do not fail the test** - just start over from the first step.  There's another component of https://github.com/keymanapp/lexical-models/issues/143 that is likely interfering and may cause all predictions to be considered too unlikely for the engine to suggest.

1.  Type `we`:  standard suggestions should appear
2. Append a `'` by using its subkey under `.`:  suggestions should (still) be based on `we`.
    - Ideally, you may actually get a `we‘re` suggestion at this time, though this is quite rare in practice due to the following sub-points.
    - The suggestion containing `‘`, instead of `'`, is due to a model data issue documented at https://github.com/keymanapp/lexical-models/issues/143#issuecomment-1092410514
    - Because these characters do not match, the suggestion is considered possible, but very unlikely at this time. 
3. Append a `r` - you should at least still have `we` based suggestions and may have `we‘re` as a suggestion.

### CODE REVIEW

**Comment by bharanidharanj** [comment]
* **TEST_WE_ARE (PASSED):** Tested this in the Android (Version 11) API 30 emulator in Chrome browser and it is working as expected.

File: web/source/osk/visualKeyboard.ts [hunk 1]
```diff
@@ -400,10 +400,8 @@ namespace com.keyman.osk {
 
         // Note:  when embedded on Android (as of 14.0, at least), we don't get access to this.
         // Just the base key.
-        if (this.keyPending && this.keyPending.key) {
-          popupKeyMass = 3.0;
-          popupKeyID = this.keyPending.key.spec.coreID;
-        }
+        popupKeyMass = 3.0;
+        popupKeyID = subkey.coreID;
```
Comment (ermshiperete) [inline web/source/osk/visualKeyboard.ts:404]: Does this have to check that `subkey` has a value?

Comment (jahorton) [reply web/source/osk/visualKeyboard.ts:404]: Just checked to see how it actually functions; `subkey` actually _always_ has a value - and isn't always a subkey when the function starts.  It's simply the key-spec for whatever key the user selected.  That said, if we're finalizing a subkey gesture... it's a subkey.  So... the nomenclature could probably use a little work.

We could add a null guard on the block's condition though, just in case.

Comment (mcdurdin) [reply web/source/osk/visualKeyboard.ts:404]: > We could add a null guard on the block's condition though, just in case.

Good plan.

File: web/source/osk/visualKeyboard.ts [hunk 2]
```diff
@@ -400,10 +400,8 @@ namespace com.keyman.osk {
 
         // Note:  when embedded on Android (as of 14.0, at least), we don't get access to this.
         // Just the base key.
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:402]: Is this comment still accurate?

File: web/source/osk/visualKeyboard.ts [hunk 3]
```diff
@@ -361,7 +361,7 @@ namespace com.keyman.osk {
       return offsetCoords;
     }
 
-    getTouchProbabilities(input: InputEventCoordinate): text.KeyDistribution {
+    getTouchProbabilities(input: InputEventCoordinate, subkey?: keyboards.ActiveKey): text.KeyDistribution {
```
Comment (mcdurdin) [inline web/source/osk/visualKeyboard.ts:364]: Can you add a doc comment for this function?

**Review by mcdurdin — APPROVED** [review]

File: web/source/osk/visualKeyboard.ts (hunk 2 above)
Comment (jahorton) [reply web/source/osk/visualKeyboard.ts:402]: I think the comment is outdated now, after the gesture rework, but not in the way you'd expect.

Turns out, it's just not available directly at all now, hence the need for the newly-added parameter to the function.  Of course, that means it's no longer special to Android, so I'll rip the comment out.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.243-beta](https://keyman.com/downloads/releases/beta/15.0.243)
