### PR TITLE
Fix #145 - OSK fill from layout freezes, and tweak display of key preview in OSK editor at same time

### LINKED ISSUE #145: Fill in the OSK from the layout
fill from layout -not working

Not sure if this is just for me, but the 'fill from the layout' function keeps me waiting forever. Not sure if this is a 'bug'.

### PR DESCRIPTION
**Pull request by mcdurdin**

### CODE REVIEW

File: windows/src/developer/TIKE/dialogs/UfrmVisualKeyboardImportKMX.pas [hunk 1]
```diff
@@ -125,6 +127,12 @@ procedure TfrmVisualKeyboardImportKMX.FormShow(Sender: TObject);
  - Prepare for key processing                                                  -
  ------------------------------------------------------------------------------}
 
+procedure TfrmVisualKeyboardImportKMX.SetStatus(const msg: string);
+begin
+  lblStatus.Caption := msg;
```
Comment (darcywong00) [inline windows/src/developer/TIKE/dialogs/UfrmVisualKeyboardImportKMX.pas]: What's the character limit for `msg` that fits in a label of `Width = 205`?

File: windows/src/developer/TIKE/dialogs/UfrmVisualKeyboardImportKMX.pas [hunk 2]
```diff
@@ -240,16 +254,37 @@ procedure TfrmVisualKeyboardImportKMX.SendKey;
...
   AddInput(vk.vkey, False, False);
+
   if (vk.kmshift and KMX_ALTFLAG) = KMX_ALTFLAG then AddInput(VK_MENU, False, False);   // I4156
   if (vk.kmshift and KMX_CTRLFLAG) = KMX_CTRLFLAG then AddInput(VK_CONTROL, False, False);
+
+  if (vk.kmshift and KMX_LCTRLFLAG) = KMX_LCTRLFLAG then AddInput(VK_CONTROL, False, False);   // I4156
+  if (vk.kmshift and KMX_RCTRLFLAG) = KMX_RCTRLFLAG then AddInput(VK_CONTROL, False, True);
+  if (vk.kmshift and KMX_LALTFLAG) = KMX_LALTFLAG then AddInput(VK_MENU, False, False);   // I4156
   if (vk.kmshift and KMX_RALTFLAG) = KMX_RALTFLAG then AddInput(VK_MENU, False, True);
   if (vk.kmshift and KMX_SHIFTFLAG) = KMX_SHIFTFLAG then AddInput(VK_SHIFT, False, False);
```
Comment (darcywong00) [inline windows/src/developer/TIKE/dialogs/UfrmVisualKeyboardImportKMX.pas]: In case somebody else needs to maintain this block (lines 270-287), is there a specific order of operations they need to do these AddInputs?  I see it's currently LIFO.

File: windows/src/developer/TIKE/dialogs/UfrmVisualKeyboardImportKMX.pas (hunk 1 above)
Comment (mcdurdin) [inline windows/src/developer/TIKE/dialogs/UfrmVisualKeyboardImportKMX.pas]: It's a proportional font, so it depends. We don't really care, because it's just for feedback as the process runs. Longer messages will be cropped. Could be helpful for diagnostics in case we get another issue like the one that was the trigger this fix.

File: windows/src/developer/TIKE/dialogs/UfrmVisualKeyboardImportKMX.pas (hunk 2 above)
Comment (mcdurdin) [inline windows/src/developer/TIKE/dialogs/UfrmVisualKeyboardImportKMX.pas]: It's not particularly important but I like LIFO because keystroke operations feel like a stack (Press Ctrl, Press A, Release A, Release Ctrl is clearer to the end user). I try to do LIFO for all synthesized key events.

**Comment by mcdurdin** [comment]
Note: please ignore the second failed CI check because that will be resolved by #148.
