### PR TITLE
[Android][Web] Update FileUtils to handle mixed-case file extensions

### LINKED ISSUE #1332: [Android][Web] Handle mixed casing of filename extensions (e.g. .TTF)
Found investigating keymanapp/keyboards#515

Version 6.0 of the sil_cameroon_qwerty.kmp package uses a font with an upper-case name "ANDIKAAFR-R.TTF".
This fails all the font handling checks (e.g. `'filename.endsWith(".ttf")`) so the keyboard doesn't use it.

Need to audit all usages of `endsWith()`

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #1332 

Version 6.0 of sil_cameroon_qwerty keyboard uses a font file "ANDIKAAFR-R.TTF" and the Android app fails to apply it because the code is expecting files that `endsWith(.ttf)`.

### Android updates
* provide utility methods similar to KMEI [String+Helpers.swift](https://github.com/keymanapp/keyman/blob/master/ios/engine/KMEI/KeymanEngine/Classes/Extension/String%2BHelpers.swift) for handling file extensions.
* ~references to `.svg` and `.woff` files are removed since they're no longer needed~
* per review comment, retain support for `.svg` and `woff`
* one small section of KMW updated to handle .TTF files
* audit usage of `indexOf()`

### KMW Updates:
* update `kmwutils.ts` to handle mixed-casing of font files
* added associated test page

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java [hunk 1]
```diff
@@ -829,8 +829,7 @@ private String makeFontPaths(String font) {
         if (sourceArray != null) {
           for (int i = 0; i < sourceArray.length(); i++) {
             fontFile = sourceArray.getString(i);
-            if (fontFile.contains(".ttf") ||
-              (fontFile.contains(".svg") && (Build.VERSION.SDK_INT == Build.VERSION_CODES.JELLY_BEAN_MR1 || Build.VERSION.SDK_INT == Build.VERSION_CODES.JELLY_BEAN_MR2))) {
+            if (FileUtils.hasFontExtension(fontFile)) {
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java]: This removes support for .svg fonts. I think that's what we want but just checking.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java [hunk 2]
```diff
@@ -49,12 +49,12 @@ public static String getPackageID(File path) {
 
     if(filename.lastIndexOf('.') != -1) {
       // Android's temp downloads attach a suffix to the extension; .kmp isn't the end of the filename.
-      if(filename.lastIndexOf(".kmp") == -1) {
+      if(!filename.toLowerCase().contains(".kmp")) {
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/packages/PackageProcessor.java]: Shouldn't we be using `FileUtils` here too? `.contains(".kmp")` will return true for a name like "foo.kmp.blah.js"...

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java [hunk 3]
```diff
@@ -413,13 +408,8 @@ public static boolean isCustom(String u) {
       String fontSourceString;
       try {
         fontSourceString = jsonFont.getString(KMManager.KMKey_FontSource);
-        if (fontSourceString.endsWith(".ttf") || fontSourceString.endsWith(".otf")) {
-          urls.add(baseUri + fontSourceString);
-        } else if (isOskFont && (fontSourceString.endsWith(".svg") || fontSourceString.endsWith(".woff"))) {
+        if (FileUtils.hasFontExtension(fontSourceString)) {
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboardDownloaderActivity.java]: We've lost support for WOFF and SVG osk fonts with this change. That could break support for some older packages on some older Android devices.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java [hunk 4]
```diff
@@ -202,4 +209,25 @@ public static String getFilename(String urlStr) {
...
+  }
+
+  public static boolean hasKeyboardPackageExtension(String filename) {
+    String f = filename.toLowerCase();
+    return f.endsWith(KEYBOARDPACKAGE);
+  }
+
+  public static boolean isWelcomeFile(String filename) {
+    String f = filename.toLowerCase();
+    return f.endsWith(WELCOME_HTM);
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java]: Technically, this will match `/foo/bar/zap-welcome.htm`...

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java (hunk 1 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java]: I've reverted .svg support for those versions of SDK.

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java [hunk 5]
```diff
@@ -210,9 +216,22 @@ public static String getFilename(String urlStr) {
     return filename;
   }
 
+  /**
+   * Utility if a given file is a font. We prefer TTF or OTF, but old Android devices use SVG or WOFF.
+   * Limitations: Include SVG only for Build.VERSION.SDK_INT == JELLY_BEAN_MR1 or JELLY_BEAN_MR2 for OSK
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/FileUtils.java]: I don't think we should limit this on the OS version. SVG fonts continue to work so an older package will work on a newer device, if we let it...
