### PR TITLE
fix(ios): Cleans up 12.0 file management, non-adhoc kmp install

### LINKED ISSUE #2482: [iOS] Installation artifacts from prior versions pollute Documents directory
**Describe the bug**
With the introduction of the file manager (for "Install from file") from #2457, Keyman for iOS now exposes the app's "Documents" directory, which we haven't been managing well to this point.

As noted in that PR, regarding the app's "Documents" directory:
>    Going forward, we'll keep this properly clean...
>    But there's the matter of cleaning up old installation artifacts, now that we're making that directory public.

**To Reproduce**
1. Install an older version of the Keyman app (say, stable-12.0)
2. Ad-hoc install **_any_** Keyman resource.
3. Install the current version of the Keyman app
4. Open up the file browser - you should see miscellaneous junk data in the Documents directory.

**Expected behavior**
Since the Documents directory has random junk in it from prior versions, I'd expect the app to purge the Documents directory when updating from 12.0 to 13.0.  The directory only held temporary install data before; useful .kmp backups only began to be stored here in 13.0 (as of #2460, a prerequisite of #2457).

**Screenshots**

While some installs with updated ad-hoc installation code have occurred (resulting in the plain .kmp file backups), note the 'temp' folder in the screenshot below.

Screen Shot 2020-01-10 at 8 55 49 AM

That folder is an artifact from resource installation as performed in prior versions of Keyman for iOS.  For example, within that directory, we can see the following:

Screen Shot 2020-01-10 at 8 57 15 AM

This is the temporary extraction that was used to install the MTNT model using processes that predate #2460.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #2482.  This thus completes the feature introduced by #2457.

Fixes file organization issues found in 12.0 and before that became exposed in 13.0 with the new file browser feature with a "migration" call triggered upon first load after the app updates to 13.0+.

This was somewhat complicated by the fact that cloud-based KMP installs (for lexical models) were still using old install paths.  As a result, cloud-based KMP installs now use common install code introduced by #2460 for adhoc installation.

### CODE REVIEW

File: ios/engine/KMEI/KeymanEngine/Classes/Migrations.swift [hunk 1]
```diff
@@ -393,4 +418,34 @@ enum Migrations {
...
+    try contents.forEach { fileURL in
+      // 12.0: extracts .kmp files by first putting them in Documents and giving
+      // them this suffix.
+      if fileURL.lastPathComponent.hasSuffix(".kmp.zip") {
+        // Renames the .kmp.zip files back to their original .kmp filename.
+        let destFile = fileURL.lastPathComponent.replacingOccurrences(of: ".kmp.zip", with: ".kmp")
+        let destURL = fileURL.deletingLastPathComponent().appendingPathComponent(destFile)
+
+        log.debug("\(fileURL) -> \(destURL)")
+        try FileManager.default.moveItem(at: fileURL, to: destURL)
```
Comment (mcdurdin) [inline ios/engine/KMEI/KeymanEngine/Classes/Migrations.swift]: What happens if there is a `foo.kmp.zip` and a `foo.kmp` in the folder?

Comment (jahorton) [reply ios/engine/KMEI/KeymanEngine/Classes/Migrations.swift]: Because of how KMP installation worked in previous versions of the app, this state should be impossible.  We never stored raw .kmps in that folder.

If, somehow, one _does_ exist, the attempt to move the item will likely fall over with an error and abort the file-relocation process, which would then result in an error message, but not an app crash.  (See line 95 for the `catch` block that handles this scenario.)
