### PR TITLE
[Windows] AltGr causes sticky Left Control when some Windows European layouts are installed.

### LINKED ISSUE #1620: [Windows] Pressing RAlt can cause LCtrl to stick when a European layout is installed (regression)
**Describe the bug**

If Keyman Desktop is running, and a European layout which uses AltGr (Right Alt) is active, or a Keyman layout is active (in most cases), then pressing RAlt+key causes the LCtrl key to become stuck, until the user presses and releases LCtrl.

This is a regression relating to the rework of the input queue in Keyman Engine, because Windows internally emits a LCtrl-down when the user presses RAlt, but Keyman Engine is not detecting it when re-emitting the key events, and so not emitting a corresponding LCtrl-up when it needs to.

However, this occurs only when a keyboard layout is installed that triggers Windows' special handling of AltGr. For keyboard layouts such as English (US) which do not have AltGr handling, this problem never arises.

**To Reproduce**
1. Install Windows French keyboard
2. Start Notepad
3. Ensure Keyman is running, and select the Windows French keyboard
4. Press French [A][Z][E][R][T][Y], [AltGr]+[E] and see a "azerty€" sign appear in the document.
5. Press French [A] ([Q] on US).

**Expected behavior**
After step 5 above, the letter 'a' should appear in the document, but instead the whole document is selected (default Ctrl+A action).

---

**Keyman Desktop:**
 - OS: Windows 7, 8.1, 10
 - Keyman version: 11.0.1312.0
 - Target Application: Any

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #1620.

When Windows has a European layout that uses AltGr installed, it can emit an additional LCtrl down via software when RAlt is pressed. However, the corresponding LCtrl up is never received, seemingly because when Keyman re-emits the LCtrl+RAlt, there are subtle differences in the event flags which we cannot duplicate -- specifically the flag that emits WM_SYSKEYDOWN for the VK_LCONTROL, even though it is received before the VK_RALT event. It appears that Windows figures this out by giving this VK_LCONTROL the scan code 0x21D instead of 0x1D. But we are unable to emit that scan code: Windows truncates the scan code sent through SendInput so that we can only send 0x1D.

So we simulate the release of the Left Control key ourselves when the release of the Right Alt is received, using VK_CONTROL and scan 0x1D, and hope for the best.

The full Windows sequence is:

            WM_SYSKEYDOWN VK_CONTROL 0x21D
            WM_SYSKEYDOWN VK_MENU 0x38 EXTENDED_BIT
            ...
            WM_KEYUP VK_CONTROL 0x21D
            WM_KEYUP VK_MENU 0x38 EXTENDED_BIT

The best Keyman can do is:

            WM_KEYDOWN VK_CONTROL 0x1D
            WM_KEYDOWN VK_MENU 0x38 EXTENDED_BIT
            ...
            WM_KEYUP VK_CONTROL 0x1D
            WM_KEYUP VK_MENU 0x38 EXTENDED_BIT

There is a possibility that some apps may try and sniff that 0x21D scan code and get confused because Keyman doesn't emit it. Hopefully this is rare.

### CODE REVIEW

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/142383:id/kvk/index.html)

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/142391:id/kvk/index.html)

File: windows/src/engine/keyman32/serialkeyeventserver.cpp [hunk 1]
```diff
@@ -415,23 +415,90 @@ class SerialKeyEventServer: public ISerialKeyEventServer {
...
+          (BYTE)input[1].ki.wVk,
+          input[1].ki.dwFlags & KEYEVENTF_EXTENDEDKEY ? TRUE : FALSE,
+          (BYTE)input[1].ki.wScan,
+          input[1].ki.dwFlags & KEYEVENTF_KEYUP ? TRUE : FALSE);
+      }
+      else {
+        INPUT input;
+        input.type = INPUT_KEYBOARD;
+        input.ki.wVk = (WORD)wParam;
+        input.ki.wScan = (lParam & 0xFFF0000) >> 16;
```
Comment (darcywong00) [inline windows/src/engine/keyman32/serialkeyeventserver.cpp]: Why did this change from `0xFF0000`?

Comment (mcdurdin) [reply windows/src/engine/keyman32/serialkeyeventserver.cpp]: Because in theory at least, we have a scancode 0x21D which we pass through to SendInput. Sadly, SendInput truncates it to 8 bits, but ... we pass it through :)
