### PR TITLE
fix(web): prevents dropping of input during rapid multitouch typing

### LINKED ISSUE #11221: bug(web): dropped chars and unintended upflicks with 17.0.307-beta
Regression from 17.0.301-beta.

Video on drive: https://drive.google.com/file/d/1AWCRAX1eT6Ql9TRycP2c3U36k5LbTqOY/view?usp=drivesdk

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #11221.

Turns out that there was a flag missing on the longpress model; if a second touch started during the longpress timer, it cancelled _both_ the longpress _and_ the new touch as a result, rather than just the longpress.  Fortunately, it's a quite simple fix.

## User Testing

TEST_RAPID_TYPE_WORDS:  Using the Keyman app on an Android device, attempt to reproduce #11221 with normal typing patterns - type rapidly and ensure no keys are unexpectedly dropped.
- Try typing `the quick brown fox jumped over the lazy dog` as fast as possible.  Don't worry about accuracy (aside from avoiding the globe key).
- Feel free to try additional sentences and/or paragraphs.
- Be sure you can compare the results with what you meant to type, so no random keymash.

TEST_RAPID_TYPE_HOME_ROW:  Using the Keyman app on an Android device, attempt to reproduce #11221 using the identified reproduction in [this comment](https://github.com/keymanapp/keyman/issues/11221#issuecomment-2062924021).

TEST_STICKY_BACKSPACE:  Using the Keyman app on an Android device, attempt to reproduce #11223.  The reporting user provided a repro.

Note:  I've added the last test, regarding backspace, because I _suspect_ the underlying issue is the same, with this PR _likely_ fixing it... but I'm willing to be wrong.  I won't block a merge of this PR should only that one user-test fail.

### CODE REVIEW

File: web/src/engine/osk/src/input/gestures/specsForLayout.ts [hunk 1]
```diff
@@ -643,7 +643,8 @@ export function longpressModel(params: GestureParams, allowShortcut: boolean, al
         },
         endOnResolve: false
       }, {
-        model: instantContactRejectionModel()
+        model: instantContactRejectionModel(),
+        resetOnInstantFulfill: true
```
Comment (jahorton) [inline web/src/engine/osk/src/input/gestures/specsForLayout.ts:647]: The actual fix, on the 'longpress' model.  It didn't reset the match-state of any auto-cancelling touches.

File: common/web/gesture-recognizer/src/engine/headless/gestures/specs/gestureModel.ts [hunk 2]
```diff
@@ -116,7 +116,7 @@ export interface GestureModel<Type, StateToken = any> {
      * Only takes effect if a model instantly resolves or rejects upon being considered for
      * inclusion in the model.
      */
-    resetOnResolve?: boolean,
+    resetOnInstantFulfill?: boolean,
```
Comment (jahorton) [inline common/web/gesture-recognizer/src/engine/headless/gestures/specs/gestureModel.ts:119]: I decided to go ahead and rename it because we're also resetting on rejection - and that's the case we're using for the longpress model to fix the underlying issue.

File: web/src/engine/osk/src/input/gestures/browser/flick.ts [hunk 3]
```diff
@@ -118,7 +118,7 @@ export default class Flick implements GestureHandler {
     let source: GestureSource<KeyElement> = baseSource;
 
     sequence.on('complete', () => {
-      previewHost.cancel()
+      previewHost?.cancel()
```
Comment (jahorton) [inline web/src/engine/osk/src/input/gestures/browser/flick.ts:121]: Threw it in since I saw a null-ref error once while testing.

Comment (mcdurdin) [reply web/src/engine/osk/src/input/gestures/browser/flick.ts:121]: Are there any reports on Sentry we can link?

**Review by mcdurdin — APPROVED** [review]
LGTM, makes sense! Looking forward to testing this one soon

File: web/src/engine/osk/src/input/gestures/browser/flick.ts (hunk 3 above)
Comment (jahorton) [reply web/src/engine/osk/src/input/gestures/browser/flick.ts:121]: My local build that was in place when the error occurred does not appear to have sent a Sentry log, unfortunately.

Comment (mcdurdin) [reply web/src/engine/osk/src/input/gestures/browser/flick.ts:121]: And no other reports from other people... a little surprising!

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_RAPID_TYPE_WORDS (PASSED):** Tested with the attached PR build (Keyman 17.0.310-beta-test-11245) on an Android 13 (Samsung Galaxy A23 5 G) Mobile device and here is my observation : 1. Opened the Keyman In-App. 2. Started typing the sentence 'the quick brown fox jumped over the lazy dog' repeatedly as fast as possible. 3. Also, added some additional paragraphs by rapidly typing. 4. Verified that the keys did not stuck at any point during the process. 5. Tried with Quechua- Kreative SuperLatin keyboard and verified that it did not produce any error. Seems to be working fine.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_RAPID_TYPE_WORDS (OPEN):** Tested with the attached PR build (Keyman 17.0.310-beta-test-11245) on an Android 13 (Samsung Galaxy A23 5 G) Mobile device and here is my observation : 1. Followed the steps as mentioned by Josh in issue 11221 in the Keyman In-app. 2. Able to see the expected result 'alskdjfhg' while rapidly typing it using the OSK. Seems to be working as expected.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_RAPID_TYPE_WORDS (PASSED):** notes

**Comment by bharanidharanj** [comment]
@jahorton Could you please rename the second test run since the test bot did not accept the results I posted for it?

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.310-beta](https://keyman.com/downloads/releases/beta/17.0.310)

File: web/src/engine/osk/src/input/gestures/browser/flick.ts (hunk 3 above)
Comment (jahorton) [reply web/src/engine/osk/src/input/gestures/browser/flick.ts:121]: Aha!  We _do_ have one now:

https://keyman.sentry.io/share/issue/9d0e6b45e99a4afab5b4425e603c35e4/ (it was under Developer)
