### PR TITLE
fix(android/app): Fix crash when clicking QR code

### LINKED ISSUE #4269: bug(android/engine): Null pointer exception on HashMap.getOrDefault()
Generated from Play Store 14.0 pre-release launch report

On 14.0.222 beta
Android 5.0 (API 21)

```
FATAL EXCEPTION: Thread-2
Process: com.tavultesoft.kmapro, PID: 12383
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.getOrDefault(java.lang.Object, java.lang.Object)' on a null object reference
	at com.tavultesoft.kmea.util.MapCompat.getOrDefault(MapCompat.java:17)
	at com.tavultesoft.kmapro.KeyboardSettingsActivity$2.onItemClick(KeyboardSettingsActivity.java:166)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1158)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3153)
	at android.widget.AbsListView$3.run(AbsListView.java:4068)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:11)
	at androidx.test.espresso.base.UiControllerImpl.n(UiControllerImpl.java:6)
	at androidx.test.espresso.base.UiControllerImpl.m(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.e(UiControllerImpl.java:8)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:4)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
	at androidx.test.espresso.ViewInteraction.a(Unknown Source:137)
	at androidx.test.espresso.ViewInteraction$1.call(Unknown Source:4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6647)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #4269 

After some spelunking in the Sentry crash reports, this PR fixes the following:

* ~Disable Sentry on unit tests~
* Throw NullPointerException if null HashMap passed to MapCompat
* Ignore null HashMap when clicking on QR code (KeyboardSettingsActivity). Note, the QR code is also displayed in KeyboardInfoActivity, but that doesn't involve a null HashMap.

### User Testing
1. Load app
2. From the "Settings" menu, install "Tohono O'odham" keyboard (from the linked Sentry report)
3. After keyboard installs, go Settings --> Installed Languages --> Tohono O'odham (Latin) --> Tohono O'odham --> settings menu
4. Click on the QR code and verify nothing happens

### CODE REVIEW

**Comment by mcdurdin** [comment]
> * Disable Sentry on unit tests

Why disable Sentry on unit tests? Doesn't it give us more detail on call stacks, etc, if we get an error?

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/MapCompat.java [hunk 1]
```diff
@@ -13,6 +13,10 @@
   private static final String TAG = "MapCompat";
 
   public static <K, V> V getOrDefault(HashMap<K, V> map, K key, V defaultValue) {
+    if (map == null) {
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/MapCompat.java:16]: I'd prefer this to still throw on `null`. It's invalid input.

If we want to do anything about that, the parent function `com.tavultesoft.kmapro.KeyboardSettingsActivity$2.onItemClick` already has a test for `hashMap == null` and logs that. Just return from that test after L152:

https://github.com/keymanapp/keyman/blob/493bb945b61f0ed0a625a45dd4e8041dcc7e047c/android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeyboardSettingsActivity.java#L150-L153

**Review by mcdurdin — CHANGES_REQUESTED** [review]

**Comment by darcywong00** [comment]
> Why disable Sentry on unit tests? Doesn't it give us more detail on call stacks, etc, if we get an error?

Ah, mis-remembered the details on #4581 disabling Sentry for dev environments (I was thinking when running tests).

I just wasn't sure we wanted to send Sentry errors with every build (tests get run every time)

**Comment by mcdurdin** [comment]
> I just wasn't sure we wanted to send Sentry errors with every build (tests get run every time)

An additional event is no big deal to receive and it really helps if we know exactly which build stops generating the errors too :grin:

File: android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/MapCompat.java (hunk 1 above)
Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/MapCompat.java:25]: We don't actually need this test at all, just let it bork as it was previously!

**Review by mcdurdin — APPROVED** [review]
LGTM but I don't think we need the additional test in `MapCompat`.

Good spelunking 👍

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.260-beta](https://keyman.com/downloads/releases/beta/14.0.260)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.20-alpha](https://keyman.com/downloads/releases/alpha/15.0.20)
