### PR TITLE
fix(windows): sentry.dll version handling

### LINKED ISSUE #5166: bug(windows): sentry integration not backwardly compatible causing crashes on start
**Describe the bug**

sentry.dll 0.4.9 is not backwardly compatible with sentry.dll 0.2.3. This means that attempts by older clients to use the newer DLL will typically crash in nasty ways. (Note: DLLs are intended to have stable exported interfaces!)

As we currently host sentry.dll in Keyman Engine rather than giving each app its own version of it, this stops us installing 
different versions of Keyman Developer and Keyman for Windows, or 3rd party apps.

My intended solution is twofold:

1. Include the 0.2.3 versions of `sentry.dll` and `sentry.x64.dll` in perpetuity in Keyman Engine. This avoids issues with older versions of an app being broken when a newer version of another app is installed.
2. Rename `sentry.dll` to `sentry.0.4.9.dll` (and `sentry.0.4.9.x64.dll`) and bundle it with each app that uses Sentry.

Each process will look for `sentry.<version>.dll` *only* in the folder where its executable is (apart from in development scenarios), to avoid accidentally loading an older version. This means including sentry.dll three times for each app (for a total of 6 dlls):

1. Because Keyman Engine, Keyman for Windows and Keyman Develper all use it and we can't rely on Keyman Engine having the same version as Keyman for Windows (we can only rely on Keyman Engine being the same version or newer).
2. Because we want to be able to update it again in the future: if each app has its own copy, this is safe.
3. And of course, including the old v2.3 sentry.dll in Keyman Engine forever.

This also means that alpha 15.0.53 and onwards until this fix lands will be broken because their versions of sentry.dll are stomping on the 2.3 dll. We'll just write off those alpha releases, though, so not the end of the world.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 
 - Keyman version: 15.0

### LINKED ISSUE #5188: bug(windows): sentry-db is not backwardly compatible
**Describe the bug**

If you install a version of Keyman which has an older version of sentry, sentry will tend to crash on startup as its sentry-db folder is not backwardly compatible.

**To Reproduce**

1. Install Keyman 15.0.53 and run any program once.
2. Uninstall v15 and reinstall v14.
3. Start any program and observe a crash, in this case:

    ```
    (2b08.68cc): Unknown exception - code c0000090 (first chance)
    (2b08.68cc): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
    ```

**Suggested resolution**
Rename the sentry-db folder for each version of sentry.
Optionally on startup, delete old sentry-db folders (but ignore failure to delete)?

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 
 - Keyman version: 15.0

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #5166.
Fixes #5188.

This introduces versioned management of sentry.dll for Keyman for Windows, Keyman Engine and Keyman Developer. As sentry.dll's ABI is not backwardly compatible, we have to maintain independent copies of each DLL for each app.

sentry.dll (or sentry.x64.dll for x64 apps) will be found in the sentry-0.4.9 folder relative to the running process, except when running from within the keyman repo tree (based on presence of KEYMAN_ROOT env var). In those cases, the windows/src/ext/sentry sentry.dll will be used, allowing us to test new debug time sentry DLLs easily.

A little bit of cleanup and consolidation was also done in the KeymanPaths.pas unit.

### CODE REVIEW

File: windows/src/.gitignore [hunk 1]
```diff
@@ -1,5 +1,6 @@
 **/*.aps
 **/BuildLog.htm
+**/*.recipe
```
Comment (mcdurdin) [inline windows/src/.gitignore:3]: This is another file generated by VS2019.

File: windows/src/buildtools/cef-checkout.sh [hunk 2]
```diff
@@ -26,6 +26,8 @@ CEF_VERSION=`cat $CEF_VERSION_MD | tr -d "[:space:]"`
 # Note that 14.0 and earlier versions rely on the `master`
 # branch, so that is the default branch checked out in the
 # build configurations
+git reset --hard
+git clean -fd
```
Comment (mcdurdin) [inline windows/src/buildtools/cef-checkout.sh:30]: I'm a little leery of this; it might be better to check if we are on the right branch already and avoid this kind of shenanigans.

File: windows/src/developer/inst/kmdev.wxs [hunk 3]
```diff
@@ -167,7 +168,7 @@
       </Component>
 
       <Component>
-        <File Name="kmbrowserhost" KeyPath="yes" Source="..\..\..\bin\desktop\kmbrowserhost.exe" />
+        <File Name="kmbrowserhost.exe" KeyPath="yes" Source="..\..\..\bin\desktop\kmbrowserhost.exe" />
```
Comment (mcdurdin) [inline windows/src/developer/inst/kmdev.wxs:171]: This was a bit of an oopsie. Belongs in a separate PR really

File: windows/src/developer/kmanalyze/kmanalyze.vcxproj [hunk 4]
```diff
@@ -119,7 +120,8 @@
     <Link>
       <SubSystem>Console</SubSystem>
       <GenerateDebugInformation>true</GenerateDebugInformation>
-      <AdditionalDependencies>..\..\ext\sentry\sentry.lib;kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;odbccp32.lib;%(AdditionalDependencies)</AdditionalDependencies>
+      <AdditionalDependencies>..\..\ext\sentry\sentry.x64.lib;kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;odbccp32.lib;%(AdditionalDependencies)</AdditionalDependencies>
```
Comment (darcywong00) [inline windows/src/developer/kmanalyze/kmanalyze.vcxproj:123]: Is it only sentry.dll that needs to be versioned, and not sentry.(x64).lib?

File: windows/src/ext/sentry/test/Sentry.Client.Test.SentryClientTestMain.pas [hunk 5]
```diff
@@ -29,7 +29,7 @@ function Init: TSentryClient;
   //o.DSN := 'https://7b1ff1dae2c8495b84f90dadcf512b84@sentry.io/4853461';
   o.Release := 'keyman-14.0.22-alpha-local';
   o.HandlerPath := 'c:\Projects\keyman\app\windows\src\ext\sentry\test\Win32\Release\crashpad_handler.exe';
```
Comment (darcywong00) [inline windows/src/ext/sentry/test/Sentry.Client.Test.SentryClientTestMain.pas:31]: Should this be a relative path to `ext\sentry\2.3\crashpad_handler.exe`?

File: windows/src/developer/kmanalyze/kmanalyze.vcxproj (hunk 4 above)
Comment (mcdurdin) [reply windows/src/developer/kmanalyze/kmanalyze.vcxproj:123]: Yes. The .lib is statically linked so not distributed as is.

File: windows/src/ext/sentry/test/Sentry.Client.Test.SentryClientTestMain.pas (hunk 5 above)
Comment (mcdurdin) [reply windows/src/ext/sentry/test/Sentry.Client.Test.SentryClientTestMain.pas:31]: No, this is a test unit only, not required for distribution.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.60-alpha](https://keyman.com/downloads/releases/alpha/15.0.60)
