### PR TITLE
fix(web): no key previews for special keys reliant on keyboard-specific OSK font

### LINKED ISSUE #3443: Key Type "Special" non-latin text
**Describe the bug**
Key Type "Special" non-latin text such as \*೧೨೩\*, will display * until \*123\*. If ೧೨೩ is used without *'s. then these keys popup.

**To Reproduce**
Change the text from \*123\* to \*೧೨೩\* Key Type "Special" in default layer of latin_euro_sil keyboard. and ೧೨೩ in place of *123* in shift layer.

1. Both will make the keys popup, unlike with it is \*123\*.
2. When it is \*೧೨೩\*, it doesn't hide *'s. Although I don't the reason for it.

**Expected behavior**
If the keyboards are to be localized in all languages, we need special keys to accept non-latin and must not popup.

### LINKED ISSUE #3513: First letter in popup key is small
**Describe the bug**
First letter in popup key is small

**To Reproduce**
Push any popup key is small

**Expected behavior**
Same size for all keys

**Screenshots**
IMG_5939
IMG_5940
IMG_5941
IMG_5942
IMG_5943

---

**iPhone/iPad/Android:**
 - Device: [e.g. iPhone 11 Pro Max]
 - OS: [e.g. iOS 13.6.1]
 - Keyman version [e.g. 14.0.133]
 - Target application: Notes

---
 
**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.9.1
 - Language name: English

### PR DESCRIPTION
**Pull request by jahorton**
Pretty much what the title says.

Fixes #3443.

A good, already-released test keyboard for this is `khmer_angkor`; it uses custom keycaps for the numeric layer and another special layer.

### CODE REVIEW

File: web/source/osk/visualKeyboard.ts [hunk 1]
```diff
@@ -1710,10 +1710,12 @@ namespace com.keyman.osk {
...
-        var excludedClasses = ['kmw-key-shift',    // special keys
-                               'kmw-key-shift-on', // active special keys (shift, when in shift layer
-                               'kmw-spacebar',     // space
-                               'kmw-key-blank',    // Keys that are only used for layout control
+        var excludedClasses = ['kmw-key-shift',      // special keys
+                               'kmw-key-shift-on',   // active special keys (shift, when in shift layer
+                               'kmw-key-special',    // special keys that require the keyboard's OSK font
+                               'kmw-key-special-on', // active special keys requiring the keyboard's OSK font
+                               'kmw-spacebar',       // space
+                               'kmw-key-blank',      // Keys that are only used for layout control
```
Comment (jahorton) [inline web/source/osk/visualKeyboard.ts:1718]: For comparison:  https://github.com/keymanapp/keyman/blob/cb98febc206c7e2d83030bb8b4890d58534cc7e1/common/core/web/keyboard-processor/src/keyboards/activeLayout.ts#L157-L171

So, the end-user difference in 'special' vs 'shift' is meant to come down to font control.  Unfortunately, this detail was ignored by the actual key preview logic.

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.225-beta](https://keyman.com/downloads/releases/beta/14.0.225)
