### PR TITLE
fix(web): Have util.wait check useAlerts option

### LINKED ISSUE #5455: fix(web): Should we check useAlerts for util.wait?
#5302 added a KeymanWeb options flag `useAlerts` to control internal alerts.

Should it also apply to util.wait?

https://github.com/keymanapp/keyman/blob/1778fa27d414ba6410133809e3a97abb229ffd0a/web/source/kmwnative.ts#L38-L70

### PR DESCRIPTION
**Pull request by darcywong00**
#5302 added an option useAlerts that controlled whether internal alerts are displayed.
This fixes #5455 by having util.wait also check the option.

* Also added a test page to display util.wait and then dismiss

### CODE REVIEW

File: web/source/kmwnative.ts [hunk 1]
```diff
@@ -53,7 +53,7 @@ if(!window['keyman']['initialized']) {
       if(s) {
         bg.pending=true;
         window.setTimeout(function() {
-            if(bg.pending) {
+            if(bg.pending && keymanweb.options.useAlerts) {
```
Comment (jahorton) [inline web/source/kmwnative.ts:56]: Would prefer for this check to be on `wait` calls... but upon investigation... it appears that `wait` is actually internal only; we never actually documented it as API.  Huh.

So... maybe it's fine not to do the checks in the same way we did for `alert`, which is published API?

Comment (jahorton) [reply web/source/kmwnative.ts:56]: Thoughts, @mcdurdin?  An initial impression based on the comment above is fine.

Comment (mcdurdin) [reply web/source/kmwnative.ts:56]: LGTM

**Review by jahorton — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.94-alpha](https://keyman.com/downloads/releases/alpha/15.0.94)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.98-alpha](https://keyman.com/downloads/releases/alpha/15.0.98)
