### PR TITLE
fix(windows): Keyman was not working with Skype

### LINKED ISSUE #1680: [Windows] Keyman does not work with Skype, Windows Search or other Windows Store apps
**Describe the bug**
In some circumstances, it seems that Keyman fails to apply the ALL APPLICATION PACKAGES permission to HKCU\Software\Keyman. In the situation that I observed, the Read permission appeared to be set correctly for that key, but not for any subkeys.

When this issue arises, Keyman does not work in any Windows Store apps, such as Skype, or Window Search.

This happened on an apparently clean install of Windows 10 1803.

**Symptoms**

1. Start Registry Editor, navigate to HKCU\Software\Keyman.
2. Right-click, select Permissions. You should see "ALL APPLICATION PACKAGES" has Read permission.
3. Right-click on HKCU\Software\Keyman\Keyman Engine, select Permissions. "ALL APPLICATION PACKAGES" is missing.

**Workaround**

Note: please see [test app below](https://github.com/keymanapp/keyman/issues/1680#issuecomment-548511867) as a preferred option.

**Manual Workaround**
1. Start Registry Editor, navigate to HKCU\Software\Keyman\Keyman Engine.
2. Right-click, select Permissions.
3. Add permission "ALL APPLICATION PACKAGES", Read.
4. Apply, restart Keyman, relevant apps, etc etc.

---

**Keyman Desktop:**
 - OS: Windows 10 1803
 - Keyman version: 11.0.1352.0

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #1680. This issue arose only on some systems where
permissions for Keyman registry keys were not being
set correctly.

### CODE REVIEW

File: windows/src/engine/keyman/main.pas [hunk 1]
```diff
@@ -181,6 +181,10 @@ procedure InitialiseRegistrySecurity;
     if r.OpenKey(SRegKey_KeymanRoot_CU, True) then
```
Comment (darcywong00) [inline windows/src/engine/keyman/main.pas]: Would this be the same?
```
if r.OpenKey(SRegKey_KeymanRoot_CU, True) or r.OpenKey('\' + SRegKey_KeymanEngineRoot_CU, True) then
```

Comment (mcdurdin) [reply windows/src/engine/keyman/main.pas]: No, because I am applying the permission to each key in turn. That change would only allow the permission to be applied to the `SRegKey_KeymanEngineRoot_CU` key.

**Comment by mcdurdin** [comment]
bug(windows): Keyman continues to not work with metro apps on some computers.

After capturing a log, it turns out that subkeys can sometimes lose their inherited permissions; unsure how this happens. The appropriate fix is to iterate through all subkeys and apply permissions accordingly.
