### PR TITLE
fix(web): optimizes, enhances caret placement within text on mobile devices

### LINKED ISSUE #5312: bug(web): performance problem clicking on textarea with large content [touch]
**Describe the bug**

I've generated a page with some lorem ipsum data in a textarea, 6360 characters altogether (i.e. not ginormous). Running in Chromium on my dev machine in mobile emulation, it took 17 seconds to focus the textarea.

`TouchAliasData.setTextCaret()` is hugely non-performant, taking 99.1% of the total time of the `touchstart` event.

image

* [Profile-20210618T110508.zip](https://github.com/keymanapp/keyman/files/6673949/Profile-20210618T110508.zip)

Looking at `setFocusWithTouch()` further, we can see the bottleneck is iterating through the entire text field rather than doing a binary search:

https://github.com/keymanapp/keyman/blob/45418a32b60709828e61de056803dad592233cdd/web/source/dom/domEventHandlers.ts#L684-L690

**To Reproduce**

I added the following script to web/testing/prediction-mtnt/index.html:

```
    <script>
      var s = '';
      for(var i = 0; i < 10; i++) {
        s += 'consequat interdum varius sit amet mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut consequat semper viverra nam libero justo laoreet sit amet cursus sit amet dictum sit amet justo donec enim diam vulputate ut pharetra sit amet aliquam id diam maecenas ultricies mi eget mauris pharetra et ultrices neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui sapien eget mi proin sed libero enim sed faucibus turpis in eu mi bibendum neque egestas congue quisque egestas diam in arcu cursus ';
      }
      document.getElementById('ta1').innerText = s;
    </script>
```

Then tested in Chrome mobile emulator, and just clicked in the textarea.

---

**KeymanWeb:**
 - OS: Windows 10 
 - Browser: Chrome 91 
 - KeymanWeb Version: 14.0.276

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #5312.

_Dramatically_ reduces the time taken to place the caret within text for `TouchAliasElement`s, the emulated text inputs KMW produces on mobile devices to facilitate use of the Web-based keyboard.  This is most notable for the first touch into such an area, which had been particularly bad due to some initialization issues for the caret-placement algorithm.

While I was at it, I also fixed up the caret placement logic; it should land where expected far, far more consistently and reliably than before.

# User Testing

This PR adds a new testing page:  `web/testing/issue5312-touch-alias-optimization`.

Said testing page (seen as "Tests performance of touch-alias elements with large amounts of text (#5312)" on the testing page index) features a text area preloaded with 6957 characters.  (Thanks, [Lorem Ipsum Generator](https://loremipsum.io/generator/?n=20&t=p).)  Without the optimizations, my testing tab in Chrome would effectively hang immediately.  (I had to force-quit Chrome a number of times for testing!)  Now... interactions feel nigh-instant!

## Tests

Use remote device emulation on Google Chrome on the testing page noted above.

- GROUP_PHONE:  Run tests on the page while emulating an iPhone SE via Chrome mobile-device emulation.
   - Note that the page will likely auto-scroll on your first touch within the testing text.  (The smaller resolution forces this.)
- GROUP_TABLET:  Run tests on the page while emulating an iPad Air (or similar tablet form-factor) using Chrome mobile-device emulation.

- TEST_INITIAL_TOUCH:  

    - Touch text in the middle of the visible paragraph, preferably toward the center vertically and horizontally.
    - The caret should land very near to the touched location, practically under the touch if possible.
    - Repeat at least 3 times in different locations; ensure it behaves as expected.
    - Finally, repeat once more slightly to the left or right of the previous repetition; ensure it behaves as expected.
    - If _any_ attempt to place a caret via touch for this test takes over 0.25 seconds, **fail** this test.

- TEST_SCROLLED_TOUCH:

    - Scroll the textbox down three paragraphs.
    - Touch text in the middle of the now-top (fourth overall) paragraph, preferably toward the center vertically and horizontally.
    - The caret should land very near to the touched location, practically under the touch if possible.
    - Repeat at least 3 times in different locations; ensure it behaves as expected.
    - Finally, repeat once more slightly to the left or right of the previous repetition; ensure it behaves as expected.
    - If _any_ attempt to place a caret via touch for this test takes over 0.25 seconds, **fail** this test.

As noted, there may be _very slight_ lag on caret-placement attempts, but only very slight.  It shouldn't ever come close to feeling like it's 'locked up' your tab in the browser.

Lone caveat:  unless I'm mistaken, it will not allow you to place the caret at the start of any line but the first.  If it does, it won't allow you to place it at the end of the previous line.  Only one of the two will be possible; that's a `TouchAliasElement` limitation.

### CODE REVIEW

File: web/source/dom/domEventHandlers.ts [hunk 1]
```diff
@@ -584,8 +584,8 @@ namespace com.keyman.dom {
     }.bind(this);
 
     // Also handles initial touch responses.
-    setFocusWithTouch(tEvent: {clientX: number, clientY: number, target?: EventTarget}) {
-      var touchX=tEvent.clientX,touchY=tEvent.clientY;
+    setFocusWithTouch(tEvent: {pageX: number, pageY: number, target?: EventTarget}) {
+      var touchX=tEvent.pageX,touchY=tEvent.pageY;
```
Comment (jahorton) [inline web/source/dom/domEventHandlers.ts:588]: The `getAbsoluteY` function operates from a `pageY` perspective.

This change is needed to properly handle caret positioning when the page is scrolled; my iPhone SE tests (see test spec) fail otherwise.

File: web/source/dom/domEventHandlers.ts [hunk 2]
```diff
@@ -641,69 +641,10 @@ namespace com.keyman.dom {
...
-            target.setTextCaret(cp);
-          }
-
-          while(dom.Utils.getAbsoluteY(caret)-dy > touchY && cp > cpMin) {
-            target.setTextCaret(--cp);
-          }
-
-          while(dom.Utils.getAbsoluteY(caret)-dy < touchY-yRow && cp < cpMax) {
-            target.setTextCaret(++cp);
-          }
```
Comment (jahorton) [inline web/source/dom/domEventHandlers.ts:669]: For comparison with the other block, re: `getAbsoluteY` motivating the `clientY` -> `pageY` change.

This block still exists; it's just been refactored into the new `performCaretSearch` function.  Along with some light refactoring to reformat and clarify the code, as it was somewhat dense in its original form.

**Comment by bharanidharanj** [comment]
### GROUP_PHONE: Run tests on the page while emulating an iPhone SE via Chrome mobile-device emulation.

* **TEST_INITIAL_TOUCH (FAILED):** Tested this as per the instructions in Chrome mobile emulator and it seems to be a little bit sluggishness on the cursor while repeating the steps. 

 

* **TEST_SCROLLED_TOUCH (FAILED):** Tested this as per the instructions in Chrome mobile emulator and it seems to be a little bit sluggishness on the cursor while repeating the steps. 

 



### GROUP_TABLET: Run tests on the page while emulating an iPad Air (or similar tablet form-factor) using Chrome mobile-device emulation.

* **TEST_INITIAL_TOUCH (FAILED):** Tested this as per the instructions in Chrome mobile emulator and it seems to be a little bit sluggishness on the cursor while repeating the steps. 
 


* **TEST_SCROLLED_TOUCH (FAILED):** Tested this as per the instructions in Chrome mobile emulator and it seems to be a little bit sluggishness on the cursor while repeating the steps.

**Review by ermshiperete — APPROVED** [review]

File: web/source/dom/domEventHandlers.ts (hunk 1 above)
Comment (jahorton) [reply web/source/dom/domEventHandlers.ts:588]: Note the second line - there's an actual functional change here.

This link may help explain the distinction:  https://stackoverflow.com/a/21452887

Comment (ermshiperete) [reply web/source/dom/domEventHandlers.ts:588]: Ahh, I fell into the TypeScript trap again :smile: The event actually contains both `client*` and `page*` fields but we were using the wrong set. Thanks!

**Comment by bharanidharanj** [comment]
> @bharanidharanj
> 
> > * and it seems to be a little bit sluggishness on the cursor while repeating the steps
> 
> Define "a little bit sluggishness". Are we talking about a quarter second, a half second, more than one second...? It'd help to know the order of magnitude.
> 
> I did note a "little bit", but on my computer (at least) it was under 0.25 seconds, hence that detail from the test instructions:
> 
> > If any attempt to place a caret via touch for this test **takes over 0.25 seconds**...
> 
> A little bit sluggish, but only about as long as it takes to blink... which I think is supposed to be about 0.1 seconds, actually. If it was the same for you, then all the tests **passed**, not **failed**.
> 
> Either way, "a little bit" is, at least, far, _far_ better than the amount of time it originally took.

@jahorton Okay, Thanks for the clarification. I will retest it (with stop clock) and will post my comment.

**Comment by bharanidharanj** [comment]
### GROUP_PHONE: Run tests on the page while emulating an iPhone SE via Chrome mobile-device emulation.

* **TEST_INITIAL_TOUCH (PASSED):** Retested this issue as per @jahorton suggestion and I noticed that the cursor appear on the text (under 0.25 seconds) in Chrome emulator. 
* **TEST_SCROLLED_TOUCH (PASSED):** Retested this issue as per @jahorton suggestion and I noticed that the cursor appear on the text (under 0.25 seconds) in Chrome emulator. 


### GROUP_TABLET: Run tests on the page while emulating an iPad Air (or similar tablet form-factor) using Chrome mobile-device emulation.

* **TEST_INITIAL_TOUCH (PASSED):** Retested this issue as per @jahorton suggestion and I noticed that the cursor appear on the text (under 0.25 seconds) in Chrome emulator. 
* **TEST_SCROLLED_TOUCH (PASSED):** Retested this issue as per @jahorton suggestion and I noticed that the cursor appear on the text (under 0.25 seconds) in Chrome emulator.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.239-beta](https://keyman.com/downloads/releases/beta/15.0.239)

File: web/source/dom/domEventHandlers.ts [hunk 3]
```diff
@@ -734,6 +675,156 @@ namespace com.keyman.dom {
...
+      } else {
+        snapOrder = function(a, b) {
+          return a > b;
+        };
+      }
+
+      // Now to binary-search the x-coordinate.
+      // Except... we... haven't modified cpMin & cpMax since their roles in the
+      // y-position search, which matters if the backing element is a TextArea.
+      // Why not?  That sounds dangerous!
```
Comment (mcdurdin) [inline web/source/dom/domEventHandlers.ts:799]: I have no idea what this comment means?!

File: web/source/dom/domEventHandlers.ts [hunk 4]
```diff
@@ -734,6 +675,156 @@ namespace com.keyman.dom {
       }
     }
 
+    private performCaretSearch(target: TouchAliasElement, scroller: HTMLElement, touchX: number, touchY: number) {
```
Comment (mcdurdin) [inline web/source/dom/domEventHandlers.ts:678]: This seems to have changed somewhat from the previous code. I have done a comparison and think I can see the differences okay.

Also, please add a code comment describing the function.

File: web/source/dom/domEventHandlers.ts [hunk 5]
```diff
@@ -734,6 +675,156 @@ namespace com.keyman.dom {
...
+      var snapOrder;
+      if(target.dir == 'rtl') {  // I would use arrow functions, but IE doesn't like 'em.
+        snapOrder = function(a, b) {
+          return a < b;
+        };
+      } else {
+        snapOrder = function(a, b) {
+          return a > b;
+        };
+      }
```
Comment (mcdurdin) [inline web/source/dom/domEventHandlers.ts:794]:
```suggestion
      const snapOrder = target.dir == 'rtl' ? (a,b) => a < b : (a,b) => a > b;
```

File: web/source/dom/domEventHandlers.ts [hunk 6]
```diff
@@ -734,6 +675,156 @@ namespace com.keyman.dom {
...
+        while(maxCpMax - minCpMax > 1) {
+          const searchPt = Math.round((maxCpMax+minCpMax)/2);
+          target.setTextCaret(searchPt);
+
+          const y=dom.Utils.getAbsoluteY(caret)-dy;  //top of caret
+          if(y > maxY) {
+            maxCpMax = searchPt-1; // We already know it's not on this row, so the maximum possible should be decreased.
+          } else {
+            minCpMax = searchPt; // Still in the same row, so the boundary can only be at or after this point.
+          }
```
Comment (mcdurdin) [inline web/source/dom/domEventHandlers.ts:772]:
```suggestion
          if(y > maxY) {
            // We already know it's not on this row, so the maximum possible should be decreased.
            maxCpMax = searchPt-1;
          } else {
            // Still in the same row, so the boundary can only be at or after this point.
            minCpMax = searchPt;
          }
```

File: web/source/dom/domEventHandlers.ts [hunk 7]
```diff
@@ -734,6 +675,156 @@ namespace com.keyman.dom {
...
+        while(maxCpMin - minCpMin > 1) {
+          const searchPt = Math.round((maxCpMin+minCpMin)/2);
+          target.setTextCaret(searchPt);
+
+          const y=dom.Utils.getAbsoluteY(caret)-dy;  //top of caret
+          if(y < minY) {
+            minCpMin = searchPt+1; // We already know it's not on this row, so the minimum possible should be increased.
+          } else {
+            maxCpMin = searchPt; // Still in the same row, so the boundary can only be at or before this point.
+          }
```
Comment (mcdurdin) [inline web/source/dom/domEventHandlers.ts:756]:
```suggestion
          if(y < minY) {
            // We already know it's not on this row, so the minimum possible should be increased.
            minCpMin = searchPt+1;
          } else {
            // Still in the same row, so the boundary can only be at or before this point.
            maxCpMin = searchPt;
          }
```

File: web/source/dom/domEventHandlers.ts [hunk 8]
```diff
@@ -734,6 +675,156 @@ namespace com.keyman.dom {
...
+
+      // Now to binary-search the x-coordinate.
+      // Except... we... haven't modified cpMin & cpMax since their roles in the
+      // y-position search, which matters if the backing element is a TextArea.
+      // Why not?  That sounds dangerous!
+      for(let iLoop=0; iLoop<16; iLoop++) {
+        // Break the binary search if our final search window is extremely small.
+        if(cpMax - cpMin <= 1) {
+          break;
+        }
```
Comment (mcdurdin) [inline web/source/dom/domEventHandlers.ts:804]:
```suggestion
        if(cpMax - cpMin <= 1) {
          // Break the binary search if our final search window is extremely small.
          break;
        }
```

File: web/source/dom/domEventHandlers.ts [hunk 9]
```diff
@@ -734,6 +675,156 @@ namespace com.keyman.dom {
...
+        // The caret itself should now lie within the target row.  The start of the row must be at or before
+        // the caret, while the end of the row must be at or after it.
+        //
+        // To properly reuse the InputHTMLElement-based x-coord search, we need the bounds to be TIGHT after
+        // this comment's containing block finishes. As in, we need [cpMin, cpMax] === [start of row, end of row].
+        //
+        // Note:  in certain scenarios, one of the bounds can be VERY far away at this point.
+        // Say, if a new touch event wants to move the caret nearby the previous location, as the
+        // bound on the opposite side may not have gotten overwritten even once so far in this call!
+        // Therefore... more binary search.
```
Comment (mcdurdin) [inline web/source/dom/domEventHandlers.ts:742]: I'm not sure I understand this comment?

File: web/source/dom/domEventHandlers.ts [hunk 10]
```diff
@@ -734,6 +675,156 @@ namespace com.keyman.dom {
...
+            // If caret's prior placement is below (after) the touch's y-pos...
+            cpMax=cp;  // new max position
+            cp=Math.round((cp+cpMin)/2); // guess the halfway mark
+          } else if(y < minY && cp < cpMax /*&& cp != cpMin*/) {
+            // If caret's prior placement is above (before) the touch's y-pos - 1 row height...
+            cpMin=cp; // new min posiiton
+            cp=Math.round((cp+cpMax)/2); // guess the halfway mark
+          } else { // the y-position lines up; cp is within the target row.
+            break;
+          }
```
Comment (mcdurdin) [inline web/source/dom/domEventHandlers.ts:712]:
```suggestion
          } else {
            // the y-position lines up; cp is within the target row.
            break;
          }
```

File: web/source/dom/domEventHandlers.ts [hunk 11]
```diff
@@ -734,6 +675,156 @@ namespace com.keyman.dom {
...
+          if(cpMax - cpMin <= 1) {
+            break;
+          }
+          const y=dom.Utils.getAbsoluteY(caret)-dy;  //top of caret
+
+          if(y > maxY && cp > cpMin /*&& cp != cpMax*/) {
+            // If caret's prior placement is below (after) the touch's y-pos...
+            cpMax=cp;  // new max position
+            cp=Math.round((cp+cpMin)/2); // guess the halfway mark
+          } else if(y < minY && cp < cpMax /*&& cp != cpMin*/) {
```
Comment (mcdurdin) [inline web/source/dom/domEventHandlers.ts:706]:
```suggestion
          if(y > maxY && cp > cpMin) {
            // If caret's prior placement is below (after) the touch's y-pos...
            cpMax=cp;  // new max position
            cp=Math.round((cp+cpMin)/2); // guess the halfway mark
          } else if(y < minY && cp < cpMax) {
```

File: web/source/dom/domEventHandlers.ts [hunk 12]
```diff
@@ -734,6 +675,156 @@ namespace com.keyman.dom {
...
+        const maxY = touchY;
+        const minY = touchY - yRow;
+
+        // Performs a binary search for a valid caret based on the y-position.
+        // cp:  the previously-set caret position.
+        for(let iLoop=0; iLoop<16; iLoop++) {
+          // Break the binary search if our final search window is extremely small.
+          if(cpMax - cpMin <= 1) {
+            break;
+          }
```
Comment (mcdurdin) [inline web/source/dom/domEventHandlers.ts:699]:
```suggestion
          if(cpMax - cpMin <= 1) {
            // Break the binary search if our final search window is extremely small.
            break;
          }
```

File: web/source/dom/touchAliasElement.ts [hunk 13]
```diff
@@ -96,6 +96,8 @@ namespace com.keyman.dom {
     __caretTimerId: number;
     __activeCaret: boolean = false;
 
+    __midCaretSearching: boolean = false;
```
Comment (mcdurdin) [inline web/source/dom/touchAliasElement.ts:99]: Perhaps `__executingCaretSearch` is better? ('mid' is a bit confusing as it has mathematical meaning as well).

File: web/source/dom/domEventHandlers.ts [hunk 14]
```diff
@@ -641,69 +641,10 @@ namespace com.keyman.dom {
...
-        while(snapOrder(dom.Utils.getAbsoluteX(caret), touchX) && cp > cpMin) {
-          target.setTextCaret(--cp);
-        }
-        while(!snapOrder(dom.Utils.getAbsoluteX(caret), touchX) && cp < cpMax) {
-          target.setTextCaret(++cp);
-        }
+        let _this = this;
+        target.executeCaretSearchFunctor(function() {
+          _this.performCaretSearch(target, scroller, touchX, touchY);
+        });
```
Comment (mcdurdin) [inline web/source/dom/domEventHandlers.ts:647]:
```suggestion
        target.executeCaretSearch(() => this.performCaretSearch(target, scroller, touchX, touchY));
```

Using arrow function means we have lexical `this`.

File: web/source/dom/touchAliasElement.ts [hunk 15]
```diff
@@ -398,6 +403,30 @@ namespace com.keyman.dom {
...
 
+    /**
+     * Facilitates higher-performance execution of caret position updates by disabling
+     * unnecessary DOM-manipulating (& layout-triggering) operations during the search.
+     * Some are still needed for the search to work, though.
+     * 
+     * Exists to encapsulate this behavior to ensure it's always, unfailingly re-enabled.
+     * @param functor A function that will search for the best caret position.
+     */
+    executeCaretSearchFunctor(functor: () => void) {
```
Comment (mcdurdin) [inline web/source/dom/touchAliasElement.ts:414]: Just `executeCaretSearch` is probably a good name? `Functor` is not really required.

I understand you need this indirection because the state variable is in touchAliasElement but the actual search is done in domEventHandlers, yes?

**Review by mcdurdin — COMMENTED** [review]
Looking good. A few comments on the comments, mostly.

File: web/source/dom/domEventHandlers.ts (hunk 3 above)
Comment (jahorton) [reply web/source/dom/domEventHandlers.ts:799]: That comment was written during my analysis of the old code; there was faulty logic when repurposing the `<input>`-oriented horizontal positioning code, which assumes `cpMin` and `cpMax` to be boundary positions on the target line.  The `<textarea>` branch never tightened the bounds.

I can probably clean that up now that the bug's removed, but it was a critical note when diagnosing the caret-misplacement aspect noted in the description:

> While I was at it, I also fixed up the caret placement logic; it should land where expected far, far more consistently and reliably than before.

File: web/source/dom/domEventHandlers.ts (hunk 5 above)
Comment (jahorton) [reply web/source/dom/domEventHandlers.ts:794]: Would it be fine if I placed this change within #6557 instead?

File: web/source/dom/touchAliasElement.ts (hunk 15 above)
Comment (jahorton) [reply web/source/dom/touchAliasElement.ts:414]: I understand you need this indirection because the state variable is in touchAliasElement but the actual search is done in domEventHandlers, yes?

> Correct.

File: web/source/dom/domEventHandlers.ts (hunk 3 above)
Comment (mcdurdin) [reply web/source/dom/domEventHandlers.ts:799]: Yes, please clean up -- comments are intended for future readers who don't know the history or context. So write them accordingly :grin:

File: web/source/dom/domEventHandlers.ts (hunk 5 above)
Comment (mcdurdin) [reply web/source/dom/domEventHandlers.ts:794]: Sure

File: web/source/dom/domEventHandlers.ts (hunk 9 above)
Comment (mcdurdin) [reply web/source/dom/domEventHandlers.ts:742]: Thanks. Can you move this commentary into the code -- it'll help future maintainers.

Comment (jahorton) [reply web/source/dom/domEventHandlers.ts:742]: Is this - taken from the followup, #6566 - sufficient?

https://github.com/keymanapp/keyman/blob/7990cdc1dd06f9c5adb8a35db4332542a2c9c3c6/web/source/dom/touchAliasElement.ts#L490-L498

That PR was how I chose to handle this aspect mentioned above:

> I'll see if I can tidy things up to make the code itself more concise and more intuitive to follow; it just turned out that there was a lot of initially-unexpected nuance that had to be handled... 

------

Other relevant altered/new comments added in that PR:

https://github.com/keymanapp/keyman/blob/7990cdc1dd06f9c5adb8a35db4332542a2c9c3c6/web/source/dom/touchAliasElement.ts#L454

https://github.com/keymanapp/keyman/blob/7990cdc1dd06f9c5adb8a35db4332542a2c9c3c6/web/source/dom/touchAliasElement.ts#L470-L475

These comments are designed to highlight that the first binary search is not focused on finding cpMin and cpMax.   It's about making guarantees on one value that will greatly help us to find cpMin and cpMax.  We just take what we can get on the way, but note that we don't guarantee we can get anything but that one value - a single index that happens to lie on the correct vertical line - and what it represents.

Comment (mcdurdin) [reply web/source/dom/domEventHandlers.ts:742]: Yep, these comments LGTM
