### PR TITLE
[Web] Unintended use of goog.DebugLoader fix

### LINKED ISSUE #1516: [Web] KeymanWeb is not loading on iOS 9.3.5 browsers due to syntax error in goog.DebugLoader
With Developer version 10.0.1202.0, I can compile a keyboard, use "Test keyboard on web" and access the keyboard from an iphone4s using Chrome. 

When I install version 11.0.1301.0 (or 11.0.1302.0), this no longer works. The iphone seems to connect to the given address, but doesn't show the keyboard being tested. (It shows EuroLatin2 or some previously tested keyboard instead.)

Uninstalling version 11 beta and reinstalling 10.0.1202.0 restores the functionality.

OS: Windows 10 1803
One keyboard under test was sil_arabic_phonetic (Keyboards PR 588)

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #1516.

Removes a dependency on the Google Closure library (separate from the compiler) that was intended to facilitate better minification, but was causing issues on some devices.  Said 'advanced-level' minification is no longer a priority and is nowhere on our roadmap at this point, so little is lost here.

Note that this fix will need a tweak when it reaches 'master' / the alpha to reflect some of its recent refactorings.

### CODE REVIEW

File: web/source/kmwapi.ts [hunk 1]
```diff
@@ -3,87 +3,56 @@
...
+}());
 
-// kmwcallback.ts
+// Keyboard callbacks
 (function() {
-  var exportKBCallback = function(miniName: string, longName: string, func:() => any) {
-    goog.exportSymbol("com.keyman.KeyboardInterface.prototype." + longName, func);
-    goog.exportSymbol("com.keyman.KeyboardInterface.prototype." + miniName, func);
-  }
+  let prototype = com.keyman.KeyboardInterface.prototype;
```
Comment (jahorton) [inline web/source/kmwapi.ts]: Note that the referenced prototype object has been moved within a new namespace on the `master` branch.

**Comment by keyman-server** [comment]
[OSK renders for Windows](https://build.palaso.org/repository/download/KeymanDesktop_TestPrRenderOnScreenKeyboards/141051:id/kvk/index.html)

File: web/source/kmwapi.ts [hunk 2]
```diff
@@ -3,87 +3,56 @@
...
-goog.exportSymbol("com.keyman.Util.prototype.saveCookie", com.keyman.Util.prototype.saveCookie);
-goog.exportSymbol("com.keyman.Util.prototype.toNumber", com.keyman.Util.prototype.toNumber);
-goog.exportSymbol("com.keyman.Util.prototype.toFloat", com.keyman.Util.prototype.toFloat);
-goog.exportSymbol("com.keyman.Util.prototype.toNzString", com.keyman.Util.prototype.nzString);
-goog.exportSymbol("com.keyman.Util.prototype.alert", com.keyman.Util.prototype.alert);
+  publishAPI('getAbsoluteX', "_GetAbsoluteX");
+  publishAPI("getAbsoluteY", "_GetAbsoluteY");
+  publishAPI("getAbsolute", "_GetAbsolute");
+  publishAPI("toNzString", "nzString");
+}());
```
Comment (darcywong00) [inline web/source/kmwapi.ts]: How come only 4 of these got updated to `publishAPI`?

Comment (jahorton) [reply web/source/kmwapi.ts]: The rest that were listed there had the same name - they were only listed to facilitate Closure's 'advanced' minification mode, which aggressively renames classes and fields.  (It'd be necessary to 'rename' them to their original name as a result.)
