### PR TITLE
[Web] Bounds-check on context deletion from keyboard rules

### LINKED ISSUE #2261: [Web] [Developer] Regression: keyboards do not behave correctly with nul statement -> full context replacement
**Describe the bug**
'nul' sequence is not output text as expected

Keyboard code

store(consonants_ra_key)  [SHIFT K_N] [SHIFT K_B] [NCAPS K_Y] 
store(consonants_ra_code) U+0CA3 U+0CAD U+0CAF 

nul U+0CB0 U+0CCD + any(consonants_ra_key) > U+0CB0 U+200D U+0CCD index(consonants_ra_code,4)

Expected output in notes app in a notes with pre existing text 'ರ್' (without quotes) and keystroke (y)
is 'ರ‍್ಯ' (without quotes)

Actual output is 'ರರ‍್ಯ'

Somehow ರ is carried over to the output with 'nul' I think.

This was not the case until recent update iOS or keyman. I don't know what's trigger this.
It was functioning correctly before.

**To Reproduce**
```
store(consonants_ra_key)  [SHIFT K_N] [SHIFT K_B] [NCAPS K_Y] 
store(consonants_ra_code) U+0CA3 U+0CAD U+0CAF 

nul U+0CB0 U+0CCD + any(consonants_ra_key) > U+0CB0 U+200D U+0CCD index(consonants_ra_code,4)
```
create a test keyboard with the above code
create a notes in iOS 13.1.2 or iOS 13.2 in the below line
ರ್
place the cursor at the end of the above text
and tap key 'y'
actual output:
ರರ‍್ಯ

Expected output:
ರ‍್ಯ

iPhone/iPad/Android (please complete the following information):

iPhone 11 pro mac
OS: iOS 13.1.2 and iOS 13.2
Keyman version 12.0.53
Target application: Notes, mail, ...
Keyboard

Keyboard name: custom

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #2261.

This adds a check to context-deletion commands, ensuring that we never attempt to delete more characters than are actually in the context - something that can break context-management within the `OutputTarget` classes due to the implementation of `.kmwString` allowing negative parameters.

I've also added a bounds-check within the `OutputTarget`s themselves; these checks are relatively easy to unit-test, so I've added something for that.

### CODE REVIEW

**Comment by MayuraVerma** [comment]
you could also use F key to type U+0CCD and R to type U+0CB0

test sequence

r f y

```
store(consonants_ra_key)  [K_N] [K_B] [K_Y] [K_F]
store(consonants_ra_code) U+0CA3 U+0CAD U+0CAF U+0CCD

nul U+0CB0 U+0CCD + any(consonants_ra_key) > U+0CB0 U+200D U+0CCD index(consonants_ra_code,4)
```

File: web/unit_tests/cases/element_interfaces.js [hunk 1]
```diff
@@ -803,6 +805,14 @@ if(typeof InterfaceTests == 'undefined') {
       pair.wrapper.deleteCharsBeforeCaret(2);
       assert.equal(pair.wrapper.getText(), Apple.mixed.substr(0, 1) + Apple.mixed.substr(4), "Error deleting context chars from a mixed SMP string");
       String.kmwEnableSupplementaryPlane(false);
+
+      String.kmwEnableSupplementaryPlane(false);
+      testObj.resetWithText(pair, Apple.normal);
+      testObj.setCaret(pair, 4);
+      pair.wrapper.deleteCharsBeforeCaret(7);
```
Comment (jahorton) [inline web/unit_tests/cases/element_interfaces.js]: The essence of the test update:  the error was happening when the `OutputTargets` were told to delete more characters than existed in context.

Text context:  `appl | e`
(`Apple.normal = "apple")

So, the test says to delete 7 characters where 4 exist.  The `e` should remain afterward, while all pre-caret text should be removed.  Before the fix, some of the pre-caret text would remain.

Comment (mcdurdin) [reply web/unit_tests/cases/element_interfaces.js]: :+1:
