### PR TITLE
fix(common/core/web): core key-processing now always returns RuleBehavior type.

### LINKED ISSUE #3695: bug(web): keyman.core.processKeyEvent has some undefined return values
Looking at the method... it looks like its return types never got fully reworked.  The intent was for the method to return either a `RuleBehavior` or `null` for any case, but there are some `undefined` and `true` cases remaining there.  I should probably address that once my current predictive tasks are done.

_Originally posted by @jahorton in https://github.com/keymanapp/keyman/pull/3664#discussion_r501502779_

### PR DESCRIPTION
**Pull request by jahorton**
`null` is still permitted, of course.

Fixes #3695.

### CODE REVIEW

File: common/core/web/input-processor/src/text/inputProcessor.ts [hunk 1]
```diff
@@ -88,10 +88,10 @@ namespace com.keyman.text {
 
         // Can the suggestion UI revert a recent suggestion?  If so, do that and swallow the backspace.
         if((keyEvent.kName == "K_BKSP" || keyEvent.Lcode == Codes.keyCodes["K_BKSP"]) && this.languageProcessor.tryRevertSuggestion()) {
-          return;
+          return new RuleBehavior();
           // Can the suggestion UI accept an existing suggestion?  If so, do that and swallow the space character.
         } else if((keyEvent.kName == "K_SPACE" || keyEvent.Lcode == Codes.keyCodes["K_SPACE"]) && this.languageProcessor.tryAcceptSuggestion('space')) {
-          return;
+          return new RuleBehavior();
```
Comment (jahorton) [inline common/core/web/input-processor/src/text/inputProcessor.ts:94]: Note:  these two lines are never actually evaluated.

These blocks are intended as a 'switch' should we ever enable _automatic_ acceptance or reversion of suggestions.  That's currently 100% disabled.

In either case, this is the best pathway forward, as it provides a "truthy" value that will be interpreted correctly by any of the method's callers.

File: common/core/web/input-processor/src/text/inputProcessor.ts [hunk 2]
```diff
@@ -56,7 +56,7 @@ namespace com.keyman.text {
      * 
      * @param       {Object}      e      The abstracted KeyEvent to use for keystroke processing
      */
-    processKeyEvent(keyEvent: KeyEvent) {
+    processKeyEvent(keyEvent: KeyEvent): RuleBehavior {
```
Comment (darcywong00) [inline common/core/web/input-processor/src/text/inputProcessor.ts:59]: chore on cleaning up the header (@returns) and the TODO block at ll. 176-182

```
      // TODO:  rework the return value to be `ruleBehavior` instead.  Functions that call this one are
      //  the ones that should worry about event handler returns, etc.  Not this one.
      //	      
      //        They should also be the ones to handle the TODOs seen earlier in this function -	
      //        once THOSE are properly relocated.  (They're too DOM-heavy to remain in web-core.)
      // Only return true (for the eventual event handler's return value) if we didn't match a rule.
```

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.245-beta](https://keyman.com/downloads/releases/beta/14.0.245)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.19-alpha](https://keyman.com/downloads/releases/alpha/15.0.19)
