### PR TITLE
fix(android): atomically updates selection with text

### LINKED ISSUE #11160: bug(android/engine): StringIndexOutOfBoundsException when end > length
Relates to #11128 which fixed StringIndexOutOfBoundsException when the selection was reversed

@mcdurdin [triggered this similar crash](https://keyman.sentry.io/issues/5022225846/events/6bd1618d50204522bb5f8c0fe15a5a43) while repeatedly holding down backspace. It's the same area of code, but where the substring end is > length

```javascript
StringIndexOutOfBoundsException
begin 0, end 12, length 11

java.lang.String in checkBoundsBeginEnd at line 4466
java.lang.String in substring at line 2517
com.keyman.engine.KMKeyboard in updateSelectionRange at line 190
com.keyman.engine.KMManager in updateSelectionRange at line 2150
com.keyman.android.SystemKeyboard in onUpdateSelection at line 132
android.inputmethodservice.InputMethodService$InputMethodSessionImpl in updateSelection at line 1414
android.inputmethodservice.IInputMethodSessionWrapper in executeMessage at line 111
com.android.internal.os.HandlerCaller$MyHandler in handleMessage at line 44
android.os.Handler in dispatchMessage at line 106
android.os.Looper in loopOnce at line 230
android.os.Looper in loop at line 319
android.app.ActivityThread in main at line 8893
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 608
com.android.internal.os.ZygoteInit in main at line 1103
```

I think we should catch this, but also add a limit
end = (end > length) ? length : end;

And if possible add some unit test

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #11160.
Supersedes #11162.

This PR prevents an error that could randomly occur during quickly-repeated text modifications that could trigger a keyboard crash in the case of repeated backspaces.

Technical details:  we had an invalid assumption that a method signalling text-selection updates and the "source of truth" for app text state were synchronous.  This was untrue, allowing an extra backspace to edit app text state while processing a previous edit's effects.  By relying on a single "source of truth", we can avoid the lack of synchronization between the two.

## User Testing

**Setup** - Install the PR build of Keyman for Android. From the Keyman app, also install basic_kbdosm (Osmonya) keyboard which outputs SMP characters.
Set Keyman as the default system keyboard

* **TEST_REVERSE** - Verifies no crash when selection is reversed (test from #11127)
1. Launch Keyman for Android
2. From "Get Started", install the Keyman keyboard basic_kbdosm (Osmanya which uses SMP characters)
3. Set Keyman as the default system keyboard
4. Launch a separate messaging app (where you can type text).
5. Use Keyman to type a mix of English (sil_eurolatin) and Osmanya (basic_kbdosm) characters.
6. In Keyman,select the basic_kbdosm keyboard
7. Double-tap to select a word in the text area (that contains a mix of English and Osmanya characters). This is the normal direction of selecting text
8. With the Keyman keyboard, press a character
9. Verify the word is replaced with the Osmanya character
10. Double-tap to select a word in the text area.
11. With the word selected, attempt to drag the end to "before" the start so the selection is "reversed"
12 Verify no crash in the Keyboard
13. With the Keyman keyboard, press a character
14. Verify the word is replaced with the Osmanya character

* **TEST_HELD_BACKSPACE** - Verifies no crash when backspace key is held down
1. Launch a separate messaging app (where you can type text)
2.  Use Keyman to type a mix of English (sil_eurolatin) and Osmanya (basic_kbdosm) characters. Type for several lines of text
3. Hold down the backspace key
4. Verify no crash in keyboard is content is deleted

### CODE REVIEW

File: android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java [hunk 1]
```diff
@@ -175,6 +175,16 @@ protected boolean updateSelectionRange(int selStart, int selEnd) {
       String rawText = icText.text.toString();
       updateText(rawText.toString());
 
+      int selStart = icText.selectionStart;
+      int selEnd = icText.selectionEnd;
```
Comment (jahorton) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java:179]: By getting the selection-state information from the same source and operation as we get the current text, we can avoid desynchronization here.

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java [hunk 2]
```diff
@@ -2137,23 +2137,18 @@ public static boolean updateText(KeyboardType kbType, String text) {
     return result;
   }
 
-  public static boolean updateSelectionRange(KeyboardType kbType, int selStart, int selEnd) {
+  public static boolean updateSelectionRange(KeyboardType kbType) {
```
Comment (darcywong00) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2140]: Noting this would be an [API change](https://help.keyman.com/developer/engine/android/17.0/KMManager/updateSelectionRange).


Do we just have  this?
```java
public static boolean updateSelectionRange(KeyboardType kbType, int selStart, int selEnd) {
  return updateSelectionRange(KeyboardType kbType);
}
```

Comment (jahorton) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2140]: Ah, didn't realize that was public API.

We could just deprecate the parameters, I guess?  The engine is now able to retrieve those values from the source.

Or would we need to find some way to make that work?  It doesn't seem to be meaningfully possible to use `KMKeyboard` without a backing `onCreateInputConnection` call, noting this code section:

https://github.com/keymanapp/keyman/blob/93dc41e2f5e1892f0de3fa821f44da8fbd144355/android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java#L472-L481

Both in-app and system keyboards have a very specific connection to their respective text sources.

As a small side question... I don't see where or when we ever _close_ the connection objects built within that block... isn't that asking for a memory leak over time?  I know Java has garbage collection, but I don't think all languages with GC have associated destructor patterns that can resolve and clean up connection stuff like this.

File: android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java [hunk 3]
```diff
@@ -187,14 +197,16 @@ protected boolean updateSelectionRange(int selStart, int selEnd) {
        */
 
       // Count the number of characters which are surrogate pairs.
+      int stringLen = rawText.length();
```
Comment (darcywong00) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java:200]: Is `stringLen` test code that can be removed?

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java (hunk 2 above)
Comment (darcywong00) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2162]: I think we go ahead and deprecate the parameters. (dunno  what to do about the potential memory leak).

At some point, we should also update `updateSelectionRange` used in SystemKeyboard for KMSample2 and the FV app

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_REVERSE (PASSED):** Tested with the attached PR build (Keyman 17.0.303-beta-test-11188) on an Android 13 mobile device and here is my observation: 1. Installed basic_kbdosm keyboard in the Keyman In-app. 2. Set Keyman as the default keyboard. 3. Opened Notes app. 4. Typed some mixture of characters using sil_eurolatin and basic_kbdosm keyboards in the text area. 5. Selected basic_kbdosm keyboard. 6. Selected a word in the text area. 7. Pressed a character from Osmanya keyboard. Verified that the word is replaced with the Osmanya character. 8. Selected another word in the text area. 9. With the word selected, I was able to drag the end to "before" the start so the selection is "reversed". Verified there is no crash occurs in the keyboard. 10. With the keyman keyboard, pressed a character and verified that the word is replaced with the Osmanya character. Seems to be working as expected.

**Comment by bharanidharanj** [comment]
# Test Results

* **TEST_HELD_BACKSPACE (FAILED):** Tested with the attached PR build (Keyman 17.0.303-beta-test-11188) on an Android 13 mobile device and here is my observation: 1. Installed basic_kbdosm keyboard in the Keyman In-app. 2. Set Keyman as the default keyboard. 3. Opened Notes app. 4. Typed a paragraph with a combination of characters using the sil_eurolatin and basic_kbdosm keyboards in the text area. 5. Held down the backspace key to delete the content and verified that no crash occurred in the keyboard.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.304-beta](https://keyman.com/downloads/releases/beta/17.0.304)

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java (hunk 2 above)
Comment (mcdurdin) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2162]: Yes, deprecation of parameters is good -- that's backwardly compatible. No changing API signatures in beta!

As for the connection objects, I see no indication at https://developer.android.com/reference/android/view/inputmethod/InputConnection or https://developer.android.com/reference/android/inputmethodservice/InputMethodService#getCurrentInputConnection() that we need to manage cleanup?

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java [hunk 4]
```diff
@@ -2137,23 +2137,40 @@ public static boolean updateText(KeyboardType kbType, String text) {
...
+   * Updates the active range for selected text.
+   * @deprecated
+   * This method no longer needs the `selStart` and `selEnd` parameters.
+   * <p>Use {@link KMManager#updateSelectionRange(KeyboardType)} instead.</p>
+   *
+   * @param kbType    A value indicating if this request is for the in-app keyboard or the system keyboard
+   * @param selStart  (deprecated) the start index for the range
+   * @param selEnd  (deprecated) the end index for the selected range
+   * @return
+   */
```
Comment (mcdurdin) [inline android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2150]: :+1:

File: android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java (hunk 2 above)
Comment (jahorton) [reply android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java:2162]: Maybe true, but isn't it a given (at least, in some programming languages) that connections need cleanup?
