### PR TITLE
fix(web): longpress validation by base key, not current location

### LINKED ISSUE #10640: bug(web): invalid subkey triggers
While investigating something else earlier today, I found a very easy input pattern that can trigger an error we've been seeing in a few Sentry reports.

1. Load up the standard "Test unminified Keymanweb" test page while on (or emulating) a mobile device.  (Chrome emulation is fine.)
2. Using the default keyboard...
3. Press any non-special key.  (For example, the `k` key.)
4. Drag up while keeping the key pressed.

Results:
- the key-preview disappears immediately
- when the touch is released, key highlighting "sticks" and is not cleared until the key with stuck highlighting is pressed again

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #10640.

The model-validation function for longpresses wasn't specified properly; it is supposed to validate based on the touch's _base_ key, not most recent key underneath the finger.  It is possible for the two to differ on lower-performance devices, as confirmed by https://github.com/keymanapp/keyman/issues/10640#issuecomment-1943080633.

## User Testing

TEST_SPACEBAR_UP_FLICK:  Using the Keyman for Android app (emulated or otherwise), ensure that no errors occur when dragging a touch rapidly from the spacebar to the banner.

1. Type a long word, such that there are no suggestions available in the banner. 
2. Starting a touch on the space bar, drag your finger from the space bar to the suggestion banner in different directions.
3. If any error notifications pop up, FAIL this test.
4. Do _not_ fail this test should the predictive-text banner highlight; this PR does not include the fix from #10695.

In essence, attempt to reproduce this user-test failure:  https://github.com/keymanapp/keyman/pull/10695#issuecomment-1941457876

### CODE REVIEW

**Comment by jahorton** [comment]
With this fix in place, the local repro I had for #10640 no longer works.  Of course, that's _my local repro_, so a user test to verify this for the setup in the original reports would be much appreciated.

File: web/src/engine/osk/src/input/gestures/specsForLayout.ts [hunk 1]
```diff
@@ -443,7 +443,7 @@ export function longpressContactModel(params: GestureParams, enabledFlicks: bool
       duration: spec.waitLength,
       expectedResult: true
     },
-    validateItem: (key: KeyElement) => !!key?.key.spec.sk,
+    validateItem: (_: KeyElement, baseKey: KeyElement) => !!baseKey?.key.spec.sk,
```
Comment (jahorton) [inline web/src/engine/osk/src/input/gestures/specsForLayout.ts:446]: https://github.com/keymanapp/keyman/blob/4755be9b869a8bf23a2da9d4671e711a5e35d432/common/web/gesture-recognizer/src/engine/headless/gestures/specs/contactModel.ts#L26-L36

The issue was obvious once I saw it.

**Review by mcdurdin — APPROVED** [review]

**Comment by jahorton** [comment]
That's a separate known issue:  #10687.

**Comment by jahorton** [comment]
Yep, the only issue noted in the test is #10687, which is a completely separate issue from what this PR addresses.  As such...

TEST_SPACEBAR_UP_FLICK:  PASSED

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.269-beta](https://keyman.com/downloads/releases/beta/17.0.269)
