### PR TITLE
Modifies the iOS app build script.

### LINKED ISSUE #403: iOS build script continues even when some targets fail to build
For example if KME-universal fails to build, the script will still continue building Keyman, assuming the framework was built successfully. This results in Keyman being built with an old copy of the framework and the script returns 0.

The script in KME-universal also proceeds even if `xcodebuild` fails.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #403 and additional CI-related issues.

----

Our most recent builds with the Swift conversion report iTunesConnect upload errors due to the inclusion of the aforementioned architectures.  It appears that they are unnecessary to include now that we're using Swift for the iOS app.

Fixes the following feedback message:

```
ERROR ITMS-90087: "Unsupported Architectures. The executable for Keyman.app/Frameworks/KeymanEngine.framework contains unsupported architectures '[x86_64, i386]'."
```

The core issue is that iTunesConnect doesn't like their inclusions, although it is necessary to keep them when attempting to run the project in simulator.

By having the app depend directly on the iOS version of the framework, we allow the app to be built by default without the additional architectures.  However, the published framework build product will be a 'universal' one that does include Simulator-oriented architectures.  See https://stackoverflow.com/a/41416964 for the requirements this places on projects that would link to just the framework.

----

For more details on CI-related changes this PR introduces, please see [this comment below](https://github.com/keymanapp/keyman/pull/402#issuecomment-344486401).

### CODE REVIEW

**Comment by gabrielwong** [comment]
In a clean build, the KME-universal target fails to build. The iphonesimulator artifacts aren't built:
```
No architectures to compile for (ARCHS=i386 x86_64, VALID_ARCHS=arm64 armv7s armv7).
```
And then subsequently:
```
fatal error: lipo: can't open input file: $KEYMAN_DIR/ios/engine/KMEI/build/Debug-iphonesimulator/KeymanEngine.framework/KeymanEngine (No such file or directory)
```

The rejected submission can be fixed by using `lipo` to remove the simulator architectures from `KeymanEngine.framework` or to build Keyman with the framework in `build/$CONFIG-iphone/KeymanEngine.framework` instead of `build/$CONFIG-universal`.

**Comment by jahorton** [comment]
Huh, thanks for checking.  I was sure I'd done a clean build... guess that's even more to look at in that regard.  :(

**Comment by gabrielwong** [comment]
Opened related #403

File: ios/build.sh [hunk 1]
```diff
@@ -143,8 +149,9 @@ if [ $BUILD_NUMBER ]; then
   /usr/libexec/Plistbuddy -c "Set CFBundleShortVersionString $BUILD_NUMBER" "$BUILD_FRAMEWORK_PATH/Info.plist"
 fi
 
-rm -r "$APP_FRAMEWORK_PATH"
-cp -R "$BUILD_FRAMEWORK_PATH" "$APP_FRAMEWORK_PATH"
+# Can we get away without this now?
+# rm -r "$APP_FRAMEWORK_PATH"
+# cp -R "$BUILD_FRAMEWORK_PATH" "$APP_FRAMEWORK_PATH"
```
Comment (jahorton) [inline ios/build.sh]: About this - the app now directly draws the ios-specific version of the engine framework from its project.

* This negates the need to copy it over 'manually' in the script.
* This prevents the .ipa file from including Simulator-oriented architectures.

When a developer goes to run the Keyman app in the Simulator, as long as they've loaded the joint workspace, Xcode will perform the necessary legwork for the operation will succeed, despite the 'official' build settings.  (It probably creates temporary build settings or something behind the scenes to facilitate this.)

File: ios/build.sh [hunk 2]
```diff
@@ -143,8 +149,9 @@ if [ $BUILD_NUMBER ]; then
   /usr/libexec/Plistbuddy -c "Set CFBundleShortVersionString $BUILD_NUMBER" "$BUILD_FRAMEWORK_PATH/Info.plist"
 fi
 
-rm -r "$APP_FRAMEWORK_PATH"
-cp -R "$BUILD_FRAMEWORK_PATH" "$APP_FRAMEWORK_PATH"
```
Comment (jahorton) [inline ios/build.sh]: About this - the app now directly draws the ios-specific version of the engine framework from its project.

* This negates the need to copy it over 'manually' in the script.
* This prevents the .ipa file from including Simulator-oriented architectures.

When a developer goes to run the Keyman app in the Simulator, as long as they've loaded the joint workspace, Xcode will perform the necessary legwork for the operation will succeed, despite the 'official' build settings.  (It probably creates temporary build settings or something behind the scenes to facilitate this.)

**Comment by jahorton** [comment]
Hmm... we're having issues with non-archive builds.  I'll need to check what's going on there.

**Comment by darcywong00** [comment]
This comment belongs on https://github.com/keymanapp/keyman/pull/401, but it's already merged.

Any additional updates to the iOS readme? The prerequisite Xcode changes from 9 to 9.1...

File: ios/build.sh [hunk 3]
```diff
@@ -135,6 +136,11 @@ echo "Building KMEI..."
 rm -r $KMEI_BUILD_PATH/$CONFIG-universal 2>/dev/null
 xcodebuild -quiet -project engine/KMEI/KeymanEngine.xcodeproj -target KME-universal -configuration $CONFIG \
   $CODE_SIGN_IDENTITY $CODE_SIGNING_REQUIRED $DEV_TEAM
+
+if [ $? -ne 0 ]; then
+  fail "KMEI build failed."
+fi
+
 assertDirExists "$BUILD_FRAMEWORK_PATH"
```
Comment (darcywong00) [inline ios/build.sh]: Now that ll.152-153 are commented out, maybe the `assertDirExists` check in l.144 can move inside the 
`if [ $BUILD_NUMBER ]; then` block.

Same for l.193

**Comment by jahorton** [comment]
OK, made some more significant changes.

Interestingly, the most recent configurations allow for potential further refactoring of the script:

* Building the app or the archive will automatically trigger the build of all required products.
    * Unfortunately, this means that each is now built independently, without reuse.
    * The 'universal' `KeymanEngine.framework` file no longer needs to be built for the App.  Though we do want it for our published products.
    * We could set up 'targets' for the build now:
        * `-engine`
        * `-app`

File: ios/build.sh [hunk 4]
```diff
@@ -135,16 +142,15 @@ echo "Building KMEI..."
 rm -r $KMEI_BUILD_PATH/$CONFIG-universal 2>/dev/null
 xcodebuild -quiet -project engine/KMEI/KeymanEngine.xcodeproj -target KME-universal -configuration $CONFIG \
```
Comment (gabrielwong) [inline ios/build.sh]: Now that KeymanEngine is built along with Keyman, maybe put the building of the universal framework behind a flag since it's not always required.

File: ios/build.sh [hunk 5]
```diff
@@ -154,29 +160,19 @@ if [ $DO_KEYMANAPP = true ]; then
...
     fi
 
-    # To dynamically set the parameters in a way xcodebuild can use them, we need to construct the entire xcodebuild call as a string first.
-    BUILD_1="xcodebuild -quiet -project keyman/Keyman/Keyman.xcodeproj ${CODE_SIGN_IDENTITY} ${CODE_SIGNING_REQUIRED} ${DEV_TEAM} -target SWKeyboard -configuration ${CONFIG}"
-    BUILD_2="xcodebuild -quiet -project keyman/Keyman/Keyman.xcodeproj ${CODE_SIGN_IDENTITY} ${CODE_SIGNING_REQUIRED} ${DEV_TEAM} -target Keyman -configuration ${CONFIG}"
-
     if [ $DO_ARCHIVE = false ]; then
-      # Performs the actual build calls.
-      $BUILD_1
+      # To dynamically set the parameters in a way xcodebuild can use them, we need to construct the entire xcodebuild call as a string first.
```
Comment (gabrielwong) [inline ios/build.sh]: This is copied from the old code but I don't think we actually need to construct the command as a string.

File: ios/build.sh [hunk 6]
```diff
@@ -20,18 +22,22 @@ display_usage ( ) {
...
+    /usr/libexec/Plistbuddy -c "Set CFBundleShortVersionString $BUILD_NUMBER" "$PRODUCT_PATH/Info.plist"
+  fi
 }
 
 KMEI_RESOURCES=engine/KMEI/KeymanEngine/resources
 KMEI_BUILD_PATH=engine/KMEI/build
 BUNDLE_PATH=$KMEI_RESOURCES/Keyman.bundle/contents/resources
-APP_FRAMEWORK_PATH=keyman/Keyman/KeymanEngine.framework
-APP_BUILD_PATH=keyman/Keyman/build/
+APP_BUILD_PATH=keyman/Keyman/build
```
Comment (gabrielwong) [inline ios/build.sh]: Since both Keyman and KeymanEngine will be built here, maybe we should move this dir to `ios/build` instead of in the Keyman project directory. And then have `KMEI_BUILD_PATH` point here as well.

File: ios/build.sh [hunk 7]
```diff
@@ -135,16 +142,15 @@ echo "Building KMEI..."
...
+if [ $? -ne 0 ]; then
+  fail "KMEI build failed."
 fi
 
-rm -r "$APP_FRAMEWORK_PATH"
-cp -R "$BUILD_FRAMEWORK_PATH" "$APP_FRAMEWORK_PATH"
+assertDirExists "$BUILD_FRAMEWORK_PATH_UNIVERSAL"
+
+set_version "$BUILD_FRAMEWORK_PATH_UNIVERSAL" "KeymanEngine"
+set_version "$BUILD_FRAMEWORK_PATH_IOS"
```
Comment (gabrielwong) [inline ios/build.sh]: General question: is this script aiming to build both universal and iphone KeymanEngine frameworks as artifacts?

File: ios/build.sh (hunk 4 above)
Comment (gabrielwong) [reply ios/build.sh]: I guess my more general observation is that the script assumed previously that KeymanEngine is a dependency of Keyman, which is no longer the case in this script (it still is in Xcode). So some of the way the script is organized could be rethought (although that could be deferred for later).

File: ios/README.md [hunk 8]
```diff
@@ -16,14 +16,13 @@ You will need to run with the command-line argument `-no-codesign` or establish
 complete the build for the final app.
 
 To run the app within a simulator after build.sh is completed,
-1. Open **keyman/Keyman/Keyman.xcodeproj** in Xcode.
-2. Run the Keyman target within Xcode.
+1. Open the main workspace in Xcode.
```
Comment (gabrielwong) [inline ios/README.md]: Open **keymanios.xcworkspace** would be more clear.

File: ios/build.sh (hunk 7 above)
Comment (jahorton) [reply ios/build.sh]: Yes, I've put in prep work so that both will be available to developers.

File: ios/build.sh (hunk 5 above)
Comment (jahorton) [reply ios/build.sh]: There's a reason it was a string in the old script.  It can be tricky - Xcode does very strange things when parsing parameters set by shell variables, and I was never able to get it right at the time.

I might put in a little time on it, but dropping the string is low priority.

File: ios/build.sh (hunk 6 above)
Comment (gabrielwong) [reply ios/build.sh]: In fact, KeymanEngine can be built through the workspace rather than the project, in the same way as Keyman, so then hopefully build intermediates will be reused.

File: ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj [hunk 9]
```diff
@@ -1202,7 +1200,7 @@
 				GCC_WARN_UNUSED_FUNCTION = YES;
 				GCC_WARN_UNUSED_VARIABLE = YES;
 				IPHONEOS_DEPLOYMENT_TARGET = 8.0;
-				ONLY_ACTIVE_ARCH = NO;
+				ONLY_ACTIVE_ARCH = YES;
```
[the remark this answers is not in the document]
Comment (jahorton) [reply ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj]: Turns out that's not entirely true for KeymanEngine.  I've gone ahead and universally set `NO` for both projects and their relevant targets.

**Comment by jahorton** [comment]
The build output directory configuration has been significantly altered; all core workspace projects now output to the same directory.  This allows intermediate products to be reused across the different builds - in particular, KeymanEngine.framework for `iphoneos`, which was being double-built in prior versions of this PR.

Resulting artifact paths - within the `build/Build/Products` directory lies the three main product directories:

* `Release-iphoneos` - this holds the actual Keyman app for device testing and the .ipa for iTunesConnect export
* `Release-iphonesimulator` - this holds the intermediate products for Simulator support, which get folded into...
* `Release-universal` - this holds the unified KeymanEngine.framework for both Simulator and on-device testing.  However, it may not be embedded in iTunesConnect submissions.  (Thanks, Apple.)

Artifacts of interest:
* `Release-iphoneos`
    * `Keyman.ipa` - the iTunesConnect upload.
    * `KeymanEngine.framework` - an iTunesConnect-compatible version of our engine's framework.
* `Release-universal`
    * `KeymanEngine.framework` - a developer-friendly version of our engine's framework, useful for testing without having to integrate the engine's source files.  Not compatible with iTunesConnect.

I'd propose renaming the latter to KeymanEngine-universal.framework on the TeamCity side and exporting both within the .zip for our published 'engine' artifact, allowing developers to choose the version that best fits their needs.

File: ios/build.sh [hunk 10]
```diff
@@ -20,28 +20,29 @@ display_usage ( ) {
...
+    /usr/libexec/Plistbuddy -c "Set CFBundleVersion $BUILD_NUMBER" "$PRODUCT_PATH/Info.plist"
+    /usr/libexec/Plistbuddy -c "Set CFBundleShortVersionString $BUILD_NUMBER" "$PRODUCT_PATH/Info.plist"
+  fi
+}
 
 do_clean ( ) {
-  rm -rf $KMEI_BUILD_PATH
-  rm -rf $APP_BUILD_PATH
+  rm -rf $BUILD_PATH
   rm -rf $APP_BUNDLE_PATH
```
Comment (gabrielwong) [inline ios/build.sh]: `$APP_BUNDLE_PATH` is unset when this is executed

File: ios/README.md [hunk 11]
```diff
@@ -16,14 +16,13 @@ You will need to run with the command-line argument `-no-codesign` or establish
 complete the build for the final app.
 
 To run the app within a simulator after build.sh is completed,
-1. Open **keyman/Keyman/Keyman.xcodeproj** in Xcode.
-2. Run the Keyman target within Xcode.
+1. Open the **keymanios.xcworkspace** in Xcode.
```
Comment (gabrielwong) [inline ios/README.md]: Sorry for the small nit: remove "the"

File: ios/build.sh [hunk 12]
```diff
@@ -66,6 +67,7 @@ while [[ $# -gt 0 ]] ; do
         -no-codesign)
             CODE_SIGN_IDENTITY="CODE_SIGN_IDENTITY="
```
Comment (gabrielwong) [inline ios/build.sh]: `CODE_SIGN_IDENTITY` and `CODE_SIGNING_REQUIRED` are unused

File: ios/build.sh [hunk 13]
```diff
@@ -84,10 +86,19 @@ while [[ $# -gt 0 ]] ; do
...
+KMW_SOURCE=../web/source
+
+# Build product paths
+APP_BUNDLE_PATH=$BUILD_PATH/${CONFIG}-iphoneos/Keyman.app
+KEYBOARD_BUNDLE_PATH=$BUILD_PATH/${CONFIG}-iphoneos/SWKeyboard.appex
+ARCHIVE_PATH=$BUILD_PATH/${CONFIG}-iphoneos/Keyman.xcarchive
+FRAMEWORK_PATH_UNIVERSAL=$BUILD_PATH/$CONFIG-universal/KeymanEngine.framework
+FRAMEWORK_PATH_IOS=$BUILD_PATH/$CONFIG-iphoneos/KeymanEngine.framework
+
+COMMON_CONFIG="-quiet -configuration $CONFIG -derivedDataPath $DERIVED_DATA"
```
Comment (gabrielwong) [inline ios/build.sh]: Can `-workspace keymanios.xcworkspace` be moved in here?

Comment (gabrielwong) [reply ios/build.sh]: Small suggestion: Maybe name this variable `XCODEFLAGS` in the Makefile style. Not too important though.

File: ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj [hunk 14]
```diff
@@ -1035,7 +1022,7 @@
 				GCC_WARN_UNUSED_FUNCTION = YES;
 				GCC_WARN_UNUSED_VARIABLE = YES;
 				IPHONEOS_DEPLOYMENT_TARGET = 8.0;
-				ONLY_ACTIVE_ARCH = YES;
+				ONLY_ACTIVE_ARCH = NO;
```
Comment (gabrielwong) [inline ios/engine/KMEI/KeymanEngine.xcodeproj/project.pbxproj]: For debug builds, if they aren't getting published I think we can get away with `ONLY_ACTIVE_ARCH=YES` to avoid doing extra work unless we plan on releasing debug version as well.

File: ios/.gitignore [hunk 15]
```diff
@@ -2,6 +2,7 @@ DerivedData
 .DS_Store
 project.xcworkspace
 xcuserdata
+build
 engine/KMEI/build
```
Comment (gabrielwong) [inline ios/.gitignore]: These old build directories and products can be removed.

File: ios/build.sh (hunk 12 above)
Comment (jahorton) [reply ios/build.sh]: Oh right, I can erase those now.  Forgot to do that when I got the unified variable working.

File: ios/.gitignore (hunk 15 above)
Comment (jahorton) [reply ios/.gitignore]: Finally.  `engine/KMEI/build` took a fair bit of work today for this goal.

**Comment by jahorton** [comment]
The resulting build product (.ipa) uploads successfully to iTunesConnect; I ran a manual upload to be sure, using the most recent failed TC build version number.
