### PR TITLE
fix(windows): handle errors starting keymanx64

### LINKED ISSUE #4988: bug(windows): keymanx64 reports 'Failed to initialise application: An unknown error occurred'
Sentry Issue: [KEYMAN-WINDOWS-3F](https://sentry.keyman.com/organizations/keyman/issues/310/?referrer=github_integration)

```
Failed to initialise application: An unknown error occurred
```

Stack:
```
  keymanx64           0x7ff631631230 CaptureStackTrace (keymansentry.cpp:96)
  keymanx64           0x7ff631631700 keyman_sentry_report_message (keymansentry.cpp:186)
  keymanx64           0x7ff631631700 Fail (keymanx64.cpp:225)
  keymanx64           0x7ff631631552 wWinMain (keymanx64.cpp:147)
  keymanx64           0x7ff631631b9d invoke_main (exe_common.inl:118)
  keymanx64           0x7ff631631b9d __scrt_common_main_seh (exe_common.inl:288)
  KERNEL32.DLL        0x7ffedd037033 BaseThreadInitThunk
  ntdll               0x7ffede482650 RtlUserThreadStart
```

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #4988.
Fixes KEYMAN-WINDOWS-3F.

This relates to #4976 and is a stop-gap until we implement that. It will reduce the number of reported errors (both to us and the end user) but does not address the core issue, which requires a more significant refactor.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

File: windows/src/engine/keymanx64/keymanx64.cpp [hunk 1]
```diff
@@ -311,6 +329,9 @@ BOOL SendPlatformComms32(WPARAM wParam, LPARAM lParam)
   HWND hwndLocalController = FindWindow(szWindowClass_x86_Wnd, NULL);
   if(hwndLocalController == NULL)
   {
+    // TODO: Perhaps we should trigger a shutdown here, because
+    // keyman.exe was not found. Right now, there is some confusion
+    // in regards to responsibility.
```
Comment (rc-swag) [inline windows/src/engine/keymanx64/keymanx64.cpp:334]:
```suggestion
    // TODO: Perhaps we should trigger a shutdown here, because
    // keyman.exe was not found. Right now, there is some confusion
    // in regards to responsibility. See #4976  
```

**Review by rc-swag — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.37-alpha](https://keyman.com/downloads/releases/alpha/15.0.37)
