### PR TITLE
fix(windows): refactor controller windows

### LINKED ISSUE #5004: chore(windows): handle case when form window is recreated in Keyman32
One question: is there any chance that Keyman32 would ever have its main window recreated? (This is possible in Delphi's form model which recreates windows in certain circumstances. See [RecreateWnd](http://docwiki.embarcadero.com/Libraries/Sydney/en/Vcl.Controls.TWinControl.RecreateWnd), [SO](https://stackoverflow.com/questions/27400973/what-external-events-trigger-tcustomform-recreatewnd)) Doing so would invalidate the handle passed into keymanx64 as a commandline parameter and cause it to work incorrectly. AFAIK, `Application.Handle` is never recreated.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/5002#issuecomment-829843630_

I have split this from the original pull request where the question was posed (by myself), because this is not a new question, so it does not need to hold up that PR. There is a chance that this is an issue that has caused instability in Keyman which we have not yet observed. I think the most appropriate thing to do is to add some monitoring into Keyman32 which reports if we get a window recreation event. Then at least we'll be aware if the issue ever arises.

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #5004.

This cleans up the use of controller windows. A single window is now given the responsibility of being the master controller, which receives messages from Keyman32 and other components around UI activation, active keyboard, etc.

The master controller is keyman.exe's `TApplication` window, which does not get destroyed and recreated, unlike the main form window.

Any thread which has responsibility for Keyman UI (keyman.exe main thread, keymanx64.exe main thread) is also registered as a controller thread. A controller thread has special handling for interactions with keyman32 around focus tracking.

Caveats:

* While keymanx64 does not have a visible window and thus probably does not need to be registered as a controller thread, it doesn't really hurt.
* Note that keymanx64 registers the 32-bit controller thread as well, which again is probably unnecessary as the 64-bit process cannot interact with the 32-bit thread.
* Keyman's main form still handles wm_keyman_control messages, as there are a number of other components which post to that window (e.g. text editor, com library visual keyboard interactions). Unlike the original problem trigger, the reference handle is not stored long-term and so there is unlikely to be a problem with main form window re-creation causing an issue in these contexts.

There are several TODO items in this which I will address in follow-ups, to reduce the scope of these changes.

I hope to cherry-pick this to stable-14.0, but will run for a while in 15.0 before doing so.

Note that this should resolve some long-standing issues with controller windows causing errors on exit of Keyman (see #2147).

### CODE REVIEW

File: windows/src/engine/keyman32/Keyman32.cpp [hunk 1]
```diff
@@ -699,8 +699,9 @@ void HandleRefresh(int code, LONG tag)
     // of keyman32/keyman64 that a refresh is coming through
     Globals::PostMasterController(wm_keyman_refresh, KR_PRE_REFRESH, 0);
 
-    // We need to tell the controller windows to refresh themselves also
-    Globals::PostControllers(wm_keyman_control, KMC_REFRESH, 0);
+    // We need to tell the controller window to refresh itself also
+    // TODO: eliminate this message (we can hop onto the above message)
```
Comment (mcdurdin) [inline windows/src/engine/keyman32/Keyman32.cpp:703]: I will leave this until a later date; it's not a real problem now; currently keyman.exe does not handle `wm_keyman_refresh` directly, only through keyman32.dll, so adding a handler for that does add complexity on the keyman.exe side of the equation.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.45-alpha](https://keyman.com/downloads/releases/alpha/15.0.45)
