### PR TITLE
change(android/app): Separate displaying welcome.htm from keyboard installation

### LINKED ISSUE #4021: bug(android): link to PDF files attached and included in the package on the welcome page at installation stage NOT_FOUND
**Describe the bug**
There are PDF files included in the keyboard package and their location is in the .\welcome folder. Hyperlinks have been used in the `welcome.htm` is not broken. It might be because of the way the package organized files and stuff included. The file path to the attached files in the `href` might have to be manipulated so that file can be viewed.

**To Reproduce**
1. Initiate keyboard installation for Khmer Angkor
2. Click on 'Install' on the bottom right corner
3. Scroll to the bottom of the "Welcome to Khmer Angkor" page 
4. Click on the link on 'here' at the end of the sentence under "Keyboard Documentations"

**Expected behavior**
The link should work? In the development processes, the link in welcome.htm is not broken. 

**Screenshots**
Screenshot_1606717834

---

  
**Android:**
 - Device: Pixel 2
 - OS: Android 10
 - Keyman version: 14.0.192
 - Target application: Keyman
 
---
 
**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.6
 - Language name: Khmer

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes #4021

Currently, linked assets in welcome.htm aren't viewable during package installation because the content is instantiated while the package resides in a temporary location (The package folder gets moved to the final path after the "INSTALL" button is clicked).

This PR separates displaying welcome.htm from the package installation process. This way, when the welcome.htm is viewed in the MainActivity handler: 
* Can reuse the HelpFile intent (already handles File Provider permissions and is used for displaying keyboard help)
* The package is in the final destination

We do lose out on the niceity of having an "OK" button to exit out of the welcome.htm page.
User will just have to hit the back button (same for closing keyboard help)

Some sample screens

khmer_angkor welcome.htm
khmer

sil_cameroon_qwerty select language during install ("INSTALL" instead of "NEXT" button)
select language

sil_cameroon_qwerty welcome.htm
welcome

sil_cameroon_qwerty - Add language to existing keyboard
add language

@MakaraSok - you can test with the PR build
Just install khmer_angkor and verify  you can access the pdf files.

Note: the `Intent.VIEW` has a quirk where it will copy the pdf file to Downloads before viewing it. 
The device will handle PDF files however it does.

### CODE REVIEW

File: android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/StepperAdapter.java [hunk 1]
```diff
@@ -107,63 +100,43 @@ public Step createStep(int position) {
...
-        }
-        else if (languageCount <= 1) {
-          // One or less language
-          count = (!hasWelcome) ? 1 : 2;
-        } else {
-          // Multiple languages
-          count = (!hasWelcome) ? 2 : 3;
-        }
-      }
+    int count = 1;
```
Comment (darcywong00) [inline android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/StepperAdapter.java:136]: `getCount()` is a lot simpler now

**Comment by mcdurdin** [comment]
Is the welcome content being displayed in a web browser? It doesn't look like it is being displayed in-app.

**Comment by darcywong00** [comment]
> Is the welcome content being displayed in a web browser? It doesn't look like it is being displayed in-app.

We've been using `Intent.ACTION_VIEW` to view welcome.htm from the keyboard help screen. The device handles the intent with a default browser.

**Comment by mcdurdin** [comment]
Okay, well that sounds like a definite candidate for improvement in a future update. But don't try and roll that improvement into this PR!

**Review by mcdurdin — APPROVED** [review]
LGTM.

**Comment by MakaraSok** [comment]
@darcywong00 This is working as expected.

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.236-beta](https://keyman.com/downloads/releases/beta/14.0.236)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.15-alpha](https://keyman.com/downloads/releases/alpha/15.0.15)

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 15.0.16-alpha](https://keyman.com/downloads/releases/alpha/15.0.16)
