### PR TITLE
fix(common/models): prevents preemptive tokenization of potential contractions

### LINKED ISSUE #6572: bug(common/models): directly pre-caret single-quotes not considered part of previous word/token
**Describe the bug**
This arises out of https://github.com/keymanapp/lexical-models/issues/143; it's only one of many components in play there.

When a single-quote appears at the end of left-context (that is, immediately pre-caret) and is passed to predictive text, the predictive text engine will not consider the (visually) same-token text as part of the suggestion, instead beginning a new suggestion at the single-quote's location.   This is _bad_ for predictions involving contractions.

This is because the default Unicode-based word-breaker will consider the single-quote its own, separate token - not part of the previous word.  According to https://unicode.org/reports/tr29/#WB_Rule_Macros, this is technically correct behavior.  In fact, it certainly makes a great deal of sense outside of end-of-context scenarios.  Further... there are end-of-context scenarios where it also makes sense - it's difficult to differentiate an actual end-of-quote from a in-progress contraction, especially without tracking complicated state information.

Note that tokenization behavior _reverts_  once a standard character is emitted after the single-quote:  one of the rules in the spec above states that word-breaking should no longer occur in such a scenario.

Unfortunately, that reversion of tokenization behavior isn't in time to fix the issue within the context-tracking system used to optimize suggestion generation; the internal engine will suffer a context desync for the rest of the word, generally basing suggestions on the part of the token after the single-quote.  This may not appear for the first post-quote character, but will show up strongly by the second.

**To Reproduce**
1. Type `we` - standard suggestions are emitted
2. Type `'` - completely unrelated suggestions to the previous context will be emitted... "almost as if" starting a new word.
    - "almost", because that's what the system thinks is happening, and no words in the MTNT model start with a `'`.
3. Type `r` - it'll seem to provide somewhat expected suggestions.
4. Type `e` - suggestions will be prefixed with `re`, not `we're`!

If interacting via debugger, directly use the word-breaking function on the following:

1.  `we` - single token
2. `we'` - two tokens:  `we`, `'`
3. `we're` - single token

**Expected behavior**
When the end of context is `we'`, predictive text should _at least consider_ the possibility that a word is still being built via typing and that `'` should not actually be tokenized separately from prior text if adjacent in position to the previous token.

It is unclear if this should be probabilistically modeled or auto-enforced.

Either way, once `we'` has been typed at the end of context, we expect to see suggestions surface that are prefixed with `we'`.

**Screenshots**

image

image

---

**KeymanWeb:**
 - OS: any (touch environment)
 - Browser: any (touch environment)
 - KeymanWeb Version: 15.0, 14.0, likely before
 - URL: `web/testing/prediction-mtnt`, use in mobile apps

**Other notes**

It does not help that this is conflated with _another_ issue noted on https://github.com/keymanapp/lexical-models/issues/143 - that the MTNT model's entries typicallly use the 'fancy' single quote, not the standard apostrophe, in contractions.  A typed `'` doesn't actually equal a `‘` - they're different code points - and there's nothing in place to map the two to each other.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #6572.
This addresses one component of https://github.com/keymanapp/lexical-models/issues/143.

While standard Unicode word-breaking is generally correct for pre-existing text, it has one notable issue for in-progress text:  if the caret immediately succeeds a `'` character adjacent to standard alphabetic characters for languages like English, there's a fair chance that the user is in the middle of typing a contraction.  A very specific and focused case, but one that definitely matters for our predictive-text engine's ability to accurately suggest contractions.

image

image

## User Testing

Use Chrome remote-device emulation with the standard `web/testing/prediction-mtnt` ("Predictive Text:  Robust Testing") test page.

TEST_WE_ARE:  Using the default keyboard on the page (where `'` has a base key), type the following.  

Make sure to be precise with your keystrokes.  If, at any point, no suggestions appear, **do not fail the test** - just start over from the first step.  There's another component of https://github.com/keymanapp/lexical-models/issues/143 that is likely interfering and may cause all predictions to be considered too unlikely for the engine to suggest.

1.  Type `we`:  standard suggestions should appear
2. Append a `'`:  suggestions should be based on `we`.
    - Ideally, you may actually get a `we‘re` suggestion at this time, though this is quite rare in practice due to the following sub-points.
    - The suggestion containing `‘`, instead of `'`, is due to a model data issue documented at https://github.com/keymanapp/lexical-models/issues/143#issuecomment-1092410514
    - Because these characters do not match, the suggestion is considered possible, but very unlikely at this time. 
3. Append a `r` - you should at least still have `we` based suggestions and may have `we‘re` as a suggestion.
4. Append an additional `e` - `we‘re` should absolutely be a suggestion at this time.
5. Move the caret before the `r` - verify that either `were` or `we‘re` shows as a suggestion.
    - It is fine if only one of the two shows up.
    - Fail if the suggestions are completely unrelated to `we`.

TEST_POST_EDIT:  Using the default keyboard on the page (where `'` has a base key), type the following.  

1.  Clear the text area completely if it is not already clear.
2.  Type `we.`:  standard new-word suggestions should appear
3. Hit backspace once, removing the `.`.  Suggestions should be based on `we`.
4. Now, type `'`.  Suggestions should still be based on `we`.

### CODE REVIEW

**Comment by bharanidharanj** [comment]
* **TEST_WE_ARE (PASSED):** Tested this PR as per the instructions in Chrome mobile emulator and it is working as expected. 

Caret appears before 'r':


Caret appears after 'r':

**Comment by darcywong00** [comment]
I recently updated en.mtnt to remove symbols and typos of contractions in keymanapp/lexical-models#164.

Do you want to update the model used in the testing page?
web/testing/prediction-mtnt/nrc.en.mtnt.model.js

File: common/models/templates/src/tokenization.ts [hunk 1]
```diff
@@ -33,6 +33,42 @@ namespace models {
...
+
+      // if the two spans are adjacent...
+      // Nested if statements in case we need another 'detokenization' condition in the future;
+      // the outer condition should hold for all such cases.
+      if(leftTailBase.end == leftTail.start) {
+        // Ideal:  if(leftTailBase is standard-char-class && leftTail is single-quote-class)
+        // But we don't have character class access here; it's all wordbreaker-function internal.
+        // Upon inspection of the wordbreaker data definitions... the single-quote-class is ONLY "'".
+        // So... we'll just be lazy for now and append the `'`.
+        if(leftTail.text == "'") {
```
Comment (darcywong00) [inline common/models/templates/src/tokenization.ts:55]: Will we need to use a new field for lexical-models to declare what character they use for contractions? (in languages that have contractions).

Or just limit to apostrophes for now?

File: common/models/templates/src/tokenization.ts [hunk 2]
```diff
@@ -33,6 +33,42 @@ namespace models {
...
     let rightSpans = wordBreaker(context.right || '') || [];
 
+    let leftTail: Span;
+    if(leftSpans.length > 0) {
+      leftTail = leftSpans[leftSpans.length - 1];
+    }
+
+    // Handle any directly-pre-caret 'detokenization' cases - where for this _specific_ context,
+    // we should not make a token division where one normally would exist otherwise.
+    // Refer to https://github.com/keymanapp/keyman/issues/6572.
```
Comment (mcdurdin) [inline common/models/templates/src/tokenization.ts:43]: 'detokenization' is not very clear to me.

```suggestion
    // For the default wordbreaker, we need to special-case handling of single quote
    // because it is treated as a word-breaking character, despite it being commonly 
    // usded within words in many Latin-script languages.
    // 
    // Handle any directly-pre-caret 'detokenization' cases - where for this _specific_ context,
    // we should not make a token division where one normally would exist otherwise.
    // See #6572.
```

File: common/models/templates/src/tokenization.ts [hunk 3]
```diff
@@ -33,6 +33,42 @@ namespace models {
...
+    if(leftSpans.length > 1 && rightSpans.length == 0) {
+      const leftTailBase = leftSpans[leftSpans.length - 2];
+
+      // if the two spans are adjacent...
+      // Nested if statements in case we need another 'detokenization' condition in the future;
+      // the outer condition should hold for all such cases.
```
Comment (mcdurdin) [inline common/models/templates/src/tokenization.ts:49]: Please drop this comment -- we shouldn't generally give code-structure justification comments like this. A future developer would still need to carefully review their code changes so at best this may cause them to take less care than they should.

```suggestion
```

File: common/models/templates/src/tokenization.ts (hunk 1 above)
Comment (mcdurdin) [reply common/models/templates/src/tokenization.ts:55]: +1 on this question.

Comment (jahorton) [reply common/models/templates/src/tokenization.ts:55]: Perhaps, if they overload punctuation marks in the same manner that English does.  Refer to https://unicode.org/reports/tr29/#WB_Rule_Macros.  That said, I just checked against https://en.wikipedia.org/wiki/Contraction_(grammar) - I don't see examples involving punctuation aside from `'`.

Note the class `Single_Quote` on the Unicode wordbreaker spec page - its usage in rules are responsible for the effects we're seeing.

While reading that page, I also remembered that in some languages `'` (more likely, a similar-looking code point) is an actual _letter_ in the language, so there's a chance an issue might arise there.

Comment (jahorton) [reply common/models/templates/src/tokenization.ts:55]: Also, I remember that at one point, @eddieantonio had suggested facilitating character class overrides or something of the sort to allow a degree of language-specific configurability for the word-breaker.  That never happened, though.  

I think his suggestion was motivated by issues we noted with its insufficiency for handling Lao and Khmer, as words for those languages break after nearly every character by default, if I recall correctly.

**Comment by jahorton** [comment]
> I recently updated en.mtnt to remove symbols and typos of contractions in [keymanapp/lexical-models#164](https://github.com/keymanapp/lexical-models/pull/164).
> 
> Do you want to update the model used in the testing page? web/testing/prediction-mtnt/nrc.en.mtnt.model.js

Done.  Didn't fix the back-tick contractions, though.  😦

**Comment by bharanidharanj** [comment]
* **TEST_POST_EDIT (PASSED):** Tested this as per the instructions and it is working as expected.

Test 1:
 

Test 2:
 

Test 3:

File: common/models/templates/src/tokenization.ts (hunk 1 above)
Comment (mcdurdin) [reply common/models/templates/src/tokenization.ts:58]: > While reading that page, I also remembered that in some languages ' (more likely, a similar-looking code point) is an actual letter in the language, so there's a chance an issue might arise there.

Apostrophe has been commonly used (but shouldn't be) for a number of languages, such as Hawaiian, for a glottal stop. The alternative preferred character is [U+02BB](https://www.fileformat.info/info/unicode/char/02bb/index.htm). A model for Hawaiian should manage that conversion. But that shouldn't impact this PR I think?

**Review by mcdurdin — APPROVED** [review]

File: common/models/templates/src/tokenization.ts (hunk 1 above)
Comment (mcdurdin) [reply common/models/templates/src/tokenization.ts:58]: > I think his suggestion was motivated by issues we noted with its insufficiency for handling Lao and Khmer, as words for those languages break after nearly every character by default, if I recall correctly.

I think that the best approach is custom wordbreakers for those languages, rather than trying to tweak the default one or making the default one adjustable.
