### PR TITLE
fix(developer/compilers): fixes dependency versioning on alpha, beta tiers

### LINKED ISSUE #4288: bug(compiler/developers): lexical model compiler improperly distributed on alpha, beta publishing tiers.
**Describe the bug**
It is impossible to `npm install @keymanapp/lexical-model-compiler@beta` (or `@alpha`) due to improperly specified dependencies for those publishing tiers.

In a screenshot:

Screen Shot 2021-01-19 at 10 10 30 AM

Note:

```
+ @keymanapp/models-types@14.0.224-beta
added 1 package from 3 contributors and audited 23 packages in 1.66s
found 0 vulnerabilities
```

But:

```
jahorton@Joshuas-MBP lexical-models % npm install @keymanapp/lexical-model-compiler@beta
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @keymanapp/models-types@^14.0.224.
```

That `npm install` failed because no `14.0.224` version was available - only `14.0.224-beta`.  Thus, when publishing to a tagged tier type, package.json should specify that same publishing tier for any in-repo dependencies.

I found this while attempting to update the https://github.com/keymanapp/lexical-models repo in order to address https://github.com/keymanapp/lexical-models/issues/108 and #4115, as the new casing feature requires a beta-version of the lexical-model compiler.

**To Reproduce**

1. `npm install @keymanapp/lexical-model-compiler@beta`
2. See error

**Expected behavior**
A healthy, error-free `npm install`.

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #4288.

This reworks the `set_npm_version` resource script function to affect _all_ packages in the repo, not just the currently-active one.  As the `@keymanapp/lexical-model-compiler` package is dependent upon the `@keymanapp/models-types` package, it's important that `beta` versions of the former link to the matching `beta` version of the latter.  Otherwise... well, #4288.

### CODE REVIEW

File: resources/shellHelperFunctions.sh [hunk 1]
```diff
@@ -257,7 +257,10 @@ set_npm_version () {
   # release of Keyman Developer -- these two versions should be in sync. Because this
   # is a large repo with multiple projects and build systems, it's better for us that
   # individual build systems don't take too much ownership of git tagging. :)
-  npm --no-git-tag-version --allow-same-version version "$version" || fail "Could not set package version to $version."
+  pushd . > /dev/null
+  cd "${KEYMAN_ROOT}"
+  npm run version "$version"  || fail "Could not set package versions to $version."
+  popd > /dev/null
```
Comment (jahorton) [inline resources/shellHelperFunctions.sh:263]: Compare against the package script being called:

https://github.com/keymanapp/keyman/blob/869899fbacb425adf1e3f24411dfdbcfbb6a0504/package.json#L8-L11

The one component that got dropped:  the `--allow-same-version` flag.  Lerna doesn't support it and will throw an error when it's present.

Fortunately, that's because it's simply not _optional_ to Lerna; it's always active.  I say this based on the following test:

Screen Shot 2021-01-19 at 11 57 44 AM

Screen Shot 2021-01-19 at 12 06 40 PM

No errors resulted from this call; `lerna` is perfectly happy if the current version is specified as the new version.

Comment (darcywong00) [reply resources/shellHelperFunctions.sh:263]: > The one component that got dropped: the `--allow-same-version` flag

I see these flags got added:
`--amend --yes --force-publish`

Just checking `--force-publish` doesn't have the potential to bite us...

Comment (jahorton) [reply resources/shellHelperFunctions.sh:263]: That's fair - I definitely had to double-check at first.

https://github.com/lerna/lerna/tree/main/commands/version#--force-publish

Comment (jahorton) [reply resources/shellHelperFunctions.sh:263]: > This will skip the lerna changed check for changed packages and forces a package that didn't have a git diff change to be updated.

File: resources/shellHelperFunctions.sh [hunk 2]
```diff
@@ -257,7 +257,10 @@ set_npm_version () {
   # release of Keyman Developer -- these two versions should be in sync. Because this
   # is a large repo with multiple projects and build systems, it's better for us that
   # individual build systems don't take too much ownership of git tagging. :)
-  npm --no-git-tag-version --allow-same-version version "$version" || fail "Could not set package version to $version."
+  pushd . > /dev/null
```
Comment (darcywong00) [inline resources/shellHelperFunctions.sh:260]: Should this fail if a version isn't passed in l.254?

`npm run version` results in

> lerna version --amend --yes --force-publish --no-git-tag-version

and waits at a prompt:
> ? Select a new version (currently 14.0.225) (Use arrow keys)
> Patch (14.0.226)
  Minor (14.1.0)
  Major (15.0.0)
  Prepatch (14.0.226-alpha.0)
  Preminor (14.1.0-alpha.0)
  Premajor (15.0.0-alpha.0)
  Custom Prerelease
  Custom Version

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 14.0.225-beta](https://keyman.com/downloads/releases/beta/14.0.225)

**Comment by mcdurdin** [comment]
This appears to have broken the Windows build. I note that the PR was merged before the last commit was built.

**Comment by mcdurdin** [comment]
I'm a little surprised that you merged this with a failing build.

File: resources/shellHelperFunctions.sh [hunk 3]
```diff
@@ -251,13 +251,20 @@ set_version ( ) {
...
+  
   local version=$1
   # We use --no-git-tag-version because our CI system controls version numbering and
   # already tags releases. We also want to have the version of this match the
   # release of Keyman Developer -- these two versions should be in sync. Because this
   # is a large repo with multiple projects and build systems, it's better for us that
   # individual build systems don't take too much ownership of git tagging. :)
-  npm --no-git-tag-version --allow-same-version version "$version" || fail "Could not set package version to $version."
+  pushd . > /dev/null
+  cd "${KEYMAN_ROOT}"
```
Comment (mcdurdin) [inline resources/shellHelperFunctions.sh:265]: These two lines could have been:

```
  pushd "${KEYMAN_ROOT}" > /dev/null
```

**Comment by jahorton** [comment]
> I note that the PR was merged before the last commit was built.
>
> I'm a little surprised that you merged this with a failing build.

Right, bad habit... I'm so used to doing Web and iOS PRs that I focus mostly on those checks.  Web / iOS-only changes can't actually affect the Windows build, after all.  Clearly should have let this one sit overnight, even though it would mean (and given the failure, still _does_ mean) delaying a fix for lexical model capitalization support.
