### PR TITLE
change(web): Selective Sentry uploads

### LINKED ISSUE #3150: bug(web): sentry upload should happen only on CI release builds
**Describe the bug**
Right now, if we do `./build.sh` in web/source, then it will finish by doing an upload to sentry.keyman.com. This should not be the default behaviour.

**Expected behavior**
For test builds, and for local builds, sourcemaps should not be uploaded to sentry.keyman.com. We should control the upload of sourcemaps with a commandline parameter that we use only in the CI process.

This should be the case even if we have our local environment setup with the required sentry variables of `$SENTRY_AUTH_TOKEN`, `$SENTRY_ORG`, `$SENTRY_URL`. We still should only be uploading sourcemaps if we deliberately specify them.

---

**KeymanWeb:**
 - OS: Windows 10
 - Browser: N/A
 - KeymanWeb Version: 14.0.79

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #3150.

Using the changes from #3162 as a base, this modifies Web's `build.sh` to do Sentry uploads only when appropriate.

### CODE REVIEW

File: web/source/build.sh [hunk 1]
```diff
@@ -297,10 +298,18 @@ while [[ $# -gt 0 ]] ; do
...
+        -upload-sentry)
+            UPLOAD_SENTRY=true
+            ;;
     esac
     shift # past argument
 done
 
+# No Sentry uploading if not a release build and not directly specified.
+if [ $UPLOAD_SENTRY = false ]; then
+    DO_NATIVE_SENTRY=false
```
Comment (mcdurdin) [inline web/source/build.sh:310]: I'm not entirely clear on the difference between $UPLOAD_SENTRY and $DO_NATIVE_SENTRY?

Comment (jahorton) [reply web/source/build.sh:310]: `$DO_NATIVE_SENTRY` already existed.

Sentry management for KMW is a bit tricky, as there are two separate versions to upload - `native` and `embedded`.  Embedded uploads are super-simple to manage - if we want an upload and we've compiled embedded-mode, upload it.

'Native' mode is less straightforward, at least in a development environment.  What behavior would we expect from `./build.sh -ui -upload-sentry`?  This command doesn't build the KeymanEngine - just the UI modules.  Alternatively, `./build.sh -web -upload-sentry` doesn't build the UI modules, but just the 'native' web engine.  What role does `-upload-sentry` have then?

The solution I opted for - so long as at least one of `-web` and `-ui` are (effectively) enabled, `$DO_NATIVE_SENTRY` is set - we've just recompiled at least part of native Web and thus have new artifacts to send to the server, even if part of them may be old.

Comment (mcdurdin) [reply web/source/build.sh:310]: Hmm. Seems to me that uploading to Sentry is really only needed for a full build. I can't see a normal scenario where we'd be wanting to upload from a partial build -- testing the Sentry integration during development work does not seem to me to be a good scenario for this pattern.

I'd prefer to simplify the logic!

Comment (jahorton) [reply web/source/build.sh:310]: > I can't see a normal scenario where we'd be wanting to upload from a partial build -- testing the Sentry integration during development work does not seem to me to be a good scenario for this pattern.

At a minimum, I'm frequently chopping off the 'embedded' part of builds during development.  When minification is at play, cutting both the 'embedded' and 'ui' portions generally chops a minute or so off of build times.

Of course, the _fastest_ builds come with the `-test` parameter in place, but that doesn't support Sentry uploads because it doesn't minify.  So, the quickest build to use for rapid-testing during development very much uses this pattern.

Comment (mcdurdin) [reply web/source/build.sh:310]: But why are you uploading your rapid test development symbols to Sentry? That's going to chew server disk space pretty quickly.

Comment (jahorton) [reply web/source/build.sh:310]: Because the Sentry integration isn't done yet.  Need I remind you:

Screen Shot 2020-05-28 at 12 21 58 PM

Screen Shot 2020-05-28 at 12 22 21 PM

Granted, once it's done, I suppose it will generally be far less of an issue.  At least, unless we start worrying about custom scopes, deliberate breadcrumbing / event generation, etc.

Comment (jahorton) [reply web/source/build.sh:310]: And, to call out myself to be fair:

Screen Shot 2020-05-28 at 12 25 48 PM

Comment (jahorton) [reply web/source/build.sh:310]: I'll clean it up a bit, but there will still be separate checks for embedded vs native.

File: web/source/build.sh [hunk 2]
```diff
@@ -297,10 +298,18 @@ while [[ $# -gt 0 ]] ; do
...
             ;;
+        -upload-sentry)
+            UPLOAD_SENTRY=true
+            ;;
     esac
     shift # past argument
 done
 
+# No Sentry uploading if not a release build and not directly specified.
+if [ $UPLOAD_SENTRY = false ]; then
```
[the remark this answers is not in the document]
Comment (jahorton) [reply web/source/build.sh]: Added a comment about how the default is set in `build-utils.sh`.

File: web/source/build.sh (hunk 1 above)
Comment (mcdurdin) [reply web/source/build.sh]: > Granted, once it's done, I suppose it will generally be far less of an issue.

Precisely. I don't want to have this kind of thing in build scripts. Design the script for the long term case. If uploading manually is a pain, just have a local script to do the sentry upload for your local testing.
