### PR TITLE
fix(developer): ensure fatal errors report message or made non-fatal

### LINKED ISSUE #10678: bug(developer): fatal exceptions in kmc may be losing error message detail
It appears that `event.exceptionVar` may be null or undefined in some cases, leading to empty error reports. We need to verify that we capture as much detail as possible, including any original error string if it is available.

Sentry Issue: [KEYMAN-DEVELOPER-1NK](https://keyman.sentry.io/issues/4932427915/?referrer=github_integration)

```
Error: 
  File "C:\BuildAgent\work\deb663ed6681f452\keyman\developer\src\common\web\utils\src\KeymanSentry.ts", line 46, in Function.reportException
    const eventId = await Sentry.captureException(e);
  File "C:\BuildAgent\work\deb663ed6681f452\keyman\developer\src\kmc\src\util\NodeCompilerCallbacks.ts", line 142, in NodeCompilerCallbacks.reportMessage
    KeymanSentry.reportException(event.exceptionVar, false);
  File "C:\BuildAgent\work\deb663ed6681f452\keyman\common\web\types\src\util\compiler-interfaces.ts", line 462, in CompilerFileCallbacks.reportMessage
    this.parent.reportMessage({filename: this.filename, ...event});
  File "C:\BuildAgent\work\deb663ed6681f452\keyman\developer\src\kmc-kmn\src\compiler\compiler.ts", line 163, in compilerMessageCallback
    this.callbacks.reportMessage(mapErrorFromKmcmplib(line, code, msg));
  File "C:\BuildAgent\work\deb663ed6681f452\keyman\developer\src\kmc-kmn\src\import\kmcmplib\wasm-host.js", line 884, in wasm_msgproc
    '{snip} ion') { console.log(`[${line}: ${msgcode}: ${UTF8ToString(text)}]`); return 0; } else { return proc(line, msgcode, UTF8ToString(text)); } }
...
(4 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #10678.

Some messages have been reduced to ERROR instead of FATAL, as they are not internal compiler errors.

Where fatal messages are raised, the message will now be reported through correctly to Sentry.

@keymanapp-test-bot skip

### CODE REVIEW

File: developer/src/common/include/kmn_compiler_errors.h [hunk 1]
```diff
@@ -41,19 +41,20 @@
...
+// maintained manually. All values must be below 0x1000 (exclusive of severity
+// code).
 #define CERR_None                                          0x00000000
 #define CERR_EndOfFile                                     0x00000001
 
 #define CERR_BadCallParams                                 0x00008002
 #define CERR_CannotAllocateMemory                          0x00008004
-#define CERR_InfileNotExist                                0x00008005
-#define CERR_CannotCreateOutfile                           0x00008006
+#define CERR_InfileNotExist                                0x00004005   // #10678: reduced from fatal to error in 17.0
```
Comment (jahorton) [inline developer/src/common/include/kmn_compiler_errors.h:54]: I assume these existed for the old compiler and were fatal then?  I feel like the comment doesn't make sense otherwise.

File: developer/src/common/include/kmn_compiler_errors.h [hunk 2]
```diff
@@ -41,19 +41,20 @@
...
+// #define CERR_CannotCreateOutfile                           0x00004006   // #10678: reduced from fatal to error in 17.0, but unused
```
Comment (jahorton) [inline developer/src/common/include/kmn_compiler_errors.h:55]: Wait, so this... can't happen anymore?  Why is it now unused?  

Surely a destination file could, in theory, be in a read-only open mode; how do we now avoid that being a problem?

File: developer/src/common/include/kmn_compiler_errors.h (hunk 1 above)
Comment (mcdurdin) [reply developer/src/common/include/kmn_compiler_errors.h:54]: They aborted the build but they are not a 'fatal' error in terms of how we define a fatal error now, which is an internal compiler error.

File: developer/src/common/include/kmn_compiler_errors.h (hunk 2 above)
Comment (mcdurdin) [reply developer/src/common/include/kmn_compiler_errors.h:55]: File writing is no longer the responsibility of this component.

**Review by jahorton — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.273-beta](https://keyman.com/downloads/releases/beta/17.0.273)
