### PR TITLE
fix(web): missing null-guard for hardware keystrokes without active Keyman keyboard

### LINKED ISSUE #10739: bug(web): missing null-guard for hardware keystrokes
Sentry Issue: [KEYMANWEB-COM-1A3](https://keyman.sentry.io/issues/4979388869/?referrer=github_integration)

```
TypeError: Cannot read properties of null (reading 'keyboard')
  at get HardwareEventKeyboard.activeKeyboard (https://s.keyman.com/kmw/engine/17.0.268/src/web/src/app/browser/src/hardwareEventKeyboard.ts:260:47)
  at this._KeyPress (https://s.keyman.com/kmw/engine/17.0.268/src/web/src/app/browser/src/hardwareEventKeyboard.ts:296:24)
```

### PR DESCRIPTION
**Pull request by jahorton**
Fixes #10739.

Without this null-guard, hardware keystrokes throw errors if when Keyman keyboard is selected.  Fortunately... I think the error should be invisible to end users, even then - as that's a code path that explicitly relies on the browser defaults to produce output.  Still, it'll clog up our Sentry logs if we don't fix it.

@keymanapp-test-bot skip

### CODE REVIEW

File: web/src/app/browser/src/hardwareEventKeyboard.ts [hunk 1]
```diff
@@ -257,7 +257,7 @@ export default class HardwareEventKeyboard extends HardKeyboard {
   }
 
   get activeKeyboard(): Keyboard {
-    return this.contextManager.activeKeyboard.keyboard;
+    return this.contextManager.activeKeyboard?.keyboard;
```
Comment (mcdurdin) [inline web/src/app/browser/src/hardwareEventKeyboard.ts:260]: I see `keyPress` calls this function:

https://github.com/keymanapp/keyman/blob/a404c20ddf12ffbe8dcd36bd51ad6343ec37cd9d/web/src/app/browser/src/hardwareEventKeyboard.ts#L409

It may be that it never gets there because of other preconditions but it should probably also be fixed.

The name of the function is a bit confusing -- in some places `activeKeyboard` refers to a type `{keyboard: Keyboard, metadata: KeyboardStub}` from contextManager.ts, and in other places, it refers to a `Keyboard` type. Something for another day though.

**Review by mcdurdin — APPROVED** [review]

**Comment by keyman-server** [comment]
Changes in this pull request will be available for download in [Keyman version 17.0.271-beta](https://keyman.com/downloads/releases/beta/17.0.271)
